### ISSUE TITLE
Page rendering issue after importing YAML Article content page

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#1002]
After Creating and Importing YAML content for one of the articles on my local Drupal Environment, page has rendering issues and displays the code first time I open the page (see screenshot).

However, it disappears when refreshing the page.
![screen shot 2019-03-08 at 1 01 38 pm](https://user-images.githubusercontent.com/46539699/54047001-e4772900-41a3-11e9-800d-e3b8b3814ff5.png)

**Comment by BrendanBeltzNIH** [comment]
Heya, can you give the file/branch this error occurred on/with? There's not quite enough to go on here. Not sure if it's a code issue or an issue with the content.yml file.

**Comment by popkhadzeg** [comment]
it was due to formatting issue in YAML file. Brendan was able to fix it. closing this ticket.
