### ISSUE TITLE
Citation links inside PDQ documents need cleanup/treatment

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1003]
## Description 

Citation Links inside PDQ content types are being rendered as plain links side by side. For example 

> Invasive breast cancer will be present but undetected  by mammography (false negative) in 6% to 46% of exams.   False-negative exams are more likely for mucinous and lobular types of cancer, for rapidly growing <em>interval</em> tumors which become detectable between regular mammograms and in dense breasts, which are common in younger women.<a href="#cit/section_1.12">12</a><a href="#cit/section_1.13">13</a><a href="#cit/section_1.14">14</a></li>

The citations should render as follows:

> Invasive breast cancer will be present but undetected  by mammography (false negative) in 6% to 46% of exams.   False-negative exams are more likely for mucinous and lobular types of cancer, for rapidly growing <em>interval</em> tumors which become detectable between regular mammograms and in dense breasts, which are common in younger women. [<a href="#section_1.12">12</a>,<a href="#section_1.13">13</a>,<a href="#section_1.14">14</a></li>]

**Comment by bkline** [comment]
@blairlearn and @venglisch - before I go digging, I wanted to give the two of you a chance to jump in and say "ah, I know what's happening here," as I'm using the same filters as are used in the current system (CDR -> GK -> Percussion), as far as I know, and I was under the impression that this was an aspect of the system which would be (with a couple of known exceptions), carried forward as is.

**Comment by venglisch** [comment]
Ah, I know what's happening here :-) - maybe not exactly but here are some of my thoughts:
a) The CDR is not formatting the citations.  Isn't that done in the GK code that would take, for instance, the citations [1, 2, 3, 4] and converts it into [1-4]?
b) When I last looked at this the href="#cit/section_1.13" was created by the JS called "routie".  But it has been a while and I'm not certain routie is still used.  That's a piece of JS running on the WCMS side of things.

I think we started using routie when we were displaying the summaries on one page section by section.

But to be honest I don't really know much of where this is coming from.

**Comment by blairlearn** [comment]
There is some particularly ancient cruft in GateKeeper's "extract" code which consolidates consecutive reference elements before the XSLT transforms.

Some of it's in the `ConsolidateReferences()` method at 

https://github.com/NCIOCPL/wcms-gatekeeper/blob/master/Core/DataAccess/CDR/SummaryExtractor.cs#L994-L1026

but the guts of are it in `FormatReferences()` at
https://github.com/NCIOCPL/wcms-gatekeeper/blob/master/Core/DataAccess/CDR/SummaryExtractor.cs#L801-L867

Not directly related to this issue, there's also some post-rendering tom-foolery (for section titles and spaces between consecutive `GlossaryTermRefs`.  That can be found in
https://github.com/NCIOCPL/wcms-gatekeeper/blob/master/Core/ContentRendering/SummaryRenderer.cs

**Comment by bryanpizzillo** [comment]
@alifr When you said:
>Also the links should have the href attribute updated to remove the cit/ text from the link. href="#cit/section_1.13" => href="#section_1.13"

Are you saying it is that way now, or in the future you would like it changed?  In looking at www.cancer.gov now, `#cit` is still part of the ID in the content. So removing it would have to be a change on the current site, and we may not have time for that.

**Comment by alifr** [comment]
ok, I'll have to port over the JavaScript that intercepts the click event and redirects the citation anchors properly.

**Comment by bkline** [comment]
@alifr So this part ...

> Also the links should have the href attribute updated to remove the cit/ text from the link.
href="#cit/section_1.13" => href="#section_1.13"

... can be removed from the requirements above for this ticket? Or am I mis-interpreting the implications of your previous comment?
