### ISSUE TITLE
CgovCoreTest should not install the profile

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#101]
Currently there is a method, testCgovSiteProfile, which tests user permissions.  These user permissions are installed as part of the cgov_core module, which *at this point in time* is a *dependent* module of the cgov_site profile.

The module tests should not reference the profile.

Additionally, the name of the test method testCgovSiteProfile is confusing with the testCgovSiteProfile method in the profile tests.

**Comment by bgnih** [comment]
The `testCgovSiteProfile` was testing only permissions on the administrator account installed as part of the `cgov_site` install profile, which seems appropriate.   However, to make the test more useful I have changed it from a permissions-based test to an `administrator` role-based test (which is defined in the install profile).

I have renamed the Core test method properly and removed the test for the `administrator` role which is created in the `cgov_site` profile.

**Comment by bgnih** [comment]
Any idea why my phpunit Functional test passes when in `/docroot/modules/custom/cgov_core/tests/src/Functional/CgovCoreTest.php` but fails when in `/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Functional/CgovCoreTest.php` with the error
```
1) Drupal\Tests\cgov_core\Functional\CgovCoreTest::testCgovCore
Drupal\Core\Extension\MissingDependencyException: Unable to install modules cgov_core due to missing modules cgov_core.
```
Oddly, the Kernel and Unit tests work fine from both locations.

**Comment by bgnih** [comment]
Moved test to Kernel and it works fine.   No answer on why it didn't work as a Functional test.
