### ISSUE TITLE
composer cgov-init produces error messages

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#102]
Following the steps in the Docker README

1. Follow the instructions under "1. Initial Setup of Your Machine"
2. Follow the instructions under "2. Initial setup of your project"
3. On step 2.4, the output from `composer cgov-init` contains errors.

```
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/learnb/git/digiplat/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
```

**Comment by blairlearn** [comment]
This is almost certainly caused by `cgov-init` looking for files that are installed after you run `composer install`. The difficulty is that some of what cgov-init does is required in order for 'docker-compose up' to run, so moving this to a later point in the instructions won't work.

Should this actually be two separate steps?  Or perhaps cgov-init should launch the Docker stack as one of its steps?

**Comment by bkline** [comment]
A known bug, I think.

https://github.com/acquia/blt/issues/3148

(I posted something about this a couple of weeks ago in Slack.)

**Comment by blairlearn** [comment]
Actually, this may be a reappearance of an earlier problem with the `composer.json` file.  The same messages show up on the `blt setup` step.

**Comment by bryanpizzillo** [comment]
I just ran this and it does not have any output like this. So closing this.
