### ISSUE TITLE
Anchors in PDQ are blocked by the headers

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1020]
When I jump to the section headings when clicking on anchors doesn't work correctly and jumps me far into the text of that section.

http://ncigovcdode36.prod.acquia-sites.com/about-cancer/treatment/cam/hp/cartilage-pdq#_146_toc

**Comment by alifr** [comment]
Now that the remaining JavaScript has been ported over, this issue should be fixed.
