### ISSUE TITLE
We should use npm ci for faster & consistent package installs

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#103]
`npm ci` will use the package-lock.json file to install the specific versions in the package-lock. This will allow for more repeatable builds, which should also be faster.  Package-lock.json needs to be committed and the frontend-reqs command hook in `blt.yml` needs to be updated.

**Comment by bryanpnih** [comment]
package-lock.json was checked in. It only showed up as a tracked changed because install was changing versions. So this issue only requires the change to `blt.yml`.
