### ISSUE TITLE
Use Simple wysiwyg for Article Body Section Heading

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1037]
On Articles, the Heading field for automated On This Page should use the [simple wysiwyg](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields-WYSIWYG). 

The simple wysiwyg alllows for bold and italics. We have instances where OTP headings include italicized terms, for example:
https://www.cancer.gov/about-cancer/causes-prevention/risk/infectious-agents/h-pylori-fact-sheet
https://www.cancer.gov/about-cancer/causes-prevention/risk/infectious-agents

**Comment by bryanpizzillo** [comment]
@adriancofie did a fix on this, but unfortunately, the OTP links contain raw HTML elements in the display.
