### ISSUE TITLE
Attach Syndication Fields to PDQ DIS

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1046]
Attached syndicate and syndicate keywords to [PDQ Drug Info Summaries](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-PDQ-Drug-Info-Summary#common-fields)

Syndicate should default to UNCHECKED.

**Comment by bryanpizzillo** [comment]
DIS has never been syndicated and therefore this should be marked out of scope. (And maybe never to be done...)

**Comment by VictoriaSunNIH** [comment]
Closing this until we one day get a request for syndicating since this is not currently syndicated content
