### ISSUE TITLE
Implement promo URLs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1049]
Fields:
Promo URL Name
Promo URL Path

Need to figure out how the promo URL would be associated with a piece of content (right now its through slots in Percussion).

Only Advanced Editors would be able to create this content type.

**Comment by amydugan** [comment]
we should put all promo URLs in the redirect map for Phase 1, so this can go in the backlog for future enhancements

**Comment by VictoriaSunNIH** [comment]
Closing this out as no longer needed - we can set up redirects in drupal
