### ISSUE TITLE
Implement Publish Preview

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1070]
@bkline - please feel free to detail out what this entails.

**Comment by bkline** [comment]
First thing to nail down is my assumption that the scope of this ticket just covers publish preview for the PDQ drug and information summaries (I'm basing that assumption on the request above directed to me to identify "what this entails," as I wouldn't be the right source for identifying the requirements for a more general capability to preview any content item stored in the Drupal CMS). If that assumption is correct, I'll narrow the scope in the ticket's title, and I'll propose something along these lines:

* At install time each of the `pdq_cancer_information_summary` and `pdq_drug_information_summary` modules creates a `node` of its type which has placeholders for the fields, including 0 for the `cdr_id` field, and is permanently kept in the `draft` state. The other placeholders are chosen to be unique strings which would not appear elsewhere in the retrieved page for the node.
* Optionally, we can add hook implementations which prevent saving a CIS or DIS node with `cdr_id` of 0 in a published state, if we believe we need to prevent an administrator from doing that.
* When a request for publish preview of a CIS or DIS document is requested in the CDR, the document is
  1. run through the "vendor" export filters
  2. run through the routine for transforming the result of the previous step into the fields needed for the Drupal CMS
  3. post-processed to adjust any relative links for embedded content (e.g., images) which assume the page is being served up by the Drupal CMS
  4. inserted into the template document retrieved from the Drupal CMS by the PDQ user (which has the permission to retrieve draft content)
  5. displayed to the user

**Comment by bryanpizzillo** [comment]
## Response to Assumption
* Publish Preview is a PDQ concept. 
  * The scope of this story is only for the Drupal Publish Preview functionality of Drupal content loaded by the CDR. (CIS & DIS)
  * NOTE: I chose my words carefully. I checked with Volker, there are items that can be previewed today, which are not CIS or DIS documents. 
     * So there will probably need to be some sort of logic to figure out if the pub preview request goes to Gatekeeper or Drupal

## Response to Approach
This sounds like a reasonable approach. 

## Questions:
1. How will you manage concurrency? 
    * Drupal will not know when two requests for previewing are occurring, each will be a separate process.
       * https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Lock%21LockBackendInterface.php/group/lock/8.7.x
    * In hindsight, this is probably an issue for the normal loader too...
2. We may need to find a way to hide this content from dashboards, which would be annoying. 
    * This may be a global node view alter?
3. III and IV confuse me. What would be clearer, or at least what I am interpreting the process to be is:
    1. Load the document into Drupal.
    2. Ask Drupal to preview the content
    3. Manipulate the response to change out paths to images
         * Recommend writing down what may actually need to be manipulated. Here are two data points:
            * Percussion's preview did not have the CGov wrapper, nor did it have the JS or CSS.
            * Previewing Drupal, should actually yield a fully viewable document with the exception of image paths to non-existent images. (Because the images may not have been published by the CDR yet...)
    4. Display to the user
    5. Profit.

**Comment by bkline** [comment]
> How will you manage concurrency?

I don't think there are any concurrency issues. Two simultaneous requests for preview of a given content type will get the same C-clamp wrapped around the placeholder document fields. According to Blair (https://github.com/NCIOCPL/cgov-digital-platform/wiki/GateKeeper-Dependencies):

> The Drupal system only needs to be responsible for supplying a basic "C-clamp" with the necessary CSS and JavaScript.

which avoids having to store the previewed content in the CMS at all.

> ... find a way to hide ...

Your idea of a view alter sounds good.

> III and IV confuse me ...

See Blair's comment quoted above. His idea (which he has promoted for a good while, starting well before we knew we were replacing Percussion) was to have the CMS supply just the C clamp and have the CDR use the same filters for generating the HTML as are used in publishing to the CMS (whether Percussion or Drupal) to create what we will insert into the C-clamp (with some post-processing to tweak links, etc.).

> Profit

Of course! 😄

**Comment by bryanpizzillo** [comment]
@bkline Is this done?

**Comment by bkline** [comment]
@VictoriaSunNIH is reviewing feedback from Robin and will close this ticket when those issues have been addressed (_e.g._, fixed, documented, or shunted off to separate tickets).

**Comment by VictoriaSunNIH** [comment]
I opened a separate ticket #1475 for the front end issues reported by Robin.  Closing this ticket as completed.
