### ISSUE TITLE
Resolve Drug and Cancer Info Summary Percussion dependencies

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1073]
The same discussion points apply to both of these. 

The dueling approaches are

* Alter the CDR publish process to not contact GateKeeper for these document types.
* Continue to send the data and modify GateKeeper to throw it away.

# Tradeoffs
## Change the CDR

Altering the CDR to not contact GateKeeper for these document types involves modifying the subsystem which handles those communications. This subsystem needs to remain in place until GateKeeper is eventually retired, at which point the subsystem can be excised en masse.

**Specific challenges include:**

Tracking which documents were sent to GateKeeper.
Handling dependency groups where some documents are sent and some aren't (e.g. Dictionary term and pronunciation).

## Change GateKeeper

Similarly, changing GateKeeper also requires changes to a system which will needs to continue running. This also gets complicated if the results of sending to GateKeeper vs. Drupal are different.

**Specific challenges include:**

Changing the reporting to always report success.
Reconciling bookkeeping when GateKeeper succeeds and Drupal fails (or the other way around).

Related to #494.

## Related Resources

* [Changes required to remove GateKeeper's Percussion dependencies](/NCIOCPL/wcms-gatekeeper/wiki/Remove-Percussion-Dependency)

**Comment by VictoriaSunNIH** [comment]
1. What are the pre-prod steps to get the media files up (so we can have it done before we have the cutover)?
2. Timing of gatekeeper going live (before or similar timing).

@blairlearn - Need to figure out the go-live steps.

**Comment by blairlearn** [comment]
High-level deployment steps are in: https://collaborate.nci.nih.gov/display/OCECTBWIKI/CGov+Digital+Platform+Launch
