### ISSUE TITLE
Metadata: Implementation of og:image meta tag

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#1091]
## Description 

This ticket captures the implementation of the logic and functionality for the 
og:image meta tag

* og:image
  * Add an og:image tag to [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#promotional-image)
     * If no promotional Image has been provided, the system will add og:image tag to [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#lead-image)

**Comment by amydugan** [comment]
Done as part of #197
