### ISSUE TITLE
Image URL Page should return 404

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1093]
We should return a 404.  /media/ID should not be a real URL.

When you click on an image link from the media dashboard (like you do to preview content), it displays multiple versions of the image. It looks bad and should be fixed.
<img width="600" alt="Screen Shot 2019-03-18 at 3 51 11 PM" src="https://user-images.githubusercontent.com/29731392/54559184-cecce500-4995-11e9-8b55-eade5c8c56c4.png">
<img width="600" alt="Screen Shot 2019-03-18 at 3 51 02 PM" src="https://user-images.githubusercontent.com/29731392/54559185-cecce500-4995-11e9-906d-52b10c5244ca.png">

**Comment by BrendanBeltzNIH** [comment]
Closing, because covered by #1668
