### ISSUE TITLE
Bug: Glossifier first occurrence highlighting incorrect with previously glossified terms.

### ISSUE THREAD

**Issue by BrendanBeltzNIH** [NCIOCPL/cgov-digital-platform#1100]
Previously glossified terms are excepted from the glossification service during a second pass, which means that the glossification service can incorrectly assign the first_occurence value to the second occurrence of a term that was already glossified, which means that now the previously glossified first occurrence of a term, though once again rendered as a selectable checkbox, will oddly not have the highlighting a first occurrence should have and instead the second occurrence will be highlighted.
It would require a pass to find all the terms rendered as checkboxes and test for first/second occurrence instead of just relying on the api’s determinations (which do not account for previously glossified terms).

![image](https://user-images.githubusercontent.com/34315527/54637967-4bc49100-4a60-11e9-9828-acd8ee1382e9.png)

**Comment by blairlearn** [comment]
This no longer occurs.
