### ISSUE TITLE
SPIKE: Investigate RAW HTML Content Block/CDN approach for Forms

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#1105]
Investigate: Migrate form as RAW HTML content block. Post the form submission to existing Cancer.gov via Akamai.

**Comment by blairlearn** [comment]
Thinking about how to approach this:

* Configure Akamai to front the INT environment as though it was www.cancer.gov.
* Create a mock contact form on www-int, set to post to www.cancer.gov.
  * Need to either define a new recipient that will go to the TEST email address, or use an existing one which goes to the OCPL team.
* Modify the local `hosts` file to alias www.cancer.gov to Akamai.
