### ISSUE TITLE
BUG: 'List Description' field should be unlimited size.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1109]
The [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#list-description) common field is supposed to have an unlimited size.  It is currently set to a maximum of 320 characters.

Do the thing.

*  In `cgov_core`, edit `field.storage.node.field_list_description.yml1
   * Set type to `string_long`.
   * Remove `settings.max_length`
*  In `cgov_media`, edit `field.storage.node.field_list_description.yml1
   * Set type to `string_long`.
   * Remove `settings.max_length`

**Comment by VictoriaSunNIH** [comment]
Closing this - I've referenced this issue in a number of places for each content type that has the wrong size.
