### ISSUE TITLE
Implement Display Modes for Content Types

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#113]
Implement the display modes:
* Feature Card
* Thumbnail Card
* [Teaser (List Item)](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields-WYSIWYG#full)

- [x] Implement display modes for Article content type
- [ ] Implement display modes for Blog content Type

**Comment by lburack** [comment]
List templates attached.
Note: A list needs a system title, but the list title and list description are not required fields. Also, lists pull from the list description field.
[20150129 List Requirements.pdf](https://github.com/NCIOCPL/cgov-digital-platform/files/2654552/20150129.List.Requirements.pdf)
