### ISSUE TITLE
Feature card description should NOT be multi-row

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1132]
Multi-row presentation of the feature card description field should be changed to be a single row.

We only use multi-row when the field allows unlimited characters.

Feature card description should have a max of 255 characters.

**Comment by blairlearn** [comment]
This impacts `cgov_infographic` and `cgov_video`.

It will be fixed in the `feature/infographic` branch.

**Comment by VictoriaSunNIH** [comment]
Closing this out - it is referenced in a number of content type tickets.
