### ISSUE TITLE
Mini Landing and Home/Landing Page - Fix Field Order

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1144]
On the Mini Landing Page, the pretty URL field should be right after the Site Section. Then the Page Title and Short Title fields. 

This also applies to the Home/Landing Page content type, so feel free to update there as well!

**Comment by VictoriaSunNIH** [comment]
CLosing this - I'll fold this into a larger ticket for updates to the mini and homepage content types
