### ISSUE TITLE
Fix Display for Two Item Feature Card

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1146]
I added a two item feature card to my mini landing page, It doesn't look like the live site. Here are the issues:

- each feature card should have a line around it with a dropshadow 
- title for each item should be our hyperlink color, not black/gray
- on hover, the title should not be underlined
- sizing of the cards is off — the cards are larger on the live site with less margin in between them
- feature card description styling is not correct — it's a larger font size and displaying as our hyperlink color on the ODE (designers can provide specs if needed)
- there should be more space between the bottom of the two item feature card row and the next chunk of content

Here's an example page from the live site of two item feature cards: https://www.cancer.gov/about-nci/organization/ccct

Here's what I'm seeing on the ODE: http://ncigovcdode63.prod.acquia-sites.com/about-cancer/coping/day-to-day
<img width="917" alt="Screen Shot 2019-03-22 at 11 01 17 AM" src="https://user-images.githubusercontent.com/29731392/54832056-db04bb00-4c91-11e9-9e61-6a8e039ad7ff.png">

**Comment by alifr** [comment]
Basically, feature card styles are missing for mini-landing page. We had a number of different feature card style blocks on the old site that made different blocks of markup look the same (blog-feature, cthp-feature, primary-feature). Now I think the markup has become the same and the styles have broken as a result.

**Comment by alifr** [comment]
testable on the /about-nci/organization/ccct page and /pets page
