### ISSUE TITLE
List Display Issues on Mini Landing Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1147]
List Items are not displaying correctly on the mini landing page. I've attached screenshots of what I'm seeing on the ODE vs what's on the live site. Issues include:

- list item title is displaying as an h3, but it's too small. According to inspect element, It's 16px on the ODE but should be 20px (might not be a bad idea to verify with designers)
- for lists with images, thumbnail images are displaying way too small (see attached screenshots for comparison)
- Image should have same hover style as the list item title. Right now, when you hover on the image, you see the hand display, but the title of the item should also turn cranberry. 
- font size for compact list items is too large. According to inspect element, it's 20px on the ODE but it should be 18px

**Screenshot from ODE with wee list with images and slightly too large compact list font size** 
note: created #1146 for issues with the two item feature card display
http://ncigovcdode63.prod.acquia-sites.com/about-cancer/coping/day-to-day
![ODE-mini-landing-lists](https://user-images.githubusercontent.com/29731392/54831027-f79ff380-4c8f-11e9-925b-038b0f2d3d8b.png)

**Live Site - list with images as they should display**
https://www.cancer.gov/about-nci/organization/ccct
https://www.cancer.gov/about-cancer/coping
<img width="1335" alt="live-site-list-with-images" src="https://user-images.githubusercontent.com/29731392/54831040-fe2e6b00-4c8f-11e9-882f-1ac48c51f70d.png">

**Live Site - compact list as it should display**
https://www.cancer.gov/about-cancer/coping/questions
![live-site-compact-list](https://user-images.githubusercontent.com/29731392/54831043-0090c500-4c90-11e9-965f-9e68bde92a0a.png)

**Comment by arcepaul** [comment]
@lburack 
When styling I based it on the excerpt from
https://github.com/NCIOCPL/cgov-digital-platform/wiki/UX-Lists:
```Right Style, Wrong Markup - https://www.cancer.gov/grants-training (see the list at the bottom)
Right Markup, Wrong Style - https://www.cancer.gov/about-cancer/managing-care```

So the list styling is exactly the same for landing pages and non-landing pages. I can make the changes and will just need to confirm what it needs to be.

**Comment by lburack** [comment]
Hi @arcepaul  - I think the Grants and Training page was a bad example, at least in isolation. Home and landing pages do not have left navigation so the container is much wider. The home and landing page list is full width. Could the list be shrinking down to fit the smaller container on the mini landing page with left nav?

**Comment by arcepaul** [comment]
@lburack 
Yes, that's exactly what's happening.  I can target the adjustment on non-landing pages.
