### ISSUE TITLE
Blog post displays debug information

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1148]
All blog posts display debug text with a link to the parent blog series.
```
=== Debug === 
content.field_blog_series: Cancer Currents Blog
```

**Comment by alifr** [comment]
This will be removed when the blog PR makes it's way through to develop: https://github.com/NCIOCPL/cgov-digital-platform/pull/1220

**Comment by amydugan** [comment]
This was fixed by the PR.
