### ISSUE TITLE
Related Resources editing label not translated

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1157]
When [editing a press release in _Spanish_](http://www.devbox/espanol/node/103/edit?destination=/admin/content%3Ftitle%3D%26type%3Dcgov_press_release%26status%3DAll%26langcode%3DAll), the label for related resources says "RELATED RESOURCES."  It should probably say something similar to "RECURSOS RELACIONADOS".

See: http://www.devbox/espanol/node/103/edit?destination=/admin/content%3Ftitle%3D%26type%3Dcgov_press_release%26status%3DAll%26langcode%3DAll

(Or perhaps the real bug is that the rest of the editing UI for Spanish content should be in English?)

**Comment by amydugan** [comment]
This is working on Dev now.
