### ISSUE TITLE
Make the glossification window smaller

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1167]
The glossification window itself is rather large.  It forces me to have to scroll my page window, to the be able to continue to scroll in my glossification window, which is rather annoying.  This also means that when i close out of the glossification window, my underlying page is no longer scrolled to the body section, but somewhere else.  Any way we can make this window smaller or fit on the page, so we only need to scroll within the glossification window?

**Comment by lburack** [comment]
@VictoriaSunNIH - I'm able to scroll only within the glossification window. The form behind the glossification window does not move unless I move my mouse and scroll outside of the glossification window. I

**Comment by BrendanBeltzNIH** [comment]
Yeah, the glossification window size is easily tweakable. I didn't think 600px minimum was too big considering your laptop is 1080 across. But it's all good. Tomorrow, we can tweak styles to your heart's content.
