### ISSUE TITLE
Public Reuse Text Styling Bugs

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1174]
The public reuse text at the bottom of the page doesn't have the correct margin between the text and the horizontal rule. Also, there looks to be more line height on the live site.

Live site on top; screenshot from dev on the bottom:

![Screen Shot 2019-03-24 at 4 33 31 PM](https://user-images.githubusercontent.com/29731392/54885459-9b390180-4e52-11e9-8f0b-2c0d49b78917.png)

**Comment by BrendanBeltzNIH** [comment]
Is this still an issue? I found the display to be matching in several places. Where is it not showing correctly exactly? 
![image](https://user-images.githubusercontent.com/34315527/56072583-cc786380-5d66-11e9-90df-2dba67e59898.png)

**Comment by lburack** [comment]
on English, the period is missing at the very end, before the end quote 
> ... using the original product's title; e.g., "Feelings and Cancer was originally published by the National Cancer Institute."

on Spanish
- the alignment is not correct 
- the quoted text at the end only included the page title. the rest of the line is missing
> ... y enlace al producto original del NCI usando el título original del producto; por ejemplo, “Los sentimientos y el cáncer publicada originalmente por el Instituto Nacional del Cáncer.”

This is from dev:
![Screen Shot 2019-04-14 at 7 22 22 PM](https://user-images.githubusercontent.com/29731392/56100761-a8de2600-5eea-11e9-9ba7-c543f8313e12.png)
