### ISSUE TITLE
Create Embedded Infographic Promotion

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1182]
As a content editor I would like to promote infographics on other pages on the web site within the WYSIWYG content.

## Editing Rules
When an infographic is embedded in the WYSIWYG, there should be multiple options available to display the infographic.  

There should be a choice of:
* Small
* Medium:
* Large

The alignment choice of None, Left, Center or Right should already exist with entity embed.

## Display

The easiest way to explain this is the infographic promotion markup is the Promotional Image rendered with a View Infographic link to the Infographic URL and the addition of a longdesc attribute to the rendered image. (Which means that this is annoyingly hard story for what it is)

### Current Rendering code with explanation of Vars as they could come from Drupal
**VARS**
* `$class` is set to:
   * Small: `image-right-small` OR `image-left-small`
   * Medium: `image-right-medium` OR `image-left-medium`
   * Large: `image-center`
* `$longDesc` - the URL to the long description if the `field_accessible_version` field of the infographic is not empty.  (`Url::fromRoute('cgov_infographic.long_description', ['media' => $entity->id()])->toString()` can get you the URL) 
* `$imgSrc` - the url of the Promotional Image's `field_media_image` field, rendered using the `cgov_article` Image style.
   * Look at how the display modes for `Image Display: Article *` display views are configured. 
* `$alt` - the alt text of the Promotional Image
* `$srcInfographic` - The URL of the infographic
* `$expandText`: The link text
   * English: `View Infographic`
   * Spanish `Ver infografía`
* `$locale` - `en-us` or `es-us`
* `$caption` - The caption of the Promotional Image
```
      <figure class="$class centered-set">
        <!-- figure begin -->
        <div class="media-highlight centered-element">
          <!-- infographic div begin -->
          #if($longDesc)
            <img src="$imgSrc" alt="$alt" longdesc="/$longdescLink"><!--Comment--></img>
          #else
            <img src="$imgSrc" alt="$alt"><!--Comment--></img>
          #end
          <a href="$srcInfographic"  class="infographic-view-full no-resize" target="_blank">$expandText</a>##
          <span class="media-label media-infographic $locale"> </span>
        </div>##<!-- infographic div end --> 
        #if($caption != "")##
          <figcaption>
            <div class="caption-container">$caption</div>
          </figcaption>
        #end##
      </figure>## <!-- figure end -->
```

Example URL:
https://www.cancer.gov/about-cancer/causes-prevention/genetics

**Comment by BrendanBeltzNIH** [comment]
```          <span class="media-label media-infographic $locale"> </span>
```
Was deemed to be unnecessary and removed from the reqs per Bryan. imageMacros.articleImage was reused for this with a small tweak to allow for custom link text.
