### ISSUE TITLE
PDQ CIS: Issues/Bugs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1183]
For http://ncigovcdode36.prod.acquia-sites.com/about-cancer/treatment/cam/hp/cartilage-pdq
1. Terms should not be capitalized in the modal windows
2. On mobile, On This Page appears above the accordion (and should not appear.  @alifr noted this was an issue already in his ticket #739 )
3. Too much space between the h2 and content (compared to prod)
4. Too much space above h3s under About This Summary
5. Page options are not appearing on PDQ summaries

On http://ncigovcdode36.prod.acquia-sites.com/types/breast/hp/breast-treatment-pdq
1. Inconsistency in spacing between  ‘a’ tag elements when ‘a’ elements are indented under In This Section
2. In Situ in Ductal Carcinoma In Situ appears within em tag (under On This Page and when it appears as h2
3. More space has been introduced above the h3s (Anatomy, Protective Factors etc.)
4. The content in the table footer is appearing bold (font weight 700)
5. The font weight of PDQ list title under Treatment Option Overview for Early/Localized/Operable Breast Cancer appears as 400 whereas in Prod it is 700 italic.
6. More space above h4 (Axillary lymph node management)
7. More space between h2 and In This Section 

Generally on IE:
1..	IE fonts looks different
2.	Modals are not appearing on IE - Getting 404 page on clicking modal
3.	Citation jump links do not work in IE

**Comment by alifr** [comment]
A lot of these issues are related to the styles in the Drupal project being behind the live site. Porting over the latest styles has been put off while other Drupal theme tickets were in flight. I will talk with the team about moving those in now, but it should probably be part of another ticket.

**Comment by alifr** [comment]
I've updated the PDQ styles on this build since the PDQ content type is not available in master. This fixes most issues with the exceptions below:

- _Terms should not be capitalized in the modal windows_ - modals are a global module and already available in develop, so changes for modals will be part of another branch when I port over the rest of the FEQ styles
- _In Situ in Ductal Carcinoma In Situ appears within em tags as plain text_ - this is a back-end issue where html tags are not being parsed.

**Comment by VictoriaSunNIH** [comment]
@bkline - can you take a look at the issue where the em tags are appearing as plain text?  As Frank indicated this is a backend issue where html tags are not being parsed, not sure who would look at this.  Thanks!

@alifr - a few more issues that we're still noticing:
1.  Page Options are not appearing on any summaries
2. Glossification is not working in IE (they go to a page not found) -- will this be resolved in the global module update for modals?
3. Citation jump links don't work in IE (they don't go anywhere...)
4. In This Section is not appearing on http://ncigovcdode36.prod.acquia-sites.com/types/breast/hp/breast-ovarian-genetics-pdq (but does appear on prod)
5. Public Use text is not appearing on any summaries

**Comment by bkline** [comment]
> ... can you take a look at the issue where the em tags are appearing as plain text?

Looks like there was more to it than

> Section Title: The title for this section. Load from /Summary/SummarySection/Title

(from https://github.com/NCIOCPL/cgov-digital-platform/issues/165).

I will modify the loader so that we strip markup from the contents of that element.

**Comment by bkline** [comment]
I have pushed fresh YAML content to the feature branch (and thence to its ODE). The markup should be gone from the summary section titles.

**Comment by alifr** [comment]
Latest build is ready on http://ncigovcdode36.prod.acquia-sites.com/
