### ISSUE TITLE
Restrict text formats for existing Content Types and update YML

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#1192]
## Description 

Restrict Text Formats and update necessary YML content to match.

**Restrict Text Formats**

cgov_blog
   * field_about_blog --- steamlined

cgov_core
   * field_body --- full_html

pdq_cancer_information_summary
   * field_pdq_section_html --- raw_html

**Update YML**
Article
Blog Series
PDQ Cancer Information Summary

Note: THe following modules with WYSIWYG  do not require any updates.
* cgov_cancer_center
* cgov_event
* cgov_biography 
* cgov_press_release

**Comment by BrendanBeltzNIH** [comment]
This would appear to be 2/3 done in making the config changes (only cgov_blog has not had it's field restricted) and the approach is already clearly defined in other .module files using hook_field_widget_form_alter().

As for whether the yaml files were also updated... But either way, the LOE on this is low and the approach seems clearcut.
