### ISSUE TITLE
Align Percussion content type specific styles to Drupal Content Types Styles

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#1197]
Inventory was completed in #1339.

**Comment by alifr** [comment]
Relates to #473. See spreadsheet posted there by Mark for complete list of page specific styles in CSS.

**Comment by alifr** [comment]
This ticket can not be finished until PDQ, Blogs and CTHP Content Types are added to develop.

**Comment by VictoriaSunNIH** [comment]
@alifr - What does this affect on the front end?  Please list out what is being targeted so that we can do the IA review properly.

PDQ, Blogs and CTHP are all on develop now.

**Comment by amydugan** [comment]
Stories to be broken out by 4/30.

**Comment by alifr** [comment]
Tasks for this ticket:
- There were variations between home page and landing page accordions in `accordion.scss`, but now they share the same template so these styles can be consolidated and scoped to homelanding entry point scss
- scope margin on `.ncilandingpage p, .ncihome p:not(.site-name):not(.site-link)` elements in `homelanding.scss` to the homelanding entry point scss
- scope margin on `.ncilandingpage h1` in `homelanding.scss` to homelanding entry point scss

- ensure layout styles seen on `#nvcgSlSectionNav` in `blogs.scss` is now handled by twig templates.
- scope blogs post specific padding on `.contentzone` in `blog.scss` to blogPost entry point scss
- medium sized images are smaller on blogs. Adjust `figure.image-right-medium` in `blogs.scss` to be properly scoped to the blogPost entry point scss file

**Comment by alifr** [comment]
Acceptance Criteria:

1. ensure margins around accordions at mobile breakpoints on the home and landing pages are correct and flush to the edge of the browser without clipping the +/- expanding icon
2. ensure margins on `<p>` elements in home and landing pages are just `.5em` on the top and bottom
3. ensure the top margin on `<h1>` elements on home and landing pages remains `.58em` even on mobile breakpoints
4. ensure layout looks correct on BlogPosts
  1. ensure that `<div id="nvcgSlSectionNav">` does not exist in the markup
  2. ensure that if `<div id="nvcgSlListBlogRTRail">` is removed from the page `<div id="main">` spans the full width of the page
  3. ensure that main content (`<div id="main">`) has a left padding of `1.6em`
5.

**Comment by alifr** [comment]
Tasks have been broken out into the following tickets:

Home/Landing: https://github.com/NCIOCPL/cgov-digital-platform/issues/1608
CTHP: https://github.com/NCIOCPL/cgov-digital-platform/issues/1606
Blogs: https://github.com/NCIOCPL/cgov-digital-platform/issues/1607
PDQ: https://github.com/NCIOCPL/cgov-digital-platform/issues/1609
Analytics: https://github.com/NCIOCPL/cgov-digital-platform/issues/1597
App Module (CTS): https://github.com/NCIOCPL/cgov-digital-platform/issues/1598

Some other code cleanup that can occur:
- remove `if(location.pathname.match('espanol'))` block from `HomePage.js`. No longer needed with Drupal platform
- remove `.cgvpressrelease hr.ps-divider` from `mainContent.scss`. These `<hr>` elements are no longer present on press releases. These `<hr/>` elements no longer appear on press release pages.

**Comment by amydugan** [comment]
Closing - stories were broken out. (See above)
