### ISSUE TITLE
Translation is not working for Cgov Image and Contextual Image

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1200]
I translated my English image to Spanish. When I add the image (both cgov image and contextual image) to my Spanish page, I see my Spanish caption, but on the front-end, the caption is not getting pulled in. Instead the English caption displays.

**Comment by bryanpizzillo** [comment]
I was able to do it ok. So let's talk about what happened exactly.

**Comment by bryanpizzillo** [comment]
@lburack Have you hit this again, or can we close this as "unable to reproduce?"

**Comment by lburack** [comment]
Just tested this again on dev and closing it as unable to reproduce.
