### ISSUE TITLE
External link checker should recognize our Acquia sites

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#1223]
The code which determines whether the visual indication that a link leaves our sites should be displayed is not recognizing absolute URLs which point to our Acquia-hosted instances (_e.g._, the ODEs) as our own sites.

**Comment by BrendanBeltzNIH** [comment]
Line 26 of cgov_common/src/libraries/exitDisclaimer/exitDisclaimer.js is where this logic is performed. It's not pretty and it's very simple. Anything that is on a different domain gets flagged.

Would the production site ever point to an ODE though?

**Comment by bkline** [comment]
Dunno, but publish preview might.

**Comment by bkline** [comment]
<img width="1042" alt="Screen Shot 2019-03-26 at 10 17 47 AM" src="https://user-images.githubusercontent.com/1634628/55004449-a7d36c00-4fb0-11e9-8ff3-a845ad5d105a.png">

**Comment by bkline** [comment]
<img width="1065" alt="Screen Shot 2019-03-26 at 10 20 20 AM" src="https://user-images.githubusercontent.com/1634628/55004539-cafe1b80-4fb0-11e9-8572-0668f9075728.png">

**Comment by BrendanBeltzNIH** [comment]
@bryanpizzillo We can certainly add in new conditional tests to reflect ACE and ACSF urls as well if you want for a pretty low LOE solution. Any thoughts?

**Comment by bryanpizzillo** [comment]
Sounds good. acquia-sites.com and acsitefactory.com I think are the two domains to ignore.

**Comment by lburack** [comment]
This has been fixed on http://ncigovcdode117.prod.acquia-sites.com/news-events/cancer-currents-blog/2019/rr-blog-post

The first link is to the dev ODE and the second is an external link to Google
![Screen Shot 2019-05-02 at 12 12 14 PM](https://user-images.githubusercontent.com/29731392/57089931-9a0db680-6cd3-11e9-9f55-e12b81c61fdb.png)
