### ISSUE TITLE
Unpublished Related Internal Link Produces Error

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1231]
When creating new content I tried to attach an internal link to a page that had not yet been published. Trying to save the content produced an error:

This entity (node: 581) cannot be referenced.

**Comment by BrendanBeltzNIH** [comment]
I was able to do this without issue while logged in as an admin. My assumption is that it's a question of bypass node access permissions being set differently for editors? 

That being said, there is an outstanding issue regarding this bug, https://www.drupal.org/project/linkit/issues/2903220, that is active.

**Comment by bryanpizzillo** [comment]
The core issue with entity reference is https://www.drupal.org/project/drupal/issues/2845144.

By default you do not want to enable bypass node access for all editors as that allows people to skip editorial checks.

**Comment by bryanpizzillo** [comment]
Making new EntityReferenceSelectionHandlers for Node and Media. They will allow unpublished nodes,  then I am modifying all the fields (field.field) that reference the `default:node` or `default:media` selection handlers.

Additionally, for fun, I am also removing the required constraint for the bundle selection for our handler. We do not usually constain bundles and it requires hand editing the exported config to set the target_bundles to be NULL.

**Comment by bryanpizzillo** [comment]
@lburack and @VictoriaSunNIH - There is one danger in all of this. You can still publish the page with none of the referenced entities being published. That needs to be trained.

**Comment by lburack** [comment]
Aaack, @bryanpizzillo. That's very scary! @claireblaustein we need to put warnings all over the training document and tell Cameron and Ally to repeat it constantly during training.

**Comment by bryanpizzillo** [comment]
Also you can add an unpublished link, publish the parent, and if you are logged in as an editor, you will see the link in the related resources. Anonymous (not logged in users) will *not* see the link though. Just pointing this out as it *could* be confusing.
