### ISSUE TITLE
Move "apply" button on popups

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1232]
Can the apply button be moved to the right, so it's more clearly connected to the search/filters on popups?

Want to avoid confusion thinking that "apply" is the go button, instead of "select" 

![screen_shot_2019-03-24_at_2 36 29_pm](https://user-images.githubusercontent.com/39384914/55032638-bd17bd00-4fe7-11e9-8138-e9a7ea802c1e.png)

**Comment by BrendanBeltzNIH** [comment]
Quite frankly it should be renamed 'filter' or 'search'.
