### ISSUE TITLE
Streamlined and Full WYSIWYGs are not displaying bullets

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1238]
For both an editor and admin, streamlined and full WYSIWYGs are not displaying bullets in the field. On the front-end of the page, I see the bullets, but it's odd that bullets do not display in the field. Numbers from an ordered list do show, however.

<img width="1029" alt="wysiwyg-no-bullets" src="https://user-images.githubusercontent.com/29731392/55079921-88e9de00-5073-11e9-8f79-79771e653580.png">

**Comment by amydugan** [comment]
Moving this up to Medium priority, as it was part of feedback from both Anne M. and Becky C.
