### ISSUE TITLE
BUGS on Blog Series and Posts

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1241]
### Archive 
- Right rail Archive should be closed by default, with a clickable plus sign users can click to open it 
- Individual archive pages should not display the blog series banner 
- For the title of archive pages, append the month and year (or year only) before the blog series name. Examples:
  - [March 2019 - Cancer Currents Blog](https://www.cancer.gov/news-events/cancer-currents-blog/archive?filter[year]=2019&filter[month]=3)
  - [2018 - RAS Dialogue](https://www.cancer.gov/research/key-initiatives/ras/ras-central/blog/archive?filter[year]=2018)

### Pagers
**Blog Series**
- not displaying correctly, but the wording is good.
- < Older Posts should be left aligned and on the same line, just aligned on the right should be the New Posts > link. The Page number should not display. See screenshot of ODE vs Live Site below.
- For Spanish, the language is correct. Just the same alignment issues as English.

![blog-pager](https://user-images.githubusercontent.com/29731392/55120018-9b433680-50ca-11e9-8b34-51d24e066e37.jpg)

**Blog Posts**
- wording of pager is incorrect. 
   - On individual posts, it should be < Older Post and Newer Post > (not previous and next)
   - In Spanish, this should be < Artículo anterior (older) and Artículo siguiente > (newer). Right now on the ODE, Spanish blog posts are displaying the same pager as English.

### Additional Issues
- One more Spanish Translation bug — Dates in Spanish should have the day before the month (6 de noviembre de 2018 NOT noviembre 6, 2018).
- If Author field is left blank, do not display anything. The byline should just read "March 27, 2019," Right now it looks like "by NCI Staff" is automatically being added if the Author field is blank.
  - Same goes for Spanish. Looks like "por NCI Staff" is automatically being added if Author field is blank on Spanish posts. This isn't even accurate — it's "por Equipo del NCI"
- If the Feedburner URL field is not populated, do not display "Subscribe" link at the top of the blog series

### Recommended Content
I opened #1258 for front-end look and feel on Recommended Content

**Comment by alifr** [comment]
> See screenshot of ODE vs Live Site below.

Not seeing the mentioned screen shot.

**Comment by daquinohd** [comment]
- [ ] Close right rail by default (Frank)
- [ ] Remove banner on archive pages (Dion)
- [ ] Month and year on archive page title (Dion)
- [ ] Fix Blog Series pager styling (Frank)
- [ ] Fix Blog Post pager wording (Dion)
- [ ] Style recommended content (Frank)
- [ ] Spanish date string order (Dion, existing bug)
- [ ] Hide 'by, ' if no author (Dion)
- [ ] Hide 'Subscribe' link if no Feedburner URL (Dion)
