### ISSUE TITLE
Collapse Right Rail Archive block by default

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#1242]
Per #1241
Right rail Archive should be closed by default, with a clickable plus sign users can click to open it

**Comment by alifr** [comment]
jQuery as `$` is undefined when the user is logged in. If logged out then everything works as expected. ???

This is probably because jQuery is in `no-conflict` mode when logged-in.

**Comment by amydugan** [comment]
This was closed with one of the blog fix PRs.
