### ISSUE TITLE
Attach editorial workflow to Home and Landing page content type

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#125]

**Comment by bkline** [comment]
My proposed approach for this ticket is to implement an install hook in `cgov_core.install` which invoked the `attachContentTypeToWorkflow()` method described in issue #127. How does that sound to you, @bgnih?

**Comment by bgnih** [comment]
Sounds reasonable to me.

**Comment by bkline** [comment]
@bgnih - We said we would create the install hook in `cgov_core.install` but now I'm wondering how this will work, exactly. I see that the landing page has its own module (`cgov_home_landing`) and that module's `info.yml` file names `cgov_core` as a dependency. Presumably I can't attach a content type which doesn't exist yet to the workflow, but if that content type depends on the installation of the `cgov_core` module before it can install itself, I seem to be caught in _Dependency Hell_. Even moving the install hook to the `cgov_home_landing` module doesn't seem like a guaranteed solution, as there, too, I would be trying to attach something (the content type) which is still in the process of being created. Any words of wisdom?
