### ISSUE TITLE
SPIKE: Investigate usage of HHS Syndication Code

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#1252]
Currently HHS Syndication code does not meet Drupal coding standards and would fail our linter. Investigate what we can do with this code to enable syndication through the HHS storefront. 

@bkline - This is the HHS syndication investigation Bryan discussed with you. It is possible my description isn't 100% accurate; feel free to update.

**Comment by bkline** [comment]
We cannot use this code, which is broken in too many ways to count. We will, however, cherry-pick some of the techniques to be used in our own implementation.
