### ISSUE TITLE
Blog Post - Recommended Content Front-End Display/Look & Feel

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1258]
- For Recommended Content, each item should be a card and styled as such (see screenshot below comparing live site vs ODE)
- the 4x3 image crop should display 
- the entire card should be clickable, linking to the page/URL that has been added. On hover, the image should dim.
- if an override card title is added, only that title should display. On the ODE I am seeing both the card title of the page and the override title I've entered. Only my override title should show. 
- card title is an h3, but it should be a smaller size and hyperlinked. See screenshot or look [look at this blog post on the live site](https://www.cancer.gov/news-events/cancer-currents-blog/2019/lymphadenectomy-advanced-ovarian-cancer-survival) for reference

![Recommended-Content-Blog-Comparison](https://user-images.githubusercontent.com/29731392/55173142-8bbb0080-5151-11e9-88ae-96bb7a5baa76.jpg)

**Comment by VictoriaSunNIH** [comment]
This was fixed as part of blogs.  Closing this ticket.
