### ISSUE TITLE
Unable to search content when adding in apostrophes

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1283]
I was trying to search for the “Nature’s Bounty” blog post.

I can type nature and find it, but when I type “Nature’s”, I get no content available.

It seems that the "Title Search" in the Content Overview cannot match apostrophes

FWIW:  http://ncigovcdode69.prod.acquia-sites.com is where I was testing

**Comment by blairlearn** [comment]
This appears to have been fixed in a recent Drupal update.  You can even search for apostrophe by itself.
