### ISSUE TITLE
 Display the date on Article

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#129]
This story is to displaythe [common date field](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#content-dates)s to [Article ](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article)content type. The date field creation and storage was addressed in  #110.

**User Story:**
* As a visitor, I would like to see the date a content author has set on an article on cancer.gov

**Acceptance Criteria:**
   * Date display rules - when more than one date is selected in Date Display Mode - use the most recent of the dates selected. Display the label of that date, and that date. If only one is selected, show the label and the date. If nothing is selected, no date displays.

**Comment by BrendanBeltzNIH** [comment]
Approach: There are multiple ways to handle the logic requirements here. A preprocess function, a custom twig extension, a twig macro, and finally an inline twig conditional. For a first pass, we will use a reusable twig macro.

**Comment by bgnih** [comment]
Twig functions `{{ newestDate(date1, date2, date3) }}` and Computed field `$field_display_date` may also be options (just to be thorough)

**Comment by BrendanBeltzNIH** [comment]
Twig functions are custom twig extensions FYI. The computed field would be nice.

**Comment by BrendanBeltzNIH** [comment]
Current approach:

1. Create a preprocessor to pass in a variable to the twig templates for the effective Date Display Mode
   This is where article can remove all but one display
   Press release would keep them all
   etc.
1. Make a twig template to render dates that could render all of the dates.
   The order of the dates to be displayed is Posted, Updated, Reviewed
   The output will be along the lines of:
```<div class="document-dates horizontal">
            <ul class="clearfix">
                <li><strong>Posted:</strong> September
 27, 2013</li>            
                            <li><strong>Updated:</strong> August
 12, 2014</li>            
            </ul>
 </div>```
1. Then call that twig from within the article template
We can reuse the date display template across the site

**Comment by bgnih** [comment]
If there will be any requirement to be able to sort by this field in Views, then a computed field (database storage) will likely be best option.   Otherwise, anything works.  ;-)

**Comment by bryanpizzillo** [comment]
@bgnih You make a valid point, but I think that should be implemented as a "field_sort_date" computed field. I.E. Use these rules to calculate what the sort date is...

(One type of content even used to have a totally separate Sort Date field. It may be going away though, but it illustrates the point)
