### ISSUE TITLE
We should allow periods in pretty URL

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1304]
PDF files on cancer.gov have a pretty URL ending with .pdf 

We need to make sure the pretty URL field allows the period character. 

The largest application for this would be in Files, but may also occur in other pretty URLs.  

In testing #1284, I had a pretty URL that ended in .pdf. When I tried to save, I got this error: The Pretty URL field only accepts letters, numbers, and dashes.  The site section browser does appear when I try to add a file

**Comment by amydugan** [comment]
For all pretty URLs (for all content types).
