### ISSUE TITLE
Blog Series Bugs (Round 2)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1306]
Blog Series

* 'About Blog’ is not displaying
* Unable to see right rail in preview (when content is in editing) – can only see changes once it’s been published
* Page Options is missing 
* Site Sections has the incorrect browser.  It’s not browsing for site sections (as it should), but is actually pulling up the content browser. This is a blocker – cannot create new series.
* When setting a site section, we should only show the “Remove” button (not both remove and edit)

* On the content type, switch Group Archive By  with Number of Years to Archive by so Group Archive By comes last 
* Update the following 
  * Meta Description
    * Tooltip: Succinct description of the page content. Most important information should be in the first 150 characters. [Displays in: Site-wide and external search results and when List Description is blank. SEO best practice – do not exceed 320 characters]
    * Ensure field is limited to 320 characters.
  * List Description
    * Tooltip: 2-3 sentence description of the page content. Can be left blank if list description will be the same as the meta description. [Displays on: Home/Landing, Mini Landing, and Cancer Research page lists]
    * Make this field unlimited
    * Make this field show as multi-line
  * Feature Card Description
    * Tooltip: Concise description for the page. [Displays on: Home/Landing page feature cards. SEO best practice – 75 characters including spaces]
    * Ensure field is limited to 255 characters
- Page Title is missing tooltip 
  * Tooltip: Unique and descriptive Title (H1 heading) for the page. [Displays on: Lists, SEO best practice – 75 characters including spaces]
* Featured Posts
  * Stacking of selected items is weird; Can they stack one on top of each other so the order of items is more clear?
  * It looks like when selecting items to add as Featured Posts, only blog posts associated with the series are being pulled in, but want to verify.
  * Because blog series is not available to Editors as a content type for editing, editors are not able to update Featured Posts. This is different than what we have in percussion (editors can edit the list that is associated with the blog series). Need to discuss how to resolve this.

**Comment by daquinohd** [comment]
- [ ] About Blog field
- [ ] Unable to see right rail in preview
- [ ] Page Options is missing
- [ ] Site Sections has the incorrect browser
- [ ] When setting a site section, only show the “Remove” button
- [ ] Switch Group Archive By with Number of Years to Archive by on form
- [ ] Meta Description Tooltip
- [ ] List Description Tooltip
- [ ] List Description - make this field unlimited
- [ ] List Description - make this field show as multi-line
- [ ] Feature Card Description Tooltip
- [ ] Feature Card Description limit to 255 characters
- [ ] Page Title Tooltip

**Comment by daquinohd** [comment]
> Featured Posts
> Stacking of selected items is weird; Can they stack one on top of each other so the order of items is more clear?

Bryan wanted this as a backlog item - I don't know if he has picked it up or not. Let me know if this needs addressing as part of this sprint.

> It looks like when selecting items to add as Featured Posts, only blog posts associated with the series are being pulled in, but want to verify.

Right now, all published Blog Posts are being made available for Featured Posts; they are not filtered by series.

**Comment by alifr** [comment]
@daquinohd I'll add page options in my branch. Some CSS is needed there as well.

**Comment by VictoriaSunNIH** [comment]
A few more:
2 more items:
- [ ]  **Short Title** field needs to be updated to only allow 100 characters

- [ ]  **Browser Title** field needs to be updated to only allow 100 characters
