### ISSUE TITLE
Bugs for Blog Series, individual Archive and Category pages (Round 2)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1307]
All Listing Pages (Blog Series, individual Archive and Category pages)
* Should have more margin between Page Title + Subscribe link and first post listing
  * Prod has this `<div` `id=”blogPageOptionsInnerContainer”>` which has 16px margin. That div looks to be empty, but it seems to be what’s creating the margin on prod…
* List Item Title is the wrong font size. It is 1.25em on the ODE, but it should be 1.5em, according to inspect element on Prod.
* “Continue Reading >” text is too large. It is 20px on the ODE, but it’s 16px on Prod.
* Margin around each list item is not correct. There should be 40px margin on top and bottom of each list item.
* Breadcrumbs are not displaying

**Comment by alifr** [comment]
Breadcrumbs are rendering correctly on the theme layer, but the values are not being populated by the backend. I've mentioned this in #1308.
