### ISSUE TITLE
Blog Post Bugs (Round 2)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1308]
Blog Post:
* Intro text styling is not quite right — the grey box should not go right up to the lead image. There should be white space between the intro text and the image to the right. 
  * Compare http://ncigovcdode69.prod.acquia-sites.com/espanol/news-events/temas-y-relatos-blog/2019/cooper-allison to this live post with intro text
* Recommended Content
  * Default to Add Internal Promo Card first when adding items in the Drupal form (similar to Related Resources). Can it use the content browser (and not type ahead)?
  * If a blog post (post A) is added as Recommended Content to another blog post (post B), updates to the card/short title of post A are not displaying unless I push post B through the workflow. 
  * 4x3 image crop should display. 
* Internal Promo Card – can we use the content browser here (and not the type ahead)?
* If a card does not have an image, it should still be the same size as a card with an image
  * http://ncigovcdode69.prod.acquia-sites.com/news-events/cancer-currents-blog/2015/fda-lenvatinib
* Public Use text is not displaying at all (should display below the cards).  See https://www.cancer.gov/news-events/cancer-currents-blog/2019/atezolizumab-triple-negative-breast-cancer-fda-approval for an example of how it displays
* There is a word “Display” between the feature cards and comments.  Not sure what that is, but it shouldn’t be there.
* Body WYSIWYG needs to be set to use Full HTML with no dropdown choices. 
  * Intro text is using the proper WYWIWYG so only change Body!
* Update the following 
  * Meta Description
    * Tooltip: Succinct description of the page content. Most important information should be in the first 150 characters. [Displays in: Site-wide and external search results and when List Description is blank. SEO best practice – do not exceed 320 characters]
    * Ensure field is limited to 320 characters.
  * List Description
    * Tooltip: 2-3 sentence description of the page content. Can be left blank if list description will be the same as the meta description. [Displays on: Home/Landing, Mini Landing, and Cancer Research page lists]
    * Make this field unlimited
    * Make this field show as multi-line
  * Feature Card Description
    * Tooltip: Concise description for the page. [Displays on: Home/Landing page feature cards. SEO best practice – 75 characters including spaces]
  * Ensure field is limited to 255 characters
* Page Title is missing tooltip 
  * Tooltip: Unique and descriptive Title (H1 heading) for the page. [Displays on: Lists, SEO best practice – 75 characters including spaces]
* Breadcrumbs are not displaying
* Horizontal Rule should display directly above public reuse text, which should display below Recommended Content (if applicable). Right now on the ODE, it is showing above Older/Newer Post pagination links. 
  * ODE Example Link: http://ncigovcdode69.prod.acquia-sites.com/news-events/cancer-currents-blog/2019/cancer-immunotherapy-targeted-therapy-combination
  * Live Site Example Links: 
    * https://www.cancer.gov/news-events/cancer-currents-blog/2019/atezolizumab-triple-negative-breast-cancer-fda-approval
    * https://www.cancer.gov/research/key-initiatives/ras/ras-central/blog/2015/ras-no-magic-bullet
* Spanish pagination issues – I believe these are translation issues, documenting anyway:
  * I translated an English post into Spanish. The older/newer post links are correctly translated, but they show the English posts. I believe this is a translation issue. 
  * For posts not translated from the English, but created as their own new Spanish posts, blog post pagination displays the correct Spanish blog post titles, but the links are not working. I believe this is a translation issue as well.

**Comment by alifr** [comment]
- [ ] Intro Text styling
- [ ] Recommended Content - Default to Add Internal Promo Card
- [ ] Recommended Content - Ensure Post Titles are updating everywhere
- [ ] Recommended Content - use 4x3 image crop
- [ ] Internal Promo Card – use the content browser for selection
- [ ] Cards without images should have same height as cards with images
- [ ] Add Public Use text with horizontal rule above
- [ ] Ensure Public Use text displays below Recommended Content
- [ ] Remove orphaned “Display” text
- [ ] Body WYSIWYG - use Full HTML with no dropdown choices
- [ ] Meta Description - add tooltip and field limit of 320 characters
- [ ] List Description - add tooltip and convert to multi-line unlimited field
- [ ] Feature Card Description - add tooltip and limit description to 255 characters
- [ ] Page Title - add tooltip
- [ ] Breadcrumbs should be visible on all pages
- [ ] Resolve spanish pagination issues - ensure post titles (short titles) and links work correctly

**Comment by alifr** [comment]
I've been looking at breadcrumbs. I'm not sure what the strategy is here since blog posts do not follow the same taxonomy as articles.
Breadcrumbs are rendering in the templates, but there is only one breadcrumb on all the blog post and blog series. That is "Home" with an href of `null`.  Since the href is null, rendering is skipped in the template.

**Comment by daquinohd** [comment]
The breadcrumbs should work the same on Blog Series as they do on other page-level content. Blog Posts will need some finagling since they always inherit the owner series path - I'm looking at it

**Comment by alifr** [comment]
I'll take care of 

- Intro Text styling
- Cards without images should have same height as cards with images
- Add Public Use text with horizontal rule above
- Ensure Public Use text displays below Recommended Content

**Comment by VictoriaSunNIH** [comment]
2 more items:
- [ ]  **Short Title** field needs to be updated to only allow 100 characters

- [ ]  **Browser Title** field needs to be updated to only allow 100 characters

- [ ] **Date Display Mode** field:
  * Update the tooltip to: Select which date to display. [Displays on page, beneath the body text.]
