### ISSUE TITLE
Infographic - Field Updates

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1309]
Please make the following updates to the Infographic content type:
- the body field has a dropdown where the user can select which wysiwyg type to use. This should be the Full WYSIWYG by default (with no dropdown option) -- this might be taken care of in a larger "body" ticket

### Field Updates:

- [x]  **Short Title** field needs to be updated to only allow 100 characters
  - [x] Update Short Title tooltip to: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Card Title** needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x]  **Browser Title** field needs to be updated to only allow 100 characters
  - [x] Update Browser Title tooltip to: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x]  **Meta-Description** Field 
  - [x] Add the tooltip: Succinct description of the page content. [Displays in: internal and external search results. SEO best practice: Max 320 characters, most important information should be in the first 150 characters]
  - [x] Ensure this field only allows 320 characters

- [x]  **List Description** field:
  - [x] Add Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** field: 
  - [x] Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 
  - [x] Allow only 255 characters
  - [x] This field should display as a single line (not multiline)

- [x] **Promotional Image** tooltip update:  Overrides Lead Image for promotional use cases (lists, cards, social media sharing)

- [x] **Posted Date** field needs tooltip update: Date the content was posted.
- [x] **Reviewed Date** field needs tooltip update: Date that the content was last reviewed by subject matter expert. 
- [x] **Updated Date** field needs tooltip update: : Date that changes were published to body text of page. 
- [x] **Date Display Mode** field:
  * Update the tooltip to: Select which date to display. [Displays on page, beneath the body text]

- [x] **Search Engine Restrictions** field needs to add tooltip: Indicate how a page should be handled by internal (sitewide search) and external (Google) search engines.

**Comment by blairlearn** [comment]
Page Title / Name will not be updated.

**Comment by VictoriaSunNIH** [comment]
I've removed lead image, and page title (since that requires a hook)
