### ISSUE TITLE
Spanish Translation Workflow Issue on Infographic

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1310]
I created and English infographic and published it. I then tried to translate that infographic, but when I go to save the Spanish translation, I get an invalid transition status error. Apparently @bkline worked on this translation workflow issue before, so hopefully he can offer some insight on how to fix!

**Comment by bkline** [comment]
I posted my analysis and proposed fix for this issue in https://github.com/NCIOCPL/cgov-digital-platform/pull/1129#issuecomment-479260703.

**Comment by bkline** [comment]
Here is the patch for avoiding this problem. GitHub won't let me attach it directly, so I've wrapped it in a `zip` file, which is accepted. Waiting for @bryanpizzillo  to give the green light for my proposed approach.

[issue-1310.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/3039933/issue-1310.zip)

**Comment by lburack** [comment]
@bkline @blairlearn @bryanpnih – the translation fix is working! We just discussed the one issue — the site section fix that was pushed to videos on dev yesterday needs to be applied to the infographic as well.
