### ISSUE TITLE
File Form Display, Tooltip and Field Updates

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1329]
### **Field Updates:**
- [x] **Site Section** field needs tooltip added: The section of the site in which this content should live. This will inform the URL.
- [x]  **Pretty URL** field  needs tooltip added: Used as the last segment of the URL. Do not include slash (/). All lowercase, with no spaces; use hyphens to separate words. Append with file extension (pretty-url.pdf)
- [ ]  **Name** field needs a tooltip: This is the name of the file, to be displayed in the system.

- [x]  **Short Title** field needs to be updated tooltip to: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Card Title** needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x]  **Browser Title** field needs updated tooltip to: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x]  **List Description** field:
  - [x] Add Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** field: 
  - [x] Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 

- [x] **Posted Date** field needs tooltip update: Date the content was posted.
- [x] **Reviewed Date** field needs tooltip update: Date that the content was last reviewed by subject matter expert. 
- [x] **Updated Date** field needs tooltip update: : Date that changes were published to body text of page. 
- [x] **Date Display Mode** field:
  * Update the tooltip to: Select which date to display. [Displays on page, beneath the body text]

- [x] **Search Engine Restrictions** field needs to be added.  Also need to add tooltip: Indicate how a page should be handled by internal (sitewide search) and external (Google) search engines.

## Make sure that Form Display matches the following order:
How the fields should display on the form
* Language Dropdown
* Site Sections
* Pretty URL
* Name
* Short Title
* Browser Title
* Card Title
* List Description
* Feature Card Description
* File Upload 
* Promotional Image
* Posted Date
* Updated Date
* Reviewed Date
* Date Display Mode
* Search Engine Restrictions

**Comment by BrendanBeltzNIH** [comment]
I don't believe there is a meta description.

Also, this is the case of needing to programmatically add the tooltip for name unfortunately.

**Comment by lburack** [comment]
I created #1452 to add the promotional image field to the file media type. @VictoriaSunNIH @BrendanBeltzNIH
