### ISSUE TITLE
Add ability to select microsite theme to cgov_common

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1333]
## Description 
As an admin I would like to select the theme override to use for a microsite. (e.g. blue, purple, etc)

The theme should provide a setting to allow admins to select the theme. It should also load the additional CSS/JS for that theme override for any page within the microsite. A microsite will be a separate Drupal installation, so its settings are separate from www.cancer.gov.

This should align very closely to how we are overriding the themes in www/percussion today. Those override CSS/JS should be reused as much as possible.

**Comment by alifr** [comment]
Creating sub themes for Purple Palette here https://github.com/alifr/cgov-digital-platform/tree/ticket/817-purple-palette
This theme is built as sub themes of `cgov_common` using the standard Drupal sub theme inheritance and it also works with our front-end build system.
