### ISSUE TITLE
Inventory all the places we are targeting the content types.

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1339]
Taken from: #473 

@alifr Can you please inventory all the places we are targeting the content types? It is a little more complicated than just getting the type
* we have merged cgvFactSheet, *some* cgvGeneral and cgvArticle into cgov-article. 
* cgvGeneral could be a cgov-article or cgov-mini-landing
* cgvTopic could be a cgov-article or cgov-mini-landing
* Some features of the old system are being replaced and new features added:
  * The hack https://github.com/NCIOCPL/wcms-front-end/blob/261f0cc46a65facf84d820a12310cea7c17ed5ca/CancerGov/_src/StyleSheets/_hacks.scss#L2 could possibly apply to all content types. More correctly it would apply just to field-article-body.
  * https://github.com/NCIOCPL/wcms-front-end/blob/2147ddbaa4fc657433b3ef72fb5d5fdba03be228/CancerGov/_src/Scripts/NCI/UX/Themes/purpl447e/purple.scss#L19 could apply to any wysiwyg really.

So we really need to find those places and determine how best to target those things. In fact as I type this, the best way to target may be by field... (he says not knowing what new hell that will unleash)

**Comment by amydugan** [comment]
[body-tag-styles.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/3073467/body-tag-styles.xlsx)
