### ISSUE TITLE
Spanish Press Release is Showing English Contact Block

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1341]
The contact block on press releases is configured to display on English, but when testing on Min's www.devbox, we are seeing the English contact block on Spanish press releases. Why? This is wrong. This should only show on English, as it's configured.

**Comment by BrendanBeltzNIH** [comment]
Every page is still showing the english contact block, no? Is this a different thing? The reason is that the yaml content creating that block does not have a translation, so it's reusing the english because no spanish block is available (the footer is done the same way but has a translation).
