### ISSUE TITLE
CTHP Bugs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1346]
Capturing all the bugs from the PR: https://github.com/NCIOCPL/cgov-digital-platform/pull/1337

## Field Updates 
- [x]  **Page Title** field needs an updated tooltip. 
  * Tooltip Text: Unique and descriptive Title (H1 heading) for the page. [SEO best practice: 75 characters including spaces]

- [x]  **Short Title** field - ensure this only allows 100 characters

- [x]  **Browser Title** field  - ensure this only allows 100 characters

- [x]  **Meta-Description** Field 
  - [x] Ensure this field has 320 character limit

- [x]  **List Description** field:
  - [x] Update Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** field: 
  - [x] Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 
  - [x] Allow only 255 characters

- [x] **Search Engine Restrictions** field needs to add tooltip: Used to indicate how a page should be handled by both internal (sitewide search) and external (Google) search engines.

- [x] **Pretty URL** field updated tooltip: Used as the last segment of the URL. Leave blank if page is the designated landing page in the site section. Do not include slash (/). All lowercase, with no spaces; use hyphens to separate words. 

- [x] **Short Title** field needs updated tooltip: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Card Title** field needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x] **Browser Title** field needs updated tooltip: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x] **Meta Description Field** needs updated tooltip: Succinct description of the page content. [Displays in: internal and external search results. SEO best practice: Max 320 characters, most important information should be in the first 150 characters]

- [x] **Overview Card Text** field on the overview card needs to default to Streamlined WYSIWYG (and not display the dropdown to select the WYSIWYG type).

- [x] **Guide Card Description** field on the Guide Card needs to default to Streamlined WYSIWYG (and not display the dropdown to select the WYSIWYG type).

- [x] **Promotional Image** updated tooltip: Overrides Lead Image for promotional use cases (lists, cards, social media sharing)

## Entity Browsers
- [x] PDQ Links Browser and Video Browser - as an editor, I cannot access these browsers (don't have rights.)  Need to update the settings on these new browsers so editors and authors can add PDQ links and videos.

## Card Issues
**CTHP Guide Card**:
- [x] The Guide Card Description should not appear if PDQ Links are added to the card.  This description should only appear when no PDQ links are added (same as is now in Percussion where "The system shall not display content in the Description WYISWYG if content exists in the PDQ Cancer Summaries slot for a card.")
- [x] When adding an internal or external link for View More Information, can we default the dropdown to "Add Internal Link" instead of external link for it to be consistent with other places we add links across the site?
- [x] If I enter PDQ links, and more information links, but do not provide a PDQ link heading, then my PDQ links do not appear at all. Only after I add the PDQ Link heading text and save do I then see the heading and the links below it.  
- [ ] For more information, the external link icon appears 3 times when an external link is added and looks funky.

**CTHP Video Card**: 
- [x] I can see the video, but do not see the link below the video when i add an internal or an external link.

## Themes
- [x]  When I choose the "Survival Rates and Prognosis" Theme for a guide card or overview card, the front-end gets a black overlay when i mouse over
![image](https://user-images.githubusercontent.com/31222859/55571474-91759080-56d3-11e9-8d62-20180492bca8.png)
![image](https://user-images.githubusercontent.com/31222859/55573659-88d38900-56d8-11e9-83c6-43cdacbca929.png)

- [x] General Resources on Coping Theme for a guide card - the bullet spacing is off compared to the other cards.
![image](https://user-images.githubusercontent.com/31222859/55571233-2035dd80-56d3-11e9-9fe6-a6a014623571.png)

**Comment by arcepaul** [comment]
For the issue above:
> For more information, the external link icon appears 3 times when an external link is added and looks funky.

After investigation, this will happen on prod, too if external links are added to link lists.  In the example below, the url was changed to a non *.cancer.gov link
<img width="807" alt="Screen Shot 2019-04-11 at 9 04 32 AM" src="https://user-images.githubusercontent.com/45469809/55959495-e61b8d00-5c38-11e9-8307-e0fd069209b9.png">
