### ISSUE TITLE
Fonts in IE don't look right

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1354]
While testing PDQ content, we noticed that the fonts in IE look off from prod.  This is likely a global bug (not related only to PDQ)

**Comment by alifr** [comment]
This seems to have been resolved by another PR. I do not see any issues with the fonts in IE at this point. If specific examples of this defect are found please attach URLs and screen shots.

**Comment by VictoriaSunNIH** [comment]
Closing this - I think when we imported the FEQ styles, this problem was fixed.
