### ISSUE TITLE
Fix List Description on Blog Series and Post

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1369]
List description should still be a field (don't use paragraphs). It should allow an unlimited number of characters. The text should wrap within the box. 

This happened b/c of a misunderstanding in #1306, but we updated the language to be more clear. This bug needs to be fixed on both the blog series and blog posts.

**Comment by daquinohd** [comment]
This will be fixed as part of a shared field ticket.
