### ISSUE TITLE
Streamline Feature Cards Implementation

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#1372]
Feature Cards is currently implemented on the site in several locations.  Topic Feature cards currently serves as the basis for feature cards but are implemented on the site in several places, each requiring different styling.  Can this be cleaned up?

- Get a design audit to determine if styling can be simplified and consolidated.  e.g. Are the h3s really supposed to be different font sizes, needing to be overridden for each place it appears?
- Better name for feature card? It's not really a feature as much as it is a promotional area for other content
- consolidate styling from topic-feature, minilanding, and feature-cards

**Comment by andyvanavery31** [comment]
Closing due to Feature Cards being updated/created for Redesign.
