### ISSUE TITLE
Breadcrumb Issue on Blog Posts

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1377]
Blog Posts are not showing their full breadcrumb. For example, Cancer Currents blog posts should show News & Events > Cancer Currents Blog, but on the ODE, they are only showing News & Events (note: Cancer Currents Blog is a site section and I did add the blog series as its landing page)

Blog Posts do not have Site Sections. When you create a blog post, you select the blog series it belongs to. The blog post URL is then formed off of the associated blog series and the posted date + pretty URL. Could this be why the breadcrumb isn't properly displaying?

ODE: http://ncigovcdode69.prod.acquia-sites.com/news-events/cancer-currents-blog/2019/pancreatic-cancer-targeting-kras-indirectly

Live Post: https://www.cancer.gov/news-events/cancer-currents-blog/2019/pancreatic-cancer-targeting-kras-indirectly

**Comment by BrendanBeltzNIH** [comment]
The cancer-current-blogs site section does not have a landing page set. Site sections without landing pages are not shown in navigation. This was an explicit requirement.

**Comment by bryanpizzillo** [comment]
I thought there may be blog specific logic, but not in this case... However, can we change the logic to show the closest site section if the current url is not the landing page for that section?

* Example 1: https://www.cancer.gov/news-events/cancer-currents-blog/2019/pancreatic-cancer-targeting-kras-indirectly
   1. What is the closest site section to the current URL?
       * cancer-currents-blog
   2. Is the current page the landing page for that section?
       * No
   3. Then draw the breadcrumbs including the current site section
* Example 2: https://www.cancer.gov/about-cancer/coping/feelings/relaxation
   1. What is the closest site section to the current URL?
       * Learning to Relax
   2. Is the current page the landing page for that section?
       * YES
   3. Only draw the parents of Learning to Relax
