### ISSUE TITLE
Remove <p>..</p> from Article On This Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1382]
When adding body sections on an article, the On This Page links at the top are displaying < p>...< /p> around the header links. See attached screenshot.

This shouldn't happen. Text entered in the Heading field should display as entered in the form.
<img width="516" alt="Screen Shot 2019-04-08 at 10 42 20 PM" src="https://user-images.githubusercontent.com/29731392/55769676-975ecf00-5a4f-11e9-808a-d92dcf0aa7d3.png">

**Comment by BrendanBeltzNIH** [comment]
The paragraph heading field (item.content['#paragraph'].field_body_section_heading) is a simple text format but contains markup. There is a twig filter 'raw' that can be applied to the value to render that text as markup in a template. This is considered potentially unsafe, but that is mitigated by the fact that the input to the heading field is sanitized (the ckeditor format only allows whitelisted elements and attributes (in this case, body, p, string, em).

**Comment by BrendanBeltzNIH** [comment]
There is a bigger story here, but I'm not sure whether it's appropriate to document here or in a new ticket. Doing investigation now. The issue revolves around syndication and excluding the OTP altogether on syndicated content, which requires a larger LOE and programmatic changes.
