### ISSUE TITLE
Insert Embedded Blocks through WYSIWYG - Only Allow Center

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1383]
When inserting embedded blocks (video and image carousels) through the WYSIWYG, for the alignment options, we should only allow center.

The alignment options of 'Right', 'Left' and 'None' should be removed. We do not currently have these options in percussion, and choosing them still only shows a centered block.  During training, we will tell users not to select these options, but we should remove them when/if we can.

Linking this to #1379 - if we can implement this for that ticket, we should apply a similar implementation for this one!

**Comment by andyvanavery31** [comment]
This behavior can occur. Closing ticket
