### ISSUE TITLE
Glossification Modal Window terms are being capitalized

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1385]
The terms that show in the glossification modal window should not be capitalized.  

On Dev (this is incorrect):
![image](https://user-images.githubusercontent.com/31222859/55804968-7926bc80-5aab-11e9-88dd-e550e4205228.png)

On Prod (this is correct): 
![image](https://user-images.githubusercontent.com/31222859/55804996-893e9c00-5aab-11e9-91a9-747cc9e2b84d.png)

**Comment by alifr** [comment]
The fix for this is in `Feature/FEQ-CSS-port` https://github.com/NCIOCPL/cgov-digital-platform/pull/1227 but it's being tied up by feature card work.

**Comment by alifr** [comment]
#1227 has been merged into develop. This can be retested now.

**Comment by VictoriaSunNIH** [comment]
Looks good on dev.  Thanks!
