### ISSUE TITLE
Docker: Enable & Document XDebug Setup

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#14]
XDebug is slow, so it should not always run. XDebug is also IDE dependent, and changes on a per developer basis. So allow developers to enable and disable it as needed.

**Comment by bkline** [comment]
I have added a [wiki page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Debugging-in-VSCode) for setting up PHP debugging in VS Code.
