### ISSUE TITLE
Citation Text Format Dropdown should not display

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#1404]
## Description 

The citiation field on at least Article is displaying the text format dropdown. This should default and be limited to Streamlined and remove the dropdown.

**Comment by adriancofie** [comment]
Possible dupe?

**Comment by adriancofie** [comment]
@amydugan @VictoriaSunNIH  I believe this was superseded by other article fixes  and has already resolved.

**Comment by lburack** [comment]
Yup, this is no longer an issue (along with #1506) so closing this out.
