### ISSUE TITLE
Taxonomy Management of Site Sections does not work

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#1413]
When a taxonomy is too large, Drupal's management tools are problematic.
* Using the management screen to reorder sections throws errors. This is due to the fact that the UI tries to post back an object that has all nodes and weights. (>1mb)
* Adding a node to a section requires you to traverse a very tiny box with the entire tree.

We need a solution that requires the smallest amount of LOE, but allows the IAs to effectively manage the taxonomy without the server breaking or causing other issues.

**Comment by bryanpizzillo** [comment]
I would add that we should use the dev branch.

**Comment by bryanpizzillo** [comment]
The [Taxonomy Manager](https://www.drupal.org/project/taxonomy_manager) module was added as a possible solution for this ticket. Unfortunately it had the following issues:
* Add screen for new terms did not allow fields to be filled in, allowing for duplicate computed paths
* Edit screen bypassed taxonomy validations allowing for duplicate computed paths
* Did not allow for drag-and-drop for ordering (although minor issue)
* Upon completing actions the tree was collapsed and the current term editing screen was changed

**Comment by VictoriaSunNIH** [comment]
Test Scenarios:

**Test 1:** Navigate to the Site Sections Taxonomy.  There should be a new site section manager that allows you to see and click on how many children there are per site section, allowing you to "drill down" by section and view the different site sections for English and Spanish.

**Test 2:** Create a new sub-site section (associating it with a higher level site section).  Navigate to where it has been added, and drag/drop the site sections to rearrange.  Make sure this saves in the backend, and displays the new change on the front-end immediately.

**Test 3:** Move your newly created site section to a different higher level site section, and ensure that it saves and displays correctly.
Do this for both English and Spanish.
