### ISSUE TITLE
When adding a spanish page to related resources, the title for the english page appears in the box

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1439]
When I add a spanish page in related resources to a spanish Article, once I select the content and insert it, the english title appears in the box.

Expected behavior - the spanish page title should appear in the box instead of the english title. This is confusing to users.

![image](https://user-images.githubusercontent.com/31222859/56042783-d9b33500-5d09-11e9-8941-6ddfc87ed821.png)

![image](https://user-images.githubusercontent.com/31222859/56044147-8ee6ec80-5d0c-11e9-8be7-109a60da76d1.png)

When I preview, the correct page is linked, its just the title in the box that shows English.

**Comment by blairlearn** [comment]
Cannot reproduce
