### ISSUE TITLE
Cancer Research List Page content type: Field & Tooltip Updates

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1457]
Capturing all the bugs from the PR: https://github.com/NCIOCPL/cgov-digital-platform/pull/1384

## Form DIsplay Updates 
- [x] Browser Title should go below Short Title
- [x] Move Lead Image and Promotional Image to be above Posted Date
- [x] Default to Internal Link first under Selected Research Pages

## Field Updates 
- [x]  **Page Title** field needs an updated tooltip. 
  * Tooltip Text: Unique and descriptive Title (H1 heading) for the page. [SEO best practice: 75 characters including spaces]

- [x] **Short Title** field needs updated tooltip: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Browser Title** field needs updated tooltip: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x] **Card Title** field needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x] **Meta Description Field** needs updated tooltip: Succinct description of the page content. [Displays in: internal and external search results. SEO best practice: Max 320 characters, most important information should be in the first 150 characters]

- [x]  **List Description** Update Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 

- [x] **Pretty URL** field updated tooltip: Used as the last segment of the URL. Leave blank if page is the designated landing page in the site section. Do not include slash (/). All lowercase, with no spaces; use hyphens to separate words. 

- [x]  **Lead Image** tooltip update: Displays in top right position on the page. Used for lists, cards, and social media sharing, unless Promotional Image is selected.

- [x] **Promotional Image** updated tooltip: Overrides Lead Image for promotional use cases (lists, cards, social media sharing)

- [x] **Search Engine Restrictions** field needs to add tooltip: Used to indicate how a page should be handled by both internal (sitewide search) and external (Google) search engines.

**Comment by sarinapadilla** [comment]
This was closed by PR #1500.
