### ISSUE TITLE
Implement LinkBack Bar

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1468]
Add a region to the theme for the linkback bar, used on microsites to come back to Cancer.gov.

**Comment by amydugan** [comment]
This is now in the backlog because we added the region to theme and are doing this through DTM.

**Comment by VictoriaSunNIH** [comment]
Update: Since we moved to adobe launch, adding this via launch breaks the markup of the pages so we still need a way to implement.  Might be OBE by redesign.

**Comment by bennettcc** [comment]
Closing this ticket - no longer relevant. The linkback bar is being retired.
