### ISSUE TITLE
Biography - Supress Exit Disclaimer Icons on Top Card

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1469]
Exit disclaimer icons shouldn't show up with the linked in/twitter/scientific publication elements.

http://ncigovcdstg.prod.acquia-sites.com/about-cancer/montserrat-garcia-closas

![screenshot-ncigovcdstg prod acquia-sites com-2019 04 15-14-42-57](https://user-images.githubusercontent.com/39384914/56157163-d4195180-5f8c-11e9-8833-456851fad342.png)

**Comment by BrendanBeltzNIH** [comment]
There is already a ticket for this issue. https://github.com/NCIOCPL/cgov-digital-platform/issues/1223

**Comment by BrendanBeltzNIH** [comment]
This is a straightforward fix. The exit notification library has a pretty clear set of criteria

```
$("a[href]:not(:has(>img))").filter(function () {
	return /^https?\:\/\/([a-zA-Z0-9\-]+\.)+/i.test(this.href) 
	 && !/^https?\:\/\/([a-zA-Z0-9\-]+\.)+gov/i.test(this.href) 
	&& this.href !== ""
	&& this.href.indexOf(location.protocol + '//' + location.hostname) !== 0 
	&& !$(this).hasClass('add_this_btn') 
	&& !$(this).hasClass('no-exit-notification');
```

The templates drawing the links in question (field--field-linkedin-handle.html.twig and (field--field-twitter-handle.html.twig) should have the class 'no-exit-notification' added to the a tags.
