### ISSUE TITLE
Biography - Shorter Organizations are moving onto a single line

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1470]
http://ncigovcdstg.prod.acquia-sites.com/doge

With two shorter organizations, they're moving onto one line.  They should each be their own

![screenshot-ncigovcdstg prod acquia-sites com-2019 04 15-14-56-33](https://user-images.githubusercontent.com/39384914/56157920-b0570b00-5f8e-11e9-9f3e-c7a3c186453a.png)

**Comment by claireblaustein** [comment]
see http://ncigovcdstg.prod.acquia-sites.com/about-cancer/albert-paul

**Comment by BrendanBeltzNIH** [comment]
".profile-panel-content .profile-org" has been specifically set to inline-block. Not sure why, this should be undone to make sure the two organizations always occupy their own line. 

Line 51 in _profile-panel.scss

https://github.com/NCIOCPL/cgov-digital-platform/blob/b0ab881d22ad74b2122f074d257abfa2a5c15757/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/styles/_profile-panel.scss
