### ISSUE TITLE
Biography - Excessive space between multiple titles

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1471]
http://ncigovcdstg.prod.acquia-sites.com/about-cancer/albert-paul

There is a lot of space between the two tiles. Reduce Line Height/Bottom Margin?

May also relate to https://github.com/NCIOCPL/cgov-digital-platform/issues/1470 - should be the same space between multiple entries.

**Comment by BrendanBeltzNIH** [comment]
@claireblaustein Which two tiles, this isn't clear to me.
