### ISSUE TITLE
Typo in List Items tooltip

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1474]
![image](https://user-images.githubusercontent.com/31222859/56163871-79d4bc80-5f9d-11e9-90b4-7063f3e2616e.png)

There is an extra "t"

**Comment by BrendanBeltzNIH** [comment]
The line to change is here https://github.com/NCIOCPL/cgov-digital-platform/blob/b94345dcf1e8f948a714356e30720fabdd533229/docroot/profiles/custom/cgov_site/modules/custom/cgov_list/config/install/field.field.paragraph.cgov_list.field_list_items.yml#L16
