### ISSUE TITLE
Embedding items in the lead image spot on Articles and Press Releases causes weird spacing

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1478]
On Article content type only - if we embed an item at the very top of the WYSIWYG, there is weird spacing to the right of the body content.  Also, if we then drag the embedded item further down the page, the space is still left over.

**Steps to recreate:**
1. Embed an item (feature cards, image or infographic) through the wysiwyg, placing it where a lead image should actually go. (http://www-dev-ac.cancer.gov/about-cancer/skidmarks-embed-image)
2. Preview the content item and see that there is weird spacing
![image](https://user-images.githubusercontent.com/31222859/56214254-8869b500-602b-11e9-9d9e-cfeb99cb3ec6.png)
3. Drag the embedded item down further within the body text (if you hover on the image (or a featured item) in the wysiwyg, you’l see a little crossbow to move it around).
4. Preview the page, and you will see there was a weird bit of spacing at the top 
![image](https://user-images.githubusercontent.com/31222859/56214360-bc44da80-602b-11e9-9c3b-36d6189fedd7.png)
5. Looking at the source code using Drupal's source code for the WYSIWYG, there is nothing to clean up.  If you look at view source, you will see embed identity align right, even though there is nothing embedded there.  It seems some spacing is left once we drag the embedded item away from the lead image position. 
![image](https://user-images.githubusercontent.com/31222859/56214312-a1726600-602b-11e9-92fd-4776b84b68d7.png)

Note: this is **NOT** an issue on Mini Landing, Event, Blog Posts, Cancer Center. We've only encountered this on Articles and Press Releases.

**Comment by BrendanBeltzNIH** [comment]
So, this isn't so much random spacing as it is an empty embed artifact 

![image](https://user-images.githubusercontent.com/34315527/56218043-45f7a680-6032-11e9-8f26-6276cbb55762.png)

That means a bunch of things. One, we could attack the embed entities potentially on the front end to make them disappear when they are empty. (This wouldn't likely just be styles unfortunately, ie11 doesn't support look ahead CSS. Collapsing the container by default is possible but might be overly messy). I will look further, once I stop getting stuck on the name.

**Comment by BrendanBeltzNIH** [comment]
This ended up just being a template issue that had snuck in earlier.
