### ISSUE TITLE
LinkIt Needs to Allow Files and Infographics

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1481]
LinkIt as it is configured now only allows us to link to nodes. We need to be able to link to File and Infographic media types. This must be included for launch as these media types (particularly files) are linked throughout content all over the site.

**Comment by BrendanBeltzNIH** [comment]
This shouldn't be more than a configuration change. Media is actually already allowed to be linked to, but right now its just videos.

![image](https://user-images.githubusercontent.com/34315527/56253444-5c315100-608a-11e9-91a5-563be7f4e0fd.png)
