### ISSUE TITLE
The Page Options Issues

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1482]
1. The PageOptions do NOT appear for the following content types:
-Home & landing pages (http://www-dev-ac.cancer.gov/about-cancer)
-Mini Landing Pages (http://www-dev-ac.cancer.gov/news-events/press-releases/2019)
-Press Release (http://www-dev-ac.cancer.gov/news-events/press-releases/2018/cll-ibrutinib-trial)

and it disappeared from PDQ Drug Info Summary (http://www-dev-ac.cancer.gov/about-cancer/treatment/drugs/bevacizumab)

2. Only the font Resizer appears in Blog Series- The other page options do not appear in Blog series.
Test url: http://www-dev-ac.cancer.gov/research/key-initiatives/ras/ras-central/blog

3.Font Resizer does NOT appear on Event , Cancer Center and Biography Content Type

**Comment by BrendanBeltzNIH** [comment]
#1482, #1483, #1484 should be done in concert.

**Comment by VictoriaSunNIH** [comment]
@alinai , @arcepaul - here is the list of pages that should have the resizer: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Page-Options

**Comment by alinai** [comment]
Confirmed with @VictoriaSunNIH , Cancer Center should have font resizers.

**Comment by alinai** [comment]
The page options do not appear at tablet and mobile breakpoint  on Blog series (http://ncigovcdode102.prod.acquia-sites.com/news-events/cancer-currents-blog)  and appears in the blue circle on the right side  at tablet breakpoint and and overlaps text at mobile breakpoint on RAS Dialogue Blog Series page (http://ncigovcdode102.prod.acquia-sites.com/research/key-initiatives/ras/ras-central/blog)

**Comment by alinai** [comment]
Need to test page options on Cancer Research List Page, Cancer Center (for font resizers), Infographic and Video content type when they are ready.
