### ISSUE TITLE
Only the font Resizer appears in Blog Series 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1483]
Only the font Resizer appears in Blog Series. The other page options do not appear in Blog series.
Test url: http://www-dev-ac.cancer.gov/research/key-initiatives/ras/ras-central/blog

**Comment by BrendanBeltzNIH** [comment]
This should be done in concert with #1484

**Comment by alinai** [comment]
Covered it on https://app.zenhub.com/workspaces/cgov-digital-platform-5c0fc73f4b5806bc2bfc78bd/issues/nciocpl/cgov-digital-platform/1482
