### ISSUE TITLE
Font Resizer does not appear on Event , Cancer Center and Biography Content Type 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1484]
Font Resizer does not appear on Event , Cancer Center and Biography Content Type

**Comment by BrendanBeltzNIH** [comment]
@lburack Do we have a single source of truth for the page options per content type or is it just a matter of going off of invision wireframes (which, I know enough not to trust)?

**Comment by alinai** [comment]
Covered in https://app.zenhub.com/workspaces/cgov-digital-platform-5c0fc73f4b5806bc2bfc78bd/issues/nciocpl/cgov-digital-platform/1482
