### ISSUE TITLE
Add ability to create SSO specific user accounts to sites

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1499]
We need the ability to add SSO-only accounts through the Drupal UI. This should create users without valid crypts so that they never can login through a form. We have done similar things for D7 and the nci_sso module. (I don't know how much can transfer.)

**Comment by blairlearn** [comment]
This is already written up at https://github.com/NCIOCPL/cgov-digital-platform/wiki/Single-Sign-On
