### ISSUE TITLE
Set the SAML IDP based on current environment.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1501]
SAML login defines multiple Identity providers (IDPs) in `simplesamlphp/metadata/saml20-idp-remote.php`. NIH uses different servers for the different tiers.  Also, since the contents of that file are essentially "provided code", we shouldn't be editing that file aside from adding a given IDP's metadata.

*Solution:*

Modify `simplesamlphp/config/authsources.php` to look at which environment its on and modify `$config['cancergov-sp']['idp']` to contain the name of the appropriate entry in the `saml20-idp-remote.php` file.

**Comment by blairlearn** [comment]
A question….   What IDP should we be using on Dev/Int/etc?

The initial assumption is:
• *Dev/Int* uses the Dev login server.
• *Staging* uses the Stage login server.
• *Prod* uses…. the Prod server.

But is that the right answer?

On the one hand, we are developing our login mechanism, so in that regard, it makes sense for Dev and Int to use the Dev login server.

On the other hand, at some level, that means we're creating and testing new entries for each environment.  Using the Production login server across the board means we're only doing this once and then it's done.

**Comment by bryanpizzillo** [comment]
Let's go with:
ACE == Dev login
ACSF dev == Dev login
ACSF test == Stage login
ACSF prod == Prod login

**Comment by bryanpizzillo** [comment]
I should add that when they make configuration changes, you will want to be able to look/modify at it on a lower tier.

**Comment by blairlearn** [comment]
Accomplished via commit fa166898509b4e63bf323424256a644433412c25.

*NOTE* There is some  uncertainty about the correct IDP URI for the test/stage environment.
