### ISSUE TITLE
Make a homepage in YAML and make sure we can make a homepage

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1504]
Out of the box, drupal has / as the login page.

We need to make sure we can have a cancer.gov homepage that doesnt go to the log in page and has the https://www.cancer.gov/, and then make a homepage using YAML content.

**Comment by bryanpizzillo** [comment]
So this one is going to be a real PITA.

Things to do from easiest to hardest:
1. Create YAML content for homepage.
2. Find a way to set the front-page node. Options:
    1. Set Configuration->Basic Site Settings->Default Front page when a site is installed
        * Someone would have to do this every time develop is rebuilt
        * Would Spanish work?
    2. When a page is set as the landing page of the site section who's parent TID is 0 (e.g. the root) that node is set as the front-page.
         * Would have to be just the English node with parent 0. Since front page setting should be just english, otherwise we need a Spanish config.
    3.

**Comment by bryanpizzillo** [comment]
### Setting the URL
For the approach of how to set it, I went with 2.II. The config should be ignored, but it was the most straightforward without worrying about caching. 

### URL Generation
We should probably do something about what to make the alias for the home page. Currently the rules generate `-0` as the alias.

**Good URLs**
* canonical
* shortlink
**Bad URLs**
* og:url
* hreflang urls
* link rel="revision"

### Additional issues
1. `/user/login` no longer works.

**Comment by bryanpizzillo** [comment]
I ended up implementing a OutputPathProcessorInterface that takes care of making sure any url generated to the site's front page is `/`. This takes care of most of the bad urls.
