### ISSUE TITLE
PubMed link should not display on another line at the end of the citation

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1506]
When migrating in content, we discovered that PubMed links are showing on a separate line from the content in the citation.   This should display on the same line after the citation content

**Comment by BrendanBeltzNIH** [comment]
Gonna need a bit more to go on for this one, please.

**Comment by lburack** [comment]
This appears to be working now. I guess someone fixed it or a Drupal genie was doing some good work one night.
