### ISSUE TITLE
Move Spanish Configuration to WWW Profile

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#151]
Much of the language configuration is tied deeply into the various other elements in the system. (Field storage, node displays, etc) As such we had to build the base profile with language and translations enabled, but with only one language. We have temporarily enabled Spanish In order to test that our design approaches will work with translations. (e.g. Paragraphs, layout builder, workflow, and combinations of those three) 

Once the www profile has been created:
1. move
    * From: 
       * cgov_site/config/install/language.entity.es.yml
    * To cgov_www_site/config/install (or whatever the www profile will be named)

**Comment by VictoriaSunNIH** [comment]
Closing this as OBE
