### ISSUE TITLE
Figure out how to deal with w3c Privacy Policy

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1528]
Figure out what to do with w3c Privacy Policy File – www.cancer.gov/w3c/p3p.xml

**Comment by BrendanBeltzNIH** [comment]
https://www.youtube.com/watch?v=5-79mMCkNbQ

**Comment by bryanpnih** [comment]
p3p has been deprecated in IE, the only major browser that ever supported p3p.
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/platformforprivacypreferences10p3p10/
