### ISSUE TITLE
The accordion bars are showing white space at the left and right. On expanding the accordion, the links are more indented

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1531]
The accordion bars are showing white space at the left and right. On expanding the accordion, the links are more indented
url: http://ncigovcdode100.prod.acquia-sites.com/about-cancer

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/7834358e-a650-46b2-bd36-d4a0f51af378)

**Comment by BrendanBeltzNIH** [comment]
This is also related to the lack of a .ncilandingpage class anymore. Currently under approach investigation. But there was a rule that negated the extra padding on .ui-accordion elements nested in .ncilandingpage.
