### ISSUE TITLE
Caching Issue with Blog Post Pagination

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1533]
When you add a new blog post to a blog series, the new post you just created does not appear as a Newer Post > link at the bottom of the previous post. 

Also, if you delete blog posts, they are still appearing in the pagination links, but they go to a page not found.

**Comment by daquinohd** [comment]
@lburack @VictoriaSunNIH - this is ready for testing on http://ncigovcdode109.prod.acquia-sites.com.

**Comment by lburack** [comment]
I added a new post and it appeared in pagination links. Also, I deleted several posts and they are now no longer showing in the Older/Newer Post pagination links.

This passes IA Review. Thanks, @daquinohd!
