### ISSUE TITLE
The page options are not right aligned at tablet breakpoint and no margin on the left of page options at mobile breakpoint

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1538]
The page options are not right aligned at tablet breakpoint and there is no margin on the left of page options at mobile breakpoint
Test url: http://www-dev-ac.cancer.gov/about-cancer

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/cfeab7de-96e7-4748-bbfb-9c4ab5764b5a)

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/7815f4bc-3a09-45ec-9503-8be718d21f0d)

**Comment by BrendanBeltzNIH** [comment]
There are a few problems here. But the largest ones stem from the page options not having the large-5 and columns class on the div with the page-options class, and the entire body not having the .nciLandingPage class anymore (which the css is currently using as a selector to override the float of the ul the page options are in).

![image](https://user-images.githubusercontent.com/34315527/56602083-b2424f00-65ca-11e9-8368-10083eaa613a.png)
