### ISSUE TITLE
The menu bar has increased height for Spanish Pages

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1540]
The menu bar has increased height for Spanish Pages (http://www-dev-ac.cancer.gov/espanol/investigacion)
Also, the menu items are not in line with each other (Noticias appears little bit above with respect to other menu items.

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/41f01573-10ec-4ff3-a11e-274eda513154)

**Comment by BrendanBeltzNIH** [comment]
This is not a valid ticket. As you'll note, the menu has a different number of elements and is still in flight. It was determined months ago that the CSS breaks when some of the elements are missing.
