### ISSUE TITLE
Remove "Edit summary" Link above Body on Blog Posts

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1542]
On the blog post content type, there is an "Edit Summary" link that appears above the body WYSIWYG.  We should suppress/hide this option (seems its out of the box with drupal).

![image](https://user-images.githubusercontent.com/31222859/56612239-d2313d00-65e1-11e9-8c67-617125f33bce.png)

**Comment by BrendanBeltzNIH** [comment]
It looks like the wrong field type was used. It should be "text, formatted" not "text, formatted, with summary".
