### ISSUE TITLE
Citations not displaying on Blog Posts

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1545]
Citations are not displaying on the front-end for blog posts.  Please fix (here was the PR when it used to work..https://github.com/NCIOCPL/cgov-digital-platform/pull/939)

**Comment by BrendanBeltzNIH** [comment]
The field is disabled on the full content display mode (which is the only template it’s included in)

**Comment by BrendanBeltzNIH** [comment]
Side note, when this is fixed, the label for citations on article's full content display mode should be set to hidden.
