### ISSUE TITLE
The white area where the page title and the page options appear in the landing page has increased height.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1547]
The white area where the page title and the page options appear in the landing page has increased height.

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/96d4c11b-3808-4875-8c7d-79b3ac55b5c5)

**Comment by BrendanBeltzNIH** [comment]
This is because there was a special rule in LandingPage.css that changed the margin top for h1s to .58  em when nested in the page level '.ncilandingpage'.

**Comment by BrendanBeltzNIH** [comment]
Without an h1 on the home page, this rule can be unscoped and just added to the HomeLanding styles. Also, a rule for h1s seems to have snuck in inexplicably in #1609 and should be removed.
