### ISSUE TITLE
The Patient/HP toggle in PDQ summaries gets cut-off when the text is enlarged using the font resizer page option.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1548]
The Patient/HP toggle in PDQ summaries gets cut-off when the text is enlarged using the font resizer page option.
url: http://www-dev-ac.cancer.gov/about-cancer/treatment/side-effects/skin-nail-changes/pruritus-pdq

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/b46db7b4-847f-4cad-b26f-b932395edde8)

**Comment by alifr** [comment]
Do you mean the icon is being clipped a little bit on the left side of the circle? The text itself does not seem to be getting cut off when I use the font-resizer

**Comment by alinai** [comment]
Yes, I meant the icon is getting clipped on the left for the Patient/HP toggle. Thanks for checking!

**Comment by alifr** [comment]
Incorrect pixel rounding is one of the known issues with our svg sprite system. It does not zoom well. Hopefully we can implement a new icon system post launch. For now this issue is not fixable.
