### ISSUE TITLE
Twitter is showing "undefined" instead of pulling up the page title

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1551]
Twitter is showing "undefined" instead of pulling up the page title.

Steps to reproduce:
1.Go to http://www-dev-ac.cancer.gov/about-cancer/coping/feelings
2. Click the Twitter button at the top right corner of the page
3.See that under Share a link with your followers, "undefined" appears before the url.

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/c841b8ee-913f-4fc1-bcdf-18989bc8064a)

**Comment by bryanpizzillo** [comment]
Hold off on testing options. This needs metatags
