### ISSUE TITLE
Back To Top Button appears as soon as the page is loaded.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1554]
Back To Top Button appears as soon as the page is loaded. Then on scrolling down it disappears and then again reappears.
Test url: http://www-dev-ac.cancer.gov/about-cancer/coping/feelings

**Comment by BrendanBeltzNIH** [comment]
This is because the footer block content yaml file has the "display:inline" rule already on the back-to-top element. This was a mistake on my part many moons ago and should be removed. (The style rule is added by the javascript on scrolling).
