### ISSUE TITLE
Editors & Authors need to access the video browser when embedding video, and media browser when adding media links

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1559]
When logged in as an editor or an author, I do not have access to:
* video browser (for adding embedded videos)
* media link browser (for adding media links to related resources and lists)

Please update the configuration so that editors and authors can access these browsers.

**Comment by VictoriaSunNIH** [comment]
Seems this is just an ODE issue, as i can access on dev.  Closing for now!

**Comment by BrendanBeltzNIH** [comment]
Someone is feeling indecisive.
