### ISSUE TITLE
Dev and Stage is showing an Exit Disclaimer in the admin Menu Bar

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1562]
Dev and Stage is showing an Exit Disclaimer in the admin Menu Bar

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/aefaa165-0ef3-48c6-bcf5-a554cf2ec47e)

**Comment by BrendanBeltzNIH** [comment]
This is related to #1223.
