### ISSUE TITLE
DCEG Contact Form

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1566]
DCEG has a contact form that they need to migrate over to Drupal: https://dceg.cancer.gov/research/clinical-studies/contact

It has gone through OMB Clearance in the past, but DCEG will follow up to ensure that's still valid. Pending no issues there, we'll need to make sure this happens for DCEG migration. Tagging @blairlearn for awareness/issues/concerns.

**Comment by amydugan** [comment]
Per Wendy Schneider-Levinson (via Megan), the DCEG form is no longer needed and will not have to be migrated. A link to a contact email address will be included in content.
