### ISSUE TITLE
IIS: Map virtual directory for MP3 files

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1576]
On the IIS servers serving up content from the legacy NCI system, a virtual directory mapping is needed from `/PublishedContent/Media/CDR/media/` to the `StaticContent\images\cdr\live` directory.

**Comment by VictoriaSunNIH** [comment]
@blairlearn  - is something going to be needed on the 12th for this?  please document

**Comment by VictoriaSunNIH** [comment]
@blairl-nih - i closed this as completed, feel free to reopen if thats not the case
