### ISSUE TITLE
Fixes to Event List View Styling (Upcoming and Past Event Pages)

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1585]
Some styling issues to resolve:

- View title showing on front end <div class="viewsreference--view-title">
-- shouldn't show on Upcoming or Past event pages, only on Events landing page
-- should be styled as an h2
-  Event series should be h4
-  Date and time should share line
-  show Venue field, if filled, or no location data.
-  Don't need to force 2 digit dates and times - shouldn't show preceding 0 (7:00 AM not 07:00 AM)
-  Separator for time should be an en dash

Spacing throughout individual entry is too tall - tighten space between elements, but allow breathing room between event entries - let me know if you want specific details. 

Check on CSS styling for h3 in lists - should be color change for hover state, not underline. This was an issue in Cgov too.

**Comment by arcepaul** [comment]
link to wireframes: 
https://lm1a12.axshare.com/#g=1&p=event_listing_no_past_events
