### ISSUE TITLE
Create CTHP External Feature Card

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1589]
We need to create a CTHP External Feature Card (cthp_feature_card_external)
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP#cthp-external-feature-card

Also, we should then change the CTHP Feature Card to be CTHP Internal Feature Card (cthp_feature_card_internal) for consistency/clarity sake. We need to understand the LOE of that change first before we make it.

**Comment by arcepaul** [comment]
Adding as AC from #1606 :
Remove DOM manipulation related to WCMSFEQ-423 in exitDisclaimer.js
and figure out appearance of exit disclaimer icon
