### ISSUE TITLE
Archiving Content Should Remove it from the site (but not from Drupal)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1591]
I created a piece of content and published it. I then moved it through the workflow to Archive it. In the Content Overview, the page showed with a status of "Unpublished", but the page was still visible on the site. 

This is a bug. If a piece of content is Archived, it should no longer be public on the website. It should still exist in the system though, with a state of "Archived".

**Comment by amydugan** [comment]
@lburack - was the archived content visible on the site to an unpermissioned user?

**Comment by bkline** [comment]
Right. The item is correctly recognized by the system as unpublished. Accounts with sufficient privileges are allowed to see unpublished items on `/admin/content`, but they're clearly marked as unpublished. Anonymous visitors are not allowed to see the content. I believe this is how the system is supposed to work, no?

**Comment by bkline** [comment]
I suppose if you wanted to pretend to the visitor that the page doesn't exist at all, you could change its URL.

**Comment by VictoriaSunNIH** [comment]
Closing this one out, it'll be resolved as part of #1741
