### ISSUE TITLE
If a Blog Series does not have a banner image, do not display "Blog" overlay

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1592]
If a blog series does not have a banner image uploaded to it, the black "blog" overlay that normally displays on top of the banner image (in the top right) should NOT display. 

screenshot from http://ncigovcdode109.prod.acquia-sites.com/pets/pets-blog
<img width="1238" alt="Screen_Shot_2019-04-30_at_10_40_18_PM" src="https://user-images.githubusercontent.com/29731392/57004034-46974d80-6b99-11e9-8a7b-e7705c6ca916.png">

**Comment by BrendanBeltzNIH** [comment]
The banner is applied to the .blog.body-banner::before element. The entire div.blog.body-banner element . should be added conditionally based on whether content.field_banner_image is empty or not (in other cases we've tested image fields with a simple content.field_banner_image[0]).
