### ISSUE TITLE
Move Permissions from Role YAML files into the Appropriate module.install install hooks

### ISSUE THREAD

**Issue by bryanpnih** [NCIOCPL/cgov-digital-platform#1594]
Our roles files in the cgov site have gotten messy including things that could be disabled for a site. We do this already for content type permissions, so there is no reason to not do it for all permissions. The benefit to this would also be that roles can move to core where they belong...

Additionally as we evaluate other configuration management approaches, having a mix of  permissions defined in the yaml files, and modifcation on module installs introduces issues.

The task is to:
1. Move the roles to core. (Administrator may cause issues...)
2. Add code to the various module.install install hooks to attach the permissions to the roles. This should be done in the module that implements the feature that convey's the permission. For example `access cgov_image_browser entity browser pages` defined for the Admin UI role should be moved into cgov_image where the `cgov_image_browser` entity browser is defined.

**Comment by bryanpizzillo** [comment]
I removed the administrator role as we should not be using it in prod, and user 1 works fine in dev. If we really do need it then we should just set the `is_admin` flag on the role and treat it as an admin role.
