### ISSUE TITLE
Content Type specific references to be updated for analytics

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1597]
There are a couple of content type specific references in our analytics files that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these JavaScript functions working. As it is now, these events will never be bound because the DOM elements will not be found on the page.

In `analytics.js` there is a reference to `$('.cgvblogpost #cgvBody').on("click",...)` and `$('#cgvBody').on("click",...)`.

In `nci-analytics-functions.js` there is reference to `body.cgvblogpost`, `body.cgvblogseries`, and `body.cgvtopicpage`

**Comment by VictoriaSunNIH** [comment]
Pending #1437
