### ISSUE TITLE
Content Type specific references to be updated for CTS

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1598]
There are a couple of content type specific references to app module DOM nodes that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

In `cts.basic.scss` there is a reference to `.nciappmodulepage .accordion-controls` and `.nciappmodulepage .accordion`. The `.nciappmodulepage` selector can probably be removed in both cases if the styles are added to a CTS specific entrypoint style sheet.

**Comment by bryanpizzillo** [comment]
@arcepaul Can this be closed?
