### ISSUE TITLE
Fix permissions for glossifier service

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#1602]
Explicitly grant the `Access POST on PDQ Glossifier API resource` permission to the authenticated user role.

**Comment by bryanpizzillo** [comment]
@bkline, Was this issue logged because during UAT it was determined that non-admin users were not able to glossify documents?

**Comment by bkline** [comment]
Correct. Victoria reported this in a Slack direct message channel (with you, Brendan, Lindsay, and myself) on April 23.

**Comment by bkline** [comment]
`Closes #...` syntax didn't work. Closing by hand.
