### ISSUE TITLE
Content Type specific references to be updated for CTHP

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1606]
There are a couple of content type specific references to CTHP pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

- scope CTHP types in `CTHPPage.scss` to cthp entry point scss. See `[data-cde-pagetemplate~="NVCGCancerTypeHomePageTemplateHP"]` 
- Remove DOM manipulation related to `WCMSFEQ-423` in `exitDisclaimer.js`
- remove/rename `.cgvcancertypehome .cardBody .icon-exit-notification` from `icons.scss`
- ensure `.cthp-card-image` styles in `icons.scss` are still needed and/or used on CTHP pages
- ensure list styles on CTHP pages have been updated properly and are scoped to cthp entry point scss. Specifically look at `lists.scss` for `.ncilandingpage ul.cancer-list` and discover if these styles are still needed and/or used on CTHP pages. Note in code mentions `These styles are Cancer Types Landing Page`

**Comment by arcepaul** [comment]
- [ ]  scope CTHP types in CTHPPage.scss to cthp entry point scss. See [data-cde-pagetemplate~="NVCGCancerTypeHomePageTemplateHP"]
- [ ]  Remove DOM manipulation related to WCMSFEQ-423 in exitDisclaimer.js
- [ ]  remove/rename .cgvcancertypehome .cardBody .icon-exit-notification from icons.scss
- [ ]  ensure .cthp-card-image styles in icons.scss are still needed and/or used on CTHP pages
- [ ]  ensure list styles on CTHP pages have been updated properly and are scoped to cthp entry point scss. Specifically look at lists.scss for .ncilandingpage ul.cancer-list and discover if these styles are still needed and/or used on CTHP pages. Note in code mentions These styles are Cancer Types Landing Page

**Comment by arcepaul** [comment]
Removing the block from exitDisclaimer.js will be handled as part of CR #1589 as external feature cards haven't been implemented yet.
