### ISSUE TITLE
Content Type specific references to be updated for Blog Pages

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1607]
There are a couple of content type specific references to Blog pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

- ensure layout styles seen on `#nvcgSlSectionNav` in `blogs.scss` is now handled by twig templates.
- scope blogs post specific padding on `.contentzone` in `blog.scss` to blogPost entry point scss
- medium sized images are smaller on blogs. Adjust `figure.image-right-medium` in `blogs.scss` to be properly scoped to the blogPost entry point scss file
- scope `.cgvblogseries .list a.title {` font size styles in `bogs.scss` to blogSeries entry point scss
- replace `.topic-feature .cgvBlogPost a h3` in `blue.scss` with `.topic-feature .feature-card a h3`

**Comment by alifr** [comment]
Acceptance Criteria
1. ensure layout looks correct on BlogPosts
    1. ensure that `<div id="nvcgSlSectionNav">` does not exist in the markup
    2. ensure that if `<div id="nvcgSlListBlogRTRail">` is removed from the page `<div id="main">` spans the full width of the page
    3. ensure that main content (`<div id="main">`) has a left padding of `1.6em`
2. ensure medium images on blog posts (near the top right of the post) have a left margin of `1em` and left padding of `2.5em`
3. ensure the blog post titles on a blog series listing page have a font-size of `1.5em` and a computed size of `24px`. Note: em units are relative to their parent elements' size, so when stacked they may have different final font size.
4. ensure blog posts place in topic-featured cards have correct styles as seen here https://www.cancer.gov/about-cancer/treatment/types/precision-medicine/tumor-dna-sequencing in the `FDA Approves Two Genomic Profiling Tests for Cancer` aside card. Note: I currently can not find an example of this in the Drupal test site.

**Comment by VictoriaSunNIH** [comment]
Hi @alifr -

1.ii : I viewed source and deleted <div id="nvcgSlListBlogRTRail"> from the page, but am not seeing the content span the full width.

Also there seems to be an extra non-breaking space between the end of the main content, above the "older/newer" pager.

![image](https://user-images.githubusercontent.com/31222859/57633170-1ffded00-7571-11e9-87b4-eb027ce07916.png)

**Comment by alifr** [comment]
I was not able to find a blog post with the additional `<p>` tag. That must be a content issue you found. Our templates are not programmatically adding those.

**Comment by VictoriaSunNIH** [comment]
Looks good.  Passes review!
