### ISSUE TITLE
Content Type specific references to be updated for Home and Landing pages

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1608]
There are a couple of content type specific references to homelanding pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

- There were variations between home page and landing page accordions in `accordion.scss`, but now they share the same template so these styles can be consolidated and scoped to homelanding entry point scss
- scope margin on `.ncilandingpage p, .ncihome p:not(.site-name):not(.site-link)` elements in `homelanding.scss` to the homelanding entry point scss
- scope margin on `.ncilandingpage h1` in `homelanding.scss` to homelanding entry point scss
- scope `.ncilandingpage #PageOptionsControl1 ul` in `pageOptions.scss` to homelanding entry point scss
- properly scope `.ncilandingpage #PageOptionsControl1 ul` in `purple.scss`. The `.ncilandingpage` selector can probably be removed. Also check on blue and green color variants.

**Comment by alifr** [comment]
acceptance criteria

1. ensure margins around accordions at mobile breakpoints on the home and landing pages are correct and flush to the edge of the browser without clipping the +/- expanding icon
2. ensure margins on `<p>` elements in home and landing pages are just `.5em` on the top and bottom
3. ensure the top margin on `<h1>` elements on home and landing pages remains `.58em` even on mobile breakpoints

**Comment by lburack** [comment]
Hi @alifr, 

> 3. ensure the top margin on `<h1>` elements on home and landing pages remains `.58em` even on mobile breakpoints

Top margin is correct on desktop, but it's 1em on mobile.

![Screen Shot 2019-05-13 at 11 32 04 AM](https://user-images.githubusercontent.com/29731392/57634177-c8f91780-7572-11e9-9003-93fe0ef34e19.png)

**Comment by alifr** [comment]
I agree with you on lists. It's been a mess to untangle. I think they look better with the additional margin anyway.

**Comment by VictoriaSunNIH** [comment]
Looks good to me!
