### ISSUE TITLE
Content Type specific references to be updated for PDQ pages

### ISSUE THREAD

**Issue by alifr** [NCIOCPL/cgov-digital-platform#1609]
There are a couple of content type specific references to PDQ pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

- properly scope `.pdqcancerinfosummary table thead tr th` in `tables.scss` to pdq entry point scss

Acceptance Criteria:
1. ensure text in table header cells are centered on PDQ pages. For example `types/breast/hp/breast-screening-pdq`

**Comment by VictoriaSunNIH** [comment]
This issue looks good!
