### ISSUE TITLE
Remove drupal form login for administrator role.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1630]
Leaving the `administrator` role and `admin` user able to login using the Drupal authentication system until we're sure we've got the kinks worked out SSO.

In `docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/config/install/cgov_saml_auth_config.settings.yml`

* Set `allow.default_login` to `false`
* Set `allow.default_login_roles.administrator` to `'0'`
* Set `allow.default_login_users` to `'0'`

**Comment by blairlearn** [comment]
A minor addition to the approach: Create a `cgov_saml_auth_config_dev` module which `blt drupal:toggle:modules` will activate on the dev tier in place of `cgov_saml_auth_config`.

The new `_dev` module will allow users in the `administrator` role to use Drupal login.

**Comment by bryanpizzillo** [comment]
I have also set the admin user as blocked when a site is installed in prod.

**Comment by VictoriaSunNIH** [comment]
@blairlearn - this still needs to be available on lower tiers, just not on prod.  Needs to be implemented as a staging factory hook to reenable admin on a dev tier
