### ISSUE TITLE
Add metadata tags for site sections

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1638]
For analytics, we need to add metadata tags for site sections.  See excel sheet attached for requirements

[Analytics_requirements_site section.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/3148991/Analytics_requirements_site.section.xlsx)

**Comment by daquinohd** [comment]
We may be able to omit some of the site section fields - Joe is looking at the navon fields report and will confirm.
