### ISSUE TITLE
Update browser title and og:site_name

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1639]
- Browser title should append " - National Cancer Institute" after the browser name.
- For spanish, append " - Instituto Nacional Del Cáncer"
- For og:site_name - it should pull the site name and append " - National Cancer Institute" unless the sitename is "National Cancer Institute"
  - if the page is a spanish page, og:site_name should then append the spanish name " - Instituto Nacional Del Cáncer" unless the sitename is "Instituto Nacional Del Cáncer"

**Comment by bryanpizzillo** [comment]
Make new tokens:
* cgov_tokens:og-site-name - this should be:
```
$name = t('National Cancer Institute');
if (trans-site-name != $name) {
  $trans-site-name - $name
} else { $name }
```
* cgov_tokens:trans-site-name - this should be t(config('system.site')->name)
