### ISSUE TITLE
Define Data Structure of PDQ Summary

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#164]

**Comment by blairlearn** [comment]
I've started (still a *very* early draft) a page at https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-PDQ-Summary

**Comment by blairlearn** [comment]
Pulling this back from the code....

Each summary has a
* CDR ID
* Title
* URL
* Collection of sections.

Each section is in turn composed of a:
* Section Title
* Section ID
* HTML

**Comment by blairlearn** [comment]
The [PDQ Summary content type description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-PDQ-Summary) wiki page has been updated.

**Comment by VictoriaSunNIH** [comment]
Common fields should all be on PDQ Summaries (unless there are any special rules.)  If there are additional fields, please add it to the wiki page.
