### ISSUE TITLE
Incorrect hover colors for microsite themes

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1642]
The following are not getting their correct hover colors for all microsite themes.  They are all appearing as cranberry on hover:
- Inline feature cards
- Secondary feature cards
- Links in lists 

Refer to #817, #818, #909 for specs for the different microsite colors

**Comment by alifr** [comment]
These links were not covered in the original microsites CSS. Probably because the content above does not appear on the microsites.

**Comment by VictoriaSunNIH** [comment]
Fixed on dev. closing.
