### ISSUE TITLE
Page options are not appearing on landing pages for microsite themes

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1643]
For all microsite themes, page options are not appearing on home/landing pages

**Comment by BrendanBeltzNIH** [comment]
@VictoriaSunNIH  Can you clarify? Are you saying home and landing pages with a color theme turned on? Or something else? I still see page options with different color themes, so I assume I'm mistaken on what this ticket is describing.

**Comment by VictoriaSunNIH** [comment]
Yes @brendanbeltznih, with the color themes turned on, there are no page options appearing on the home and landing pages (they do appear on inner pages).

**Comment by BrendanBeltzNIH** [comment]
Are you testing on a particular PR ODE? Because I'm not seeing this issue on dev or local.

**Comment by VictoriaSunNIH** [comment]
Closing this issue as suggested - didn't realize that it was so far behind at this point.  Thanks for pointing it out @BrendanBeltzNIH
