### ISSUE TITLE
Green Microsite Theme: The first toggle in the mobile menu is not the right color

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1648]
The + and - background color in the mobile menu for the first item (about cancer) is not correct - it should be consistent with the rest of the + and - in the menu, http://ncigovcdode100.prod.acquia-sites.com/about-cancer/coping/feelings

![image](https://user-images.githubusercontent.com/31222859/57306270-89cd5100-70b0-11e9-852a-8d2a26485b35.png)

![image](https://user-images.githubusercontent.com/31222859/57306279-8d60d800-70b0-11e9-98dd-65da7f1f25c8.png)

**Comment by alifr** [comment]
I can't fix this at the moment because someone removed the mobile menu bar.

**Comment by bryanpizzillo** [comment]
@alifr are you still having issues with the menu bar? I ask because it is displaying on dev.

**Comment by VictoriaSunNIH** [comment]
This looks good on dev.  Closing as completed
