### ISSUE TITLE
Update/Fix/Revert Order for List Link Types 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1667]
Home/landing and Mini Landing Pages — the order of list link types isn't correct. I feel like it was at one point. But I could also be losing my mind and be wrong. Either way, please change it so when you add to the list items, the order you see is:
Add Internal Link
Add External Link
Add Media Link

<img width="395" alt="Screen_Shot_2019-05-07_at_8_42_56_PM" src="https://user-images.githubusercontent.com/29731392/57342037-d9406b00-710a-11e9-8ba6-2b65e00e73fe.png">

**Comment by BrendanBeltzNIH** [comment]
Lines 27 and 28 just need to be swapped in field.field.paragraph.cgov_list.field_list_items
