### ISSUE TITLE
outlook downloads for all day events have random times

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#1669]
The outlook downloads for all day or multi day events are downloadng with random times

http://ncigovcdode114.prod.acquia-sites.com/news-events/events/dceg-seminar-treon - 7-8 AM

http://ncigovcdode114.prod.acquia-sites.com/news-events/events/cell-fate - 3 AM - 12 AM

**Comment by VictoriaSunNIH** [comment]
This would be nice to have for go live if the LOE isn't super high.

**Comment by andyvanavery31** [comment]
Closing due to redundancy with #2922 .
