### ISSUE TITLE
Browser title is missing from Drug Info Summaries

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1678]
This means that the `<title>` metatag is broken, as well as its ability to be used as a feature card on the site doesn't exist, because there is no field_browser_title on DIS.

We need to add these to DIS in Drupal, and map it as its currently mapped in percussion/GK.

**Comment by blairlearn** [comment]
It appears the mapping for `short_title` was left out of the [Drug Info Summary](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-PDQ-Drug-Info-Summary) field mapping.

Given that the `short_title` field no longer exists, I believe the document title should be placed in the `browser_title` field.

@VictoriaSunNIH  and @lburack - can you confirm?

**Comment by VictoriaSunNIH** [comment]
@blairlearn - yes, if thats what is currently mapped to "short title" in percussion, then that should be what is placed in the browser title field.
