### ISSUE TITLE
DTM metatag - additional values for dcterms.isReferencedBy

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#1681]
Add custom values for Best Bets, dictionary, CTS values once those components are in place.

- Name: “dcterms.isReferencedBy”
- Page-specific values (these are added to the default values set in JS):
  - “event10” – Best Bets appears on page load
  - “event11” – Dictionary definition page or popup loaded
  - “event2” – CTS results page or trial listing page loaded

**Comment by bryanpizzillo** [comment]
Closing as outdated. Also we now have the app modules.
