### ISSUE TITLE
DTM metatag - values for totalResults

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#1683]
For Sitewide and Microsite Search Results; 
Cancer Term, Drug, Genetics Dictionaries; 
Genetics Services Directory Results;
Basic CTS Results, Advanced CTS Results, Trial Listing pages.

Add values once the appmodules are in place.

- name: “totalResults”
  - content: total number of search result items (int); 0 if no results found
  - Any other pages / appmodules that return a search total value should be added to this list.

**Comment by bryanpizzillo** [comment]
Closing these as outdated. (They are app modules now)
