### ISSUE TITLE
DTM data element - verify CDR ID

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#1684]
For Dictionary Definition pages:

- Element: `<dfn>`
- Attributes:
  - data-cdr-id: CDR ID 
  - This is an existing data element; see https://www.cancer.gov/publications/dictionaries/cancer-terms/def/a33. We need to verify once definitions are built out on dev.

**Comment by VictoriaSunNIH** [comment]
We will need to do this whenever we migrate the dictionaries

**Comment by VictoriaSunNIH** [comment]
Verified.
