### ISSUE TITLE
Press Release Type - Alignment is off on the front-end 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1687]
On Press Releases, the Press Release Type field is a text field. If populated, the text should top-align with the left navigation. 

Screenshot below shows prod on the left and the dev ODE on the right.

![Screen_Shot_2019-05-09_at_7_36_07_PM](https://user-images.githubusercontent.com/29731392/57493465-03249980-7293-11e9-8121-ec5c3133fe2c.png)

I don't think this is high priority, but @amydugan @VictoriaSunNIH chime in if you think otherwise.

**Comment by BrendanBeltzNIH** [comment]
The template needs correcting.

Right now, the field is not wrapped correctly or in the right parent:
```
<article>
  <div class="resize-content">
    {{ content.field_press_release_type }}
```

Should be something like:

```
<article>
  {% if content.field_press_release_type|field_value %}
     <div id="cgvBodyHeader" class="row banner-slot">
	  <div class="slot-item only-SI large-12 columns body-banner">
		  <div class="news-type">{{ content.field_press_release_type }}</div>
	  </div>
     </div>
  {% endif %}
  <div class="resize-content">
```
