### ISSUE TITLE
Create Promo Image

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#169]
This story is to create the [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#promotional-image) common field for use on content types.

**User Story**
* As a content owner, I would like to add a promotional image to content I am creating.

**Acceptance Criteria**
* The Promo Image field exists and can be attached to content items

**Comment by bgnih** [comment]
Approach:  Add a media:image entityreference field storage configuration changes to the .../cgov_site/config/install folder

**Comment by bryanpizzillo** [comment]
This is duplicated by #421 -- this was not attached to the Epic, so I created a new one.
