### ISSUE TITLE
Make Title field on External Link not required for CTHP Video Card

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#1695]
Preferably, title should not be a required field on an external link when added to a CTHP Video Card. For the CTHP Video Card, the external link title should not appear anywhere on the front-end, so it shouldn't be required.

**Comment by VictoriaSunNIH** [comment]
External link is a shared field - If we wanted to address this, we could just update the tooltip to say that even though its required, it only shows in certain places
