### ISSUE TITLE
Replace use of deprecated drupal_set_message

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#1697]
The global `drupal_set_message()` function has been deprecated since Drupal 8.5, and will not survive an upgrade to 9.x. Use the `Messenger` service instead on line 117 of `cgov_core.module`.

```
  \Drupal::messenger()->setMessage(...);
```

**Comment by bryanpizzillo** [comment]
Oh hey, we finally fixed this. Yay! Closing.
