### ISSUE TITLE
Use content posted date for blog_rss view filter

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#1713]
The view currently filters by the revision posted date, which results in duplicate rows in the view.

**Comment by VictoriaSunNIH** [comment]
@bkline - I tested this on Press Releases and its working fine.  For blog series, when I go to the RSS feed for blogs, I encounter an error:

![image](https://user-images.githubusercontent.com/31222859/57879654-f2bc7380-77ea-11e9-9f29-8abbb155ac7d.png)

The URL I used was: http://ncigovcdode138.prod.acquia-sites.com/espanol/PublishedContent/RSS/syndication/rss/blog.rss
