### ISSUE TITLE
If a list includes unpublished content only, the Heading/List Title (and unpublished list items) should not be visible to anonymous, non-logged in users

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1715]
cgov_internal_link and cgov_media_link should not be displayed when:
- if the field_internal_link or field_media_link point to an unpublished entity and an anonymous user is viewing the page
- The field_internal_link or field_media_link is not a real page
- If the field_internal_link or field_media_link is empty

**Specific Implementations**
- If a cgov_list (used on mini landing pages) would not be displaying any items then it should not be displayed.
  - There should be an html comment generated saying the list is being hidden. 
- If field_related_resources would not display any items, than the Related Resources heading should not display.

**Places that should Implement the General Requirements**
- field_selected_research (on the CTHP Research List Pages) — no special stuff, but this shouldn't break. If you have no items, it should show no items. That should also apply to the Research card on the CTHP. 
- CTHP Guide Card should not display the 'View more information' heading if no items should be displayed. 

TEST THE RULES ABOVE.

Here's an example of the bad things that happened and why this ticket was created:
<img width="434" alt="Screen Shot 2019-05-14 at 10 57 25 AM" src="https://user-images.githubusercontent.com/29731392/57708354-2d7daa80-7637-11e9-94ac-f689bdd44af9.png">

**Comment by bryanpizzillo** [comment]
# Test Cases/URLs

## cgov_list Tests
### /test/mini-landing/bad-lists
Contains 4 Lists:
* One with a single unpublished page
   * Expectations:
      * Anon Users: The list should be hidden
      * Authors+:  The list should appear with a link to the unpublished page
* One with a unpublished file
   * Expectations:
      * Anon Users: The list should be hidden
      * Authors+:  The list should appear with a link to the unpublished file
* One with a cgov_internal_link with a bad reference
   * Expectations:
      * Anon Users: The list should be hidden
      * Authors+:  The list should be hidden
* One with no list items
   * Expectations:
      * Anon Users: The list should be hidden
      * Authors+:  The list should be hidden

## cgov_cancer_research Tests
### /test/cancer-research/unpublished-page
* Contains a single selected research item with a link to an unpublished page
   * Expectations:
      * Anon Users: The link **should not** display
      * Authors+:  The link **should** display
### /test/cancer-research/bad-page
* Contains a single selected research item to a cgov_internal_link with a non-existant page
   * Expectations:
      * Anon Users: The link **should not** display
      * Authors+:  The link **should not** display
### /test/cancer-research/no-page
* Contains a single selected research item to a cgov_internal_link with NO page
   * Expectations:
      * Anon Users: No link **should not** display
      * Authors+:  No link **should not** display
### /test/cancer-research/unpublished-file
* Contains a single selected research item with a link to an unpublished file
   * Expectations:
      * Anon Users: The link **should not** display
      * Authors+:  The link **should** display
### /test/cancer-research/bad-file
* Contains a single selected research item to a cgov_media_link with a non-existant file
   * Expectations:
      * Anon Users: The link **should not** display
      * Authors+:  The link **should not** display
### /test/cancer-research/no-file
* Contains a single selected research item to a cgov_media_link with NO page
   * Expectations:
      * Anon Users: No link **should not** display
      * Authors+:  No link **should not** display
