### ISSUE TITLE
Migration ODE - Styles of PDQ List Pages aren't migrating with the right styles

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1720]
The styles used on the Adult Treatment and Pediatric Treatment PDQ list pages are not coming through on the migration ODE. The two links (patient & health professional) are showing as bullets; they should be on one line with a vertical pipe in between. See screenshot below — left is prod; right is migration ODE.

https://www.cancer.gov/publications/pdq/information-summaries/adult-treatment 
https://www.cancer.gov/publications/pdq/information-summaries/pediatric-treatment
VERSUS
http://ncigovcdode118.prod.acquia-sites.com/publications/pdq/information-summaries/adult-treatment
http://ncigovcdode118.prod.acquia-sites.com/publications/pdq/information-summaries/pediatric-treatment

![Screen Shot 2019-05-14 at 6 47 51 PM](https://user-images.githubusercontent.com/29731392/57737232-dc8ea600-7678-11e9-874a-3952b4be7e2a.png)

**Comment by VictoriaSunNIH** [comment]
ODE: http://ncigovcdode139.prod.acquia-sites.com/
