### ISSUE TITLE
If an unpublished content is added to Primary, Secondary or MM Feature Card areas on home and landing pages, the card container should not be visible to anonymous, non-logged in users

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1728]
When an unpublished node is added to a home or landing page, users who are not logged into the CMS should not see the card containers for those unpublished contents.

For the primary feature card row, the teal background should not appear for an unpublished item:
![image](https://user-images.githubusercontent.com/31222859/57801363-89246280-7721-11e9-8f80-0fbe0c07664a.png)

For the secondary feature card row, the white background should not appear for an unpublished item:
![image](https://user-images.githubusercontent.com/31222859/57801418-a6593100-7721-11e9-8f1a-393e3ae687d4.png)

For the MM card area, the white background should not appear for an unpublished item for the feature card:
![image](https://user-images.githubusercontent.com/31222859/57801458-bd981e80-7721-11e9-8854-bb7ced0f6b5c.png)

If the MM card is empty, the styling is really off for just the feature card:
![image](https://user-images.githubusercontent.com/31222859/57801856-bcb3bc80-7722-11e9-9538-5dd2ade27533.png)

If both the MM feature and the MM feature card is empty, it should not show the teal bar at all:
![image](https://user-images.githubusercontent.com/31222859/57801687-3f884780-7722-11e9-9660-f54875c5302b.png)

**Comment by bryanpizzillo** [comment]
# Test Cases/URLs
**It should go without saying that all the following test cases should perform without a Drupal error occurring.**

## cgov_card_internal Tests
### /test/cards/bad-cards
http://ncigovcdode158.prod.acquia-sites.com/test/cards/bad-cards

I added content blocks above each scenario with a `<h2>` heading, I will refer to that as the "title" in each test below. It is not part of the card, and will always display.

* Two Item Row with Unpublished Page (TITLE: Unpublished Item)
   * Expectations:
      * Anon Users: No card should display
      * Authors+: The card to the unpublished page should appear
* Two Item Row with a cgov_card_internal pointing to bad reference (TITLE: Bad Item)
   * Expectations:
      * Anon Users: No card should display
      * Authors+: No card should display
* Two Item Row with a cgov_card_internal pointing to no page (TITLE: No Item)
   * Expectations:
      * Anon Users: No card should display
      * Authors+: No card should display

## Card Container Tests
Card Containers that are empty should not display any wrapper markup. (This is most notable in containers with headings or the multimedia row.)

I added content blocks above each scenario with a `<h2>` heading, I will refer to that as the "title" in each test below. It is not part of the card, and will always display.

### /test/cards/two-column
http://ncigovcdode158.prod.acquia-sites.com/test/cards/two-column
Tests a two-column container on a mini-landing
* A two-column container with an unpublished page (TITLE: Bad Card)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: The card & container should display
* A two-column container with no cards (TITLE: No Cards)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display

### /test/cards/two-column
http://ncigovcdode158.prod.acquia-sites.com/test/cards/two-column

Tests the Primary, Secondary, Guide Card and Multimedia Row containers on a Home/Landing

* A primary feature card container with an unpublished page (TITLE: Primary Row, Unpublished)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: The card & container should display. Heading on mobile "Primary Row, Unpub"
* A primary feature card container with no cards (TITLE: Primary Row, No item)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display
* A secondary feature card container with an unpublished page (TITLE: Secondary Row, Unpublished)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: The card & container should display.
* A secondary feature card container with no cards (TITLE: Secondary Row, No item)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display
* A guide row with nothing (TITLE: Empty Guide Row)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display
* A Multimedia row with an unpublished video and unpublished file (TITLE: MM Row, Both Unpub)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display
* A Multimedia row with no cards (TITLE: MM Row, Empty)
   * Expectations:
      * Anon Users: No container should display
      * Authors+: No container should display
