### ISSUE TITLE
Add no index to the syndicated content html

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1751]
Based on an email thread with Lakshmi and Kevin - where google is finding out syndicated pages, we need to add a `<meta name="robots" content="noindex">`  tag to the syndicated content pages (any content returned by the `cgov_syndication` module with the path `/node/{node}/syndication`).

**Comment by bkline** [comment]
Sure, I'll fold this into the PR I'll be creating for #792.

**Comment by bkline** [comment]
Just to confirm that the first comment overrides the implication of the title for this ticket, and we're _not_ adding the tag to the HHS syndication, right, @VictoriaSunNIH?

**Comment by VictoriaSunNIH** [comment]
Yes - we are adding the tag.  The tag is “noindex” for any syndicated content pages. Sorry if the title is unclear, feel free to update.

**Comment by bkline** [comment]
> Yes - we are adding the tag.

Looks like my request for clarification wasn't clear. 😃 The title implies we're adding this for _all_ syndicated content. The first comment seems to say we're only adding the tag for content at `/publishedcontent/syndication`, which would exclude the HHS syndication, right?

**Comment by VictoriaSunNIH** [comment]
@bkline - Any html generated by the route /publishedcontent/syndication should have the robots tag added to the head block.

**Comment by bkline** [comment]
Got it. Any objection if I change the first comment with the ticket description to bring it in line with this?
