### ISSUE TITLE
Migrate delta for containers in order to maintain list/card ordering

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1764]
We need to migrate delta from Percussion in for containers to maintain the order of the lists and cards.  The fields that need this are:
- field_citation
- field_related_resources
- field_recommended_content
- field_featured_posts
- field_selected_research
- field_cthp_cards
  - cgov_cthp_guide_card
- field_landing_contents
  - cgov_primary_feature_row
  - cgov_secondary_feature_row
  - cgov_guide_row
  - cgov_two_item_feature_row
- cgov_list

Examples (as of 5/20) of pages where related resources are not following the same order as cancer.gov:
- http://ncigovcdode118.prod.acquia-sites.com/espanol/cancer/naturaleza/que-es (last 2 bullets are switched)
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/understanding/statistics
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/causes-prevention/risk/substances
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/types/radiation-therapy
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/types/chemotherapy
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/types/immunotherapy
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/paying 
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/patient-safety
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/questions
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/questions

Examples where display order is incorrect for research pages:
- http://ncigovcdode118.prod.acquia-sites.com/about-cancer/causes-prevention/research
- http://ncigovcdode118.prod.acquia-sites.com/types/breast/research

**Comment by zhuomingao** [comment]
on ODE 166
