### ISSUE TITLE
All Content is missing from the about-nci/legislative/contact

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1765]
- All content is missing from this page:
  - http://ncigovcdode118.prod.acquia-sites.com/about-nci/legislative/contact

**Comment by zhuomingao** [comment]
this page in percussion does not have a body field, but has a content block in body slot and that is why the body is not migrated

**Comment by zhuomingao** [comment]
solution: In PROD percussion, change 1026859, 1026882 so that its content block in body slot becomes body field

**Comment by lburack** [comment]
Closing this issue. I've updated PROD to move the content block into the body of this page. This should no longer be an issue.
