### ISSUE TITLE
Validation for Site Sections

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#177]
This story is to create code to validate site sections. Related to issue #176.

[Validation Rules](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Vocabularies-Site-Sections#pretty-url):
* No capital letters
* Only allows 0-9, a-z, and - (dash)
* When preceded by the parent section's pretty URL path, the full alias must be unique within the site
   * This includes validating against any microsite (future requirement)
   * Note: will need to check if a page on the site already exists with this same pretty URL and lives within this parent section
   * Further refinements will need to be made to previous rule

**Comment by VictoriaSunNIH** [comment]
Closing this issue and combining with 175 (validation for pretty URL)
