### ISSUE TITLE
On the cancer.gov homepage, the words "homepage" should not appear above the primary feature card zone

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1771]
On the Cancer.gov HOMEPAGE ONLY - the words "homepage" should not appear above the primary feature card row.

**Don't Show This - Home Page above the row**:
![image](https://user-images.githubusercontent.com/31222859/58054683-51eef080-7b29-11e9-90d7-e380500a72ca.png)

However, on all other landing pages, that page title should appear (for example, on About Cancer or Cancer Research.

**Do Show This - About Cancer above the row**
![image](https://user-images.githubusercontent.com/31222859/58054697-603d0c80-7b29-11e9-9c03-b6a13bd5a403.png)

**Comment by BrendanBeltzNIH** [comment]
![image](https://user-images.githubusercontent.com/34315527/58110374-67155f00-7bbd-11e9-8aef-7b008e9d1c03.png)
