### ISSUE TITLE
When a MM feature card doesn't have an image, the background of the card does not line up with the featured MM item

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1772]
If I put a piece of content with no image associated to it in the MM Feature card area (to the right of the MM feature zone), the card does not align with the top of the MM feature zone.

![image](https://user-images.githubusercontent.com/31222859/58055711-a6e03600-7b2c-11e9-90ed-9aedebf2cbaa.png)

**Comment by BrendanBeltzNIH** [comment]
Sadly, this is the behavior on prod currently

**Comment by VictoriaSunNIH** [comment]
This is apparently a bug that's on prod now.  We can backlog this for future fix.

**Comment by andyvanavery31** [comment]
We no longer support these items due to Redesign.
