### ISSUE TITLE
Migration Issues with Blogs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1775]
Some bugs I noticed on the ODE for blogs yesterday:

- Blog series is not showing the Featured Posts in the right column
- Blog posts are not showing intro text (e.g. https://www-test-ac.cancer.gov/news-events/cancer-currents-blog/2019/kidney-cancer-immunotherapy-targeted-therapy-combination)

**Comment by amydugan** [comment]
@daquinohd - We entered this in the Migration project, but it appears some of these could be code related. Could you take a look, please?

**Comment by zhuomingao** [comment]
fixed 

see example http://ncigovcdode118.prod.acquia-sites.com/news-events/cancer-currents-blog

**Comment by zhuomingao** [comment]
https://www-blue-dev.cancer.gov/news-events/cancer-currents-blog/2019/kidney-cancer-immunotherapy-targeted-therapy-combination

has no intro text, this is false alarm
