### ISSUE TITLE
Add role for viewing unpublished content and revisions of content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1778]
There needs to be a role in the system that allows users to view unpublished content and view the  revisions of content on the front-end.  

This role should be called "Content Previewer".  The content previewer role has no connection to any other role in the system, other than the fact that they have to authenticate in (i.e. they get their own permissions)

**Comment by bryanpizzillo** [comment]
This was incorrectly labeled in PR #1801, which was pulled into a larger PR #1791
