### ISSUE TITLE
Blog categories are showing an empty URL for topic when migrated in

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1781]
On the migration ODE, blog categories are showing an empty URL for topic.

URL: https://www-test-ac.cancer.gov/news-events/cancer-currents-blog?topic=

topic seems to be empty for each category.

**Comment by daquinohd** [comment]
May not be related, but some categories are no longer showing Blog Posts that are tagged to that topic.

**Comment by daquinohd** [comment]
Category filter issue happens between 
`6c500e4 Load site sections from migration data` (topics not appearing) 
`cedcdd8 Feature/core prod check` (latest 'good' build where topics appear)
