### ISSUE TITLE
Image is missing even though it has all crops from grants-training/training

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1782]
- Image did not migrate properly (even though it had all of the crops in Percussion):
  - http://ncigovcdode118.prod.acquia-sites.com/grants-training/training

**Comment by zhuomingao** [comment]
on BLUE, image 1042056 NCI FYI Mobile App Thumb only has thumbnail and that in why it does not show since it is missing media image field
