### ISSUE TITLE
Shared Body field should use full html wysiwyg

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1806]
The body field is no longer pulling the proper wysiwyg. It should be the [full html wysiwyg](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields-WYSIWYG#full-html-used-for-body-content).
The body is a shared field so this impacts:
- blog posts
- cancer research list page
- event
- biography
- press release
- cancer center

Below screenshot is from a blog post, showing the intro text field is correct, but body field is missing all the toolbar options.
<img width="1056" alt="Screen Shot 2019-05-23 at 9 52 59 AM" src="https://user-images.githubusercontent.com/29731392/58258821-6c9bb200-7d41-11e9-8ce3-4eef3f6c7d3d.png">

**Comment by alifr** [comment]
Closes #1802 as well?

**Comment by lburack** [comment]
Yes @alifr. I closed out that issue.
