### ISSUE TITLE
Styling Issues on Cancer Types Landing Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1835]
Looking at the migration ODE, the A-Z List of Cancer Types landing page does not look like production. The leading/line height appears to be much tighter on the ODE (less vertical space between each `<li>`). 

ODE is on the left; prod is on the right:
<img width="1517" alt="Screen Shot 2019-05-29 at 1 10 04 PM" src="https://user-images.githubusercontent.com/29731392/58576831-2f3c9600-8213-11e9-9fe9-5c145875d20d.png">

**Comment by alifr** [comment]
After a quick glance I noticed a container has lost it's `rawHtml` class name which was adding margin to all the list items on this page
```
.rawHtml li {
    margin-top: 0.5em;
    margin-bottom: 0.5em;
}
```
It seems the markup has changed a bit on this page, but I'm not seeing this issue on the develop branch. Perhaps changes will make their way over soon?
