### ISSUE TITLE
When an infographic has no promotional image, and is embedded in content, it breaks the page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1842]
On Dev - when I embed an infographic that has no promotional crop associated with it and preview the page (or publish and try to view on the live site), the page will show "unexpected error occurred".

We should update the rule for this display so that it does not break the page.  If a promotional image is not set for the infographic, we should leave a blank space with the "view infographic" button so that users can tell they forgot to set a promo image for the infographic.

**Comment by BrendanBeltzNIH** [comment]
The issue was calls to the promotional image entity when it wasn't present. Wrapping it in an existence check conditional solved the crash. What to display in place of the promo image might be a bigger question and I'm punting that.
