### ISSUE TITLE
Media Link List Item Isn't Pulling Promotional Image Associated with the File

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1849]
If you add a file (via media link) to a list on either a home/landing or mini landing page, the promo image associated with the file does not display (yes, I checked that the promo image has the correct crops). If you add the override promo image to the media link list item, however, that will display on the page. 

The expected behavior is 
- if a file has a promotional image (with required crops), that image should appear if the file is added to a list as a media link. 
- if a file is added to a list as a media link, and an override promotional image is added, the override image should display.

For anyone who thinks files shouldn't be added to lists — per #1503 we decided to use external links for files in feature cards, but this did not include lists.

**Comment by arcepaul** [comment]
@lburack 
Can we please retest?  I was not able to recreate this issue locally.

**Comment by lburack** [comment]
Drupal gremlins strike again. This is now working... even though Michelle and I both experienced this issue last week. Closing this out as it's no longer a thing.
