### ISSUE TITLE
Output Page Metadata - SEO

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#185]
This story is to output SEO page metadata on cancer.gov

**User Story**
As a user, I would like to enter SEO metadata to boost my content in search engines.
* browser title
  * If browser title does not exist, use the short title from the content type
  * we need to append the Site Name to the browser title with a dash (e.g. National Cancer Institute for cancer.gov). Display would be "Browser Title - Site Name"
* metadescription
* search engine restrictions (if exclude from search is selected, this should output noindex nofollow.  e.g. `<META` NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">)

**Comment by adriancofie** [comment]
Pending resolution of Drupal test case bug that is preventing pipelines build.

**Comment by adriancofie** [comment]
http://ncigovcdode70.prod.acquia-sites.com/
