### ISSUE TITLE
Analytics: Prop25 returning no value

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1868]
Analytics page load: Prop25 – Release Date returning “no value” on the test environment

**Comment by daquinohd** [comment]
> Prop25 – Release Date not being set on Page Load. This pulls from a field in percussion
> currently. I’m seeing “no value” on the test environment. This may just be a data migration issue.

Verified that this is a content issue; closing.
