### ISSUE TITLE
Analytics: Issues with Blogs

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1870]
- Analytics click: Blogs (this can all be in one ticket)
  - No click event being fired when you click on a body link in a blog.
  - Clicks on glossified terms are firing glossified term analytics, but missing the customization for these links on blogs to also include prop66.
  - On archive section, expand and collapse are working as expected, but clicks on the actual links in the archive are not firing a click event.
  - Clicks on the prev/next navigation on the blog is not firing any click event.
  - Related Resources listed on blog pages are having the same prop44 value issue, but also are not accounting for the special values for these posts on blogs (as compared to the rest of the site). Should start with Blog_.

**Comment by daquinohd** [comment]
> No click event being fired when you click on a body link in a blog.
Working as expected.
> Clicks on glossified terms are firing glossified term analytics, but missing the customization for these links on blogs to also include prop66.
Fixed.
> On archive section, expand and collapse are working as expected, but clicks on the actual links in the archive are not firing a click event.
*wip*
> Clicks on the prev/next navigation on the blog is not firing any click event.
*wip*
> Related Resources listed on blog pages are having the same prop44 value issue, but also are not accounting for the special values for these posts on blogs (as compared to the rest of the site). Should start with Blog_.
*wip*
