### ISSUE TITLE
Mega Menu alignment is off - should be four columns

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1876]
The mega menu display is not correct. On both the dev and migration ODEs, the mega menu is only spanning 3 columns, when it should span 4.

Here's a screenshot from DEV:
<img width="1539" alt="Screen Shot 2019-06-03 at 3 17 07 PM" src="https://user-images.githubusercontent.com/29731392/58828198-e91c7380-8612-11e9-97dd-437848f1e2f7.png">

Here's a screenshot from PROD:
<img width="1519" alt="Screen Shot 2019-06-03 at 3 17 34 PM" src="https://user-images.githubusercontent.com/29731392/58828223-f46f9f00-8612-11e9-83a5-8c2f7c115545.png">

**Comment by BrendanBeltzNIH** [comment]
This is a thankless issue and is a good opportunity to redo the very simple structure of the desktop mobile menu internal items with flex-box, which is what it should have been to begin with when the scrollbar was removed.
