### ISSUE TITLE
Grants & Training Home/Landing Page - display issues on Latest Funding Announcements card

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1888]
On the Grants & Training home/landing page on the migration ODE 166, the Latest Funding Announcements card is not displaying as it does on prod
https://www.cancer.gov/grants-training
http://ncigovcdode166.prod.acquia-sites.com/grants-training

On prod, the entire card is white; on the ODE, the extra "whitespace" is teal.

Here's a screenshot of the ODE:
<img width="1273" alt="Screen_Shot_2019-06-04_at_2_07_22_PM" src="https://user-images.githubusercontent.com/29731392/58903108-93a79b80-86d2-11e9-84d4-f71ebe3774ca.png">

**Comment by BrendanBeltzNIH** [comment]
This is an issue with a missing rawHtml wrapper
