### ISSUE TITLE
News & Events home/landing page isn't displaying 2-column design correctly (English & Spanish)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1889]
Both the English and Spanish News & Events home/landing page is not displaying correctly on the migration ODE. The two columns should be side by side, there needs to be right and left padding (15px) on each `<div class="row card">` and `<div class="news-share">`, and the All NCI news link should appear at the bottom of the press release listing.

Compare prod (https://www.cancer.gov/news-events and https://www.cancer.gov/espanol/noticias) to the ODE, English screenshot below: 

![screencapture-ncigovcdode166-prod-acquia-sites-news-events-2019-06-04-14_22_53](https://user-images.githubusercontent.com/29731392/58905546-049d8200-86d8-11e9-91d0-f8e1f4cb065c.png)

**Comment by BrendanBeltzNIH** [comment]
I can't verify now. But, much like #1914, I believed this was a migration issue.

**Comment by BrendanBeltzNIH** [comment]
There is a single class missing on a container ('news'), all the column and card stylings are dependent on this. I'm gonna see if it's something we can add in hard or we need to conditionally add it.

**Comment by VictoriaSunNIH** [comment]
@lburack - rebuilt this on the ODE.  looks good to me: http://ncigovcdode193.prod.acquia-sites.com/news-events
