### ISSUE TITLE
Cancer Centers - Styling Issues

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1890]
Found some minor, low priority issues with the Cancer Center content type:

- If two separate phone numbers are provided, there should only be a single line break between the two lines (see screenshot comparison below)
- If a city and state are provided by the CMS user, a comma automatically appears between the two. There's an extra space between the city and the comma (see screenshot comparison below)
- On production, the state name is currently fully spelled out, but on the ODE, the state abbreviation displays. We should implement what's currently on the live site, so the full state name should display.

<img width="1675" alt="cancer-center-compare" src="https://user-images.githubusercontent.com/29731392/58913842-163c5500-86eb-11e9-8686-39c373952c58.png">

**Comment by arcepaul** [comment]
@lburack 
will add fixes for this to my PR that I have open right now (#1875 )
