### ISSUE TITLE
Some embedded images are not aligning correctly because of outer positioning div

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1904]
Since we have had to separate the positioning from sizes of images, the override styles for .cgh-staff that remove the extra margin at the top are not being honored.

BAD:
http://ncigovcdode118.prod.acquia-sites.com/research/key-initiatives/ras/spokes-funding
![Screen Shot 2019-06-05 at 7 40 21 PM](https://user-images.githubusercontent.com/11215649/58997261-c84a4e80-87c9-11e9-8948-569f36a36d09.png)

GOOD:
https://www.cancer.gov/research/key-initiatives/ras/spokes-funding
![Screen Shot 2019-06-05 at 7 41 07 PM](https://user-images.githubusercontent.com/11215649/58997285-e87a0d80-87c9-11e9-890d-1377b7e02aeb.png)

**Comment by arcepaul** [comment]
@lburack @VictoriaSunNIH @bryanpizzillo 
This can be solved via content entry.  It looks like these are supposed to be aligned left and not centered.  The margin doesn't exist for left and right aligned embedded images.

Updated ODE content: 
http://ncigovcdode118.prod.acquia-sites.com/research/key-initiatives/ras/spokes-funding

<img width="874" alt="Screen Shot 2019-06-06 at 10 42 06 AM" src="https://user-images.githubusercontent.com/45469809/59042026-b4453200-8847-11e9-88ec-e9f79b329157.png">

**Comment by VictoriaSunNIH** [comment]
@arcepaul - This is not a content issue.  This is an issue with the embeds for the article displays where no one looked at the containers that are targeting these sizes.
