### ISSUE TITLE
Migrate in Blog Topics Description Text

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1908]
Body content from the topic page for each category needs to be migrated in from Percussion to the description on each taxonomy term in Blog Topics in Drupal. 

See attached spreadsheet for topic and corresponding description.

[blog-topics-descriptions-for-migration.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/3262190/blog-topics-descriptions-for-migration.xlsx)

**Comment by zhuomingao** [comment]
[Archive.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/3262608/Archive.zip)

**Comment by zhuomingao** [comment]
in the zip is the two XML for blog topics and blog topics ES, can you please update the description ? I currently put DESCRIPTION GOES HERE as place holder.

**Comment by lburack** [comment]
@zhuomingao - here's the XML with the descriptions.
[blog-topics-lb.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/3278570/blog-topics-lb.zip)

**Comment by VictoriaSunNIH** [comment]
Looking good.
