### ISSUE TITLE
Missing Icons in Migrated Content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1910]
Missing Assets/Icons Issues:
- Email icon missing from GovDelivery callout (http://ncigovcdode118.prod.acquia-sites.com/research/key-initiatives/moonshot-cancer-initiative)
- Email icon is missing from “Get email updates” http://ncigovcdode118.prod.acquia-sites.com/news-events/events/social-media
- Buttons are all missing: http://ncigovcdode118.prod.acquia-sites.com/about-nci/organization/crs/research-initiatives/team-science-field-guide

**Comment by BrendanBeltzNIH** [comment]
This seems to be a mapping issue. I see references to nodes or percussion pages in the image sources.

**Comment by VictoriaSunNIH** [comment]
These will be manual updates to content to replace the location of publishedcontent to the new location in github
