### ISSUE TITLE
Funding Opportunities has the wrong background color for the icon

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1911]
- Icon should be white for Funding Opportunities: http://ncigovcdode118.prod.acquia-sites.com/research/key-initiatives/moonshot-cancer-initiative/implementation/patient-engagement

**Comment by BrendanBeltzNIH** [comment]
This is a content issue. The styles on that element are inline.

![image](https://user-images.githubusercontent.com/34315527/59056274-d3eb5300-8865-11e9-9d4b-f4f479f15d6b.png)

**Comment by VictoriaSunNIH** [comment]
This has been fixed.
