### ISSUE TITLE
Migrated Content - Missing/Incorrect Card Titles and Themes 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1912]
HP CTHPs – Statistics cards are not displaying CTHP Card Title and CTHP Card Theme
http://ncigovcdode176.prod.acquia-sites.com/types/breast/hp
http://ncigovcdode176.prod.acquia-sites.com/types/lung/hp

Patient & HP CTHPs — Some internal feature cards are not displaying the CTHP Card Title and CTHP Card Theme
http://ncigovcdode176.prod.acquia-sites.com/types/breast
http://ncigovcdode176.prod.acquia-sites.com/types/lung

Incorrect Card Theme Displaying (After Treatment Ends)
http://ncigovcdode176.prod.acquia-sites.com/types/breast

Statistics Cards are not displaying the CTHP Card TItle and CTHP Card Theme

**Comment by BrendanBeltzNIH** [comment]
Ok. This is a weird one. Another migration issue I think.

If you go into the editor for any of the offending pages and try to preview or save, you'll get an error that an entity reference doesn't exist. If you remove the offending block. The page will render correctly again. (I did this on the migration ODE for Anal and Breast cancer). So the bad reference seems to be breaking something in drupal's rendering. However, you'll note on Breast cancer that three of the cards have Title: Statistics and Theme:Treatment. So I'm guessing there is a mapping issue there too.

**Comment by VictoriaSunNIH** [comment]
These have all been fixed in the last migration code.  Closing as completed
