### ISSUE TITLE
Home/Landing pages are missing Featured Content at mobile/tablet

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1913]
All Home/Landing Pages (except Cancer Types/Tipos de cancer) are missing “Featured Content” (and “Contenido especial”) at mobile and tablet breakpoints on migrated content

**Comment by BrendanBeltzNIH** [comment]
Um, cancer types should never have it right?

It's not there on dev either. Looks like this one never made it through testing correctly. Taking a look now at the templates.

**Comment by BrendanBeltzNIH** [comment]
Yeah, this was because someone forgot to add 'content.' to 'field_container_heading' in the template.
