### ISSUE TITLE
View All NCI News link missing on media resources page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1914]
Missing “View All NCI News >” link (should display at bottom of page): http://ncigovcdode118.prod.acquia-sites.com/news-events/media-resources

**Comment by BrendanBeltzNIH** [comment]
So, I believe this is a mapping issue as well. That link should be inside of the container of that first column, but it's not being inserted there. You documented it yourselves in #1889. I noticed on that other ticket that the other contents of the second column also seemed to be mapping wrong, but didn't get a chance to describe further.
