### ISSUE TITLE
Video titles have incorrect styles on migrated content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1916]
Video title styling is incorrect and should appear as h4: 
o	http://ncigovcdode118.prod.acquia-sites.com/research/nci-role/spotlight/videos

**Comment by BrendanBeltzNIH** [comment]
The template has it as a p. That cleared testing. Is it supposed to be an h4 everywhere and I can just change the templates or is it only in this case and we have to figure out how to override based on page?

**Comment by lburack** [comment]
@BrendanBeltzNIH , yes, when video titles are provided, they should display as an h4 when selected.
