### ISSUE TITLE
Social Media Row on Home Page missing images

### ISSUE THREAD

**Issue by BrendanBeltzNIH** [NCIOCPL/cgov-digital-platform#1919]
The social media icons on the home page reference images stored at /PublishedContent/..., which no longer exists. These content references need to be changed to match the new image paths.

In addition, the icons for Youtube and GovDelivery are not a part of the new or old repo but are still referenced by that path. They may need to be added to the repo manually. Otherwise this seems to be a content or migration task (easy enough to edit post-migration, pre-release if it's just content since it's only 8 references across 2 pages).

**Comment by VictoriaSunNIH** [comment]
This will be a manual task to update.  Already documented in JIRA.
