### ISSUE TITLE
PDQ Listing Page styling is not right

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1934]
On migrated content ODE, the styling for PDQ Listing pages is incorrect. 

URL: http://ncigovcdode176.prod.acquia-sites.com/publications/pdq/information-summaries/adult-treatment

**On the ODE, every line has bullets.**
![image](https://user-images.githubusercontent.com/31222859/59140643-81498e00-896e-11e9-9f1e-2a7c8263fa6d.png)

**Prod looks like this, and this is the correct styling**
![image](https://user-images.githubusercontent.com/31222859/59140634-69720a00-896e-11e9-873e-0ffe2014dd20.png)

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack @bryanpizzillo 
Previously, this content was published as an article and not as a Mini Landing Page as it is here.  Is this correct?

**Comment by lburack** [comment]
@arcepaul – This is currently a General page in percussion. I've always had it as migrating to a mini landing in my content mapping spreadsheet. We've had some back and forth with migrating mini landings, so this could have been migrated as an Article on another ODE in the past, but I can't say for certain there.

**Comment by arcepaul** [comment]
@lburack
ok, should be able to move the styling over to mini-landing page styles pretty easily.
