### ISSUE TITLE
Blog Archives by Month are showing out of order

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1935]
On the migration ODE, the months under blog archives are showing in random orders (and not descending month order). 
http://ncigovcdode176.prod.acquia-sites.com/news-events/cancer-currents-blog

![image](https://user-images.githubusercontent.com/31222859/59140695-0634a780-896f-11e9-8190-9ce5943994bd.png)

**Comment by popkhadzeg** [comment]
Blog Archives for month now showing in correct order. Closing this issue
