### ISSUE TITLE
Search Bar is not spanning wide enough on microsites

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1949]
The search bar on microsites is not spanning the full length that it should.

On ODE:
http://ncigovcdode177.prod.acquia-sites.com/

![image](https://user-images.githubusercontent.com/31222859/59209751-0f459480-8b7a-11e9-85bc-9a7d8315ba2f.png)

On Prod:
![image](https://user-images.githubusercontent.com/31222859/59209808-2ab09f80-8b7a-11e9-9d3f-6ae2265d8db9.png)

**Comment by BrendanBeltzNIH** [comment]
This is because the rule for the width is conditional on a slot-item class on the search bar container, which is missing here.

**Comment by BrendanBeltzNIH** [comment]
Since the search form is a content block, this was a mistake in the content creation. There needs to be another wrapper ``` <div class="slot-item"> </div> ``` wrapping the block content from percussion.

**Comment by VictoriaSunNIH** [comment]
Updated the code.  Closing out -this will be a manual task
