### ISSUE TITLE
Output Page Metadata - Href Lang

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#195]
This story is to output href lang page metadata on cancer.gov

**User Story**
As the system, I would like to tell search engines that I have alternative content in other languages.
add a tag like:  

link rel="alternate" hreflang="es" href="http://es.example.com/foo" 

to the head block of the HTML page. This tells search engines how to find the content.

More information: https://support.google.com/webmasters/answer/189077?hl=en

**Comment by adriancofie** [comment]
Req: Ensure the original translations hreflang gets updated (cache invalidated)  when a new translation is created or an existing one updated.

**Comment by adriancofie** [comment]
Should be ready for review on all current builds.

**Comment by adriancofie** [comment]
http://ncigovcdode70.prod.acquia-sites.com/
