### ISSUE TITLE
View Infographic Overlay isn't correct

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1953]
When we migrated content, the VIEW INFOGRAPHIC overlay isn't correct. 
http://ncigovcdode176.prod.acquia-sites.com/research/areas/treatment/pmi-oncology

It should have caret arrow, not magnifying glass. It also seems the font size might be too small..? See comparison screenshot:
![Screen Shot 2019-06-07 at 10 02 42 PM](https://user-images.githubusercontent.com/29731392/59231897-46cf3380-8bb0-11e9-8df6-2496bb59f880.png)

**Comment by BrendanBeltzNIH** [comment]
This is an esoteric one. The correct styles exist, the correct markup exists, the correct sprites exist, nothing has changed in the code, and yet, it's different. It seems to be an issue with how the sprite build system treats %placeholders and @extend. This might be an issue in more place than one if that's the case and is a real head scratcher.
