### ISSUE TITLE
Extra spacing on mobile after lead image

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1954]
On all pages with a lead image, there's extra spacing after the image that is very apparent on mobile. Screenshot below is of http://ncigovcdode176.prod.acquia-sites.com/research/nci-role/intramural 
<img width="992" alt="spacing-on-mobile-comparison" src="https://user-images.githubusercontent.com/29731392/59232174-58650b00-8bb1-11e9-9024-a68cb16c8812.png">

**Comment by BrendanBeltzNIH** [comment]
The real takeaway here is that Bryan shouldn't do front end work. Which I'm sure he'd happily agree with.

![image](https://user-images.githubusercontent.com/34315527/59283131-0ca97480-8c38-11e9-8558-18a2a7333733.png)

Essentially, there are almost no media query (ie responsive) rules in the embedded-entity styles that were written. I'm going to add them in
