### ISSUE TITLE
Issues with Image caption

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1955]
Image captions are not displaying line breaks between lines of text. See screenshot below, comparing
http://ncigovcdode176.prod.acquia-sites.com/research/areas/public-health/sue-wharfe-lifestyle-exercise-nutrition-study
TO
https://www.cancer.gov/research/areas/public-health/sue-wharfe-lifestyle-exercise-nutrition-study
![image-captions-missing-line-breaks](https://user-images.githubusercontent.com/29731392/59232668-5b60fb00-8bb3-11e9-9665-8b8006cb82cf.png)

Additional pages like this include:
- http://ncigovcdode176.prod.acquia-sites.com/research/areas/childhood/philip-moss-improving-outcomes-nf1-neurofibromas
- http://ncigovcdode176.prod.acquia-sites.com/research/areas/clinical-trials/valerie-winston-clinical-trial-multiple-myeloma
- http://ncigovcdode176.prod.acquia-sites.com/about-nci/organization/ocpl/contact/peter-garrett-bio

**Comment by VictoriaSunNIH** [comment]
We'll have to allow p tags in the caption (change it to streamlined?)  This will introduce an old bug back that @BrendanBeltzNIH is already looking into (where an empty p tag appears when there is no caption).

**Comment by BrendanBeltzNIH** [comment]
The hope here is to create a twig function that takes a block of html and determines whether or not any textContent is present. To that end I am investigating the approach taken by the Drupal field html formatters that strip tags and see if a similar approach is feasible.
