### ISSUE TITLE
Buttons Missing

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1957]
Buttons are missing from pages across the site, like 
- all the [Patient Education Publications pages](http://ncigovcdode176.prod.acquia-sites.com/publications/patient-education) (e.g., http://ncigovcdode176.prod.acquia-sites.com/publications/patient-education/guide-for-parents — screenshot below)
- http://ncigovcdode176.prod.acquia-sites.com/publications/health-communication
- all Fact Book pages to "Download the Data" (e.g., http://ncigovcdode176.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg — screenshot below)

screenshot of [/publications/patient-education/guide-for-parents](http://ncigovcdode176.prod.acquia-sites.com/publications/patient-education/guide-for-parents):
<img width="450" alt="missing-buttons-screenshot" src="https://user-images.githubusercontent.com/29731392/59233769-d7f5d880-8bb7-11e9-8497-894c66cea330.png">

screenshot of [/about-nci/budget/fact-book/extramural-programs/rpg]
(http://ncigovcdode176.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg):
![factbook-missing-buttons-high-charts](https://user-images.githubusercontent.com/29731392/59233910-72eeb280-8bb8-11e9-947b-af1a9d745a3f.png)

**Comment by BrendanBeltzNIH** [comment]
I'm not sure if these are all the same issue. So I'm going through. I can tell you that most buttons are the result of a class. And at least in some of these cases, the markup is not migrating correctly. You can see below how the only button taht displays is the one that has the full markup with the button class 

![image](https://user-images.githubusercontent.com/34315527/59298265-2c509500-8c58-11e9-9ce8-4ebb10c72979.png)

**Comment by BrendanBeltzNIH** [comment]
The second example, on fact bok is the same but a bit more. Somehow the structure of the markup changed a bit too in the migration and I don't know why or if it's consequential.

Prod:

![image](https://user-images.githubusercontent.com/34315527/59298875-679f9380-8c59-11e9-87fd-9db1ce439f63.png)

Migration:

![image](https://user-images.githubusercontent.com/34315527/59298899-76864600-8c59-11e9-8288-b1100d49c2ee.png)

**Comment by BrendanBeltzNIH** [comment]
Best I can tell, this is a migration issue.

**Comment by VictoriaSunNIH** [comment]
The factbook buttons - we have to add the new location (update published content pointer).  I don't know about the first one though

**Comment by adriancofie** [comment]
@amydugan  As far as I know this working as of now:

**Comment by VictoriaSunNIH** [comment]
Looks like it is working! closing.
