### ISSUE TITLE
Search on mobile is not appearing correctly on migrated content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1959]
Search on mobile is not appearing correctly on migrated content:
![image](https://user-images.githubusercontent.com/31222859/59282942-b89e9000-8c37-11e9-95d5-12336253c5a7.png)

http://ncigovcdode176.prod.acquia-sites.com/

**Comment by BrendanBeltzNIH** [comment]
This is also a migration/content issue. The markup in the mobile-menu-bar is getting mangled

![image](https://user-images.githubusercontent.com/34315527/59300180-85bac300-8c5c-11e9-9cd2-09b23d272b6e.png)

**Comment by VictoriaSunNIH** [comment]
Ah yes - i fixed this in the raw html.  Closing this out as a manual task
