### ISSUE TITLE
Output Page Metadata - Internal NCI Search 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#196]
This story is to output Internal NCI page search page metadata on cancer.gov

**User Story**
As a user, I would like to correctly identify my content for DTM and Internal NCI Search.
* dcterms.type (NOTE: we need to make sure that qualtrics is using these new tags to determine where surveys appear, and not "data-cde-contenttype" as its target)

**Comment by adriancofie** [comment]
Pending resolution of Drupal test case bug that is preventing pipelines build.

**Comment by adriancofie** [comment]
http://ncigovcdode70.prod.acquia-sites.com/

**Comment by lburack** [comment]
I found the proper content type being outputted in the source. Marking this as passed.
