### ISSUE TITLE
Implement high charts 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1960]
We need to make high charts work and appear on the following pages (all in the https://www.cancer.gov/about-nci/budget/fact-book section of the site):

- https://www.cancer.gov/about-nci/budget/fact-book/data/program-structure
- https://www.cancer.gov/about-nci/budget/fact-book/data/extramural
- https://www.cancer.gov/about-nci/budget/fact-book/data/obligations
- https://www.cancer.gov/about-nci/budget/fact-book/data/management-fund
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/nrsa
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/bypass-appropriations
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/extramural-intramural-rms
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/comparison
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/aids-funding
- https://www.cancer.gov/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations

Also, can we verify that charts.js is the only file in published content that is needed for high charts?

**Comment by BrendanBeltzNIH** [comment]
This is a two parter, with one half needing to be done in percussion pre-migration (wrapping all script blocks in a function that only runs after jquery and other assets (like Chart.js) are loaded).

The second is of course making sure Chart is loaded.

**Comment by BrendanBeltzNIH** [comment]
I'm going to rewrite the wrapper in such a way that it will load on every page but only really load on specified pages in a whitelist (like the social media delighter). So I'll need a list of all the pages (all the pages) it appears on. Yeah, this isn't ideal, but we aren't adding JS files to individual pages anymore, so this needs to move into Common.js in a way that is minimally intrusive/heavy.

**Comment by BrendanBeltzNIH** [comment]
So, I've built the necessary pieces on the FE for this to work in Drupal. However, any script block calling Chart still needs to be manually edited to be wrapped as such:

Above:
```
const onChartLoaded = () => {
  const $ = window.jQuery;
```

EXISTING SCRIPT GOES HERE UNCHANGED

Below:
```
}
window.addEventListener('NCI.Chart.load', onChartLoaded);
```

This can't be done pre-migration because the custom event doesn't exist and the script blocks will never get executed. So we'll have to make the change pre-go-live.
