### ISSUE TITLE
Add design assets to github

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1963]
Please add the following design assets that are in PublishedContent to Github so we can reference it correctly in our raw html.

Design Assets Needed:
- /publishedcontent/images/images/design-elements/logos/nci-logo-full.svg
- /publishedcontent/Images/images/design-elements/icons/syndication.png
- /publishedcontent/images/images/design-elements/social-media/twitter/twitter-circle-icon.svg
- /publishedcontent/images/images/design-elements/social-media/facebook/facebook-circle-icon.svg
- /publishedcontent/images/images/design-elements/social-media/linkedin/linkedin-circle-icon.svg
- /publishedcontent/images/images/design-elements/social-media/instagram/instagram-circle-icon.svg
- /PublishedContent/images/images/design-elements/social-media/youtube/youtube-circle-icon.svg
- /PublishedContent/images/images/design-elements/social-media/gov-delivery/govdelivery-circle-icon.svg
- /PublishedContent/Images/research/key-initiatives/moonshot-cancer-initiative/moonshot-logo-article.png
- /publishedcontent/Images/about-nci/organization/crchd/inp/screen-to-save/connect/screen-to-save-tile.png 
- /PublishedContent/Images/images/design-elements/icons/gov-delivery-icon.png 
- /PublishedContent/Images/images/fact-book/general/Download_Data_button.png
- /PublishedContent/images/images/playlist-icon.jpg
- /publishedcontent/images/images/design-elements/icons/alert-banner-open-button.png
- /publishedcontent/images/images/design-elements/icons/alert-banner-close-button.png
- /publishedcontent/images/images/design-elements/logos/nsbd-logo-full.svg
- /publishedcontent/images/images/design-elements/logos/nci-logo-full-es.svg
- /publishedcontent/images/images/design-elements/logos/ccr-logo-full.svg

**Comment by BrendanBeltzNIH** [comment]
/publishedcontent/images/images/design-elements/logos/nci-logo-full.svg = /profiles/custom/cgov_site/themes/cgov/static/images/design-elements/logos/nci-logo-full.svg

**Comment by BrendanBeltzNIH** [comment]
Here, for testing, just add this to the source of a content block on some page. It's all the above paths in img elements.

```
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/logos/nci-logo-full.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/icons/syndication.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/twitter/twitter-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/facebook/facebook-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/linkedin/linkedin-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/instagram/instagram-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/youtube/youtube-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/social-media/gov-delivery/govdelivery-circle-icon.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/general/moonshot-logo-article.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/general/screen-to-save-tile.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/icons/gov-delivery-icon.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/general/Download_Data_button.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/icons/playlist-icon.jpg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/icons/alert-banner-open-button.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/icons/alert-banner-close-button.png">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/logos/nsbd-logo-full.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/logos/nci-logo-full-es.svg">
<img src="/profiles/custom/cgov_site/themes/cgov/static/images/design-elements/logos/ccr-logo-full.svg">
```
