### ISSUE TITLE
Microsites - Public Reuse needs to be an external link to C.gov

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1966]
Public reuse text for the microsites is pointing to /policies/copyright-reuse. Since the microsites are their own sites in Drupal, we need to make this an external link: https://www.cancer.gov/policies/copyright-reuse

This needs to be done for 
- Nano
- myPART
- NCI-CONNECT

**Comment by bryanpizzillo** [comment]
Go edit the content as a manual task.

**Comment by lburack** [comment]
Manual task is documented in OCECREATIV-3108.
