### ISSUE TITLE
Migration Issue: Some Blog Posts are showing the wrong author

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1968]
For some blog posts on ODE 176, the wrong author is appearing (the spanish version of "NCI Staff" is appearing.

http://ncigovcdode176.prod.acquia-sites.com/news-events/cancer-currents-blog

http://ncigovcdode176.prod.acquia-sites.com/news-events/cancer-currents-blog/2019/cancer-immunotherapy-investigating-side-effects

![image](https://user-images.githubusercontent.com/31222859/59305290-fadfc580-8c67-11e9-87f8-c612b6568098.png)

**Comment by bryanpizzillo** [comment]
The core issue is that `field_author` for `cgov_blog_post` does not support translations.
