### ISSUE TITLE
Output Page Metadata - Open Graph Tags

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#197]
This story is to output Open graph tags on cancer.gov

**User Story**
As a user, when I share content to social media, I would like share the social media metadata that I've selected from my content type
* og:title
  * Map to [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#short-title) field
* og:description
  * Map to [Meta-Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#meta-description)
* og:type
  * The system shall set a default value of "website" to og:type
  * The system shall allow the default value to be overridden by the page template
* og:url
  *  Based on meta property=og:url
  *  Use the Canonical URL (link rel="canonical") when the OpenGraph URL does not exist
* og:sitename
  * Based on the site the user is on (need to figure out how this works for non www microsites).  The site names should be:
      * Cancer.gov: National Cancer Institute
      * DCEG: Division of Cancer Epidemiology & Genetics - National Cancer Institute
  
* twitter:card
  * The system shall set a default value of "summary" to twitter:card
  * The system shall allow Twitter to use the OpenGraph metadata for similar Twitter metadata fields

**Comment by adriancofie** [comment]
Pending resolution of Drupal test case bug that is preventing pipelines build.

**Comment by adriancofie** [comment]
http://ncigovcdode70.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
This looks to be working (used the social media icons to test it) - however it looks like Facebook and Pinterest aren't using the og:title attribute to populate
