### ISSUE TITLE
Key Initiatives Mini Landing Page - Custom Links Should Migrate in as Override Descriptions to the List

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1973]
http://ncigovcdode176.prod.acquia-sites.com/research/key-initiatives is a mini landing page. Three of the five list items (items in thumbnail slot in percussion) are custom links:
- The RAS Initiative
- National Clinical Trials Network (NCTN)
- NCI Genomic Data Commons (GDC)

The Override Description of the custom link in percussion should be pulled into the Override List Description field in Drupal.

<img width="1084" alt="Screen_Shot_2019-06-12_at_5_13_57_PM" src="https://user-images.githubusercontent.com/29731392/59386816-a6a31700-8d35-11e9-9754-3b797ce3f187.png">

**Comment by zhuomingao** [comment]
fixed and xml in L drive
