### ISSUE TITLE
Redirects will need to be implemented with analytics

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1979]
Right now, when we redirect, we add a ?redirect=true parameter to the end of the URL.

We'll need to keep this behavior when we implement redirects.

Example: https://www.cancer.gov/mypart redirects to https://www.cancer.gov/nci/pediatric-adult-rare-tumor?redirect=true

**Comment by andyvanavery31** [comment]
Relates to the redirect issue contained within #2800

**Comment by andyvanavery31** [comment]
Determined that redirects are not being handled this way, so this ticket will be closed. #2800 will be prioritized.
