### ISSUE TITLE
Infographic in Home/Landing Page Multimedia Row should link to the infographic page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1981]
If an infographic is added to the multimedia row, clicking the item on the front-end should link users to the infographic page.  See functionality on current cancer.gov:
https://www.cancer.gov/research
https://www.cancer.gov/about-nci

This is not happening on dev or the migration ODE (http://ncigovcdode176.prod.acquia-sites.com/research) or

**Comment by BrendanBeltzNIH** [comment]
I think this might just be the way the url is being added in the template. Which would be ideal as it's a relatively quick fix.

**Comment by BrendanBeltzNIH** [comment]
Yeah, I fixed it. In the template, the url was getting pulled off the page, not the media item.
