### ISSUE TITLE
Amenities Map Raw HTML Content Block Missing from /about-nci/visit 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1987]
https://www.cancer.gov/about-nci/visit has a map that's added to the body slot of the page. It's a raw HTML content block — Amenities Map[#1703] (770043).

This is not appearing on http://ncigovcdode176.prod.acquia-sites.com/about-nci/visit. This page is a mini landing page so the map should be added as a raw html block.

**Comment by zhuomingao** [comment]
fixed
