### ISSUE TITLE
Issues with Migrated Images

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1988]
Images on the following pages did not seem to migrate in correctly. These pages are used in lists on mini landing pages, so the images are not appearing.

http://ncigovcdode176.prod.acquia-sites.com/about-cancer/causes-prevention/research
- this page is in the list on http://ncigovcdode176.prod.acquia-sites.com/about-cancer/causes-prevention
- image is: Checking Mole on Shoulder (Thumb Only)

http://ncigovcdode176.prod.acquia-sites.com/about-cancer/treatment/clinical-trials 
- this page is in the list on http://ncigovcdode176.prod.acquia-sites.com/about-cancer/treatment
- image is: media:cgov_image:b61f9b92-3bee-400e-ac32-ae46452a576a 
The same image is used in Spanish, which appeared correctly on http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento for "[Información sobre estudios clínicos para pacientes y personas a cargo de su cuidado](http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/estudios-clinicos)"

Cancer Prevention Overview (PDQ®) 
- this page is in the list on http://ncigovcdode176.prod.acquia-sites.com/about-cancer/causes-prevention
- in percussion, this is a custom link. The override title, override description, and image should be pulled in as the overrides in the list on the mini landing page.

**Comment by zhuomingao** [comment]
fixed by adding image_promotional to inline link
