### ISSUE TITLE
Spanish Patient CTHPs say 'OVERVIEW' when they should say 'ASPECTOS GENERALES"

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1991]
On the Spanish Patient CTHPs, the first card title says "Overview", but it should migrate in with the title "Aspectos Generales"

Example URLs:
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/piel VERSUS [cancer.gov/espanol/tipos/piel](https://www.cancer.gov/espanol/tipos/piel)
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/pulmon VERSUS [/espanol/tipos/pulmon](https://www.cancer.gov/espanol/tipos/pulmon)

<img width="1223" alt="Screen Shot 2019-06-14 at 11 19 13 PM" src="https://user-images.githubusercontent.com/29731392/59546407-d7807900-8efa-11e9-8879-7be0e58d80f6.png">

**Comment by zhuomingao** [comment]
fixed
