### ISSUE TITLE
Infographic Missing

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1992]
NCI National Clinical Trials Network Structure infographic is missing from http://ncigovcdode176.prod.acquia-sites.com/research/areas/clinical-trials/nctn. The infographic has been migrated into Drupal, but is not appearing on the page, as it does on https://www.cancer.gov/research/areas/clinical-trials/nctn and https://www-blue-dev.cancer.gov/research/areas/clinical-trials/nctn

<img width="1657" alt="Screen_Shot_2019-06-14_at_11_33_20_PM" src="https://user-images.githubusercontent.com/29731392/59546529-f2ec8380-8efc-11e9-91a4-8b951d196cf2.png">

Another example of an missing infographic: http://ncigovcdode176.prod.acquia-sites.com/about-nci/budget/fact-book VS
https://www.cancer.gov/about-nci/budget/fact-book

**Comment by adriancofie** [comment]
@VictoriaSunNIH Will push a fix for this today.

**Comment by adriancofie** [comment]
Issue 1) has been resolved as mentioned by #2020 :  http://ncigovcdode176.prod.acquia-sites.com/research/areas/clinical-trials/nctn

**Comment by lburack** [comment]
FYI - The Fact Book infographic should have never been in the /images folder; it's page-level content and should be added to a proper site section. I moved the infographic to the Fact Book folder on prod so this shouldn't be an issue for migration anymore: 
[/about-nci/budget/fact-book/budget-glance-infographic](https://www.cancer.gov/about-nci/budget/fact-book/budget-glance-infographic)
