### ISSUE TITLE
Section Menu (the "tongue") is not appearing on blogs at mobile breakpoints

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1993]
On all blog series and posts, the section menu (aka "the tongue") is missing at tablet and mobile breakpoints.

Examples include:
- http://ncigovcdode176.prod.acquia-sites.com/research/key-initiatives/ras/ras-central/blog and all subsequent blog posts
- http://ncigovcdode176.prod.acquia-sites.com/about-nci/organization/ccg/blog and all subsequent blog posts
- http://ncigovcdode176.prod.acquia-sites.com/about-nci/organization/crchd/blog and all subsequent blog posts
-http://ncigovcdode176.prod.acquia-sites.com/news-events/cancer-currents-blog and all subsequent blog posts
- http://ncigovcdode176.prod.acquia-sites.com/espanol/noticias/temas-y-relatos-blog and all subsequent blog posts

Left is live site; right is ODE 176:
<img width="1033" alt="Screen Shot 2019-06-14 at 11 46 57 PM" src="https://user-images.githubusercontent.com/29731392/59546617-ccc7e300-8efe-11e9-810c-29b91ffafa58.png">

**Comment by VictoriaSunNIH** [comment]
Not sure what we will do about this one...needs more discussion..

**Comment by BrendanBeltzNIH** [comment]
Looks like the section nav was just never added to the page templates for blog posts and blog series.
