### ISSUE TITLE
NCI's Role in Cancer Research (Article) is not migrating over with syndication checked

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1994]
NCI's Role in Cancer Research is an Article page. It displays the syndication message at the bottom of the page on [blue](https://www-blue-dev.cancer.gov/research/nci-role) and [prod](https://www.cancer.gov/research/nci-role/)
but it's not getting migrated in on http://ncigovcdode176.prod.acquia-sites.com/research/nci-role

<img width="1653" alt="Screen_Shot_2019-06-15_at_11_29_13_AM" src="https://user-images.githubusercontent.com/29731392/59553290-07626780-8f61-11e9-9e83-a74c3ce8155f.png">

**Comment by zhuomingao** [comment]
so we will not migrate any Spanish syndicate or keyword

**Comment by lburack** [comment]
This has been updated on the new ODE 176. Closing this out.
