### ISSUE TITLE
Spanish CTHPs (Patient and HP) say 'RESEARCH' when they should say 'INVESTIGACIÓN'

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2000]
Example URLs:
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/vejiga
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/vejiga/pro
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/seno
http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/seno/pro

Example Screenshot:
![image](https://user-images.githubusercontent.com/28450779/59557872-e0cd1c80-8fb2-11e9-989f-4364851148ad.png)

**Comment by zhuomingao** [comment]
fixed
