### ISSUE TITLE
Inline Images with links are not being migrated in

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2003]
The call out box image is missing on this page http://ncigovcdode176.prod.acquia-sites.com/research/areas/clinical-trials 

We have a problem with inline images that are linked not showing.  Here's another example on a microsite:
http://ncigovcdode176.prod.acquia-sites.com/sites/nano/about/factsheet

**Comment by VictoriaSunNIH** [comment]
this is a migration issue

**Comment by adriancofie** [comment]
Embedded-ception issue.

<p><a onclick="s.linkTrackVars='prop57,prop58,prop59,prop60'; s.prop57='Find a Clinical Trial Callout'; s.prop58='Find a Clinical Trial Image'; s.prop59='Callout'; s.prop60='www.cancer.gov' + location.pathname.toLowerCase(); s.tl(this,'o','Callout')" href="https://percussion.cancer.gov:443/Rhythmyx/assembler/render?sys_revision=12&amp;sys_context=0&amp;sys_authtype=0&amp;sys_siteid=305&amp;sys_variantid=2285&amp;sys_contentid=1052944" sys_contentid="1052944" inlinetype="rxhyperlink" sys_variantid="2285" sys_relationshipid="7309069" sys_siteid="305" rxinlineslot="103" sys_dependentid="1052944" sys_dependentvariantid="2285">

<img src="https://percussion.cancer.gov:443/Rhythmyx/assembler/render?sys_revision=3&amp;sys_context=0&amp;sys_authtype=0&amp;sys_siteid=305&amp;sys_variantid=1482&amp;sys_contentid=1090006" inlinetype="rximage" sys_relationshipid="7309068" sys_siteid="305" rxinlineslot="104" sys_dependentid="1090006" sys_dependentvariantid="1482" />


</a></p>
