### ISSUE TITLE
Create Intro Text Common Field

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#201]
This story is to create an [Intro Text](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#intro-text) common field. 

**User Story**
As a content author, I would like to the option add into text to a content page.

**Acceptance Criteria**
The Intro Text common field exists for use on content items and utilizes a streamlined WYSIWYG.

**Comment by blairlearn** [comment]
This has an implicit dependency on defining and creating the "streamlined" WYSIWYG editor configuration.

**Comment by nicolecrom** [comment]
Here is the information on streamline version so far:
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields-WYSIWYG#streamlined

**Comment by blairlearn** [comment]
`field_intro_text‎`

**Comment by blairlearn** [comment]
Thanks @nicolecrom. I've created ticket #207 for the streamlined editor configuration.
