### ISSUE TITLE
Caption missing from English image (but migrated in on Spanish translation of image)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2010]
The caption for the 'One Third of Precision Medicine Infographic' English image did not migrate. Its Spanish translation did migrate though.

The image is used on: http://ncigovcdode176.prod.acquia-sites.com/about-cancer/treatment/types/targeted-therapies

**Comment by adriancofie** [comment]
@lburack  @zhuomingao  There are two mirgrations rows with the same  percussion ID / image. The first one does NOT have a caption.


  <row id="1086243">
    <langcode>en</langcode>
    <name>One Third of Precision Medicine Infographic</name>
    <field_media_image>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-article.png</field_media_image>
    <field_override_img_thumbnail>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-thumb.png</field_override_img_thumbnail>
    <field_override_img_featured>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-feature-card.jpg</field_override_img_featured>
    <field_override_img_social_media>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-social-media.jpg</field_override_img_social_media>
    <field_accessible_version>silhouettes of people, a DNA strand, and a bottle of medication</field_accessible_version>
    <field_display_enlarge>0</field_display_enlarge>
    <field_credit>Credit: National Cancer Insitute</field_credit>
  </row>
  <row id="1086243">
    <langcode>en</langcode>
    <name>One Third of Precision Medicine Infographic (Different Caption for Targeted Therapy Page)</name>
    <field_media_image>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-article.png</field_media_image>
    <field_override_img_thumbnail>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-thumb.png</field_override_img_thumbnail>
    <field_override_img_featured>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-feature-card.jpg</field_override_img_featured>
    <field_override_img_social_media>https://www.cancer.gov/PublishedContent/Images/images/illustrations-graphics/precision-medicine-infographic-piece-social-media.jpg</field_override_img_social_media>
    <field_accessible_version>silhouettes of people, a DNA strand, and a bottle of medication</field_accessible_version>
    <field_caption><![CDATA[<div class="rxbodyfield">
<p>Targeted therapy treats cancer by targeting the changes in cancer cells that help them grow, divide, and spread.</p>
</div>]]></field_caption>
    <field_display_enlarge>0</field_display_enlarge>
    <field_credit>Credit: National Cancer Institute</field_credit>
  </row>
