### ISSUE TITLE
List Did Not Migrate Correctly on /espanol/cancer/manejo-del-cancer

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2011]
http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/manejo-del-cancer:
- List items are appearing twice
- Images are missing, as they are on [prod](https://www.cancer.gov/espanol/cancer/manejo-del-cancer)

Screenshot from ODE 176:
![Screen Shot 2019-06-16 at 3 10 45 PM](https://user-images.githubusercontent.com/29731392/59568456-f3923080-9048-11e9-982f-308a97fd8a64.png)

**Comment by zhuomingao** [comment]
fixed
