### ISSUE TITLE
Spanish PDQ Summaries Missing from Left Nav (prevención and detección)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2012]
The Spanish Overview PDQ summaries — Versión para pacientes — are missing from the left navigation:
- Aspectos generales de los exámenes de detección del cáncer (http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/deteccion/aspectos-generales-deteccion-paciente-pdq)
- Aspectos generales de la prevención del cáncer (http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/causas-prevencion/aspectos-generales-prevencion-paciente-pdq)

![Screen_Shot_2019-06-16_at_3_18_49_PM](https://user-images.githubusercontent.com/29731392/59568599-f4c45d00-904a-11e9-9b26-1dcca9b1fa0e.jpg)

![Screen_Shot_2019-06-16_at_3_14_20_PM](https://user-images.githubusercontent.com/29731392/59568602-f8f07a80-904a-11e9-8807-bc8ed6a8787a.jpg)

**Comment by zhuomingao** [comment]
fixed

**Comment by zhuomingao** [comment]
fixed in 6/17 refresh
