### ISSUE TITLE
Spanish Drugs Section (/espanol/cancer/tratamiento/medicamentos) Not Showing in Left Nav

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2013]
http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/medicamentos + 4 subpages are not showing in the left navigation. 

**Left is Prod; Right is ODE 176:**

![Screen Shot 2019-06-16 at 3 30 33 PM](https://user-images.githubusercontent.com/29731392/59568663-b7ac9a80-904b-11e9-8310-3cfd5ff0c29f.png)

**Comment by zhuomingao** [comment]
fixed

**Comment by zhuomingao** [comment]
fixed

**Comment by lburack** [comment]
This has been fixed on 176 now. Closing this out!
