### ISSUE TITLE
Update NCI Connect Delighter URL

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2018]
NCI-Connect should have a delighter on its main page.  Right now, it's showing cancer.gov because we haven't set the targeted URL to be correct. 

Please update the target URL of the NCI Connect delighter to be https://www.cancer.gov/rare-brain-spine-tumor

**Comment by BrendanBeltzNIH** [comment]
You're going to have to be a bit more specific since the rules you want to replace are a bit more extensive. Here they are for reference (you can probably find the old jira ticket with the requirements - based on the git blame it looks like WCMSFEQ-1092).

```
    {
        rule: /^\/nci\/rare-brain-spine-tumor/i,
        delighter: nciConnect,
        exclude: [
            /\/refer-participate/i,
            /\/blog/i,
            /^\/nci\/rare-brain-spine-tumor\/about/i,
            /\/living\/finished-treatment/i,
            /\/living\/coping/i,
            /\/living\/stories/i
        ]
    },
```

**Comment by BrendanBeltzNIH** [comment]
Let me step back, I think I'm making it sound more complicated. I'm just asking for verification that the first rule and the third exclusion should change, but everything else is still ok. I'm gonna assume so. Ignore the above except for reference for when things go wrong someday.

**Comment by VictoriaSunNIH** [comment]
@BrendanBeltzNIH  - yes, first rule, and 3rd exclusion should change. Thanks!
