### ISSUE TITLE
Spanish CGOV - Missing Images and Infographics

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2019]
Images are missing from Spanish pages. These got migrated into Drupal, but they are not appearing on the front-end. Some examples pages include:

- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/naturaleza/que-es
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/sobrellevar/supervivencia/infancia
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/tipos/radioterapia/haz-externo

- Infographic on http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/naturaleza/desigualdades

---
AC - Adding Videos from #2020

http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/tipos/inmunoterapia
VERSUS https://www.cancer.gov/espanol/cancer/tratamiento/tipos/inmunoterapia
• http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/naturaleza/desigualdades
VERSUS https://www.cancer.gov/espanol/cancer/naturaleza/desigualdades
• http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/estudios-clinicos/seguridad-paciente
• http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/estudios-clinicos/pago (edited)

**Comment by adriancofie** [comment]
@zhuomingao From the conversation this morning, to resolve this we need a mapping of Spanish image ID's to their new English ID in percussion. This should extend to any media items that have had their ID change in Drupal.

FYI @lburack
