### ISSUE TITLE
Pages Missing Videos

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2020]
Several pages don't have videos on them. The videos for all of these migrated into Drupal though, just not onto the page. Here’s a few for examples:

- http://ncigovcdode176.prod.acquia-sites.com/about-cancer/treatment/types/immunotherapy (compare to [prod](https://www.cancer.gov/about-cancer/treatment/types/immunotherapy) )
- http://ncigovcdode176.prod.acquia-sites.com/about-cancer/treatment/types/immunotherapy
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/tipos/inmunoterapia
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/naturaleza/desigualdades
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/estudios-clinicos/seguridad-paciente
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/tratamiento/estudios-clinicos/pago
- http://ncigovcdode176.prod.acquia-sites.com/about-cancer/managing-care/using-trusted-resources
- http://ncigovcdode176.prod.acquia-sites.com/espanol/cancer/manejo-del-cancer/uso-de-recursos-fidedignos

**Comment by adriancofie** [comment]
Added spanish videos to #2019 as they are the indentical issue. The overall video display mode mapping  issue was fixed in this one.
