### ISSUE TITLE
Update microsite mappings for cross linking

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2021]
For crosslinks from CancerGov to microsites, we need to update the mappings that are generated so that instead of pointing to /sites or /nci, the microsite URLs are:
- https://www.cancer.gov/nano
- https://www.cancer.gov/pediatric-adult-rare-tumor
- https://www.cancer.gov/rare-brain-spine-tumor

**Comment by zhuomingao** [comment]
[micrositeurl.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/3297766/micrositeurl.xlsx)

**Comment by lburack** [comment]
FWIW, https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative/implementation/patient-engagement is a page on Cgov that links to NCI-CONNECT and MyPART. 

Both of these links have been updated on http://ncigovcdode192.prod.acquia-sites.com/research/key-initiatives/moonshot-cancer-initiative/implementation/patient-engagement, to point to https://www.cancer.gov/rare-brain-spine-tumor and https://www.cancer.gov/pediatric-adult-rare-tumor. 

I'm not sure of a CGOV page that links to Nano, but I think these two updates are a good sign that this ticket is good :)
