### ISSUE TITLE
Inline feature card not migrating

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2023]
On this page, there is a missing inline feature card:
http://ncigovcdode178.prod.acquia-sites.com/pediatric-adult-rare-tumor/news/rare-tumor-clinics

Compare to prod:
http:s//www.cancer.gov/pediatric-adult-rare-tumor/news/rare-tumor-clinics

**Comment by adriancofie** [comment]
Per, @lburack this is an "inline feature (added through the wysiwyg) that points to a blog on cancer.gov"

Searched for similar items with the same variant and this was the only cross-site one.  Per the convo, we're treating this as a manual task.

**Comment by lburack** [comment]
Closing this out. https://tracker.nci.nih.gov/browse/OCECREATIV-3112 has been created for the manual cleanup during the content freeze.
