### ISSUE TITLE
IE font is wrong

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2025]
The font for the site when viewing in IE is wrong. Fix it please.
![image](https://user-images.githubusercontent.com/31222859/59625388-27339000-9107-11e9-801b-88b4c7fdbaa5.png)

**Comment by amydugan** [comment]
Per Bryan: If a font is served up from *.cancer.gov IE is ok.
www-dev-ac.cancer.gov has correct fonts
