### ISSUE TITLE
Feature Card on Mini Landing (two item row) Did Not Migrate

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2026]
http://ncigovcdode178.prod.acquia-sites.com/pediatric-adult-rare-tumor/rare-tumors

Currently, this topic page has a single item added to the Primary Feature Card Slot.  That should have migrated to the Two Item Feature Card Row in Drupal. It didn't. See screenshot below of PROD (left) versus ODE 178 (right) 

<img width="982" alt="Screen Shot 2019-06-17 at 1 48 16 PM" src="https://user-images.githubusercontent.com/29731392/59625423-3f0b1400-9107-11e9-8755-006039ca1075.png">

**Comment by zhuomingao** [comment]
fixed
