### ISSUE TITLE
Nano Microsite – List Did Not Migrate 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2027]
The compact list on this page did not migrate from Percussion (body slot) to Drupal
http://ncigovcdode177.prod.acquia-sites.com/nano/research/plan

Right is PROD; Left is ODE is 177:

<img width="1612" alt="Screen Shot 2019-06-17 at 1 59 49 PM" src="https://user-images.githubusercontent.com/29731392/59625862-5ac2ea00-9108-11e9-8b6d-219f2d1a7759.png">

**Comment by zhuomingao** [comment]
fixed

**Comment by amydugan** [comment]
Done in percussion pre-freeze
