### ISSUE TITLE
Spanish Home/Landing Pages are not migrating with dates (required field)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2033]
The Spanish home/landing are migrating without the date fields filled in. These are required fields. They should migrate filled in.

<img width="480" alt="Screen Shot 2019-06-18 at 9 55 05 AM" src="https://user-images.githubusercontent.com/29731392/59690286-2ce4b080-91af-11e9-968c-33b46c074d84.png">

**Comment by zhuomingao** [comment]
fixed on local
