### ISSUE TITLE
Create Content Series Tag Common Field

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#204]
This story is to create a [Content Series Tag](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#content-series-tag---may-exist-on-cancergov-but-not-used-there--pending-dceg-analysis-for-usage-for-now) common field. 

**User Story**
As a content author, I would like the option to tag items as a part of a content series on order to create dynamic lists.

**Acceptance Criteria**
The Content Series Tag common field exists for use on content pages.

**Comment by VictoriaSunNIH** [comment]
This may no longer be needed.  Needs more discussion

**Comment by VictoriaSunNIH** [comment]
I don't believe this is needed.  Closing until we need it
