### ISSUE TITLE
Cancer Center Institution Type and Region Drop Downs Showing Duplicate Values

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2042]
For the cancer center type, we are seeing duplicate values for the institution type and region drop downs. https://www-test-ac.cancer.gov/node/add/cgov_cancer_center

![image](https://user-images.githubusercontent.com/28450779/59764248-67128880-9269-11e9-92a0-e0fb48777619.png)

From Adrian: 
Those values are getting created  automatically with the cancer center module on install in
`function cgov_cancer_center_install() {`

Since we’re mapping directly to the percussion term ID’s and not the text, we need to remove them from the module install.

**Comment by adriancofie** [comment]
http://ncigovcdode200.prod.acquia-sites.com/node/add/cgov_cancer_center
