### ISSUE TITLE
green theme: The first accordion on mobile for the mobile menu is the wrong color

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2045]
![image](https://user-images.githubusercontent.com/31222859/59773421-93370500-927b-11e9-9ef2-1a0d6f97368c.png)

In the green theme, for the mobile menu, the first accordion is the wrong color.

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack 
Are there comps for this theme anywhere?  Are we sure that this isn't the color when that particular section is highlighted?

**Comment by VictoriaSunNIH** [comment]
Just kidding, i rechecked the comps. This is correct behavior.  closing this ticket.
