### ISSUE TITLE
All block content being migrated must have a description

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2051]
On 176 - I am seeing a number of block contents that were migrated in that do not have a description/title.

This is causing CTHP Block content, and other block content on the site to break the page on the front end.  All block content being migrated must have a description (its a required field).

Can you regenerate the XML to migrate in the block content, specifically for the following content IDs:
- 1014291
- 1014292
- 1101611
- 1038928
- 1016919
- 1036941
- 1042061
- 1115052
- 1115053
- 1041070
- 1043902
- 1115050
- 1115049

**Comment by zhuomingao** [comment]
fixed
