### ISSUE TITLE
Spanish Infographics embedded in content are not pointing to the correct url

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2052]
A Spanish infographic is embedded on a page.
When I click "Ver Infografía", the link is not including /espanol in the url path.

I saw this when testing #2019 (missing spanish images and infographics, as part of the migration scripts) on http://ncigovcdode192.prod.acquia-sites.com/espanol/cancer/naturaleza/desigualdades. That ODE is gone now, but once that's pulled onto 176, you should see it there.

**Comment by bryanpizzillo** [comment]
The two embedded infographic templates need to call the url generator and not reference alias directly.

* https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-medium.html.twig
* https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/templates/media/infographic/media--cgov-infographic--infographic-display-article-large.html.twig
