### ISSUE TITLE
Wrong List Type on NCI-CONNECT Rare Brain & Spine Tumor Stories

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2054]
http://ncigovcdode179.prod.acquia-sites.com/living/stories

The list type did not migrate correctly on this page:
- remove list title
- list with title, description, and image

Left is prod; Right is ODE:
![Screen Shot 2019-06-19 at 9 20 50 PM](https://user-images.githubusercontent.com/29731392/59811513-46cde280-92d8-11e9-9eed-46e0597fa08c.png)

**Comment by zhuomingao** [comment]
fixed
