### ISSUE TITLE
Admin toolbar User Logout button does not work with SSO.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2061]
The logout button in the Drupal menu under `username` > Log out does not currently work. You get immediately logged back in. In reality you are being logged out, detected as not logged in, routed to Okta (where your session is usually still live), routed back to Drupal, and logged back in automatically.

Solution is to point the logout button to the Okta logout URL so that you are logged out of Okta and break the loop.

**Testing**

- Log in to CMS
- Click logout button
- Expected: You land on the Okta log in page; logging back in again takes you to the Okta dashboard where you can click on the CMS name to return to the CMS

@bryanpizzillo's original:

> It keeps logging me back in.

**Comment by jfrank-nih** [comment]
I suspect that this might fix that: https://github.com/NCIOCPL/cgov-digital-platform/blob/7288bc5425f2b8d7f13429d132ffb7c913c090b0/docroot/profiles/custom/cgov_site/modules/custom/cgov_saml_auth_config/config/install/simplesamlphp_auth.settings.yml#L28
