### ISSUE TITLE
Incorrect Display for About NCI Mega Menu

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2065]
About NCI mega menu isn't displaying correctly on https://www-prod-acsf.cancer.gov:

<img width="1402" alt="Screen Shot 2019-06-21 at 1 10 20 PM" src="https://user-images.githubusercontent.com/29731392/59939557-59eec880-9426-11e9-859e-8c43fbdd0eb2.png">

Budget & Appropriations should be in the first column on the second line, where Legislative Activities is appearing, with Leg. Activities, Contracts, Careers, Visitor Information all shifting over a column. 
Here's a screenshot from PROD: 

<img width="1305" alt="Screen Shot 2019-06-21 at 1 14 44 PM" src="https://user-images.githubusercontent.com/29731392/59939659-a6d29f00-9426-11e9-8fed-46892d0fc92a.png">

**Comment by BrendanBeltzNIH** [comment]
#1876 introduced the error and just needs to be backed out. That's the problem with doing dev work on yaml versions of content blocks I guess.
