### ISSUE TITLE
Cancer Centers should migrate with dates selected

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2070]
All of the Cancer Centers have their dates in the drupal form, but the date display mode is not selected (as it is in percussion). These should all migrate with the proper dates checked, as they are in percussion.

Here's a screenshot of the form from https://www-cms.cancer.gov/research/nci-role/cancer-centers/find/uclajonsson
<img width="509" alt="Screen Shot 2019-06-21 at 8 27 46 PM" src="https://user-images.githubusercontent.com/29731392/59957096-241c0500-9463-11e9-9c62-261969e288d8.png">

**Comment by zhuomingao** [comment]
fixed
