### ISSUE TITLE
Bullets in raw html/content block are being ignored on the Subvenciones landing page

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2079]
https://prod-acsf.cancer.gov/espanol/subvenciones-capacitacion

The bullets in the content are being ignored so that bullets don't show up on the front end.

![image](https://user-images.githubusercontent.com/31222859/60029712-ab3dc880-966f-11e9-89e4-c5d39e2a1edb.png)

**Comment by BrendanBeltzNIH** [comment]
This is another rawhtml issue
