### ISSUE TITLE
Incorrect Tooltip for External Links

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2091]
The tooltip that's displaying for external links is totally not right. I have no idea where this came from. It provides incorrect guidance.

I'm seeing this on the following:
- CTHP External Feature Card
- External Feature cards on Mini Landing Page and Home/Landing Page

<img width="1050" alt="Screen Shot 2019-06-25 at 11 21 56 AM" src="https://user-images.githubusercontent.com/29731392/60111193-7eef7e00-973b-11e9-982c-6153aca374f9.png">

Field Name is: cgov_external_link

The tooltip should be:
> Enter the full URL starting with https://

Acceptance Criteria:
```gherkin
Scenario: adding an external link to cancer type homepage
Given Content creator is adding an external link via the External Feature Card paragraph to the cancer type homepage content type
When the content creator looks at the cgov_external_link field
Then they will see a field with the title "External Link"
	And that field will have a tooltip that reads "Enter the full URL starting with https://"
	And the field is required.
```
```gherkin
Scenario: adding an external link to home/landing page
Given Content creator is adding an external link via the External Feature Card paragraph within any card row or list to the home and landing page content type
When the content creator looks at the cgov_external_link field
Then they will see a field with the title "Featured Item URL"
	And that field will have a tooltip that reads "Enter the full URL starting with https://"
	And the field is required.
```
```gherkin
Scenario: adding an external link to mini landing page
Given Content creator is adding an external link via the External Feature Card paragraph within any card row or list to the mini landing page content type
When the content creator looks at the cgov_external_link field
Then they will see a field with the title "Featured Item URL"
	And that field will have a tooltip that reads "Enter the full URL starting with https://"
	And the field is required.
```

**Comment by suryatheja-muppalla** [comment]
@adriancofie  @VictoriaSunNIH 
<img width="545" alt="Screen Shot 2021-05-25 at 5 12 14 PM" src="https://user-images.githubusercontent.com/84407535/119687934-92b72980-be15-11eb-8653-85e7aad60f9b.png">
I have an approach that i can hide the below highlighted part of external link in the screenshot through CSS?

**Comment by alinai** [comment]
Looks good on test-acsf for CTHP, Mini Landing Page and Home/Landing page.
