### ISSUE TITLE
Better UX for embedded items

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2098]
Feedback from multiple training sessions - is there a way to get better icons than "E" for all of the embedded items?

**Comment by adriancofie** [comment]
Noticed as well; there is. We just need someone to create the desired icons and we can replace them.

**Comment by bryanpizzillo** [comment]
@adriancofie please test this. Make sure that the icon change does not flag a features difference.

**Comment by adriancofie** [comment]
I tested this using the latest patch available at : https://www.drupal.org/project/embed/issues/2824110
Screen shots / features export below:
<img width="931" alt="Screen Shot 2019-06-27 at 9 38 22 PM" src="https://user-images.githubusercontent.com/38888889/60459400-10b12c80-9c0f-11e9-99da-8e8fad687d07.png">
<img width="836" alt="Screen Shot 2019-06-27 at 2 31 52 PM" src="https://user-images.githubusercontent.com/38888889/60459436-2de5fb00-9c0f-11e9-9b86-3a634d43f067.png">
<img width="907" alt="Screen Shot 2019-06-27 at 9 41 22 PM" src="https://user-images.githubusercontent.com/38888889/60459445-33dbdc00-9c0f-11e9-8b71-9fa7e53be77b.png">
<img width="1054" alt="Screen Shot 2019-06-26 at 3 26 33 PM" src="https://user-images.githubusercontent.com/38888889/60459461-3dfdda80-9c0f-11e9-86b0-63981c90e8d3.png">

**Comment by mworrest** [comment]
Here are the UI icons for the WYSIWYG. 

![content-block-icon](https://user-images.githubusercontent.com/4921685/60545529-4cb8c000-9ce9-11e9-9523-952b20c77578.png)
![featured-content-icon](https://user-images.githubusercontent.com/4921685/60545530-4cb8c000-9ce9-11e9-9e81-2d90857c5cb9.png)
![image-icon](https://user-images.githubusercontent.com/4921685/60545531-4cb8c000-9ce9-11e9-88b5-1eb38fd042dc.png)
![infographic-icon](https://user-images.githubusercontent.com/4921685/60545533-4d515680-9ce9-11e9-9b48-a5e37d039d31.png)
![video-icon](https://user-images.githubusercontent.com/4921685/60545534-4d515680-9ce9-11e9-87a4-5839844a1e71.png)

**Comment by bryanpizzillo** [comment]
So I am running into an issue where when I install the patch 28 all permissions for most roles disappear. Obviously the admin user has no issues, but any other role loses the menu bar and, well, the ability to do anything.
