### ISSUE TITLE
Syndication Keywords Should Not Have a Character Limit

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2107]
I went to edit: http://ncigovcdode209.prod.acquia-sites.com/about-cancer/treatment/types/immunotherapy/bio-therapies-fact-sheet

When I went to save the page, I got an error that keywords cannot be longer than 128 characters.
<img width="740" alt="Screen Shot 2019-06-26 at 8 06 29 PM" src="https://user-images.githubusercontent.com/29731392/60224032-d3cfe900-984e-11e9-8f0a-35e362ac9057.png">

HHS Syndication Keywords should not have a character limit.

**Comment by bryanpizzillo** [comment]
We are going to limit this to 300 characters which should be more than enough for the problem pages.
