### ISSUE TITLE
Blogs - Featured Posts should pull 'card title', with fallback to browser title

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2114]
The right rail Featured Posts on blogs used to pull the short title. But we killed the short title, and now are pulling the page title so what's showing on ODEs does not match PROD. 

I would suggest Featured Posts displays the card title of the blog post.
If there's no card title, then display the browser title.

PROD:
<img width="275" alt="Screen Shot 2019-06-27 at 10 36 11 PM" src="https://user-images.githubusercontent.com/29731392/60313156-01d72b00-992c-11e9-85c2-b6b2e09a0a5c.png">

[ODE](http://ncigovcdode210.prod.acquia-sites.com/news-events/cancer-currents-blog)
<img width="275" alt="Screen Shot 2019-06-27 at 10 36 16 PM" src="https://user-images.githubusercontent.com/29731392/60313157-069bdf00-992c-11e9-9df2-7fd313e135d9.png">

**Comment by adriancofie** [comment]
The ask is a bit unclear on this one.

Currently the logic is using the node **title** field:
"The Childhood Cancer Data Initiative: Why Data Sharing Is Essential to Progress"

The  old "PROD" values in the screenshot seem to align with the **field_browser_title.**
"The Childhood Cancer Data Initiative: Sharing for Progress"

The proposed **field_card title** would result in the following:  
"Why Sharing Childhood Cancer Data Is Essential"


Attached is what it would look like using **field_card_title** by default, and falling back to **field_browser_title**.
<img width="287" alt="Screen Shot 2019-08-05 at 9 08 18 PM" src="https://user-images.githubusercontent.com/38888889/62504153-3361d280-b7c5-11e9-9ea4-7b3609cfb733.png">

Which specific field listed should it default to and fall back to?

**Comment by lburack** [comment]
Yes @adriancofie - since we took away the short title as part of the migration, the titles may not match exactly. But the rule for Featured Posts:
- display field_card_title
- if card title is blank, display field_browser_title

**Comment by blairlearn** [comment]
Merged in #2298
