### ISSUE TITLE
For all Microsites the color of the Social Media Icons on the footer are appearing different and the hover color is not appearing on hover.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2118]
For all three Microsites,  the color of the Social Media Icons on the footer are appearing different from the comps, and the hover color is not appearing on hover. 

We need to update each of the themes for the icons to match what is expected.

Please check against the spreadsheets for the following tickets to verify the correct color:
Blue: https://github.com/NCIOCPL/cgov-digital-platform/issues/818
Purple: https://github.com/NCIOCPL/cgov-digital-platform/issues/817
Green: https://github.com/NCIOCPL/cgov-digital-platform/issues/909

**Comment by bennettcc** [comment]
MVP1 launched yesterday - ticket no longer needed
