### ISSUE TITLE
PDQ Summaries are showing the same browser title for HP and Patient summaries

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2125]
PDQs have the same browser title for patient and HP (which is bad for SEO.  browser titles should be different). This is because browser title is being populated by short title from CDR instead of the page title, which actually is different.  However, the browser title is being used on CTHPs because it is the shorter one, so we cant just have browser title be populated with page title.  

Can we get a list of all the Display Elements and what they map to in one place for CDR/CancerGov front end so we can verify the list?

https://www.cancer.gov/types/lymphoma/patient/adult-hodgkin-treatment-pdq
* **H1 Page Title:** Adult Hodgkin Lymphoma Treatment (PDQ®)–Patient Version
* **Browser Metatitle:** Adult Hodgkin Lymphoma Treatment (PDQ®)–Patient Version (same as H1)
* **Card Title:** Adult Hodgkin Lymphoma Treatment  
* **cgov_list Title:** Adult Hodgkin Lymphoma Treatment (PDQ®)–Patient Version (same as H1)
* **Related Pages List Title (Related Resources):** Adult Hodgkin Lymphoma Treatment (PDQ®)–Patient Version (same as H1)
* **CTHP Guide Card PDQ Link:** Adult Hodgkin Lymphoma Treatment
* **CTHP Guide Card More Info:** I believe it's the H1, but it doesn't matter b/c we use the Override Title
* Research Card (?): N/A (I would assume it would be the list title, but PDQ summaries will never be pulled in here so who cares)
* The other guide card on CTHP, or is that just HTML? - it's just HTML

https://www.cancer.gov/types/ovarian/hp/ovarian-epithelial-treatment-pdq
* **H1 Page Title:** Ovarian Epithelial, Fallopian Tube, and Primary Peritoneal Cancer Treatment (PDQ®)–Health Professional Version
* **Browser Metatitle:** Ovarian Epithelial, Fallopian Tube, and Primary Peritoneal Cancer Treatment (PDQ®)–Health Professional Version (same as H1)
* **Card Title:** Ovarian Epithelial, Fallopian, & Peritoneal Cancer Treatment
* **cgov_list Title:** Ovarian Epithelial, Fallopian Tube, and Primary Peritoneal Cancer Treatment (PDQ®)–Health Professional Version (same as H1)
* **Related Pages List Title (Related Resources):** Ovarian Epithelial, Fallopian Tube, and Primary Peritoneal Cancer Treatment (PDQ®)–Health Professional Version (same as H1)
* **CTHP Guide Card PDQ Link:** Ovarian Epithelial, Fallopian, & Peritoneal Cancer Treatment
* **CTHP Guide Card More Info:** I believe it's the H1, but it doesn't matter b/c we use the Override Title
* Research Card (?): N/A (I would assume it would be the list title, but PDQ summaries will never be pulled in here so who cares)

**Comment by lburack** [comment]
I filled this out for you @bryanpizzillo. Stop yelling at me.
