### ISSUE TITLE
Microsite: The "Join an NCI-CONNECT Study" delighter does not appear on a page

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2133]
The "Join an NCI-CONNECT Study" delighter does not appear on 
https://www-prod-acsf.cancer.gov/rare-brain-spine-tumor/tumors/about-cns-tumors

It does appear on Prod (https://www.cancer.gov/nci/rare-brain-spine-tumor/tumors/about-cns-tumors)

Screen-shot for Prod:
![image](https://user-images.githubusercontent.com/28455973/60460633-499ed080-9c12-11e9-9e79-38e65b8b3fe2.png)

**Comment by BrendanBeltzNIH** [comment]
The fix is super simple. A line in the rules for where the delighter shows needs to be updated to be more specific. `/\/about/i,` can be replaced with `/^\/rare-brain-spine-tumor\/about/i` to restore the correct functionality.
