### ISSUE TITLE
DCEG Events - times did not migrate correct

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2135]
Events for DCEG migrated in with the incorrect times. 
Left is Prod; Right is ODE 216:

![Screen Shot 2019-07-01 at 4 25 27 PM](https://user-images.githubusercontent.com/29731392/60465709-c7b5a400-9c1f-11e9-9a4d-92c17b192747.png)

**Comment by zhuomingao** [comment]
in XML it is correct time, 10:30 and 11:30, so the Drupal loads the time not as east timezone but UTC

**Comment by zhuomingao** [comment]
fixed using time offset in L drive
