### ISSUE TITLE
Biography Migration Issues

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2136]
There are several fields which are not migrating properly.

- The Campus field on Drupal should have the content from Address Line 1 in Percussion
- The Organization 1 field in Drupal should have the content from Division in Percussion. Currently it is filled with content from Organization (NCI)
- If a biography had information for Journalists slotted in in Percussion, the Information for Journalists box should be set to "Display" on Drupal

**Comment by zhuomingao** [comment]
campus is taxonomy

**Comment by zhuomingao** [comment]
The underlying problem for campus is due to code loaded bio campus duplicately, ticket is created: https://github.com/NCIOCPL/cgov-digital-platform/issues/2143 to fix that.
