### ISSUE TITLE
DCEG Event Did Not Migrate 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2138]
This event is currently in the upcoming Events listing for DCEG, but I'm not able to find it on ODE 216

https://dceg.cancer.gov/news-events/events/2019/dceg-seminar-lajous

**Comment by zhuomingao** [comment]
this page is not in the content mapping sheet

**Comment by lburack** [comment]
Okay @zhuomingao . @goldenec is going to ask you for a report of new content to ensure everything gets migrated in.
