### ISSUE TITLE
PDFs Not Opening in Browser

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2139]
This issue came in from Lakshmi:

URL -  https://www-prod-acsf.cancer.gov/about-nci/budget/congressional-justification
In Chrome I noticed that the live and prod test site open PDFs differently. On the live site, it automatically opens the PDF in the browser when I click on the PDF link. On the new site, it automatically downloads a pdf file that I can then open.
 
Is this expected behavior?

**Comment by bryanpizzillo** [comment]
This is related to https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php#L147.  

This sets the header to `Content-Disposition: attachment; filename="<filename>"`. Content-Disposition: attachment forces the browser to download.  

It should be noted that the Content-Type header must be set to the mime type of the file.
