### ISSUE TITLE
Build out Dictionary API 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#214]
This story is to build out the Dictionary API for Cancer Terms and Genetics Terms and Autosuggest.

**Comment by sarinapadilla** [comment]
The Dictionary API will implemented similarly to the R4R, Best Bets, and Sitewide Search APIs. The API will be built in .NET Core 2.0 and will integrate with Elasticsearch. It will also include a Swagger interface.

Program.cs and Startup.cs will look similar to the other APIs...I won't get into those.

As for controllers, the Dictionary API will need three routes: one for GetTerm, one for Search, and one for SearchSuggest. Each of these routes will take in query parameters that are then passed on to the TermQueryService 

1) The GetTermController (route "getterm") will accept four query parameters: termId, dictionary, language, and audience.
2) The SearchController (route "search") will accept five query parameters: searchText, searchType, offset, numResults, language, and dictionary.
3) The SearchSuggestController (route "searchsuggest") will accept four query parameters: searchText, searchType, language, and dictionary.
	
There will be an ITermQueryService interface with an asynchronous methods for GetTerm, SearchTerms, and SearchSuggestTerms.
1) The GetTerm method will accept a TermQuery object, build the query using this object, and return a TermReturn.
2) The SearchTerms method will accept a SearchQuery object, build the query using this object, and return a SearchReturn.
3) The SuggestReturn method will accept a SuggestQuery object, build the query using this object, and return a SuggestReturn.

An ESTermQueryBase will have methods to build the query for Elasticsearch using the given TermQuery, SearchQuery, or SuggestQuery object(s).

The ESTermQueryService implementation of the ITermQueryService will query the ElasticClient using the given parameters for each implemented query method from above.

The required models are outlined in the attached YAML file.

**Comment by VictoriaSunNIH** [comment]
Closing this out as we should open new tickets with our new implementation plan based on conversations in 10/2019
