### ISSUE TITLE
DCEG  - Files did not migrate

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2142]
The file metadata migrated, but the actual files did not. 

http://ncigovcdode216.prod.acquia-sites.com/media/303435/edit?destination=/admin/content/media

![image](https://user-images.githubusercontent.com/39384914/60532886-55e76400-9ccc-11e9-9127-a5c8a093bd94.png)

**Comment by zhuomingao** [comment]
fixed
