### ISSUE TITLE
Mobile (Android)- The accordions are not displaying on android when hamburger menu is clicked.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2144]
The accordions are not displaying on android when hamburger menu is clicked.  For NCI-CONNECT it appears on load and then moves towards right. The linkback is not center aligned for Micro-sites.

![image](https://user-images.githubusercontent.com/28455973/60540177-8d5e0c80-9cdc-11e9-9339-77bccd365b0b.png)

![image](https://user-images.githubusercontent.com/28455973/60542944-1bd58c80-9ce3-11e9-81da-8fcfd03d87ed.png)

**Comment by BrendanBeltzNIH** [comment]
This is actually on all pages. Paul noticed the device width was being set differently, which has an affect on fixed elements.

replacing `<meta name="viewport" content="width=device-width, initial-scale=1.0">` with `<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1, minimum-scale=1">` fixes it

**Comment by alinai** [comment]
Entered https://github.com/NCIOCPL/cgov-digital-platform/issues/2305 for the link back alignment issue on Mobile (androids)

**Comment by blairlearn** [comment]
Merged in #2300.
