### ISSUE TITLE
Images with null value in the database are not getting empty alt attribute set

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2157]
If a user saved an image through the UI, it will get an empty string for the alt text, and Drupal will output an empty alt tag. Migrated content was migrated in with database NULLs instead of empty strings. If the database has a null value, Drupal will NOT output an empty alt tag.

**Comment by bryanpizzillo** [comment]
I wish there were some examples here. I am trying to find which images specifically are missing their alt tags.
