### ISSUE TITLE
The h3 title in a call out box is not getting hover color and is getting an underline on hover

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2160]
The h3 title in a call out box is not getting hover color and is getting an underline on hover
url: https://www-prod-acsf.cancer.gov/research/key-initiatives

![image](https://user-images.githubusercontent.com/28455973/60748361-31ed8200-9f5b-11e9-9659-7aef210696b3.png)

**Comment by andyvanavery31** [comment]
No longer an issue.
