### ISSUE TITLE
Build Out Demo Site - Microsite

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#217]
This story is to create a [Microsite](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Microsites-Layout-(not-www.cancer.gov)) buildout (demo site).

[Wireframe](https://hzgfzw.axshare.com/#g=1&p=non_cgov_microsite_homepage)

**Comment by amydugan** [comment]
Division Microsite Logo Example PNG:
<img width="209" alt="example microsite asset" src="https://user-images.githubusercontent.com/28450779/51982580-687f1800-2464-11e9-83f3-7fc955363482.png">
SVG Version attached to https://tracker.nci.nih.gov/browse/CGOV-8688. (SVG not supported by Git for attachments).

**Comment by blairlearn** [comment]
YAML content?  Which specific pages?

**Comment by VictoriaSunNIH** [comment]
As long as we are able to apply the microsite theme color to cancer.gov and have some user testing done there, I don't think we need this ticket. Closing this out.
