### ISSUE TITLE
Video doesn't play on NANO home page.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2173]
1. Go to https://www-prod-acsf.cancer.gov/nano/
1. Scroll down to the nanotechnology video.
1. Click the "Play" button in the middle of the image.
1. Nothing happens.
1. In the developer tools, a 403 error is reported for the URL `https://www-prod-acsf.cancer.gov/media/oembed?url=https%3A//www.youtube.com/watch%3Fv%3DjC8CUIID2HA&max_width=0&max_height=0&hash=0ArUILmUATW8tTrJNWC4JBvJE4dtYe1mdtZ5wkN54BM`

**Comment by bryanpizzillo** [comment]
The URL for the microsite should have the base url, e.g. `/nano/media/oembed?url=https%3A//www.youtube.com/watch%3Fv%3DjC8CUIID2HA&max_width=0&max_height=0&hash=0ArUILmUATW8tTrJNWC4JBvJE4dtYe1mdtZ5wkN54BM`

I believe this is why it is giving a 403.

**Comment by bryanpizzillo** [comment]
So, it looks like nano-cms.cancer.gov/nano/ generates the link directly. So it is possible the public URL is cached. Trying to clear out that URL has revealed some issues in the purge module.

**Comment by bryanpizzillo** [comment]
Trying it out on lower Akamai'd tiers to see what happens

**Comment by bryanpizzillo** [comment]
In some sort of Punked way, https://nano.ncigov.acsitefactory.com/ has the correct /nano/media/oembed. (Which is incorrect because /nano/ is not in the URL.)

**Comment by bryanpizzillo** [comment]
... AND it is now working on https://www-prod-acsf.cancer.gov/nano/.  So who the hell knows what was up with that one. Take a stick and keep poking until clear. :(

Something to keep an eye on.
