### ISSUE TITLE
Date Display Issues for Spanish Blog Posts on Cancer Research List Pages 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2177]
Spanish blog posts on Spanish Cancer Research List Pages are displaying the English blog post date.
- When a Spanish blog post is used in a list that displays dates, the posted date of the Spanish blog post should display.
- When an English blog post is used in a list that displays dates, the posted date of the English blog post should display.

https://www-prod-acsf.cancer.gov/espanol/cancer/tratamiento/investigacion
when you click one of the blog post links, you'll see the correct posted date displaying on the blog post itself.

Left is percussion live site; right is prod-acsf:
![Screen Shot 2019-06-27 at 10 26 48 PM](https://user-images.githubusercontent.com/29731392/60897437-1376d780-a236-11e9-8310-d385ff15baf5.png)

**Comment by blairlearn** [comment]
Released in v1.1.4
