### ISSUE TITLE
Incorrect margin on left medium image template

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2179]
The margin on the left medium image template appears to be on the wrong side of the image. I've attached a screenshot that shows a left small image followed by a left medium image. The first image has the correct margin so the left medium image should match (40px right and bottom only).
https://www-cms.cancer.gov/about-nci/organization/cgh/blog/2017/brazil-visit
I have since changed the image from medium to small but this is one of the pages I found it on.

![Screen Shot 2019-07-09 at 2 04 49 PM](https://user-images.githubusercontent.com/4921685/60915794-b9d4d400-a25a-11e9-9058-4f820382c352.png)

**Comment by arcepaul** [comment]
@mworrest 
Could you please recheck if this is still an issue?
I have not been able to recreate the embedded entities appearing the way it does in your screenshot.

**Comment by VictoriaSunNIH** [comment]
@arcepaul - this is still an issue for Left Medium Image templates.  It was not see on the URL @mworrest provided because she changed it out to use Left Small Image templates.

I recreated the issue on dev-acsf: https://www-dev-acsf.cancer.gov/about-nci/organization/cgh/blog/2017/brazil-visit

**Comment by arcepaul** [comment]
@VictoriaSunNIH 
Thanks for the example!  It looks like some rogue entity embed styles.
