### ISSUE TITLE
Create Forms Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#218]
This story is to create the [Forms](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Forms) special content type.

This content type will need a way to pull in data from a set of fields on the form (dependent on the form type), format it into an email, and then send the email.  We may or may not need to build a content type...this needs more investigation.

Depends on #1105

**Comment by blairlearn** [comment]
**Possible approach:** Could this be handled via the existing forms handler, directing the request via Akamai?

**Comment by VictoriaSunNIH** [comment]
completed
