### ISSUE TITLE
At tablet/mobile breakpoint, the Subscribe link in the blog post should appear above the Page Options 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2198]
At tablet/mobile breakpoint, the Subscribe link in the blog post should appear above the Page options

![image](https://user-images.githubusercontent.com/28455973/61074753-6d1e0400-a3e6-11e9-901a-a340eb0f13eb.png)

**Comment by sarinapadilla** [comment]
This was fixed with https://github.com/NCIOCPL/cgov-digital-platform/commit/b8a18dc2e25a1a20cd6ac77ce69f25526cba731f.
