### ISSUE TITLE
Prop5 on click of Delighters is not setting pagename value correctly

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#2203]
Go to the homepage on Cancer.gov. Click on the CTS delighter. An analytics click event is fired. In that click event, prop5 is meant to set a name for the click (like hp_find ct) then a pipe and the page name of where the event occurred. The code tries to use an Adobe dynamic variable to set the page name value. This looks like: "D=pageName". Since this value is being set in the middle of a longer value (ex: livehelp_proactive chat - display|D=pageName), Adobe does not execute the dynamic value and instead just passes the text "D=pageName".

Please correct so that the pageName value is inserted into this string on the client side before the data is sent out to Adobe.

**Comment by welshja** [comment]
Tested on homepage. Looks good.

**Comment by welshja** [comment]
This is working in production. Closing this issue out.

**Comment by bennettcc** [comment]
Closing this ticket - it is no longer needed as the Delighter has been removed with the MVP1 release
