### ISSUE TITLE
Inconsistent loading of analytics code

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#2204]
As we are navigating through the site and testing, we are seeing sporadic instances where the pageload code seems to be pulling from the wrong place. The reportsuite that gets load is only nciglobal and not nciglobal,ncienterprise as expected. As you then navigate to another page, an exit link is recording despite navigating from one page to the next on c.gov.

This is happening sporadically and have not been able to establish steps to recreate. Entering to note the issue, but haven't seen it re-occur in the past hour.

**Comment by daquinohd** [comment]
This may have been a result of the DNS cutover process. Something to keep an eye on, but haven't been able to recreate.

**Comment by welshja** [comment]
We have been able to identify that this issue occurs on the initial page load call to Adobe and seems to be related to a dependency in DTM on appmeasurementcustom which is loaded by common.js. DTM is completing its call before common.js is loaded. This results in a call to Adobe devoid of meaningful information like page name and other key values.

**Comment by markecramer** [comment]
DTM is calling AppmeasurementCustom (in satellite.pageBottom) before it has loaded in common.js. We have changed the order around so the DTM code loads after the NCI JS including common.js.
