### ISSUE TITLE
Site Section Navigation Caching Issues

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2206]
When pages within a section reside in the Akamai cache, and an advanced editor makes changes to the navigation for that section (by adding a taxonomy item, editing a taxonomy item, etc.)  - those pages are not updated within the Akamai cache and do not display the changes made to the section nav on the front end.

**Comment by bryanpizzillo** [comment]
While this could easily be accomplished by bubbling up the cache tags on the block, this would create too many tags. (Mostly for large sections, but still) (The tags would be all the landing pages and all the terms in that section) We would most likely clear out too many items as well. 

In fact, the section nav should only be invalidated under a small number of conditions:
* For the site section term:
  * Selecting a new landing page
  * A change to the status of field_section_nav_root
  * 
* For nodes that are the landing page target:
  * If the site section, or pretty url name change.

...inprogress...

A couple of technical requirements:
1. The

**Comment by adriancofie** [comment]
## User Story 1
As an admin I’d like the ability to clear the cache tag for a specific section.

 ### Scenario 1:
   The Pretty URL of a site sections has been changed and I’d like to manually clear the cache for pages affected by the changes

 
## Acceptance Criteria:
**When I view the HTML header on a page:**
(Chrome: Inspect Element 
-> Click the `Network` Tab. 
->  Refresh the page you are on.
-> Click the `Doc` tab 
-> Click `Headers`)

**Within `X-Drupal-Cache-Tags` I should see tags with the following pattern:**
 - ` site_section:<Taxonomy-ID-Of Section> `
   For example:
   -  `site_section:11844 `

**Comment by VictoriaSunNIH** [comment]
Detailing some more test cases used for this ticket:
1.  In order to test a change of the site section pretty URL, you will need to re-save the affected NODES (ie any nodes containing the section nav). This is because the links in the navigation are based on the computed URL for the landing page, which still has the old data.
2. Reordering Site Section terms should be a change that takes effect immediately without a cache clear.
3. Similarly, changing a Site Section Name or Nav Label will show immediately without a manual cache clear.
