### ISSUE TITLE
Add schema.org logo markup to www.cancer.gov site.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2213]
To help Google understand what our logo for the knowledge graph should be, we may add the following to our web site. This should only be for www.cancer.gov, and could be placed in the banner of the site. The logo may be an svg image, and should most likely use the Square Social Media logo. See https://developers.google.com/search/docs/data-types/logo for more information. 
```
<script type="application/ld+json">
      {
      "@context": "http://schema.org/",
      "@type": "Organization",
      "url": "https://www.cancer.gov/",
      "logo": "http://www.cancer.gov/<LOGO_HERE>"
      }
    </script>
```

**Comment by andyvanavery31** [comment]
Header has been updated. Closing this ticket.
