### ISSUE TITLE
Site footer doesn't stick to bottom of view area.

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#2214]
Currently the sites footer does not stick to the bottom of the view area. This causes a blank area to appear on larger displays when pages do not have a significant amount of content.

Examples seen in the wild would be the Page Not Found page, and the User Login page, however would also affect other content pages. 

<img width="1706" alt="Screen Shot 2019-07-17 at 2 47 59 PM" src="https://user-images.githubusercontent.com/38888889/61402986-4d815280-a8a2-11e9-9d78-db4ba365927e.png">
<img width="1707" alt="Screen Shot 2019-07-17 at 2 47 46 PM" src="https://user-images.githubusercontent.com/38888889/61402987-4d815280-a8a2-11e9-9e43-5c367907c225.png">

**Comment by bryanpizzillo** [comment]
This is not really a fixable thing. Even the new NCIDS footer has this.
