### ISSUE TITLE
The Help Popup Modal is not showing up on Cancer Drug Dictionary

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2216]
The Help Popup Modal is not showing up on Cancer Drug Dictionary on clicking the help link
Steps to recreate:
1.Go to the url: https://www.cancer.gov/publications/dictionaries/cancer-drug
2.Click on the help link besides the Search Button

Screen-shot of the modal:
![image](https://user-images.githubusercontent.com/28455973/61405113-ffbb1900-a8a6-11e9-9541-020e2cbda4cb.png)

**Comment by andyvanavery31** [comment]
Old version of dictionary. Closing ticket.
