### ISSUE TITLE
The magnifying glass on the CTS delighter is cut-off at different breakpoints

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2217]
The magnifying glass on the CTS delighter is cut-off at different breakpoints.
![image](https://user-images.githubusercontent.com/28455973/61407759-7c9cc180-a8ac-11e9-90b2-c7f032ce3f1e.png)

![image](https://user-images.githubusercontent.com/28455973/61407902-d1d8d300-a8ac-11e9-99b5-48b3359f7cbb.png)

![image](https://user-images.githubusercontent.com/28455973/61407938-e6b56680-a8ac-11e9-90f9-ae00c862b052.png)

**Comment by bennettcc** [comment]
Closing this ticket - it is no longer needed as the Delighter has been removed with the MVP1 release
