### ISSUE TITLE
Issues with Spanish Search Results

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2218]
Issues with Spanish search results:
- Many search results are not showing meta descriptions, even though they are available in the CMS
- Description text that does appear in search results isn't actually the meta description (or even the list description) of the page. In the screenshot below, the two results that have text are displaying the first bit of body text from their respective page. None of the description fields match the text:
  - https://www.cancer.gov/espanol/noticias/temas-y-relatos-blog/2018/cancer-tratamiento-corazon-efectos-secundarios
  - https://www.cancer.gov/espanol/noticias/temas-y-relatos-blog/2019/cancer-inmunoterapia-investigacion-efectos-secundarios
-  “Instituto Nacional Del Cáncer” is appended to titles in the search results. This should only be appended to the browser titles for external search, not cgov's search.

![spanish-search-results_7-17-2019](https://user-images.githubusercontent.com/29731392/61413170-d60aed80-a8b8-11e9-9938-907569507c1d.jpg)

**Comment by bryanpizzillo** [comment]
@sarinapadilla - this time can you please just copy ALL the fields into the content specific ones. I am assuming this is the same issue.

**Comment by bryanpizzillo** [comment]
@popkhadzeg This is related to https://github.com/NCIOCPL/cgov-digital-platform-qa/issues/89

**Comment by bryanpizzillo** [comment]
@amydugan  Please break this up into individual tickets for each item, I am guessing they will end up being different solutions on different projects.

@lburack @VictoriaSunNIH - FYI

**Comment by amydugan** [comment]
Closing this issue. It has been broken out into: #2221 #2222 #2223 

Posed the question in #2223 as to whether additional updates are needed for changing Del in “Instituto Nacional Del Cáncer” to “Instituto Nacional del Cáncer” in other places.
