### ISSUE TITLE
Spanish Search Results: many search results are not showing meta descriptions

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2221]
In Spanish, when a user performs a search, many of the search results are not displaying meta descriptions, even though they are available in the CMS. See screenshot of first page of search results for efectos secundarios below.

![image](https://user-images.githubusercontent.com/28450779/61457141-ab12af00-a935-11e9-95ca-f705c3f02b70.png)

**Comment by bryanpizzillo** [comment]
I am seeing that the meta-description tag is missing from the pages without a description.
