### ISSUE TITLE
Spanish Search Results: “Instituto Nacional Del Cáncer” is NOT being removed from titles in the CGov search results

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2223]
Spanish Search Results: “Instituto Nacional Del Cáncer” is not being removed from titles in the CGov search results. (See screenshot below from search for efectos secundarios.) As the crawler indexes the browser titles, the appended site name should be removed.

In addition, "del" should not be capitalized. It should display as “Instituto Nacional del Cáncer” 

![image](https://user-images.githubusercontent.com/28450779/61457871-40627300-a937-11e9-8e0e-580a3818778f.png)

**Comment by amydugan** [comment]
Are there other places in the system where “Instituto Nacional Del Cáncer” needs to be updated to “Instituto Nacional del Cáncer”?

**Comment by lburack** [comment]
@amydugan @VictoriaSunNIH - Spanish browser titles are the only place where I’ve see the “del” with a capital D. Before the migration, Spanish browser titles appended the English “-National Cancer Institute” so this change might have slipped past Spanish review.

**Comment by bryanpizzillo** [comment]
@lburack So just to be clear, prior to migration, the Spanish site was always broken and it had improper browser titles?
