### ISSUE TITLE
Full Pager Pagination on Views needs styling

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2224]
Views with pagers are not styled correctly. Scroll down to the bottom for screenshot of how they should look.
**Mini Pager screenshot:**
<img width="449" alt="mini-pager" src="https://user-images.githubusercontent.com/29731392/61468079-b58b7380-a94a-11e9-8fd5-4d00440ef76a.png">

**Full Pager screenshot:**
https://dceg-prod-acsf.cancer.gov/news-events/events/past-events
<img width="551" alt="full-pager" src="https://user-images.githubusercontent.com/29731392/61468170-d81d8c80-a94a-11e9-85e3-f17c24aa85ef.png">

The full pager pagination should be styled like the CGOV press release pagination:
![Screen Shot 2019-07-18 at 5 12 26 PM](https://user-images.githubusercontent.com/29731392/61492426-40866100-a97f-11e9-86bb-c9a0f51fcc87.png)

**Comment by arcepaul** [comment]
@lburack 
Examples please!  I'm having a heck of a time trying to find one in the wild.

**Comment by lburack** [comment]
@arcepaul - https://www.cancer.gov/news-events/press-releases/2015. Unfortunately this example only has two pages worth of results. So I messed with the view settings on dev to create https://www-dev-ac.cancer.gov/news-events/press-releases/2018. This has 10 pages of results.

So the requirements as they stand now are to show 
< Previous [numbers 1-9, if applicable] Next >
![Screen Shot 2019-07-25 at 10 42 42 AM](https://user-images.githubusercontent.com/29731392/61883897-3b6a6a00-aec9-11e9-8410-a221bdbf65d6.png)

Once a user gets to page 6, the numbers begin to shuffle (i.e., I can now numbers 2-10)
![Screen Shot 2019-07-25 at 10 44 59 AM](https://user-images.githubusercontent.com/29731392/61883923-458c6880-aec9-11e9-801d-3b51ee820c14.png)

Hopefully this makes sense. Holler if you have more questions!
