### ISSUE TITLE
Accessibility: screen reader text is invisible to screen reader

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#2226]
The .hidden class is being applied to some elements with the intention of being a sr-only|show-for-sr class but a display: none is being applied to it by one of the stylesheets, making it invisible to screenreaders.

This issue exists in production.

(ex. search button icon )
<img width="1510" alt="hidden" src="https://user-images.githubusercontent.com/45469809/61491520-6c084c00-a97d-11e9-942f-a6503c1a4b87.png">

**Comment by arcepaul** [comment]
@lburack @VictoriaSunNIH @bryanpizzillo 
So the approach here is to replace the "hidden" class everywhere it was used to represent text for screenreader with the class "show-for-sr".  This has been completed in the templates.

This means that it has to be replaced in the block content files as well in files such as the mobile-menu and footer(all the social media icons for example)

What would be the easiest way for me to help revise this content?

**Comment by markecramer** [comment]
Looks good. What was the mobile menu change mentioned? Didn't see that one.

**Comment by amydugan** [comment]
@arcepaul - Could you point Mark to the mobile menu change that needs testing? Thanks!
