### ISSUE TITLE
DCEG Homepage Needs to Have 'Find a Clinical Trial' Delighter Removed

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2229]
The Find a Clinical Trial delighter is showing on the DCEG homepage. This needs to be removed.
https://dceg-prod-acsf.cancer.gov/

**Comment by arcepaul** [comment]
The presence of delighters will now be driven off of an entry(shouldShowFloatingDelighters) in the global config.  This does mean that this key will need to be added to the cgov config for the floating delighters to appear.  This can be done before this patch is pushed to prod to prevent reports of delighters not appearing.
