### ISSUE TITLE
Refactor nci-analytics-functions.js and analytics.js

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#2235]
Placeholder to do the following:
* Clean up the mess of jQuery in analytics.js and replace on.click() calls with listeners
* Refactor unneeded clickTrack() methods in nci-analytics-functions
* Remove unused methods in nci-analytics-functions.
* Eventually remove nci-analytics-functions.js completely.

**Comment by andyvanavery31** [comment]
This is outdated.
