### ISSUE TITLE
DTM / Analytics - update AppMeasurement version

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#2239]
Update the managed version for Adobe AppMeasurement.js to v2.15.0
* Login to DTM and select the managed version dropdown for the Analytics Tool
* Run auto and manual tests

**Comment by bryanpizzillo** [comment]
I am going to close this and say it is overcome by events. We now use Adobe Launch and AppMeasurement is selected there.
