### ISSUE TITLE
Technical Epic: Create Default Content

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#224]
This epic encompasses creating a set of predefined content (for blocks and content types)  to be made available upon site install.

- [ ] Create default content for the www footer block #140 
- [ ] Create default content for page blocks that are pending  req's/ development

**Comment by adriancofie** [comment]
This was not intended for #217. It was intended primarily to capture the footer block, and stubbed content for regions. If we're re-purposing it we can move it to another Sprint. Otherwise, the tasks mentioned have been completed.

**Comment by amydugan** [comment]
Closing per Adrian's last comment.
