### ISSUE TITLE
Glossification not working on dceg-cms

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2241]
I am not able to glossify content on dceg-cms.cancer.gov

My guess is it needs to be configured?  Someone please investigate!

**Comment by blairlearn** [comment]
This had several causes.

* **Missing CORS headers** - Fixed the CORS headers on services. (The fix in the CDE configs never made it to the `master` branch and was overwritten.)
* **No glossification data** - Added DCEG to the CDRs list of glossification data  delivery targets.

We'll have to recheck on Monday.

**Comment by bryanpizzillo** [comment]
@blairlearn or @VictoriaSunNIH -- Did you recheck on Monday?

**Comment by VictoriaSunNIH** [comment]
Yes @bryanpizzillo  and its working! Closing this as compelted.
