### ISSUE TITLE
Streamlined WYSIWYG needs to allow classes to support glossification

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2246]
Streamlined WYSIWYG has glossification option, but glossified links in article intro text (uses [streamlined wysiwyg](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields-WYSIWYG)) are displaying as traditional hyperlinks, not our glossified styling. 

This ticket is to update the streamlined WYSIWYG to allow the proper glossification styling.

Add `data-glossary-id` and `class` as allowed attributes  to the `a` element in the format.streamlined.yml in cgov_core/config/install

**Comment by VictoriaSunNIH** [comment]
It looks like the relevant tags are being stripped out.
The page is https://www.cancer.gov/about-cancer/diagnosis-staging/diagnosis where this occurred.

Into HTML
![image](https://user-images.githubusercontent.com/11215649/61396370-9252bc80-a895-11e9-9479-34e2536dcced.png)

Working definitions in body on the same page:
![image](https://user-images.githubusercontent.com/11215649/61396422-b6160280-a895-11e9-9c82-0581489dfa08.png)
