### ISSUE TITLE
Some PDQ content is stuck in the draft state

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#2249]
The Drupal entity API returns the wrong revision number for the latest revision of an English summary when it is queued together with its Spanish translation for transition to the `published` state. As a result, the English summary in such as case is left in the `draft` state.

**Comment by bkline** [comment]
We have identified four possible solutions for this problem.

1. Use SQL instead of the Drupal entity query API in the implementation of the REST API for moving PDQ content from `draft` to `published`.
2. Modify the CDR publishing software to use separate passes for publishing the English and Spanish drafts.
3. Have the API which saves a new PDQ summary return both the node ID and the revision ID, instead of just the node ID, and have the client send the revision ID instead of the language code to the API for publishing PDQ drafts.
4. Use the storage API method which was created last year for obtaining the revision ID for the most recent revision for a given language of a given node.

We are testing the fourth option.

**Comment by bkline** [comment]
There appears to be a bug in the entity `save()` method, which sometimes cause the wrong value to be stored in the `revision_translation_affected` column of the `node_field_revision` table on which the API used for solution #4 relies. It doesn't look as if this bug will prevent our solution from working, as it only seems to happen as we're moving the Spanish translation from `draft` to `published`, when the `revision_translation_affected` column for the English table row for the new revision gets marked (incorrectly) as having been changed for this revision, which means the next call to `$storage->getLatestTranslationAffectedRevisionId()` for the English translation will get the wrong revision number. But by that point we no longer need that method, and the next time we need it the English translation will have a new revision, correctly flagged. It does mean, however, that we can't use the database tables to verify programmatically that our fix has worked correctly for all 1,043 summaries, so we'll have to fall back on visual spot-checking in the API. We will come up with a Behat test which fails without the fix and passes with it.

**Comment by bkline** [comment]
It looks as if the bug which sets the wrong value in the `revision_translation_affected` column of the `node_field_revision` table breaks the API to fetch a PDQ summary node, causing the test suite to fail even before it's modified to add the test for the stuck `draft` states. As far as I can tell from manual testing, the only way we can address both problems (short of getting Drupal to fix the `revision_translation_affected` bug, which I suspect is the result of a deep flaw in the handling of multiple draft revisions for different languages in the same node) is to accept the fact that we have to publish the English summary before we save the Spanish translation. If we do that as well as use the new `getLatestTranslationAffectedRevisionId()` method, the publishing of the summary's translations _and_ the fetching of PDQ summary nodes both work correctly when I perform the steps manually. I'm going to hold of on rewriting the test script to reorder the saving and publishing steps until @bryanpizzillo approves the approach I'm proposing.

**Comment by bkline** [comment]
Collecting links for Drupal core issues which may be related to this ticket. I haven't read all of the issues thoroughly, so I am aware that not all of them really _are_ necessarily relevant, but I want to preserve this list so I can come back to it if I need to. The first one on the list (filed by [Wim Leers](https://www.drupal.org/u/wim-leers)) pretty much sums up what I'm finding:

> I noticed this a long time ago, but didn't dig into it because there were bigger problems to solve. But the mysterious revision_translation_affected field that isn't really a field and is exposed by both core REST and JSON API is a huge WTF for developers.

- [The semantics of the "revision_translation_affected" field are unclear to Decoupled Drupal developers (REST/JSON API/GraphQL) users, improve this](https://www.drupal.org/project/drupal/issues/2933518)
- [[PP-2] Add parallel revisioning support](https://www.drupal.org/project/drupal/issues/3023194)
- [Add an API to create a new revision correctly handling multilingual pending revisions](https://www.drupal.org/project/drupal/issues/2924724)
- [Ensure that changes to untranslatable fields affect only one translation in pending revisions](https://www.drupal.org/project/drupal/issues/2878556)
- [Add revision_translation_affected by default](https://www.drupal.org/project/drupal/issues/2714163)
- [Migrate D6 and D7 node revision translations to D8](https://www.drupal.org/project/drupal/issues/2746541)
- [revision_translation_affected is not re-calculated when re-saving a revision](https://www.drupal.org/project/drupal/issues/2889530)
- [EntityQuery returns incorrect results for notExists condition where one translation matches but others do not](https://www.drupal.org/project/drupal/issues/2933202)
- [Add API methods for determining whether an entity object is the latest (translation-affecting) revision](https://www.drupal.org/project/drupal/issues/2926483)
- [Forward revisions + translation UI can result in forked draft revisions](https://www.drupal.org/project/drupal/issues/2766957)
- [ContentEntityStorageBase::getLatestRevisionId() returns empty value](https://www.drupal.org/project/drupal/issues/3031142)

**Comment by bkline** [comment]
ODE is http://ncigovcdode241.prod.acquia-sites.com/AH_VIEW

**Comment by amydugan** [comment]
Went live with Hotfix 1.1.3 8/1. Closing.
