### ISSUE TITLE
Clear Varnish and Akamai caches when cgov_file entities are updated.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2251]
When the file behind a `cgov_file` entity are updated, the Varnish and Akamai caches should be invalidated, or at the very least, the file's cache life time shortened.

On a local dev environment, with `cgov_caching_nocdn` enabled, retrieving `http://www.devbox/research/progress/discovery/test-file-url` shows no `X-Acquia-Purge-Tags:`  or `X-Drupal-Cache-Tags` headers.

Per conversation w/ @bryanpizzillo, this is most likely a problem in the `cgov_file` module, the request handler _probably_ needs to have cache tagging added.

**Comment by bryanpizzillo** [comment]
This was fixed in PR #2255. The PR even said it was closed by this. Dunno what went wrong. Closing.
