### ISSUE TITLE
Date Picker is different between Chrome and Firefox

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2252]
![image](https://user-images.githubusercontent.com/31222859/61803531-502efb00-ae00-11e9-8219-4d706a932341.png)

In Chrome (pictured left), the date picker allows us to select current date.  in Firefox (pictured right), it does not have this option.  Can we try to get the two date pickers to be the same?  This is a MINOR bug.

**Comment by BrendanBeltzNIH** [comment]
I heartily suggest you don't do that. Using the built-in date-picker brings with it the most accessible and robust solution per browser. A user would not naturally expect each browser to be the same, much like a MacOS and windows date picker vary though they accomplish the same task. 

Fulfilling this request would potentially involve having to select and implement a totally 3rd party picker for all browsers, to standardize the behavior.

**Comment by andyvanavery31** [comment]
Internal team received approval from client to close this ticket during CGDP O&M Client Prioritization meeting on 31JAN2024.
