### ISSUE TITLE
Green Microsite Theme: Break out +toggle styles for use in body

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2263]
Reported by DCEG2 contractor: + toggle style not pulling into body content
We have the nice + that is used to expand left nav items, but this still doesn’t cross over into body content and then have body content that has the expand/collapse functionality. I think the same style used in the left nav should be used in the body.

The stylings are targeted specifically for the side nav and wouldn’t show up anywhere else.  We would just need to break out the styles for use elsewhere.

**Comment by lburack** [comment]
Is this a request to allow the + / - (expand/collapse) that we have in the left nav in body text? Is there a specific place where the old(current) DCEG site uses this? If not, I think this needs UX consideration before we implement.

**Comment by amydugan** [comment]
@lburack - On DCEG2, I believe it's the staff directory, where they have the Division Branches expand and collapse. https://dceg2.cancer.gov/cgi-bin/Personnel.pl?1=ALL. I can see where this would be problematic, though. They should use the left nave to expand/collapse the staff directory, not put it in the body of the page. @arcepaul - hold on this one until we can get more UX input. I will circle back with Megan.

**Comment by bennettcc** [comment]
MVP1 launched yesterday - ticket no longer needed
