### ISSUE TITLE
Getting Linked image missing alternative text, Broken ARIA reference, Empty heading, Empty table header,Missing Form Label errors

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2269]
1. Getting **Linked image missing alternative text error** for all thumbnail images and Broken ARIA reference error for all pages on the site. (Home Pages, Landing Pages, Mini landing pages (e.g. https://www.cancer.gov/about-nci/organization), Inner pages

![image](https://user-images.githubusercontent.com/28455973/61973448-07b73f00-afb2-11e9-8183-52f052a7cefa.png)

2.Getting **Empty heading error** for the home page, https://www.cancer.gov/grants-training/training/idwb/student-recruiting-program
3. Getting **Empty link error** on https://www.cancer.gov/grants-training/training/funding, 
https://www.cancer.gov/grants-training/training/funding/early-k99, https://www.cancer.gov/grants-training/training/funding/f31, https://www.cancer.gov/grants-training/training/funding/k99, https://www.cancer.gov/grants-training/training/funding/t32 
4. Getting **Empty table Header error** for https://www.cancer.gov/grants-training/training/funding/t32
5.Getting **Missing Form Label error** on https://www.cancer.gov/about-cancer/causes-prevention/genetics/directory, https://www.cancer.gov/about-cancer/causes-prevention/genetics/directory/application-form, https://www.cancer.gov/contact/email-us, https://www.cancer.gov/espanol/contactenos/correo-electronico

**Note:** We need to fix all these issues for Spanish pages as well.

**Comment by andyvanavery31** [comment]
Outdated by Redesign.
