### ISSUE TITLE
Can't reorder site sections

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2273]
Within www-cms.cancer.gov Structure > Taxonomy > Site Sections, I tried to reorder site sections. I clicked saved at the bottom of the site sections page, but my changes are not actually saving. 

Users with access to the taxonomy should be able to reorder site sections and save those changes, to be seen on the front-end.

**Comment by kalidindir** [comment]
@bryanpizzillo 
The error is happening because we are hitting the limit with max_input_vars php.ini variable. I was able to update the order on my local with setting the value to a very high value of 10000. The default value is 1000 which did not work on my local.

**Comment by lburack** [comment]
@kalidindir @bryanpizzillo - is this something we can get onto an ODE so me/Victoria/other IAs can test? Thanks!

**Comment by kalidindir** [comment]
https://docs.acquia.com/acquia-cloud/manage/php/#max-input
Acquia cloud defaults to 1000. I have tried with different values, 2000, 5000 and 7000. The form save worked at 7000. 
However Acquia does not recommend using a value above 5000. A workaround to do the sorting for now would be to manually adjust the weight for each individual item which is rather painful.

**Comment by amydugan** [comment]
This should be closed once https://github.com/NCIOCPL/cgov-digital-platform/pull/2385 has been approved/closed.
