### ISSUE TITLE
Incorrect event firing for a number of content types

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2277]
It seems that @welshja found some issue with the metadata where an the  `dcterms_is_referenced_by` metadata tag is getting `'event1,event53'` for a number of content types. Event 53 is only for blog posts. This appears to be a copy/paste error.

Details from JIRA:

On prod, if you go to any landing page, you'll see that event 53 is being loaded. This event should only fire on blog post views (only posts, not the series pages). It is currently working as expected on blog post pages, but should be removed from the landing pages, like www.cancer.gov/about-cancer.

**Comment by bryanpizzillo** [comment]
@welshja can you please verify that blog posts are the only content types that should get an event other than event1? Also, feel free to update the title with more information.

@sarinapadilla can you please target this for hotfix/v1.1.3 - it is going to mess up analytics the longer it goes.

**Comment by welshja** [comment]
Yep, the blog post pages are the only pages where this should fire on page load. It should not be on the series pages or any other content types.

**Comment by welshja** [comment]
Looks good on http://ncigovcdode244.prod.acquia-sites.com/.

**Comment by welshja** [comment]
Looks good on dev-acsf.
