### ISSUE TITLE
Left and Right Pullquotes are not Styled Properly

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2283]
The left and right pullquotes are not styled properly on cgov and DCEG. See below for screen shot showing the left pullquote incorrect styling vs the full width pullquote that has the proper styling. The right pullquote has similar styling to left pullquote, it's just on the right side of the page.

**SOLUTION:** 
The left and right pullquotes should get the same styles from the full width pullquote, they should just get the width, margin and float specs that are currently applied to them. 

**INCORRECT STYLES:**
![Screen Shot 2019-07-31 at 3 03 41 PM](https://user-images.githubusercontent.com/4921685/62240522-2d26bd00-b3a5-11e9-8345-a79db99b64e7.png)

**CORRECT STYLES:**
![Screen Shot 2019-07-31 at 3 09 06 PM](https://user-images.githubusercontent.com/4921685/62240553-3879e880-b3a5-11e9-96e4-1c48bbe0e837.png)

**Comment by mworrest** [comment]
So I found a page where this is working correctly: https://www.cancer.gov/about-cancer/coping/caregiver-support/parents
The correct class name is <div class="pullquote pullquote-left"> or <div class="pullquote pullquote-right">
I have updated the crib notes that were documenting this incorrectly. We should think about changing the class name so it's not so redundant.

**Comment by VictoriaSunNIH** [comment]
Yep - let’s close it!
