### ISSUE TITLE
Configure ACSF for New Relic

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2286]
Loosely following the instructions at https://docs.acquia.com/acquia-cloud/monitor/apm/multisite/, and more specifically https://docs.acquia.com/site-factory/extend/hooks/settings-php/#new-relic-monitoring, in order to configure the codebase for new relic.

**Comment by amydugan** [comment]
went live 8/8/19 in HF v1.1.4
