### ISSUE TITLE
Implement Content Type Cache Tags

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2315]
We need cache tags for the specific entity/bundle types so that we can easily bulk clear all content of that type from CDN/Cache. This is very useful on metadata changes. This would reduce the burden on the servers by not requiring the clearing of the entire cache.

**Comment by adriancofie** [comment]
Approach:

Choosiing to alter this in `hook_ENTITY_TYPE_build_defaults_alter()` instead of `hook_entity_view_alter()` or` hook_ENTITY_TYPE_view_alter()`. See description below:

> `hook_ENTITY_TYPE_build_defaults_alter()`
> 
>  * Alter entity renderable values before cache checking in drupal_render().
>  *
>  * The values in the #cache key of the renderable array are used to determine if
>  * a cache entry exists for the entity's rendered output. Ideally only values
>  * that pertain to caching should be altered in this hook.
