### ISSUE TITLE
Multiple simultaneous publish preview requests break publish preview for PDQ

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#2318]
If two requests for publish preview of the same PDQ summary hit the same site at the same time, it is likely that the calls to delete the temporary nodes will fail with an error message complaining that the request is ambiguous (because the node ID lookup for the negative CDR ID used for the PP request finds more than one node). This can happen if the user gets impatient and clicks the publish preview link a repeatedly. Once that condition occurs, subsequent attempts to preview the same summary will fail, because none of the temporary documents get deleted and they start piling up.

I’ll have to give some thought to how to prevent this from happening. I could just modify the code to not worry about ambiguous delete requests if the CDR ID is negative (which it is for the PP requests, to distinguish from the permanent summary content nodes). The downside for that would be that if two users request PP for the same summary at exactly the same time, one of them (likely the second user) will get an error. Very unlikely to happen, though, and a much less problematic result than a summary getting stuck so that all future attempts to run publish preview on it will fail until the temporary nodes are cleared out.

**Comment by blairlearn** [comment]
Merged in #2325.
