### ISSUE TITLE
Watchdog entry is created when a PDQ POST request comes in with a missing nid index

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#2319]
The primary CDR publishing code for PDQ content ensures that the `$summary` array passed to the end point has a `nid` index, even if the value is `NULL` (as it will be for a new English summary). However, the publish preview code does not behave the same way, the that index is missing. A Jira ticket will be filed to fix that problem on the CDR side, but the Drupal PHP code for the CIS and DIS POST end points should assign the `$nid` variable defensively:

`$nid = $summary['nid'] ?? '';`

**Comment by blairlearn** [comment]
Merged in #2325.
