### ISSUE TITLE
Fine Tune Best Bets Results

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2328]
Looking at www-stage.cancer.gov (ahead of the launch of search), some Best Bets are displaying that are not relevant to the search term.

For example,
- "Division of Cancer Prevention"
  - gave 6 BBs — one was for DCP, and the other 5 were not relevant (Best Bets for: Hematologic/Blood Cancers; Cost of Cancer; Division of Cancer Biology; Division of Cancer Epidemiology and Genetics; Division of Cancer Control and Population Sciences)
- "Challenges of Advanced Breast Cancer"
  - On www-stage.cancer.gov, got BB for Hematologic/Blood Cancers and a BB for Cost of Cancer (empty; no link provided)
  - On the live site, no BBs for this search phrase
- "Advances in Pancreatic Cancer"
  - On www-stage.cancer.gov, got BB for Cancers by Body Location/System
  - On live site, no BBs for this search phrase

**Comment by bryanpizzillo** [comment]
This is an issue with the BB loader. Closing this issue. https://github.com/NCIOCPL/bestbets-loader/issues/13
