### ISSUE TITLE
Best Bets, Definitions should NOT display in Microsite Search Results

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2330]
Only Cancer.gov search should display Best Bets and/or Definitions. The microsites (Nano, NCI-CONNECT, MyPART, DCEG) should **not** display Best Bets and/or Definitions in their search results.

Tagging @arcepaul as the front-end will need to be updated when this back-end change happens.

**Comment by bryanpizzillo** [comment]
This has nothing on the back end. This will just be requirements, hopefully already articulated, for the react app.

**Comment by lburack** [comment]
This issue can be closed as it's being resolved now with SWS migration.
