### ISSUE TITLE
The automatic resizing of images can run out of memory

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2335]
There was an issue today where an 8.3mb image required too much memory and failed. This was resolved by using a smaller image. We should either review our image sizes, increase memory usage for the resizer specifically, force sizing on save OR find a better resizer. (The resizer is Drupal's)

This was found when Julie was trying to create a Cancer Currents blog post.

**Comment by bryanpizzillo** [comment]
The easiest way to reproduce this is:
1. Create a cgov image with an image of 10000x10000 pixels.
2. Create a blog post and use the cgov image as the lead image
3. View the blog series and you should see a broken image next to the item.

**Comment by bryanpizzillo** [comment]
@popkhadzeg Can you take a look to see what the limits are? I am looking for a good image generator

**Comment by popkhadzeg** [comment]
This ticket was tested on dev-ac to find a threshold for acceptable image sizes. 

We checked this on both windows and mac and noticed that errors produced for different sizes depending on the platform we tested. While 6000x6000 image size produced "Fatal error: Allowed memory size of bytes exhausted" on MAC, it passed while creating the same size image on windows machine.

We narrowed the list of JPG image sizes down to following:

Passed scenarios:
5000x5000
5010x5010
5000x3000

Failed Scenarios:
8000x8000
6000x6000 (passed on Windows)
6000x5000
5050x5050 (passed on Windows)
5020x5020 (passed on Windows)

Please note that sometimes fatal errors occurred on saving the image and sometimes while accessing the published blog post link or accessing it from Blog series page.
