### ISSUE TITLE
Refine Block and Cache Tags for Blog Archive Block

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2340]
Currently the Blog Archive Block uses the node_list cache tag. This would be fired way too often for what is needed. We should use the blog series cache-tag instead (node:xxxx). Additionally the block should be rendered in such a way as to ensure that the cache tag is *actually* sent with all blog-posts that display the archive.

**Comment by kalidindir** [comment]
@lburack @VictoriaSunNIH
http://ncigovcdode256.prod.acquia-sites.com

**Comment by lburack** [comment]
I added and archived blog posts and the numbers displayed in the Archive right rail updated as expected, both when logged in and viewing in an incognito window. Marking this as passed IA review, but based on the ticket description, this needs some technical review, too.
