### ISSUE TITLE
Refine Block and Cache Tags for Blog Featured Posts Block

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2341]
Currently the Blog Featured Posts Block does not include any cache tags. This means that if a feature-post is added, blog-posts would not be invalidated from the cache. We should use the blog series cache-tag (node:xxxx) for the block. Additionally the block should be rendered in such a way as to ensure that the cache tag is actually sent with all blog-posts that display the archive.

**Comment by kalidindir** [comment]
@lburack @VictoriaSunNIH
http://ncigovcdode256.prod.acquia-sites.com

**Comment by lburack** [comment]
I added a new blog post to Featured Posts and pushed live.
I renamed the card title and pushed live. I also renamed the page title and pushed live. The proper title appeared in Featured Posts right rail on the blog post, the blog series, and another blog post. 
CC @VictoriaSunNIH @bryanpizzillo
