### ISSUE TITLE
Blog Category Browser Titles

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2347]
Browser Titles on blog category pages are pulling the browser title of the blog series itself. This is seen in the screenshot below and if you check the og:title in the source code on any of the blog category pages (ex: https://www.cancer.gov/news-events/cancer-currents-blog?topic=biology)

The browser title should be the same as the page title for these pages. This is important for SEO so all of these pages aren't being viewed as having the same exact title.

<img width="1240" alt="Screen Shot 2019-08-21 at 7 53 15 PM" src="https://user-images.githubusercontent.com/29731392/63476061-7f5f7900-c44d-11e9-8688-8c3dc9ffbb38.png">

**Comment by kalidindir** [comment]
@bryanpizzillo 
**Problem**
The title for the blog series page is implemented in a twig macro while the metatags for the blog series page is implemented using a custom module and tokens. Current logic is different in both places.
**- Solution**

- Implement a new twig extension for blog and move the title for logic into blog manager.
- Use the blog manager service to generate the title in the cgov_tokens module.
