### ISSUE TITLE
Dictionary of Cancer Terms - Move Definition to the Top of the Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2348]
This request is to flip the hierarchy of the dictionary content for all dictionaries, including Spanish.
 
- On the [Dictionary of Cancer Terms](https://www.cancer.gov/publications/dictionaries/cancer-terms), there's text about the dictionary and a large search box at the top of the page. This makes sense for the main dictionary page.
- If you click on an individual term (like https://www.cancer.gov/publications/dictionaries/cancer-terms/def/absolute-risk), users expect to see the actual definition, not a large search box.

**Requirements:**
- the h1 should change to the term name
- First line below the H1 would be the audio icon and phonetic spelling, followed by the definition (including related information, if applicable)
- browser title should remain as is 
  <img width="269" alt="Screen Shot 2019-10-23 at 9 31 21 AM" src="https://user-images.githubusercontent.com/29731392/67397909-e7c6f580-f577-11e9-9384-78df3b3eeeda.png">
- remove what is currently the intro text** 
> The NCI Dictionary of Cancer Terms features 8,463 terms related to cancer and medicine.
We offer a widget that you can add to your website to let users look up cancer-related terms. Get NCI’s Dictionary of Cancer Terms Widget.
- Search box + Browse A-Z List links move to the bottom, below an h3 of "Search NCI's Dictionary of Cancer Terms"

![image (4)](https://user-images.githubusercontent.com/29731392/67400988-75a4df80-f57c-11e9-8c25-d98e218e373e.png)

**This text should only be removed on individual dictionary term pages. The text will remain on www.cancer.gov/publications/dictionaries/cancer-terms and each letter index page -- e.g., www.cancer.gov/publications/dictionaries/cancer-terms?expand=B)

**Comment by VictoriaSunNIH** [comment]
Being taken care of in glossary-app stories.  Closing this out
