### ISSUE TITLE
Implement typeahead feature

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2351]
Implement the typeahead feature to be used on the CTS basic and advanced forms.

This includes:
- Ensuring that type ahead options appear after 3 letters have been inputted
- "Faux" drop down 
- Custom option styling/display of items in the "faux" drop down (e.g. drugs, treatment options)
- Multi select versus single select options

![image](https://user-images.githubusercontent.com/31222859/63891702-d1efe680-c9b3-11e9-8637-77c31e2feb89.png)

**Comment by SupriyaSaxena0605** [comment]
@VictoriaSunNIH As mentioned above, will the typeahead feature allow multi select option? Currently it allows only single selection in prod.

**Comment by VictoriaSunNIH** [comment]
@SupriyaSaxena0605 - It depends on the use case for the typeahead.  For example, for Subtype, Stage, Side effects, Drugs, and Treatment, on the advanced search, we allow multiselect.  But on Primary Cancer, Trial Investigators, Lead Organizations, we only allow single select.  It should match what is currently on Prod.
