### ISSUE TITLE
Implement Base CTSAPI Library Framework

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2376]
## Description 

We need a PHP version of the Clinical Trials Search API Library for use by the system. Technically this should be able to live on its own and be packed as an individual composer package. (NOTE: This is NOT a Drupal module, but just a PHP Library) However, for the first couple of rounds, and until we can figure out how to build and package for distribution, this should live in our main codebase. (Although it may be quite easy to separate it into its own code base with its own dockerfile for testing - so convince me otherwise)

### Links
* CTS API
  * https://clinicaltrialsapi.cancer.gov/#/Clinical45trials
* Our .NET code
   * https://github.com/NCIOCPL/wcms-cde/tree/master/CDESites/CancerGov/SiteSpecific/Modules/CancerGov.ClinicalTrialsAPI
   * This API should be similar. At the very least this code demonstrates how to make requests to the CTS API.
* You may be able to just autogenerate the client code?
   * https://swagger.io/tools/swagger-codegen/
* Nice lite article on building a PHP client
   * https://www.chapterthree.com/blog/building-rest-api-clients-php-easy-way

*  Create the following: 
    * The API Client Class (implementing the /term/{term_key} method)
       * The get term method should be fairly easy to implement and should not distract from the core task to get the framework in place so we can implement the REALLY complicated objects, such as trials.
    * A unit test for the API & /term/{term_key} method.
*  Configure the:
    * PSR-4 autoloader loading to ensure it shows up in our Drupal stack
    * The new test paths in the blt.yml file. (Both in phpunit and paratest elements)
       * Both elements are a array of locations that hold test code.

**Comment by blairlearn** [comment]
Implemented as https://github.com/NCIOCPL/clinical-trials-search-client.php.
