### ISSUE TITLE
Spike: Investigate how to add schema.org markup to our content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2383]
Please investigate how to add schema.org markup to our content via either a 3rd party module or custom implementation?  We need to be able to markup some FAQ pages on cancer.gov (which are article content types currently) with the correct markup.

Markup examples:
https://schema.org/FAQPage
https://developers.google.com/search/docs/data-types/faqpage

We should create YAML content that mimics this factsheet with headings/content as Q&As so that we can apply the markup to this content on dev ac.
https://www.cancer.gov/types/prostate/psa-fact-sheet

**Comment by lburack** [comment]
@sarinapadilla  - requirements have been updated on the implementation ticket #2384
