### ISSUE TITLE
Updating display of citations

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2419]
PENDING APPROVAL from content owners

Adding citations to a piece of content creates a section on the front end at the end of content, above Related Resources.

We'd like to make some universal changes, and offer additional display options to users

* Change the header that appears from "Selected References" to "References"
* Allow users to choose whether or not the items are numbered on the front end - numbering should be used only if user is using footnotes by including anchor links in the text 
* Add a tooltip to the Citation Content field to specify that users should use AMA style for citations

**Comment by andyvanavery31** [comment]
Updates will be made to Articles with decisions being made then. Closing this ticket.
