### ISSUE TITLE
Hover boxes for citations are separating box and carat

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2420]
On several fact sheets I noticed that when hovering over citation numbers, the citation box and the carat weren't aligned.

- carat is over he number, and the box with the citation is off to the right
- citation box is over number, carat is off to the left  

![citationinplace](https://user-images.githubusercontent.com/39384914/64648474-f8b51080-d3e8-11e9-86d1-41ef3f6700c1.png)
![carratinplace](https://user-images.githubusercontent.com/39384914/64648475-f8b51080-d3e8-11e9-921a-58f9d0b4cd3a.png)

Appeared on these pages:
https://www.cancer.gov/types/breast/breast-hormone-therapy-fact-sheet
https://www.cancer.gov/about-cancer/treatment/types/immunotherapy/bio-therapies-fact-sheet

**Comment by andyvanavery31** [comment]
Outdated by Redesign.
