### ISSUE TITLE
The images and titles are going beyond the inline feature cards on blog posts on IE

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2422]
The images and titles are going beyond the inline feature cards on blog posts on IE.
https://www.cancer.gov/news-events/cancer-currents-blog/2019/targeting-cancer-metabolism-low-methionine-diet

![image](https://user-images.githubusercontent.com/28455973/64715016-af6acc80-d48d-11e9-8efd-5625a225f628.png)

**Comment by andyvanavery31** [comment]
IE no longer supported.
