### ISSUE TITLE
The blog posts are getting horizontal rule at mobile breakpoint (640px and lower)

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2423]
The blog posts are getting horizontal rule at mobile breakpoint (640px and lower). The images are going beyond the page.

url: https://www.cancer.gov/news-events/cancer-currents-blog/2019/lowy-annual-plan-fiscal-year-2021

![image](https://user-images.githubusercontent.com/28455973/64716822-1c339600-d491-11e9-9c01-fce42df052e2.png)

**Comment by sarinapadilla** [comment]
Outdated due to redesign - we do have a ticket for the blog image being right aligned: #2306 though.
