### ISSUE TITLE
Item level of taxonomy back end missing breadcrumbs

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2427]
When editing individual items in any taxonomy, the breadcrumbs don't include the full path. 

**List view of Sections:** 
Home >> Administration >> Structure >> Taxonomy >> Edit Site Sections

![image](https://user-images.githubusercontent.com/39384914/64728914-18f8d400-d4aa-11e9-9d94-c6b4cb8306d8.png)

**Edit Individual Site Section**
Home >> Cancer Moonshot℠

The path of this site section is: /research/key-initiatives/moonshot-cancer-initiative

<img width="575" alt="Screen Shot 2019-10-21 at 4 12 13 PM" src="https://user-images.githubusercontent.com/29731392/67239635-9dc9fc80-f41d-11e9-9a92-7462cbe02b9b.png">

**Comment by andyvanavery31** [comment]
Cannot reproduce the issue.
