### ISSUE TITLE
Need a way to clear the CTS Search Forms

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2429]
For both Basic and Advanced form, we need to implement a way to "clear" the form fields.

@lburack can you please provide your suggested UX for this option?
Relates to Sept. 9 comment on https://tracker.nci.nih.gov/browse/OCECREATIV-3164

**Comment by lburack** [comment]
Spoke with @mworrest and @blilianyu. Going to try to add this to the bottom sticky on Advanced Search Form. It will get lost elsewhere on the form.

**Comment by mworrest** [comment]
![clear-form-button-desktop](https://user-images.githubusercontent.com/4921685/65460760-9dd7dc00-de20-11e9-9e78-504a8af830fc.jpg)
![clear-form-button-mobile](https://user-images.githubusercontent.com/4921685/65460761-9dd7dc00-de20-11e9-997e-9573cfddf59e.jpg)

**Comment by lburack** [comment]
Assigning this over to @arcepaul and @NIsaf for implementation. Thanks, @mworrest and @blilianyu!

**Comment by VictoriaSunNIH** [comment]
@arcepaul - we're good to go with this implementation - Lynn approved!
