### ISSUE TITLE
Attach Promotional Image fields to Home/Landing Page content type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#244]
Attach [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image) to [Home/Landing Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-Page). Dependent on #421.

**Comment by bgnih** [comment]
Approach:  Add the `field_article_image` and `field_promo_image` entityreference field configuration changes to the `.../cgov_home_landing/config/install` folder.

**Comment by bryanpizzillo** [comment]
@nicolecrom I assume you mistyped this and it should NOT add Article image to the Home/Landing page. Correct??

**Comment by bryanpizzillo** [comment]
> @nicolecrom I assume you mistyped this and it should NOT add Article image to the Home/Landing page. Correct??

Well, I see the description now. I updated the title to reflect what this story actually is.
