### ISSUE TITLE
Do not cache PDQ Images

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2449]
The image on the PDQ page below was recently updated but the file name remained the same.

https://www.cancer.gov/types/brain/patient/child-glioma-treatment-pdq

One user has the old image cached and is not able to see the new image that is being served up through Akamai.

PDQ images should not be cached as they are not fed through Drupal, but rather come in from the CDE.

**Comment by blairlearn** [comment]
Created a rule for the PDQ image and audio paths to:

* Force the CDN cache to revalidate before serving up the file.
* Send a `cache-control: max-age=0, no-cache` header downstream.
