### ISSUE TITLE
Attach Article/Promo Image fields to Article content type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#245]
Attach [Article Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#article-image) Field and [Promo Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#promotional-image) Field to [Article](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article) Content Type. See #421 for the field storage.

**Comment by bgnih** [comment]
Approach:  Add the `field_article_image` and `field_promo_image` entityreference field configuration changes to the .../cgov_article/config/install folder.
