### ISSUE TITLE
Glossary Term Definition is not showing

### ISSUE THREAD

**Issue by venglisch** [NCIOCPL/cgov-digital-platform#2453]
There exists a glossary term that - when clicked - the glossary definition does not get displayed.  The summary is 
https://www.cancer.gov/espanol/tipos/pulmon/paciente/tratamiento-pulmon-celulas-no-pequenas-pdq
Search for *estadio IIIA*.  There is no definition pop-up when clicking this term.

It appears that clicking this term causes a JS error.  The error message comes from Common.js and is:
"dictionary request failed. lookup:term, id:045367"
and
"parsererror SyntaxError: Unexpected token in JSON at position 5913"

<img width="890" alt="Screen Shot 2019-09-24 at 16 52 57" src="https://user-images.githubusercontent.com/28308671/65549583-d2fd3080-deeb-11e9-8960-63ef31e274f7.png">

**Comment by bryanpizzillo** [comment]
This is not an issue for me on prod right now. Closing
