### ISSUE TITLE
Implement ability to "refine search results"

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2454]
As part of the CTS Migration - we need to implement new functionality that allows users to refine their search results.

## Requirements/Scenarios:
**Scenario 1:**  Users submit a search, and click the "back" button on their browser window.  They should be taken back to the form they were previously on (either basic or advanced), and the form should retain the inputs they had previously entered for their search.

**Scenario 2:** Users submit a search without search criteria.  They should see an option on their screen to "Refine Search Results".  Selecting this link should lead users to a blank Advanced Form (since no criteria was previously provided).
For results pages with no search criteria:
![image](https://user-images.githubusercontent.com/31222859/65614016-e8726900-df84-11e9-9c13-cf6203f4b4d6.png)

**Scenario 3:** Users submit a search with search criteria (either basic or advanced form).  They should see an option on their screen to "Refine Search Results".  Once users click this option:
1. Users are returned to the Advanced Form only.  
2. If users have come from the advanced form, any search criteria that was previously entered is retained in the Form.
2. Any previously entered search criteria from the Basic Form is populated into the Advanced form
  * If a user selected a primary cancer from the dropdown on the Basic Form, it is populated in the primary cancer dropdown on the Advanced Form
  * If a user entered a keyword and did not select a primary cancer, it is populated in the Keywords field on the Advanced Form
  * If a user entered an Age, it is populated in the Age on the Advanced Form
  * If a user entered a Zipcode, it is populated in the Zipcode field on the Advanced Form (and Zipcode is automatically selected in the Locations section of the form)

For results pages with search criteria:
![image](https://user-images.githubusercontent.com/31222859/65614025-ec9e8680-df84-11e9-98f3-53106a7d088f.png)

**Comment by mworrest** [comment]
Change to modify :) @blilianyu and I worked on a no results screen. Some wordsmithing may happen as we haven't shown the client yet.
![NO RESULTS](https://user-images.githubusercontent.com/4921685/68712049-e4b49900-0568-11ea-815b-21db35765879.jpg)
