### ISSUE TITLE
Implement Github Rebase Feature 

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2455]
## Description 

Someone has made a [Github Action](https://github.com/cirrus-actions/rebase) that allows one to just add /rebase as a comment on a PR to trigger a rebase and force-push. This will very much help the PR approvers to pull in tickets as we will not have to clone other developer's repos and get them setup only to just rebase. The code however should be a little more discerning.

*  Create the following:
    * a github action (in a separate repo) based off that code which only allows the rebase:
       1. the comment is made on a PR
       2. the source pr is NOT this repository, or maybe a better way to say is that the source is a *fork* of this repository
       3.  the  branch is PRable.
            * Also maintainers can change?
    * create a `/.github/workflows/rebase.yml` workflow config loosely following the instructions at: https://github.com/cirrus-actions/rebase (but of course taking your new action into account)

**Comment by bryanpizzillo** [comment]
acquia_connector adds an external link to the menu bar, Urls that are external links can not have getRouteName called. The site section code to replace the taxonomy link was not checking if the link was routed or not.

**Comment by andyvanavery31** [comment]
Deemed out of scope. Other options may be investigated in the future. Closing this ticket.
