### ISSUE TITLE
Create a Controller to handle List Server subscription forms

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2469]
This is a placeholder issue, pending analysis/discussion of whether the functionality is needed or will be replaced with GovDelivery before the legacy servers are shut down.

---
This is a replacement for the legacy SubscribeToListServ.aspx HTTP Handler.

* [ASP.Net IHttpHandler implementation](https://github.com/NCIOCPL/wcms-cde/blob/master/CDEFramework/Libraries/NCILibrary/Code/NCILibrary.Web.CDE/HttpHandlers/ListservSubscriptionHandler.cs)

**Comment by blairlearn** [comment]
Pages using the subscription handler:

* https://www.cancer.gov/resources-for/hp/education/cancer-patient-education-resource

**Comment by blairlearn** [comment]
**_If_** we implement this, it would likely be in dynamic services.

* [CDE ListServ HttpHandler](https://github.com/NCIOCPL/wcms-cde/blob/master/CDEFramework/Libraries/NCILibrary/Code/NCILibrary.Web.CDE/HttpHandlers/ListservSubscriptionHandler.cs)
* [HTTPHandler configuration entry](https://github.com/NCIOCPL/wcms-cde-config/blob/master/CDESites/CancerGov/SiteSpecific/CancerGov.Web/Web.config#L367)

**Comment by andyvanavery31** [comment]
Legacy servers are gone. Closing this ticket.
