### ISSUE TITLE
Correct punctuation on cropping tool

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2470]
The cropping tool is asking for aspect ratios, so instead of an x between the numbers it should be a : 

4:3
3:4
1:1
16:9
9:16

![image](https://user-images.githubusercontent.com/39384914/66330318-27e27300-e8fe-11e9-8a9e-4177026a161d.png)

**Comment by blairlearn** [comment]
This appears to be a small configuration item, so 20 minutes to fix plus build time and testing.

**Comment by andyvanavery31** [comment]
This is a non issue.
