### ISSUE TITLE
Change Request: Update Spanish Livehelp Queue in Spanish Clinical Trials Popup

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2473]
Request received on CGOV-10614 from Meghan Alleyne

"We would like to switch the queue of where the Spanish LiveHelp popup takes you on the various spanish clinical trials pages.

The popup currently appears on CT search and on various cancer type search string pages:  https://www.cancer.gov/espanol/cancer/tratamiento/estudios-clinicos/que-son-estudios.

In these popups, when a user clicks, they are currently taken to our general spanish cancer queue. We would like them to be routed to the spanish clinical trials queue so that trained agents can reply without transferring."

Per Mark on 10/8: 

File lives here: /docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveChat/LiveChat.js,

**Comment by venglisch** [comment]
This is the Spanish version which is fixed with #2472.
