### ISSUE TITLE
CTS - Change Placeholder Text when Selection is Unavailable

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2482]
For fields that have no available selections, disable the field and replace placeholder text.

When Choroid Plexus Cancer is selected from Primary Cancer Type/Condition on advanced search, users are unable to select a stage. In cases like this, make this field disabled and replace the placeholder text inside the box: "No available options based on your previous selections"

This came up during our demo meeting 10/16.

**Comment by VictoriaSunNIH** [comment]
this was implemented.
