### ISSUE TITLE
CTS - Visually Indicate that Field is Populated when Modifying Search

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2483]
Consider a visual indicator for populated fields when you come back to advanced after modifying search on results page. The flow should include coming from basic and advanced. Users coming to a results page from a link given to them won't have the context of which criteria were selected unless they open the drop down so if the search was performed on advanced, they should see the yellow highlights when they modify the search.

- Green outline? This conveys validation so would we be mixing messages?

**Comment by mworrest** [comment]
We will use a yellow highlight #FEE685 (USWDS .bg-yellow) per Lilian's suggestion.
![image (3)](https://user-images.githubusercontent.com/4921685/67032024-c467fa80-f0e0-11e9-8504-bbd0ce187b77.png)

**Comment by VictoriaSunNIH** [comment]
This was implemented for coming from basic search.  Advanced search will be a separate change request.
