### ISSUE TITLE
Implement Simple JSON Settings editing for App Module Instances

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2487]
## Description 

The ticket #2486 is what we really want for managing App Module instance settings. That being said, it is quite complicated and will require more time that we can alot right now. So for this ticket we need to:
1. Modify the AppModuleReferenceSelectWidget to add a text area field that:
    * When generating the form
       1. Serializes the AppModuleReferenceItem data property to JSON
       1. Populates the text area with that JSON as a string
    * When handling the submission
       1. Parses the JSON object
           1. If the JSON is invalid an error message should be displayed to the user indicating the field is invalid and the save should be prevented. 
       1. Deserializes the JSON object to a PHP assoc array
       1. Sets the AppModuleReferenceItem data property to that assoc array.
2. Create test coverage for:
     1. The form should be generated when there is no AppModuleReferenceItem data
     1. The form should be generated when there is AppModuleReferenceItem data
     1. No settings data was provided, and thus no settings data is saved.
     1. A valid JSON object was provided
     1. An invalid JSON object should prevent saving and display a message to the user indicating that the settings are invalid.

NOTE: The AppModuleReferenceSelectWidget uses the Forms API, so the implementation should follow proper usage of the forms API. (e.g. setting the validation on the fields, etc.)

**Comment by bryanpizzillo** [comment]
So it seems that the data property was not configured 100% correct. There is a way for the property to automatically serialize and deserialize. This was done in 8.7 so there are not a lot of docs. This ticket should also take care of that as well.

**Comment by blairlearn** [comment]
Closed in e2b7b8ec5450a170b0e374b9c47c2ecbe318fd51
