### ISSUE TITLE
Attach Citations Field to Article Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#249]
Attach [Citation Content](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citation-content) #425 and [Citation Pub Med ID](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citation-pub-med-id) #426 common fields to [Article Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article) Content Type

**Comment by VictoriaSunNIH** [comment]
This has been completed on dev.
