### ISSUE TITLE
Attach Body Text Field to Article Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#250]
Attach [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body) Common Field #29 to [Article Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article) Content Type

**Comment by bryanpizzillo** [comment]
Article got its own local Article Body field in #29, with that this got closed.
