### ISSUE TITLE
Table class not being pulled in Drupal

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2500]
If there is a case to keep the styling of table, then the default table class (class="table-default") should be added when you create a table in the WYSIWYG.

If all tables are expected to have the styling of `class="table-default"`, then table should be styled to be the default.

**Note to** @lburack @laurelthrash  - once this bug is fixed, the Drupal training guide needs to be updated.

**Comment by lburack** [comment]
Might be wise to work on this ticket along with #2474 (or at least have a dev verify if that makes sense/is efficient)

**Comment by andyvanavery31** [comment]
Dependent on the update from CK4 to CK5. Being put on hold.

Accessibility of the table and its headings needs to be investigated and addressed on a different ticket.

**Comment by zhuomingao** [comment]
[table_cgov.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188578/table_cgov.csv)
[table_dceg.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188579/table_dceg.csv)
[table_ttc.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188580/table_ttc.csv)
[table_ccg.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188581/table_ccg.csv)
[table_sbir.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188582/table_sbir.csv)
[table_nano.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14188583/table_nano.csv)

**Comment by zhuomingao** [comment]
Hi @andyvanavery31 , reports of pages contain table in WYSIWYG have been attached.

**Comment by zhuomingao** [comment]
[tabledefault_cgov.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14620492/tabledefault_cgov.csv)
[tabledefault_dceg.csv](https://github.com/NCIOCPL/cgov-digital-platform/files/14620493/tabledefault_dceg.csv)

**Comment by andyvanavery31** [comment]
Closing this ticket. Further evaluation of tables will occur in the redesign of inner pages.
