### ISSUE TITLE
Card Title - Update Tooltip 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2501]
Need to update the tooltip for Card Title. It's referencing a field (short title) that doesn't exist anymore.

- **Current Tooltip Text:** A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.
- **Change Tooltip Text to:** A shortened version of the title, for use in cards and lists. If left blank, browser title will display instead. 

Field Name: field_card_title - this is a shared field as per https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#card-title

```gherkin
Scenario: Card Title field tooltip update
Given Content creator is adding a card title to any content type 
When the content creator looks at the field_card_title field
Then they will see a field with the title "Card Title"
	And that field will have a tooltip that reads "A shortened version of the title, for use in cards and lists. If left blank, browser title will display instead. "
	And the field is not required.
```

**Comment by VictoriaSunNIH** [comment]
@suryatheja-muppalla  - please also update the tooltip text on Infographic and Video media types.  

cc: @alinai for catching this one

**Comment by suryatheja-muppalla** [comment]
@VictoriaSunNIH @alinai  Updated the tooltip text on File, infographic and video media types.

**Comment by alinai** [comment]
Looks good on test-acsf.

**Comment by alinai** [comment]
Looks good on test-acsf - (2nd round)
