### ISSUE TITLE
Add a "Ready to Test" flag to the DOM at the end of all page load JS execution.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2508]
For test-automation purposes, we need a way of knowing that the DOM is ready for examination, regardless of whether all images, fonts, etc. have finished downloading. This flag should be set when:

1. The request to load the page has finished.
2. All of the JavaScript has loaded.
3. All JavaScript has executed in response to the page onReady event. (We're not as concerned about asynchronous calls initiated by JS, though there may need to be consideration for the various client-side applications.)

An initial thought is to add a script tag at the very bottom of the page (so it's executed last), _without_ async or defer, and have that set a `ReadyToTest` flag on the `window` object with a value of `true`.

**Comment by andyvanavery31** [comment]
Closing due to a different test automation tool being used currently compared to the creation of this ticket.
