### ISSUE TITLE
Integrate clinical-trials-search-app and cgov_cts modules.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2510]
## Description 
There were issues when #2502 was being built that did not allow the clinical-trials-search-app react app to be added to the cgov front-end source. Once those issues are worked out this should be:
1. Update package.json to include the clinical-trials-search-app
    * we had to include tarballs. This can be seen in https://github.com/bryanpnih/cgov-digital-platform/blob/ticket/2502-integrate-cts-js/docroot/profiles/custom/cgov_site/themes/custom/cgov/package.json#L18
2. Update the cts library to initialize the react app. This can be seen in https://github.com/bryanpnih/cgov-digital-platform/blob/da260fd8c4ade1c3f0532586d360cdfe5d461583/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/cts/cts.js

**Comment by andyvanavery31** [comment]
This ticket is being closed due to #3303 . This removed the cgov cts code.
