### ISSUE TITLE
CTS: Investigate excluding trials from search results with no participating sites on Blue

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2512]
Through the Finding Clinical Trials Committee (FCTC), CCCT/CTRP requested a number of potential enhancements to CGov CTS. One of the updates they asked for was to have the option to include or exclude trials from search results that do not have any active NCI study sites. This investigative ticket was to make the update to exclude these sites.

Proposed update copied from 8/20/2019 notes: Option to include/exclude rials with no participating sites 
	Many of these trials are pharmaceutical studies with active status, but no active NCI sites. However, it needs to be determined if keeping out an “active” study with no active sites will have unintended consequences of keeping out trials that should not be kept out.  OCPL can build/tweak a query of what we might search for (for an active site and what should be shown), and work with CCCT to review the results that come back. Based on the results, a joint decision can be made on how to proceed.

Sarina updated queries on the current CTS to exclude these results and put them on Blue https://www-blue-dev.cancer.gov/about-cancer/treatment/clinical-trials/search.

From Sarina re update made to Blue: Previously, CTS was only filtering by active sites if the search included location filters (by zip code, city/state, etc.). This update includes filtering by active sites on all searches, so trials returned include only sites that are actively recruiting.

**Comment by VictoriaSunNIH** [comment]
CIS said we should always show all trials so we are not doing this on prod. Closing as completed
