### ISSUE TITLE
Update BLT

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2513]
## Description 

We need to go from 9.2.x to 10.X (10.5 at the time of this ticket) The impetus is that Acquia support is now bringing it up when we are encountering platform issues.

**Comment by blairlearn** [comment]
Additional impetus: BLT 9.2.x is [end of life on December 1, 2019](https://docs.acquia.com/support/eol/?mkt_tok=eyJpIjoiWWpJd01tRXhORGt3TmpNMSIsInQiOiJSSzU2Y3VQdkhCVWJaK1wvUCtGanU0aE44UEJoM0dXSjlxUGpodmc2VExKTk8rUU5hQmorZWxGV1ArbXpVVjJQNmdLV3lpZk1GaGZkV3E3OUpibE5UTWJRRTNPdjBLTVRTWThjaEdhWFMxbzdkbTlDZGdZUFwvQVpORkMyTmFCeis1In0%3D).

**Comment by bryanpizzillo** [comment]
This went live. Closing
