### ISSUE TITLE
App Module Page Templates to show left nav/not show left nav

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2515]
We need to implement an option of the App Module Page content type in Drupal to show/not show left navigation (1 column/2 column layouts).

We need to also build out page templates for these displays:
- Page with left nav (2 column)
- Page without left nav (1 column)

**Comment by bryanpizzillo** [comment]
So quick approach:
1. Create a field to select template - field_page_template
2. Add a `cgov_application_page_theme_suggestions_page_alter` suggestion hook to cgov_application_page.module
    1. if bundle NOT cgov_application_page  or entity is not node return
    2. add a suggestion for:
```
    // Add theme suggestion of 'page__article', 'page__biography', etc.
    $content_type = $node->bundle();
    $suggestions[] = 'page__' . $content_type . '__' . $node->field_page_template->value;
```
