### ISSUE TITLE
Update YAML content for Spanish Grants and Training URL

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2530]
The URL for the Spanish Grants and Training YAML content is incorrect and should be updated.

It currently loads as cancer.gov/espanol/grants-training.

It should be cancer.gov/espanol/subvenciones-capacitacion

Please update the YAML file pretty URL.  Thanks!

**Comment by andyvanavery31** [comment]
Closing due to Redesign and update of the YAML.
