### ISSUE TITLE
Create Zip Code Service

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2543]
Create a RESTful API for looking up geolocation based on Zip Code. 
* This should take in a zip code and:
   * if found, return a longitude and latitude with a 200 status.
   * if not found return a 404
* This should only be available to the host header that was passed in. (e.g. NO CORS)
* This should allow for caching of the response, with a cache tag of api:zip-code-lookup. (unless we find a better tag) This is to allow us to clear the cache upon updating the Zip Lookup File
* The location of the zip lookup file should be configurable and not stored in source control. This is because it should not be publicly available.

This should be implemented using the RESTful API module from Drupal, live in the cgov_cts module and have tests.

**Comment by bryanpizzillo** [comment]
A couple of things:
1. I used a free zip code DB resource to generate a database and then I added to source control. 
    * This has been configured to be used by default, but settings.php can contain `cgov_cts_zip_lookup_path` which indicates the path to an alternate file.
2. CORS may or may not be disabled. Unfortunately it seems that Drupal will enable it for all resources or none. I do not believe we enabled it globally, but it could have been done through blt. I did not test it and we can treat it as a backlog item to get this out the door.
