### ISSUE TITLE
Empty Research Card Should Be Automatically Removed from CTHP

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2551]
Client reported an empty research card on the [Pheochromocytoma and Paraganglioma CTHP](https://www.cancer.gov/types/pheochromocytoma) and an empty [P&P research list page](https://www.cancer.gov/types/pheochromocytoma/research). Here's a screenshot since I will clean that up after logging this bug:
![screencapture-cancer-gov-types-pheochromocytoma-2019-11-15-17_55_31](https://user-images.githubusercontent.com/29731392/68981470-7b838e80-07d1-11ea-9dbd-cdff6878dc22.png)

Pre-migration, a 2012 press release was linked on that card. The 2012 press release did not get migrated.

The business rule for the CTHP Research card was that if it was empty (no links to pull from the Research List Page), the card would not display. Tagging @VictoriaSunNIH for verification on this requirement.

**Comment by sarinapadilla** [comment]
This empty research card has since been removed, and the cancer research list page has been removed as well. Closing!
