### ISSUE TITLE
Clinical Trial Advanced Form does not appear on IE 11.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2570]
1. Launch IE 11
2. Go to `/about-cancer/treatment/clinical-trials/search`
3. Click the "advanced search link"

The underlying error is "'IntersectionObserver' is undefined."

**Comment by blairlearn** [comment]
Possible Polyfill: https://github.com/w3c/IntersectionObserver

https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js

**Comment by arcepaul** [comment]
Interesting!  This is my first time seeing this polyfill.  I was just going to disable it for IE but if this works, it's worth testing.
