### ISSUE TITLE
Redirecting about-cancer/treatment/clinical-trials/advanced-search yields bad URL

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2603]
As part of CTS go live, when we redirected about-cancer/treatment/clinical-trials/advanced-search using a Drupal redirect, we got redirected to this URL: https://www.cancer.gov/about-cancer/treatment/clinical-trials/search?app_module_route=/advanced&&app_module_id=cgov_cts_app

It should have just been /about-cancer/treatment/search/advanced

Needs investigation - for now we've routed through akamai to avoid the wrong URL and wrong CTS form being loaded (it's loading basic instead of advanced)

**Comment by sarinapadilla** [comment]
We are moving towards having Akamai handle our redirects instead of Drupal. This also was updated with the move of CTS from /`about-cancer/treatment/clinical-trials/search/advanced` to `/research/participate/clinical-trials-search/advanced`.
