### ISSUE TITLE
Site sections won't allow draft translations content to be made the landing page

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2604]
Issue:
On NCI-CONNECT, it won't let me assign anything as the landing pages for the new site sections

All the pages are:

- translations
- in draft (never published) 

I'm unclear which of these factors is affecting the placement.

Expected Outcome:

- For a newly created site section, I should be able add the following as the site section's landing page:
  * An English page that is in any state (draft, review, published)
  * A Spanish page that is in any state (draft, review, published), that has an English translation in published state
  * A Spanish page that is in draft any state (draft, reviewed, published) state, that has an English translation in any state (draft, reviewed, published)

**Comment by bennettcc** [comment]
Removing this item from the NCI Microsite sprint

**Comment by blairlearn** [comment]
Cannot duplicate this problem
