### ISSUE TITLE
Update Drupal Core to next minor version: 8.9.x

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#2607]
## Description 
Drupal 8.7 is EOL and there is a security patch that requires an update to the next minor version. Drupal 8.9 is the LTS version now that 9.0 is out, so we should skip 8.8 and try to get to 8.9 which should be good until 11/2021.

**Comment by bryanpizzillo** [comment]
### Notes
* 
* This requires Pathauto 1.6 because of the changes for aliases to entities.  Cgov-digital-platform #2810

**Comment by bryanpizzillo** [comment]
### Attempt 2
Followed https://www.previousnext.com.au/blog/updating-drupal-880-beta-composer

1. Upgraded pathauto to 1.6
2. Removed old webflo/drupal-core-require-dev
    * `composer remove --dev webflo/drupal-core-require-dev`
    * First attempt failed with "Cannot apply patch 3029219"
3.

**Comment by bryanpizzillo** [comment]
## Attempt 2.5
1. `composer cgov-clean && composer install`
2. Removed the following patches from `drupal/core` in composer.json:
    ```
    "3029219 : State transition validation ignores language when determining \"first time moderation\"": "https://www.drupal.org/files/issues/2019-03-24/3029219-8.patch",
    "3045648 : Use language for determining initial moderation state": "https://www.drupal.org/files/issues/2019-04-07/3045648-15.patch",
    ```
3. `composer cgov-clean && composer install`
4.
