### ISSUE TITLE
Hide alt text field on image entity embeds -- affects entity_embed 8.x-1.0

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2608]
Issue found when testing PR #2606 (issue #2605) 

Images embedded in the WYSIWYG should **not** have the _Alternate text_ field. This field is on the image media item itself.

If for some reason there's no plausible way to hide the _Alternate text_ field from the Embed media window, then we will need to further discuss requirements.

This affects both Contextual Images and Images.

Currently on PROD, this is the modal a user sees when they click to embed an image via the WYSIWYG:
<img width="300" alt="PROD WYSIWYG image embed" src="https://user-images.githubusercontent.com/29731392/72077803-de6f3e80-32c5-11ea-9a31-56cad605c718.png">

This is the modal I'm seeing on ODE 313 when I try to embed an image via the WYSIWYG:
<img width="500" alt="ODE 313 - WYSIWYG image embed" src="https://user-images.githubusercontent.com/29731392/72077825-ed55f100-32c5-11ea-9c03-c8963354b0d1.png">

**Comment by VictoriaSunNIH** [comment]
OBE - this is ok now with the updated drupal version 8.9
