### ISSUE TITLE
Issues working with non-translated Spanish content

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2609]
On NCI-CONNECT the client created three pages and set the language as spanish, instead of creating translations of english pages.

These pages have a few different issues (so far)

- They won't preview - clicking on the title and looking at the URL results in a 404 (see https://nciconnect-cms-dev.cancer.gov/rare-brain-spine-tumor/node/1149621)

![image](https://user-images.githubusercontent.com/39384914/72109727-78ee7280-3304-11ea-96c8-aa8e752e5b75.png)

- They won't delete - attempts to delete them result in an error message

![image](https://user-images.githubusercontent.com/39384914/72109592-32991380-3304-11ea-88b4-96f7dd287e84.png)

This is true on Dev and Prod. Attempts to preview and delete english content worked fine. 
Changing the language on the item from Spanish to English resolved .

**Comment by bennettcc** [comment]
Removing this ticket from the NCI Connect milestone -- not critical for go live as all content will be translated from english to spanish (not created initially in spanish)

**Comment by VictoriaSunNIH** [comment]
related to how drupal automatically links to the english version if you are creating spanish only content.  should be resolved by #1853
