### ISSUE TITLE
Links to HP radiation therapy terms not working on Cancer.gov

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2614]
Issue reported by Robin Juthe on 1/16:

The links to HP radiation therapy terms are not working on Cancer.gov.

For example, in the Childhood CNS Germ Cell Treatment summary, the second instance of the term "stereotactic radiosurgery", which is linked to the glossary term, is underlined on Cancer.gov but nothing happens when you click on the term. 

As a reminder, these HP radiation therapy terms are a special type - the definitions have an HP audience but no dictionary.

Other terminology links in the summaries (e.g., for LOE terms, dictionary of cancer terms, and HP genetics terms) are working fine on Cancer.gov.

**Comment by blairlearn** [comment]
In `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/dictionaryService/index.js`, the "dictionary of dictionaries" doesn't include an entry for the "notset" dictionary. This causes the look up at line 55 to fail.

**Comment by blairlearn** [comment]
Examples for testing (substitute hostnames as appropriate):
* http://www-dev-ac/types/brain/hp/child-glioma-treatment-pdq
   * 3-dimensional conformal radiation therapy
   * Stereotactic
   * Reese-Ellsworth grouping system
* https://www-dev-ac.cancer.gov/espanol/tipos/cerebro/paciente/tratamiento-cerebro-infantil-pdq
   * oncólogo pediatra
