### ISSUE TITLE
Modify the microsite CSS to unhide the translation toggle

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#2617]
Expected behavior:
- When a piece of content has an existing translation, the toggle should appear.

**Comment by mworrest** [comment]
The color of the text for the language toggle is Asphalt - #2e2e2e and the background on  tablet/mobile is Sky Blue - #77bcff. 

Is it possible to hide the language toggle (and background color) when no translation for the page exists?

**Comment by blairlearn** [comment]
This is replaced by #2625
