### ISSUE TITLE
Microsite Purple Theme - Fix to View Infographic button

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2618]
**Description of Issue:** The View Infographic button is missing styling. The styles should replicate the Enlarge button.  

**Business Value:** NCI-CONNECT requires this style to be in place to launch translations and content updates. 

**Incorrect Style:** 
![image](https://user-images.githubusercontent.com/39384914/73292948-fb19da80-41d0-11ea-85c9-f1ccdf9ccd32.png) 

**Correct Style:** 
![image](https://user-images.githubusercontent.com/39384914/73292918-ee958200-41d0-11ea-94db-99a8223edd4a.png)

**Acceptance Criteria:**
1. Text should be White
2. Background Color for "View Infographic" should be Azure (#1e6fd6)
3. Hover Background Color should be Sangria (#951b81)

**Additional Notes:** 
* The original requirements for this button are located here: https://github.com/NCIOCPL/cgov-digital-platform/issues/817
* Example URL:

**Comment by adriancofie** [comment]
@blairlearn 

FYI, currently if you directly view an infographic page it has the correct style. The incorrect style shows when you embed the infographic on another page. 

At a minimum the "article-image-enlarge" class should be added to the anchor element within the figure tag.

E.g:

```
<figure class="large centered-set"><div class="centered-element">
              <img longdesc="/rare-brain-spine-tumor/media/1149711/long-description" src="/rare-brain-spine-tumor/sites/g/files/xnrzdm226/files/styles/cgov_article/public/cgov_image/media_image/2020-01/Spine-Functions-infographic.gif?itok=RIjiO7Qu" alt="Spine anatomy and functions" width="970" height="1202">

<a href="/rare-brain-spine-tumor/tumors/anatomy/spine-functions-infographic" target="_blank" class="infographic-view-full **article-image-enlarge**">View Infographic</a>
              </div>
        </figure>
```

Some other refactoring can be likely be done, but the above gets it working.

Relevant CSS

**Purple.css**

```
figure a.article-image-enlarge {
  background-color: #1e6fd6; }
  figure a.article-image-enlarge:hover, figure a.article-image-enlarge:focus {
    background-color: #951b81;
    color: #fff; }
```

**Common.css**
```

a.infographic-view-full, a.video-view-full {
  background-color: rgba(18, 62, 88, 0.7); }
  a.infographic-view-full::before, a.video-view-full::before {
    width: 1.25em;
    height: 0.78125em;
    background-position: 5.84795% 21.92621%;
    font-size: .9em;
    -webkit-transform: translateY(-50%) rotate(90deg);
            transform: translateY(-50%) rotate(90deg); }

```

**Comment by blairlearn** [comment]
The infographic-view-full classes were missing from the purple.scss.
