### ISSUE TITLE
Removal Delighter from NCI Connect Spanish Translation

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2620]
The delighter on the spanish translated NCI Connect site needs to be removed.

We should configure the delighters so that NCI Connect Spanish URLs are excluded from display of the delighter.

https://www.cancer.gov/rare-brain-spine-tumor/

**Comment by blairlearn** [comment]
Need to modify the rule for when the NCI-connect delighter is displayed to exclude the Spanish version of the micro-site.  Should be a regex in the rules.js file.

Rules file: docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/rules.js

Explanation of how that works: docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/floatingDelighter/README.md
