### ISSUE TITLE
Add Spanish Logo image for use on NCI Connect spanish translation

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2622]
The spanish CCR logo for the spanish microsite homepage needs to be added so that it can be placed for use on the microsite. 

Please see the two images attached on this JIRA ticket(Github doesn't support this file type for attachments): https://tracker.nci.nih.gov/browse/CGOV-11224

**Comment by blairlearn** [comment]
Need to add a Spanish version of the Site Banner block and then make the theme use it.

**Comment by blairlearn** [comment]
Post deployment:
1. Go to Custom block library
2. Find the "NCI Connect Site Banner" Raw HTML block
3. Create a translation.
4. For the body of the HTML block, use this (**NOTE:** The alt text should be translated):
```
<div class="slot-item only-SI nci-logo-pages large-12 columns">
  <a href="/rare-brain-spine-tumor">
    <img src="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/logos/ccr-logo-full-es.svg" alt="National Cancer Institute Center for Cancer Research" />
  </a>
</div>
```
5. Save and publish.

**Comment by claireblaustein** [comment]
For the record - alt text translation:
Instituto Nacional Del Cáncer Centro de Investigación del Cáncer

**Comment by blairlearn** [comment]
The alt text is in the Raw HTML block.  You can edit that directly.  :-)

**Comment by claireblaustein** [comment]
Yep. Wanted to document here just in case.
