### ISSUE TITLE
DCEG Search results are sensitive to accent marks and can have differing results when accents are used/not used

### ISSUE THREAD

**Issue by goldenec** [NCIOCPL/cgov-digital-platform#2624]
**Problem**
When a search term includes an accent mark, the search results differ from the same query without an accent mark. When users enter the query with an accent mark, key results can appear low. This has become a particular issue for DCEG, given their deputy director's name has an accent mark.  https://tracker.nci.nih.gov/browse/CGOV-11190.

Although this issue is most apparent for DCEG right now, we should consider how accent marks and other similar characters affect results in English and Spanish. Here is a list of potential characters to consider. https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html

**Requested change**
First suggestion is to make search strings insensitive to accent marks and similar "diacritical characters". The feasibility of this, or other potential solutions, should be discussed with Sarina or other developers. 

**Acceptance criteria**
The search results are the same for a query with an accent (or character with diacritical mark) and a query without. 

This ticket will be updated as more information is available. 

**Additional Examples of Names with Accents** 
**_Note_**: these are fellows **without** their own specific biography page; their names are included in the body of Current Fellows pages

1. Daphnée Villoing  - Search of Daphnée Villoing  with accent finds 8 items, and her bio paragraph on the REB fellows page comes up 3rd in search. Search of “Daphnee Villoing” without accent only brings up one item: https://dceg.cancer.gov/news-events/news/2019/srk-dcdp-2020. Search for just “Villoing” brought up all 8 items.

- **Expected Behavior:** The search results are the same for "Daphnée Villoing" and "Daphnee Villoing", bringing up all 8 pages where her name appears.

2. André Rose – Search of “André Rose” with accent brings up his bio paragraph on the REB fellows page, but also 3 other unrelated items. Search of “Andre Rose” without accent brings up the same list, but in different order. Search of just “Rose” brings up a list of items related to Dr. Rose Yang.
- **Expected Behavior:** 
  - Content matching both (1) "André" and "Rose" OR (2) "Andre" and "Rose" should get higher ranking and appear first. 
    - So search results for "André Rose" and "Andre Rose" should bring up the REB Fellows page, where his bio paragraph appears (https://dceg.cancer.gov/fellowship-training/what-our-fellows-do/meet-current-fellows/reb-fellows)
  - Content that matches "Andre" OR "Rose" should still appear in search results, but not given highest ranking.

3. Ebonée Butler – Search for “Ebonée Butler” with accent brings up nothing. Search for “Ebonee Butler” without accent brings up nothing. Search of “Butler” bring up 3 items, including her bio paragraph on the MEB fellows page. I noticed that she is listed on the MEB fellows page as Ebonée Nicole Butler, which may be what’s causing the problem.

**Comment by VictoriaSunNIH** [comment]
tracked via  https://tracker.nci.nih.gov/browse/CGOV-11190 and comments indicate this was fixed
