### ISSUE TITLE
Utility Bar Should Only Display if Microsite Has Translated Content

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2625]
Just like Cancer.gov, the utility bar for NCI-CONNECT will appear on all pages, but if the page doesn't have a translation, the language toggle link just doesn't display (see screenshots at the end below)

We (product owners and stakeholders) would like to have the utility bar only on microsites with translated content; the other microsites that do not have translated content should not display an empty language/utility bar.

```gherkin
Scenario: Able to toggle to a translation on desktop
  Given the user is viewing an English page on desktop with a Spanish translation 
  Then the user sees the 'Español' link in the top right on the page (utility bar area)
  When the user clicks the 'Español' link
  Then the page URL changes to the path of the Spanish page and the Spanish translated content displays
  And the language toggle link changes from 'Español' to 'English'
```

```gherkin
Scenario: Able to toggle to a translation on mobile
  Given the user is viewing an English page on a mobile device with a Spanish translation 
  Then the user sees the 'Español' link in the top right, on a white background in between the logo and the colored utility bar (where the program name is spelled out)
  When the user clicks the 'Español' link
  Then the page URL changes to the path of the Spanish page and the Spanish translated content displays
  And the language toggle link changes from 'Español' to 'English'
```

```gherkin
Scenario: No language toggle appears on desktop
  Given the user is viewing an English page without a Spanish translation on a desktop computer
  Then there is no 'Español' link in the top right of the page
```

```gherkin
Scenario: No language toggle appears on mobile
  Given the user is viewing an English page without a Spanish translation on a mobile device 
  Then no 'Español' link appears
  And there is xxx pixels of white space in between the logo and the colored utilty bar (where the program name is spelled out)
```

<img width="1452" alt="Screen Shot 2020-02-06 at 4 44 17 PM" src="https://user-images.githubusercontent.com/29731392/73981369-15a23100-4900-11ea-935f-5b3cf13534cf.png">

<img width="916" alt="Screen Shot 2020-02-06 at 4 44 54 PM" src="https://user-images.githubusercontent.com/29731392/73981378-19ce4e80-4900-11ea-88a7-bd616204f249.png">

**Comment by blairlearn** [comment]
* docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/theme-settings.php
  * Add setting for "Has translations"
* In docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
  * cgov_common_preprocess_html
    Conditionally add class "has-translated-content" if the "has translatons" setting is  turned on.
* Update CSS
  - Control visibility of the utility bar with the "has-translated-content" CSS class. (The language toggle itself is smart enough to only appear when the current content item has a translation.)
  - Figure out how to pull `.language-bar, #microsite-a .utility` out of microsite CSSes without breaking cancer.gov.

**Comment by blairlearn** [comment]
Two implementation options:
1. Add CSS to the default theme to show/hide the language bar depending on whether the `body` element has the `has-translated-content` class. This would require setting the `has_translations` setting during deployment or (more correctly) adding an update hook to check for the existence of non-English content.
2. Leave the language bar visible all the time in the main theme and control its visibility entirely from the child themes.

Given that we're unlikely to ever remove the non-English content from the main site, this solution opts for the latter solution.

**Comment by blairl-nih** [comment]
**Old behavior:** the default cgov_common theme (without a color variant) presented the language bar and the color variants hid it.

**New Behavior:** all variants on the theme are capable of presenting the language bar. There is a new "Has Translations" setting on the cgov_common theme. If the option is set (default), the language bar appears, if it is not set, the language bar is hidden.

**Comment by blairlearn** [comment]
Set language toggle text color as follows:

theme | color name | RGB
 --- | --- | ---
purple| ultra-violet |  #6B35A6
green | ocean | #006789
blue | denim | #00527D
