### ISSUE TITLE
Create NCI Connect Spanish Sitewide Search Template

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2626]
The NCI Connect site is being translated to spanish -- we need to create the NCI connect spanish sitewide search template to ensure that the spanish search collects only spanish content and does not collect any english content.

**Comment by zhuomingao** [comment]
1. Search template: cgov_search_doc_es needs to be created
2. Search template: cgov_search_doc_en needs to be changed to test it is a EN page, since right now it is used regardless of language.

**Comment by VictoriaSunNIH** [comment]
This was completed in march, jsut needs to be closed
