### ISSUE TITLE
Call Spanish SiteWide Search Template

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2627]
The NCI Connect site is being translated to spanish -- a template will be created to allow the NCI connect spanish sitewide search template to ensure that the spanish search collects only spanish content.

Please create a call so that the spanish template is used when a user searches for spanish content.

**Comment by blairlearn** [comment]
@bennettcc - can you explain what this means?

**Comment by bennettcc** [comment]
Currently, one search template exists in NCI connect for existing english content.

Min will be creating a second search template allowing spanish content to be collected and displayed within search.  Min mentioned that a "call" will need to be created to tell queries made from the spanish sitewide search to only use the spanish search template.  @zhuomingao  could you provide Blair with the current english search template so he can see an example?

@blairl-nih Last week, you mentioned that this is likely a task that would require a javascript update.

**Comment by zhuomingao** [comment]
DOC EN search template name: cgov_search_doc_en

**Comment by blairlearn** [comment]
Worst. Ticket. Ever.

Created additional tickets for the actual items to be done:
#2679 - Add NCI Connect Spanish translation of Search HTML block
#2680 - Add CDE Config for NCI Connect Spanish Search
#2681 - Create NCI Connect Spanish search results page in Percussion
#2682 - Add NCI Connect Spanish search results to Akamai rule set.
