### ISSUE TITLE
Error on Console on clicking on Find more link on Statistics section on CTHP page

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform#2628]
Getting this error on Console on clicking on Find more link on Statistics section on CTHP page on both Stage and Prod

![image](https://user-images.githubusercontent.com/31008800/74264553-d3e20380-4cce-11ea-96a9-64fc909146de.png)

**Comment by andyvanavery31** [comment]
This ticket relates to the seer website, which is not the responsibility of the digital platform at this time. Therefore, it will be closed.
