### ISSUE TITLE
Analytics error when clicking "On This Page" links.

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform#2629]
When I clicked On This page link for Childhood Cancer on https://www.cancer.gov/publications/patient-education, this error is captured on console

![image](https://user-images.githubusercontent.com/31008800/74271073-4dcbba00-4cda-11ea-9467-8e4f1b7cc4a4.png)

**Comment by blairlearn** [comment]
Closing as this error no longer occurs.
