### ISSUE TITLE
Wrong revision displayed for PDQ Drug Information Summary

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#2631]
The weekly CDR publishing job sent several PDQ summaries to the production Drupal server late Friday afternoon 2020-02-07. All but one of those summaries were processed correctly, but the users noticed on the following Monday that the Drug Information Summary CDR767077 (_Blinatumomab_) was still showing the old information. A look at the _Revisions_ tab showed that the first and third rows from the top were both marked as _Current revision_ and the row in between them -- holding the new information published the previous Friday -- had the *Set as current revision* button. We clicked on that button to show that new information on the web site, but the page for the node in the CMS indicated that there was a draft available, so we checked and confirmed that the draft also contained the current information published the previous Friday and we made that draft publishable. It would be nice to know what caused this anomaly. Was there a race condition in effect? Was it related in some way to issue #2630? Did a user manually create a draft version of this node?

**Comment by bkline** [comment]
Revisions table following the weekly publishing job.

![image](https://user-images.githubusercontent.com/1634628/74289218-6f3d9d80-4cfc-11ea-8ef9-4ad94d7616e4.png)

**Comment by bkline** [comment]
This is what the _Revisions_ tab normally looks like for a PDQ node.

![image](https://user-images.githubusercontent.com/1634628/74289278-9eeca580-4cfc-11ea-95ef-e17cfd8b601a.png)

**Comment by bkline** [comment]
The problem happened again during this past Friday's weekly publishing job. We pushed 70 PDQ summaries to the production Drupal server. One of them (DIS node 1098823 from CDR791271) ended up with an extra copy of the earlier published revision plopped on top of the new version of the summary, in the same situation as illustrated in the first screen shot above. 
![image](https://user-images.githubusercontent.com/1634628/80997680-ab6e2f00-8e0f-11ea-8c7a-75c71294b442.png)

The process to resolve the situation was:
1. Cross your fingers.
2. Click the `Set as current revision` button on the second line in the revisions list.
3. Click the `View` tab.
![image](https://user-images.githubusercontent.com/1634628/80999290-67c8f480-8e12-11ea-8799-1dffe65e48ec.png)
4. Click on the yellow `DRAFT AVAILABLE` box in the upper right corner, opening a pop-out panel.
![image](https://user-images.githubusercontent.com/1634628/80998036-4109be80-8e10-11ea-99c5-28a807cf3557.png)
5. Click the `View existing draft` box.
![image](https://user-images.githubusercontent.com/1634628/80998164-77dfd480-8e10-11ea-9385-cb14a70a0519.png)
6. Verify that this draft has the correct, current content for the summary.
7. Click the red `DRAFT` box in the upper right corner, opening another pop-out panel.
![image](https://user-images.githubusercontent.com/1634628/80998286-ae1d5400-8e10-11ea-8661-fd09ffb2d189.png)
8. Click the blue `Publish` box.
![image](https://user-images.githubusercontent.com/1634628/80998388-e58c0080-8e10-11ea-8ed6-5e2db2e9d18d.png)
This is what you should see.
![image](https://user-images.githubusercontent.com/1634628/80998608-3996e500-8e11-11ea-8f00-7cfacb9231af.png)
9. Go back to the revisions page and confirm that the published revision is at the top of the list.
![image](https://user-images.githubusercontent.com/1634628/80999008-ef623380-8e11-11ea-95bb-72b4feeb061f.png)

**Comment by bkline** [comment]
One additional source of confusion: when you click `Edit` from the item in the content list page, what came up for this page (before fixing it using the previous steps) showed that the current state for what you are editing is _Published_ and the data is the correct, current data for the page (in this case, the _Updated Date_ is in April, as it should be), even though what the web site showed was the stale, incorrect data.
![image](https://user-images.githubusercontent.com/1634628/80999970-87145180-8e13-11ea-99ca-82370dfe3ace.png)

**Comment by bkline** [comment]
Slack exchange 2020-09-21

[Volker 10:56 AM]
Hey Bob, we have again a DIS that was pushed to Drupal but didn’t get published.  The new version is sitting in the list of revisions while the older version is still the “Current revision”.

[Bob  10:56 AM]
aargh!

[Volker 10:56 AM]
The document is CDR746946 - Ado- Trastuzumab Emtansine
[Volker 10:57]
The node is https://www-cms.cancer.gov/node/533049/revisions
[Volker 10:57]
From the logs on the CDR side it appears that everything went OK
[Volker 10:58]
It appears the version with the button “Set as current revision” is the correct version.
[Volker 10:59]
Under the section “Research Results and Related Resources”  There should only be 3 links for the current version.  The older version has 5 links.

[Bob 11:00 AM]
All the others OK?

[Volker  11:00 AM]
This is the only one William reported.
[Volker 11:00 AM]
I can double-check with him
[Volker  11:08 AM]
Looking at the content list in Drupal there are no other documents that are messed up like this.
[Volker 11:11]
When I list the documents (by document type) in Drupal, the documents are listed in chronological order - latest update first.  Going through this list I can see that Ado-Trastuzumab is included in this list although the “Updated” date is 07/17 instead of 09/18.  That shows me that this document is the only one with the problem.

[Bob  11:25 AM]
OK, I think I’ve fixed it. Have the users take a close look and confirm that all is as it should be.

**Comment by blairlearn** [comment]
No longer an issue per @bkline 
https://ncisape.slack.com/archives/GCC0K6F40/p1699306143352929
