### ISSUE TITLE
Draft translation not appearing in back end

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2633]
On NCI-CONNECT, the mini-landing page "Consulta" cannot be found through searching the back end content tab - either Overview or Moderated.

The only way to access this page is to go to the English equivalent and use the Task menu to access the translation. 

English: https://nciconnect-cms.cancer.gov/rare-brain-spine-tumor/refer-participate
Spanish: https://nciconnect-cms.cancer.gov/rare-brain-spine-tumor/espanol/node/1123421/latest

**Note**: there is also an article called Consultas.

**Comment by blairlearn** [comment]
This is no longer an issue

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/21063180/4ea4a10f-b4bb-411e-8d28-73d9c6201650)
