### ISSUE TITLE
Page title appears on unpublished microsite homepage's Spanish translation.

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2636]
When a Spanish translation is added to a microsite's home page, the page title appears instead of the site title until the translation is published.

---

Please make sure the page title doesn't appear on the homepage for Spanish NCI Connect? The title is not appearing on the English NCI-CONNECT homepage, but it's showing on the Spanish translation.

Per Adrian: is_front is determined by which node alias we have set to be the front page. At first glance this  should be the same for both the english and spanish translation.

```
Code snippet: 
{# Title Row #}
<div class="row">
  {% if is_front == FALSE %}
    <div class="large-7 columns">
      <h1>{{ node.label }}</h1>
    </div>
  {% endif %}
```

**Comment by adriancofie** [comment]
@bennettcc  I believe this is a non-issue. The Spanish home page just needs to be published.

**Comment by bennettcc** [comment]
After review with Blair, this does not require additional code implementation.   This can be tested on Dev https://www-dev-acsf.cancer.gov/rare-brain-spine-tumor/espanol

**Comment by claireblaustein** [comment]
Looks good after test on Dev.

**Comment by blairlearn** [comment]
@bennettcc - this is no longer a blocker for NCI-Connect.

It should still be fixed for unpublished content, but that's a fairly low priority.

**Comment by bennettcc** [comment]
Removing this item from the sprint -- since it is not directly impacting the nci connect go live.  Should be prioritized for completion during a backlog release.
