### ISSUE TITLE
Story: Allow Infographics in Feature Cards

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2643]
## As a content owner, I want to feature infographics in feature cards, so that I can display a crop of the infographic where the layout won't allow for the entire infographic to be displayed. 

> **ESTIMATE** 20 

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: https://www.cancer.gov/grants-training/apply-grant

### Notes

As a result of the infographic audit, 3 pages use a crop of the infographic so the demand is fairly low, but this could be a solution that is nice to have. In the meantime, we will probably make these into callout boxes as a result of removing the freeform promo crop on infographics.

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
Outdated due to redesign - we allow infographics in Multimedia Feature Cards.
