### ISSUE TITLE
Fix 404 errors for favicon.ico

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2646]
### Issue description
We get some number of failed requests from browsers looking for favicon.ico, or one of the apple-touch-icon equivalents.  Our markup specifies they should be loaded from the theme's design-elements directory, but not all browsers support this use of `<link>` tags and look for them in the root (default) directory instead. 

This adds noise to the error logs, and additional 404 errors Drupal has to process.

### Steps to reproduce the issue

1.  Review site access logs, looking for 404 errors for /favicon, /favicon-*, /apple-touch-icon.png, and /apple-touch-icon-*.png 

### What's the expected result?
- Should not find 404 errors for the favicons

### What's the actual result?
- Errors are found.

**Comment by andyvanavery31** [comment]
Closing this ticket due to redundancy with #3893, and this ticket is linked to the newer one.
