### ISSUE TITLE
Microsite Green Theme - Fix to View Infographic button

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2654]
### Issue description
The View Infographic button text is missing styling - it should be white. 

Business Value: Unstyled the button is not 508 compliant

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/39384914/75901367-66784d00-5e0c-11ea-87b2-413eb9e06687.png)

![image](https://user-images.githubusercontent.com/39384914/75901465-8a3b9300-5e0c-11ea-9d97-1ecfab88ddf3.png)

https://dceg-cms-dev.cancer.gov/about/test-infographic-button

### Acceptance Criteria:

Text | White
Background   Color | Ocean | #006789
Hover Background Color | Tangerine | #ff881e

### Related Tickets
* Issue #909 
* Issue #2618

**Comment by bennettcc** [comment]
Removing this from the microsite sprint

**Comment by bennettcc** [comment]
MVP1 launched yesterday - ticket no longer needed
