### ISSUE TITLE
Microsite Blue Theme - Fix to View Infographic button

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2655]
Issue description
The View Infographic button text is missing styling - it should be white.

Business Value: Unstyled the button is not 508 compliant

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/39384914/75901791-0e8e1600-5e0d-11ea-9e25-a5339a1f5c28.png)

![image](https://user-images.githubusercontent.com/39384914/75901851-26fe3080-5e0d-11ea-86b1-1b61de3096be.png)

https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors/about-rare-cancers

### Acceptance Criteria:
Text | White
Background   Color | Cobalt | #4659A5
Hover Background Color | Clementine | #f9a921

### Related Tickets
Issue #818
Issue #2618

**Comment by bennettcc** [comment]
Removing this from the microsite sprint

**Comment by sarinapadilla** [comment]
Outdated due to redesign (we don't have the microsite theme anymore).
