### ISSUE TITLE
Extramural Funding Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2664]
*Please update the data for the Extramural Funding Highcharts pie on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/extramural with the data attached in the corresponding JIRA ticket: [CGOV-10803](https://tracker.nci.nih.gov/browse/CGOV-10803)*

[extramural-funds-fy19 (2).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308313/extramural-funds-fy19.2.xlsx)

**Comment by erikscottmeyer** [comment]
custom block: Highcharts-HTML-Extramural

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
@erikscottmeyer I've reviewed this graph and everything looks good!

**Comment by blairlearn** [comment]
Completed by 4777743413bc0ac82e8ebabdf84f42bdbd88fb2b
