### ISSUE TITLE
NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Pie Chart

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2665]
*Please update the data for the NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Highcharts Pie Chart on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/obligations with the data attached in the corresponding JIRA ticket: [CGOV-11696](https://tracker.nci.nih.gov/browse/CGOV-11696)*

[nci-obligation-by-mechanism-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308316/nci-obligation-by-mechanism-fy19.1.xlsx)

**Comment by erikscottmeyer** [comment]
Made changes, put in branch ticket/2665-nci-obligations-by-mechanism in erikscottmeyer/cgov-digital-platform

**Comment by allymh** [comment]
Hi @erikscottmeyer  - Unfortunately Alice just sent me a few updates to this data. I have added an updated file for NCI Obligations by Mechanism. In the Centers section, there were updates made to the count and amounts for SPOREs and Other Specialized Centers. 
[nci-obligation-by-mechanism-fy19 (2).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4382606/nci-obligation-by-mechanism-fy19.2.xlsx)

**Comment by allymh** [comment]
Created a change request for this ticket here: https://github.com/NCIOCPL/cgov-digital-platform/issues/2721

**Comment by erikscottmeyer** [comment]
custom block obligations-mechanism

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test
