### ISSUE TITLE
NIH Management Fund: Highcharts Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2666]
Please update the data for the NIH Management Fund Highcharts pie on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/management-fund with the data attached in the corresponding JIRA ticket: [CGOV-10810](https://tracker.nci.nih.gov/browse/CGOV-10810).

[management-fund-fy19 (2).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308307/management-fund-fy19.2.xlsx)

**Comment by erikscottmeyer** [comment]
custom block Highcharts-HTML-ManagementFund

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
@erikscottmeyer I've reviewed this graph and everything looks good!

**Comment by blairlearn** [comment]
Completed by 8a9347b57a448c185b86dd464cf2098dfa03b47a
