### ISSUE TITLE
Program Structure: Highcharts Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2667]
Please update the data for the Program Structure Highcharts pie on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/program-structure with the data attached in the corresponding JIRA ticket: [CGOV-10820](https://tracker.nci.nih.gov/browse/CGOV-10820)

[program-structure-fy19 (1) (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308325/program-structure-fy19.1.1.xlsx)

**Comment by erikscottmeyer** [comment]
custom block highcharts-program-structure

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
@erikscottmeyer Data looks good on ODE, but the date needs to be updated to 2019

**Comment by allymh** [comment]
This one looks good now, thank you!
