### ISSUE TITLE
Number of RPG Awards: Highcharts Bar

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2669]
Please update the data for the Number of RPG Awards bar graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg#awards with the data attached in the corresponding JIRA ticket: [CGOV-10829](https://tracker.nci.nih.gov/browse/CGOV-10829).

** Note: Still awaiting data from the client, so this is just a placeholder for now

**Comment by allymh** [comment]
Hi @erikscottmeyer - The data for this Highchart is finally ready! Please update using the attached spreadsheet.
[Uploading rpg-number-of-awards-fy19.xlsx…]()

**Comment by erikscottmeyer** [comment]
I've completed the changes locally.

**Comment by allymh** [comment]
Thanks @erikscottmeyer! Assigning to @blairlearn to review the code and push the commit so I can review.

**Comment by allymh** [comment]
@erikscottmeyer  I've reviewed this graph and everything looks good!

**Comment by blairlearn** [comment]
Completed by cc0554452e8c82e08cfba0bd1ae6cd8cce70c651
