### ISSUE TITLE
RPGs Funding Mechanism: Highcharts Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2670]
Please update the data for the RPGs Funding Mechanism pie graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg#funding-mechanisms with the data attached in the corresponding JIRA ticket: [CGOV-10831](https://tracker.nci.nih.gov/browse/CGOV-10831).

** Note: Still awaiting data from the client, so this is just a placeholder for now

**Comment by allymh** [comment]
Hi @erikscottmeyer - The data for this chart is now ready!
[Uploading rpg-funding-paylines-fy19.xlsx…]()

**Comment by erikscottmeyer** [comment]
I've completed the changes locally.

**Comment by allymh** [comment]
Thanks @erikscottmeyer! Assigning to @blairlearn to review the code and push the commit so I can review.

**Comment by allymh** [comment]
Hi @erikscottmeyer - I've reviewed this graph and everything looks good!

**Comment by blairlearn** [comment]
Completed by f315b038c6d7fee3002607d4a7bce27f29d629f1
