### ISSUE TITLE
K Awards: Highcharts Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2671]
Please update the data for the K Awards pie graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards with the data attached in the corresponding JIRA ticket: [CGOV-10841](https://tracker.nci.nih.gov/browse/CGOV-10841).

**Comment by allymh** [comment]
@erikscottmeyer The data for this chart is ready now! 
[k-awards-fy19-2.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4382507/k-awards-fy19-2.xlsx)

**Comment by allymh** [comment]
Looks good on ODE!

**Comment by blairlearn** [comment]
completed by 0ca6c31b10ba89a05a5d6f188c55c18757566493
