### ISSUE TITLE
Highcharts Map - Grant and Contract Awards by State and Institution

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2672]
Please update the data for the Highcharts map on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards with the data attached in the corresponding JIRA ticket: [CGOV-11699](https://tracker.nci.nih.gov/browse/CGOV-11699).

This 'chart' is a little more complicated than the rest, so please let me know if it's confusing at all. I don't remember exactly what the code looked like and if it's straightforward, so I'm happy to walk through it with you once we get the data.

** Note: Still awaiting data from the client, so this is just a placeholder for now

**Comment by allymh** [comment]
Hi @erikscottmeyer - The data sets for this map is also ready! This should be the last set of data we need for Highcharts.
[Uploading awards-by-state-fy19.xlsx…]()
[Uploading inst-receiving-more-than-15M-fy19.xlsx…]()

**Comment by erikscottmeyer** [comment]
I've completed the changes locally.

**Comment by allymh** [comment]
Thanks @erikscottmeyer! Assigning to @blairlearn to review the code and push the commit so I can review.

**Comment by allymh** [comment]
@erikscottmeyer I've reviewed the map and everything looks good!

**Comment by blairlearn** [comment]
Completed by 3dee5044622d164c5a6264ab1672d4c61411e7d2
