### ISSUE TITLE
Extramural vs Intramural & RMS Funding: Highcharts Line Graph

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2674]
Please update the data for the Extramural vs Intramural & RMS Funding Highcharts Line Graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/extramural-intramural-rms with the data attached in the corresponding JIRA ticket: [CGOV-10860](https://tracker.nci.nih.gov/browse/CGOV-10860).

[extramural-vs-IR-and-RMS-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308445/extramural-vs-IR-and-RMS-fy19.1.xlsx)

**Comment by erikscottmeyer** [comment]
custom block: highcharts-rms-funding

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
Hi @erikscottmeyer - The data updates look good! Just a couple changes/questions.

1) Could you please remove 2014 from the data table and update the dates to 2015-2019
2) It looks like you inputted the percentages which then calculate the amount, correct? The amounts listed for a few of the data points seem right, but they are just slightlyyyyy off from the spreadsheet. Ex: Cancer Centers in the spreadsheet is listed as 337.1 but in Highcharts it says 337.08. I will confirm with Alice, but I think this is fine. I just want to be sure that's what's happening before I talk to her. Thanks!

**Comment by erikscottmeyer** [comment]
Actually, I copied the numbers directly, but I changed the column formatting to number, and it defaulted to 2 decimal places instead of one.  The data in the sheet is apparently 2 decimal places, rounded off to 1; I changed the highcharts data to use the rounded off numbers to keep it consistent.

**Comment by allymh** [comment]
Ah, ok! Thanks for clarifying!

**Comment by allymh** [comment]
Looks good now!
