### ISSUE TITLE
Comparison of Dollars, Positions, and Space: Highcharts Line Graph

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2675]
Please update the data for the Comparison of Dollars, Positions, and Space Highcharts line graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/comparison with the data attached in the corresponding JIRA ticket: [CGOV-10864](https://tracker.nci.nih.gov/browse/CGOV-10864).

[comparison-dollars-position-space-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308459/comparison-dollars-position-space-fy19.1.xlsx)

**Comment by erikscottmeyer** [comment]
custom content: Highcharts-HTML-amount

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
Hi @erikscottmeyer  - This one is almost there! The 2019 Funds number should be $5,992,000 (instead of 3). Also, please remove 2009 and update the dates so it's just the data from 2010-2019. Thanks!

**Comment by allymh** [comment]
Looks good!
