### ISSUE TITLE
AIDS Funding History: Highcharts Line Graph

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2676]
Please update the data for the AIDS Funding History Highcharts line graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/aids-funding with the data attached in the corresponding JIRA ticket: [CGOV-10871](https://tracker.nci.nih.gov/browse/CGOV-10871).

[aids-funding-history-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308461/aids-funding-history-fy19.1.xlsx)

**Comment by erikscottmeyer** [comment]
custom block: aids-funding

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
Hi @erikscottmeyer  - These data updates look good for the most part! Could you just remove the year 1998 please and update the dates under the title to 1999 - 2019? Thanks!

**Comment by allymh** [comment]
Looks good, thanks!
