### ISSUE TITLE
CM Obligations: Highcharts Pie

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2677]
Please update the data for the Cancer Moonshot Highcharts pie graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations with the data attached in the corresponding JIRA ticket: [CGOV-10880](https://tracker.nci.nih.gov/browse/CGOV-10880).

[moonshot-funding-m3-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4308473/moonshot-funding-m3-fy19.1.xlsx)

**Comment by erikscottmeyer** [comment]
custom block: moonshot-obligations

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
Hi @erikscottmeyer  - R&D contracts sub-amount should be 17,639,644. You accidentally put the 'Subtotal, R&D Contracts' amount there. Although, I admit that is confusing since they have the same label. Also, the Research Management & Support total should be $128,645 instead of 0. Let me know if that doesn't make sense. Everything else looks good though!

**Comment by erikscottmeyer** [comment]
I made the first revision.  Unsure what's going on with Research, Management and Support because the number is 128645 now; I tried to load it in the ODE but I keep getting some security scan interrupt anywhere on the ODE and it never loads.

**Comment by allymh** [comment]
Hmm, strange! Let me know if you are able to figure it out.

**Comment by allymh** [comment]
Looks good now! I see that the RM&S number is correct, but the percentage is showing as 0 I guess because it's so small compared to the other numbers. We'll see if the client thinks this is an issue and we need to change how it rounds the percentages. This is fine for now though.
