### ISSUE TITLE
Create NCI Connect Spanish search results page in Percussion

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2681]
Create and publish an app module page in Percussion, similar to the existing English one.

**Parent Issue:** #2627 

Page path:
~/rare-brain-spine-tumor/espanol/buscar/resultados~
/rare-brain-spine-tumor/espanol/nci-connect-buscar-resultados

**Comment by blairlearn** [comment]
@claireblaustein - I'm proposing the path above based, in part, on the path for Spanish search results on the main part of the site.  Does that seem reasonable to you?

**Comment by claireblaustein** [comment]
@blairlearn the english pattern for search results on the microsites is different than cgov:

cancer.gov/rare-brain-spine-tumor/nci-connect-search-results

can we follow the same pattern for spanish?

cancer.gov/rare-brain-spine-tumor/espanol/nci-connect-buscar-resultados

**Comment by blairlearn** [comment]
Yes. That would be consistent with the search results for the other microsites. As long as we keep the /espanol path segment, this seems OK.
