### ISSUE TITLE
"Download The Data" Button Issues

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2683]
Hi @erikscottmeyer  - Each of the Fact Book pages includes a 'Download the Data' button (a contextual image in Drupal) that is hyperlinked to an excel file. I think during the transition to Drupal from Percussion something didn't translate well because now some of the links are broken and I'm not able to change the hyperlink on the ones that are working. 

You can see an example here: https://www-cms.cancer.gov/about-nci/budget/fact-book/data/extramural. The button is working on the live site, but I'm not able to change the link to the FY19 file.

The file that I would want to hyperlink to the button is labeled as 'extramural-funds-fy19.xlsx' in Drupal.

Please let me know how we can hyperlink these files to the image. Thanks!

**Comment by erikscottmeyer** [comment]
When the code was migrated from percussion, these embedded inline images (the "Download the Data' buttons) were wrapped in links (to the files), and the content was published programmatically.  Editing any of the nodes associated with this content triggers the drupal/ckeditor filters, which strip the links out, so what you see in the editor no longer has the links.  Further, any attempt to wrap the images in links will result in the links being stripped out...  so we have to either change the filters or adopt a different linking solution.

**Comment by lburack** [comment]
As mentioned on Slack earlier today, having this image as a link is not accessible so it's not an ideal solution anyway. 
The **preferred solution** is to create a class for this `Download the Data` button, for use across the Fact Book pages. This is an approach we're currently using — there's a class for the buttons used on Patient Education Publication pages ([here's an example](https://www.cancer.gov/publications/patient-education/advanced-cancer))

**Comment by laurelthrash** [comment]
Revisited ticket in Nov. 2022 and determined that this ticket was complete, but not closed. Verified that functionality is working properly on production. Closing this ticket.

**Comment by sarinapadilla** [comment]
The proposed solution in [#2755](https://github.com/NCIOCPL/cgov-digital-platform/issues/2755) was fixed by PR [#2756](https://github.com/NCIOCPL/cgov-digital-platform/pull/2756).
