### ISSUE TITLE
Story: Term Count (Drupal)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2687]
## As a content editor, I want to be able to add term count for a dictionary to my intro text, so that users know how many terms my dictionary contains.

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: User is able to add the dictionary term count in their intro text
  Given user is logged into Drupal and editing/creating an app module
  Then dynamic total number of terms is made available for a selected dictionary source 
    And user is able to enter the “Dynamic total number of terms” as part of intro text. 
```

### Notes 
---

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Related App Story: NCIOCPL/glossary-app#97 

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
This is no longer needed as the app is Javascript only
