### ISSUE TITLE
Story: Definition Page Rendering for SEO

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2688]
## As a search engine, I want to index the page, so that I can show results to users

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
Given I am on a definition page
Then I should see a H1 title with the [Term Name]
   And Definition
   And Related Links
   And Video?
   And Images
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by andyvanavery31** [comment]
Will this be addressed by prerendering?

**Comment by andyvanavery31** [comment]
This is closed as this was addressed before the app was launched.
