### ISSUE TITLE
K Awards: Highcharts Bar

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2719]
Please update the data for the K Awards bar graph on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards with the data attached in the corresponding JIRA ticket: CGOV-10840.

[k-awards-fy19.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4382690/k-awards-fy19.xlsx)

**Comment by erikscottmeyer** [comment]
custom block: Highcharts-KAwards-pie

**Comment by erikscottmeyer** [comment]
http://ncigovcdode331.prod.acquia-sites.com/test

**Comment by allymh** [comment]
Number of awards should be '446' instead of '448'. All other changes look good though - thanks!
