### ISSUE TITLE
Changes to NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Pie Chart

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2721]
Hi @erikscottmeyer - Unfortunately Alice just sent me a few updates to this data for the NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Highcharts Pie Chart on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/obligations. In the Centers section, there were updates made to the count and amounts for SPOREs and Other Specialized Centers.
[nci-obligation-by-mechanism-fy19 (2).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4387585/nci-obligation-by-mechanism-fy19.2.xlsx)

corresponding JIRA ticket: CGOV-11696

**Comment by allymh** [comment]
Hi @erikscottmeyer - R&D contracts sub-amount should be 17,639,644. You accidentally put the 'Subtotal, R&D Contracts' amount there. Although, I admit that is confusing since they have the same label. Also, the Research Management & Support total should be $128,645 instead of 0. Let me know if that doesn't make sense. Everything else looks good though!

**Comment by allymh** [comment]
Looks good! The percentages don't match up to the spreadsheet, but I think that's an error in the spreadsheet. Highcharts totals 100% while the spreadsheet totals 153.3%

**Comment by blairlearn** [comment]
Completed by ef9c8be351e4de7617731aa196d3eed15451820c
