### ISSUE TITLE
["CancerGov and NCI-Connect Spanish"] Placeholder for search bar on SiteWideSearch results page should be displayed in Spanish

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform#2722]
### Issue description
Placeholder for search bar on Spanish SiteWideSearch results page for CancerGov and NCI-Connect should be displayed in Spanish. It is currently displayed in English.

![image](https://user-images.githubusercontent.com/31008800/77707413-6dbdf100-6f9b-11ea-9eca-f6585006fb01.png)

![image](https://user-images.githubusercontent.com/31008800/77707723-64815400-6f9c-11ea-9bf8-b6b6cc242b99.png)

### Steps to reproduce the issue

1.  https://www.cancer.gov/rare-brain-spine-tumor/espanol/nci-connect-buscar-resultados
2.  https://www.cancer.gov/espanol/buscar/resultados

**Comment by VictoriaSunNIH** [comment]
OBE we removed this on search results pages
