### ISSUE TITLE
Update Credit Display Translation in Spanish

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2725]
### Issue description
Currently, when an image has a credit in Spanish, Crédito is displayed.  The client has requested that we update this to be Fuente

> **ESTIMATE** XXX

### What's the expected change?
When an image is displayed on the spanish site, and the image has a credit, "Fuente: " is displayed before the contents of the credit field below the image caption.

The field_credit should show Fuente on the front-end when there is content provided in the field

### What's the current functionality?
Currently, the word Crédito is displayed before the contents of the credit field, below the image caption

### What's the updated acceptance criteria?
```gherkin
Given language is set to es
When a user is viewing an image on a Spanish page
  And the image has a spanish translation
  And the image has text filled in the field_credit field in Drupal
Then user sees "Fuente: " before the credit content on Cancer.gov when viewing in Spanish
```

### Additional details / screenshot
- Example: https://www.cancer.gov/espanol/cancer/naturaleza/que-es (multiple images on this page has a credit with the word "Crédito" before it)

**Comment by VictoriaSunNIH** [comment]
PR #3080 closes this ticket

**Comment by alinai** [comment]
Looks good on test-acsf. Test url: 
/espanol/cancer/tratamiento/efectos-secundarios/nauseas
/espanol/noticias/temas-y-relatos-blog/2015/cancer-privaciones-economicas
/espanol/cancer/causas-prevencion/riesgo/sustancias/acidos-aristoloquicos/test-and-test-sp

**Comment by alinai** [comment]
Looks good on test-acsf- (2nd round)
Test url: 
/espanol/cancer/causas-prevencion/riesgo/sustancias/acidos-aristoloquicos/test-and-test-sp
/espanol/cancer/tratamiento/efectos-secundarios/nauseas
/espanol/noticias/temas-y-relatos-blog/2015/cancer-privaciones-economicas
