### ISSUE TITLE
Infographic Promo Image Migration

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2734]
## As an admin, I want to migrate the current promotional images associated with an infographic into the infographic content type, so they can be managed from one location going forward

> **ESTIMATE**  NEEDS ESTIMATE

### Acceptance Criteria

```gherkin
Scenario: Migrate all crops
	Given that an infographic has a promotional image associated with it
		And that image has all reqired crops
	Then the 4x3 crop from the promotional image will appear in the 4:3 Promotional Image slot on the infographic
		And the 16x9 crop from the promotional image will appear in the 16:9 Promotional Image slot on the infographic
		And the 1x1 crop from the promotional image will appear in the 1:1 Promotional Image slot on the infographic
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* Ideally we'd be able to identify the promotional images that are now unused and remove them from the CMS (could be done though content reporting)

---

### Prerequisites
* New infographics image fields have been added #2705 

### Tasks
* Generate a complete listing/mapping of infographic items and the promo image media items they use
* Generate a listing of unused promo images
* Create a php script to programmatically migrate the existing images and crops into the new infographics fields
* Programmatically remove the existing infographics field

**Comment by meglake** [comment]
On hold as 2705 is also on hold and this story is dependent on 2705.

**Comment by meglake** [comment]
Moving to redesign - design ticket project for consideration during redesign work.
