### ISSUE TITLE
Enabler: Expose Proactive Live Help Functionality to the Window Object

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2750]
# Expose Proactive Live Help Functionality to the Window Object

We need to make a proactive chat popup for the COVID-19 page. The easiest way to handle any content changes without a release is to use Launch. The issue is that we cannot get to the ProactiveChat class without it being exposed onto the window object.

This task is to make the following available on the window:
* [Live Chat Is Available](https://github.com/NCIOCPL/cgov-digital-platform/blob/25dfc6838ab7716707981ca5543c4f5fdef109fa/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/index.js#L77)
* [ProactiveLiveHelp Class](https://github.com/NCIOCPL/cgov-digital-platform/blob/abc955dca299d8bcf0cbc6d17540fbc6aa609606/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/ProactiveLiveHelp.js#L5)

> **ESTIMATE** NN

**Comment by andyvanavery31** [comment]
This was closed by #2751.
