### ISSUE TITLE
Add custom analytics tracking 

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2769]
# As an analytics analyst, I want to be able embed specific tracking codes on the view and enlarge functionality, so I can track their use 

> **ESTIMATE** NEEDS ESTIMATE

### Acceptance Criteria

  ```gherkin
  Scenario: Click events for “View and Print Infographic” from the page
    Given user is viewing page infographic
    When user clicks on "View and Print Infographic" button
    And page click request is sent
    Then the following parameters should be captured
      | parameter | value |
      | event71   |       |
      | prop66   |     viewprint|inline|imageTitle  |
      | prop67   |       |

  ```
### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* See Enabler: Update Analytics Handler to push to NCIDataLayer #124
* Will apply to infographics in-line at medium and large formats, as well as infographic page
* "imageTitle" in the analytics should reference the content in the "Name" field of the infographic media type in the CMS
* Original analytics
  * 
```
  On click of “View and Print Infographic” from the page we would like to pass:
	  	1.Event71 (infographic click)
	  	2.Prop66 to collect viewprint|inline|image title
	  	3.Prop67 to collect the pagename
```
	
	

---

**Comment by kate-mashkina** [comment]
```gherkin
Scenario: Click events for 'Enlarge" button
Given user is viewing modal infographic
When user clicks on "Enlarge" button
And page click request is sent
Then the following parameters should be captured
|parameter|value|
|event71     |        |
|event66    |        |
|event67    |        |
 
```
```gherkin
Scenario: Click events for “View and Print Infographic” from the modal 
Given user is viewing modal infographic
When user clicks on "View and Print Infographic" button
And page click request is sent
Then the following parameters should be captured
|parameter|value|
|event71     |        |
|event66    |        |
|event67    |        |
 
```
```gherkin
Scenario: Click events for “View and Print Infographic” from the page 
Given user is viewing page infographic
When user clicks on "View and Print Infographic" button
And page click request is sent
Then the following parameters should be captured
|parameter|value|
|event71     |        |
|event66    |        |
|event67    |        |
 
```

**Comment by kate-mashkina** [comment]
@claireblaustein I formatted the acceptance criteria to be consistent with existing analytics tests

**Comment by claireblaustein** [comment]
thank you @kate-mashkina !

**Comment by claireblaustein** [comment]
@kate-mashkina question - all three of the parameters are listed as events, but should 66 and 67 be prop instead, as they're listed here:

	2.Prop66 to collect viewprint|modal|image title
	3.Prop67 to collect the page title

**Comment by kate-mashkina** [comment]
@claireblaustein My mistake! Yes, they should be props with values

**Comment by kate-mashkina** [comment]
You will notice that I added \ (escape character in Gherkin) in front of the pipe - so the table divider (|) is not mixed up with the pipes that belong to value

**Comment by claireblaustein** [comment]
Updated to just cover the current functionality - modal analytics added to modal story #2732
