### ISSUE TITLE
Regression: The <meta name="title"> tag is no longer being generated.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2770]
### Issue description
Most pages on the site should include a meta tag of the form `<meta name="title" content="The title of the page" />`.  These tags are no longer being generated.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Browse to https://www.cancer.gov/about-nci/organization/ccct
2. View page source.

### What's the expected result?
- Within the `<head> ... </head>` section, there should be a tag of the form `<meta name="title" content="The title of the page" />`.  This is usually at the top of the section, immediately after the New Relic script (if present).

### What's the actual result?
- The tag is missing.

### Additional details / screenshot
- This likely happened during the 1.1.16 release. This problem appeared once during that release, but was believed to have been fixed.

**Comment by bryanpizzillo** [comment]
This is actually a good thing. It was fixed in a metatag release. The Drupal ticket is https://www.drupal.org/node/3099168.

**PLEASE DO NOT FIX THIS!!!**
