### ISSUE TITLE
Story: Content Block for AP link (Visual)

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2779]
## As a content editor, I want to be able to embed a content block, so that we can drive visitors to a relevant file easily. 

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: Web site visitor views a page with a link on desktop and tablet only 
  Given a user is viewing the AP landing page 
    And the browser width is 768px or greater 
  Then the download link should appear at the top before Director’s Message 
    And a PDF icon will display   
    And the link will read “Annual Plan & Budget Proposal At-A-Glance”  
    And clicking on the link will open the PDF in a new window 
```
Analytics
```gherkin
 Scenario: Click events for “Annual Plan & Budget Proposal At-A-Glance” file download button from the page (top link)
    Given user is viewing the AP landing page
    When user clicks on top "Annual Plan & Budget Proposal At-A-Glance" button
    Then page click request is sent
    And the following parameters should be captured
      | parameter | value                          |
      | event52   |                                |
      | prop8     | [language]                     |
      | prop66    | filedownload_icon               |
      | prop67    | D=pagename                     |
      | eVar2     | [language]                     |
```
### Resources:
Mockups
- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop

- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024

- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile

### Notes

- Front-end visual only
- No change in backend

---

### Tasks
- [ ] Create example markup; ensure styling is in place
- [ ] Add analytics (add ACs to story)

**Comment by Andrew-Olsson** [comment]
**Analytics:**

Scenario: Click event for “Annual Plan & Budget Proposal At-A-Glance” link at top of page
Given user is viewing the AP landing page 
When user clicks on “Annual Plan & Budget Proposal At-A-Glance” link at top of page
And page click request is sent
Then the following parameters should be captured
•	Event52
•	Prop8: [language]
•	Prop66 to display: “annualplan_filedownload_top”
•	Prop67: [D=pagename]
•	eVar2: [language]

**Comment by Andrew-Olsson** [comment]
Custom analytics: prop66 values.
