### ISSUE TITLE
Story: Content Block for AP button (Visual)

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2780]
## As a content editor, I want to be able to embed a content block, so that we can promote a button more prominently. 

> **ESTIMATE** 2

### Details

- No new functionality - visual design only
- Button will be added to the content block library so it can be re-used beyond the Home and Landing page (generally at the bottom of a content page)
  - either Raw HTML or Content Block
- For Home and Landing button content block would presumably need to be nested inside a "content block" paragraph (?)

  

### Acceptance Criteria

```gherkin
Scenario: Web site visitor views a page with a button on desktop, tablet or mobile 
  Given a user is viewing the AP landing page 
  Then the button to download At a Glance should appear at the bottom of the page 
    And a PDF icon will display 
    And the button will read “Annual Plan & Budget Proposal At-A-Glance” 
    And clicking on the link will open the PDF in a new window 
```
**Analytics**
```gherkin
 Scenario: Click events for “Annual Plan & Budget Proposal At-A-Glance” file download button from the page
    Given user is viewing the AP landing page
    When user clicks on bottom "Annual Plan & Budget Proposal At-A-Glance" button
    Then page click request is sent
    And the following parameters should be captured
      | parameter | value                          |
      | event52   |                                |
      | prop8     | [language]                     |
      | prop66    | filedownload_button |
      | prop67    | D=pagename                     |
      | eVar2     | [language]                     |
```

### Resources:
Mockups
- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop

- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024

- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile

### Notes

- Front-end visual only
- No change in backend
- Built by a class, will add CSS modifier for alignment (center on landing page vs left align on article pages) (Article page comp example: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/408708927)

---

### Tasks
- [ ] Create example markup; ensure styling is in place
- [ ] Add analytics (add ACs to story)

**Comment by Andrew-Olsson** [comment]
**Analytics:**

Scenario: Click events for “View and Print Infographic” from the page
Given user is viewing the AP landing page 
When user clicks on "View and Print Infographic" button
And page click request is sent
Then the following parameters should be captured
•	Event52
•	Prop8: [language]
•	Prop66 to display: “annualplan_filedownload_bottom”
•	Prop67: [D=pagename]
•	eVar2: [language]

**Comment by Andrew-Olsson** [comment]
Custom analytics: prop66
The rest are global analytics.

**Comment by SupriyaSaxena0605** [comment]
@blilianyu what should be the spanish requirements for the AP button

**Comment by blilianyu** [comment]
@SupriyaSaxena0605  The Read More button should read as "Lee Mas".
