### ISSUE TITLE
Create a new twig template for Special Report style

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#2794]
Create a  new twig template for the Special Report landing page style

- [ ] Create Template
- [ ] Create styles for page options
- [ ] Add layout styles
- [ ] Create webpack entrypoint

**Parent Issue:** #2785

**Comment by sarinapadilla** [comment]
Closing this ticket, as the new Special Report Home & Landing page style has been implemented on CGov.
