### ISSUE TITLE
Update S-code value in Front end repo 

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2795]
Please make the following change to the c.gov front end repo to update the Scode value, allowing for the use of Adobe's first party cookies.

// Send tagging requests to correct server based on protocol
if(document.URL.indexOf("https://") >= 0)
s.trackingServer="nci.122.2o7.net";
else
s.trackingServer="metrics.cancer.gov";
s.dc="122";

The original request is tracked in Jira: https://tracker.nci.nih.gov/browse/CGOV-11499

**Comment by bryanpizzillo** [comment]
This is the wrong place for this.
