### ISSUE TITLE
Story: Default Home and Landing pages to Standard

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2809]
## As a content editor, I want to be able to save my Spanish translation of an existing Home and Landing page without re-saving the English version, so that I can get my work done faster. 

> **ESTIMATE**

The template field for Home and Landing pages is non-translatable. Existing Home and Landing pages need to have their template set to "Standard" to avoid issues with saving Spanish Home and Landing pages. 

### Acceptance Criteria

```gherkin
Scenario: Existing content after the new field is added
  Given that a user is editing an existing English Home and Landing page
  Then the Home and Landing Page Style will be set to the default value of Standard 
```

```gherkin
Scenario: Existing content after the new field is added - spanish
  Given that a user is editing an existing Spanish Home and Landing page
  Then the Home and Landing Page Style field will not show
    And the user will be able to save the page without errors
```

### Notes

https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#page-style

#### Page Style Specs

- **Field Name:** field_page_style
- **Label:** Home and Landing Page Style
- **Type**: Dropdown
  - Standard (Default)
  - Special Report
- **Required:** Yes
- **Max characters:** N/A
- **Tooltip Text:** Select a template for the page
- **Cardinality:** 1
- **Translatable:** No

### Technical Notes
**ODE Home and Landing pages**
- /special-report
- /test/borderless-card
- /test-/cards/landing-containers

Main Nav H&L
-  /
- /types
- /research
- /grants-training
- /about-nci
- /news-events
- /about-cancer

-  Depending on the number of Home and Landing page on production, manually updating the pages may be a preferred option.

- Once the script has has been verified, a separate ticket should be created to update the values in YML content for the pages.

**Comment by adriancofie** [comment]
[page_style.php.txt](https://github.com/NCIOCPL/cgov-digital-platform/files/4886112/page_style.php.txt)
