### ISSUE TITLE
Change Special Report Template Hero Image to scale without gutters

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2811]
### Issue description
Hero image should scale without gutters 

> **ESTIMATE** 20

### What's the expected change?
- Hero image should scale without gutters

### What's the current functionality?
- Gradient is showing past 1440px+

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- 

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by meglake** [comment]
See solution outlined in spike #2812  (Paul K.'s notes here: https://github.com/NCIOCPL/cgov-digital-platform/issues/2812#issuecomment-652605590)
