### ISSUE TITLE
Spike: Research ways to make Special Report hero image scalable to X-large breakpoint

### ISSUE THREAD

**Issue by blilianyu** [NCIOCPL/cgov-digital-platform#2812]
## In order for the Hero image to look good, we need to be able to scale it up to the X-large breakpoint 1920px. Gutters will appear after that and no gradient past 1920px.

*Examples:*
* XXL Breakpoint (1920+ with gutters) https://publicis.invisionapp.com/share/DZWC0VL2B3E#/422622570_AP_Landing_Page_V9_-_XXL_Desktop_2560
* XL Breakpoint (1920 no gutters)
https://publicis.invisionapp.com/share/DZWC0VL2B3E#/422622571_AP_Landing_Page_V9_-_XL_Desktop_1920

> **Story Points** 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
*Examples:*
* *Answers to better story point*
* *A spreadsheet with affected items*
* *A new set of stories breaking down this story*

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by karlikpj** [comment]
Updated CSS to allow image to scale to full width of page. This was done in a few areas around the hero slot in the CSS code.  

- ```.row.hero-slot``` - updated media queries for height of container
```position: relative;
    width: 100%;
    max-width: none;
    overflow: hidden;
    height: 59.375vw;
     // large
    @media only screen and (min-width: 1440px) {
      max-height: 540px;
      height: 540px;
    }
    // medium
    @media only screen and (min-width: 1024px)  {
      max-height: 384px;
      height: 37.5vw;
    }
    // small
    @media only screen and (max-width: 1024px)  {
      max-height: 384px;
      height: 37.5vw;
    }
    // xsmall
   @media only screen and (max-width: 640px) {
      max-height: 384px;
      height: 384px;
    }
```

- ```.row.hero-slot::after``` - updated size of black gradient - Design might need to review

```
&::after {
      content: "";
      display: block;
      position: absolute;
      bottom: 0;
      width: 100vw;
      height: 155px;
      background: linear-gradient(rgba(0,0,0,0) 0%, rgba(0,0,0,.8)  100%);
      
      @media only screen and (min-width: 1024px) {
        height: 185px;
      }

      @media only screen and (min-width: 1440px) {
        height: 275px;
      }
    } 
```

- ```picture``` tag - remove flexbox css

```
    width: 100%;
    height: 100%;
    //display: flex;
    //justify-content: center;

```

- ```img``` tag - add media query and change scaling.

```
img {
     
      width: 100%;
      height: auto;
     
      @media only screen and (max-width: 1024px)  {
      object-fit: cover;
      width: auto;
      height: 100%;
      }
    }
```
