### ISSUE TITLE
Incorrect canonical URLs on lower tiers.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2818]
### Issue description
On all lower tier sites (e.g. www-dev-acsf.cancer.gov, www-dev-ac.cancer.gov, or ncigovcdode275.prod.acquia-sites.com) the generated canonical URL points to the lower tier server instead of production.

This is problematic as:
* It potentially impacts SEO.
* It can lead to lower-tier sites appearing in search results.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Browse to https://www-dev-acsf.cancer.gov
2. View page source
3. Search for `<link rel="canonical"`

### What's the expected result?
- The `href` attribute should start with `https://www.cancer.gov`

### What's the actual result?
- The `href` attribute should start with the URL of the lower tier site being visited.  (In this case, `https://www-dev-acsf.cancer.gov`)

### Related Tickets
* Issue #322
* Issue #1810

**Comment by andyvanavery31** [comment]
Our Robots.txt sets Disallow so Google does not index the site.
