### ISSUE TITLE
V2 Changes to NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Pie Chart

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2826]
Hi @erikscottmeyer - In ticket #2721 I noted there was an issue with the data. It turns out that the data is correct, but it wasn't clear which data needed to be used. Rather than using the amount noted as 'Subtotal, Research Grants' for the 'Other Research' category in the table, please use the amount listed for 'Subtotal, Career and Other Research Grants'. **In other words, the correct amount for the 'Other Research' category should be 506,763,422 which would total 8.5%.**

**File**: [nci-obligation-by-mechanism-fy19 (2) (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/4847420/nci-obligation-by-mechanism-fy19.2.1.xlsx)

**Page/Table Name & Link:**

NCI Obligations by Mechanism "Percent Share of Total NCI Dollars" Highcharts Pie Chart on this page: https://www.cancer.gov/about-nci/budget/fact-book/data/obligations.

corresponding JIRA ticket: CGOV-11696

**You can wait to do this change when we have received the remaining data and edits. I'll let you know when - just wanted to capture this change for now.**

** Getting additional clarification from Alice **

**Comment by allymh** [comment]
Hi @erikscottmeyer - The sub-sets of data you have in here already should be correct, but the data for the main pie chart should use only the numbers highlighted in the spreadsheet attached. The note I had above is correct, but we also needed to not use 'Subtotal, Career Program' line. The rest of the numbers you had in there should be correct as well. Just slack me if you have any questions!

[corrected-data.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/5698407/corrected-data.xlsx)

**Comment by blairlearn** [comment]
c4e3f4cb2d6d04d0acbefe716c0f8884b25f90e8
