### ISSUE TITLE
change label and tooltip on accessible text version field 

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2839]
### Issue description

Change current “Accessible Text Version” label to "Accessibility Long Description", with a tooltip “Used when the Alternative Text (alt text) is not sufficient to describe a complex chart, diagram, or infographic. Should not duplicate the alt text.”

> **ESTIMATE** ??

### What's the expected change?

Field Name field_accessible_version will display a new label and tooltip in Drupal.

### What's the current functionality?

This field currently appears on:

- Images
- Infographics
- Contextual Images

When filled in, it adds a `longdesc` to the image, linking to the text description. 

Currently labeled as Accessible Text Version, with tooltip "Details to supplement alt text. [Used when an alt tag alone is not sufficient to describe a complex chart, diagram, and/or infographic]"

### What's the updated acceptance criteria?

```gherkin
Scenario: adding an image that requires longdesc
Given Content creator is adding a media item that allows for a longdesc
When the content creator creates the media item
Then they will see a field with the title "Accessibility Long Description"
	And that field will have a tooltip that reads "Used when the Alternative Text (alt text) is not sufficient to describe a complex chart, diagram, or infographic. Should not duplicate the alt text."
	And that field will be plain text.
	And the field will not be required.
```

### Additional details / screenshot

- Wiki will require update: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images
- Once this ticket is complete, the Drupal Guide will need to be updated to change the labels https://mynci.cancer.gov/topics/drupal-guide-images-and-multimedia 

#### Accessible Text Version

- **Field Name:** field_accessible_version
- **Label:** Accessibility Long Description 
- **Type:** Text (plain)
- **Required**: Not Required
- **Max Characters:** currently no limit
- **Tooltip Text:** Details to supplement alt text. [Used when an alt tag alone is not sufficient to describe a complex chart, diagram, and/or infographic]
- **Translatable:** Yes
- **Note:** When filled in "img longdesc” attribute points to a URL that contains the media ID (e.g. /media/923228/long-description) 

### Related Tickets

*

**Comment by alinai** [comment]
Looks good on test-acsf.

**Comment by alinai** [comment]
Looks good on test-acsf - (2nd round)
