### ISSUE TITLE
Setup Genetics Dictionary in Spanish

### ISSUE THREAD

**Issue by venglisch** [NCIOCPL/cgov-digital-platform#2850]
### Issue description
Currently, only for the Dictionary of Cancer Terms exists a translation of the terms.  The other dictionaries exist in English only.  Over the past months, CIAT has translated a number of genetics terms and would like to publish these to be available in a Genetics Dictionary in Spanish.
This is a request the CDR team has held back for a while until the new dictionary API was ready and in production

> **ESTIMATE** 20

### What's the expected change?
- Add a Spanish version of the Dictionary of Genetics Terms

### What's the current functionality?
- Does not exist currently

### What's the updated acceptance criteria?
``` A language toggle clicked on the Dictionary of Genetics Terms click will switch to the Spanish version of that dictionary
```

### Additional details / screenshot
- There are currently no Spanish terms loaded in Elastic Search but many terms are ready to be published.

**Comment by VictoriaSunNIH** [comment]
This has been pushed live
