### ISSUE TITLE
Remove Language Toggle from Search Results Page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2868]
### Issue description
http://ncigovcdode377.prod.acquia-sites.com/
The language toggle should not appear on search results pages. 
Search results are not 1:1 as translations for words differ. Users must search either the EN or ES site respectively. 

> **ESTIMATE** 20

### What's the expected change?
- Remove the language toggle link on search results

### What's the current functionality?
- Currently on PROD, the language toggle does not appear on search results.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / Screenshot
![Screen_Shot_2020-07-31_at_12_48_44_PM](https://user-images.githubusercontent.com/29731392/89057905-65e8d180-d32c-11ea-9cbb-3650c429b7a9.png)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by VictoriaSunNIH** [comment]
I don't see this on prod - closing as non issue or OBE.
