### ISSUE TITLE
Limit paragraph options on mini-landing pages

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2871]
### Issue description
The new Borderless Feature Card paragraph is showing as an option for mini-landing pages. It should only be available on Home and Landing pages.

> **ESTIMATE** 20

### What's the expected change?
- the Borderless Feature Card will not appear in the list of content options. 

### What's the current functionality?
- it is an option. 

### What's the updated acceptance criteria?
```gherkin
Scenario: Content editor adds paragraphs to a mini-landing page 
  Given the user is logged in as an editor 
    And the user creates a mini-landing page
    And expands the drop down to add a paragraph to Contents 
Then the dropdown should have five options - "add content block", "add two-item feature card row", "add list", "add raw HTML", "add dynamic list"
```

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/39384914/89221709-c16fc500-d5a1-11ea-9295-20ccc83c0331.png)

### Related Tickets
#2775

**Comment by andyvanavery31** [comment]
Closing due to the redesign project working on MLPs.
