### ISSUE TITLE
The mobile menu items are moving down on clicking the Close (x) button of the alert drawer

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2876]
### Issue description
*Description of the issue*

> **ESTIMATE** 20

The mobile menu items are moving down leaving huge white space between the NIH logo and page options on clicking the (x) button of the alert drawer.

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/ at mobile breakpoint
2. Click on the expand button of the alert drawer
3. Click on the mobile (hamburger) button.
4. Click on the Close (x) button of the alert drawer

### What's the expected result?
- The menu items should be in line with the blue utility bar.

### What's the actual result?
- The menu items moves down leaving huge white space between the NIH logo and the menu.

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/89446155-2ce0a080-d722-11ea-8255-39fd57392a08.png)

**Comment by alinai** [comment]
The mobile menu looks like the following on navigating to News & Events-> Conferences (+) -> ASCO 2020 (note: the screen on Prod was refreshed  to see the Collapse (+) buttons Expanded (-) [otherwise all the Expand (-) buttons appears Collapsed (+) on Prod]

![image](https://user-images.githubusercontent.com/28455973/89583032-a0101280-d807-11ea-8200-8b2ac2bea9b8.png)

**Comment by blairlearn** [comment]
No longer an issue.
