### ISSUE TITLE
The COVID-19 banner does not appear on R4R pages

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2877]
### Issue description
*Description of the issue*
The COVID-19 banner does not appear on R4R pages

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/research/resources
2. Go to https://www.cancer.gov/research/resources/search?from=0&researchAreas=cancer_biology
3. Go to https://www.cancer.gov/research/resources/resource/250

3. 

### What's the expected result?
- The COVID-19 banner (alert drawer) should appear on those pages

### What's the actual result?
- The COVID-19 banner (alert drawer) does not appear on those pages

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/89458560-3293b180-d735-11ea-8d1f-fa7b24fb5bfb.png)

**Comment by lburack** [comment]
Closing this out because reasons. We're taking care of this this week.
