### ISSUE TITLE
Glossify error when content is links 

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2878]
### Issue description
When trying to run glossify in a content field, the content of the box is displayed in the glossify modal. 

Appears to happen when majority of content is links - but adding non-link text doesn't fix it. 

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Add a section to an article page
2. Fill the "content" with primarily links 
3. Activate the glossifier

### What's the expected result?
- The glossifier would either run, or return no words 

### What's the actual result?
-  The modal appears, with the content duplicated in it 

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/39384914/89461928-ab493c80-d73a-11ea-938d-be54be6fa630.png)

![image](https://user-images.githubusercontent.com/39384914/89461939-adab9680-d73a-11ea-9c75-bf5d1227f923.png)

```
<p>test glossifier</p>

<ul>
	<li><a href="http://www.google.com">link</a></li>
</ul>

<p><a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="e119b18f-5781-48db-9a4a-42f62aaa4e52" href="/node/13367">link</a></p>

<p>&nbsp;</p>
```

**Comment by VictoriaSunNIH** [comment]
Glossification should only be used when users are writing content, and not when users are creating a list of links.  The modal is meant to bring up the content and show you any content that can be glossified.  Users should not be trying to add definitions to their list of links.  We should update our training documentation if this is a real use case that is happening often.
