### ISSUE TITLE
Unmatched end tag console message in Sitewide Search App with IE 11

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2886]
### Issue description
Using the Sitewide Search Application in IE 11 results in an "Unmatched end tag" message being output to the console.  This appears to be an error in the code output by Drupal and not in the glossary application itself.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Launch Internet Explorer 11.
2. Open the F12 developer tools.
3. Browse to any page on the site.
4. Clear any existing messages from the console.
5. Do a search for any term.

### What's the expected result?
- The  console should contain no warning messages about the HTML.

### What's the actual result?
- The console contains a message, "HTML1509: Unmatched end  tag.  resultados (637,3)"

Line 637 of the underlying page HTML (view-source as opposed to DOM) contains a closing `</div>` tag.

### Additional details / screenshot
- ![message](https://user-images.githubusercontent.com/21063180/90057863-fae5b600-dcae-11ea-8131-cc29b3b2c54d.png)
- ![image](https://user-images.githubusercontent.com/21063180/90057931-1355d080-dcaf-11ea-91e4-3ee9e1726e9a.png)

**Comment by sarinapadilla** [comment]
We don't support IE anymore, so closing this ticket!
