### ISSUE TITLE
Breadcrumb is displaying on non-home/landing-page-type children of homepage on non-English Cancer.gov sites

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#2888]
Currently, the breadcrumbs are displaying on direct children of the homepage on non-Cancer.gov English sites. This is inconsistent with the behavior on Cancer.gov English and DCEG, where the breadcrumbs are not displayed on any direct children of the home page.

> **ESTIMATE** 5 (including testing across all microsites and Spanish!!)

### Steps to reproduce the issue

1.  Go to any of the following sites: 
https://www.cancer.gov/espanol/publicaciones
https://www.cancer.gov/espanol/acerca-sitio
https://www.cancer.gov/pediatric-adult-rare-tumor/research
https://www.cancer.gov/nano/grants-training
https://www.cancer.gov/rare-brain-spine-tumor/blog
2.  See that the breadcrumb is displaying, with only the homepage link in it.

### What's the expected result?
- The breadcrumb should not display for any of the direct children of the homepage of the microsite or Spanish site.

### What's the actual result?
- The breadcrumb displays only the homepage link.

### Here's how to fix it
Update Breadcrumb.php:
```
// Requirement: If the only breadcrumb is the root, we
// don't want to render any breadcrumbs.
$homeUrl = Url::fromRoute('<front>')->toString();

if (count($formattedBreadcrumbs) === 1 && $formattedBreadcrumbs[0]['href'] === $homeUrl) {
  $formattedBreadcrumbs = [];
}
return $formattedBreadcrumbs;
```

Also remove the temporary fix from sitewideSearchApp.js:
```
// This is a temporary fix for removing the breadcrumb element that displays on Spanish and microsite search results
// pages. REMOVE THIS when the sitewide fix for the breadcrumbs is implemented!
let breadcrumbs = document.querySelector(".breadcrumbs");
if(breadcrumbs !== null && breadcrumbs.parentNode) {
  breadcrumbs.parentNode.removeChild(breadcrumbs);
}
```

**Comment by bryanpizzillo** [comment]
This affects the microsites as they currently show the Home page in bread crumbs. So this needs to be discussed with the client.

**Comment by bryanpizzillo** [comment]
Based on multiple discussions, it was decided that some micro sites should actually have the front-page (e.g. home or Pagina Principal) show in the breadcrumbs on its own. However, Spanish www should not.  

As such we will add a setting to the Breadcrumb block:
* Machine Name: `show_home_alone`
* Title/Label: `Root Site Section Display`
* Description/Tool Tip: `Should the root site section display on pages when it is the only breadcrumb?`
* Type: `select`
* Options:
   * `Hide when only breadcrumb item`
     * Value: `hide`
     * Default Value
  * `Show when only breadcrumb item`
     * Value: `show`
  
When there is only 1 breadcrumb AND the URL is the `<front>` page AND show_home_alone is FALSE then the breadcrumbs should not show. There is a SUPER-DOOPER assumption here -- that the root site section's landing page is set to `<front>`. (it should be)
