### ISSUE TITLE
The audio icon for the glossary pop-up is cut-off on Edge 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2891]
### Issue description
*Description of the issue*

The audio icon for the glossary pop-up is cut-off on Edge 

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/types/bladder/patient/bladder-treatment-pdq on Edge 
2. Click the glossified term "malignant"
3. See that the audio icon is getting  cut-off.

### What's the expected result?
- The audio icon should not get cut-off at any breakpoint.

### What's the actual result?
- - The audio icon gets cut-off at all breakpoint.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/90452410-09bbd680-e0bc-11ea-84a3-102561e6a64d.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
Closing as this no longer occurs.  Verified on both Mac and PC.
