### ISSUE TITLE
The items within the accordion on News&Events page gets cut-off at mobile breakpoint.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2893]
### Issue description
The right rail on the News & Events landing page collapses into accordion on mobile. The items within the mobile accordions get cut off.

> **ESTIMATE** 

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/news-events and  https://www.cancer.gov/espanol/noticias
2. Switch to mobile breakpoint
3. Scroll all the way down until you see the accordions for Cancer Currents Blog, Media Resources , Social Media
4. Expand the accordions and see that the items are getting cut-off within the accordion.

### What's the expected result?
- The accordions should not get cut-off within the accordion.

### What's the actual result?
- The items are getting cut-off within the accordion.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/90580534-22e58580-e197-11ea-833c-c8cd428627fd.png)

The links in the right rail have changed since [this WayBack Machine capture](https://web.archive.org/web/20190702191348/https://www.cancer.gov/news-events), but it's a reference for how they should look.

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by arcepaul** [comment]
It looks like there's a css rule for Homelanding pages that's causing it.  

@lburack @VictoriaSunNIH 
Are there other homelanding pages with accordions that you know of?  I want to make sure that I don't break it EVERYWHERE.

**Comment by lburack** [comment]
@arcepaul - Guide Cards on Home/Landing Pages accordion on mobile. 
* In English, all the H/L pages except Cancer Types have guide cards
* In Spanish, H/L pages with guide cards that accordion on mobile are the [Spanish homepage](https://www.cancer.gov/espanol), [El cáncer](https://www.cancer.gov/espanol/cancer) and [Investigacion](https://www.cancer.gov/espanol/investigacion)

**Comment by arcepaul** [comment]
@lburack 
So the quick solution is to add this style tag into the first rawHtml block in the secondary content for these two pages:
```
<style type="text/css">
@media only screen and (max-width: 640px) {
  .ui-accordion .rawHtml div.ui-accordion-content {
    margin: 0;
  }
}
</style>
```

This would be a temporary fix and we should leave this ticket open as an issue to be fixed down the road when more time is available to possibly reconfigure the layout of this news-events page to match other homelanding pages.

**Comment by lburack** [comment]
Thanks, @arcepaul  - I've added the style to the English and Spanish pages and they look good. I'll keep this ticket open though as it's a temporary fix ^
