### ISSUE TITLE
Two-Item Feature Card Row with one item needs correct styling

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2894]
### Issue description
When a two-item feature card row is added to a mini-landing page, and only one item is added to it, that item should look the same as cards in a row with two cards, and should sit flush left. 

**Works on microsites: https://www.cancer.gov/pediatric-adult-rare-tumor/rare-tumors** 

> **ESTIMATE** 20

### Steps to reproduce the issue

1. Add a two-item feature card row to a mini-landing page contents
2. Select an item for the first internal feature card
3. Do not add another card
4. Publish page

### What's the expected result?
- The card appears on the page at the dimensions of a two-item feature card, sitting in the left column, and flexes to be full width on mobile. 

### What's the actual result?
- Card appears in the smaller, inline feature card format, sitting in the middle of the row.

It does appropriately flex on mobile. 

### Additional details / screenshot
Content unpublished in CMS: https://www-cms.cancer.gov/research/annual-plan/stories

![image](https://user-images.githubusercontent.com/39384914/90931145-00877e00-e3ca-11ea-8dd5-16fb0ff6f1c3.png)

![image](https://user-images.githubusercontent.com/39384914/90931173-0f6e3080-e3ca-11ea-821b-133c1fa291b2.png)

**Comment by VictoriaSunNIH** [comment]
A 2-item feature card row should never only have one item.  If we need to only add one item, we should use a inline feature card.  Closing this request.
