### ISSUE TITLE
Main nav on MyPART is losing the /pediatric-adult-rare-tumor/

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2895]
### Issue description
when clicking on main navigation on MyPART, the path isn't retaining the /pediatric-adult-rare-tumor/, so is pointing to paths on cancer.gov*

Seems to be limited to MyPART - cannot replicate on NCI-CONNECT, DCEG, or Nano.

* Triggered by Production deployments.  Can be resolved by clearing the mega menu cache for the microsite.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/pediatric-adult-rare-tumor/
2.  From the home page or an interior page, click on a main navigation item (Rare Tumors) 
3.  Profit.

### What's the expected result?
- Go to the landing page.

### What's the actual result?
- Going to cancer.gov/main-pretty-url

### Additional details / screenshot
![Screen Shot 2020-08-21 at 4 32 59 PM](https://user-images.githubusercontent.com/39384914/90932182-1bf38880-e3cc-11ea-9944-fcef3b7be806.png)

### Related Tickets
* Issue #2889

**Comment by VictoriaSunNIH** [comment]
This will be resolved with #2930
