### ISSUE TITLE
Sitewide Search - Autosuggest

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#290]
This story is to create the Autosuggest for Sitewide Search #191

**Comment by bryanpizzillo** [comment]
The Site-Wide Search API has and Autosuggest feature. This story should be part of the Site-Wide Search Application Module epic, to connect the Search Bar to the (not launched yet) Site-Wide Search API. So this is more of a Sprint 8 thing.

**Comment by VictoriaSunNIH** [comment]
closing this.  this was part of SWS app module when it was migrated
