### ISSUE TITLE
Sitewide Search - Update how Best Bets works

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#291]
Similar to how R4R updates its resources, we would like to create a way to update Best Bets via spreadsheet/content instead of creating a content type for best bets.  Requirements TBD (need to know what data fields are needed)

**Comment by VictoriaSunNIH** [comment]
1. Decouple BB from Percussion
2. Store content into GitHub (R4R method) - checkout content, add synonym
Update how the Best Bets API returns the items

**Comment by amydugan** [comment]
Closing. See #1153 #1152
