### ISSUE TITLE
CT delighter overlapped by sticky nav when COVID banner is open

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2910]
### Issue description
When the COVID banner is open, the Clinical Trials delighter gets overlapped by the stick nav on non-retina MacBook pro in chrome.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to cancer.gov on macbook pro (not retina) and make sure browser takes up full height of screen (768px)
2. See CT delighter on right (in purple) getting overlapped (for new visits COVID banner is open)

### What's the expected result?
- The delighter will float further down the page so it isn't overlapped

### What's the actual result?
- The delighter is overlapped

### Additional details / screenshot
<img width="1395" alt="Screen Shot 2020-09-10 at 3 37 39 PM" src="https://user-images.githubusercontent.com/4921685/92793574-85880680-f37c-11ea-9845-1735604ffb04.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
Sticky nav has been removed from c.gov, closing this ticket as Overcome By Events.
