### ISSUE TITLE
BLT Configuration is not running PHPCS on entire code base

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2919]
### Issue description
It is only running on `<docroot>/modules/custom` and `<docroot>/themes/custom`. This has allowed issues to creep into our code base. Enabling `<docroot>/profiles/custom/cgov_site/modules/custom` and `<docroot>/profiles/custom/cgov_site/themes/custom` will require fixes to the codebase.

> **ESTIMATE** NN

### See also
#4143

**Comment by jfrank-nih** [comment]
I think already done? 

https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/phpcs.xml#L38

**Comment by bryanpizzillo** [comment]
IDK - I am confused, and I confused myself. See https://github.com/NCIOCPL/cgov-digital-platform/issues/2920, which would have been created about the same time.

**Comment by bryanpizzillo** [comment]
I am going to close this as it seems duplicate with #2920. One of the two probably separated out the setting up the config with fixing the issues, but #2920 says we need to go fix things.
