### ISSUE TITLE
Front-end Display of Sitewide Search - Results Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#292]
This story is to style the Results Page for use with Sitewide Search #1156 

* Only display English Best Bets on the English site
* Display content type after the page title in parentheses for the following content types that appear in results:
    * Infographic
    * Video
    * Video Carousel
* Only display Spanish Best Bets on the Spanish site
* Display content type after the page title in parentheses for the following content types that appear in results:
    *  Infographic (text to be displayed is "Infografía")
    *  Video (text to be displayed is "Video")
    * Video Carousel - (text to be displayed is "Lista de reproducción de videos")
* Display the file size, and an icon if a selected list item is a file content type

**Comment by bryanpizzillo** [comment]
Closing as these were placeholders and do not have a lot of information. Will be recreated as needed.
