### ISSUE TITLE
Table remains left aligned even when center aligned for all content types

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2921]
### Issue description
*Description of the issue*
When we create a table in the wysiwyg editor and select center alignment, the table that we see at the front end gets the left alignment. We checked it for Article and Press Release.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to cms-test and create an article content type by filling all the required fields.
2. Create a table in the wysiwyg editor
2. Select the center alignment for the table.
3. Publish the content.
4. When viewed at the front end, the table does not appear center aligned.

### What's the expected result?
The table should appear center aligned

### What's the actual result?
-The table appears left aligned.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/94488707-1cdcbe80-01b1-11eb-86d9-d32f08f3b089.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by SupriyaSaxena0605** [comment]
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/31008800/7ff5b089-2b9a-497d-a0af-ebefc58b1aaf)

**Comment by andyvanavery31** [comment]
Closing due to this no longer occurring per the last comment above.
