### ISSUE TITLE
Events - End Time Shall Not Be Allowed to be Earlier Than Start Time

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2922]
### Issue description
*Description of the issue*
For events (seen in DCEG) we can select earlier end time than start time but when we download the event in the outlook, the start time is always the earlier time entered. So outlook always picks up the earlier time entered in the CMS and relates it to the Start Time. To fix this issue, the CMS will be changed so that a content editor cannot put an end time that occurs prior to the start time.

### Steps to reproduce the issue

1.  Create an event content type on DCEG
2. Select date as the system date
3. Select End Time earlier than Start Time (For example, Start Time 3pm and End Time 6am).
4. Publish the event content type
5. View at the front end and the time will appear as 3:00pm-6:00am
6. For adding to the Outlook Calendar click the "Add to Outlook Calendar" link

### What's the expected result?
- If a user in the CMS puts an end time that occurs earlier than the start time, then the user shall be given an error and not allowed to post the event.

### What's the actual result?
- The front end time appears as 3:00pm-6:00am and not in sync with the Outlook Calendar

### Acceptance Criteria

```gherkin
Scenario: A content editor tries to add an event with a start time later than end time in English
  Given a content editor is logged into the CMS
    And the content editor is creating a new event in English
  When the user enters a start time of 3pm on June 1st 2024
    And the user enters an end time of 6am on June 1st 2024
    And the user clicks the "Save" button
  Then the system will display an error message "Start date and time must begin before event ends. Please select a start date and time that begins prior to the event end date and time."
    And the content editor cannot save the content item
```

```gherkin
Scenario: A content editor tries to add an event with a start time later than end time in Spanish
  Given a user is logged into the CMS
    And the content editor is creating a new event in Spanish
  When the user enters a start time of 3pm on June 1st 2024
    And the user enters an end time of 6am June 1st 2024
    And the user clicks the "Save" button
  Then the system will display an error message "La fecha y la hora de inicio deben ser anteriores a la finalización del evento. Seleccione una fecha y una hora de inicio anteriores a la finalización del evento."
    And the content editor cannot save the content item
```

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/94491635-92975900-01b6-11eb-97e7-5c32c9bc3284.png)

### Related Tickets
* Originally captured in #1669 which was closed due to this ticket having more information.

**Comment by alinai** [comment]
@navsunka , I could reproduce it for Cgov as well.

**Comment by alinai** [comment]
@andyvanavery31 , @navsunka,  the Spanish "Event" content type does not have any "Event Start Date & Time" and "Event End Date & Time" field. 
cc: @sarinapadilla , @laurelthrash, @KateMashkinaNIH, @santwuma

**Comment by alinai** [comment]
@andyvanavery31 , if we create a new Spanish "Event" content type (not the translation), we don't see the Date/Time at the front end even if we add Date/Time in the Spanish content in the CMS.  It is same on cms-test.
cc: @KateMashkinaNIH , @navsunka

**Comment by alinai** [comment]
@andyvanavery31 , should it allow us to enter same "Start time" and "End Time"?

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/702e598d-cfc0-4195-b8b9-7d84b005b143)

**Comment by alinai** [comment]
It is also allowing us to select and save past dates from the "Start Date" and "End Date" field without displaying any error message. cc: @andyvanavery31 , @navsunka , @KateMashkinaNIH , @sarinapadilla

**Comment by andyvanavery31** [comment]
@alinai great finds! For the Spanish events, I will look in the backlog to see if this already exists, but if it doesn't, I will make a new ticket for it. 

For being able to make an event that runs for 0 time (i.e. a 2:00pm - 2:00pm meeting), I am fine with this use case. I don't think it will be common, but if someone needs to use it as an start/end time standalone, I'd rather have it available instead of making them run it from 2:00pm - 2:01pm which I think looks worse.

For being able to create an event in the past, I would like to remove this capability, though I believe it is outside of the scope of this ticket. Therefore, I will make another ticket to address it, unless you think it should be added to this ticket's work.

cc: @navsunka @KateMashkinaNIH @sarinapadilla
