### ISSUE TITLE
Update Content Block functionality

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2925]
### Issue description
Currently the content block has a title field, which is only optimized to work when it is used within a guide card row. But the more common use of the block is on Mini Landing pages, where the title field comes through but is unstyled.

Smallest update would be to fix the tooltip. 

Better functionality would come if the content block itself were more flexible, having options to appear either with or without the title. 

NOTE: Given the limited use of the guide cards, and the possibility that during redesign we will come up with a more functional solution for those kinds of links, this should be discussed with the redesign team. 

> **ESTIMATE** 20

### What's the expected change?
- Two template options for content blocks (modeled after lists) - with title and without
- Styles added to mini-landing page to accomodate title

### What's the current functionality?
- Content block has title field by default, and shows but is unstyled. 
- content blocks are used in guide cards, as well as on mini-landing

### What's the updated acceptance criteria?
```gherkin
TBD based on solution.
```

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by VictoriaSunNIH** [comment]
This ticket should be discussed as we revisit larger conversations around how this block should be used

**Comment by bryanpizzillo** [comment]
Closing this as it is outdated. Basically, the redesign of Home and Landing means the old content blocks should be retired. Mini-landing has also been redesigned and the new NCIDS Content Block does not have the title field.
