### ISSUE TITLE
Video carousel not working in mobile

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2928]
### Issue description
On mobile, the video carousel buttons are not appearing to advance the videos forward or backward.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/diagnosis-staging/prognosis on mobile device
2. Note the controls for going forward and back through the carousel are missing.

### What's the expected result?
Carousel should show controls

### What's the actual result?
Controls not appearing.

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
This was pushed as part of PR 2923. Closing.
