### ISSUE TITLE
Separate caching of main menu for path-based domain from the non-path version

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#2930]
### Issue description
After a deployment, the first site visitor to one of the  microsites with a path-based domain (nano, mypart, nci-connect) generates the main menu for that site. This copy of the menu is then cached for any future  visitors.

There's a window immediately after a deployment when the site monitoring system may visit micro-site.ncigov.acsitefactory.com/user/login *before* a user visits www.cancer.gov/micro-site.  If this happens, the menu will be cached with the wrong context and later users will find that it doesn't work correctly.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
The identified microsite page will not be impacted by the contents of this ticket. This will be closed.

**Comment by blairlearn** [comment]
Adding for clarity: The mechanism for generating the navigation has changed as part of the ncids changes.
