### ISSUE TITLE
The /notrials view of the Dynamic Listing Pages does not work

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2933]
### Issue description
When a visitor requests a dynamic listing page that has 0 results, the user is taken to a /notrials page. This page lets them know there are no trials, and they can contact the CIS. In order to ensure Google does not index these, a 404 status is returned with the response. It looks like the general 404 page is being returned instead of the bespoke /notrials page.

Examples:
* Listing Page URL: https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/l-377202
* Redirected No Trials URL: https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/notrials?p1=l-377202
* (Example working notrials) https://colo.cancer.gov/about-cancer/treatment/clinical-trials/intervention/notrials?p1=l-377202

> **ESTIMATE** TBD

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo , @blairlearn  - would this ticket be OBE after we launch the new DLPs?  Is there anything else we need to do to make sure we are showing the right 404 pages? (I think it's all covered in ACs but double checking)

**Comment by blairlearn** [comment]
In short, yes.  Part of the go-live for dynamic listing pages is to stop serving them from Shady Grove.  That will negate the part of the "Fancy 404" setup that says "Anything that runs at Shady Grove gets its error page from Shady Grove."
