### ISSUE TITLE
Sticky nav flashing on cgov and doc sites as you scroll down 

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#2935]
### Issue description
As you scroll on cgov or any of the doc sites, the header looks like it flashes because the ribbon disappears too early then there is gap underneath the global nav bar as it sticks to the browser window (viewport) and where the content area begins. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to a cgov or doc page. Here are some examples: 
- https://www.cancer.gov/
- https://dceg.cancer.gov/about
- https://www.cancer.gov/nano/research/plan
- https://www.cancer.gov/rare-brain-spine-tumor/refer-participate/referrals/clinic

2. Scroll slowly down the page to witness 'flashing' of header elements

### What's the expected result?
- There shouldn't be any 'flashing' of header elements. It should be a smooth transition.

### What's the actual result?
- The header elements appear to be 'flashing' causing a gap underneath the global nav bar as it sticks to the browser window (viewport) and where the content area begins.  

### Additional details / screenshot
![Screen-Shot-2020-10-21-at-4 31 20-PM](https://user-images.githubusercontent.com/4921685/96787035-1829b580-13bf-11eb-84c9-ee777f6a5aaf.jpg)
![Screen-Shot-2020-10-21-at-4 31 26-PM](https://user-images.githubusercontent.com/4921685/96787046-1e1f9680-13bf-11eb-9138-a837b0ef02fc.jpg)
![Screen-Shot-2020-10-21-at-4 32 22-PM](https://user-images.githubusercontent.com/4921685/96787047-1eb82d00-13bf-11eb-998b-3e862a2cf349.jpg)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
Sticky nav has been removed from c.gov, closing this ticket as Overcome By Events.
