### ISSUE TITLE
Create editable hero image

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2941]
Please create an editable hero image that will be displayed below the main navigation on the Connect homepage.

We believe that this image will be evergreen, but we should have the ability to change the image that is displayed in the hero location.

Including comps for reference:

Final Desktop: https://publicis.invisionapp.com/share/V3Y2YRRSGMH
Final Mobile: https://publicis.invisionapp.com/share/NKY61SDE97H
Annotated Comps: https://publicis.invisionapp.com/share/NEYL4UKXB63

**Comment by sarinapadilla** [comment]
Outdated due to redesign.
