### ISSUE TITLE
Ability to edit homepage paragraphs

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2942]
As a content owner, I want edit the paragraph content blocks that appear on the homepage so that title, description text, and and/or image can be changed via the Drupal CMS without a code release.

Comps: 
Final Desktop: https://publicis.invisionapp.com/share/V3Y2YRRSGMH
Final Mobile: https://publicis.invisionapp.com/share/NKY61SDE97H
Annotated Comps: https://publicis.invisionapp.com/share/NEYL4UKXB63 

Estimate:

Acceptance Criteria:

Content editor is able to revise home and landing page content via the Drupal CMS and send the homepage through workflow to publish updates live.

**Comment by bryanpizzillo** [comment]
I am closing this as the invision comps are no longer valid. Also we redesigned these, so whatever this ticket was about is not longer valid anyway.
