### ISSUE TITLE
Create Press Release Listing Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#297]
This story is to create the Listing Page (aka archive) for [Press Release](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) #155.

The Listing Page will allow for listing Press Releases by Year.

Wireframe
[Example of Listing Page](https://www.cancer.gov/news-events/press-releases/2018)

Requirements:
- English version
  - [ ] Page view as /news-events/press-releases/YYYY 
  - [ ] Show only English content
  - [ ] Language switcher block works and says "Espanol" (at top right of page)
  - [ ] Year in page title: "YYYY Press Releases"
  - [ ] show Year selectors: "2019 | 2018 | ..."
  - [ ] Block between header and content: ```Get Email Updates From NCI:
Get email updates from NCI on cancer health information, news, and other topics```. This block needs to be editable by content authors.
  - [ ] Have pager if over 10 *(???)* press releases
- Spanish version
  - [ ] Page view as /espanol/noticias/comunicados-de-prensa/YYYY showing only Spanish content
    - ISSUE: Can't define alternate path for page view.   
      - WORKAROUND: Can define an alias `/noticias/comunicados-de-prensa -> /news-events/press-releases`
        - RISK:  Duplicate content on `/espanol/noticias/comunicados-de-prensa/YYY` and `/espanol/news-events/press-releases/YYY`.   (will try using Redirect module instead)
  - [ ] show only Spanish content
  - [ ] Language switcher block works and says "English" (at top right of page)
  - [ ] Year in page title: "Comunicados de prensa de YYYY"
  - [ ] show Year selectors: "2019 | 2018 | ..."
  - [ ] Have pager if over 10 *(???)* press releases (w/Spanish labels)
  - [ ] Block between header and content: ```Suscríbase al correo electrónico de actualizaciones del NCI: Reciba actualizaciones por correo electrónico del NCI con información médica sobre el cáncer, noticias y otros temas.```

Implementation:
- For listing view modes use:
  - List: Item: Title
  - List: Item: Title Date
  - List: Item: Title Date Desc
  - List: Item: Title Date Desc Image
  - List: Item: Title Date Image
  - List: Item: TItle Desc
  - List: Item: Title Desc Image

**Comment by bgnih** [comment]
Needs:
- Page view as /news-events/press-releases/YYYY 
  - [ ] show only English content
  - [ ] Year in page title: "YYYY Press Releases"
  - [ ] show Year selectors: "2019 | 2018 | ..."
  - [ ] Have pager if over 10 *(???)* press releases
- Page view as /espanol/news-events/press-releases/YYYY showing only Spanish content
  - [ ] show only English content
  - [ ] Year in page title: "YYYY Press Releases"
  - [ ] show Year selectors: "2019 | 2018 | ..."
  - [ ] Have pager if over 10 *(???)* press releases
