### ISSUE TITLE
Event Content type: User can Save and Publish with End Date and End Time earlier than Start Date and Start Time 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#2979]
### Issue description

Event Content Type- When we enter End Date (12/03/2020)  earlier than Start Date (12/10/2020), we can publish the content without getting any warning or error message. Same thing happens for End Time and Start Time. At the front end we see only the Start Date though we entered the End Date at the back end. For the time, we can see both the Start time and End Time with the Start time showing later time.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Create an Event Content Type and fill up all required fields 
2. Enter  Start Date as 12/10/2020 
3.  Enter end Date as 12/03/2020 
4. Enter Start Time as 11:00am
5. Enter End time as 09:00am
6. Publish the content through the work flow and view the content at the front end.

### What's the expected result?
- The user should be getting a warning or error message and should not be able to Save and Publish his content on trying to Publish an Event content type with End Date (12/03/2020)  earlier than Start Date (12/10/2020) and should be getting a warning or error message and should not be able to Save and Publish his content  on trying to Publish an Event content type with End Time (09:00 am)  earlier than Start  Time (11:00am) 

### What's the actual result?
- The user does not get any warning or error message and is able to Save and Publish his content  on trying to Publish an Event content type with End Date (12/03/2020)  earlier than Start Date (12/10/2020) and does not get a warning or error message and is able to Save and Publish his content on trying to Publish an Event content type with End Time (09:00 am)  earlier than Start  Time (11:00am) 

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/100916362-a0fa3d80-34a3-11eb-8f26-140fd839f1dc.png)

![image](https://user-images.githubusercontent.com/28455973/100916481-cbe49180-34a3-11eb-837a-c3141c1032f8.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Replica of #2922 and is to be closed.
