### ISSUE TITLE
Additional  /sites/settings/  *.settings.php files are not being pulled in.

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#2983]
### Issue description
Additional  /sites/settings/  *.settings.php files are not being pulled in. This is a blocker since it affects several production configuration settings.

> **ESTIMATE** 3

### Steps to reproduce the issue

A quick way to verify this is checking to see if CSS/JS aggregation is disabled: 
https://www-cms-dev.cancer.gov/admin/config/development/performance

Another is: drush cget locale.settings

### What's the expected result?

CSS/JS Aggregation should be disabled on non-production tiers.
 https://www-cms-dev.cancer.gov/admin/config/development/performance
<img width="930" alt="Screen Shot 2020-12-03 at 3 20 13 PM" src="https://user-images.githubusercontent.com/38888889/101084004-37faee80-35a5-11eb-8b2f-b4d87be851b7.png">

### What's the actual result?

<img width="876" alt="Screen Shot 2020-12-03 at 3 20 06 PM" src="https://user-images.githubusercontent.com/38888889/101084049-4e08af00-35a5-11eb-9ec3-b0e73822056d.png">

**Comment by blairlearn** [comment]
Not an issue.  You cannot use the UI to check whether a `.settings ` file has been loaded.

1. The UI for the various entities is just loading the YAML files.
2. `drush cget whatever` does the same thing.
3. None of these will find values from the settings files.

From https://www.drupal.org/docs/drupal-apis/configuration-api/configuration-override-system

> _Note_ that values overridden via `$config` within `settings.php` will not be viewable from the Drupal administration interface ([until #2408549: There is no indication on configuration forms if there are overridden values is fixed](https://www.drupal.org/project/drupal/issues/2408549),

The _correct_ way to check whether settings values were loaded is to login on the machine and run

`drush php`

From the REPL, run:
`\Drupal::config('my_setting')`

For `system.performance`, which is where aggregation and fast_404 are set, it would be:
`\Drupal::config('system.performance')`

Which would lead to the output:
```
>>> \Drupal::config('system.performance')
=> Drupal\Core\Config\ImmutableConfig {#5188
     cache: [
       "page" => [
         "max_age" => 16588800,
       ],
     ],
     css: [
       "preprocess" => false,
       "gzip" => false,
     ],
     fast_404: [
       "enabled" => true,
       "paths" => "/.*/",
       "exclude_paths" => "/\/ErrorPages\/.*/i",
       "html" => "<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "@path" was not found on this server.</p></body></html>",
     ],
     js: [
       "preprocess" => false,
       "gzip" => false,
     ],
     stale_file_threshold: 2592000,
     _core: [
       "default_config_hash" => "b2cssrj-lOmATIbdehfCqfCFgVR0qCdxxWhwqa2KBVQ",
     ],
   }
>>> 
```
