### ISSUE TITLE
CTS app hangs when API returns no trial study sites

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#2984]
When performing a search, trials returned by the CTS API seem to remove the trial.sites element if there are no sites, as opposed to returning an empty array. The app does not guard against this and breaks displaying to the user an endless loading screen. 

Seyi has set up a test package for testing `1.0.3-beta.1`

NOTES:
At the time of breakage, some URLs are:
* Search Results : https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=1&t=C3550
* View Trial : https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2018-02825

* When we come to the CTS search results page from print page using "go back" option of the browser, the search results are not loaded

### Related Tickets
* https://github.com/NCIOCPL/clinical-trials-search-app/issues/205
* PR: https://github.com/NCIOCPL/clinical-trials-search-app/pull/208

**Comment by blairlearn** [comment]
Closed by b2ee9cc2557094d96dc8e25fdfa90d4fada46155
PR #2994
