### ISSUE TITLE
Change Request: Bypass Requests & Appropriations: Highcharts Line Graph

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2986]
### Issue description
In next round of Highchart edits, the "Bypass Requests and NCI Appropriations” graph should be updated with the data found in the attached excel workbook. Title should be “Historical Budget Comparison”and the subtitle should be updated to “Fiscal Years 1974 – 2021” (from 2020).

[professional-judgment-presidents-budget-enacted-fy19 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/5690701/professional-judgment-presidents-budget-enacted-fy19.1.xlsx)

### Related Tickets
* Original Story Ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/2673
* JIRA Ticket: https://tracker.nci.nih.gov/browse/CGOV-10856

**Comment by blairlearn** [comment]
Completed by ffc4fb484a24ae975ff9edfe85a152b493b5ea1e
