### ISSUE TITLE
CTS No Trials Search Page Live Help Link

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#2987]
CTS No Trials Match Search Page is going to the regular Cancer Information LiveHelp queue instead of the CTS LiveHelp queue.

### Related Issues
https://github.com/NCIOCPL/clinical-trials-search-app/issues/203

**Comment by blairlearn** [comment]
Closed by b2ee9cc2557094d96dc8e25fdfa90d4fada46155
PR #2994
