### ISSUE TITLE
Create Press Release Listing Block for Landing Pages

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#299]
This story is to create the Listing Block for use on Landing Pages.

For the listing block on the News and Events Landing Page:
* Display a maximum of the 10 most recent items in reverse  chronological order 
* Display the following for each press release (on desktop and tablet):
  * Page Title
  * Listing Description 
    * If no listing description exists, use the meta description
  * Posted Date
  * Thumbnail image associated with the press release
* On mobile, only display the following:
  * Page Title
  * Posted Date
* Display a link to "All NCI News"  that links to the most recent year
  * Display the link text as "Todas las noticias del NCI" when viewing the link on spanish

[Example Landing Page](https://www.cancer.gov/news-events)

Wireframe - https://hzgfzw.axshare.com/#g=1&p=news___events_landing_homepage
![capture1](https://user-images.githubusercontent.com/43382138/50358945-fb08cf00-0528-11e9-972e-9784a283203d.PNG)

**Comment by bgnih** [comment]
Requirements needed:
- How many items should appear in block?   
- This is a displaying in a different layout than on the PR page, correct?  (This has images, the listing page does not)
- Which description field should be displayed here?

**Comment by bryanpizzillo** [comment]
I may reopen this pending some testing. We need to control items per page in 2 different ways. However, the homepage block's numbers to display and the archive block's numbers to display should be ok for now. (One would want each display configured to be the same, and when it is used on a page, then the number of items to show can be changed.
