### ISSUE TITLE
Program Structure Pie Chart Corrections

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2995]
Hi @eriksmeyer  - Looks like unfortunately we missed the updates to the Program Structure pie chart. They are all wrong, so I'm wondering if this one just didn't update with the 2019 data during the merge? 

Here are the correct numbers:

Research - 69.6%
Resource Development - 14.5%
Cancer Prevention and Control - 5.8%
Program Management and Support - 10.1%

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/data/program-structure

**Comment by blairlearn** [comment]
Completed by 1fb4d4b3f6d20948de1faa2f904493906b80f14a
