### ISSUE TITLE
RPGs Number of Awards Chart Change

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2996]
Hi @erikscottmeyer  - Here is just a small change to the RPGs Number of Awards chart.

Years should be 2010 to 2019 (remove 2009 from title and data set).

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg#awards

**Comment by blairlearn** [comment]
Completed by dc453a879a7c3a1c149922147d256f4411158228
