### ISSUE TITLE
RPGs Funding Mechanisms Chart Change

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2997]
Hi @erikscottmeyer - Looks like there is a bit of a technical issue in the RPGs Funding Mechanisms chart.
 
When hovering over each RPG type the percentage numbers are displayed as dollar amounts. Instead it should display the budget $ amount. Please see last year as an example: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg#ui-id-2. Here is the FY19 data if you need that again: [rpg-funding-paylines-fy19-2.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/5736288/rpg-funding-paylines-fy19-2.xlsx)

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg#ui-id-2

**Comment by erikscottmeyer** [comment]
@allymh The excel sheet doesn't have budget numbers, it only has percentages.  What's the number for 2019 RPG total funding?  If I had that, I could calculate the others.

**Comment by allymh** [comment]
@erikscottmeyer Ahh - that's strange! Ok - I will ask Alice to send an updated version of the data that includes those numbers. Unfortunately all I have is the excel sheet as well.

**Comment by erikscottmeyer** [comment]
@ally apparently the total is $2456156.41 (I got that from the updated sheet referenced in https://github.com/NCIOCPL/cgov-digital-platform/issues/2998). I used that to calculate all of the others; I'm attaching an updated version of the spreadsheet with a new tab, Dollar Totals, that has those numbers.

**Comment by erikscottmeyer** [comment]
[rpg-funding-paylines-fy19-2-esm.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/5766265/rpg-funding-paylines-fy19-2-esm.xlsx)

**Comment by allymh** [comment]
@erikscottmeyer  Oh, ok! Great! Hopefully that is the correct amount for this chart as well but I will double check with the client.

**Comment by blairlearn** [comment]
Completed by 2cf3c86fd8b52e39b6d486c665df0641c3c6b1cb
