### ISSUE TITLE
RPG Awards by Grant Activity Code Higcharts

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2998]
Hi @eriksmeyer - Apologies - looks like I missed sending you the data for one of the charts on the RPGs page. 

The RPG Awards by Grant Activity Codes chart should have the years 2010 - 2019. [rpg-awards-by-activity-code-fy19 (2).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/5736311/rpg-awards-by-activity-code-fy19.2.xlsx)

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/rpg#grant-codes

**Comment by blairlearn** [comment]
Completed by 0d9624ad693cbec889c2802a68f5eb29f94dd257
