### ISSUE TITLE
NRSA Chart Changes

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#2999]
Hi @erikscottmeyer - Just a couple of small changes to the NRSA High Chart.

2014 figures incorrect should read 485, 947, and 1,432.
2015 figures incorrect should read 538, 893, and 1,431.

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/nrsa

**Comment by blairlearn** [comment]
Completed by a41d0c9341cc275f0d0b33fc9b496c22e6a69003
