### ISSUE TITLE
Spike: Related Pages Field Questions

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#30]
Our users would like the following UX for adding related pages (its a field) they should be able to:
* Select site content, though a nice UI, of any(?) Node, and a few Media (Video, Infographic, Document) entities
   * The link should pull in the Entities title - The user should not have to specify the title
   * The user should be able to override the title
* Enter an external link & custom title for that link

* Note: The approach should take into account a possible future where the Node/Media items description should be displayed. This would also mean the editors could override the description too, AND external links would get a description.  They may even want images, who knows -- the point is the approach should support future flexibility!

**Comment by bgnih** [comment]
There doesn't appear to be any out of the box (OOTB) solutions that meet these requirements.  Some components that meet parts of the requirements include:

### LinkIt 
- Pros
  - more flexible interface for entering links
  - has dropdowns to select existing node content with limited previewing ability
  - Pulls in title and lets you override
- Cons
  - only works OOTB for WYSIWYG editor links, but there is a patch (still being worked on) to allow it to be used with EntityReference fields.

![image](https://user-images.githubusercontent.com/44211455/49745453-fad91b80-fc6c-11e8-99c5-c106ba821fde.png)

![image](https://user-images.githubusercontent.com/44211455/49745558-3f64b700-fc6d-11e8-980a-2ca52e86c4e7.png)


### Entity Reference + Entity Browser
- Pros
  - Can define custom view to display options
  - Decent interface to switch between views using tabbed interface
  - Can select multiple items across tabs and add all at once when completed
- Cons
  - Can only select a single entity type (can't select nodes and media items)
  - No support for external links
  - No way to override titles/descriptions OOTB

![image](https://user-images.githubusercontent.com/44211455/49745881-f82af600-fc6d-11e8-9b7d-091f88e4a964.png)

![image](https://user-images.githubusercontent.com/44211455/49745651-776bfa00-fc6d-11e8-9537-dcd960412f0c.png)

### Dynamic Entity Related
- Pros
  - Can select multiple entity types (such as Nodes and Media items) in a single field 
  - Can define different selector views for each entity type
- Cons
  - Does not work with Entity Browser yet (patch underway)
  - No support for external links
  - No way to override titles/descriptions OOTB

How it looks after selecting content
![image](https://user-images.githubusercontent.com/44211455/49746797-f19d7e00-fc6f-11e8-919c-1f46a55d3238.png)

Defining different reference types to for dropdowns
![image](https://user-images.githubusercontent.com/44211455/49746865-1c87d200-fc70-11e8-8aaf-cfe8b19cac08.png)

**Comment by bgnih** [comment]
Javascript/php code to get live title on Link fields: https://www.drupal.org/project/link/issues/1295160#comment-6896876 (D7)

**Comment by bgnih** [comment]
Paragraphs implementation
![image.png](https://images.zenhubusercontent.com/5c0fd0a81a65780cf410b298/977064b8-8cb1-4553-82c2-455ca1c1c935)

with entity browser and optional title/desc fields (would need wiring to link to selected node's title)
![image.png](https://images.zenhubusercontent.com/5c0fd0a81a65780cf410b298/2fdb0004-a970-41fc-99fd-81283503cace)

custom entity browser view
![image.png](https://images.zenhubusercontent.com/5c0fd0a81a65780cf410b298/0fd1a92f-1470-45eb-be07-431f4acaa9cf)
