### ISSUE TITLE
Total Number of K Awards Chart Change

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#3000]
Hi @erikscottmeyer - Small change in the Total Number of K Awards high chart.
Years should be 2010 - 2019 and the 2019 count is incorrect and should be 446

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/k-awards

**Comment by blairlearn** [comment]
Completed by 5bdb6dba127229ce61d0bc7b8dec9494dc687d25
