### ISSUE TITLE
Grant and Contract Awards Map Update

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#3001]
Hi @erikscottmeyer - It looks like this data didn't get merged. 2019 changes aren't appearing on preview.

Original ticket: https://github.com/NCIOCPL/cgov-digital-platform/issues/2672

http://ncigovcdode331.prod.acquia-sites.com/about-nci/budget/fact-book/extramural-programs/grant-contract-awards

**Comment by allymh** [comment]
Hi @erikscottmeyer  - Just two little errors that need to be fixed. 

 Alabama - count correct but amounts wrong. Grants is 32,036,913 and Contracts is 666,907
 Arizona - count is correct but amounts wrong. Grants is 37,531,259 and Contracts is 1,267,397.

**Comment by blairlearn** [comment]
Completed by 84996b94bae94a0cecdf924eff12df058d9e3b12
