### ISSUE TITLE
Refactor high charts code to load JSON data from content

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3008]
### Issue description
The high charts functionality for the Fact Book uses data which is encoded directly into the JavaScript files. Although this was expedient when the charts went live several years ago, it means that all updates and corrections to the data require developer time and a software release.

Link to High chart - https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards

> **ESTIMATE**
> - First: 2
> - Subsequent: 1

Impacted files include (this list may be incomplete):
* [aids-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/aids-funding.js)
* [bypass-appropriations.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/bypass-appropriations.js)
* [grants-contracts.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js)
* [html-amount.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-amount.js)
* [html-bar.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-bar.js)
* [html-extramural.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-extramural.js)
* [html-nrsa.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-nrsa.js)
* [kawards-pie.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/kawards-pie.js)
* [management-fund.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/management-fund.js)
* [moonshot-obligations.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/moonshot-obligations.js)
* [number-rpg-awards.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/number-rpg-awards.js)
* [obligations-mechanism.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/obligations-mechanism.js)
* [program-structure.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/program-structure.js)
* [rms-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rms-funding.js)
* [rpg-cost-per-award.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-cost-per-award.js)
* [rpg-funding.js](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-funding.js)

Next steps:
1. Review SOP - https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Standard%20Operating%20Procedures/deploy-acsf-site-to-local.md?csf=1&web=1&e=jhXwx8
2. Review affected files and update as needed
3. Define an approach 
4. Implement approach

### What's the expected change?
- The data should be loaded from JSON files stored as content in the CMS.

### What's the current functionality?
- The data is hard-coded in .JS files which are part of the front end code.

### What are the updated requirements?
- 3008 . JSON files uploaded to the CMS will provide the data for an individual HighChart .JS file used in the Factbook.
    - 3008.1. The CDEConfig object shall have a property that contains for the base URL for data files used by Factbook charts.
        - 3008.1.1. The CDEConfig object shall have a "ChartData" property.
        - 3008.1.2. The "ChartData" property shall have a "Factbook" property.
        - 3008.1.3. The "Factbook" property shall have a "BaseUrl" property.
            - 3008.1.3.1. The "BaseUrl" property will be a string.
            - 3008.1.3.1. The "BaseUrl" property value will be the base URL for all files uploaded to the CMS containing chart data.
        - 3008.1.4. The "Factbook" property shall have a "DataType" property.
            - 3008.1.4.1. The "DataType" property will be a string, and allow the value "json".
    - 3008.2. The individual HighChart .JS file shall hardcode the file name associated with the CMS file containing JSON data for the chart.
    - 3008.3. The individual HighChart .JS file shall use the "BaseUrl" value and the hardcoded file name to determine the path for the CMS file containing JSON data for the chart.
    - 3008.4. The individual HighChart.JS file shall read in the JSON data in the file and create the chart using that data.

### What's the updated acceptance criteria?
```gherkin
Scenario: CDEConfig object is updated with ChartData parameter

Given a user is viewing a page with a HighChart
When the user views the page source
Then the CDEConfig JSON object literal has a property "ChartData"
  And the value for the "ChartData" property is an object with the property "Factbook"
  And the value for the "Factbook" property is an object with properties "BaseUrl" and "DataType"
  And the "BaseUrl" property is a string with the base path where the HighChart data files live (update this with the base URL)
  And the "DataType" property is an object with a string, "json"
```

```gherkin
Scenario: Individual chart JS files use hardcoded JSON file names to load data

Given a developer creates a new HighChart .JS file
  And the .JS file has a hardcoded value with the filename containing the JSON data
  And the user uploads a JSON file containing the data to the CMS
When the user views the page containing the chart
Then the chart will display the data in the JSON file
```

```gherkin
Scenario: Updating uploaded chart JS files updates the chart

Given a HighChart JSON file has been uploaded to the CMS
  And the .JS file for the chart exists
  And the user can view the chart on the page containing it
When the user uploads an updated JSON file with new data for the chart
Then the chart will display the new data from the JSON file
  And the user can view the chart on the page containing it
```

### Tasks (SP 5)
- [x] Review [SOP](https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Standard%20Operating%20Procedures/deploy-acsf-site-to-local.md?csf=1&web=1&e=jhXwx8)
- [x] Review affected files and update as needed
    - [x] #3719 
    - [x] #3720 
    - [x] #3721 
    - [x] #3722 
    - [x] #3723 
    - [x] #3724 
    - [x] #3725 
    - [x] #3726 
    - [x] #3727 
    - [x] #3728 
    - [x] #3729 
    - [x] #3730 
    - [x] #3731 
    - [x] #3732 
    - [x] #3733 
    - [x] #3734
- [x] Setup content

**Comment by jfrank-nih** [comment]
Other potential, not necessarily superior, ideas include:

- Loading data files from Netstorage where they're less likely to get accidentally trounced
- Putting data into some HTML block on the source page itself so that it can be directly replaced from the WYSIWYG editor

**Comment by meglake** [comment]
Noting from a 6/16/22 convo with Lynn that this might be something we'd want to do sooner than the next Fact Book as data visualization requests are becoming more popular. She also noted that if NCORP comes on the platform they will likely need a map functionality (like what high charts offers). I will also put this item on the backlog for redesign to consider.

**Comment by jfrank-nih** [comment]
@meglake , if we're talking generic data visualization requests, you may want to open a new ticket specifically on "create ad-hoc chart or map from data source". This particular task would significantly simplify updating _current_ charts each year/off-cycle. But it wouldn't make creating a new chart from scratch any simpler. 

Conceptually, that's a different thing, and a much harder task. _Very roughly_ speaking, I would think of it this way:

- Updating a single chart's data in the codebase: LOE 1
- Updating all charts to load from external files (this ticket): LOE 10
- Making ad-hoc charts available from the front end: LOE 50

That's all custom coding it, of course. If we're able to find a module that supports charts (Highcharts or otherwise) it could bring that down. Alternatively, we could also examine loading charts from an external source such as Power BI into the platform. That's definitely the most flexible route.

My point is mostly that we probably want to separate out the particular requests (update chart, update charts from file, create charts ad-hoc) as they're significantly different scopes.

**Comment by laurelthrash** [comment]
@sarinapadilla @andyvanavery to follow-up with @blairlearn on this ticket to determine if additional information is needed and inquire about ACs before moving forward. Cc: @santwuma

**Comment by blairlearn** [comment]
From a discussion on December 7, the high-level design for this is:

- The data moves to JSON files to be uploaded into the CMS.
- Individual charts will have a hard-coded name for their particular data file.
- The base URL for the chart data (e.g. `https://www.cancer.gov/about-nci/budget/fact-book/data`) is available from the front-end global `CDEConfig` object.
