### ISSUE TITLE
Enabler: Update list of modules to disable on ODEs

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3010]
Update the [blt.yml entry for ODE environments](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/blt/blt.yml#L33-L35) to disable all production-only modules.

This list should include:
acquia_connector, shield, simplesamlphp_auth, cgov_saml_auth_config, cgov_https_config, akamai, syslog

**Comment by bryanpizzillo** [comment]
@blairlearn 

1. I don't think `cgov_https_config` is correct. The ODEs can use https now without cert errors or anything.
2. It is an acquia environment so the `acquia_connector` and `shield` should be able to stay unless they are actively breaking things. (I would rather find breakage here than on ACSF somewhere)
3. I am with you on saml

So it sounds like the entries should be the following, which is basically the same as dev except for SAML modules.
```
    enable: [dblog, acquia_connector, shield, cgov_https_config, cgov_caching_nocdn]
    uninstall: [syslog, cgov_caching_cdn, akamai, simplesamlphp_auth, cgov_saml_auth_config]
```

Does that sound ok to you?

**Comment by blairlearn** [comment]
Sounds good to me. Not sure where my list came from at this point.

**Comment by jfrank-nih** [comment]
The list in Bryan's comment above is how the configuration currently is except for the SAML portions. But we moved to have SAML always enabled and shown/not shown at the `/user/login` screen based on other configuration. So it's irrelevant now. Closing this.
