### ISSUE TITLE
All Spanish PDQs get horizontal scroll bar within an accordion at mobile breakpoint 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3015]
### Issue description

 On Chrome and IE, all Spanish PDQs get horizontal scroll bar at mobile breakpoint for the "Información sobre este sumario del PDQ" accordion at mobile breakpoint.  It is happening because of the link https://www.cancer.gov/espanol/tipos/leucemia/pro/tratamiento-llc-pdq within the accordion which is not wrapping properly. (See the screen-shot)

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/espanol/tipos/leucemia/pro/tratamiento-llc-pdq
2. Switch to mobile breakpoint.
3. Scroll all the way down until the last accordion, "Información sobre este sumario del PDQ", on the page is reached.
4. Expand the accordion to see the horizontal scroll bar that appears just above the date.

### What's the expected result?
- No horizontal scroll bar should appear within the accordion

### What's the actual result?
- Horizontal bar is appearing within the accordion

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/105905051-fc523300-5fef-11eb-85b9-081ecd7fc0c4.png)
![image](https://user-images.githubusercontent.com/28455973/105905969-1d675380-5ff1-11eb-99e9-e889175a2812.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Fixed due to Redesign. Closing ticket.
