### ISSUE TITLE
Spanish Translation Workflow Issue for Multimedia (Video, Infographic & File)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#3023]
### Issue description
When trying to create a translation of an English video, English infographic or English file, you're not able to save the Spanish translation; you get an invalid transition status error. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Create an English video or English infographic. You can either save the English item. in review or go ahead and publish it. The end outcome is the same regardless of whether the English media item is published or in draft/review.
2. Translate the media item you created in step 1. Update all fields, including site section and YouTube link, to Spanish translations. 
3. Try to save and you'll get the an invalid transition status error

### What's the expected result?
- You should be able to translate the media item and save it without an error. 

### What's the actual result?
- You aren't able to save the translated media item. You have to create a new, independent Spanish media item. The result is the English and Spanish aren't related and there is no language toggle.

### Additional details / screenshot
- Likely a bug that was reintroduced from the Drupal upgrade last year. 
   - We upgraded Drupal toward the end of September 2020. The last Spanish video was added into Drupal 8/14/2020 and the last Spanish infographic was from June 2020. 

### Related Tickets
* I believe this is related to #1310

### Updated Acceptance Criteria
``` gherkin
Scenario: Translate infographic from English to Spanish
Given the user is logged in as an editor
When the user creates a new infographic content item
  And the infographic is created in English
  And the infographic has all of the required fields set in English
Then the user is able to save the infographic content item in English
  And the user is able to push the content item through the workflow to Published
When the user creates a Spanish translation of the infographic
  And the infographic has all of the required fields set in Spanish
Then the user is able to save the infographic content item in Spanish
  And no error displays upon saving
  And the user is able to push the content item through the workflow to Published

Scenario: Language toggle works for translated infographics
Given the user is viewing a page for an English infographic
  And the infographic has a Spanish translation
Then the page displays the language toggle
  And clicking on the language toggle takes the user to infographic page in Spanish
```

``` gherkin
Scenario: Translate video from English to Spanish
Given the user is logged in as an editor
When the user creates a new video content item
  And the video is created in English
  And the video has all of the required fields set in English
Then the user is able to save the video content item in English
  And the user is able to push the content item through the workflow to Published
When the user creates a Spanish translation of the video
  And the video has all of the required fields set in Spanish
Then the user is able to save the video content item in Spanish
  And no error displays upon saving
  And the user is able to push the content item through the workflow to Published

Scenario: Language toggle works for translated videos
Given the user is viewing a page for an English video
  And the video has a Spanish translation
Then the page displays the language toggle
  And clicking on the language toggle takes the user to video page in Spanish
```

``` gherkin
Scenario: Translate file from English to Spanish
Given the user is logged in as an editor
When the user creates a new file content item
  And the file is created in English
  And the file has all of the required fields set in English
Then the user is able to save the file content item in English
  And the user is able to push the content item through the workflow to Published
When the user creates a Spanish translation of the file
  And the file has all of the required fields set in Spanish
Then the user is able to save the file content item in Spanish
  And no error displays upon saving
  And the user is able to push the content item through the workflow to Published

Scenario: Language toggle works for translated files
Given the user is viewing a page for an English file
  And the file has a Spanish translation
Then the page displays the language toggle
  And clicking on the language toggle takes the user to file page in Spanish
```

**Comment by alinai** [comment]
@santwuma , Should we see language toggle for Files? The file gets downloaded on clicking the created file. We can see the respective page by opening the downloaded file. Is the language toggle requirement for file is for any special type of file?

**Comment by alinai** [comment]
@santwuma , @laurelthrash , @KateMashkinaNIH, Verified that we are able to translate the media item (file, infographic and video) and save it without an error on the ODE. Also verified that the "Language Toggle" appears on both the English and Spanish Infographic and Video landing pages on the ODE.
Since File does not have its own landing page, it is not possible to test "Language toggle" for a file. Verified that the Spanish translation for File appears in the Related Resources of a Spanish translation of an Article and on the List item of a Spanish translation of Mini Landing page. 
Please confirm if the above test for files is good enough for verifying the "Language toggle".
