### ISSUE TITLE
CTS App Module is not use CDE Config for API URL

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3041]
### Issue description
It is defaulting to its the app module's default, which is ctsproxy.cancer.gov. 

> **ESTIMATE** TBD

### Steps to reproduce the issue
N/A - CTS is broken on acsf-test 

### What's the expected result?
- To not be broken

**Comment by sarinapadilla** [comment]
The CTS app is now passing `"ctsApiEndpointV2": window.CDEConfig.ctsConfig.apiServer` instead of hardcoding in the app.
