### ISSUE TITLE
Borderless Card Spacing is incorrect on DEV ACSF for AP

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3051]
### Issue description
While testing out the changes for the borderless card on ACSF, there is a distinct change to the spacing around the borderless card now on AP and NCA50.  The card on ACSF should look like it does on Prod.

What it looks like on PROD:
![image](https://user-images.githubusercontent.com/31222859/117319695-8ca6dc00-ae59-11eb-8fcd-168ca7750a52.png)

What it looks like on ACSF:
![image](https://user-images.githubusercontent.com/31222859/117319739-97617100-ae59-11eb-90c3-c4526769c69f.png)

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www-dev-acsf.cancer.gov/research/annual-plan and look at the first borderless card at the top of the screen
2. See how the spacing around the card is different from https://www.cancer.gov/research/annual-plan

### What's the expected result?
- Card display should match on Prod and ACSF

### What's the actual result?
- ACSF's borderless card is missing the spacing around the card/

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This is corrected in #3052

**Comment by sarinapadilla** [comment]
Apparently this has been fixed, also we don't support borderless cards anymore due to redesign.
