### ISSUE TITLE
The text of the parent page becomes white when clicked 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3056]
### Issue description

 At desktop, when I am on a child page and click the parent page, the text of the Parent page becomes white. The text color of the parent should be Capri,#2A72A5

### Steps to reproduce the issue

1.  Go to https://ncigovcdode411.prod.acquia-sites.com/about-cancer/coping/feelings/relaxation
2. Click the parent text link "Feelings and Cancer" from the left nav
3. See that the Parent text color for "Feelings and Cancer" becomes white.

### What's the expected result?
-The text color of the parent should be Capri,#2A72A5 on clicking and always.

### What's the actual result?
- The Parent text color for "Feelings and Cancer" becomes white.

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/118015688-8ebdde80-b322-11eb-869f-d506538d6b7f.png)

CC: @bennettcc

**Comment by alinai** [comment]
Feelings and Cancer text becomes invisible on clicking it in the left nav. If we click "Feelings and Cancer" in the left nav fast, then we see that the text link blinks. @acsnedegar , can you please check for me?

![image](https://user-images.githubusercontent.com/28455973/119407699-97af9800-bcb2-11eb-91a8-bccb802b8614.png)

**Comment by acsnedegar** [comment]
@alinai Yes - I am seeing that blink as well on click.
