### ISSUE TITLE
Enlarge button text is blue on hover.

### ISSUE THREAD

**Issue by acsnedegar** [NCIOCPL/cgov-digital-platform#3058]
### Issue description
*For all breakpoints, the enlarge button on hover text "Enlarge" changes from white to blueberry. It should stay white so it is still legible on hover.*

### Steps to reproduce the issue

1. Go to https://ncigovcdode411.prod.acquia-sites.com/test/lead-img-crops   
2. Hover over Enlarge button on image corner
3. See that the "Enlarge" changes to dark blue

### What's the expected result?
- "Enlarge" should be #FFFFFF

### What's the actual result?
- "Enlarge" changes with background hover color

### Additional details / screenshot

![Screen Shot 2021-05-12 at 1 46 04 PM](https://user-images.githubusercontent.com/79338977/118020730-6fc24b00-b328-11eb-88ce-dd9a97449e36.png)

Cc @bennettcc

**Comment by alinai** [comment]
Looks good to me on Chrome, FF, Edge and IE. @acsnedegar , can you please confirm?

**Comment by acsnedegar** [comment]
@alinai - looks good on safari too
