### ISSUE TITLE
Common Display Elements - Page Options

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#306]
This story is to create the common display element - Page Options.

Page Options will include the ability to Print, Email, Share on Facebook, Share on Twitter, Share on Pinterest, and Resize Font.

Resize Font should appear on Articles, Blog Posts, Cancer Center, Biographies, Press Releases, Events, and Forms, but not appear on Home/landing pages and App modules.

**Comment by BrendanBeltzNIH** [comment]
The description of this is a bit backwards. Page options is a piece that needed to be ported in full, but it's functionality on different content types is a story for the creation of those content types attending templates.
