### ISSUE TITLE
The dimensions of the first image on two pages are different on dev-acsf

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3071]
### Issue description

There is a difference in dimensions of the first image on dev-acsf. When Inspecting the first image I am also noticing wrapping of text on the left side of the image appearing differently and there is slight difference in the position of the "Read More" button as well.

> **ESTIMATE** TBD

### Steps to reproduce the issue  /news-events/nca50

1.  Go to https://www-dev-acsf.cancer.gov/news-events/nca50
2. Inspect the first image
3. See that image dimension is appearing as 259x259 but on Prod the image dimension is 265x265.
4. Go to https://www-dev-acsf.cancer.gov/research/annual-plan
5. Inspect the first image
6. See that image dimension is appearing as 259x259 but on Prod the image dimension is 265x265.

### What's the expected result?
- The dimension of the first image should be unchanged (265X265)

### What's the actual result?
- The dimension of the first image is appearing as 259X259

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/119718057-1e8c7e00-be35-11eb-9288-a137928daa51.png)

![image](https://user-images.githubusercontent.com/28455973/119718148-35cb6b80-be35-11eb-9125-f3ea532d76ac.png)

### Related Tickets
* Issue #9999
* Issue #9999

cc: @bennettcc

**Comment by alinai** [comment]
> @alinai - I'm unable to verify this issue. I went to the two NCA50 pages in different tabs of the same browser instance, right-clicked on the first Capitol Building image on each, and selected "View Image." Both pages are using the same image name. Next, I saved the two images and did a binary compare. It came back identical.
> 
> I did notice that flipping between the two tabs, the image "jumps" slightly, but that's not what's being reported here.

@blairlearn , please inspect the image and hover over the image source as shown in the screen-shot. The image and the "Read More" button jumps slightly and the 4th line wraps at "us" on acsf whereas on Prod 4th line wraps at "Join".

**Comment by blairlearn** [comment]
@alinai -- Got it.  You're saying the image is _styled_ at a different size on DEV vs.Prod.
I read that as the physical image was sized differently.

**Comment by alinai** [comment]
We noticed that some extra space got introduced in the h2 title for borderless card. We noticed the same issue on dev-ac. Then we checked Annual plan and nca50 and found the same issue with the first h2 title on Annual Plan and nca50. 
![image](https://user-images.githubusercontent.com/28455973/121607745-90142100-ca1e-11eb-8680-32e8bdbbd5b3.png)

**Comment by andyvanavery31** [comment]
Closing due to not being able to replicate this issue after updates to these pages.
