### ISSUE TITLE
The OpenGraph Image Metatag Generation can Break Under Certain Circumstances

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3083]
### Issue description
If a node's `field_image_promotional` or `field_image_article` referencing an image that has been deleted in the system, metatag generation for token `'[cgov_tokens:cgov-og-image]'` breaks. The underlying code does not guard against the possibility that the referenced image may not exist.

This issue is closely tied to #839. If #839 is resolved before this ticket, the steps to reproduce will be much harder.

> **ESTIMATE** TBD

### Steps to reproduce the issue
1.  Create a cgov_image and publish it.
2. Create a cgov_article and reference the cgov_image in the field_image_promotional. Publish the article.
3. Delete the cgov_image.
4. Try and view the article. It should error out.

### What's the expected result?
When viewing the node, the og:image metatag does not exist, and the page still displays without error.

### What's the actual result?
The page displays an error.

### Additional details / screenshot
(This was from www-cms.cancer.gov when it occurred, so this may be a error page generated by ACSF)
![image](https://user-images.githubusercontent.com/11215649/121043649-d0f00980-c782-11eb-8605-f0bef2d9b77d.png)

The log at the time was
```
...snip...
php-error web-3323 #3 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('cgov_metatag_to...', Array)
php-error web-3323 #2 [internal function]: cgov_metatag_tokens('cgov_tokens', Array, Array, Array, Object(Drupal\Core\Render\BubbleableMetadata))
php-error web-3323 #1 /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc(62): get_meta_og_image_token(Array)
php-error web-3323 [04-Jun-2021 17:25:56 America/New_York] Error: Call to a member function get() on null in /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc on line 157 #0 /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc(131): get_social_image_path_from_media(NULL)
```

### Related Tickets
* Issue #839 - the reason content owners can trigger this issue.

**Comment by alinai** [comment]
On test-acsf, the og:image metatag continues showing in the content when the image is deleted. This does not happen on dev-ac.

**Comment by alinai** [comment]
For the og:image metatag issue, when I clear my cache and the first time I delete an image and check the article (e.g. Spanish article) where it was used, I don't see the og:image metatag.  The second time when I delete another image and check the article (e.g. English article) where it was used, I see the og:image metatag in both regular browser and incognito browser.
