### ISSUE TITLE
Intermittent Memory Failure on Prod

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3085]
### Issue description

This issue was originally occurring after a stage from a higher tier to a lower one. Now it is occurring intermittently on production. So it is no longer a staging issue. All the questions below still apply. The steps to reproduce are still iffy because we don't know what is causing the issues with the tags.

This appears to be happening in the `AkamaiTagPurger` code, called during the `purge_processor_lateruntime` code's LateRuntimeProcessor subscriber. This occurs sometime during the page load process.

This has just started, so it raises many questions, specifically about why now, but also is this a "ticking" time-bomb for future deployments/cache clears.

#### Some Questions:
1. Should we only use cron?
    * this would mean more time after save to see items. Full cache clear may take a while.
2. Should we limit the number of items to be processed?
    * Should limit the items being loaded in memory. Is there a way to 3. set this for cron/drush separately from web traffic?
4. What the heck is in there?
     * Does a backup from prod contain items it cannot deal with and that is why it is getting tripped on this specific restore?
5. Why now?
     * is there something else in the code that is now taking up the memory that was once there for Akamai?
6. Should we kill off paragraphs as cache items to limit the tags processed?
    * This should limit the tags to be cleared by purge?

> **ESTIMATE** TBD

### Steps to work around the issue
1. Clear cache
2. Hit the origin server root  — error
3. Hit a different path on the origin (e.g. /about-nci) — success
4. Return to origin — success

Hitting refresh on step 4 sometimes works, sometimes fails. (Possibly due to load balancers?)

### Additional details / screenshot
```
Stack trace
E_ERROR: Allowed memory size of 268435456 bytes exhausted (tried to allocate 47560101 bytes)
in PDOStatement::execute called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Database/Statement.php (59)
in Drupal\Core\Database\Statement::execute called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Database/Connection.php (640)
in Drupal\Core\Database\Connection::query called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php (357)
in Drupal\Core\Database\Driver\mysql\Connection::query called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Database/Query/Update.php (148)
in Drupal\Core\Database\Query\Update::execute called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Database/Query/Merge.php (395)
in Drupal\Core\Database\Query\Merge::execute called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/KeyValueStore/DatabaseStorage.php (116)
in Drupal\Core\KeyValueStore\DatabaseStorage::set called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/State/State.php (84)
in Drupal\Core\State\State::set called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/StatusStorage.php (89)
in Drupal\akamai\StatusStorage::saveStatuses called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/StatusStorage.php (79)
in Drupal\akamai\StatusStorage::save called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/StatusStorage.php (64)
in Drupal\akamai\StatusStorage::saveResponseStatus called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/Plugin/Client/AkamaiClientV3.php (89)
in Drupal\akamai\Plugin\Client\AkamaiClientV3::purgeRequest called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/AkamaiClientBase.php (294)
in Drupal\akamai\AkamaiClientBase::purgeTags called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/akamai/src/Plugin/Purge/Purger/AkamaiTagPurger.php (141)
in Drupal\akamai\Plugin\Purge\Purger\AkamaiTagPurger::invalidate called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/purge/src/Plugin/Purge/Purger/PurgersService.php (487)
in Drupal\purge\Plugin\Purge\Purger\PurgersService::invalidate called at /mnt/www/html/ncigov01dev/docroot/modules/contrib/purge/modules/purge_processor_lateruntime/src/EventSubscriber/LateRuntimeProcessor.php (84)
in Drupal\purge_processor_lateruntime\EventSubscriber\LateRuntimeProcessor::onKernelFinishRequest called at ? (?)
in call_user_func called at /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php (111)
in Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher::dispatch called at /mnt/www/html/ncigov01dev/vendor/symfony/http-kernel/HttpKernel.php (209)
in Symfony\Component\HttpKernel\HttpKernel::finishRequest called at /mnt/www/html/ncigov01dev/vendor/symfony/http-kernel/HttpKernel.php (193)
in Symfony\Component\HttpKernel\HttpKernel::filterResponse called at /mnt/www/html/ncigov01dev/vendor/symfony/http-kernel/HttpKernel.php (173)
```

### Related Tickets
NONE

**Comment by blairlearn** [comment]
This occurred after the development tier was staged from production.  A new release (v1.2.9) was deployed to development and cache cleared using the site factory user interface.

Because we don't backup the lower tiers, we can't examine the database from before the error occurred.

The current hypothesis however is that there were a "large" number of cache tags in the queue to be purged from Akamai.  The purge module is limited to processing no more than 100 items at a time.  We believe the purge module loads the entire list, trims off 100, and then update the list.  The update is what fails.

We should investigate what exactly gets stored in the queue. Should we reduce what we're putting in?  e.g. It's not possible to update a paragraph without updating the page it's on. Are we storing a cache-tag for each paragraph on a page instead of limiting it to a tag for the page itself?

**Comment by bryanpizzillo** [comment]
Ok, some more details here. The Akamai module stores the response information, which includes cache_tags purged, purgeId, supportId, and a few other bits of info. Think of this as the "purge log". It stores this in the Drupal `state` key value store. FYI, this is not an appropriate type of thing to store in state...
(For those wondering, the Drupal State is store in the DB table `key_value`, with a collection column ===``state`` -- but it is too big to select AND there are more than one...)

I dumped out the Purge Log from prod `~/bin/www-drush.sh sget --format=json akamai.purge_status > /tmp/akamai_state.json`. The resulting file is 38MB, so pretty large for simple state of one thing. 

I did notice 2 things:
1. The log seems to go back to 9/2020, so IDK how it trims it up, why it is only Sept, or what.
1. The current dev branch no longer saves the result status, or at least the storage class that is trying to do the save is no longer in the code base. A quick trace to https://git.drupalcode.org/project/akamai/-/blob/8.x-3.x/src/Plugin/Purge/Purger/AkamaiTagPurger.php#L141 seems to indicate it never does logging of the IDs anymore. (IDK if throwing away the supportId/purgeId is a good thing.)

One more TODO is to analyze what exactly is in state and see what is taking up space. There could be other modules adding to this issue, it is just the Akamai module is the one that gets called a lot the time.

In the meantime, a quick fix was to just delete the `akamai.purge_status` state.

**Comment by bryanpizzillo** [comment]
Additional notes:
1. This was actually causing nightly backups to fail.
2. This was also affecting DCEG. 4 DB backups failed, cleared out 36MB from the state, backup succeeded.

Dump of additional state values
+-------------------------------------------+---------------+
| name                                      | length(value) |
+-------------------------------------------+---------------+
| acquia_connector.identifier               |            19 |
| acquia_connector.key                      |            40 |
| acquia_spi_data.new_optional_data         |             4 |
| acquia_subscription_data                  |           871 |
| acquia_subscription_data.timestamp        |            13 |
| acsf_site_scrubbed                        |            15 |
| akamai.purge_status                       |         58289 |
| akamai.valid_credentials                  |             4 |
| drupal_css_cache_files                    |         10951 |
| install_task                              |            11 |
| install_time                              |            13 |
| locale.translation.formulae               |            89 |
| locale.translation.javascript             |            66 |
| locale.translation_last_checked           |            13 |
| purge_purger_measurement_8813de186f       |            22 |
| purge_queue_number_of_items               |             4 |
| purge_queue_total_failed                  |             9 |
| purge_queue_total_succeeded               |            10 |
| router.path_roots                         |           986 |
| routing.menu_masks.router                 |           593 |
| routing.non_admin_routes                  |          6042 |
| simple_sitemap.last_cron_generate         |            13 |
| simple_sitemap.queue_items_initial_amount |             7 |
| simple_sitemap.queue_stashed_results      |       2860794 |
| system.cron_key                           |            40 |
| system.cron_last                          |            13 |
| system.css_js_query_string                |            13 |
| system.javascript_parsed                  |          6586 |
| system.js_cache_files                     |         11569 |
| system.maintenance_mode                   |             4 |
| system.private_key                        |            82 |
| system.profile.files                      |          1570 |
| system.theme.files                        |           527 |
| twig_extension_hash_prefix                |           130 |
| views.view_route_names                    |          1090 |
+-------------------------------------------+---------------+
