### ISSUE TITLE
The feature cards under Recommended From NCI section on blog posts looks bad on IE

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3086]
### Issue description

The Feature Cards in the Recommended From NCI section in blog posts looks weird on IE. https://www.cancer.gov/news-events/cancer-currents-blog/2021/cervical-cancer-minimally-invasive-surgery-declining

The content and image breaks the containers for feature posts.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to  https://www.cancer.gov/news-events/cancer-currents-blog/2021/cervical-cancer-minimally-invasive-surgery-declining
2. Scroll all the way down to the "Recommended from NCI" section
3. See how the feature cards appears

### What's the expected result?
- The feature cards should appear with all images and content within the feature card

### What's the actual result?
- The contents and images are showing outside the feature card

### Additional details / screenshot
-
![image](https://user-images.githubusercontent.com/28455973/121085823-563de300-c7b0-11eb-8d25-1232e3e6d5be.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
We don't support IE anymore, so closing this ticket!
