### ISSUE TITLE
H2s (body section headers) in accordions have wrong spacing

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/cgov-digital-platform#3091]
### Issue description
On mobile, the heading Why People with Cancer Receive Radiation Therapy has too much spacing in the accordion. On desktop, the OTP link for Why People with Cancer Receive Radiation Therapy doesn't work. There is too much spacing below body section headers throughout site on desktop.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/types/radiation-therapy on mobile. See spacing of accordion on Why People with Cancer Receive Radiation Therapy heading.
2. Go to https://www.cancer.gov/about-cancer/treatment/types/radiation-therapy on desktop
3. The OTP link Why People with Cancer Receive Radiation Therapy doesn't skip to that section
4. See too much spacing below H2s that are body section headers. This is also on microsites: https://dceg.cancer.gov/fellowship-training/fellowship-experience/advantages

### What's the expected result?
- Less spacing below h2 than above it

### What's the actual result?
- Too much spacing below H2

### Additional details / screenshot
<img width="487" alt="Screen Shot 2021-06-14 at 3 06 15 PM" src="https://user-images.githubusercontent.com/4921685/121964543-b3e6a800-cd39-11eb-978b-eee18504880a.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Issue has been resolved.
