### ISSUE TITLE
Add Hero Banner to Home/Landing Page

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#310]
This story is to add hero banner to the home/landing page content type. See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#hero-image for field definition and link to Paragraph definition.

Image hero banner components are (see comment with attachments below):
* Image
  * Two images are provided for the image banner:
     * Desktop image (1025 breakpoint and above)
     * Tablet image (displays once we are at the 1024 breakpoint)
  * The "hero" image does not display on mobile.
* Text Overlay
  * On desktop, this overlays the image as white text
  * On Tablet, this displays at the bottom of the image as white text in a dark gray overlay

**Comment by lburack** [comment]
Attached are Cgov's homepage image banner (desktop and tablet) and Cgov's News & Events image banner (desktop and tablet)

![hero_image_home_desktop](https://user-images.githubusercontent.com/29731392/53134052-8ad7f300-3543-11e9-8780-3bdd0d2c762e.jpg)
![hero_image_home_tablet](https://user-images.githubusercontent.com/29731392/53134053-8ad7f300-3543-11e9-9e0b-442cfd64ecfd.jpg)
![hero_image_news_desktop](https://user-images.githubusercontent.com/29731392/53134054-8ad7f300-3543-11e9-968c-f50899cc0a74.jpg)
![hero_image_news_tablet](https://user-images.githubusercontent.com/29731392/53134055-8ad7f300-3543-11e9-950e-6bac932eddc1.jpg)
