### ISSUE TITLE
CSS not correctly updating after saving and publishing an app module

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3100]
### Issue description
When updating and saving an application module page, the CSS file associated with that application module does not get properly updated. It should not be required to have to clear the Drupal and Akamai caches in order to use the new CSS file if the application module is updated and pushed through the workflow.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Update existing app module with new config (appCssUri, appJsUri)
2. Push it through the workflow
3. View the app module page

### What's the expected result?
- The new CSS should be pulled in by the app module

### What's the actual result?
- The cached version of the file is pulled, or nothing is pulled at all if the previous version of the app module did not have a config (was empty, like Disease/Intervention DLPs)

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by jfrank-nih** [comment]
Old issue and has not been seen in a while. Going to close out. We can re-open if needed.
