### ISSUE TITLE
Improve cGovTools tests (from #124/#126)

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#311]
Improve tests in CgovToolsTest.php:

- Make a Unit test with mocked objects instead of a Kernel test for `addContentTypePermissions()`
- Refactor to use loops instead of long strings of commands / more modular
- Add additional tests for various combinations:
  - addContentTypePermissions(invalid_type);
  - addContentTypePermissions(type, nonexistent_role);
  - addContentTypePermissions(type, nonexistent_role, nonexistent_permission);
  - addContentTypePermissions(type, string); 
  - addContentTypePermissions(type, array); 
  - addContentTypePermissions(type, string, string); 
  - addContentTypePermissions(type, array, string);
  - addContentTypePermissions(type, array, array);
  - addContentTypePermissions(type, null, string);

- Add test inside `addContentTypePermissions()` to verify permission being added actually exists

**Comment by VictoriaSunNIH** [comment]
At this point in time we need a larger test strategy, and have some regression tests in place.
