### ISSUE TITLE
Utility Bar - www. Demo Assets 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#313]
This story is to create the common display element - Utility Bar for the www. demo.

Demo Assets to be added to ticket.

**Comment by amydugan** [comment]
Closing demo asset tickets, as JIRA tickets have been entered for designers to provide the assets. https://tracker.nci.nih.gov/browse/CGOV-8687 Is the www demo asset ticket. The assets will be attached to the dev ticket once provided.
