### ISSUE TITLE
RPGs Funding Mechanisms Chart

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#3130]
Hi @erikscottmeyer - Please update the chart on this page with the attached data. It includes the actual dollar amounts rather than just the percentages. https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg#ui-id-2.

[rpg-funding-paylines-fy20 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/6786269/rpg-funding-paylines-fy20.1.xlsx)

**Comment by blairlearn** [comment]
This is being handled as part of #3044
