### ISSUE TITLE
Highcharts Map - Grant and Contract Awards by State and Institution

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#3131]
Please update the data for the Highcharts map on this page: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards with the data attached.

[awards-by-country-fy20 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/6786420/awards-by-country-fy20.1.xlsx)

[awards-by-state-and-institution-fy20 (1).xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/6786419/awards-by-state-and-institution-fy20.1.xlsx)

**Comment by blairlearn** [comment]
This is being handled as part of #3044
