### ISSUE TITLE
Spike: Investigate BLT's `validate.acsf` setting.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3143]
## In order to determine whether the BLT `validate.acsf` setting is useful to us, a developer  needs to investigate what the setting does.

> **Estimated Timeframe** *half day for completion* 

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

### Expected Deliverables:
Recommendation for whether we should actively manage it or leave it as something BLT and/or Acquia's systems take care of.

### Additional Notes:
In the process of reviewing PR #3139 (Fix for #2927 - add deprecation checks), it was discovered that BLT's underlying `ValidateAllCommand` code includes validation for ACSF.  It appears to default to `false`, although we likely don't  want to turn it on for local dev and ACE, it does lead to the question of whether we should actively set it to true for our ACSF environments.

And that depends on what it does.

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpizzillo** [comment]
@blairlearn  We should keep it. It runs `drush --include=docroot/modules/contrib/acsf/acsf_init acsf-init-verify` and it was what told me that I needed to update my files after `composer update`. This update is what fixes our issue with the db-scrubbing and staging new sites from prod that have never had cache tables created. So the double check was pretty useful in this case.

Closing this issue
