### ISSUE TITLE
NCI-Connect| NCIConnect delighter is hiding under the main menu

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform#3172]
### Issue description
NCI Connect delighter is hiding under the main menu from 640 to 1024 pixels. 
https://www.cancer.gov/rare-brain-spine-tumor/tumors

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/31008800/134226953-0469b8dc-e1aa-4560-9c8a-f18f40653eaf.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bennettcc** [comment]
Closing this ticket - it is no longer needed as the Delighter has been removed with the MVP1 release
