### ISSUE TITLE
Technical Item: Create unit test(s) for the "streamlined" HTML editor.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#319]
Unit tests are needed for the "Streamlined" editor configuration.

For now, the test should confirm that the configuration is available to each of these roles:

* advanced_editor
* content_author
* content_editor
* layout_manager 

Related to #207 and #201.

**Comment by VictoriaSunNIH** [comment]
At this point in time we need a larger test strategy, and have some regression tests in place.
