### ISSUE TITLE
Arch: Define Layout Builder Approach

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#32]
Question to Answer:
1. How will we support workflow?
2. How will we handle translations?
3. How can we control what is allowed in the "regions"
4. How to we even define the layouts?
5. How do those layout definitions get packaged with a theme?
6. How do we control LB for the content area, but lock down C-Clamp items? (e.g. Banner, Footer, etc)
7. How can we define and discuss layouts for different types? (What will the entire (e.g. IAs) team need to know to speak intelligently about and define requirements for?
8. What other questions have not been asked here?

The Deliverable will be the final approach documented at https://github.com/bryanpizzillo/cgov-digital-platform/wiki/Drupal-Design-Layout-Builder.

**Comment by adriancofie** [comment]
I do believe this one can be closed out.
