### ISSUE TITLE
Output Page Metadata - DTM Analytics 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#321]
This story is to output DTM Analytics metadata on cancer.gov

Links to information from DTM from original implementation on cancer.gov:
https://collaborate.nci.nih.gov/pages/viewpage.action?spaceKey=OCECTBWIKI&title=WCMS+Requirements+Traceability+Matrix
https://tracker.nci.nih.gov/browse/OCEPROJECT-4578

**Comment by nicolecrom** [comment]
Adding in Dion's document on tags for DTM
[tags-for-dtm.docx](https://github.com/NCIOCPL/cgov-digital-platform/files/2746517/tags-for-dtm.docx)

He lists the following caveats
* I have no idea what the nav/folder structure is, so when I say “folder” or “navon”, it’s referring to the equivalent of the Percussion navons.
* These requirements assume that the custom analytics variables can be set or overridden at the navon level, same as our current functionality.
* I’ve left out requirements for the CTS results pageload values for now – I’m thinking it would be better to pull the needed values from the URL or create an appmodule-specific data element. Again, I don’t know anything about how appmodule pages or CTS will function; I’ll need to talk to someone on the dev team so that we can avoid redundant code.

**Comment by daquinohd** [comment]
- [ ] html lang
- [ ] og:title
- [ ] og:url
- [ ] dcterms.coverage
- [ ] dcterms.subject
- [ ] dcterms.type
- [ ] dcterms.issued
- [ ] dcterms.isPartOf
- [ ] da_interactionSelector
- [ ] audience

**Comment by daquinohd** [comment]
*TODO:*

- [ ] Add suite rules within DTM (number of needed suites has been reduced greatly, and Joe will help manage this in the Adobe DTM UI. 
- [ ]
