### ISSUE TITLE
Accordion clearfix css is not properly scoped on CTHP pages

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#3218]
On CTHP there is a clearfix rule that is not properly namespaced which causes a glaringly obvious issue when viewing the cancer type homepages while logged in, using the admin ui in drupal 9.

<img width="1065" alt="Screen Shot 2021-10-15 at 2 35 59 PM" src="https://user-images.githubusercontent.com/45469809/137536351-3062220f-db18-4bc0-b250-2d9879f57f3b.png">

**Comment by bryanpizzillo** [comment]
Oops this was also closed in #3209
