### ISSUE TITLE
Story: Update Cancer Information Summary content type with SVPC field

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3231]
## As the system, I want to render a Cancer Information Summary content items with an "SVPC" field, so that user can view whether a cancer information summary is an SVPC document or not.

We need to update Drupal to reflect the inclusion of an “SVPC" field on CDR cancer information summary documents.

Tasks: update schema for incoming CDR cancer information summaries, update pdq_cancer_information_summary UI

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: Content editor can see “SVPC” field on the Liver Cancer Treatment content item in Drupal CMS
Given the user is logged into the CMS as an editor
  And the incoming Liver Cancer Treatment CDR document has the "SVPC" field selected
  And this CDR document has been successfully processed into the CMS
When the user edits the Liver Cancer Treatment pdq_cancer_information_summary content item
Then the system displays the “SVPC” field as a checkbox
  And the system displays the “SVPC” field as selected
```

```gherkin
Scenario: Content editor can see “SVPC” field on the <insert non-SVPC cancer information summary here> content item in Drupal CMS
Given the user is logged into the CMS as an editor
  And the incoming <non-SVPC cancer information summary> CDR document has the "SVPC" field unselected
  And this CDR document has been successfully processed into the CMS
When the user edits the <non-SVPC cancer information summary> pdq_cancer_information_summary content item
Then the system displays the “SVPC” field as a checkbox
  And the system displays the “SVPC” field as unselected
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bkline** [comment]
> When the user views/edits the Liver Cancer Treatment pdq_cancer_information_summary content item

I would have assumed that the flag would appear on the editing form, but not on the rendered page for viewing the summary. The wording above seems to imply that it should appear on both. Is that right?

**Comment by sarinapadilla** [comment]
@bkline, that line should just say "edit" as it is just when you are viewing the edit UI in Drupal. I'll fix this wording to clarify!

**Comment by bkline** [comment]
Installed on https://ncigovcdode444.prod.acquia-sites.com/
