### ISSUE TITLE
Spike: Determine Test Strategy/Approach for working with 2 Drupal Themes

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3235]
## In order to implement a new theme for NCIDS and still support the existing `cgov_common` theme, the testers need a way to test both themes on a single ODE.

* Given that there will now be one site that is using this, we're putting this on hold as it will be easier to review.

> **Estimate** *# point* 

The most likely approach is to use Drupal/BLT's multisite configuration to support a path-based domain microsite. So in this case 2 sites would be installed:
- ncigovcdodeXXX.prod.acquia-sites.com -- this is the new NCIDS transitional theme
- ncigovcdodeXXX.prod.acquia-sites.com/microsite -- this would be a site with the existing `cgov_common` theme.

I would think that there is still only 1 profile, and it is just www.cancer.gov that will use the new one. So each install of the "www site" will be to install the existing profile, then switch out the theme. (IDK if there are BLT multisite settings to define the site AND what profile/theme should be installed.)

### Some Expected Challenges:
1. Speed: Installing 2 sites means a new code deployment will be 2 times slower.
2. Testing: We will need 2 times the acceptance test runs.
    * What about Drupal unit tests. 
3. Path of Least Resistance: How do we make this process such that devs will test both versions. 

### Expected Deliverables:
* A working prototype that:
   * Works locally
   * Works on an ODE/ACE
   * Works on ACSF
      * by works here, I mean does not confuse ACSF in any way. For example, if you break sites.php, ACSF will not work.  
* A set of tickets to implement to make this happen (if possible)

### Additional Notes:
* https://support.acquia.com/hc/en-us/articles/360053713173-How-to-Setup-Multisite-on-ACE-with-Acquia-BLT-with-optional-Pipelines-and-Config-Split-
* https://docs.acquia.com/blt/tech-architect/multisite/
* https://docs.acquia.com/site-factory/manage/domains/path/

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by sarinapadilla** [comment]
As we are implementing NCIDS on cgov and microsites (not DCEG Connect), we don't need this ticket.
