### ISSUE TITLE
Spike: Determine the Changes that Need to be Made to Layouts

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3240]
## In order to build out the NCIDS grid with the NVCG grid, developer needs to identify what the new page/node templates need to be.
> **Estimate** *# point* 

NCIDS spacing is based on the NCIDS grid. The current site uses our modified Foundation grid system (NVCG). For all the elements in the heading and footer section, this is easy enough to retrofit. The question is, how do we mix and match elements built to the NCIDS grid with elements in the modified Foundation grid. Examples of this issue will be:
* NCIDS breadcrumbs + NCIDS Page Options (where they appear above and below, and only show the 2 options available - see #3256 )
* NCDS Side Nav + NVCG Body Column

### Expected Deliverables:
* A List of the `page.html.twig`, `node--*--full.html.twig` and `media--*--full.html.twig` templates that must be modified.
* A prototype/roadmap of what changes need to be made documented onto ticket #3241.

### Additional Notes:
* One of the biggest issues will be with pathing as there are many NVCG elements that require very specific ancestors in order to display correctly.
* #3349 defines a rough approach to handling NCIDS and Legacy CSS. 

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*
Diff https://github.com/arcepaul/cgov-digital-platform/compare/v1.3.8...ncids_trans

templates/layout/html.html.twig:
- [ ] replace skipnav with `.usa-skipnav` 

templates/layout/html--cgov-application-page.html.twig:
- [ ] replace skipnav with `.usa-skipnav` 

`{{ drupal_block('page_options') }}` - not sure if we are removing all instances, since page options will now be inline with breadcrumbs, or if we need to update `templates/block/page_options/block--page-options.html.twig` with new variant:
- [ ] templates/content/article/node--cgov-article--full.html.twig
- [ ] templates/media/video/media--cgov-video--full.html.twig
- [ ] templates/media/infographic/media--cgov-infographic--full.html.twig
- [ ] templates/content/pdq/node--pdq-drug-information-summary--full.html.twig
- [ ] templates/content/pdq/node--pdq-cancer-information-summary--full.html.twig
- [ ] templates/content/mini_landing/node--cgov-mini-landing--full.html.twig
- [ ] templates/content/home_landing/node--cgov-home-landing--full.html.twig
- [ ] templates/content/event/node--cgov-event--full.html.twig
- [ ] templates/content/blog/node--cgov-blog-series--full.html.twig
- [ ] templates/app_module/r4r/app-module--cgov-r4r-app.html.twig

Create:
- [ ] templates/block/ncids/block--cgov-breadcrumb.html.twig
- [ ] block--ncids-banner.html.twig
- [ ] block--ncids-header.html.twig
- [ ] block--ncids-sidenav.html.twig

Remove:
- [ ] templates/block/page_options/block--cgov-common-languagebar.html.twig (replacement is in ncids banner)
- [ ] templates/block/section_nav/block--cgov-section-nav.html.twig (replacement is ncids-sidenav)

These pages need the same treatment:
- [ ] templates/layout/page.html.twig
- [ ] templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig
- [ ] templates/content/blog/page--cgov-blog-post.html.twig
- [ ] templates/content/blog/page--cgov-blog-series.html.twig
- [ ] templates/content/cthp/page--cgov-cthp.html.twig
- [ ] templates/content/home_landing/page--cgov-home-landing.html.twig
- [ ] templates/content/home_landing/page--cgov-home-landing--dceg-connect.html.twig
- [ ] templates/content/home_landing/page--cgov-home-landing--special-report.html.twig
- [ ] templates/page/page--404-en.html.twig
- [ ] templates/page/page--404-es.html.twig

List for above:
- Add `.legacy` class to appropriate container, usually a direct parent of `.contentzone` or a WYSIWYG, see [#3349](https://github.com/NCIOCPL/cgov-digital-platform/issues/3349)
-  Replace and/or delete
    -  page.site_banner
    -  page.language_bar
    -  page.utility_bar
    -  page.mobile_nav
    -  page.main_nav
    -  page.search_bar
    -  page.breadcrumb
    -  page.footer
    -  page.notification_banner
    -  page.section_nav
- Remove `tabindex="0", see https://github.com/NCIOCPL/cgov-digital-platform/issues/3295
- Replace <div role="main" id="main"> with <main id="main-content">
- Remove foundation: `.row` `.flex-columns` `.medium-9` `.columns` `.large-12` `.large-6` `.medium-10` `.gutter`  (to name a few). Everything has a uswds equivalent 

More foundation:
- do we remove foundation totally or as we update existing templates?
- [ ] block-content--cgov-image-carousel--full.html.twig 
    - .row -> .grid row
    - note: check for custom css on row, carousels are messy
- [ ] block-content--cgov-video-carousel--full.html.twig 
    - .row -> .grid-row
    - columns small-12 -> col-grid-12 (or mobile-lg:col-grid-12)
    - note: col-grid-12 is just full width. is uswds built so we can remove row and col 12?
- [ ] templates/listing/paragraph--cgov-list.html.twig
    - medium-10 columns > tablet:grid-col-10
- [ ] templates/field/recommended_content/field--field-recommended-content.html.twig
    - row -> grid-row
    - .flex-columns -> remove, grid-row uses flex
    - note: were are items in foreach? those will need to be updated too
- [ ] templates/content/mini_landing/field--paragraph--cgov-two-item-feature-row.html.twig
    - .row -> .grid-row
    - .flex-columns remove
    - .large-6 .columns -> .desktop:grid-col-6
 - [ ] templates/content/home_landing/paragraph--cgov-title-first-feature-card-ro.html.twig
     - row -> grid row
     - medium-10 columns -> tablet:grid-col-10
     -  flex-columns rmeove
     - align-center
 - [ ] templates/content/home_landing/paragraph--cgov-secondary-feature-row.html.twig
     - [ ] row -> grid-row
     - [ ] flex-columns remove
 - [ ] templates/content/home_landing/paragraph--cgov-primary-feature-row.html.twig
     - [ ] row -> grid-row
     - [ ] felx-columns?
 - [ ] templates/content/home_landing/paragraph--cgov-multimedia-row.html.twig
     - [ ] row -> grid-row
     - [ ] flex-columns remove
 - [ ] paragraph--cgov-multimedia-row.html.twig
     - [ ] large-12 columns -> desktop:grid-col-12 (x2)
     - [ ] grid -> grid row
 - [ ] paragraph--cgov-guide-row.html.twig
     - [ ] ...repeating
 - [ ] paragraph--cgov-column-two.html.twig
    - [ ] ... 
    - [ ] gutter should be replaced with grid-gap on row, but there are custom styles for gutter
 - [ ] paragraph--cgov-column-one.html.twig
     - [ ] ...
 - [ ] node--cgov-home-landing--full.html.twig
     - [ ] ...
 - [ ] field--paragraph--field_guide_cards.html.twig
     - [ ] ...
 - [ ] field--paragraph--field-row-cards.html.twig
    - [ ] ...
 - [ ] field--paragraph--field-container-heading--cgov-primary-feature-row.html.twig
     - [ ] ...
 - [ ] templates/content/cthp/field--field-cthp-cards.html.twig
     - [ ] ...
 - [ ] asdf
- TODO and probably forever ongoing

### Outstanding tickets:
- [ ] Header https://github.com/NCIOCPL/ncids/issues/205
- [ ] `usa-prose` https://github.com/NCIOCPL/ncids/issues/412
- [ ] Page options https://github.com/NCIOCPL/cgov-digital-platform/issues/3256
- [ ] `nci-megamenu` https://github.com/NCIOCPL/ncids/issues/436
- [ ] Remove `tabindex=0` https://github.com/NCIOCPL/cgov-digital-platform/issues/3295#issuecomment-1099236212
- [ ] Mixins task added to cgov
- [ ] dart-sass task added to cgov
- [ ] create new transitional theme
- [ ]  Add `.legacy` styles to `Common.scss`

**Comment by meglake** [comment]
Noting for future reference:
* Print styles will be same as current Cancer.gov (Tickets: https://github.com/NCIOCPL/ncids/issues/440 and https://github.com/NCIOCPL/ncids/issues/441)
* Need to add to home and landing page requirements ticket (when created) that we want to change only background (in body container only) on home and landing pages to new color: #f0f0f0

**Comment by VictoriaSunNIH** [comment]
The investigation is complete, we will need to break down #3241 into all of the work needed to support this.
