### ISSUE TITLE
[META] Update Page & Node Templates to Reflect NCIDS Layout

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3241]
# Update Page & Node Templates to Reflect NCIDS Layout
> **ESTIMATE** TBD

 #3240 determined this

The mixing of NCIDS and Legacy CSS was validated and documented in #3349. Use that as guidance for setting up the CSS.

### Prerequisites
- [x] #3240

### Tickets in this Epic
- [x] #3237 
- [x] #3375 
- [x] #3379 
- [x] #3380 
- [x] #3381 
- [x] #3383 
- [x] #3384 
- [x] #3385 
- [x] #3386 
- [x] #3387

**Comment by VictoriaSunNIH** [comment]
We'll break down this ticket in Sprint 29, so that we can write up work for Sprint 30. @meglake , @sarinapadilla , @olitharp-nci - I'll schedule some time!
