### ISSUE TITLE
Spike: Prototype removing Sticky Nav

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3245]
## In order to for our team to feel more comfortable with removing the sticky nav ahead of the rest of the updates, developer needs to work on a prototype that does not have sticky nav.
> **Estimate** *# point* 

The new NCIDS will no longer make the navigation "sticky", as such the implementation of the NCIDS navigation on WWW will need to disable the Sticky Nav and any related logic.

The Sticky Nav is a very complicated bit of code that also affects many other features of the site given how it breaks deep linking. There are many elements within the site that must also detect the scroll position to ensure they do not "crash" into the sticky nav. (The nav is taller on an upward scroll than it is when scrolling downward) 

It will be easier to manage the new NCDS Transitional Theme and the current theme side by side with the sticky nav removed. This is because the new transitional theme will be a lightweight copy of the current theme in which we will just be referencing the current JS & CSS for most of the features. At the point we remove the sticky nav, and if the current site still uses it, we will have to duplicate all the JS & CSS that references or handles sticky nav offsets into the transitional theme. At this point we will have to maintain two sets of these files. Examples of code that "know" about the sticky nav are Deep Linking, however there are probably many more styles that account for the spacing.

We have been requested to prepare a prototype of the existing site so we can see what the site would look like without the sticky  nav, as well as be able to demo it to other microsite owners. The idea being that the sticky nav will be removed from all sites when they are updated, so can we just accelerate this removal to reduce maintenance costs.

### Expected Deliverables:
* A working prototype to demo.

**Comment by bryanpizzillo** [comment]
## Testing Scenarios
These scenarios are documenting what currently happens on production, not what makes sense or what "works", but the state of things now. These links are based on "ODE" content. For the purposes of this scenario, "top of the window" means right below the sticky nav on current codebase and the top of the window on the prototype.

### Enter top-level section URL directly
#### Desktop
1. Open a browser and enter `/types/breast/patient/breast-treatment-pdq#_185`
    * This is the "Treatment Option Overview" section 
**Result:** You should be taken to the "Treatment Option Overview" section and it should be at the top of the window.

#### Mobile
1. Open a browser and enter `/types/breast/patient/breast-treatment-pdq#_185`
    * This is the "Treatment Option Overview" section 
**Result:** You should be taken to the "Treatment Option Overview" heading in the accordion, with the contents collapsed.

### Enter deep section URL directly
#### Desktop
1. Open a browser and enter `/types/breast/patient/breast-treatment-pdq#_136`
    * This is the "Breast cancer is sometimes caused by inherited gene mutations (changes)." section 
**Result:** You should be taken to the "Breast cancer is sometimes caused by inherited gene mutations (changes)." section and it should be at the top of the window.

#### Mobile
This actually has 2 behaviors. (Well it does in Chrome)
1. Open a browser and enter `/types/breast/patient/breast-treatment-pdq#_136`
    * This is the "Breast cancer is sometimes caused by inherited gene mutations (changes)." section 
**Result:** The "General Information About Breast Cancer" accordion section should open and "Breast cancer is sometimes caused by inherited gene mutations (changes)." should be at the top of the window.

1. Open a browser and enter `/types/breast/patient/breast-treatment-pdq#_136`
2. Scroll to the bottom of the page
3. Hit enter in the URL line (or re-enter the full URL)
**Result:** The browser shows the footer and does not scroll to the section; however if you scroll up, you will see that the "General Information About Breast Cancer" section is opened.

### Maintain scroll position on back button (when viewing top level section)
#### Desktop
1. Go to https://www.cancer.gov/types/breast/patient/breast-treatment-pdq
2. Click the "General Information About Breast Cancer" link in the ON THIS PAGE section
3. Scroll to the subsection titled "Breast cancer is sometimes caused by inherited gene mutations (changes)."
4. Click the Generics of Breast and Gynecologic Cancers" link
5. Click the browser back button
**Result:** You should be around the same area of the page as you were before. (i.e. you should NOT be at the top of General Information About Breast Cancer)

#### Mobile
1. Go to https://www.cancer.gov/types/breast/patient/breast-treatment-pdq
2. Expand the "General Information About Breast Cancer" section in the accordion
3. Scroll to the subsection titled "Breast cancer is sometimes caused by inherited gene mutations (changes)."
4. Click the Generics of Breast and Gynecologic Cancers" link
5. Click the browser back button
**Result:** The entire document is collapsed into an accordion without any sections expanded

### Resize from Desktop -> Mobile when in a top-level section
1. Go to https://www.cancer.gov/types/breast/patient/breast-treatment-pdq
2. Click the "General Information About Breast Cancer" link in the ON THIS PAGE section
3. Scroll to the subsection titled "Breast cancer is sometimes caused by inherited gene mutations (changes)."
4. Shrink browser to mobile breakpoint
**Result:** The entire document is collapsed into an accordion without any sections expanded

**Comment by bryanpizzillo** [comment]
## Investigation Notes:
1. Removing Sticky Nav
    1. Remove the `headroom.js` package
    2. Remove the `/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/headroom/headroom-patch.js`
    
1. Fix Deep Link Patch (`docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/deepLinkPatch/deepLinkPatch.js`) 
    * References headroom element to adjust spacing. This spacing just needs to be 0.
    * Exists to handle two functions:
       1. Adjusting the scroll position based on a stick nav. <-- This is no longer needed without a sticky nav.
       2. Expanding an accordion section and scrolling to deep sections on mobile. <-- This IS still needed.
    * `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/deepLinkPatch/jquery.nci.scroll_to.js` is only used by the deep link patch. This should be refactored out and NOT be a jQuery plugin.
    * I think the best approach is to NOT do any deep linking whoo-hah on non-mobile breakpoints. In fact this should probably get moved to the accordion code if possible. (After making the accordion then scroll to the right position.)
3. Bad Code Finds. In some cases it looks like since we "enable" default browser functionality new code is getting hit that breaks. (It does not break on prod...)
     1. `/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/accordion/index.js` is a duplicate and should be removed. (This cause some wasted time in debugging the accordion code)
     2. Global variable declared in [nci-analytics-functions](https://github.com/nciocpl/cgov-digital-platform/blob/f61597b269a744234033c86f437d0898357df6ae/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js#L1890).  Actually it has no visibility set, so it is not even a var. Chrome choked on this.
     3.

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - I have tested this on the ODE https://ncigovcdode448.prod.acquia-sites.com/ for ALL BROWSERS (Chrome, Firefox, Edge, IE).  I found some discrepancies between what is expected and what I actually saw happening, but in all cases, what I actually saw happening should be fine, and does not need to be fixed.  Leaving a detailed comment on everything observed in case we need to retest/evaluate any of these.  Thanks!

### Enter top-level section URL directly
Desktop works as described. 
Mobile - the heading is not collapsed, but is expanded to the section (which I think is fine, but different than what you wrote in the expected results) on all browsers

### Enter deep section URL directly
Desktop works as described.
Mobile - Scenario 1 works as described. Scenario 2 - same as above, the heading was not collapsed, I was brought to the right section in Chrome (but this is fine, just different from what was described in expected results)

### Enter deep section URL directly, but have scrolled
Desktop: Works on all browsers, except IE.  In IE, I was brought back to the section (and not kept where i was on the page). I don't think this is an issue but just noting it.
Mobile: Re-entering the section would just bring me back to the initial section that was open

### Maintain scroll position on back button (when viewing top level section)
Desktop: Works on all browsers.
Mobile: The entire document was collapsed into accordions as expected, and led me to the footer on edge and firefox.  On Chrome, it brought me back to where i had previously scrolled.

### Maintain scroll position on back button (when viewing sub section)
Desktop: Works as expected.
Mobile: This returned me to the correct scroll position, and not the footer as indicated in expected results.

### Resize from Desktop to Mobile
Desktop and Mobile resizing worked as expected.

**Comment by bryanpizzillo** [comment]
Closing this ticket as the research has been done.
