### ISSUE TITLE
Enabler: Update node and npm versions

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3253]
# Update the frontend build to use a supported version of NodeJS and NPM

Update the frontend build in the Acquia build pipeline and local development environment to use Node v14.18.1 and npm v8.1.4.

The versions we are currently using are no longer in support.

> **ESTIMATE** TBD

### Notes

- Pipelines: `scripts/pipelines/setup_env`
- Dockerfile: `docker/web/Dockerfile`

**Comment by bryanpizzillo** [comment]
Note: there is an issue with v16 that will not build node-sass no matter what version of npm. The errors say it is missing python2, but this appears to be an artifact of a really old node-sass package.
