### ISSUE TITLE
Infographic overlaps footer when embedded on Home and Landing page

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform#3254]
### Issue description
*Description of the issue*
It was found that when embedding an infographic into a content block on home and landing it's getting outside of the main page container onto the footer ( see screenshot attached)
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Add
<img width="970" alt="Screen Shot 2021-11-19 at 4 29 19 PM" src="https://user-images.githubusercontent.com/67657582/142694165-17018c16-69ee-4fcd-a2c4-7e437db00aea.png">
itional details / screenshot

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Footer has been updated with Redesign. Closing this ticket.
