### ISSUE TITLE
Do Not Generate and Display "In This Section" on Cancer Information Summary content

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3260]
### Issue description
Currently, "In This Section" content is generated automatically on pdq_cancer_information_summary content items. We would like to remove the generation and display of "In This Section" content on pdq_cancer_information_summary content items, since this will now be done in the XSLT.

> **ESTIMATE** TBD

### What's the expected change?
- "In This Section" content is not generated and displayed on pdq_cancer_information_summary content items
### What's the current functionality?
- All pdq_cancer_information_summary content items have "In This Section" content generated and displayed automatically.

### What's the updated acceptance criteria?
Desktop:
```gherkin
Scenario: User views the Patient Cervical Cancer Treatment content item without In This Section content on CGov on desktop
Given the Patient Cervical Cancer Treatment pdq_cancer_information_summary content item exists in the CMS
  And the content item has the “SVPC” field selected
When a user views the Patient Cervical Cancer Treatment page on CGov at the desktop breakpoint
Then “In This Section” in the "Treatment Options By Stage" section does not display on the CGov page
  And there is no list of anchor links to the H3s in the "Treatment Options By Stage" section displayed
```

``` gherkin
Scenario: User views the HP Cervical Cancer Treatment content item displaying In This Section content on CGov on desktop
Given the HP Cervical Cancer Treatment pdq_cancer_information_summary content item exists in the CMS
  And the content item does not have the “SVPC” field selected
When a user views the HP Cervical Cancer Treatment page on CGov at the desktop breakpoint
Then “In This Section” in the "General Information About Cervical Cancer" section displays on the CGov page
  And there is a list of anchor links to the H3s in the "General Information About Cervical Cancer" section listed under "In This Section"
```

Tablet:
```gherkin
Scenario: User views the Patient Cervical Cancer Treatment content item without In This Section content on CGov on tablet
Given the Patient Cervical Cancer Treatment pdq_cancer_information_summary content item exists in the CMS
  And the content item has the “SVPC” field selected
When a user views the Patient Cervical Cancer Treatment page on CGov at the tablet breakpoint
Then “In This Section” in the "Treatment Options By Stage" section does not display on the CGov page
  And there is no list of anchor links to the H3s in the "Treatment Options By Stage" section display
```

``` gherkin
Scenario: User views the HP Cervical Cancer Treatment content item displaying In This Section content on CGov on tablet
Given the HP Cervical Cancer Treatment pdq_cancer_information_summary content item exists in the CMS
  And the content item does not have the “SVPC” field selected
When a user views the HP Cervical Cancer Treatment page on CGov at the tablet breakpoint
Then “In This Section” in the "General Information About Cervical Cancer" section displays on the CGov page
  And there is a list of anchor links to the H3s in the "General Information About Cervical Cancer" section listed under "In This Section"
```

Mobile:
"In This Section" content does not display on mobile, so there will be no change in Acceptance Criteria at this breakpoint.

#### Publish Preview
```gherkin
Scenario: User views the Patient Cervical Cancer Treatment content item without In This Section content on CGov in CDR Publish Preview
Given the Patient Cervical Cancer Treatment content item exists in the CDR
  And the content item has the “SVPC” field selected
When a user views the Patient Cervical Cancer Treatment content item in CDR Publish Preview
Then “In This Section” in the "Treatment Options By Stage" section does not display
  And there is no list of anchor links to the H3s in the "Treatment Options By Stage" section display
```

``` gherkin
Scenario: User views the HP Cervical Cancer Treatment content item displaying In This Section content on CGov on desktop
Given the HP Cervical Cancer Treatment content item exists in the CDR
  And the content item does not have the “SVPC” field selected
When a user views the HP Cervical Cancer Treatment content item in CDR Publish Preview
Then “In This Section” in the "General Information About Cervical Cancer" section displays
  And there is a list of anchor links to the H3s in the "General Information About Cervical Cancer" section listed under "In This Section"
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bkline** [comment]
Just a heads-up that there's a bug in the [current code](https://github.com/NCIOCPL/cgov-digital-platform/blob/db258e067dc385cde1c1232f3dfd5569fab0ecbb/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/entrypoints/pdq/PDQ.js#L39) which adds a spurious `role=` class to the top-level `nav` element for the "In This Section" and suppresses the `role` attribute which should be set to "navigation" but isn't. I point this out because my rewrite will eliminate this bug, causing the spurious class to disappear and the `role` attribute to come back into existence, possibly re-enabling behaviors and/or styling which had been been broken, with possibly unintended or undesirable consequences. @sarinapadilla will be reaching out to folks who may be more familiar with the affected code for help in identifying any components which might have been controlled by the presence of the `role` attribute (it's theoretically possible, but extremely unlikely, that anything would be dependent on the bogus `role=` class), in order to assist testers in knowing where to look for such changes in behavior or appearance.

**Comment by bkline** [comment]
The corresponding ticket for generating the _In This Section_ block further upstream, before the HTML is pushed to the CMS, is https://tracker.nci.nih.gov/browse/OCECDR-5079.

**Comment by bkline** [comment]
The new code for OCECDR-5079 has been implemented and tested as much as is possible without the work for this ticket, but the new OCECDDR-5079 code can't be enabled until the JavaScript code is removed (otherwise, we'll have duplicate _In This Section_ blocks).
