### ISSUE TITLE
Enabler: Update Drupal to 9.4.0

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3267]
# Update Drupal to 9.4.0
> **ESTIMATE** TBD

This needs to be started by April 2022 as 9.4.0 will be out June 2022. However the sooner the better. This **may** end up having a connection to updating BLT if they add 9.3.0 as a required dependency. (#3187) **IF IT IS NOT** a dependency that I strongly urge this to be handled by itself.

**Comment by blairlearn** [comment]
Renaming the ticket to say 9.4.0 since it's out and there are already important notes on this one.

**Comment by blairlearn** [comment]
Dependency Packages updated

cweagans/composer-patches (1.7.1 => 1.7.2)
drupal/core-composer-scaffold (9.2.16 => 9.2.21)
acquia/acsf-tools (dev-9.x-dev 0a2b871 => dev-9.x-dev 496a145)
zumba/amplitude-php (1.0.2 => 1.0.5)
symfony/polyfill-php72 (v1.25.0 => v1.26.0)
symfony/polyfill-php73 (v1.25.0 => v1.26.0)
symfony/polyfill-php81 (v1.25.0 => v1.26.0)
symfony/filesystem (v4.4.39 => v4.4.42)
symfony/config (v4.4.37 => v4.4.42)
grasmash/yaml-cli (2.0.1 => 2.0.2)
symfony/finder (v4.4.37 => v4.4.41)
guzzlehttp/guzzle (6.5.5 => 6.5.7)
enlightn/security-checker (v1.9.0 => v1.10.0)
webmozart/assert (1.10.0 => 1.11.0)
nikic/php-parser (v4.13.2 => v4.14.0)
psy/psysh (v0.10.9 => v0.11.7)
consolidation/site-alias (3.1.1 => 3.1.5)
consolidation/site-process (4.1.0 => 4.2.0)
consolidation/output-formatters (4.1.2 => 4.2.2)
consolidation/log (2.0.2 => 2.1.1)
consolidation/annotated-command (4.4.0 => 4.5.6)
drush/drush (10.3.6 => 10.6.1)
drupal/core (9.2.16 => 9.2.21)
acquia/drupal-environment-detector (v1.4.0 => 1.4.1)
drupal/acsf (2.69.0 => 2.72.0)
drupal/acsf_variables (2.69.0 => 2.72.0)
drupal/acsf_theme (2.69.0 => 2.72.0)
drupal/acsf_duplication (2.69.0 => 2.72.0)
behat/behat (v3.10.0 => v3.11.0)
symfony/dom-crawler (v4.4.39 => v4.4.42)
drupal/drupal-driver (v2.1.1 => v2.2.0)
instaclick/php-webdriver (1.4.10 => 1.4.14)
behat/mink-selenium2-driver (dev-master 3c3da51 => dev-master 5d15043)
drupal/drupal-extension (v4.1.0 => v4.2.1)
textalk/websocket (1.5.7 => 1.5.8)
acquia/blt-behat (v1.1.1 => v1.3.0)
symfony/phpunit-bridge (v5.4.3 => v5.4.10)
symfony/lock (v4.4.38 => v4.4.40)
sebastian/environment (5.1.3 => 5.1.4)
phpdocumentor/type-resolver (1.6.0 => 1.6.1)
phpunit/phpunit (9.5.19 => 9.5.21)
justinrainbow/json-schema (5.2.11 => 5.2.12)
squizlabs/php_codesniffer (3.6.2 => 3.7.1)
phpstan/phpdoc-parser (1.2.0 => 1.6.4)
slevomat/coding-standard (7.0.19 => 7.2.1)
drupal/coder (8.3.14 => 8.3.15): Checking out 0cfad3a21f from cache
seld/jsonlint (1.8.3 => 1.9.0)
composer/xdebug-handler (2.0.5 => 3.0.3)
composer/spdx-licenses (1.5.6 => 1.5.7)
composer/ca-bundle (1.3.1 => 1.3.2)
composer/composer (2.2.9 => 2.2.16)
drupal/core-dev (9.2.16 => 9.2.21)
acquia/coding-standards (v0.7.0 => v1.0.0)
simplesamlphp/simplesamlphp (v1.18.8 => v1.18.9)
simplesamlphp/simplesamlphp-module-sqlauth (v0.9.3 => v0.9.4)
simplesamlphp/simplesamlphp-module-smartattributes (v0.9.1 => v0.9.2)
simplesamlphp/simplesamlphp-module-radius (v0.9.3 => v0.9.4)
simplesamlphp/simplesamlphp-module-preprodwarning (v0.9.2 => v0.9.3)
simplesamlphp/simplesamlphp-module-ldap (v0.9.12 => v0.9.17)
simplesamlphp/simplesamlphp-module-negotiate (v0.9.11 => v0.9.12)
simplesamlphp/simplesamlphp-module-metarefresh (v0.9.6 => v0.9.7)
simplesamlphp/simplesamlphp-module-memcachemonitor (v0.9.2 => v0.9.3)
simplesamlphp/simplesamlphp-module-expirycheck (v0.9.3 => v0.9.4)
simplesamlphp/simplesamlphp-module-consent (v0.9.7 => v0.9.8)
simplesamlphp/simplesamlphp-module-consentadmin (v0.9.1 => v0.9.2)
simplesamlphp/simplesamlphp-module-cdc (v0.9.1 => v0.9.2)
simplesamlphp/simplesamlphp-module-authyubikey (v0.9.1 => v0.9.3)
simplesamlphp/simplesamlphp-module-authx509 (v0.9.8 => v0.9.9)
simplesamlphp/simplesamlphp-module-authtwitter (v0.9.1 => v0.9.3)
simplesamlphp/simplesamlphp-module-authorize (v0.9.3 => v0.9.4)
simplesamlphp/simplesamlphp-module-authcrypt (v0.9.3 => v0.9.4)
simplesamlphp/simplesamlphp-module-adfs (v0.9.8 => v0.9.9)
simplesamlphp/saml2 (v4.2.4 => v4.6.3)
phpmailer/phpmailer (v6.5.1 => v6.6.3)
gettext/languages (2.8.1 => 2.9.0)
gettext/gettext (v4.8.5 => v4.8.6)
dflydev/placeholder-resolver (v1.0.2 => v1.0.3)
doctrine/cache (1.12.1 => 1.13.0)
commerceguys/addressing (v1.2.1 => v1.3.0)
drupal/address (1.9.0 => 1.10.0)
drupal/admin_toolbar (3.0.3 => 3.1.0)
monolog/monolog (1.26.1 => 1.27.1)
league/climate (3.7.0 => 3.8.2)
drupal/console (1.9.7 => 1.9.8)
drupal/core-recommended (9.2.16 => 9.2.21)
drupal/devel (4.1.1 => 4.1.5)
drupal/entity_browser (2.6.0 => 2.7.0)
drupal/embed (1.4.0 => 1.5.0)
drupal/crop (2.1.0 => 2.2.0)
fileeye/mimemap (1.2.0 => 1.2.2)
drupal/sophron (1.1.0 => 1.2.0)
phenx/php-font-lib (0.5.2 => 0.5.4)
lsolesen/pel (0.9.10 => 0.9.12)
drupal/file_mdm (2.1.0 => 2.4.0)
drupal/imagemagick (3.2.0 => 3.3.0)
drupal/token (1.9.0 => 1.10.0)
drupal/metatag (1.16.0 => 1.19.0)
drupal/migrate_file (2.0.0 => 2.1.1)
drupal/migrate_plus (5.1.0 => 5.3.0)
drupal/migrate_tools (5.0.0 => 5.1.0)
drupal/moderation_sidebar (1.4.0 => 1.5.0)
drupal/ctools (3.7.0 => 3.8.0)
drupal/paragraphs (1.12.0 => 1.14.0)
drupal/pathauto (1.8.0 => 1.10.0)
drupal/redirect (1.6.0 => 1.7.0)
drupal/role_delegation (1.1.0 => 1.2.0)
drupal/shield (1.4.0 => 1.6.0)
drupal/simple_sitemap (3.10.0 => 3.11.0)
drupal/token_filter (1.3.0 => 1.4.0)
phpstan/phpstan (0.12.99 => 1.8.0)
phpstan/phpstan-deprecation-rules (0.12.6 => 1.0.0)
nette/neon (v3.2.2 => v3.3.3)
mglaman/phpstan-drupal (0.12.15 => 1.1.21)
mglaman/drupal-check (1.1.10 => 1.4.0)
vlucas/phpdotenv (v2.6.8 => v2.6.9)

**Comment by blairlearn** [comment]
Update attempts so far:

## Update `drupal/core` and all other packages.
- `drupal/core` 9.4.0
- All dependent packages
- Update `drupal/akamai` to v4.0.1
- Fix up `features:packages:list` mismatches (a new `image_loading` property on some fields).
- Clean up repository list (#3409)
- Fix tests broken by the upgrade (#3134)

Problems encountered:
- Site administrators lose all roles upon login.
- The site homepage breaks overnight, this seems to be related to the watchdog log entries:
  - `Trying to get property 'value' of non-object in cgov_list_paragraph_view() (line 110 of /mnt/www/html/ncigov01dev/docroot/profiles/custom/cgov_site/modules/custom/cgov_list/cgov_list.module)`
  - `Field field_raw_html is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /mnt/www/html/ncigov01dev/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php)`

## Update only `drupal/core`
- `drupal/core` 9.4.0
- Fix up `features:packages:list` mismatches
- Clean up repository list (#3409)
- Fix tests broken by the upgrade (#3134)

Used `wget --mirror -e robots=off` to simulate traffic.

Cannot duplicate errors on locally nor on acsf dev.

## Update only dependent packages (not `drupal/core')
- PR #3440 

Additional tests now break.
  - pdq_drug_information_summary/tests/src/Functional/ApiTest.php
  - pdq_glossifier/tests/src/Functional/ApiTest.php
  - docroot/profiles/custom/cgov_site/tests/src/Functional/CgovSiteTest.php
  - docroot/profiles/custom/cgov_site/tests/src/Functional/PdqNodeTypeTest.php

Used `wget --mirror -e robots=off` to simulate traffic.

Cannot duplicate errors on locally nor on acsf dev.

## Update to `drupal/core` 9.4.2
- PR #3416 
- Fix up `features:packages:list` mismatches
- Clean up repository list (#3409)
- Fix tests broken by the upgrade (#3134)
- Disable the additional tests broken tests noted for the "dependency only" attempt.

Used `wget --mirror -e robots=off` to simulate traffic.

Cannot duplicate errors on locally nor on acsf dev.
