### ISSUE TITLE
Allow custom NCI_averageCost Highchart to override calculated numbers

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3284]
### Issue description
As part of the 2020 Factbook update (#3044) there was a request to override the calculated numbers (sums, averages) displayed by High Charts in certain instances. This can be needed when the formula to arrive at the actual calculation is more complicated than a simple arithmetic function.

Example fiddle of override functionality: https://jsfiddle.net/jefrank/yzsq1tjv/9/

> **ESTIMATE** 4-8 hours

### What's the expected change?
- [ ] Modify the underlying chart data to contain advanced data points with a tooltip override where needed:

`data: [2088352, 2075295, 1924803, 1939623, 2019308, 2068869, 2195184, 2366530, 2456156, 2677206]`

to 

`data: [2088352, 2075295, 1924803, 1939623, 2019308, 2068869, 2195184, 2366530, 2456156, {y: 2677206, overrideAverage: 514]`

- [ ] Possibly fix line [553](https://github.com/NCIOCPL/cgov-digital-platform/blob/fd322d882aac1d357c20e04665a3576caf425f42/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js#L553) if it can't handle the advanced data points
- [ ] Override the tooltip in the chart file to use a formatter function to display the same data:

```
tooltip: {
    formatter: function() {
      var s = '<b>' + this.x + '</b>';

      for (let i = 0; i < this.points.length; i++) {
        point = this.points[i]
        var labelText = (!point.point.labelNum ? point.y : point.point.labelNum)
        s += '<br/>' + point.series.name + ': ' +
          labelText + 'm';
      }

      return s;
    },
    //pointFormat: "{point.labelNum}",
    shared: true
  },
```
- [ ] Alternatively, re-do the [default tooltip](https://github.com/NCIOCPL/cgov-digital-platform/blob/fd322d882aac1d357c20e04665a3576caf425f42/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/Chart.js#L584) code per above to allow advanced data points with a specific custom field without having to override the tooltip in each file
- [ ] Potentially expand the other `nci_*` chart types to also allow label overrides on any calculated data

### What's the current functionality?
- Highcharts displays calculated numbers in labels for NCI custom charts
- There is no way to override the numbers visible because they are calculated in the custom chart and tooltips are created there

### Related Issues
- Caused by #3044

**Comment by laurelthrash** [comment]
After discussions with our internal Factbook team, we decided to close this issue for the time being. We will open a new ticket in the event this issue comes up again during this year's Factbook (FY22 data) or a future year. Cc: @santwuma
