### ISSUE TITLE
Blogs get horizontal scroll bar on Chrome, FF, Edge at mobile break point

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3286]
### Issue description

Blogs get horizontal scroll bar on Chrome, FF, Edge at mobile break point

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://www.cancer.gov/news-events/cancer-currents-blog/2022/mrna-vaccines-to-treat-cancer at mobile break point
2. A horizontal scroll bar appears at the bottom of the page
3. The image and image caption can not be seen without scrolling the horizontal scroll bar.

### What's the expected result?
- The horizontal scroll bar should not appear at the bottom of the page.
- The image and image caption and all contents of the page should fit the screen at mobile break point.

### What's the actual result?
- The horizontal scroll bar appears at the bottom of the page.
- The image and image caption does not fit the screen at mobile break point and we have to scroll the horizontal scroll bar to view the full image and full image caption.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/150848371-16fc45be-9a9d-4072-8c8d-93d638f9f40a.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Outdated due to redesign.
