### ISSUE TITLE
Change Request: Update Browser Title

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3299]
### Issue description
Update the browser title to reduce the character count that is taken up be " - NCI". 

> **ESTIMATE** TBD

### What's the expected change?
Browser Title's across cancer.gov as well as all microsites have "- NCI" appended to them

### What's the current functionality?
Currently, our Browser Title is set at "[Browser Title] – National Cancer Institute"

With NCI written out and appended, this integral SEO real estate is already 50% full. National Cancer Institute is 23 characters, and Browser Titles should be around 55-60 characters max. If we shorten National Cancer Institute to NCI, this removes 20 characters, and allots for prime space for high value keywords.

### Tech Notes

- For pages on Cancer.gov, we should be updating `cgov_tokens:cgov-trans-org-name`
This seems to appear in `cgov_metatag/cgov_metatag.tokens.inc `and possibly the spanish translations file
- For react apps, this should be configurable for most through updating the app module config in Drupal. 
- CTS and R4R would be the exceptions, and would need to be updated separately. 

### What's the updated acceptance criteria?
```gherkin
When a user is viewing any page on cancer.gov 
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/espanol
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on dceg.cancer.gov
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/nano
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/pediatric-adult-rare-tumor/
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/rare-brain-spine-tumor/
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/rare-brain-spine-tumor/espanol
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on physics.cancer.gov/
  The browser title is "[Browser Title] - NCI"
```
```gherkin
When a user is viewing any page on cancer.gov/connect-prevention-study/
  The browser title is "[Browser Title] - NCI"
```

```gherkin
When a user is viewing any page within the Dictionary of Cancer Terms on cancer.gov 
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing any page within the Dictionary of Genetic Terms on cancer.gov 
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing any page within the Drug Dictionary on cancer.gov 
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing Dynamic List Page on cancer.gov (ex: cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/)
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing Manual List Page on cancer.gov (ex: cancer.gov/about-cancer/treatment/clinical-trials/covid-19)
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing search results page on cancer.gov (ex: cancer.gov/search/results)
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing any page within Clinical Trials Search (ex. any page with or below the URL: /about-cancer/treatment/clinical-trials/search). This will include the basic and advanced search pages, results page, trial description page, etc.)
  The browser title is appended with " - NCI"
```
```gherkin
When a user is viewing any page within R4R (ex. any page with or below the URL: /research/resources). This will include the search page, results page, resource page, etc.)
  The browser title is appended with " - NCI"
```
### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bryanpizzillo** [comment]
@ramu-nih This should just be updating https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_metatag/cgov_metatag.tokens.inc#L65 to be NCI instead of `National Cancer Institute`
