### ISSUE TITLE
Cancer Types Landing Page - YAML content

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#330]
This story is to create the YAML content for the Cancer Types Landing Page with an A-Z list.
[Example on current site](https://www.cancer.gov/types/) using the html markup from the front-end, and make sure that the code works with the new structure of the page.

**Comment by lburack** [comment]
I pulled the HTML from percussion into this yml file. @BrendanBeltzNIH - let me know if I need to do any cleanup or anything else. I also sent this, and a few other yml files, to Bryan earlier today.

[099_cancer_types.content.yml.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/2866975/099_cancer_types.content.yml.zip)

**Comment by BrendanBeltzNIH** [comment]
I think you need the markup to be indented under value: 
Also, you'll want to have a field_site_section__ES since that term exists in the yaml already.
It's hard to say for sure without running it through the loader, but that's what stands out to me as being possible changes.
