### ISSUE TITLE
Borderless card - h1 does not display mobile-display in the html and hide desktop-tablet-display at mobile breakpoint

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3308]
### Issue description

On https://www.cancer.gov/connect-prevention-study, , at mobile display we see desktop-tablet-display for h1 in the html instead of mobile-display. There are 2 h1 - for desktop and tablet first one should be displayed and other hidden, for mobile it should be the opposite 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/connect-prevention-study
2. Switch to the mobile breakpoint
3. Inspect the h1 (What is Connect?)
4. See that it displays desktop-tablet-display instead of mobile-display in the html.

### What's the expected result?
- There are 2 h1 - For **desktop and tablet** desktop-tablet-display should be displayed and mobile-display should be hidden. For **mobile**, mobile-display should be displayed and  desktop-tablet-display should be hidden.

### What's the actual result?
- For both **desktop and tablet**  and **mobile**, desktop-tablet-display is displayed.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/156603029-60542ef8-d7b2-4d29-95fa-e94b4daddcdf.png)

![image](https://user-images.githubusercontent.com/28455973/156603180-51db4913-f85a-49f3-90cb-be20ae6708f9.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Borderless cards are being removed. To close this ticket.
