### ISSUE TITLE
Add space above the blue navigation bar on SBIR's template for use cancer.gov

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3310]
Please add space (a container) above the blue bar for use on the SBIR homepage within the cancer.gov theme

This is to make room for the new blended logo that SBIR will use on their homepage

SBIR Homepage Comps: https://publicis.invisionapp.com/share/D512EWYA3GTE#/screens

**Comment by erikscottmeyer** [comment]
This is a manual configuration issue; add language toggle in site configuration

**Comment by acsnedegar** [comment]
This looks good and passes for me too. Thanks!

**Comment by sarinapadilla** [comment]
This is outdated due to redesign.
