### ISSUE TITLE
Update the full wide card within the cancer.gov template

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3311]
1) Change the Cool theme button color, background color, and text hoverstate for use within cancer.gov on full wdith borderless cards:

Accent button: #123E57
Button Hover: #1D567E
Background color: #2A72A5 (as is)
Text hoverstate color: stay white and get an underline

2) Change the Warm theme button color, background color, and text hoverstate for use within cancer.gov on full width borderless cards:

Accent button: #123E57
Button Hover: #1D567E
Background color: #FFFFFF
Text hoverstate color: #BB0E3D (red as is)

SBIR Homepage Comps: https://publicis.invisionapp.com/share/D512EWYA3GTE#/screens

**Comment by acsnedegar** [comment]
This passes for me, thanks!

**Comment by alinai** [comment]
Looks good to me on ODE 446. Thanks @erikscottmeyer and @acsnedegar!

**Comment by alinai** [comment]
Looks good to me

**Comment by alinai** [comment]
Looks good to me on dev-acsf.

**Comment by acsnedegar** [comment]
Also looks good to me there
