### ISSUE TITLE
Hide the delighter for sites that are not www-cancer

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3313]
Currently, the delighter appears automatically on new sites that are created. 

Please hide the delighter for sites that are not www.cancer (they will be added to other microsites as needed)

**Comment by acsnedegar** [comment]
Not seeing the delighter, this passes for me.

**Comment by bennettcc** [comment]
Closing this ticket - it is no longer needed as the Delighter has been removed with the MVP1 release
