### ISSUE TITLE
Create raw HTML block for information sessions

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3314]
Please create a raw HTML block to be used for information session on the SBIR custom homepage.  The addition/management of text and imagery should be done through this custom block (editable within the CMS)

SBIR Homepage: https://publicis.invisionapp.com/share/D512EWYA3GTE#/screens

**Comment by acsnedegar** [comment]
This looks good to me on dev-acsf and cms view
