### ISSUE TITLE
Spanish Grants Landing Page - YAML

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#332]
This story is to create the YAML content for the Spanish Grants Landing Page based on the raw HTML content that is currently in Percussion, and make sure it works with our new structure.
[Example on current site](https://www.cancer.gov/espanol/subvenciones-capacitacion)

**Comment by lburack** [comment]
Here's the .yml file I created. I sent this and a few other yml files over to @bryanpizzillo for cleanup and to add to the dev environment for testing.
[099_grants_training.content.yml.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/2866956/099_grants_training.content.yml.zip)
