### ISSUE TITLE
Unable to Crop Image within CMS

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3325]
Reported on 3/21 by a Physics CMS User: on 3/21:

User is unable to apply any crops to an image after uploaded to the image content type.  The crop dropdown is available, however the user is unable to click any portion of the image to set the desired crop.  Upon saving the image (without setting crops), the user receives the 'unable to save: crops required' error message.

Steps to reproduce:
1) Navigate to add image within CMS backend
2) Upload an image to the template
3) Attempt to set require crops
Note: There will no ability to select the image and apply the crop

This was reproduced within Physics the cancer.gov Prod CMS's

**Comment by blairlearn** [comment]
This appears to be a third-party dependency.  Loading the F12 tools, when you attempt to crop an image, an error is logged to the JavaScript console.

![image](https://user-images.githubusercontent.com/21063180/159367081-e5f90f19-0806-4da2-b603-132d1a2cb204.png)

Looking at the Network tab, there are two remote file references which timeout shortly after the error occurs:

* https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js
* https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css

**Comment by blairlearn** [comment]
Possibly related... we use the `drupal/image_widget_crop` package.  According to [package's page on Drupal.org](https://www.drupal.org/project/image_widget_crop), it has a dependency on the https://github.com/ fengyuanchen/cropper library (link deliberately broken).  That library is marked as deprecated and its repository archived.

**Comment by blairlearn** [comment]
It appears the NIH firewall is blocking the cropper library.
If you drop off VPN, the files load.
But if you drop off the VPN, attempts to edit content may be blocked.

![image](https://user-images.githubusercontent.com/21063180/159372427-eb0f9479-00c7-4cd4-9bc0-9a884dd37883.png)
