### ISSUE TITLE
CTHP Guide Card View More Info has Contrast Issues

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3326]
### Issue description
> **ESTIMATE** TBD

While investigating an issue with nested SASS and the View more information list, we discovered some other issues with the display. 

**Non-hovering Display**
<img width="569" alt="image" src="https://user-images.githubusercontent.com/11215649/159501547-8919e68c-deff-4e2e-983c-de18cef21d15.png">

**(BAD) Hovering over an External Link with exit disclaimer**
<img width="572" alt="image" src="https://user-images.githubusercontent.com/11215649/159501725-15fd48d3-a879-45a4-a98d-15976562e34c.png">

**Hovering over a file link text**
<img width="570" alt="image" src="https://user-images.githubusercontent.com/11215649/159502074-a9da516c-d50f-4601-9888-cc25aa9e9f54.png">

**(BAD) Hovering over a file link outside of link text**
<img width="574" alt="image" src="https://user-images.githubusercontent.com/11215649/159501907-bcd86fc4-6554-47f1-9076-9a25d080b0d9.png">

**Comment by alinai** [comment]
Exit Disclaimer icon looks different on dev-acsf. 

Hovering on External Link, we see that the Exit disclaimer turns grey. Same is happening for Video, Infographic. Screen-shot is attached. Are we expecting these fixes on dev-acsf at this point?

![image](https://user-images.githubusercontent.com/28455973/165180460-37e23919-87bf-49eb-84c2-76a2954852d7.png)

![image](https://user-images.githubusercontent.com/28455973/165180794-a0c45113-2893-4e6e-8fe0-88b45b5b8b9c.png)

![image](https://user-images.githubusercontent.com/28455973/165180934-3dca5820-40f0-424d-8ccc-5da3890bca76.png)

cc: @VictoriaSunNIH @SupriyaSaxena0605
