### ISSUE TITLE
Fact book Grant and Contract chart doesn't load

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3329]
### The US map on the "Grant and Contract Awards" page doesn't always load.

The map on the fact book "Grant and Contract Awards" page intermittently fails to load. If it fails to load, clicking refresh  will eventually allow it to succeed.  Attempting to pin to a prior version of the library (See PR #3319) makes no difference.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Browse to https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards

### What's the expected result?
- The map of "Grant and Contract Awards by State and Institution" should load.

### What's the actual result?
- The map will (intermittently) fail to display.  (Reproducing the issue may require refreshing the page.)

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/21063180/159948648-9d358ce0-c33f-461d-9a8e-07cc9b8bd48c.png)

**Comment by laurelthrash** [comment]
Note: The US map on the "Grant and Contract Awards" (reported in this ticket) is temporarily removed and replaced with a static chart per #3446. Thus, #3329 is dependent upon restoring the high chart from #3446.

**Comment by laurelthrash** [comment]
Presently, this high chart is being addressed in #3446. Added note to #3446, and closing this ticket.
