### ISSUE TITLE
Navigations Caches are not Cleared when a Landing Page is Archived

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3333]
### Issue description
> **ESTIMATE** TBD

Found this during testing of #3281. If you archive a landing page of site section, that change will not be reflected on the front-end content, nor in the API. 

### Steps to Reproduce:
1. Edit `A.1.1 - Landing` and move it to the request for archive state. Hit save.
1. Edit `A.1.1 - Landing` and move it to the archive state. Hit save.
1. Look at the A.1 landing page and you will see A.1.1 and all of its children still in the nav. This applies for getting the JSON for  1500002 from the section-nav API.

**Comment by KateMashkinaNIH** [comment]
Test Cases
Background:
When As a user I create a nav root site section with a landing page
And I add a child site section which is set as nav root and has a landing page
And I add a child site section which is NOT set as a nav root and has landing page

Scenario: As a user I want to archive site landing page which site section is set as nav root
When I archive landing page of a site section which is set to nav root 
Then I do not see that site section in the left nav on FE

Scenario: As a user I want to archive site landing page which site section is not set as nav root
 When I archive landing page of a site section which is NOT set to nav root 
Then I do not see that site section in the left nav on FE
