### ISSUE TITLE
Spike: Determine Best Approach for Theme Logos

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3340]
## In order to <achieve some goal> <a system or persona> needs to <some action>.
> **Estimate** *# point* Timebox to 3 hours

Options:
1. Use switch statements to serve up the correct logo
    * FINDING: **This will not work.** The `systemLanguage` is based on the user's system language.
2. Use symbols to chose the correct logo
     * FINDING: **This may work** There are currently some issues with the header in how `<svg><use>` works in the nci-header. 
3. Use text for the logo and only NIH tag as SVG
    * We need to see what we can do with the block. 
    * FINDING: **This will not work** Fonts are slow to load and there were some other issues.
4. Add multiple fields to the theme for each language, even if they are not used. (ewwww)

Open Questions:
1. How do we handle alt text without a release? How can we programmatically do it for every site?
    1. It is possible that we can use aria-labeledby="symbol in svg with a <title> element" 

### Expected Deliverables:
* The approach for managing logos in the Drupal theme without having to add to our code base

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

- Resizing the the logos to be consistent in this ticket: https://github.com/NCIOCPL/ncids/issues/433
- Reorganizing the header in this ticket: https://github.com/NCIOCPL/ncids/issues/426

We will go with option 2

**Comment by arcepaul** [comment]
Regarding use of a multi-lingual svg for the logo, it WILL NOT work in a way that would be useful.  Unfortunately, the SVG switch statement using `systemLanguage` as a conditional looks at what language is set for the system (or application in some cases).  Unfortunately it does not respect the language of the DOCUMENT (ie, `<html lang="en">`) so the language toggle would not work.

A codepen example is available at: https://codepen.io/arcepaul/pen/BampLgP

Changing the language for the application (safari in this case) works but there is no way to change application settings programmatically.
<img width="1128" alt="Captura de Pantalla 2022-04-05 a la(s) 9 07 45 a  m" src="https://user-images.githubusercontent.com/45469809/161765504-88c10005-78bd-429f-9e0c-a3e3f07690c5.png">
