### ISSUE TITLE
Reconfigure Fonts for use on Platform

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#3350]
Currently, we are serving up Montserrat and DIN Condensed from Common.css.  (more specifically, _fonts.scss).  In addition, we are not correctly preloading the fonts properly.

Montserrat is available as a google font, so it should be utilized in the same manner that we use Noto Sans as a google font. 

DIN Condensed is only used in Charts and should not be a part of Common.  Rather, we should only ever be forcing users to download the font if they access FactBook Charts.

> **ESTIMATE** 2

### What's the expected change?
- Add Montserrat as a selected font on our Google Fonts request
- remove Montserrat fonts from static
- update html header template with recommended preload tags for google fonts
- Move import of DIN Condensed into Charts library

The possibility of slight variations between the web font and the font we were serving up will require extensive visual regression testing.

**Comment by sarinapadilla** [comment]
Closing this ticket and creating a new ticket for DCEG Connect.
