### ISSUE TITLE
In Borderless Cards, the hover state color does not appear on title text when the button is removed.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3355]
### Issue description

When button is removed from the borderless cards, the whole card becomes clickable but the hover state color (red) on the titles disappear. We see it happening on AP and NCA 50. Currently, AP has a "Read More" button so we get the hover state color (red) on the title. NCA50 does not have any button so we don't see any hover state color on it. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/news-events/nca50
2. Hover on the title text "Why Commemorate 50 Years of the National Cancer Act?"
3. There is no hover state color for the title text as there is no button. 
														

### What's the expected result? (from @acsnedegar (see the comment))
- The title text should continue showing hover state color with/without button for all borderless cards:
Accent Warm and Default themes: #bb0e3d
Cool Theme: White text with underline

### What's the actual result?
- There is no hover state color for the title text when there is no button. 

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999
cc: @acsnedegar , @bennettcc, @VictoriaSunNIH

**Comment by alinai** [comment]
> @alinai Expected Result: The title text should continue showing hover state color with/without button for all borderless cards:
> 
> * Accent Warm and Default themes: #bb0e3d
> * Cool Theme: White text with underline

Thanks @acsnedegar for providing the acceptance criteria (AC). I have updated the "Expected Result" per your AC.

**Comment by andyvanavery31** [comment]
Borderless cards are no longer supported.
