### ISSUE TITLE
Press Release list is intermittently empty

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3370]
### Issue description
The dynamic list of press releases for 2022 intermittently comes up blank. This appears to periodically happen overnight with no errors recorded in the watchdog log.  Both the English and Spanish lists are affected (though not necessarily at the same time). The error seems to occur in Drupal with Akamai then caching the empty list.

This does not occur every day.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  First thing in the morning, browse to either https://www.cancer.gov/news-events/press-releases/2022 or https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2022

### What's the expected result?
- A list of press releases should appear (presently, at least 3 for English and 1 for Spanish).

### What's the actual result?
- The list is empty.

**Comment by santwuma** [comment]
@blairlearn can you please add the steps you've used in the past to fix this on the ticket? Also is this something that will need a code deployment?

**Comment by blairlearn** [comment]
Now that we know this wasn't some temporary glitch, the steps for resolving it are:

1. Login to either of the ncigov.01live webheads.
2. `bin/www-drush pinv url https://www.cancer.gov/news-events/press-releases/2022`
3. `bin/www-drush pinv url https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2022`
4. Login to https://control.akamai.com.
5. Click the hamburger menu and choose "Purge Cache".
6. Choose "Purge content by URLs"
7. Enter the URL(s) to be purged.
8. Verify "Current Network" is set to `Production` and "Purge Method" is set to `Invalidate`.
9. Click "Submit Purge"

Depending on what the underlying cause turns out to be, this will almost certainly require a code deployment.

**Comment by laurelthrash** [comment]
Not sure if we note anywhere about the frequency for which this issue occurs. Noting here this issue was reported and resolved on 05/15/23.
