### ISSUE TITLE
Background color for home and landing pages.

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3372]
### Based on our conversation on 4/29 we will need to update background colors on all microsites.

> **ESTIMATE** TBD

### Styling across microsites (except DCEG Connect): 
- [ ] Change Home and Landing Pages Background Color to: #F0F0F0 
    - [ ] Replaces the tannish background color on current home and landing pages  (current page: https://www.cancer.gov/)
    - [ ] Replaces the background "sides" on special report template pages (AP, NCA50, Patient Portal) but the current body container white background, header, and footer should stay the same  (current page: https://www.cancer.gov/research/annual-plan)
    - [ ] DCEG Connect's home/landing page should not be changed.
- [ ] Inner Pages should have white background color (#FFFFFF) across the whole background (except header and footer) and no dropshadow around the body container (current page: https://www.cancer.gov/research/areas/biology)
    - [ ] This includes inner pages across all microsites, including DCEG Connect inner pages

## Solution

**Comment by sarinapadilla** [comment]
Closing this ticket, as each individual build ticket for the different page types will address the background color change.
