### ISSUE TITLE
Get Transitional Theme Working

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3374]
Related to: https://github.com/arcepaul/cgov-digital-platform/compare/v1.3.8...ncids_trans and sorting through the 330 files changed

We need to:
a.	Get the backend theming architecture in place in Drupal 
b.	Get transitional theme files in place, and before we begin tackling features

This is an output from #3241 and the first step in updating the page and node templates to reflect NCIDS Layout

**Comment by bryanpizzillo** [comment]
Closing as this is a dupe
