### ISSUE TITLE
Make content area work with transitional theme

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#3375]
Note, this will require full testing of ALL page/content types visually (front-end).

There are a number of tasks associated with making the content area work:

- [ ] Remove tab index – we should do this as part of getting the theme working -- https://github.com/NCIOCPL/cgov-digital-platform/issues/3295#issuecomment-1099236212 (we had tried it here)
- [ ] Replace div with main and change the ID to main-content
- [ ] Add legacy class to wrap main-content as a container
- [ ] Replace skip-nav with .usa-skip nav
- [ ] Replace foundation with USWDS grid (this will be the bare minimum touched on pages for the change to work)
    - Templates to be touched:
      - [ ] templates/layout/page.html.twig
      - [ ] templates/content/application_page/page--cgov-application-page--no-left-nav.html.twig
      - [ ] templates/content/blog/page--cgov-blog-post.html.twig
      - [ ] templates/content/blog/page--cgov-blog-series.html.twig
      - [ ] templates/content/cthp/page--cgov-cthp.html.twig
      - [ ] templates/content/home_landing/page--cgov-home-landing.html.twig
      - [ ] templates/content/home_landing/page--cgov-home-landing--dceg-connect.html.twig --- WE SHOULDN’T BE TOUCHING THIS?
      - [ ] templates/content/home_landing/page--cgov-home-landing--special-report.html.twig
      - [ ] templates/page/page--404-en.html.twig
      - [ ] templates/page/page--404-es.html.twig

For all components below, we need to add them to the list of templates above, as well as build the components themselves (I think these might be separate tickets)
- [ ] Banner + Language Toggle – “This is a Government Website”
- [ ] Site Alert – Notification Area
- [ ] Header – NCI Logo, Search, Navigation
- [ ] Breadcrumbs
- [ ] Footer + Subscribe + Back to Top
- [ ] Side Nav (Left Nav) – not all pages, need the analysis of which pages would be affected
- [ ] Page Options – not all pages, need the analysis of which pages would be affected? Victoria to ask designers for final comps for page options

**Comment by sarinapadilla** [comment]
These updates are tracked in #3240, so closing this ticket.
