### ISSUE TITLE
Unsanitized URL parameter passing input through

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3402]
### Issue description
Security scans turned up an XSS vulnerability that actually looks to be an unsanitized URL parameter getting processed by Drupal on the some pages. Note that this is not active on PROD due to Akamai's countermeasures. 

Sample links:

This link places the word "netsparker" in the H1:

`https://dceg-test-acsf.cancer.gov/about/diversity-inclusion/inclusivity-minute?year=%3c%2ftitle%3%20e%3cscRipt%3enetsparker(0x085F79)%3c%2fscRip%20t%3e`

This link places the word netsparker in the page title:

`https://dceg-test-acsf.cancer.gov/news-events/news?year=%3C%2ftitle%3E%3CscRipt%3Enetsparker%20(0x0A2019)%3C%2fscRipt%3E`

This link generates an alert:

`https://dceg-test-acsf.cancer.gov/about/diversity-inclusion/inclusivity-minute?year=%3C%2ftitle%3E%3CscRipt%3Ealert(%22All%20your%20base%20are%20belong%20to%20us!%22)%3C%2fscRipt%3E`

This link demonstrates that it is not JS based:

`view-source:https://dceg-test-acsf.cancer.gov/news-events/news?year=%3C%2ftitle%3E%3CscRipt%3Enetsparker%20(0x0A2019)%3C%2fscRipt%3E`

Finally, this link is just for fun:

`https://dceg-test-acsf.cancer.gov/about/diversity-inclusion/inclusivity-minute?year=%3Ciframe%20width%3D%22560%22%20height%3D%22315%22%20src%3D%22https%3A%2F%2Fwww.youtube.com%2Fembed%2FdQw4w9WgXcQ%3Fautoplay%3D1%26mute%3D1%22%20frameborder%3D%220%22%20allow%3D%22accelerometer%3B%20autoplay%3B%20encrypted-media%3B%20gyroscope%3B%20picture-in-picture%22%20allowfullscreen%3E%3C%2Fiframe%3E%0A`

### Steps to reproduce the issue

1. Go to the sample links
2. View the title tag, H1 tag, or JavaScript alert that results

### What's the expected result?
- Input should be validated and set to empty if invalid
  - For year, only four digit numbers should be valid
  - For month, only numbers 01-12 should be valid (note that 01 - 09 are always 0 padded and don't work not 0 padded)
  - For topic, only alphanumeric characters should be allowed, plus colon ( : ) and hyphen ( - )
- Status code should be set to `400 Bad Request` if any input is invalid

### What's the actual result?
- Not sanitized
- XSS attacks possible

### Related Tickets
* Issue #3364

**Comment by blairlearn** [comment]
The key to this is the `_get_blog_series_title` function [at the end of docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.tokens.inc](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/cgov_blog.tokens.inc#L141-L148).

This function should verify that `$year`, `$month` and `$topic` are valid.

- `$year` - Integer.  **Business questions**: Non-negative? A specific range of years? (Not just the years we currently use, but what are reasonable years so we don't have to change this annually? 1900-3000?)
- `$month` - Integer, 1 through 12
- `$topic` - Needs investigation. How is this used? Can we limit it to a certain set of characters? (e.g. `a-zA-Z0-9\-`)

**Unresolved question:** How should the system respond if any of these are invalid? Pretend they weren't received? Return an HTTP 400 status? Something else?

**Comment by jfrank-nih** [comment]
Unless @lburack has a different opinion, I would go with just ignoring it if it doesn't match.

Topic is an open question still, as you note.

**Comment by lburack** [comment]
> Topic example: https://www.cancer.gov/news-events/cancer-currents-blog?topic=disparities
> 
> If it's not too computationally expensive, we could check the provided topic against known topics and ignore if no match.

@jfrank-nih  - does "ignore" = not populate the page/give a 404 error?

**Comment by jfrank-nih** [comment]
I just added a couple of questions:

- What should the status code be set to?
  - If it is a completely invalid parameter? (I.e. the attack)
  - If it is a valid but not-existing parameter? (i.e. 2029)

Can you give us input on what's best?

**Comment by jfrank-nih** [comment]
After reviewing the status codes, I think a `400 Bad Request` as @blairlearn suggested is probably applicable to anything that doesn't pass validation.  And I think that a simple alphanumeric validation for Topic, maybe also allowing hyphens and colons, would be sufficient. No need to validate against existing topics.

Upon further consideration I don't think `404 Not Found` actually applies at all here. Because the _page itself_ is a valid page, even if there are 0 results. (Ideally we would say "0 results found", but that's a matter for a different ticket.) 

Everyone good with that?

**Comment by lburack** [comment]
Heh, I like the I'm a teapot! But a `400 Bad Request` is good for me. 
I don't imagine users would stumble on such pages themselves. We (should) only link to these pages that are actually valid so users would have to enter the URL criteria themselves, which isn't likely.

**Comment by blairlearn** [comment]
@ramu-nih, Additional review has turned up additional places where this vulnerability exists.

In addition to what's in the main description, you'll also need to search through the `cgov_blog` module and look for other places where `$topic`, `$month`, and `$year` appear to see if they're retrieving values in an unsafe manner.

`blog_macros.twig` creates a `drawBlogSeriesTitle` macro.

There are also a number of places in the twig macros which access query parameters via the `get.` object.  These also need to be reviewed to determine whether they are output. (And if so, are they output in a safe manner?)

**Comment by KateMashkinaNIH** [comment]
Blogs:
- verified year parameter reply with 404s if value contains string ( however no set boundaries, e.g. 123456678 is allowed )
-verified month parameter reply with 404s if value is less or equals to 0 and more or equals to 13, or string

did not verify topic as it is not sanitizing
