### ISSUE TITLE
Enabler: Create a Utility Library for EDDL Analytics

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3408]
# Create a Utility Library for EDDL Analytics
> **ESTIMATE** TBD

A number of years ago we implemented a Data Layer for handling Launch analytics that decouples our applications from the analytics layer. The Digital Platform did not get updated to use this, only using the legacy NCIAnalyticsFunction. Now that we are creating the new `ncids_trans` theme and need to implement new analytics it is time to implement the EDDL.

For now we only need to support the "Other" event type. The definition of the data is below.

#### Other Event Data
```
window.NCIDataLayer.push({
  type: 'Other',
  event: '<EVENT_NAME>',
  linkName: '<SOME_IDENTIFIER',
  data: {

  }
})
```
| Property                    | Description |
| --------------------------- | ----------- |
| event                       | The name of the event. This is the Direct Call ID. e.g. ButtonClick |
| linkName                    | The debugging linkname that this event represents. Making this different from event since there could be one launch rule, (e.g. ButtonClick) that is going to handle the same data elements, but with different elements application triggers. This can cut down on the number of launch rules, but still let us know what element was sending the click. |
| data                        | The data for the event. This is free form and whatever is needed by the click event. |

>**_NOTE:_** While a developer only sends the data for the click, the Direct Call event would get the full page object along with the click data and link name.

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3393!
