### ISSUE TITLE
The token current-page:title double encodes html entities

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3419]
### Issue description
> **ESTIMATE** 5

In reviewing the inner pages implementation we noticed a page with the title `TCGA&#039;s Study of Lung Squamous Cell Carcinoma` is displaying the HTML entity, visually, in the breadcrumbs. (Which is happening because it is double encoding the entities.) The URL you can see this is `/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers/lung-squamous`, but that is from production. So as a developer, you will probably need to create add a node through YAML content to see it on a local machine. 

Notes:
Spanish characters seem to work: https://ncigovcdode476.prod.acquia-sites.com/espanol/investigacion/areas/biologia

Added quotes to this page title and they are showing up with HTML entity in the breadcrumb: https://ncigovcdode476.prod.acquia-sites.com/about-nci/organization/ccg/research/structural-genomics/tcga/studied-cancers/cholangiocarcinoma

Also tried entering the apostrophe directly in the page title field and from pasting in and both result in the HTML showing in the breadcrumb

### Additional details / screenshot
<img width="741" alt="image" src="https://user-images.githubusercontent.com/11215649/175077004-bb0726f5-fcaf-4c2b-9a7a-5b8393b6b340.png">

### Related Tickets
* #3242

**Comment by sarinapadilla** [comment]
This might only have to do with single and double quotes.

**Comment by ramu-nih** [comment]
It seems[ Drupal core token replacement](https://github.com/drupal/drupal/blob/9.3.18/core/lib/Drupal/Core/Utility/Token.php#L204) function provides sanitized value.

I think we need to use twig filter (raw) to render this token value.

@bryanpizzillo Please advise. Thanks

**Comment by sarinapadilla** [comment]
Closing this ticket as it was fixed by PR #3445!
