### ISSUE TITLE
A number of sass partials reference breakpoints, colors and variables

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3422]
### Issue description
> **ESTIMATE** 3

Partials should not reference mixins and settings, but just produce classes. (I guess they can reference other partials that also generate classes 🤷) This is an issue with the redesign as we need to "remove[1]" the widescreen breakpoint. This became a problem as there are many SASS partials that reference mixins, the breakpoint and colors. We cannot override the breakpoints and still share the partials in the new ncids_trans theme if those partials are including their own breakpoints mixin. The entry points should require these, and the import of the other partials should use the ones the entry point pulled in.

So I had said we should only do breakpoints, and wait on the others, but that day has already come. This ticket will be to remove ALL mixins and settings all from partials and make sure they are imported in all the entry points that use those partials.

[1] Remove means to set it to a stupidly-high number such that no monitor side would ever trigger that media query.

**Comment by bennettcc** [comment]
Closing this ticket. Per @bryanpizzillo it was completed and committed as a part of https://github.com/NCIOCPL/cgov-digital-platform/pull/3393
