### ISSUE TITLE
Cookies not marked as HttpOnly

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3427]
HTTPOnly cookies cannot be read by client-side scripts, therefore marking a cookie as HTTPOnly can provide an additional layer of protection against cross-site scripting attacks.

During a cross-site scripting attack, an attacker might easily access cookies and hijack the victim's session.

The following cookies were not marked as `HttpOnly`:

- `ProactiveLiveHelpForCTSPrompt-timer`
- `Spanish-CTSPrompt-timer`
- `nci_scroll`

**Remedy**

Mark cookies as `HttpOnly` when creating them.

**Comment by jfrank-nih** [comment]
@bryanpizzillo or maybe @arcepaul: I am not familiar enough with our cookies to know for sure, but these all _look_ to me like cookies that A) do need to be accessible from client-side scripts and B) are unlikely to be a concern if they were accessed via an XSS attack. Who can confirm for me?

**Comment by blairlearn** [comment]
These are all "working as designed."

The first is a countdown for the "Proactive Help" popup on CTS pages.
The second is similar for Spanish. (I'm surprised the names aren't similar.)
The last one is used by analytics.

**Comment by jfrank-nih** [comment]
I have updated the description with these additional cookies. I believe them to all be Adobe related (@welshja) and thus would need to have script access. Leaving the ticket closed.

- `s_fid`
- `gpv_pn`
- `s_ppv`
- `s_tp`
-  `engagementTracking`
- `s_cc`
- `s_sq`
