### ISSUE TITLE
Update Institute Type Drop Down on the Cancer Center Content Type

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3443]
Change Request submitted by Adriana Martinez of OCC:

When updating the cancer center content type in drupal there is a mandatory field "Institution Type" - the dropdown menu lets you pick from 3 Institution types "Basic laboratory Cancer Center, Cancer Center, Comprehensive Cancer Center". The change is for "Cancer Center" it should read "Clinical Cancer Center"

This text selected in the dropdown is shown on the front end of each Cancer Center page. Example: https://www.cancer.gov/research/infrastructure/cancer-centers/find/vanderbiltingram

What's the updated acceptance criteria?
The 'Cancer Center' institution type reads 'Clinical Cancer Center'

![image](https://user-images.githubusercontent.com/22639543/178792837-025bf009-1051-4d9e-a700-8b71ad026731.png)

**Comment by andyvanavery31** [comment]
Closing due to this being completed.
