### ISSUE TITLE
Change the Adobe Launch config to dev environment of main property

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3455]
### Issue description
> **ESTIMATE** TBD

Currently the CGDP uses the Production environment of the Digital Platform: Extension Development property when it installs a new instance of Drupal. This is for ODEs and for new production ACSF sites. Using the extension development property has become a challenge as:
* There is no way to easily move rules and other configuration between a property configured for extension development and a property not configured for extension development, e.g., the one for www.cancer.gov.
* We have an ever more increasing number of rules for redesign that would require copy/pastes.

So the request is to change the default Adobe Launch configuration to use the **development** environment of the Digital Platform: CGov: EDDL-Enabled property. (`<script src="https://assets.adobedtm.com/6a4249cd0a2c/949e98979342/launch-d90dca90a30f-development.min.js"></script>`)

This will allow the analytics team to easily create and test rules, reducing the time for duplication, as well as not **requiring** the Adobe Experience Platform Debugger to test rules. (It is still helpful to debug broken rules though)

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed by PR #3456!
