### ISSUE TITLE
Enabler: Validate Pull Requests and Commits

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3457]
# Validate Pull Requests and Commits

* Validate that commits have a correct subject in format `(#issue) subject`
* Validate that commit subjects are long enough and short enough
* Validate that pull requests note close out targets

# Resources
* http://commitlint.js.org/
* https://commitlint.js.org/#/reference-rules
* https://github.com/marketplace/actions/commit-linter
* https://dev.to/strdr4605/commitlint-custom-commit-message-with-emojis-3ob4
* https://github.com/marketplace/actions/github-script

**Comment by bryanpizzillo** [comment]
Closing this out as we have the .github workflow we use for this now.
