### ISSUE TITLE
Carousel UI Issue When Editing Home Page

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3469]
### Issue description
*Identified issue during Drupal 9.4 Upgrade testing on 07/21/2022 that occurs when editing the Cancer.gov home page. While editing the home page, carousel content at the bottom of the page is not representative of the UI while in a "Published" state. This occurs when the workflow is in "editing." Carousel appears as expected once in "published" state. 

Environments impacted: all*

> **ESTIMATE** TBD

### Steps to reproduce the issue (in Dev environment)

1. Log into CMS
2. Navigate to the cancer.gov home page: https://www-cms-dev.cancer.gov/
3. Click "Tasks Published" in the top right corner
4. Select "View in edit form"
5. Scroll to the bottom of the page
6. Click "Save (this translation)"
7. Page will refresh and the home page will be in "Editing" status
8. Scroll to the bottom of the page > see UI issue (screen shot attached)

### What's the expected result?
- Expected result is for the home page UI while in "Editing" status to display the same UI that displays while in "Published" status.

### What's the actual result?
- Actual result is that the home page UI while in "Editing" status displays a UI not representative of the UI in "Published" status.

### Additional details / screenshot
![1  Carousel UI During Editing](https://user-images.githubusercontent.com/102998716/182202562-c96b0869-04ac-475c-b7fe-8169093d2fec.jpg)
![2  Carousel UI in Published Status](https://user-images.githubusercontent.com/102998716/182202575-1f575a15-13fe-44de-bc61-6da8efc90d6f.jpg)

**Comment by andyvanavery31** [comment]
The carousel no longer exists so this is being closed.
