### ISSUE TITLE
Update CCG logo with correct crop

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3485]
The current CCG logo is cropped with too much whitespace around the logo itself. This should be updated to look like SBIR's logo, which has minimal whitespace around the edges.

[CCG](https://github.com/NCIOCPL/cgov-digital-platform/blob/b321288654143a4ff17e59590d628cafc62dca78/docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/logos/ccg-logo.svg) vs. [SBIR](https://github.com/NCIOCPL/cgov-digital-platform/blob/b321288654143a4ff17e59590d628cafc62dca78/docroot/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/logos/sbir-logo.svg)

**Comment by acsnedegar** [comment]
![CCG-Logo-COLOR](https://user-images.githubusercontent.com/79338977/184393544-cade09d5-50f0-45cd-b7a6-6be676a5ad4b.svg)
Hi @sarinapadilla and @meglake - here is a cropped svg of that logo but let me know if you need anything else. Thanks!
