### ISSUE TITLE
Story: Build NCIDS Inline Video 

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3491]
## As a content editor, I want be able to add an Inline Video component, so that I can embed a NCIDS Video module onto Cancer.gov content.

This story is to implement one of the prioritized variants of the NCIDS Video. For MVP2, this will be implemented on the Home & Landing page content type.

* Install NCIDS Video package/import it onto pages wherever they go/whatever
* Drupal currently has oembed, which adds an iframe
* ncids_inline_youtube_video paragraph
  * field_youtube_link on this paragraph
* How do we handle existing cgov_videos on the site?

### Acceptance Criteria for Analytics
_NOTE: These depend on whether we are implementing a new video module_
- Component: Video
- how long they watched?
- index of component on page
- number of row components on page
- location ("body" maybe)
- current page - the EDDL extension in launch captures and passes this value for all click events

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: Content editor is able to add an "NCIDS Inline Video" to a Home and Landing page
Given the user is logged in as an editor
  And the user edits a Home and Landing content item
When the user expands the dropdown to add a paragraph to Contents
Then the dropdown displays the "Add NCIDS Inline Video" option
When the user selects the "Add NCIDS Video" option
Then the fields for an "NCIDS Video" paragraph appear
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---
## Accessibility
[ ] Add the title attribute into the iframe element. Describe in a few words the content of the video. (SC 4.1.2)
[ ] Add subtitles, if there is spoken words or important sound effects in the video (SC 1.2.2)
[ ] Add audio description, if necessary (SC 1.2.3, SC 1.2.5)
[ ] Use enough contrast for text in the video (SC 1.4.3)
[ ] Disable keyboard short cuts. Change YouTube's default disablekb=0 to 1 (SC 2.1.4)
[ ] Do not use autoplay. Keep it to YouTube's default: autoplay=0
[ ] Show controls. Keep it to YouTube's default: controls=1 (in case of autoplay SC 1.4.2)
[ ] Keep full screen option available. Keep it to YouTube's default: fs=1
[ ] Keep the YouTube logo, so the user can easily watch the video on YouTube or in the YouTube app. Keep it to YouTube's default: modestbranding=0

## Solution
- New paragraph with type cgov video
- display modes
- new template for ncids inline-video

### Prerequisites
- #3747 

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
Content model: [NCIDS Inline Video](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-inline-video)

- https://www.figma.com/file/3LA0fAGyGdzpBeNDCoulFf/NCI-Design-System?type=design&node-id=2162-3511
<img width="337" alt="Screenshot 2023-05-12 at 12 22 56 PM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/45469809/0763ebb0-7727-4511-9945-7db99032fb54">

**Comment by arcepaul** [comment]
1. Should there be a title displayed along with the video
2. Should there be a link to transcripts?
