### ISSUE TITLE
Store browser title field separate from page title field

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#3513]
### Issue description
The CDR users would like to be able to edit the browser title for Cancer Information Summary (CIS) pages in the CDR.

> **ESTIMATE** TBD

### What's the expected change?
- Drupal accepts from the CDR and stores a possibly different value for the browser title than the value used for the title displayed at the top of the page, and actually uses this new value as the browser title (sent to the browser as the `<title>` element of the `<head>` block of the HTML document).

### What's the current functionality?
There are currently two fields for storing titles in CIS nodes.

1. A field labeled "**Title**" on the node-editing form in Drupal, populated from the `SummaryTitle` field in the CDR document. This is used both for the browser title (`html/head/title`, displayed in the browser tab and tooltip, possibly truncated, with the site identification appended) and the title displayed at the top of the page.
2. A field labeled "**Browser Title**" on the Drupal node-editing form, populated from the CDR `AltTitle` element with the type element equal to "**Short**," and used on the _Cancer Type Home Page_. Despite the label for this field (as well as its description, which says that it is displayed in the browser tab), the value stored in this field is **not** used as the browser title.

#### Titles on Drupal node form
![image](https://user-images.githubusercontent.com/1634628/187998191-908b2f09-03b6-46f7-815a-c39ada967df2.png)
#### Title element in the head block of the HTML document
![image](https://user-images.githubusercontent.com/1634628/187998220-50b1d51c-befe-4c5d-b6b3-a32f67d01132.png)

### Related issues
https://tracker.nci.nih.gov/browse/OCECDR-5104

**Comment by bryanpizzillo** [comment]
@bkline this seems to be a little off. The browser title SHOULD be used as a browser title. I think the need here is that we do not want audiences to appear on the CTHP Guide Cards. So a shell game was played at the end of migration where the old CDR short title went to browser title, and then the "browser title" was used on CTHP Guide Cards to the Audience did not appear. THEN we changed the meta title to be the node title for ???.

I think this should be:
1. Make the `field_browser_title` be the actual browser title like everything else in the system.
2. Change the template `node--cthp-guide-card-list-item.html.twig to use a new `field_cthp_card_title`. Probably would be even better to create a new `node--pdq_cancer_information_summary--cthp-guide-card-list-item.html.twig` template to make sure that all the other content, if it *was ever* added to the PDQ links, would still work.

**Comment by bkline** [comment]
Agreed.

**Comment by bkline** [comment]
@lburack I understand you wanted to weigh in on this ticket. @laurelthrash this is the ticket we talked about getting onto the DP board so it could get into the work pipeline.

**Comment by lburack** [comment]
@bkline - 
1. Would this change just impact cancer information summaries, or all content in the CDR? 
2. I think we should get a report of all impacted summaries (based on the answer to # 1) with their URLs and what's currently populated in each title field. 

Question for @bryanpizzillo  in response to his comment above:

> 2\. Change the template `node--cthp-guide-card-list-item.html.twig to use a new `field_cthp_card_title`. Probably would be even better to create a new `node--pdq_cancer_information_summary--cthp-guide-card-list-item.html.twig` template to make sure that all the other content, if it _was ever_ added to the PDQ links, would still work.

Would this `field_cthp_card_title`only display on CTHP cards? Ideally this should display in feature cards or anywhere else the card title is used.

**Comment by bkline** [comment]
Reading the JIRA ticket, I'd say this request is just for CIS documents, not for the drug summaries.

**Comment by bkline** [comment]
Here's the report you requested, @lburack —
[issue-3513.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/9684134/issue-3513.xlsx)

**Comment by lburack** [comment]
Thanks! My thoughts after reviewing the report and thinking through this ticket a bit more:

- I agree with Bryan’s comment that the `field_browser_title` should be the actual browser title
   - This field is on the Drupal form, currently being pulled from the CDR short title
   - We are saying this Drupal field should be the actual page’s browser title
   - If I understand this correctly, this wouldn’t actually change anything about the page metadata
- I think there’s still an issue that CDR doesn’t have separate fields for browser title and H1 page title. Our SEO guidance advises having distinct titles (page vs browser).
   - I've mentioned this to @amydugan so we can discuss in an upcoming CDR meeting. We need to finalize the requirements so we can then determine what development work needs to happen and when it can be completed.

**Comment by bkline** [comment]
> ..., this wouldn't actually change anything about the page metadata

That's true for how the page metadata is stored, but not true for how it's used, I think.

> ... there's still an issue that CDR doesn't have separate fields for browser title and H1 page title.

That issue is addressed by what you wrote above that sentence:

> We are saying this Drupal field [`field_browser_title`] should be the actual page's browser title

The issue which that decision doesn't address is the fact that we need three titles (ignoring the fourth title for left navigation, which is stored separately from the page's node entity fields) but we currently only have two title fields. The solution proposed by Bryan above is to add a third field (`field_cthp_card_title` is the name he suggested) which will be populated separately from the CDR.

I think that, from a high-level perspective, the development work which needs to happen would include
* add the new field to the `pdq_cancer_information_summary` type (Drupal/Bob)
* modify the REST plugin code to accept and store the new field's value (Drupal/Bob)
* modify the twig template(s) to adjust which field values are used where (Drupal/TBD)
* modify the `Summary` schema and XMetaL CSS to support the new value (CDR/Bob)
* populate the summary documents with the new value (CDR/PCIB+CIAT)
* modify the publishing filters to pick up and export the new value (CDR/Volker)

I estimate a couple of days total for the tasks with my name on them.

**Comment by bkline** [comment]
@lburack Can you tell me what the limit should be for the number of characters in each of the three PDQ title fields?

**Comment by bkline** [comment]
I'll create another report for you to show the lengths of the PDQ summary titles.

**Comment by bkline** [comment]
Here's the report. 154 summaries have browser titles longer than 52 characters. Five have main titles which are longer than 100 characters, and 132 main titles over 60 characters.
[gh-3513.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/10574259/gh-3513.xlsx)

**Comment by bkline** [comment]
Another question about how I should implement this. I could have the update hook copy the values from the existing browser title field into the new cthp-card field (making the new field required). Or we could have the template fall back on the browser title field for the CTHP card if the new field has no value. Arguments pro or con?

**Comment by bkline** [comment]
@bryanpizzillo Did you want to weigh in on the question in the previous comment (Blair demurred, saying he hasn't part of any of the conversations surrounding this new field)? Off the top of my head, the drawback of making the new field optional is a slight complication in the template's logic, and the drawback of making it required (and populating it in the update hook) would be causing the deployment to take longer. I don't have a good sense as to whether the possibility that the field might be used for other bundles has any bearing on the decision (my understanding is that we can make that property — required/optional — bundle-specific). I'm happy to do it whichever way you prefer.

**Comment by bkline** [comment]
Also, I see there's already a`paragraph__field_cthp_card_title` field. That field has a maximum length of 255 characters, but I assume the new field will have a limit of 100 (following the input from @lburack above).

**Comment by bkline** [comment]
@lburack In setting up the new field type, I notice that there are many more view modes in our site than I realized. One of them is "CTHP: Research Card" and it's not given custom display settings (unlike the "CTHP: Guide Card List Item" view mode, which did have custom settings, and where I swapped out the browser title for the new CTHP card title field). Any idea whether the "CTHP: Research Card" view mode should be customized now that we have the new field? Or is the default set of settings (which includes the new field) still an adequate fallback?

**Comment by bryanpizzillo** [comment]
>Reverting commit [787973e](https://github.com/NCIOCPL/cgov-digital-platform/commit/787973e) does what I expected in making sure that the browser title field is used for the PDQ CIS head title in a newly built site, but it's not clear to me how a change to configuration in an "install" directory gets propagated to the existing (already installed) production site. There must be some magic somewhere in the release deployment scripts which takes care of this, though, since modifying the settings in that configuration file was all that happened in the commit I'm reverting.

This is what Features does. Technically `blt drupal:update` calls `drush updb` followed by (multiple) `drush features:import:all`. This all happens when it is deployed.

As far as templates go. I think you would only make a new `node--pdq-cancer-information-summary--cthp-guide-card-list-item.html.twig` and then have it use the CTHP title.

**Comment by bkline** [comment]
@lburack The changes on the CDR side have been promoted up through the STAGE tier and tested, and the transformed summaries have been published to the [ODE](https://ncigovcdode539.prod.acquia-sites.com/) for this ticket. Please look them over and let me know if they have everything you need. If there are any deficiencies, now would be the time to point them out, before @bryanpizzillo brings out his magnifying glass to examine the PR. 🔍👀😅

**Comment by bkline** [comment]
@bryanpizzillo asked in this afternoon's meeting if any changes had been made to the [code](https://github.com/NCIOCPL/cgov-digital-platform/blob/pdq-title-fields/docroot/profiles/custom/cgov_site/modules/custom/pdq_cancer_information_summary/pdq_cancer_information_summary.module) which adds site sections. I just checked and no changes have been made to that code in several years.

**Comment by KateMashkinaNIH** [comment]
Verified the new card title field ( also built automated tests to cover it ) 
Verified that PDQ summary https://ncigovcdode539.prod.acquia-sites.com/types/breast/hp/child-breast-treatment-pdq displays browser title as left nav without a label override. Added a label override and that persists after updating the summary
