### ISSUE TITLE
Proactive Chat Window not appearing

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3514]
### Issue description
The proactive chat window for Clinical Trial Search did not appear on Tuesday, September 6, 2022. Labor Day is (of course) on a Monday this year, however the underlying code examines holiday dates in 2021.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Set your computer's clock to sometime during business hours on Tuesday, September 6, 2022.
2. Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&rl=1 (any path under https://www.cancer.gov/about-cancer/treatment/clinical-trials should do)
3. Wait

### What's the expected result?
- The proactive chat window appears after 30 seconds

### What's the actual result?
- Nothing happens

**Comment by blairlearn** [comment]
The cause of the problem is [the `findObservedHoliday` method](https://github.com/NCIOCPL/cgov-digital-platform/blob/63ad6f43909c08e6b2cd439270221da011442ac5/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/utilities/dateUtility.js#L64-L82).

The prospective holiday's date is passed in as the `holiday` object. If the date is a Saturday, it's adjusted to one day earlier. In 2022, New Year's Day was on a Saturday, causing the holiday date's _year_ to also be changed.

Because the holiday date was passed as an object (aka "call by reference") the object is modified for the calling method as well.  In the case of the `isHoliday` method, that object is expected to contain the current date. Because the first holiday checked for is New Year's, all subsequent comparisons are for dates in the previous year.

**Comment by santwuma** [comment]
@sarinapadilla to test ticket in ODE and update ticket with comments.
