### ISSUE TITLE
Update CTS LiveHelp pop-up for NCIDS Layouts

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3522]
### Issue description
The Proactive Chat pop-up is currently missing styling on the inner and application pages on which it shows. The pop-up styles need to be updated to work in NCIDS.

This is related to #3385 and #3379 and maybe #3380 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
- The LiveHelp pop-up displays with it's current CGov styling.

### What's the actual result?
- The LiveHelp pop-up is smushed into the bottom left corner, with no styling.

### Additional details / screenshot
<img width="1463" alt="livehelp" src="https://user-images.githubusercontent.com/24591940/189236703-ec5512fa-2def-4d0d-868c-bda1fc7e5881.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bennettcc** [comment]
This is complete - closing
