### ISSUE TITLE
Update analytics event and linkname on Footer Email Sign-up Component

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#3528]
### Issue description
This change is to update the analytics event name and linkname in the footer email sign up component. These values are part of what is fired as an analytics event when someone clicks into the form field, clicks submit with errors, or clicks submit successfully.

In all cases, the analytics event name and linkname are within each of the three actions. Those current names are:
Form:Start
Form:Error
Form:Complete

We'd like to update them to be the following:
Footer:EmailForm:Start
Footer:EmailForm:Error
Footer:EmailForm:Complete

> **ESTIMATE** 2

### What's the expected change?
Values for both the analytics event name and the link name are updated as specified above.

### What's the current functionality?
These values are passed when someone clicks into the form field, clicks submit with errors, or clicks submit successfully. This change is an update to the names of the values.

### What's the updated acceptance criteria?
``` gherkin
Scenario: Email Sign-Up Form Click
Given a user is on any page of cancer.gov
Then there should be an NCIDataLayer Other event 
  And the event has the name “Footer:EmailForm:Start”
  And the event has the the linkname “FooterForm:Start”
  And this event should have the following data:
      | key      | value       |
      | formType | EmailSignUp |
      | status   | Start       |
      | location | Footer      |
```

``` gherkin
Scenario: Email Sign-Up Form Submit
Given a user is on any page of cancer.gov
Then there should be an NCIDataLayer Other event 
  And the event has the name “Footer:EmailForm:Complete”
  And the event has the the linkname “Footer:EmailForm:Complete”
  And this event should have the following data:
      | key      | value       |
      | formType | EmailSignUp |
      | status   | Complete    |
      | location | Footer      |
```

``` gherkin
Scenario: Email Sign-Up Form Error
Given a user is on any page of cancer.gov
Then there should be an NCIDataLayer Other event 
  And the event has the name “Footer:EmailForm:Error”
  And the event has the the linkname “Footer:EmailForm:Error”
  And this event should have the following data:
      | key      | value       |
      | formType | EmailSignUp |
      | status   | Error       |
      | location | Footer      |
```

### Related Tickets
* Original Story Ticket #3216

**Comment by sarinapadilla** [comment]
Possibly related to this change request, the email form analytics events are not currently firing on ACSF Test. This may be caused by a change in the rule in Launch to the updated values above, but no change in the code.

**Comment by meglake** [comment]
Note - This is an as time permits change request but we wont hold up MVP 1 launch for this change.
