### ISSUE TITLE
Update CMS UI Modules

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3537]
# Update CMS UI Modules

### Modules to be updated:
- admin_toolbar - upgrade from 3.0.3 -> 3.4.1
- moderation_sidebar - upgrade from 1.4.0-> 1.7.0 (D10 version)
-  1.7 Latest module version

**Comment by alinai** [comment]
@sarinapadilla, @navsunka , How are we supposed to test this? Running Automated Regression Tests suffice for this?
cc: @KateMashkinaNIH , @santwuma
