### ISSUE TITLE
Update Media Modules

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3539]
# Update Image Modules

### Modules to be updated
- crop - upgrade from 2.1.0 -> 2.3.0
- Image_widget_crop - upgrade from 2.3 -> 2.4
- imagemagick - upgrade from 3.2.0 -> 3.4.0
- file_mdm - upgrade from 2.1 -> 2.3
- sophron - upgrade from 1.1.0 -> 1.3.0

**Comment by bryanpizzillo** [comment]
`composer require drupal/imagemagick:^3.4.0 drupal/crop:^2.3.0 drupal/image_widget_crop:^2.4.0 drupal/file_mdm:^2.6.0 --update-with-dependencies`

```
Updating dependencies
Lock file operations: 1 install, 7 updates, 1 removal
  - Removing lsolesen/pel (0.9.10)
  - Upgrading drupal/crop (2.1.0 => 2.3.0)
  - Upgrading drupal/file_mdm (2.1.0 => 2.6.0)
  - Upgrading drupal/image_widget_crop (2.3.0 => 2.4.0)
  - Upgrading drupal/imagemagick (3.2.0 => 3.4.0)
  - Upgrading drupal/sophron (1.1.0 => 1.3.0)
  - Upgrading fileeye/mimemap (1.2.0 => 2.0.1)
  - Locking fileeye/pel (0.9.20)
  - Upgrading phenx/php-font-lib (0.5.2 => 0.5.4)
```
