### ISSUE TITLE
Update SEO Modules

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3541]
# Update SEO Modules

### Modules to be updated
- ~~metatag - upgrade from 1.16.0 -> 1.22~~
   - This is being handled in #4012
- ~~pathauto - upgrade from 1.8.0 -> 1.11.0~~
- ~~redirect - upgrade from 1.6.0 -> 1.8.0~~
- simple_sitemap - upgrade from 3.10.0 -> 4.x-dev
- ~~token - upgrade from 1.9.0-> 1.11.0~~
  - This is being handled in #4012
- ~~token_filter - upgrade from 11.3.0 -> 2.x-dev~~

The `/sitemap.xml` url is not available on lower-tier environments.  What appears to be needed is for the deployment script to include `drush cron` followed by `drush cr`.

Testing note:
  Verify that `/sitemap.xml` is available.

**Comment by naveen-kumar2** [comment]
simple_sitemap upgraded to stable version [4.1.6](https://www.drupal.org/project/simple_sitemap/releases/4.1.6)

**Comment by SupriyaSaxena0605** [comment]
@blairlearn @santwuma Regression tests passed on ODE 643
