### ISSUE TITLE
Enabler: Update ctools

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3544]
# Update ctools
The plan is to change blogs to Layout Builder and remove Page Manager and Panels. (#3807) Ctools is still needed in any case, so this task is to just update Ctools now.

### Prerequisites
- ctools - upgrade from 3.7.0 -> 4.0.4

**Comment by SupriyaSaxena0605** [comment]
@blairlearn Regression testing passed for this ticket. Checked content creation for blogs and blog series manually also
