### ISSUE TITLE
Enabler: Update twig tweak module

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3546]
# Update twig tweak module

### Module to be updated
- twig tweak - upgrade from 2.9.0 -> 3.1.3
 **Supported by D10

Since this is a major upgrade there is a potential for breaking changes. Please search through all the templates that use twig tweak and add a comment to this issue with that list. This will help QA in doing more targeted testing, and helping you test locally as well.

**Comment by smitahantziosps** [comment]
Below are the release from Twig Tweak 

### **twig_tweak 3.0.0**

#3174903: Error: Call to a member function getRegion() on null in hook_theme_suggestions_block_alter()
#3174273: Migrate documentation from drupal.org to Git
#3173946: drupal_region() overcaches empty
#3185016: Translation filter
Added drush twig-tweak:debug command
Added drush twig-tweak:validate command
Multiple minor bug fixes and improvements

### **twig_tweak 3.1.0**

Added cache_metadata Twig filter
#3188441: Allow arguments to be passed to token_replace
#3209909: Using file_url on a media field where the referenced entity is deleted, results in a fatal error
#3207943: Add UUID support to drupal_entity

### **twig_tweak 3.1.1**

Downgraded symfony/polyfill-php80 requirement to make the module compatible with drupal/core-recommended 9.0+
#3211870: Composer installation failed

### **twig_tweak 3.1.2**

#3222014: Allow custom display settings for drupal_field()

### **twig_tweak 3.1.3**

#3212340: drupal_block() show fatal error if block plugin return NULL
#3245953: TwigExtension::drupalTitle() should check for NullRouteMatch
#3222666: drupal_menu() incorrectly caches the active parent menu item in two-leveled menu

**Comment by smitahantziosps** [comment]
Navigate through the front end and test any disorder in frontend pages.

Example : twig_tweak module has lot of functions that is used for rendering like "drupal_view" that is used in https://ncigovcdode508.prod.acquia-sites.com/news-events/cancer-currents-blog - to render the blocks.

And it is rendering properly.

**Comment by smitahantziosps** [comment]
@alinai @kate-mashkina @santwuma This is ready for you to test!

**Comment by andyvanavery31** [comment]
This was closed in PR #3600 .

**Comment by blairlearn** [comment]
Closed in #3600
