### ISSUE TITLE
Blog RSS Feed

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#356]
Requirements:
* Generate the RSS link using the Feedburner Link field from the Blog Landing page that has been associated with the blog post through the Blog Series field.
  * Generate the link to the raw RSS Feed when the   feedburner link field has not been populated for a Blog Landing Page content   type.
  * Do not display the "Exit disclaimer"   button and link when the raw RSS feed is displayed

* On an RSS Feed, the following information from each blog post in the RSS feed should appear:
   * The Page Title of each blog post
   * The list description of each blog post
      * If no list description exists, then use the meta-description
   * Thumbnail image associated with each blog post

Front-end display:
* Display an RSS link beneath the title of the Blog Post with a   link that says "Subscribe" on desktop
* Display the RSS link as "Suscribir"   when viewing a Spanish blog post
* Display the "Exit Disclaimer" button and link when a Feedburner RSS link exists
   * Alt text associated with the "Exit   Disclaimer" button that displays when the user hovers over the button

Current Feeds:
https://www.cancer.gov/PublishedContent/List?root=RSS&fmt=html

Cancer Currents Blog: https://www.cancer.gov/PublishedContent/rss/news-events/cancer-currents-blog.rss
RAS: https://www.cancer.gov/PublishedContent/rss/research/key-initiatives/ras/ras-central/blog.rss
basically, the URL of the blog seiries on cancer.gov
looks like the pattern
but those are 2 examples
Cancer Current Categories are different
https://www.cancer.gov/PublishedContent/List?root=RSS&path=/news-events/cancer-currents-blog&fmt=html
those are all of the cancer currents category feeds
also:
https://www.cancer.gov/PublishedContent/List?root=RSS&path=/about-nci/organization&fmt=html
https://www.cancer.gov/about-nci/organization/crchd/blog

TESTING LINKS:
EN Full Feed (all blogs): /PublishedContent/RSS/syndication/rss/blog.rss
EN Blog Feed: /PublishedContent/RSS/syndication/rss/blog-series.rss?series=24 (NID of Blog Series)
EN Blog/Topic: /PublishedContent/RSS/syndication/rss/blog-series-topic.rss?series=24&topic=80 (series=[BlogSeries.NID], topic=[BlogTopic.TermID]

ES Full Feed (all blogs): /espanol/PublishedContent/RSS/syndication/rss/blog.rss
ES Blog Feed: /espanol/PublishedContent/RSS/syndication/rss/blog-series.rss?series=24 (NID of Blog Series)
ES Blog/Topic: /espanol/PublishedContent/RSS/syndication/rss/blog-series-topic.rss?series=24&topic=80 (series=[BlogSeries.NID], topic=[BlogTopic.TermID]

**Comment by bgnih** [comment]
For the categories (blog-topics) feed (https://www.cancer.gov/PublishedContent/List?root=RSS&path=/news-events/cancer-currents-blog&fmt=html ) we need to resolve the legacy categories (dl-biology, dl-cancer-risk) to the Drupal taxonomy terms.  

Should we
- add a blog-topics.legacy-key that contains the 'dl-*' value and use that as a contextual filter on the rss feed view?
- manually reroute it via Akamai redirects (may require updates when new terms are added)

**Comment by bgnih** [comment]
Per @VictoriaSunNIH, have the blog RSS feeds show ALL results, not just first 10 like Press Releases does.
