### ISSUE TITLE
Enabler: Upgrade Drupal Core to 9.4.7

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#3560]
# Upgrade Drupal Core to 9.4.7

Drupal core security upgrade required. Move core to 9.4.7. Addresses a Twig vulnerability and a related Drupal core vulnerability. Security risk rated as critical.

https://www.drupal.org/sa-core-2022-016

> **ESTIMATE** TBD

**Comment by santwuma** [comment]
Deployed 10/4//22
