### ISSUE TITLE
Mega Menus do not work for Microsites

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3565]
### Issue description
> **ESTIMATE** TBD

It looks like the mega menu adapter code is fetching the mega menu from `/taxonomy/term/<XXX>/mega-menu` for path based domains such as /nano. This is obviously not right as it would only get 404s. It should be fetching from `<microsite-path>/taxonomy/term/<XXX>/mega-menu`.

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed with PR #3567!
