### ISSUE TITLE
MyPART Home Page Hero Text Wrapping Issue

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3583]
### Basic Information

- Issue: During review with federal team on Tues. 10/4 @ 9:30am, team discussed how on the MyPART home page, the text in the hero is wrapping more lines than in production and is not centered in the hero, thus causing the text to be snug to border of the banner image. 
- Desired Outcome: For the text to wrap the same amount as in production so that the text is not snug to the border of the hero. Please reference production for the desired appearance (screenshot). 
- Notes: Bryan indicated on the call that we could try adding a raw HTML block to fix the issue

### Steps to Reproduce

- Navigate to microsite (https://www-test-acsf.cancer.gov/pediatric-adult-rare-tumor/)
- Look at the text inside the banner image
- See that the text wraps strangely and is not centered, compared to production (screenshot) 

### Screen Shots
![Image](https://user-images.githubusercontent.com/102998716/193864685-dd06ad42-1b7d-4769-80fe-5f0f3a3456a3.png)

**Comment by bryanpizzillo** [comment]
The code is:
```
<style>
  .cgdpl .hero-text p {
    font-size: .85em;   
  }
</style>
```

I added as a raw html block on test.

**Comment by bennettcc** [comment]
Thank you @bryanpizzillo! We show ODDC feds the myPart homepage this morning, and they approved it

**Comment by meglake** [comment]
@laurelthrash  added raw html block of NCI Connect ACSF test as well and is documenting steps for MVP 1 launch clean up. Closing out ticket.
