### ISSUE TITLE
NCI-CONNECT (Spanish) Home Page Hero Text Wrapping Issue (same as "MyPART Home Page...")

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3584]
SAME ISSUE OUTLINED as ISSUE "MyPART Home Page Hero Text Wrapping Issue"

### Basic Information

- Issue: During internal testing, noticed the same issue as mentioned in "MyPART Home Page Hero Text Wrapping Issue" is occurring on the home page for NIC-CONNECT (Spanish).T he text in the hero is wrapping more lines than in production and is not centered in the hero, thus causing the text to be snug to border of the banner image. 
- Desired Outcome: For the text to wrap the same amount as in production so that the text is not snug to the border of the hero. Please reference production for the desired appearance (screenshot). 
- Notes: Bryan indicated on the call that we could try adding a raw HTML block to fix the issue

### Steps to Reproduce

- Navigate to microsite (https://www-test-acsf.cancer.gov/rare-brain-spine-tumor/espanol)
- Look at the text inside the banner image
- See that the text wraps strangely and is not centered, compared to production (screenshot) 

### Screen Shots
![Image](https://user-images.githubusercontent.com/102998716/194420948-8555e590-e226-442b-9ecd-775e492df160.png)

**Comment by sarinapadilla** [comment]
Closing this ticket as it has been fixed on ACSF Test.
