### ISSUE TITLE
NCI Bottom Line Blog is not linked correctly in Mega Menu

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3592]
### Update ###
Initially thought this was a content issue to be corrected within the CMS (no code fix), however, determined on 10/7 that this is actually a bug. Updated "triage notes" to reflect this. 

**Video showing bug:** https://user-images.githubusercontent.com/102998716/194619189-ed4c1a4f-2d96-4f14-a385-e3113cc0464a.mp4

**Steps to Reproduce**
1. Navigate to microsite home page (https://www-test-acsf.cancer.gov/)
2. Click on "Grants and Training" 
3. Hover over "NCI Bottom Line Blog"
4. See in bottom left corner that link is correct (/grants-training/nci-bottom-line-blog)
5. Click on "Grants and Training" 
6. Hover over "NCI Bottom Line Blog"
7. See in bottom left corner that link is incorrect (/grants-training/grants-training/nci-bottom-line-blog)
8. Receive Page Not Found error

### Reported Issue ###
NCI Bottom Line Blog link in Mega menu is https://www-test-acsf.cancer.gov/about-nci/organization/ccg/grants-training/nci-bottom-line-blog. In #[3381](https://github.com/NCIOCPL/cgov-digital-platform/issues/3381) the link is https://www-test-acsf.cancer.gov/grants-training/nci-bottom-line-blog

**Comment by bryanpizzillo** [comment]
@bennettcc  Is this ticket to update YAML content? Otherwise, this should not be in this queue.

**Comment by meglake** [comment]
Confirmed this was a YAML issue (no / before the url string for Bottom Line blog menu link). This has been fixed in the YAML file on Teams, on PROD, and on ACSF Test. Note that you wont see this issue fixed unless you clear cache or open in a new incognito browser.
