### ISSUE TITLE
Print style page on microsite prints the linkback bar

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3597]
When printing the page from a microsite (screenshot below is from DCEG), the linkback bar appears at the top of the printed page

Steps to reproduce:
1) Navigate to any microsite page (any browser)
2) Print page within browser

![Image](https://user-images.githubusercontent.com/22639543/194389226-87f55baf-97b5-4f45-b46a-7ab1b17bb89d.png)

**Comment by bryanpizzillo** [comment]
@bennettcc & @meglake This issue should not be this. There should be no linkback on any NCIDS site, so this ticket should be to make sure the linkback bar does not show up on platform microsites. It does not matter if it prints or not. I would say turning it off is one of the go-live steps.

**Comment by bennettcc** [comment]
Perfect, thanks @bryanpizzillo - I'll close this one for that reason. @meglake we can add the 'remove linkback' step to our go live list
