### ISSUE TITLE
Implement Megamenu style changes

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3602]
### Issue description
Implement changes to megamenu in Drupal per DS ticket: https://github.com/NCIOCPL/ncids/issues/615

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bennettcc** [comment]
closing, the work described in this ticket was completed as a part of this request: https://github.com/NCIOCPL/ncids/issues/615
