### ISSUE TITLE
Mobile Menu needs more information from section nav

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3604]
### Issue description
> **ESTIMATE** TBD

The section-nav API implemented in #3243 does return information about the section navigation. However, there is a challenge determining what the "parent section navigation" is for a given section. In the digital platform, the mobile navigation only shows up to 4-levels deep. Many of the sections of the web site fall below those 4 levels. The mobile navigation allows a user to navigate all the way up to the primary menu from the page they are on. Given the mobile navigation is only 4 levels deep, and many (most?), section navigations do not appear in the mobile nav, we must fetch multiple navs from the API. (e.g., the section navigation for the page, any other section navigations, and the mobile navigation)

This change request is to also return 2 extra pieces of information:
* The next navigation to fetch when the user has "moved" out of the current section tree. This should include:
   * The site section id of the next navigation root.
   * The menu type of of that navigation:
      * `section-nav` - for a site section.
      * `mobile-nav` - for the mobile nav.
* The ID of the site section within that parent menu where the returned section navigation should be placed.
   * This should follow all the display rules as defined in ticket #3243. So there may be gaps if multiple parent site sections do not have valid landing pages, or are marked as hiding in navigation. That is ok. Find the closest. 
   * This ID will sometimes be the same ID as the section nav root id.

**Comment by bennettcc** [comment]
This is complete - closing
