### ISSUE TITLE
Change Request: Make logo larger in site header [Drupal Dev]

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3610]
Per feedback from client on 10/17, they would like to see a more proportional hierarchy in the header between the logo, section nav items, and megamenu items.

- [x] Update NCIDS Trans theme with new image upload fields for logos on all configured languages
- [x] Revise the site header to adjust the size of the site logo to the following:
-- Widescreen/Desktop: 50px 
-- Tablet/Mobile: 38px (logo is wrapped to two lines where necessary - for Drupal dev this includes: Cgov English, Cgov Spanish, DCEG, Nano, and Physics) 

**Due: ASAP week of 10/24 (this should be top priority)**

Once ticket is complete we'll review on ACSF Test (along with changes from [#615](https://github.com/NCIOCPL/ncids/issues/615)) with client to re-confirm approval on logo sizes across all breakpoints and on all microsites. 

> **ESTIMATE** TBD

### What's the expected change?
- Site logo shows in header at:
-- Widescreen/Desktop: 50px
-- Tablet 38px
-- Mobile 38px (longer logos changed to 2-line stacked, for DS dev this includes: Cgov English, Cgov Spanish, DCCPS, and DCEG)

### What's the current functionality?
- Site logo shows in header at 385x38 for all breakpoints

### What's the updated acceptance criteria?
```gherkin
```

### Related Tickets
* Design Ticket https://github.com/NCIOCPL/ncids/issues/625 
* DS Dev https://github.com/NCIOCPL/ncids/issues/626

**Comment by bryanpizzillo** [comment]
## Approach
So the single logo field is pretty hardcoded into Drupal theme support. There is actually some hoops it jumps through to even setup up the logo.url setting. So I think the best approach will be to:
1. Add the 2 logos to the NCIDSHeader block config.
    2. This is going to require 2 upload fields, and those fields will be required. 
3. Set the logo.svg in the theme to be the full english logo. This is used when in maintenance mode, so we should not beak that.

**Comment by meglake** [comment]
ODE (https://ncigovcdode510.prod.acquia-sites.com/) sent to clients for review on 10/27 asking for quick review/feedback. ODE contains logos for Cgov [English], Cgov [Spanish], DCEG, DCCPS, and MyPart as well as a megamenu item with DCEG's Tools & Resources menu items.

**Comment by bennettcc** [comment]
This is complete - closing
