### ISSUE TITLE
Update new Feature Card twig templates with NCIDS styling

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform#3613]
We need to update the twig templates for the new Feature Card related paragraphs to use NCIDS styling.

- [ ] NCIDS 3 Feature Card Row
- [ ] NCIDS Internal Feature Card
- [ ] NCIDS External Feature Card
- [ ] NCIDS Multimedia Feature Card

### Links
**Parent**: #3492 
**Siblings**: #3611, #3612,  #3637

### Technical Notes
Content Modeling:
- [NCIDS Feature Card](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-feature-card)
- [NCIDS Feature Card Row](https://github.com/NCIOCPL/cgov-digital-platform/wiki/paragraph-type-ncids-feature-card-row)

**Comment by sarinapadilla** [comment]
Since we have completed the NCIDS component for this ticket, we will be able to update the feature cards with the correct styling with the actual feature card tickets (#3611 and #3612 ) so closing this ticket!
