### ISSUE TITLE
Footer: clicking "Sign Up" button with no email displays "Enter a valid email address" rather than "Invalid email address" English

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform#3623]
***Basic Information***

**Issue:**
No Issue. Display text changed to show "Enter a valid email address" instead of "Invalid email address".

**Desired Outcome:**

The current outcome is correct.

**Steps to Reproduce**
N/A

**Comment by meglake** [comment]
Recommend leaving as is and changing acceptance criteria on the original ticket.

**Comment by andyvanavery** [comment]
This is a non-issue, the system is behaving as intended.
