### ISSUE TITLE
Uploaded NCIDS Header logos are temporary and being removed

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3624]
### Issue description
Currently, Drupal is saving the logo image files attached to a NCIDS Header as temporary instead of permanent. This is likely causing the logos to disappear when viewing the site on mobile. (And sometimes desktop.) Additionally, the Akamai cache is still able to access these files even though they have been deleted from the file system.

> **ESTIMATE** TBD

### Related Tickets
* #3610

**Comment by bryanpizzillo** [comment]
After 6 hours the Drupal Cron will delete any uploaded files that are marked as temporary. The uploaded files must be registered with the file usage service in order to make sure they are not deleted.
