### ISSUE TITLE
Remove Page Options from CTHPs

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3628]
### Issue description
We are removing page options from CTHPs, as they are not content-rich pages and do not need them. They caused some headaches when trying to display them on both top and bottom in order to keep consistent with page options everywhere displaying the same way, so we decided on removing them.

> **ESTIMATE** TBD

### What's the expected change?
- Page options should not show on CTHPs.

### What's the current functionality?
- Page options show on CTHPs.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Related to Original Story Ticket: #3582 
* PR Ticket: #3626

**Comment by bennettcc** [comment]
This item is completed - closing
