### ISSUE TITLE
Cursor and Search Icon not Aligning on sitewide search

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3638]
### Issue description
1) The cursor for the search bar starts in the middle of the field when clicked before moving to the beginning (when typing begins)

> **ESTIMATE** TBD

### What's the expected result?
1) The cursor should appear aligned to the left side of the search bar

### Additional details / screenshot

https://user-images.githubusercontent.com/22639543/201970969-74658ff9-00a6-4687-b928-20251f55f52e.MP4

### Related Tickets
[* Issue #9999
* Issue #9999](https://github.com/NCIOCPL/cgov-digital-platform/issues/3279)

**Comment by meglake** [comment]
PO reviewed on 11/15/2022 and recommend this is not priority for MVP1 and recommend closing out this ticket and noting this issue on the Know Issues list. Will confirm with ODDC clients and then close ticket.

**Comment by bennettcc** [comment]
Closing this ticket - not able to reproduce on acsf dev

**Comment by meglake** [comment]
12/2 Client meeting confirmed that this should be closed and reported as a known issue. 
Note - this is only visible when you are on a mobile device, not resizing your desktop browser.
