### ISSUE TITLE
Front-end Interface Always Thinks it is in English

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#364]
When viewing Spanish content on the front-end, the interface language is picking up English. This should obviously be Spanish.

(The issue is that the interface detection methods should also use URL in addition to admin interface.)

**Comment by bryanpizzillo** [comment]
This was closed in 2ce9bca, but mis-referenced.

**Comment by BrendanBeltzNIH** [comment]
I think in general, sentient front ends should be considered a dangerous thing.
