### ISSUE TITLE
Blog RSS items appear in the order created instead of date posted

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3640]
### Issue description
When the RSS feed for a blog is generated, items are ordered according to their content ID with the "Posted Date" field acting as a tie-breaker. An effect of this is that if an item is created, but held in an "editing state" for a period before being posted, it may appear _after_ other items which have older "Posted Date" entries, but were created more recently.  (At an extreme, this can cause items with a more recent "Posted Date" to be dropped from the RSS feed because more than 10 items were created more recently.)

Fundamentally, the issue is that the `blog_rss` view in `cgov_blog` as written sorts on content ID with "Posted Date" as a "tiebreaker".

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Create a new blog post:
   1. Assign it to the Cancer Currents blog series.
   2. Set Title to "November 15 - Newer"
   3. Set Posted Date to 11/15/2022
   4. Other fields may be set to test values.
   5. Publish it
1. Create a second blog post:
   1. Assign it to the Cancer Currents blog series.
   2. Set Title to "November 2 - Older"
   3. Set Posted Date to 11/02/2022
   4. Other fields may be set to test values.
   5. Publish it
1. Go the Cancer Currents blog RSS Feed.

### What's the expected result?
- The entry titled "November 15 - Newer" appears **before** the one titled "November 2 - Older"

### What's the actual result?
- The entry titled "November 15 - Newer" appears **after** the one titled "November 2 - Older"

**Comment by navsunka** [comment]
I rearranged the sort criteria for Blog RSS view to appear in the order of date posted. To make consistency, I added Content: ID sort filter in blog posts view as well.
