### ISSUE TITLE
Section nav API parent item is incorrect sometimes

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3644]
### Issue description
> **ESTIMATE** TBD

We have a tree that looks like the below tree. The issue is that when fetching the TCGA nav, the closest parent is Research. It should be Structural Genomics.
```
NCI Organizations (SN Root)/
├─ CCG (SN ROOT, Hide in SN)/
│  ├─ Research/
│  │  ├─ .../
│  │  ├─ Structural Genomics/
│  │  │  ├─ TCGA (SN Root, Hide in Section Nav)/
│  ├─ .../
```

**Comment by bryanpizzillo** [comment]
CCG has a depth of 3, and there was a bug in depth counting to determine the parent. So the code that figures out the parent incorrectly thought that Structural Genomics would not appear in the nav.

**Comment by bennettcc** [comment]
Per 11/21 standup - closing this item. It was merged into develop branch on 11/18 - should've been closed automatically
