### ISSUE TITLE
Language Toggle Shows Link to Unpublished Alternate

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#365]
Steps:
1. Create English content, save in Draft
2. Create Spanish translation
3. Publish English content
4. View English page as anonymous visitor. You will see a link to Spanish.

Expected Result: There would be no link to Spanish until Spanish had been published.

**Comment by bryanpizzillo** [comment]
This should be reopened, this ticket was accidentally referenced in 2ce9bca.

**Comment by amydugan** [comment]
Additional Case: When viewing newly created translation in draft, language toggle tries to take you to English page that doesn't exist, so you get error implying there is something there but it won't let you see it.

**Comment by bryanpizzillo** [comment]
## Test Cases
### English Page, no translation

### English Page, unpublished Spanish translation
**URL:** http://www.devbox/test/pub-en-unpub-es-page
Expectations:
* Anon Users: No language toggle appears
* Auth+ Users: Language toggle for Español appears and links to http://www.devbox/espanol/test-es/pub-en-unpub-es-page

### English Page, published Spanish translation
**URL:** http://www.devbox/test/no-img
Expectations:
* Anon Users: Language toggle for Español appears and links to http://www.devbox/espanol/test-es/no-img
* Auth+ Users: Language toggle for Español appears and links to http://www.devbox/espanol/test-es/no-img

### Spanish Page, no English translation
**URL:** http://www.devbox/espanol/test-es/spanish-only-page
Expectations:
* Anon Users: No language toggle appears
* Auth+ Users: No language toggle appears

### Spanish Page, unpublished or Published English translation
This is **NOT** a valid use case for our editors.
