### ISSUE TITLE
Language Toggle needs ID for Glossary App Module to find.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3656]
### Issue description
> **ESTIMATE** TBD
The language toggle is breaking for the Glossary App Module. We pass in a CSS selector to find the language toggle. The selector is still set to `#LangList1 a`. which is the old toggle. Unfortunately the new toggle has a bunch of generic classes, and none would be a good replacement. We should add an ID attribute to the toggle link and call it a day.

**Comment by sarinapadilla** [comment]
This issue was fixed with commit [b5abff3](https://github.com/NCIOCPL/cgov-digital-platform/commit/b5abff370154a7cfa8b0be23cdb431985a1fca80) so closing this ticket!
