### ISSUE TITLE
Resolve issues with Translation files and translated configurations

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#366]
@bryanpizzillo - Type what you're doing here.

**Comment by bryanpizzillo** [comment]
Attempting to add translations to profile following:
https://api.drupal.org/api/drupal/core%21modules%21locale%21locale.api.php/group/interface_translation_properties/8.2.x

It is not 100% clear if this needs to be added to all themes and modules we make.

**Comment by bryanpizzillo** [comment]
Added some more workarounds. I forced the translations path in settings.php to be at the docroot root. Then I disabled downloads. This prevents an errant drupal-8.x.es.po file from being downloaded.

**Comment by bryanpizzillo** [comment]
@daquinohd Created a blt command to load up translation files. This is a more permanent temporary workaround for now. (Core still has the issue, but process wise this gets our translations in.)

**Comment by bryanpizzillo** [comment]
ACSF still will have an issue.

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo  said that he created a post update hook and post install hook that will call the drush locale update and so our translations get imported correctly into the ACSF sites. Language still sucks but we can close out this issue.
