### ISSUE TITLE
'/publications' on c.gov and all microsite mobile menu L1s show "< Back" on first open instead of "< Main Menu"

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3674]
### Basic Information

(Technical Notes below the description)

**Issue:** When opening the Mobile Menu on c.gov '/publications' all the Microsites, the top of the Mobile Menu shows "< Back" instead of "< Main Menu" when opening the first time. After maneuvering around the Mobile Menu, it will show "< Main Menu" when on the Explore Publications level. Occurs on Chrome, FF, and Edge

**Desired Outcome:** When opening the Mobile Menu on '/publications', the top of the Mobile Menu should always show "< Main Menu".

**Steps to Reproduce**
1. Go to https://www-dev-acsf.cancer.gov/publications
2. Resize to 1023px or smaller
3. Click the Mobile Menu button
4. View that at the top left of the Mobile Menu, it says "< Back" instead of "< Main Menu"
5. Click "< Back"
6. Click "Publications >" at the bottom of the list
7. View that at the top left of the Mobile Menu, it now says "< Main Menu"

**Screen Shots**
Opening the Mobile Menu the first time on the '/publications' page

![Image](https://user-images.githubusercontent.com/115043734/204867060-c2f46bf6-0d9b-46e2-9cd7-66e6e4633c03.png)

Clicking the "< Back" button

![Image](https://user-images.githubusercontent.com/115043734/204867092-e12f8cdb-55e1-4e2c-a31b-dada71738a41.png)

Returning to the Publications section by clicking "Publications >"

![Image](https://user-images.githubusercontent.com/115043734/204867139-0a3bb651-bbd2-463d-b019-8c10d9034b0a.png)

### Technical Notes

This will occur for any Section nav that is a child of the root of the mobile nav. The problem code is
```
		const label =
			this.nextMenuToFetch === null && parentNode.id === rootId
				? locale['main_menu'][this.langcode]
				: locale['back'][this.langcode];
```

In the case of a section nav, the nextMenuToFetch will NOT be null, but will be the mobile nav. We might need to pass in a baseURL, and check if the parentNode.path matches the baseURL.

**Comment by bennettcc** [comment]
Per discussion with client on 12/1, this should be backlogged - not prioritized for MVP1
