### ISSUE TITLE
Add space above the footer on app module pages

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3675]
This item was reported during ACSF-dev testing:

Page elements at the bottom of app module pages are aligning too closely to the page footer - see examples below. Please add padding above the footer on the app module pages to increase the separation between the body content and the footer.

Example link: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer
Prod version: https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer

![image](https://user-images.githubusercontent.com/22639543/205144616-c7326db6-8181-42a2-88c7-80afbd337a73.png)

![image](https://user-images.githubusercontent.com/22639543/205144715-d9f6c494-2359-4b2e-832e-a7990ba892db.png)

**App Module Pages that need the updated spacing:**

Clinical Trials Search: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/search 
Dynamic Listing Pages: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/ 
Manual Listing Pages: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/covid-19 
Dictionary of Cancer Terms: https://www-dev-acsf.cancer.gov/publications/dictionaries/cancer-terms 
Genetics Dictionary: https://www-dev-acsf.cancer.gov/publications/dictionaries/genetics-dictionary 
Drug Dictionary: https://www-dev-acsf.cancer.gov/publications/dictionaries/cancer-drug 
R4R: https://www-dev-acsf.cancer.gov/research/resources

**Comment by bryanpizzillo** [comment]
@bennettcc what about https://www-dev-acsf.cancer.gov/research/resources

**Comment by bennettcc** [comment]
Yup @bryanpizzillo @dev-rana-publicis  the R4R page is another example. It looks like all the App Module Pages need the additional space except for Sitewide search.

App Module Links:

Clinical Trials Search: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/search 
Dynamic Listing Pages: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/ 
Manual Listing Pages: https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/covid-19 
Dictionary of Cancer Terms: https://www-dev-acsf.cancer.gov/publications/dictionaries/cancer-terms 
Genetics Dictionary: https://www-dev-acsf.cancer.gov/publications/dictionaries/genetics-dictionary 
Drug Dictionary: https://www-dev-acsf.cancer.gov/publications/dictionaries/cancer-drug 
R4R: https://www-dev-acsf.cancer.gov/research/resources 

Search results looks okay to me: Search Results: https://www-dev-acsf.cancer.gov/search/results?swKeyword=cancer
