### ISSUE TITLE
Default User's Admin UI Language to English

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#368]
By default the system selects "whatever" as the preferred Admin UI Language. This means that when SPanish content is viewed, the Spanish UI will display until the user selects English as their preferred language. We should default all users to having English Selected.

**Comment by blairlearn** [comment]
The default language for the administrative pages can be set via this hook.  However, this will *NOT* change the language selections in the inline admin menu. That still follows the language in the URL.

```
function cgov_core_user_presave(EntityInterface $entity) {
  if($entity->isNew()) {
    $entity->set('preferred_admin_langcode', 'en');
  }
}
```
