### ISSUE TITLE
Missing left nav on specific PDQ

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3682]
![Image](https://user-images.githubusercontent.com/22639543/205367358-a562c072-6d94-4134-833f-0e1ce124f5b5.PNG)

Reported by ODDC Feds:

The left nav is not showing on this page on ACSF dev or test:

https://www-dev-acsf.cancer.gov/espanol/tipos/neuroblastoma/paciente/tratamiento-neuroblastoma-pdq

Currently on Prod, the left nav shows correctly: https://www.cancer.gov/espanol/tipos/neuroblastoma/paciente/tratamiento-neuroblastoma-pdq

**Comment by bryanpizzillo** [comment]
This was a content issue. The Neuroblastoma section was missing a home page.
