### ISSUE TITLE
"X" to clear search does not appear on Firefox (desktop) and Chrome/Safari (actual mobile device)

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3686]
### Basic Information ###
- Issue: The "X" used to clear search does not appear on Firefox. This occurs in both English and Spanish, as well as on Desktop and mobile. 
- Desired Outcome: For the "X" used to close search to appear when using Firefox. 

Update: during meeting with federal team on 12/2, determined scope also includes Chrome and Safari on mobile (tested on actual device) - screenshot added below

### Steps to Reproduce ###
1. Navigate to cancer.gov on Edge
2. Initiate search using the search bar
3. See that the "X" to close search does not appear

### Screen Shots ###

SAFARI: ACSF-dev (actual mobile device) - incorrect: 

![Image](https://user-images.githubusercontent.com/102998716/205348085-1a7f5fd0-3e4d-467a-9407-eba7dd54a88e.png)

FIREFOX: ACSF-dev (1050 breakpoint) - incorrect: 

![Image](https://user-images.githubusercontent.com/102998716/205118632-fa08a775-9f4d-4f99-a7b2-51d17a8e6b1f.png)

FIREFOX: ACSF-dev (420 breakpoint) - incorrect:

![Image](https://user-images.githubusercontent.com/102998716/205118966-a300237e-0cf4-4f7b-a736-cf491589f22a.png)

CHROME: ACSF-dev (1050 breakpoint) - correct:

![Image](https://user-images.githubusercontent.com/102998716/205119265-ccf0bbbf-fbc9-4794-8318-6b9f4ed05b10.png)

CHROME: ACSF-dev (420 breakpoint) - correct: 

![Image](https://user-images.githubusercontent.com/102998716/205119446-5f2743c0-f97c-4e8e-89dc-0f137e532396.png)

**Comment by arcepaul** [comment]
Firefox accounts for less than 4% of total visits to cancer.gov(mobile and desktop).  We will close this as a known issue, taking into account that this will not affect enough users to risk the introduction of more issues in other browsers in the future.

**Comment by arcepaul** [comment]
- Firefox is 0.3% of mobile visits
- desktop Firefox is 4.5% of visits
- 0.3% of visits for mobile and 4.1% of visits for desktop over the past 3mo.(Sept - Nov)

![image (1)](https://user-images.githubusercontent.com/45469809/207366447-81865e62-783e-4562-82b5-e2aa9a105341.png)

**Comment by bennettcc** [comment]
Closing this ticket - sent additional FF usage information to ODDC feds and recommended closing
