### ISSUE TITLE
Create NCIDS Feature Card 16:9 Image Style

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3690]
This task is to create the image style for the 16:9 image for the NCIDS Feature Cards.

See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images-Styles#ncids-feature-card-169 for details.

**Parent Issue:** #3637, #3612, #3611

**Comment by dev-rana-publicis** [comment]
We added upscaling to 16:9 and 4:3 images due to smaller images causing both types of feature cards to shrink and not take the 33.33% width.
