### ISSUE TITLE
Enabler: Replace Behat with Cypress

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3695]
# Replace Behat with Cypress
> **ESTIMATE** TBD

Behat is a behavioral testing language that uses Gherkin for test features, and PHP to handle step definitions. Within the BLT stack, Behat is used to do automation against an empty Drupal/cgov_site installation. You write your Gherkin scenarios, and it automates a browser, or directly inserts data into Drupal, to test the codebase. While our stack has on a small amount (3) of Behat tests, we really do not use it and instead use the Drupal Test framework.

We do have the need to create a new behat test as we have a test case that is ill-suited for the Drupal Test framework. Instead of struggling through a Behat test, we should just replace it with cypress for the following reasons:
1. The team does not have a lot of Behat experience. (It is not common outside of Drupal, and even within the Drupal community, the vast number of devs don't do Behat.
2. JS is the common language across the team and Cypress (technically cypress-cucumber-preprocessor) is the behavioral test stack across our projects 
3. Behat seems to be loosing ground within the PHP community. Even Acquia [recommends](https://github.com/acquia/blt-behat#acquia-blt-behat) to use something different.
4. Behat has a number of dependencies that actually caused us issues earlier in 2022. See issue 21 on https://github.com/acquia/blt-behat.
5. While the Drupal Test framework does handle our needs, it is actually quite slow. Moving some browser tests to cypress might decrease the amount of time (~16min) it takes for our CI tests to run. 

This enabler consists of:
1. Implementing cypress in `<repo_root>/tests/cypress`
   * This will require updating blt and ci scripts for setting up environments. (e.g., `npm ci` in the cypress folder)
   * A test command for blt should be created -- `blt test:cypress`. This should also get included when the `blt test` command is run.
      * This command should start the webserver. (it is an attribute when you create a test function -- go look at blt)
   * Cypress should be setup such that [Cypress Github Action](https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action) can be used.
   * This means that `blt test:cypress` is used locally, but github action in the CI pipeline.
      * The github action allows for parallelization
2. Porting of the existing Behat tests to cypress
3. Removal of Behat and its friends. Look at acquia/blt-behat for an idea of the dependencies that can be removed.

**Comment by blairlearn** [comment]
From branch `origin/prototype/cypress-debug-2`
1. Get hash df3b216525bd108b86fa15b30d37a54ba522360e (tip as of this writing)
2. `composer cgov-clean && composer install`
3. `docker composer --file docker/docker-compose.yml build --no-cache`
4. `docker composer --file docker/docker-compose.yml up --detach`
5. `docker composer --file docker/docker-compose.yml exec web /bin/bash`
6. (This is now in the container)
7. `blt drupal:install`
8. `blt tests:server:start`
9. `cd tests/cypress`
10. `npm ci`
11. `npx cypress run --browser chromium`

**Comment by blairlearn** [comment]
General notes:

- The message "ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read" appears to be noise caused by the lack of a physical GPU.  See issue 28061 in https://github.com/cypress-io/cypress
