### ISSUE TITLE
Citation is not displaying on hover

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3698]
### Issue description
This bug was found on 12/8:
The citation should display as text on hover when the user is hovering on the link to the citation within the text. This hover text isn't displaying on ACSF Test.

> **ESTIMATE** TBD

### Steps to reproduce the issue
1.  Go to https://www-test-acsf.cancer.gov/types/prostate/psa-fact-sheet#what-is-a-normal-psa-test-result
2. Hover over the 1st citation

### What's the expected result?
- The citation text should display on hover.

### What's the actual result?
- The citation text does not display on hover.

### Additional details / screenshot
Prod:
<img width="395" alt="Screen Shot 2022-12-08 at 4 58 31 PM" src="https://user-images.githubusercontent.com/24591940/206576206-caf3b5a6-89ff-47e3-b904-99580c5de9df.png">

ACSF Test:
<img width="328" alt="Screen Shot 2022-12-08 at 4 58 46 PM" src="https://user-images.githubusercontent.com/24591940/206576218-07309d7a-924c-44f0-9e59-b67163965da4.png">

**Comment by bennettcc** [comment]
Closing this ticket - it has been completed
