### ISSUE TITLE
Technical Item: Create Behat Tests for Article

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#370]
## Description 

Article has a complicated body and needs automation tests to ensure continued working of sections with translations and workflow.

Initial test:
1. Create an Article in English
2. Add 2 sections with content
3. Leave in Draft
4. Create Spanish Translation
5. Update the 2 sections (the english content is pull over with the translation)
6. Leave in Draft
7. Edit English and add a section
8. Save in Review
9. Make sure English has the 3 sections and Spanish has only 2
10. Publish the English
11. View English in incognito window (as a visitor to the site
12. Edit Spanish and publish it.
13. As incognito view Spanish and make sure it has only 2 sections
14. Add another section to English, and save to edit, then to publish.
15. In the incognito window, check english has 4 sections and Spanish has 2
16. Edit Spanish and add in the other two sections
17. Publish Spanish make sure it appears.

(This would also be a good place to test Language Toggle between Articles working)

**Comment by VictoriaSunNIH** [comment]
At this point in time we need a larger test strategy, and have some regression tests in place.
