### ISSUE TITLE
Searching a long term with a definition and pronunciation wraps the pronunciation over the definition

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3702]
### Basic Information ###
- Issue: Searching a term that has a definition and pronunciation that is longer than the width of the container will cause it to wrap and be overlaid on the definition. This occurs with extremely long phrases at 1400px, but the overlap increases as the breakpoint decreases. Additionally, the spacing in the Dictionaries is impacted. The speaker button will overlap a letter above it that has a lower tail (e.g. "g"), and when the pronunciation is long and wraps, the spacing between the pronunciation and the definition is reduced to nearly zero. This has been seen occurring on Chrome, Edge, and FF.

- Desired Outcome: The distance between the searched term and pronunciation should remain the same on a single line as when the pronunciation wraps to the second line for both the Global search function and the Dictionaries. The speaker button icon should not overlap the search term on the Dictionaries.

### Steps to Reproduce ###
1. Go to https://www-test-acsf.cancer.gov/
2. Click on the Search text box in the upper right of the page
3. Type in "atypical glandular cells of undetermined significance"
4. Click "Search"
5. Observe that the Speaker button and the pronunciation overlap the definition at all breakpoints.
6. At a smaller breakpoint (i.e. 480px) the pronunciation and definition are significantly overlapping

1. Go to https://www-test-acsf.cancer.gov/publications/dictionaries/cancer-terms/
2. Click on the "Enter keywords or phrases" text box in the middle of the page
3. Type in "atypical glandular cells of undetermined significance"
4. Click "Search"
5. Observe that the Speaker button overlaps the "g" in "significance" at the 1400px breakpoint
6. Observe that the desired spacing between the pronunciation and the definition is gone when the pronunciation wraps (occurs at the breakpoint <619px)

### Screen Shots ###
Searching term at 1400px breakpoint.

![Image](https://user-images.githubusercontent.com/115043734/207100407-0b3aae1a-9b43-4762-ae37-f38513bfaa79.png)

Searching term at 480px breakpoint.

![Image](https://user-images.githubusercontent.com/115043734/207100632-85cb4e8e-dadf-4b39-a369-240b783b28cb.png)

Dictionary of Cancer Terms at 1400px

![Image](https://user-images.githubusercontent.com/115043734/207101628-aba366e0-a7f8-4f91-97e8-3f77f9516930.png)

Dictionary of Cancer Terms at 480px

![Image](https://user-images.githubusercontent.com/115043734/207101546-0525290d-ed88-4104-8278-6783ee66c309.png)

**Comment by bennettcc** [comment]
Closing this ticket - it has been completed
