### ISSUE TITLE
Inline Link Outline overlapping on multiline links on Firefox

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3704]
### Basic Information ###
- Issue: When clicking on an inline link that goes more than one line, the outline of the link selection overlaps itself. This only occurs on Firefox, and happens on all sites that have multiline links. Certain multiline links have enough vertical space between the lines so it is not extremely noticeable, however, the examples shown below have a small vertical space between lines.
- Desired Outcome: Multiline links should have a single outline box, like it appears in Chrome and Edge. See image below.

![Image](https://user-images.githubusercontent.com/115043734/206794754-d6034b13-8576-493d-a1e5-82a92dcbe92f.png)

### Steps to Reproduce ###
1. Open Firefox
2. Go to https://www-test-acsf.cancer.gov/news-events/cancer-currents-blog
3. Click the "Bariatric Surgery May Reduce the Risk of Some Common Cancers" link, so that the outline box can be viewed
4. Observe that the outline box of the two lines are overlapping instead of making a single box, like the image shown above.
5. This behavior also occurs at the following links: https://www-test-acsf.cancer.gov/rare-brain-spine-tumor/blog (the titles of any of the blogs that are long enough for multiple lines). https://www-test-acsf.cancer.gov/rare-brain-spine-tumor/tumors/diffuse-midline-gliomas (occurs slightly under the "Open Clinical Studies for Diffuse Midline Gliomas" section near the bottom for any multiline link at the 480px breakpoint).

### Screen Shots ###

Same page as the image above, but on Firefox with the overlapping outlines on Cancer Currents Blog

![Image](https://user-images.githubusercontent.com/115043734/206796369-79ac3fa9-7c08-4351-9a6e-74dbe98c6653.png)

Occurrence on the NCI-CONNECTions page with 3 lines

![Image](https://user-images.githubusercontent.com/115043734/206796525-98f3041c-016a-4e55-995c-ab1d9fa17098.png)

Slight occurrence as described in Step 5

![Image](https://user-images.githubusercontent.com/115043734/206796651-efd70caf-e0f5-4e54-a53a-fcc802f716ea.png)

**Comment by bennettcc** [comment]
Per discussion with @dev-rana-publicis - this ticket shouldn't move forward to be worked on. Firefox's focus for wrapped text working as expected - firefox does not apply focus to the block of text but rather at the individual line level.  The focus we're seeing on cancer.gov is consistent with what is seen on all other sites using firefox (ex: https://nexus.od.nih.gov/all/)

@bennettcc to confirm with client then close ticket.

**Comment by andyvanavery31** [comment]
Since this is a Firefox behavior this will be closed.
