### ISSUE TITLE
Refactor high charts code to load CSV data from content

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3713]
### Issue description
The high charts functionality for the Fact Book uses data which is encoded directly into the JavaScript files. Although this was expedient when the charts went live several years ago, it means that all updates and corrections to the data require developer time and a software release.

Link to High chart - https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards 

SPs
- First: 3pt
- Subsequent: 1pt 

Impacted files include (this list may be incomplete):
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/aids-funding.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/bypass-appropriations.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/grants-contracts.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-amount.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-bar.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-extramural.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/html-nrsa.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/kawards-pie.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/management-fund.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/moonshot-obligations.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/number-rpg-awards.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/obligations-mechanism.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/program-structure.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rms-funding.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-cost-per-award.js
- [ ] docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/charts/library/rpg-funding.js

Next steps:
1. Review SOP - https://nih.sharepoint.com/:t:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Standard%20Operating%20Procedures/deploy-acsf-site-to-local.md?csf=1&web=1&e=jhXwx8
2. Review affected files and update as needed
3. Define an approach 
4. Implement approach

> **ESTIMATE** TBD

### What's the expected change?
- The data should be loaded from CSV files stored as content in the CMS.

### What's the current functionality?
- The data is hard-coded in .JS files which are part of the front end code.

### What are the updated requirements?
- 3008 . CSV files uploaded to the CMS will provide the data for an individual HighChart .JS file used in the Factbook.
    - 3008.1. The CDEConfig object shall have a property that contains for the base URL for data files used by Factbook charts.
        - 3008.1.1. The CDEConfig object shall have a "ChartData" property.
        - 3008.1.2. The "ChartData" property shall have a "Factbook" property.
        - 3008.1.3. The "Factbook" property shall have a "BaseUrl" property.
            - 3008.1.3.1. The "BaseUrl" property will be a string.
            - 3008.1.3.1. The "BaseUrl" property value will be the base URL for all files uploaded to the CMS containing chart data.
        - 3008.1.4. The "Factbook" property shall have a "DataType" property.
            - 3008.1.4.1. The "DataType" property will be an object with two strings, "json" and "csv"
    - 3008.2. The individual HighChart .JS file shall hardcode the file name associated with the CMS file containing CSV data for the chart.
    - 3008.3. The individual HighChart .JS file shall use the "BaseUrl" value and the hardcoded file name to determine the path for the CMS file containing CSV data for the chart.
    - 3008.4. The individual HighChart.JS file shall read in the CSV data in the file and create the chart using that data.

### What's the updated acceptance criteria?
```gherkin
Scenario: CDEConfig object is updated with ChartData parameter

Given a user is viewing a page with a HighChart
When the user views the page source
Then the CDEConfig JSON object literal has a property "ChartData"
  And the value for the "ChartData" property is an object with the property "Factbook"
  And the value for the "Factbook" property is an object with properties "BaseUrl" and "DataType"
  And the "BaseUrl" property is a string with the base path where the HighChart data files live (update this with the base URL)
  And the "DataType" property is an object with two strings, "json" and "csv"
```

```gherkin
Scenario: Individual chart JS files use hardcoded CSV file names to load data

Given a developer creates a new HighChart .JS file
  And the .JS file has a hardcoded value with the filename containing the CSV data
  And the user uploads a CSV file containing the data to the CMS
When the user views the page containing the chart
Then the chart will display the data in the CSV file
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by laurelthrash** [comment]
Closing this ticket after completion of #3761. No longer need this ticket which uses CSV data.
