### ISSUE TITLE
Change Request to YouTube Video Player

### ISSUE THREAD

**Issue by meglake** [NCIOCPL/cgov-digital-platform#3747]
### Issue description
*Description of the issue.*
Please look at the platform's YouTube video player used today and:

1.  Make the JS only load when a video is on the page
     * This means it will need to be registered in ncids_trans.libraries.yml
     * The video js will need to be made into an entry point. 
3. Move it out of legacy JS and copy to ncids_trans  

> **ESTIMATE** TBD

### Related Tickets
This request is in relation to the video component for home and landing pages in R2.1, as well as fixing performance issues on pages without video.

**Comment by arcepaul** [comment]
per @meglake: As part of R2.1 video component work, would it be possible to also fix the bug of the thumbnail not updating if it's changed on YouTube? Or is that something totally separate?

**Comment by arcepaul** [comment]
Closed in lieu of #3888
