### ISSUE TITLE
SER Requirements are Confusing

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#375]
The requirements state that this should allow multiple selections, but each of the current items are mutually exclusive. (e.g. How can something be Include in Search and Exclude from Search at the same time?)

Was this mean to be dropdown select allowing only a single choice?

https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#search-engine-restrictions

**Comment by nicolecrom** [comment]
Originally we had more options on this and the dropdown with multiple options was a remnant from that. Here is the latest update based on @lburack email

We should only allow one to be selected. It can be a checkbox or radio button (if it has not yet been built).

Include in search would be selected by default, with the option to switch to exclude. If a checkbox is used, it should only allow one item to be checked. 

I'll update the wiki.

**Comment by lburack** [comment]
I updated the Common Fields page so Search Engine Restrictions type is now a checkbox. 
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#search-engine-restrictions
