### ISSUE TITLE
Spike: Investigate Feature Card Image Issue Ahead of Widescreen Launch

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3750]
## In order to fix the issue with the DCEG feature card images ahead of the widescreen release, a designer needs to review the current images and determine the root cause.

It was discovered that on ACSF-dev (contains code for widescreen), that the feature card images on DCEG's home page are varying sizes.

> **Estimate** *TBD* 

### Expected Deliverables:
- A hypothesis for what might be causing the issue
- A path forward with specific steps to remedy the issue 

### Steps to Reproduce:
1. Navigate to DCEG's home page on ACSF-dev: https://dceg-dev-acsf.cancer.gov/
2. See that the feature card images are not the same size and do not all fit within the card

![DCEG Home Page - Feature Card Image Issue](https://user-images.githubusercontent.com/102998716/214964515-494af0fb-6f43-49a7-a892-6b746d772e75.jpg)

### Results of Spike
- Enter the information, or links to any (non-sensitive) files with the findings here

***NOTE: a single story point is about 1 day.  A spike should not go on for than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.**

**Comment by laurelthrash** [comment]
Requested larger images from DCEG. Confirmed these are not blockers for the upcoming widescreen deployment.

**Comment by bennettcc** [comment]
@laurelthrash DCEG provided the two images at the needed minimum size; they've been replaced on Prod so they won't be issues when the widescreen package is release. This ticket is complete and can be closed, thanks!

**Comment by laurelthrash** [comment]
@bennettcc - excellent! Thank you for making that update. Closing this ticket now.
