### ISSUE TITLE
Upload TTC SVG Logo to microsite

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3771]
### Upload TTC Blended SVG Logo on TTC microsite instance to replace current NCI logo

TTC Website - http://techtransfer-cms.cancer.gov/ 

#### Logo stored on Teams : https://nih.sharepoint.com/:u:/r/sites/NCI-OCPLTTCMigration/Shared%20Documents/General/TTC%20Site%20Migration/IA%20%26%20Content%20%26%20Design%20Resources/Design/TTC%20Logo%20Assets.zip?csf=1&web=1&e=wbAJ1M

**- TTC Logo Assets --> Web --> SVG Files --> TTC Logo Color**

### AC
Scenario - User goes on the TTC website
Given i go on the TTC Microsite ( http://techtransfer-cms.cancer.gov/ )
When i navigate through the website
Then i should see the TTC logo at the top right corner of the site

### Notes

* Logo has to be on the site by end pf february

**Comment by andyvanavery31** [comment]
These items are no longer stored in source control.
