### ISSUE TITLE
Bug: Extra Style Loaded on cgov Mobile with 2 "ul"

### ISSUE THREAD

**Issue by andyvanavery** [NCIOCPL/cgov-digital-platform#3777]
### Issue Description
On both prod and ODE for cancer.gov, if the user goes to mobile (breakpoint < 765px), and then back up > 765px, an extra style is loaded. Then the last item in the list will be pushed outside of the container. See attached screenshots.

### Steps to reproduce the issue

1.  Go to https://ncigovcdode534.prod.acquia-sites.com/
2. Reduce the size of the window so the width is less than 765px
3. Increase the size of the window so the width is greater than 765px
4. See that the last link in the "Your Guide to Cancer" section is pushed outside of the container
5. This occurs on product as well, but it does not have 2 'ul', so it doesn't immediately appear.

### What's the expected result?
- The last link should remain within the container

### What's the actual result?
- The last link is pushed outside of the container

### Additional details / screenshot
ODE
![image](https://user-images.githubusercontent.com/115043734/219786201-c30895d0-3146-4057-8c27-0d25e579ba38.png)

![image](https://user-images.githubusercontent.com/115043734/219786242-cfb7cbbf-5960-4058-bd39-5b8ec465546b.png)

Prod
![image](https://user-images.githubusercontent.com/115043734/219786264-b759be0e-641a-4b91-83a6-f655fe096775.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This issue is fixed since R2.1 and the update of our home page to use new NCIDS components.
