### ISSUE TITLE
Technical Item: Create Date Formats (in English and Spanish)

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#378]
## Description 

The most common date format is the following:
* English: April 29, 2015
* Spanish: 29 de abril de 2015

*  Create the following: 
    * Create a new English Date Format 
       * Machine Name: cgov_ui_date
       * Label: Cgov UI Date
       * Format: `F j, Y` - although if someone other than I picked up this ticket, then you should have figured that out. :P
       * Language: English
    * Translate the format
       * Format: `j \d\e F \d\e Y`
       * Language: Spanish
    * Create tests
*  Figure out:
    * How do you translate the months and make them lowercase?

**Comment by amydugan** [comment]
@daquinohd - is this the Spanish dates update that was part of one of your Blog PRs?

**Comment by amydugan** [comment]
Remove the translated config now that the translation file contains the translated string. @daquinohd
