### ISSUE TITLE
Bug: Multiple Image Upload Timeout

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3781]
### Issue description
Uploading multiple images at the same times causes system timeout. 

This issue was discovered while testing the PHP 8 upgrade deployment. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Log into CMS
2. Create new content page or update an existing page
3. Upload multiple images at the same time

### What's the expected result?
- Users should be able to upload multiple images without system timeout

### What's the actual result?
- System timeout when multiple images are uploaded at the same time or multiple users upload images at the same time

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
This is because Clamscan AV is exhausting resources. We need to remove Clamscan AV Drupal Module as it is too fragile.

**Comment by laurelthrash** [comment]
On 03/02, applied configuration to production to prevent this issue on live site. This ticket intended to apply the configuration change across all environments in the codebase.
