### ISSUE TITLE
Enabler: Turn off ClamAV 

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3795]
#Disable clamAV in production

*Background
UPDATE AFTER v2.3.0: There are a lot of memory issues using the ClamAV Drupal module. Each file upload requires 1GB of RAM for the scan. Our dev/test tier consistently has around .8GB free. Production usually has only around 1.8GB free. Using ClamAV was not a scalable approach and we need to identify a different approach to handling this. See https://github.com/NCIOCPL/cgov-digital-platform/issues/3781 for more information on the issue.

### Sub-Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

**Comment by blairlearn** [comment]
[The module was deactivated on 3/2/2023](https://github.com/NCIOCPL/cgov-digital-platform/issues/3781#issuecomment-1458856865) and disabled in b0c93d89047b6791beaac8d18bc2d5249e623bbf (ticket #3781).

The module will be completely removed by #4098.
