### ISSUE TITLE
A11y: Back to top needs label for mobile/tablet breakpoints

### ISSUE THREAD

**Issue by arcepaul** [NCIOCPL/cgov-digital-platform#3812]
At mobile and tablet breakpoints, the Back to Top link in the footer replaces the text with an arrow up icon with no discernable text for screen readers to announce its presence.  Addition of an aria label will 

> **1** 

### Steps to reproduce the issue

1.  open any page on cancer.gov at a non-desktop breakpoint
2. Notice the back to top button in the bottom right hand corner
3. Run axe-dev tools or use a screenreader to see that there is no text in the button for the screen reader to read out.

### Remediation steps
1.  Modify the back to top link in the footer rawHTML, adding the appropriate aria-label:
```
<a href="#top" aria-label="Back To Top"><span>Back To Top</span></a>
```

**Comment by laurelthrash** [comment]
Paul A. to verify ACSF-test.

**Comment by arcepaul** [comment]
verified presence on acsf-test for both english and spanish

**Comment by laurelthrash** [comment]
@arcepaul the updates have been made in production to the English and Spanish footer. Will you please verify and then close out this ticket? 

Internal note: the code equivalent for Spanish is `<a href="#top" aria-label="Volver arriba"><span>Volver arriba</span></a>`

**Comment by andyvanavery31** [comment]
Aria label has been added in English and Spanish.
