### ISSUE TITLE
Factbook High Chart Mobile Breakpoint Issues

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3814]
**Description:** 

During manual testing for the initial Factbook enhancement updates (#3761), the below issues was identified. At mobile breakpoint for the "Research Career Awards 'K' Program," : 
1. the legend text is centered and thus legend text wraps (see screen shot)
2. title of the chart overlaps with the mobile menu (see screen shot)

At the time of testing, these issues were not occurring in production. Determined that these issues were not substantial enough to prevent release of #3761. Creating this ticket to retroactively address these two issues. 

Prod URL: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards

**Steps to reproduce:** 
1. Navigate to the "Research Career Awards 'K' Program," chart in production (link above)
2. Reduce to mobile breakpoint
3. See two issues mentioned above

**Screenshots of issue:** 
![image](https://user-images.githubusercontent.com/102998716/229544192-c64d69a5-aaca-42c7-a310-beaa9d899282.png)
![image](https://user-images.githubusercontent.com/102998716/229543950-6aa79990-399d-4e7a-a9da-181dbc7b465e.png)
![image](https://user-images.githubusercontent.com/102998716/229544090-ce218513-a8aa-4079-a241-70cd7f07c72e.png)

**Comment by laurelthrash** [comment]
Determined on 09/25/23 with internal Factbook team that this ticket will be deprioritized. Intention is to leave this ticket open to reference this existing issue, but acknowledge it is not presently a priority to fix. Tagging @andyvanavery31 to add this ticket to the general backlog. Cc: @santwuma @sarinapadilla

**Comment by alinai** [comment]
At mobile breakpoint the chart on https://www.cancer.gov/about-nci/budget/fact-book/data/obligations appears cut-off when the purple area is clicked. cc: @seyilonge-nci , @laurelthrash

**Comment by alinai** [comment]
@seyilonge-nci , the legend text wrapping issue (issue#1) exists across all devices (simulated) and on resizing browsers to mobile breakpoint.

**Comment by alinai** [comment]
For issue#2, I am not seeing the title overlapping the menu anymore. Please see the screen-shot below to verify how close the title gets to the menu in different devices (simulators): 
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/5a61db9e-b893-4c0b-8429-af62bad243e6)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/66922568-9b64-419d-9ec1-eb882197a092)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/179440cd-2f6e-4b93-82ea-e64be48b804f)

**Comment by alinai** [comment]
cc: @KateMashkinaNIH
