### ISSUE TITLE
Confirm Specs on Common Fields

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#382]
## Need to resolve a few questions about some of the common fields specs:

- If a field does not have a `Tooltip text` field specified, does that mean we should leave that field blank, or should all fields have tips?  (eg: Meta Description, Promotional Image, Pretty URL, etc)
- `Search Engine Restrictions` is currently listed as a Text List with 2 options: [Include in Search, Exclude from Search]
  - If these are going to be the only two options, this field should probably be a Boolean (checkbox) with the label `Include in Search` and default to checked.
  - If there are going to be different options for internal site search vs external Internet search, this should probably be split into two Boolean fields, `[X] Include in Site Search` and `[X] Include in Internet Search`, rather than having a 4-option Text List.
- `Public Use` is currently a checkbox, but Cardinality = Infinite.  This should be a single value, right?
  - Are there various licensing schemes that might be needed that could be specified with this field?  eg, Public Domain, Creative Commons, etc?
- `Syndicate` should probably be a checkbox with the label like `[X] Syndicate` instead of the two text list options [`Syndicate`, `Don't Syndicate`], unless there are other options expected in the future.
- `Pretty URL`, `Syndication Keywords` need Field names defined.

**Comment by nicolecrom** [comment]
* Tooltips may be left blank for self explanatory fields
* Search Engine Restrictions - There will be only 2 options so a checkbox or radio dial will be fine. I've updated the wiki
* Public Use - I would assume but @lburack please confirm
* Syndicate - I believe this is related to SER (both were going to be one field originally and have remnants from that change) so yes it can be a checkbox or radio dial
* I will add the field names into the wiki

**Comment by bgnih** [comment]
@lburack @VictoriaSunNIH @nicolecrom Thanks for the clarifications.  Was there a final decision on the Public Use field?

@bryanpizzillo Shall I create a ticket to change the SER/Syndicate fields to a checkboxes?  Should it be added to the current sprint or put on the backlog?

**Comment by VictoriaSunNIH** [comment]
@bgnih  - Public Use should be a single use only, and cardinality should be 1.  This is a field that can appear on content types (but whether or not it defaults to being "checked" will depend on the content type.)  I will update it on the common fields page.

For the SER/Syndicate fields to checkboxes, please create a ticket in the current sprint.  Thank you!

**Comment by VictoriaSunNIH** [comment]
Note that Syndication fields have been moved to a later sprint (along with the possible use of a HHS Syndicate module).

**Comment by amydugan** [comment]
@bgnih , do you still need info on this from @lburack ?

**Comment by bgnih** [comment]
@VictoriaSunNIH Have the requirements been updated to be in line with this?  If so, I think we can close this ticket.
