### ISSUE TITLE
Create YAML content for testing usa-prose

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3823]
In order to test `usa-prose`, we need to create a YAML page to test all of the WYSIWYG content that can can be in `usa-prose` sections.

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
@sarinapadilla this has nothing to do with usa-prose. This is just YAML content for testing the Drupal WYSIWYG "HTML" features.
