### ISSUE TITLE
Issue with Favicons for Spanish Content

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3825]
### Issue description
Issue initially reported via Jira (https://tracker.nci.nih.gov/browse/CGOV-18528).

Drupal favicon displays instead of the NCI branded favicon on Spanish content for some Google searches with Spanish-language results.

NOTE: I am not sure if this is expected behavior. I have logged this as a change request, but it may in fact be a bug. 

> **ESTIMATE** TBD

### What's the expected change?
- NCI favicon displays for cancer.gov/espanol pages

### What's the current functionality?
- Drupal favicon displays for cancer.gov/espanol pages
- Example: https://www.google.com/search?q=que+es+la+mca+para+tratar+el+cancer

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
Screenshot #1 
![image](https://user-images.githubusercontent.com/102998716/232891135-7d2a05a0-979f-4c13-bf11-492d9ee3366b.png)

Screenshot #2
![image](https://user-images.githubusercontent.com/102998716/232891401-43dab85f-4e59-40d5-bd84-7df5f3570f67.png)

**Comment by santwuma** [comment]
Unable to reproduce issue. NIH favicon is showing as expected.

@laurelthrash
