### ISSUE TITLE
Blog Series RSS feed breaks when user adds a blog without promo image 

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform#3827]
### Issue description
*Description of the issue*
It was discovered, that when user creates a blog post without a promo image and adds it to cancer-current series, rss feed breaks and returns 500 

Here is an entry from log
![Screenshot 2023-04-20 at 2 53 20 PM](https://user-images.githubusercontent.com/67657582/233485838-31f780db-bd4d-45d8-9174-8200629ee146.png)

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Create a new blog post, add it to cancer currents series,  fill out mandatory fields and DONT add promo image
2.  navigate to /PublishedContent/RSS/syndication/rss/blog-series.rss/### where ### is content ID
3. you get The website encountered an unexpected error. Please try again later.

### What's the expected result?
- it should not bring down RSS feeds for blog series

### What's the actual result?
- 

### Additional details / screenshot
- ![Screenshot]()
<img width="1023" alt="Screenshot 2023-04-20 at 4 55 36 PM" src="https://user-images.githubusercontent.com/67657582/233486411-c4871d63-6d69-46f2-8590-6d1aa06d691c.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
@KateMashkinaNIH Doesn't Blog Post have a `field_image_article` (aka Lead Image) field too? If so the expected above should call out our fallback rule.
