### ISSUE TITLE
Spanish Media Items are not viewable in the CMS

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3828]
### Issue description
*Whether a file is translated or not, you are not able to view the Spanish file when logged into the CMS.*

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  In the [Media Overview](https://www-cms.cancer.gov/admin/content/media?name=&type=cgov_file&status=All&langcode=en), look at English Files
2. Click on any Media Item blue Media Name link) and you’ll be taken to the file within the www-cms URL
Files do have URLs so this is expected
3. Now filter the [Media Overview to see only Spanish Files](https://www-cms.cancer.gov/admin/content/media?name=&type=cgov_file&status=All&langcode=es)
4. Click on any Media Item blue link and you’ll be taken to a /media/#### URL that gives an error.  You should be taken to the file within the www-cms URL, just as you are with the English version.

This occurs with all Spanish files, whether the file is a translation of an English version or it was created as its own media item (not a translation)

### What's the expected result?
- Spanish files, translated or not should be viewable in the CMS

### What's the actual result?
- Spanish files, translated or not are not viewable in the CMS

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Unable to reproduce this issue.
