### ISSUE TITLE
Enabler: cgov_admin theme must change to use claro base theme

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3829]
# cgov_admin theme must change to use claro base theme
> **ESTIMATE** TBD

The Drupal admin them we all know and love, seven, is replaced with the claro theme in D10. In order to be able to upgrade to Drupal 10, we must change our cgov_admin theme to use the new claro theme. The theme changes lots of colors, adds whitespace, and does some other funky things, but for the most part, everything stays in the same place. So the biggest part of this story may be updating training materials.

### Changes
* Content landing page
  * Breadcrumb moves to top of content window
  * Filter button is in line with filters (Title, Content type, Published Status, Language)
* Edit content items
  * If multiple paragraphs added, each paragraph displays collapsed in an accordion
    * NOTE: CTHP Cards are not in accordion and therefore all display expanded
  * Each item displays paragraph name, field values on paragraph (until no more characters can be displayed and it truncates), Edit button, and dropdown to Remove or Duplicate
  * Clicking Edit expands the accordion section for the paragraph to view and edit fields
  * Clicking Collapse closes the accordion section for the paragraph
  * Clicking Remove immediately deletes the paragraph (no Confirm Removal button)
  * Clicking Duplicate creates a duplicate paragraph with a caution triangle next to the Heading (???)
  * Show Row Weights displays at the top right of the accordion
  * Clicking Show Row Weights displays row weights next to each accordion section (starts at 0)
  * Clicking Hide Row Weights removes them from display next to each accordion section

### Acceptance Criteria
**Visiting the Content Page**
```gherkin
Scenario: A user visits and interacts with the Content page on Drupal
  Given a user goes to an active ODE site
    And the user logs in as an editor
    And the user goes to the Content page
  Then the user shall see that the breadcrumbs appear at the top left of the content window
  When the user clicks on any of the breadcrumbs
  Then the user will be redirected to the respective page as indicated by the breadcrumb
  When the user returns to the Content page
  Then they will see the Filter button is on the same horizontal line as the Filter options (Title, Content Type, Published Status, and Language)
```

**Editing Content**
```gherkin
Scenario: A content editor edits existing content on Drupal
  Given a user goes to an active ODE site
    And the user logs in as an editor
    And the user goes to the Content Page
    And the user selects the "Edit" button under Operations in the main table of available content
    And the user is redirected to the page of the "Edit <Content Type> <Title of Content Page>" page
  Then the users will see a language dropdown selection
    And the Contents section will contain the paragraphs
  When the Contents section contains multiple paragraphs
  Then the paragraphs will appear collapsed in an accordion
    And the collapsed paragraphs will display the paragraph name, field values on paragraph (until no more characters can be displayed and it truncates(, an Edit button, and a dropdown to Remove or Duplicate
  When the user clicks on the Edit button on a collapsed paragraph
  Then the paragraph will expand
    And the fields can be edited
  When the user clicks on the Collapse button that replaced the Edit button on expansion
  Then the paragraph will return to the collapsed state
  When the user is viewing a CTHP Cards
  Then they will not be included in the collapsed paragraphs section
    And they will appear in the expanded state
  When a user clicks the Remove button on a paragraph
  Then the item will immediately be deleted
  When the user clicks the Duplicate button on a paragraph
  Then an identical paragraph will appear will appear in the expanded state
  When a user clicks Collapse on the Duplicate paragraph
  Then a yellow caution icon will appear to the right of the paragraph title
    And on hover the icon will indicate to the user that they have unsaved changes on the paragraph
  When a user goes to the top of the Contents section
  Then the Show row weights button will appear at the top right of the section
  When the user clicks on the Show row weights button
  Then a column will be added to the paragraphs shown with the heading of "Order"
    And each paragraph will have a dropdown selection under "Order" starting with an index of 0
    And each subsequent paragraph will have a sequentially numbered index increasing by one from the previous paragraph
    And on selection of the dropdown, the user will be able to change the order index value of the paragraph
    And the four-directional arrow that allows the user to rearrange the order of the paragraphs on the left side of the collapsed paragraph section will disappear
  When the user clicks on the Hide row weights button at the top right of the Contents section, that replaced the Show row weights button
  Then the paragraphs will revert to their initial state that was shown prior to clicking Show row weights
  When a user views all other components of the page
  Then the names and functionality of the fields and components on the page will match the Drupal site prior to the theme change with changes made to the style of those other fields and components 
```

### Dependencies:
* #3484 - The newest version of paragraphs includes [3175491](https://www.drupal.org/project/paragraphs_asymmetric_translation_widgets/issues/3175491) which is needed for the Claro theme.

### Resources:
* Original notice: https://www.drupal.org/node/3087157

### Sub-Tasks
- [ ] Change `cgov_admin.info.yml` to use `claro`
- [ ] Make sure that existing sites do no break

**Comment by santwuma** [comment]
Based on how Claro looks, we need to determine if it's still the best choice. May consider other alternatives.

**Comment by santwuma** [comment]
Will need update to training materials

**Comment by alinai** [comment]
@sarinapadilla , please confirm if the requirements above looks good to you for this ticket. cc: @KateMashkinaNIH , @santwuma , @navsunka

**Comment by alinai** [comment]
@sarinapadilla , for this requirement, 
```
When a user clicks the Delete button on a paragraph
  Then the item will immediately be deleted
```

The button name is "Remove". Is it expected?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/07605bb8-b934-4ae5-8cdb-0435727ea5e9)

**Comment by alinai** [comment]
@sarinapadilla , does the text that appears on hovering on the Caution Icon looks good to you?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/3eea8431-d896-4499-b866-a7b2df539b35)

**Comment by alinai** [comment]
@sarinapadilla , for the following requirement, I can see the third text field, 4th text field, 5th text field as well along with the the paragraph name, the first two text fields. Is it expected?
`[And the collapsed paragraphs will display the paragraph name, the first two text fields (truncated), an Edit button, and a dropdown to Remove or Duplicate]`
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/1a40e3d6-96da-4b11-8cc4-20a1b5c1500d)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , for this requirement,
> 
> ```
> When a user clicks the Delete button on a paragraph
>   Then the item will immediately be deleted
> ```
> 
> The button name is "Remove". Is it expected? ![image](https://user-images.githubusercontent.com/28455973/271362779-07605bb8-b934-4ae5-8cdb-0435727ea5e9.png)

Yes, it is Remove and not Delete

**Comment by sarinapadilla** [comment]
> @sarinapadilla , does the text that appears on hovering on the Caution Icon looks good to you? ![image](https://user-images.githubusercontent.com/28455973/271375243-3eea8431-d896-4499-b866-a7b2df539b35.png)

Yes this is correct

**Comment by sarinapadilla** [comment]
> @sarinapadilla , for the following requirement, I can see the 3rd text field, 4th text field, 5th text field as well along with the the paragraph name and the first two text fields. Is it expected? `[And the collapsed paragraphs will display the paragraph name, the first two text fields (truncated), an Edit button, and a dropdown to Remove or Duplicate]` ![image](https://user-images.githubusercontent.com/28455973/271393449-1a40e3d6-96da-4b11-8cc4-20a1b5c1500d.png)

@alinai that is expected, I was looking at a different paragraph that only had two fields when I wrote that requirement. So the collapsed row will display all of the field values in the order they display on the paragraph, until it is truncated. What is displaying is expected.

**Comment by alinai** [comment]
Thanks for the clarification @sarinapadilla

**Comment by alinai** [comment]
Content landing page
Breadcrumb moves to top of content window.....PASS
Filter button is in line with filters (Title, Content type, Published Status, Language)....PASSed ODE
Edit content items......PASSed ODE
If multiple paragraphs added, each paragraph displays collapsed in an accordion....Verified this w.r.t spreadsheet
NOTE: CTHP Cards are not in accordion and therefore all display expanded
Each item displays paragraph name, field values on paragraph (until no more characters can be displayed and it truncates), Edit button, and dropdown to Remove or Duplicate.......PASSed ODE
Clicking Edit expands the accordion section for the paragraph to view and edit fields......PASSed ODE
Clicking Collapse closes the accordion section for the paragraph......PASSed ODE
Clicking Remove immediately deletes the paragraph (no Confirm Removal button)...PASSed ODE
Clicking Duplicate creates a duplicate paragraph with a caution triangle next to the Heading (???) .......
Show Row Weights displays at the top right of the accordion....PASSed ODE
Clicking Show Row Weights displays row weights next to each accordion section (starts at 0) ...........PASSed ODE
Clicking Hide Row Weights removes them from display next to each accordion section......PASSed ODE

**Comment by alinai** [comment]
Visiting the Content Page: **PASSED**

Scenario: A user visits and interacts with the Content page on Drupal
  Given a user goes to an active ODE site
    And the user logs in as an editor
    And the user goes to the Content page
  Then the user shall see that the breadcrumbs appear at the top left of the content window
  When the user clicks on any of the breadcrumbs
  Then the user will be redirected to the respective page as indicated by the breadcrumb
  When the user returns to the Content page
  Then they will see the Filter button is on the same horizontal line as the Filter options (Title, Content Type, Published Status, and Language)

**Comment by alinai** [comment]
@sarinapadilla , should I see the yellow caution cone when I click the "Collapse" button? I see the yellow caution cone when user clicks "Collapse" on the Duplicate paragraph as stated in the requirement but want to confirm if I should see the yellow caution cone at the step highlighted below?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/ecd81a3a-4767-4ef2-8093-0f661a7ed430)


![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/b47d1e93-7d13-48f3-bd0d-bde0811afb16)

**Comment by alinai** [comment]
@sarinapadilla , when I click "Show row weights" in one of the Content (e.g. Home and Landing page), then if I go back using the "Back" option of the browser, then again if I select the edit option of the same content (the Home and Landing page that I selected before) or any other content type, the "Hide row weights" continues to appear for all content type on the environment.

**Comment by alinai** [comment]
Passed on ODE and CMS. Issues that were noticed are getting tracked on https://github.com/orgs/NCIOCPL/projects/52/views/1

**Comment by alinai** [comment]
Looks good on ODE 647.
