### ISSUE TITLE
Highcharts have visual discrepancies when first loaded 

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform#3830]
### Issue description
*Description of the issue*
It was first discovered comparing dev-ac against ODE - when loaded the first time in chrome having two tabs with the same chart one being ODE and another dev-ac the two charts appeared slightly different ( see video) 
Refresh however makes them equal

also tested dev-ac VS dev-ac having the same page open in different tabs -on a first load charts were slightly different and refreshing one made them the same 

Also one of the charts had trouble loading - it needed a few refreshes to appear on FF ( or the same chart did not properly load after a refresh, see video) 

I suspect that the rest of the charts behave similarly, but I didn't have time to verify all of them.

This prevents us from having reliable visual tests in place 
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

https://user-images.githubusercontent.com/67657582/234103284-2433b41b-5e9d-4371-ba0e-b1f141f5bd9c.mov

https://user-images.githubusercontent.com/67657582/234103529-a0102feb-4611-4326-8845-a0a588eafe4e.mov

- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by laurelthrash** [comment]
Tagging @andyvanavery31 to bring this ticket into the general O&M board for prioritization. Determined on 09/25/23 with internal Factbook team that this ticket is still a priority to be fixed. Order of priority as of 09/25/23 can be found in the "Factbook Enhancement Project 2023" project board. 

Goal is to complete this ticket by the end of January 2024, ahead of conversations beginning in February 2024 regarding the FY24 Factbook release. This will need to be slotted in around other existing prioritized work for Seyi, should Seyi remain the primary developer. 

Cc: @santwuma @sarinapadilla

**Comment by seyilonge-nci** [comment]
For the first scenario with the "Grants & Awards Contract" chart, this chart is currently inactive pending resolution on #3446. Should not be displayed anywhere till previously mentioned issue is resolved. 
Second scenario is due to text wrapping being applied inconsistently by Highcharts which affects some other charts as well. Fix has been identified and will not require a code deployment, but a chart data update. Issue can be tracked [here](https://github.com/NCIOCPL/cgov-chart-data/issues/12)
