### ISSUE TITLE
Language Selection Toggle Missing from Content Types (Application Page, Biography, Cancer Center, Event)

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3836]
### Issue description
The language selection toggle is missing on the creation form for the following content types:

- Application Page
- Biography
- Cancer Center
- Event

> **ESTIMATE** TBD

### Steps to reproduce the issue (for Application Page, specifically) 

1. Login to any of the `*-cms` sites.
2. Go to `Content` > `Add content` > `Application Page` 

### What's the expected result?
- There should be a language selection dropdown at the top of the page.

### What's the actual result?
- The language selection dropdown is missing.

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/21063180/234976454-2c1e431d-13f8-436e-8cd3-3f7168025849.png)

**Comment by laurelthrash** [comment]
Note: intend to pick up this ticket in May 2023, prior to tentative June/July 2023 MyPART Spanish launch.

**Comment by blairlearn** [comment]
Adding the language toggle to the Biography, Cancer Center, and Event content types extends this issue to include their various taxonomies

- `cgov_biography_campuses`
- `cgov_cancer_center_regions`
- `cgov_cancer_center_types`
- `cgov_event_series`
- `cgov_event_venues`

If the content types are to allow Spanish, then the entries in these taxonomies must also allow it.
