### ISSUE TITLE
Enabler: Akamai Module Update

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3841]
# Akamai module update

- Akamai - upgrade from 3.x-dev -> 5.0.0-rc1
-  Note - This is a problem. 4.0.2 does not support D10, 5.0.0-rc1 does not support D9.

**Comment by santwuma** [comment]
This will need to be testing on wwwintAC beacause ODE do not have akamai.

**Comment by bryanpizzillo** [comment]
I am closing this as it had to be done with #3769 and it is causing confusion.
