### ISSUE TITLE
Update Security Module

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3845]
# Security modules

 - seckit from 2.0.0 --> 2.0.1
- role_delegation - upgrade from 1.1.0 -> 1.2.0
- shield - upgrade from 1.4.0 -> 1.7.0
- config_perms module- 8.x-2.1 has been release and supports Drupal 10

**Comment by SupriyaSaxena0605** [comment]
@blairlearn @navsunka Both Visual regression and Functional regression passes on the ODE627.
