### ISSUE TITLE
Spike: Investigate Raw HTML needs for home and landing page components

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3848]
## In order to determine what utility classes are needed for Raw HTML Blocks, a developer needs to create examples of certain components on an ODE (maybe in YAML).

> **Estimate** *# point* 

Raw HTML Blocks are going to need certain utility classes in order to implement them. However, we don't want to include the entire list of USWDS utility classes, so we need to figure out which utilities we will need for the components we are using on home and landing pages.

### Expected Deliverables:
* Built components on an ODE, possibly in YAML
* A list of utility classes needed for Raw HTML Blocks on home and landing pages

Examples of current/future use of HTML raw content blocks:
Known examples: 
- Pull Quotes
- Factoids
- DCEG Connect Logo box: https://www.cancer.gov/connect-prevention-study/

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/b7c6f083-8f54-4249-8d73-a3ee6fe46858)

- SBIR Info Session list (will likely be replaced by feature cards on landing page with R2.1 content changes): https://sbir.cancer.gov/
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/80a58d39-9db0-47e3-aa50-f67727cb19ab)

- Cancer.gov News and Events page, All NCI News button: https://www.cancer.gov/news-events
 Current: 
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/5e3c97b8-335b-471c-9a35-cc996adcf0b9)
Future:
- Cancer Types Home Page. [Comp in Figma ](https://www.figma.com/file/ZIgPLcQOlHYrbUxeWYaanZ/Cancer-Types?type=design&node-id=1%3A4&t=EtuuOK51H6cDLVrY-1)

- Partners and Cancer Research Page – callout box and Get Involved button: https://www.cancer.gov/research/cancer-research-partners

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/5653fcf4-5b84-416d-939d-40274319d070)

- Grants and Training page R2.1 comp (Spanish) – https://www.figma.com/proto/PRq3EH3lbIny6izBqkuuoA/R2.1-Content-Recs%3A-English-%26-Spanish?page-id=142%3A11354&node-id=142-11355&viewport=174%2C867%2C0.25&scaling=min-zoom

- NCP: Download Full Plan Button https://nationalcancerplan.cancer.gov/?cid=wl_cgov_feature_ncp

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/0129cc7c-bf20-4375-b97a-cbf4d2968a61)

- SBIR: Future use on event content types as Call to Action button to register for events
<img width="615" alt="Screenshot 2023-05-17 at 12 54 31 PM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/109552399/32bf9693-8f73-4108-9de7-21e52e960c49">

### Additional Notes:
* This investigation is needed in order to complete #3521

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by bryanpizzillo** [comment]
# Findings

## Initial File Sizes with R2.1 components up to NCI Hero (No Analytics)

**Before**
| File | Size |
| --- | ----- |
| `ncids-common.css` | 320152  |
| `home-landing.css`   |   39920 |
| `ncids-common.js`    | 283476 |
| `home-landing.js`      |   67760 |
| **TOTAL**                   |               |
**After**
| File | Size |
| --- | ----- |
| `ncids-minimal.css`            | 126415 |
| `ncids-home-landing.css` |   32533 |
| `ncids-minimal.js`               |            0 |
| `ncids-home-landing.js`    |   80364 | 
| **TOTAL**                            |                |
