### ISSUE TITLE
Update Henry Ford Logo on Connect Homepage

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3857]
![hp-ist-2h-gry](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/2cf98230-435f-4eb2-aa90-bb391ba69e04)
Please replace the Henry Ford Health Care System logo with the attached, updated version. This logo lives on the DCEG Connect microsite homepage: https://www.cancer.gov/connect-prevention-study/

Per Erik M: This div pulls in the logo as a background-image, so either that image (which lives in the codebase) will have to be updated (via release), or a new image added and the style changed to point to that.

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/22639543/e43396f7-9956-4c99-b362-6c7c3a1281a0)

The updated logo file is attached to https://tracker.nci.nih.gov/browse/CGOV-18718 (GitHub does not support the file type, so we added it to a JIRA ticket

**Comment by bennettcc** [comment]
@santwuma @laurelthrash - the Connect team request that this logo be updated within 2 weeks or so. Please let me know what you think a reasonable timing for this may be based on team availability.  The Connect team is looking to coordinate this update with the same logo update on their other promotional/public materials. Thanks!

**Comment by laurelthrash** [comment]
Logo updated in production and verified by the client 6/8. Closing this ticket. Cc: @bennettcc @seyilonge-nci
