### ISSUE TITLE
Rss feeds enclosure url breaks for microsites

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform#3869]
### Issue description
*Description of the issue*
enclosure url doesn't build correctly  
> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  go to https://www-dev-ac.cancer.gov/nano/PublishedContent/RSS/syndication/rss/blog-series.rss/281
2.  look at <enclosure url > tags, e.g. 
 <enclosure url="https://www-dev-ac.cancer.govnano//nano/sites/default/files/styles/cgov_thumbnail/public/cgov_image/thumbnail/2023-05/panorama-nature.jpg" length="6304" type="image/jpeg"/>

### What's the expected result?
- url builds correctly, such as 
https://www-dev-ac.cancer.gov/nano/sites/default/files/styles/cgov_thumbnail/public/cgov_image/thumbnail/2023-05/panorama-nature.jpg

### What's the actual result?
-https://www-dev-ac.cancer.govnano//nano...

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
@KateMashkinaNIH Yet more never been tested issues. https://www-int-ac.cancer.gov/nano/PublishedContent/RSS/syndication/rss/blog-series.rss/281 is running on 2.6.0, so it was not this change, it was just that it started getting tested. :)

We should fix though... (maybe)

**Comment by SupriyaSaxena0605** [comment]
@KateMashkinaNIH @santwuma Enclosure Url is building correctly on ODE 
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/31008800/c22fd35c-1a55-47c1-a3a9-b9adcab37c34)
