### ISSUE TITLE
Attach Pretty URL to Press Release Content Type with Validation 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#388]
**User Story:**
* As a content author, I would like to add a [pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#pretty-url) to a [press release](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) on cancer.gov. #174 

**Acceptance Criteria:**
* I have the option to enter a "tail" to the URL for my article. 
* My selection is validated by the system in order to ensure I am not duplicating an existing URL.

**Comment by bgnih** [comment]
Caveats:
- The current validation does not give errors on uppercase letters, but instead casts strings to lowercase before saving
- The system will not allow a duplicate Pretty_URL value via the UI, but importing via cgov_yaml_content module allows duplicate values, though the generated aliases are appended with `-0`, `-1`, etc. as needed for a unique alias.
