### ISSUE TITLE
ODE#557- Spacing issue when embedding Block Contents to the WYSIWYG

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#3880]
When embedding content block (display as = full), some extra space is appearing on WYSIWYG on ODE557. 
Also, when embedding Image Carousel (display as = Image, None), the area covered by the blue border around the image carousel has more width than the area covered by the blue border of the embedded Image Carousel (display as = Image, None) on cms-test. See the screenshot below of ODE and cms-test for visual comparison. 

![Image](https://user-images.githubusercontent.com/28455973/240735549-b4359ef3-f038-4549-96e5-75d4cc0202c0.png)
![Image](https://user-images.githubusercontent.com/28455973/240735656-e70e4769-f283-484c-949f-8790f26f7282.png)

![Image](https://user-images.githubusercontent.com/28455973/240735776-857090e2-5fa3-4b4a-b589-6573473bc42f.png)

![Image](https://user-images.githubusercontent.com/28455973/240735896-f1a971cd-9076-40a9-821c-49d129a9306d.png)

**Comment by sarinapadilla** [comment]
After discussion with Andy, this is not really an issue we care about. If it comes up again we can reopen, but closing for now!
