### ISSUE TITLE
'NIH Management Fund' high chart not appearing in production

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/cgov-digital-platform#3892]
### Issue description
*Description of the issue*
NIH Management Fund chart is not displayed on the page as expected

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Visit https://www.cancer.gov/about-nci/budget/fact-book/data/management-fund
2. Below the `Download the Data` button, there's a huge empty space where the chart used to be displayed

### What's the expected result?
- Chart should be displayed

### What's the actual result?
- Blank space

### Additional details / screenshot
<img width="1442" alt="Screenshot 2023-06-01 at 3 30 37 PM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/58226882/676bf016-5ac8-4721-9031-24f91e9b7350">

**Comment by laurelthrash** [comment]
This was fixed in NCIOCPL/cgov-chart-data#3
