### ISSUE TITLE
Attach Citations Fields to Press Release Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#390]
Attach [Citation Content](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citation-content) #425 and [Citation Pub Med ID](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citation-pub-med-id) #426 common fields to [Press Release](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) Content Type

**Comment by bgnih** [comment]
@nicolecrom This is blocked by Citations, which is unassigned in Sprint 7.   Should this be moved to Sprint 7?

**Comment by sarinapadilla** [comment]
Completed with PR #939
