### ISSUE TITLE
Enabler: Enable Linting for Profile in CI/CD

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3924]
Configure `blt validate:lint` so that it checks our profile's src folder, the modules within our profile, the themes within the profile. It should not attempt to lint our JS. 

## Linting
TODO: TBD -- the text below was from the last time it was investigated.

Custom Fileset Needed for Deprecated Code Checking

In trying to implement #2918, it looks like BLT would never check our profile's modules because of the BLT configuration. Unfortunately, it is not as easy as just adding some paths to a list in a yml file. No, we need to create our own version of https://github.com/acquia/blt/blob/11.x/src/Robo/Filesets/Filesets.php#L23. That is a class that defines methods, each of which returns is a list of files.

The blt.yml file will need to be updated as well to use these new files lists https://github.com/acquia/blt/blob/f50616adcbaf5c890e42c75d4c76bf6968c57f4f/config/build.yml#L258. This should probably update the linter definition as well.

**Comment by bryanpizzillo** [comment]
This was actually fixed by 3dd0a0a9f9703c7b5e5647d5ba1314d5032c534c in PR #3951.
