### ISSUE TITLE
Build Out Demo Site - www.

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#394]
This story is to create a www.cancer.gov buildout (demo site).

**Comment by amydugan** [comment]
SVG with the www banner is attached to https://tracker.nci.nih.gov/browse/CGOV-8687. SVG won't attach to this ticket.

**Comment by adriancofie** [comment]
This needs to be more defined.

**Comment by VictoriaSunNIH** [comment]
Closing this.  Will add more definitive tickets as we look at how we are approaching microsites.
