### ISSUE TITLE
Update token_filter, Entity Embed and Embed modules

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3950]
I have updated to latest versions which are Drupal 10 ready but not CKeditor 5 yet, Development for those are still in progress and I found patches which are working fine in my local but not sure if those affect anything else. we have to look out for the stable patches for those to work without any issues.

CKeditor5 supports SVG images only, so we have to update all the entity embed icon images to SVG. There are some CSS issues in the editor for all the entity embed plugins which needs to checked after doing CKeditor5 CSS changes we mentioned in #3846 

Current version: “drupal/embed": "^1.6"
Latest version:   "drupal/embed": "1.x-dev@dev"

Current version: "drupal/entity_embed": "^1.2.0"
Latest version:   "drupal/entity_embed": "^1.4"

Current version: "drupal/token_filter":"^1.3.0"
Latest version: "drupal/token_filter":"^2.0"

Issues:
https://www.drupal.org/project/entity_embed/issues/3272732
https://www.drupal.org/project/embed/issues/3309747

NOTE: This is not production ready yet as there are patches still being worked on.

**Comment by alinai** [comment]
@sarinapadilla, @navsunka , How are we supposed to test this? Running Automated Regression Tests suffice for this?
cc: @KateMashkinaNIH , @santwuma
