### ISSUE TITLE
Accessibility: Replace headings in footer content (all sites)

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3955]
**Reported Issue:** 
- Issue: In the footer, the Sign up for Emails header is an `<h3>` element, which is too large of a level increase.
- How to Fix: Change the header level for Sign up for Emails. [More info](https://dequeuniversity.com/rules/axe/4.7/heading-order?application=AxeChrome).
- Priority: Moderate
- Affects: The footer on all pages
- Note: The `<h3>` is part of USWDS. I assume it would be better to have it updated there instead of updating it just for our site.

**Screen shots:**

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/102998716/aad2f906-ae3a-44bc-9b3d-a91e0a55485b)

**History:** Reported on a July 2023 accessibility scan. Project board "Accessibility Issues (2023.07)" linked in the ticket. Original document here:  [Accessility Issues - Template and Non-Content (1).docx](https://github.com/NCIOCPL/cgov-digital-platform/files/12009906/Accessility.Issues.-.Template.and.Non-Content.1.docx)

**Comment by arcepaul** [comment]
We assume that page content would have both an <h1> and <h2> in the content of the page.

**Comment by laurelthrash** [comment]
Updates to footers on production were made the evening of 7/27/23 along with 2.8.1 deployment. Updated footers include those for: Cgov English, Cgov Spanish, CCG, DCEG, DCEG-Connect, MyPART English, MyPART Spanish, Nano, National Cancer Plan, Physics, and SBIR.

Update to TTC not made since the site is not live. Footer HTML is attached: [2023.07 html footers.zip](https://github.com/NCIOCPL/cgov-digital-platform/files/12194917/2023.07.html.footers.zip) 

Cc: @arcepaul @bryanpizzillo @santwuma

**Comment by bryanpizzillo** [comment]
@laurelthrash Can this ticket be closed?

**Comment by laurelthrash** [comment]
@bryanpizzillo - I believe so as the necessary change was applied to the platform sites. @arcepaul - anything I am missing before we close this out?

**Comment by bryanpizzillo** [comment]
I am closing this out as it is all content anyway, and people think it is done on all sites.
