### ISSUE TITLE
Card Title Not Updating Automatically on NCIDS Landing Page

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#3961]
### Issue description
A page is linked as a feature card on an NCIDS landing page. The card title for the linked page is updated and published, however, the card title does not automatically update. The landing page was pushed through the workflow (no changes made) and the new card title then displayed.

When this issue was discovered, Lindsay tested the same process on the News & Events page (using our standard template) and the title was automatically updated.

Hypothesis: Is it possible that there’s a cache issue affecting the NCIDS landing page templates? (Note that this has only been found on the feature card. May need to test other components as well.)

### Steps to reproduce the issue

1. Navigate to a landing page that uses the NCIDS style
2. Identify a piece of featured content on that page
3. Navigate to the page that is linked as feature content
4. Change the card title
5. Publish the page with the new card title
6. Refresh the landing page on which the piece of content is linked
7. See that the title of the featured content does not change

### What's the expected result?
- The card title on the landing page automatically updates with the new card title.

### What's the actual result?
- The card title does not automatically update. The landing page was pushed through the workflow (no changes made) and the new card title then displayed.

### Additional details / screenshot
- N/A

**Comment by laurelthrash** [comment]
@lburack Verified steps from description in ACSF-test on 7/13, following the steps below and received the same outcome as when we initially experienced the problem:

1. Navigated to About Cancer landing page (uses NCIDS style) 
2. Identified a piece of featured content (Advanced Cancer)
3. Changed card title (added " - TEST" so that the card title is "Advanced Cancer - TEST")  
4. Published page
5. Returned to About Cancer landing page 
6. Verified that the card title on the landing page is still "Advanced Cancer"
7. Pushed About Cancer landing page through the full work flow and published the page, but did not change anything on the page
8. Updated card title of "Advanced Cancer - TEST" successfully displays on the page

**Comment by bryanpizzillo** [comment]
@laurelthrash and @lburack Thank you very much for the steps to repeat it!

**Comment by laurelthrash** [comment]
Lakshmi reported problems in production with refreshing CGOV pages where content does not display on the front-end automatically, even after I clear cache from my browser. Noting on this ticket since the issue reported here was only tested in ACSF-test.

**Comment by santwuma** [comment]
Issue hasn't occurred again - closing ticket.
