### ISSUE TITLE
Update NCIDS to 2.2.0

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#3977]
For the 2.2 release of NCIDS components on the digital platform, we need to update the `ncids` package to 2.2.x.

> **ESTIMATE** TBD

**Comment by alinai** [comment]
@andyvanavery , for Scenario#1, for the hover state, we are seeing the color #004971 instead of  #00314B - primary-darker / Cerulean-80. However the active state color is showing as
#00314B. Can you please check it on dev-acsf and confirm.

**Comment by alinai** [comment]
The second scenario works as expected.

**Comment by alinai** [comment]
Thanks @andyvanavery for updating the AC. Both scenarios looks good on dev-acsf. cc: @bennettcc , @santwuma, @SupriyaSaxena0605
