### ISSUE TITLE
Fix field_ncids_theme to be used for other components

### ISSUE THREAD

**Issue by dev-rana-publicis** [NCIOCPL/cgov-digital-platform#3981]
### Issue description
The current `field_ncids_theme` storage config is setting `Dark` to `nci-promo-block--dark` which will work for NCIDS Promo Block but not NCIDS Hero with Dark Theme. This ticket is to make the field storage work for both components.

**Comment by SupriyaSaxena0605** [comment]
@bryanpizzillo @santwuma Verified this ticket on ODE 614 for NCIDS Promo Block and NCIDS Hero with Dark Theme. Both seems to be working fine.
NCIDS Promo block with Dark theme
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/31008800/6a93d92a-3add-48d7-9c81-0ecf1d19a9cc)

NCIDS Hero with Dark theme
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/31008800/05343820-4559-4f9e-9eeb-7625f0069c65)

**Comment by alinai** [comment]
Looks good on dev-acsf. The "Theme" dropdown under NCIDS Promo Block Internal and External and NCIDS Hero shows a new option "DON'T USE" along with "Dark" and "Light" options. Confirmed with @bryanpizzillo that it is expected. cc: @SupriyaSaxena0605
