### ISSUE TITLE
Expose information in meta data about Drupal site value

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#3990]
### Issue description
To help us better segment in analytics, we'd like to start collecting information about the domain/microsite value from Drupal (ex: cgov, ttc, mypart, nano, dceg). To do, so we need to make that piece of information available to be picked up by Adobe Anlaytics.

In the past, we've done that through adding additional meta data values in the header of the page and then getting that information through Adobe Launch. More recently, we've pass additional details about a page directly to the EDDL and added into the page load and click event values. I'm fine with whatever approach the dev team would like to take.

> **ESTIMATE** TBD

### What's the expected change?
A value representing the domain/microsite folders in Drupal is made available to be collected in Adobe Analytics.

### What's the current functionality?
This value is not currently collected.

### What's the updated acceptance criteria?
This new value is sent into Adobe as part of the standard page load and click event actions on pages within the digital platform.

### Testing notes
- Joe to review and provide sign off, then
- Kate to run front end tests for meta data and analytics, in addition to updating meta data tests to reflect the new additions / confirm it shows up on all content types

**Comment by bryanpizzillo** [comment]
Solution: This should get the name of the Site Factory site if set. We do need to figure out what to do on ODEs and non-acsf dev environments.

**Comment by blairlearn** [comment]
A possible (haven't tried this yet) way to get the Site Factory site name is via [DrupalKernel::findSitePath](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21DrupalKernel.php/function/DrupalKernel%3A%3AfindSitePath/10.1.x).

There's some sample code at: https://drupal.stackexchange.com/a/257333/92606

**Comment by bryanpizzillo** [comment]
@welshja we are going to call this `<meta name="cgdp.domain" content="<DOMAIN>">`. 
The `<DOMAIN>` would be something like:
**ACSF** 
* `cgov`, `mypart`, `dceg`, etc for production ACSF
* `cgov-dev`, `mypart-dev`, `mypart-test`, etc for lower tiers

**ACE** (this should come from the AH_ENVIRONMENT var)
* `ode` for an ode
* `dev` for www-dev-ac
* `staging` for www-test-ac
* `int` for www-int-ac

**Local**
* `local` for a local machine

Do you have any issues with this?


-----------

Implementation Notes:
ACSF name
* This will come from the ACSF site configuration file (e.g. `$domains = gardens_data_get_sites_from_file($GLOBALS['gardens_site_settings']['conf']['acsf_db_name']);`)
* You should find the domain that matches `XXX.YYY.acsitefactory.com`
* Take the `XXX` part of the the domain to begin the contents of the meta tag.
   * If `YYY` is `$AH_SITE_GROUP` (e.g. ncigov) then just set the domain to XXX
      * e.g., `cgov`, `mypart`, `dceg`, etc for production ACSF
   * If `YYY` part does not equal `$AH_SITE_GROUP` then:
     1. remove `'-' . $AH_SITE_GROUP` from the `YYY` part.
         * this will leave you with something like `dev` or `test`
     2. Append the above with a `-` to the `XXX` part.
         * you should end up with something like `cgov-dev`, `mypart-dev`, `mypart-test`, etc for lower tiers
