### ISSUE TITLE
phpstan fixes for cgov_common, ncids_trans themes

### ISSUE THREAD

**Issue by navsunka** [NCIOCPL/cgov-digital-platform#3993]
*Remove unused global variables in Ncids Trans & Cgov Common themes*

**Parent Issue:** #3964

Below are the files which are need to fixed as part of this ticket:

Cgov Common :
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/cgov_common.theme
- docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/theme-settings.php

Ncids Trans :
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/ncids_trans.theme
- docroot/profiles/custom/cgov_site/themes/custom/ncids_trans/theme-settings.php

Regression testing in related routes:
- FE changes in Ncids Trans & Cgov Common  Theme
- Validate all the items in the theme settings page:
/admin/appearance/settings/cgov_common 
/admin/appearance/settings/ncids_trans

**Comment by SupriyaSaxena0605** [comment]
@navsunka @blairl-nih Visual regression and CMS regression tests passed on test-ac.
