### ISSUE TITLE
Extraneous bullet appears next to High Chart graphs

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3997]
Some charts have a bullet point character ("•") next to them.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://www.cancer.gov/about-nci/budget/fact-book/data/program-structure
2. Scroll down to the "Program Structure" chart.

### What's the expected result?
- The chart should appear without a bullet point.

### What's the actual result?
- There should be no bullet.

This may be observed on these pages:
- https://www.cancer.gov/about-nci/budget/fact-book/data/program-structure
- https://www.cancer.gov/about-nci/budget/fact-book/data/extramural
- https://www.cancer.gov/about-nci/budget/fact-book/data/obligations
- https://www.cancer.gov/about-nci/budget/fact-book/data/management-fund
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/nrsa
- https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/bypass-appropriations
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/extramural-intramural-rms
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/comparison
- https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/aids-funding
- https://www.cancer.gov/about-nci/budget/fact-book/cancer-moonshot/moonshot-obligations

### Additional details / screenshot
- ![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/21063180/f99537a0-4606-4016-9f9a-9e176897d157)

**Comment by alinai** [comment]
Looks good on Chrome, FF and Edge.

**Comment by KateMashkinaNIH** [comment]
And Safari ^
