### ISSUE TITLE
Update Paragraph to use paragraphs stable widget

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#4001]
Update and Paragraph config changes 

Related ticket: #3847 and #3986 

### Requirements
- Each field where paragraphs can be added has the "Add <Default Paragraph>" button
  - Example: "Add Primary Feature Card Row" to Contents field of Home and Landing content type
- Clicking on the `Add <Default Paragraph>` button adds to the field
- If multiple options, there is a down arrow that displays next to the `Add <Default Paragraph` option
- Clicking down arrow displays all paragraph options for that field
- Selecting an option from the list adds that paragraph to the field
- `Add <Default Paragraph>` button disappears if the max cardinality for the field has been reached
- Clicking "Remove" deletes the paragraph

**Comment by santwuma** [comment]
Evaluate LOE for adding patch for "Confirm Removal" option for collapsed items when dev work to implement this Claro starts.

Make a note for training documentation if this option is removed.

**Comment by alinai** [comment]
@sarinapadilla , please clarify the requirement: "Each field displays a default paragraph to add"

**Comment by alinai** [comment]
@sarinapadilla , When I add a new Article, I see the Body, Related Resources and Citation as follows:

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/2b1e06df-1cd3-46b0-9d4d-2711bb7ca4ce)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/f6e4b247-9b26-43c8-aafb-7100c5369a17)

Then when we add 1 more Body section and Related Resources and Citation, we see the following in the "Edit" mode:
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/7d2a2a07-6c76-4a9a-9c26-2d2a5acc6d03)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/2300abd2-4e63-4fe7-9657-241cfe62aeea)

Is that the expectation from the requirement on the spreadsheet?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/c07c16fd-1c65-4e23-bf01-f7b734f014c0)

**Comment by alinai** [comment]
@sarinapadilla , For the following requirement:
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/0bb41b33-f95f-4285-9533-675ca7868517)

For #1, I can see the "Remove" button for a field in the Paragraph, not for the entire Paragraph. So we should see the "Remove" button only for the fields of the paragraph?
Also, we do not see any text message on removing a field

For#2, It is contradictory to the requirements of removing paragraph on #3829 

cc: @KateMashkinaNIH

**Comment by alinai** [comment]
The focus on the checkbox is cut off:
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/e272fceb-159b-403f-ad59-437f867449c6)

**Comment by alinai** [comment]
> @sarinapadilla , When I add a new Article, I see the Body, Related Resources and Citation as follows:
> 
> ![image](https://user-images.githubusercontent.com/28455973/270819234-2b1e06df-1cd3-46b0-9d4d-2711bb7ca4ce.png)
> 
> ![image](https://user-images.githubusercontent.com/28455973/270819311-f6e4b247-9b26-43c8-aafb-7100c5369a17.png)
> 
> Then when we add 1 more Body section and Related Resources and Citation, we see the following in the "Edit" mode: ![image](https://user-images.githubusercontent.com/28455973/270819514-7d2a2a07-6c76-4a9a-9c26-2d2a5acc6d03.png) ![image](https://user-images.githubusercontent.com/28455973/270819569-2300abd2-4e63-4fe7-9657-241cfe62aeea.png)
> 
> Is that the expectation from the requirement on the spreadsheet? ![image](https://user-images.githubusercontent.com/28455973/270819688-c07c16fd-1c65-4e23-bf01-f7b734f014c0.png)

@sarinapadilla , confirmed that this looks good in the check-in.

**Comment by alinai** [comment]
@sarinapadilla , on clicking the three dots, we see the "Remove: button and "Duplicate" button. Should we see the "Remove" button on clicking those three dots? 
Please confirm the requirement of the "Duplicate" button.

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/6f268a07-2aad-4a62-baa7-ce2f4b911ab9)

**Comment by sarinapadilla** [comment]
@alinai from our meeting:
* We discussed the difference between the field and the paragraph and confirmed the Remove button was displaying for the paragraphs.
* I updated the requirements for the Remove button, and it simply should remove the paragraph (no "Deleted Paragraph:" text or "Confirm Removal" button). Essentially this ticket has been updated with the same requirements as #3829 - apologies for not updating it here as well!
* Limited cardinality items
  * Added to Home and Landing Page Contents:
    * NCIDS 3 Feature Card Row: 3
    * NCIDS 3 Guide Card Row: 3
    * NCIDS 2 Guide Card Row: 2
    * NCIDS Call to Action Strip: 3
    * Primary Feature Card Row: 3
    * Secondary Feature Card Row: 3
    * Guide Card Row: 3
    * Two Item Feature Card Row: 2
  * Added to NCIDS Guide Card Rows:
    * Links for Guide Card Buttons: 6
  * Added to NCIDS Hero:
    * Primary Call to Action Link: 1
    * Call to Action Strip: 3
  * CTHP Video Card: 1
  * Added to Multimedia Row:
    * Feature Card: 1
  * Added to Title First Feature Card Row:
    * Two Column Feature Card: 1
    * One Column Feature Card: 1
  * Added to Mini Landing Page Contents:
    * Two Item Feature Card Row: 2
* Answering your most recent question, the Duplicate button is new with the Claro theme and should be there. The functionality of adding another paragraph with the same content is correct.

**Comment by alinai** [comment]
> @alinai from our meeting:
> 
> * We discussed the difference between the field and the paragraph and confirmed the Remove button was displaying for the paragraphs.
> * I updated the requirements for the Remove button, and it simply should remove the paragraph (no "Deleted Paragraph:" text or "Confirm Removal" button). Essentially this ticket has been updated with the same requirements as [Enabler: cgov_admin theme must change to use claro base theme #3829](https://github.com/NCIOCPL/cgov-digital-platform/issues/3829) - apologies for not updating it here as well!
> * Limited cardinality items
>   
>   * Added to Home and Landing Page Contents:
>     
>     * NCIDS 3 Feature Card Row: 3
>     * NCIDS 3 Guide Card Row: 3
>     * NCIDS 2 Guide Card Row: 2
>     * NCIDS Call to Action Strip: 3
>     * Primary Feature Card Row: 3
>     * Secondary Feature Card Row: 3
>     * Guide Card Row: 3
>     * Two Item Feature Card Row: 2
>   * Added to NCIDS Guide Card Rows:
>     
>     * Links for Guide Card Buttons: 6
>   * Added to NCIDS Hero:
>     
>     * Primary Call to Action Link: 1
>     * Call to Action Strip: 3
>   * Added to CTHP Cards:
>     
>     * CTHP Video Card: 1
>   * Added to Multimedia Row:
>     
>     * Feature Card: 1
>   * Added to Title First Feature Card Row:
>     
>     * Two Column Feature Card: 1
>     * One Column Feature Card: 1
>   * Added to Mini Landing Page Contents:
>     
>     * Two Item Feature Card Row: 2
> * Answering your most recent question, the Duplicate button is new with the Claro theme and should be there. The functionality of adding another paragraph with the same content is correct.

Thanks @sarinapadilla

**Comment by alinai** [comment]
@sarinapadilla , do we want to see both the link and the Title for External link for Related Resources when it appears collapsed in Editing mode in the CMS?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/9b465675-6bee-4484-a9e7-61ec072cb666)

**Comment by alinai** [comment]
@sarinapadilla , When we add Override Title, we see both the Title and Override Title in the collapsed Internal link, Media in Related Resources on the CMS. Is it ok?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/aa6c61eb-d89c-4146-8ffc-34a2a1ac8749)

**Comment by alinai** [comment]
@sarinapadilla , this is the window that appears on clicking the link button (ss#1) and after selecting the link(ss#2). Does it look right?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/13c0d346-4cb1-4c1b-9904-0397b1f6d763)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/d580b279-7220-4a53-9f99-20df0f9be2ed)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , do we want to see both the link and the Title for External link for Related Resources when it appears collapsed in Editing mode in the CMS? ![image](https://user-images.githubusercontent.com/28455973/271070582-9b465675-6bee-4484-a9e7-61ec072cb666.png)


> @sarinapadilla , When we add Override Title, we see both the Title and Override Title in the collapsed Internal link, Media in Related Resources on the CMS. We don't see the Override description. Is it ok that we see both the Title and Override Title and no override description ? ![image](https://user-images.githubusercontent.com/28455973/271071662-aa6c61eb-d89c-4146-8ffc-34a2a1ac8749.png)


@alinai for both of these issues, I have the requirement listed in the [Claro ticket](https://github.com/NCIOCPL/cgov-digital-platform/issues/3829). I have all of the requirements for the accordion items in that ticket, since this one is specifically for the paragraphs module. But yes, the first two fields of the paragraph display in the accordion. If only one of those fields is set, then just that field will display
* For internal links, it will be the title of the content item that is being linked, and the override title (if set)
* For external links, it will be the link URL, and the title
* For media links, it will be the title of the content item that is being linked, and the override title (if set)

**Comment by alinai** [comment]
> > @sarinapadilla , do we want to see both the link and the Title for External link for Related Resources when it appears collapsed in Editing mode in the CMS? ![image](https://user-images.githubusercontent.com/28455973/271070582-9b465675-6bee-4484-a9e7-61ec072cb666.png)
> 
> > @sarinapadilla , When we add Override Title, we see both the Title and Override Title in the collapsed Internal link, Media in Related Resources on the CMS. We don't see the Override description. Is it ok that we see both the Title and Override Title and no override description ? ![image](https://user-images.githubusercontent.com/28455973/271071662-aa6c61eb-d89c-4146-8ffc-34a2a1ac8749.png)
> 
> @alinai for both of these issues, I have the requirement listed in the [Claro ticket](https://github.com/NCIOCPL/cgov-digital-platform/issues/3829). I have all of the requirements for the accordion items in that ticket, since this one is specifically for the paragraphs module. But yes, the first two fields of the paragraph display in the accordion. If only one of those fields is set, then just that field will display
> 
> * For internal links, it will be the title of the content item that is being linked, and the override title (if set)
> * For external links, it will be the link URL, and the title
> * For media links, it will be the title of the content item that is being linked, and the override title (if set)

Thanks for confirming @sarinapadilla

**Comment by alinai** [comment]
@sarinapadilla , same requirement for Internal Links and External Links that you mentioned above holds for External Feature Cards and Internal Feature Cards (in this case in Recommended Contents in Blog Posts) ad wherever we have External Feature Cards and Internal Feature Cards , right?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/84cceff0-7e8c-4737-9aa6-5bd29b7f4c74)

**Comment by alinai** [comment]
@sarinapadilla , Per requirement on the Excel Sheet  ncids_2_guide_card_row and ncids_3_guide_card_row should be "Open". I am seeing that ncids_2_guide_card_row and ncids_3_guide_card_row are appearing collapsed on editing Home and Landing Page. Can you please check for me? Test url: https://ncigovcdode633.prod.acquia-sites.com/about-cancer/coping/survivorship/new-normal/test-and-test-home-landing1

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/d2d07ed0-c9a0-426b-8325-dd3d9b74df89)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/386763af-15aa-4c8d-b332-e5423dacc84e)

**Comment by alinai** [comment]
@sarinapadilla , not seeing the "Target Url" label on the ODE for this requirement:

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/d6977807-4397-4674-8807-708c0b826bf8)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/aa5299f2-bea3-47b7-9ee7-cf7e3d207586)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/dfb13e5d-629b-4d62-a015-3fef8a19213a)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , not seeing the "Target Url" label on the ODE for this requirement:
> 
> ![image](https://user-images.githubusercontent.com/28455973/271449076-d6977807-4397-4674-8807-708c0b826bf8.png)
> 
> ![image](https://user-images.githubusercontent.com/28455973/271448728-aa5299f2-bea3-47b7-9ee7-cf7e3d207586.png) ![image](https://user-images.githubusercontent.com/28455973/271448985-dfb13e5d-629b-4d62-a015-3fef8a19213a.png)



@alinai it looks like in the first image you are looking at a new CTHP Video Card that does not have a link paragraph (internal vs. external vs. media) selected, whereas for the second image you are looking at a CTHP Video Card where internal link has already been selected. I am able to see the Target URL with the paragraph selection button:

<img width="469" alt="Screenshot 2023-09-29 at 12 03 10 AM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/24591940/05ac3b41-a874-437a-9116-4ae15e370f02">

**Comment by alinai** [comment]
@sarinapadilla , Which content type I can find the following:
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/9ea85137-1874-4764-af1f-cb4e2d3040e9)

**Comment by alinai** [comment]
@sarinapadilla , Can you please check the following requirement in the spreadsheet? I am seeing the multimedia row as collapsed but per spreadsheet it should be opened. Does your following comment for "Open" applies here as well?

> when the spreadsheet says open, it means that once you click on the Edit for the 2 and 3 Guide Card Rows, then the cards within that row are open rather than collapsed. 

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/4e80a7ce-3c6b-4742-a2c8-f612c7446f71)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/78174176-aa8f-42dc-aaf4-dd2d07d07088)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , Which content type I can find the following: ![image](https://user-images.githubusercontent.com/28455973/271601220-9ea85137-1874-4764-af1f-cb4e2d3040e9.png)

You can find that on the old Guide Card Row that can be added to a Home and Landing Page!

**Comment by alinai** [comment]
> > @alinai from our meeting:
> > 
> > * We discussed the difference between the field and the paragraph and confirmed the Remove button was displaying for the paragraphs.
> > * I updated the requirements for the Remove button, and it simply should remove the paragraph (no "Deleted Paragraph:" text or "Confirm Removal" button). Essentially this ticket has been updated with the same requirements as [Enabler: cgov_admin theme must change to use claro base theme #3829](https://github.com/NCIOCPL/cgov-digital-platform/issues/3829) - apologies for not updating it here as well!
> > * Limited cardinality items
> >   
> >   * Added to Home and Landing Page Contents:
> >     
> >     * NCIDS 3 Feature Card Row: 3
> >     * NCIDS 3 Guide Card Row: 3
> >     * NCIDS 2 Guide Card Row: 2
> >     * NCIDS Call to Action Strip: 3
> >     * Primary Feature Card Row: 3
> >     * Secondary Feature Card Row: 3
> >     * Guide Card Row: 3
> >     * Two Item Feature Card Row: 2
> >   * Added to NCIDS Guide Card Rows:
> >     
> >     * Links for Guide Card Buttons: 6
> >   * Added to NCIDS Hero:
> >     
> >     * Primary Call to Action Link: 1
> >     * Call to Action Strip: 3
> >   * Added to CTHP Cards:
> >     
> >     * CTHP Video Card: 1
> >   * Added to Multimedia Row:
> >     
> >     * Feature Card: 1
> >   * Added to Title First Feature Card Row:
> >     
> >     * Two Column Feature Card: 1
> >     * One Column Feature Card: 1
> >   * Added to Mini Landing Page Contents:
> >     
> >     * Two Item Feature Card Row: 2
> > * Answering your most recent question, the Duplicate button is new with the Claro theme and should be there. The functionality of adding another paragraph with the same content is correct.
> 
> Thanks @sarinapadilla

@sarinapadilla , for the cardinality, I am seeing it allows me to add 
4 NCIDS 3 Feature Card Row
4 NCIDS 3 Guide Card Row
4 NCIDS 2 Guide Card Row

In your comment above, the number at the end means the number of paragraphs that cab be added to  Contents, right? 
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/00477b44-db54-4a4a-9393-c4963c6339cb)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/93122fad-090e-4a38-ba9e-c859a604c89f)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , Can you please check the following requirement in the spreadsheet? I am seeing the multimedia row, primary feature row, secondary feature row, Two Column Feature Card, One Column Feature Card appearing as collapsed but per spreadsheet it should be opened. Does your following comment for "Open" applies here as well?
> 
> > when the spreadsheet says open, it means that once you click on the Edit for the 2 and 3 Guide Card Rows, then the cards within that row are open rather than collapsed.
> 
> ![image](https://user-images.githubusercontent.com/28455973/271664399-b0ab39f2-c3b7-440a-9786-30abed25adc9.png)
> 
> ![image](https://user-images.githubusercontent.com/28455973/271638030-78174176-aa8f-42dc-aaf4-dd2d07d07088.png) ![image](https://user-images.githubusercontent.com/28455973/271659001-586ec8be-360f-4cf8-8811-8fac85daaeda.png)

@alinai yes, what I explained for the 2 or 3 Guide Card Row applies here as well. For the spreadsheet, you are testing the paragraph named in the Field Label column, and that paragraph exists on the Bundle Name item.

Example using the Contents field on a Home and Landing page, which is row 20 on the spreadsheet. The Field Label is Contents, and the Bundle Name is Home and Landing, and it says collapsed. That means all of the items added to the Contents field on a Home and Landing page are collapsed, which you have in the screenshot, and that is expected.

For all of the paragraphs that you highlighted, you need to be looking at the field with the Field Label rather than the Bundle Name. So you need to expand the paragraph in Bundle Name (Primary Feature Card Row, for example) and then view that the Feature Cards field has all of its items expanded.

Primary Feature Card Row: edit, and see that the contents of Feature Cards field are open
Secondary Feature Card Row: edit, and see that the contents of Feature Cards field are open
Multimedia Row: edit, and see that the item in Feature Card field is open
Title First Feature Card Row: edit, and see the item in One Column Feature Card is open
Title First Feature Card Row: edit, and see the item in Two Column Feature Card is open

**Comment by sarinapadilla** [comment]
@alinai we just spoke about the cardinality testing and I updated my comment accordingly!

**Comment by alinai** [comment]
Limited cardinality items

Added to Home and Landing Page Contents:

NCIDS 3 Feature Card Row: 3 - PASS
NCIDS 3 Guide Card Row: 3 - PASS
NCIDS 2 Guide Card Row: 2 - PASS
NCIDS Call to Action Strip: 3 - PASS
Primary Feature Card Row: 3 - PASS
Secondary Feature Card Row: 3 - PASS
Guide Card Row: 3 -PASS
Two Item Feature Card Row: 2 (Mini Landing page) - PASS

Added to NCIDS Guide Card Rows:
Links for Guide Card Buttons: 6 (Pass in NCIDS 2 Guide Card Row, NCIDS 3 Guide Card Row)

Added to NCIDS Hero:
Primary Call to Action Link: 1 -PASS
Call to Action Strip: 3 -PASS

Added to CTHP Cards:
CTHP Video Card: 1

Added to Multimedia Row:
Feature Card: 1

Added to Title First Feature Card Row:
Two Column Feature Card: 1
One Column Feature Card: 1

Added to Mini Landing Page Contents:
Two Item Feature Card Row: 2

**Comment by alinai** [comment]
@sarinapadilla , please confirm if what I stated in the QA Status column is what we are expecting?
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/46bc7408-0c90-4701-b6cc-598f59074d68)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/0970b375-ec40-4d71-9458-ca0645a6a056)

**Comment by alinai** [comment]
Requirements
Each field where paragraphs can be added has the "Add " button ............PASSed on ODE
Example: "Add Primary Feature Card Row" to Contents field of Home and Landing content type..........PASSed on ODE
Clicking on the Add <Default Paragraph> button adds to the field..........PASS
If multiple options, there is a down arrow that displays next to the Add <Default Paragraph option...........PASSed on ODE
Clicking down arrow displays all paragraph options for that field..........PASSed on ODE
Selecting an option from the list adds that paragraph to the field.............PASSed on ODE
Add <Default Paragraph> button disappears if the max cardinality for the field has been reached..............PASSed on ODE
Clicking "Remove" deletes the paragraph..............PASSed on ODE


> Limited cardinality items - Test Status
> 
> Added to Home and Landing Page Contents:
> 
> NCIDS 3 Feature Card Row: 3 - PASS NCIDS 3 Guide Card Row: 3 - PASS NCIDS 2 Guide Card Row: 2 - PASS NCIDS Call to Action Strip: 3 - PASS Primary Feature Card Row: 3 - PASS Secondary Feature Card Row: 3 - PASS Guide Card Row: 3 -PASS
> 
> Two Item Feature Card Row: 2 (Mini Landing page) - PASS
> 
> Added to NCIDS Guide Card Rows: Links for Guide Card Buttons: 6 (Pass in NCIDS 2 Guide Card Row, NCIDS 3 Guide Card Row)
> 
> Added to NCIDS Hero: Primary Call to Action Link: 1 -PASS Call to Action Strip: 3 -PASS
> 
> Added to CTHP Cards: CTHP Video Card: 1 - Question (the card or the link Cardinality)
> 
> Added to Multimedia Row: Feature Card: 1 - PASS
> 
> Added to Title First Feature Card Row: Two Column Feature Card: 1 - PASS One Column Feature Card: 1 -PASS
> 
> Added to Mini Landing Page Contents: Two Item Feature Card Row: 2 - PASS

@sarinapadilla , the following requirement is for the CTHP Video Card Cardinality or the Link under CTHP Video Card?

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/6c7c3a9b-1532-45ec-8428-3eefe307e4ea)


![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/60c8a12b-eb03-42e9-b0c2-a1c0585becf1)

**Comment by alinai** [comment]
Requirements
Each field where paragraphs can be added has the "Add " button ............PASSed on ODE
Example: "Add Primary Feature Card Row" to Contents field of Home and Landing content type..........PASSed on ODE
Clicking on the Add <Default Paragraph> button adds to the field..........PASS
If multiple options, there is a down arrow that displays next to the Add <Default Paragraph option...........PASSed on ODE
Clicking down arrow displays all paragraph options for that field..........PASSed on ODE
Selecting an option from the list adds that paragraph to the field.............PASSed on ODE
Add <Default Paragraph> button disappears if the max cardinality for the field has been reached..............PASSed on ODE
Clicking "Remove" deletes the paragraph..............PASSed on ODE

**Comment by alinai** [comment]
Cardinality Tests after updating the requirements got updated: 
Limited cardinality items
**Home and Landing page paragraphs**
NCIDS 3 Feature Card Row: 3 Cards (internal, external, media) : No. of cards that can be added =3, but the cards are Internal, external and Multimedia Card and Raw HTML Block 

NCIDS 3 Guide Card Row: 3 Cards ((internal, external, media):No. of cards that can be added =3,  but the cards are Internal, external only 

NCIDS 2 Guide Card Row: 2 Cards (internal, external, media): No. of cards that can be added =2, but the cards are Internal, external only 

NCIDS Call to Action Strip: 3 Link Buttons (internal, external) : PASS

Primary Feature Card Row: 3 Feature Cards (internal, external, media): No. of cards that can be added =3,  but the cards are Internal, external and Raw HTML Block 

Secondary Feature Card Row: 3 Feature Cards (internal, external, media) PASS but the cards are Internal, external and Raw HTML Block 

Guide Card Row: 3 items (content block, raw HTML block): PASS

Two Item Feature Card Row: 2 Feature Cards (internal, external, media): No. of cards that can be added =2, but the cards are Internal, external and Multimedia Card and Raw HTML Block 

**NCIDS Guide Card Row paragraphs:**
Links for Guide Card Buttons: 6 (internal, external, media): No. of cards that can be added =6, but the cards are Internal, external only, no media 

NCIDS Hero paragraphs:
Primary Call to Action Link: 1 (internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only, no media 

Call to Action Strip: 3 (internal, external, media): No. of cards that can be added =3,  but the cards are Internal, external only, no media 

**Added to CTHP Video Card:**
Target URL: 1 link (internal, external, media): PASS

**Added to Multimedia Row:**
Feature Card: 1 Feature Card (internal, external, media): No. of cards that can be added =1, but the cards are Internal, external and Raw HTML Block 

**Added to Title First Feature Card Row:**
Two Column Feature Card: 1 Feature Card ((internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only
One Column Feature Card: 1 Feature Card ((internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only

Added to Mini Landing Page Contents:
Two Item Feature Card Row: 2 Feature Cards (internal, external, media):  No. of cards that can be added =2, but the cards are Internal, external and Multimedia Card and Raw HTML Block 

@sarinapadilla , some of the places do not have media or have other options as well which does not match the requirement.

**Comment by sarinapadilla** [comment]
@alinai, some of the requirements were copy paste errors. Here is the updated list - and it looks like what you have listed for testing is correct and should pass.

* Limited cardinality items
  * Home and Landing page paragraphs
    * NCIDS 3 Feature Card Row: 3 Cards (internal, external, media, raw HTML)
    * NCIDS 3 Guide Card Row: 3 Cards (NCIDS guide card)
    * NCIDS 2 Guide Card Row: 2 Cards (NCIDS guide card with image and description)
    * NCIDS Call to Action Strip: 3 Link Buttons (internal, external)
    * Primary Feature Card Row: 3 Feature Cards (internal, external, raw HTML)
    * Secondary Feature Card Row: 3 Feature Cards (internal, external, raw HTML)
    * Guide Card Row: 3 items (content block, raw HTML block)
    * Two Item Feature Card Row: 2 Feature Cards (internal, external, media, raw HTML)
  * NCIDS Guide Card Row paragraphs:
    * Links for Guide Card Buttons: 6 (internal, external)
  * NCIDS Hero paragraphs: 
    * Primary Call to Action Link: 1 (internal, external)
    * Call to Action Strip: 3 (internal, external)
  * Added to CTHP Video Card:
    * Target URL: 1 link (internal, external, media)
  * Added to Multimedia Row:
    * Feature Card: 1 Feature Card (internal, external, raw HTML)
  * Added to Title First Feature Card Row:
    * Two Column Feature Card: 1 Feature Card (internal, external)
    * One Column Feature Card: 1 Feature Card (internal, external)
  * Added to Mini Landing Page Contents:
    * Two Item Feature Card Row: 2 Feature Cards (internal, external, media, raw HTML)

**Comment by sarinapadilla** [comment]
> @sarinapadilla , please confirm if what I stated in the QA Status column is what we are expecting? ![image](https://user-images.githubusercontent.com/28455973/272066694-46bc7408-0c90-4701-b6cc-598f59074d68.png) ![image](https://user-images.githubusercontent.com/28455973/272067068-0970b375-ec40-4d71-9458-ca0645a6a056.png)

@alinai this looks good!

**Comment by alinai** [comment]
Cardinality Tests after updating the requirements got updated: 
Limited cardinality items
**Home and Landing page paragraphs**

NCIDS 3 Feature Card Row: 3 Cards (internal, external, media) : No. of cards that can be added =3, but the cards are Internal, external Multimedia Card and Raw HTML Block ...............PASSed on ODE and cms-test

NCIDS 3 Guide Card Row: 3 Cards ((internal, external, media):No. of cards that can be added =3,  NCIDS guide card, Raw HTML Content ...............PASSed on ODE and cms-test

NCIDS 2 Guide Card Row: 2 Cards (internal, external, media): No. of cards that can be added =2, NCIDS guide card with image and description, Raw HTML Content ...............PASSed on ODE and cms-test

NCIDS Call to Action Strip: 3 Link Buttons (internal, external) : PASS

Primary Feature Card Row: 3 Feature Cards (internal, external, media): No. of cards that can be added =3,  but the cards are Internal, external and Raw HTML Block .............PASSed on ODE and cms-test

Secondary Feature Card Row: 3 Feature Cards (internal, external, media) PASS but the cards are Internal, external and Raw HTML Block ..............PASSed on ODE and cms-test

Guide Card Row: 3 items (content block, raw HTML block): ...............PASSed on ODE and cms-test

Two Item Feature Card Row: 2 Feature Cards (internal, external, media): No. of cards that can be added =2, but the cards are Internal, external and Raw HTML Block PASSed on ODE and cms-test

**NCIDS Guide Card Row paragraphs:**
Links for Guide Card Buttons: 6 (internal, external, media): No. of cards that can be added =6, but the cards are Internal, external only, no media 

NCIDS Hero paragraphs:
Primary Call to Action Link: 1 (internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only, no media 

Call to Action Strip: 3 (internal, external, media): No. of cards that can be added =3,  but the cards are Internal, external only, no media 

**Added to CTHP Video Card:**
Target URL: 1 link (internal, external, media): PASS

**Added to Multimedia Row:**
Feature Card: 1 Feature Card (internal, external, media): No. of cards that can be added =1, but the cards are Internal, external and Raw HTML Block 

**Added to Title First Feature Card Row:**    ................PASSed on ODE and cms-test
Two Column Feature Card: 1 Feature Card ((internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only
One Column Feature Card: 1 Feature Card ((internal, external, media):  No. of cards that can be added =1, but the cards are Internal, external only

Added to Mini Landing Page Contents:    ...................PASSed on ODE and cms-test
Two Item Feature Card Row: 2 Feature Cards (internal, external, media):  No. of cards that can be added =2, but the cards are Internal, external and Raw HTML Block

**Comment by alinai** [comment]
Passed in ODE and cms-test.

**Comment by alinai** [comment]
Looks good on ODE 647.
