### ISSUE TITLE
Enabler: Make workflow for validating successful ACSF update

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4006]
# PRs that add or update config/install/*.yml files must test Drupal Updating.
> **ESTIMATE** TBD

We have had NUMEROUS (at least 3, but more depending on how you want to count them) failures in importing configurations when deploying to ACSF Dev/Test during the `blt drupal:update` command. As a safe guard against this we need an efficient method of determining if production could be updated with the commits in this code base. This should be done with a github workflow.

The following steps should get us something like 80% confident that the update will work. We could increase this by actually viewing a page or trying to create a piece of content. Note we are not rebuilding the front-ends here to save time. Also note that we probably need to do something to get the `settings` working.
1. Checkout `master`
2. `composer install`
    * Nothing should be there, so no need to `composer cgov-clean`
4. `blt cgov:reinstall --no-interaction`
    * NOTE: you need content to be in the system for some of the types of failures to be found.
5. Checkout working branch
6. `composer cgov-clean && composer install`
7. `drush cr`
8. `blt drupal:update --no-interaction`

The main challenge is that this is at the very least like a 20 min process, so we don't want to run it all the time. We probably need  it for:
* Pull request changes where there modified `**/config/install/*.yml` file changes.
* Pull request changes where a `<module>/<module>.install` file has been modified.

Even this will be too much for multiple pushes, so any optimization there would be great. This should probably be done as a separate workflow in order to keep the, already long, CI workflow as quick as possible. It can range from 35-50min currently and we don't want it any longer. Additionally good use of composer caching should help speed up those steps, so it will be the `blt cgov:reinstall --no-interaction` that will take the most time.

**Comment by jfrank-nih** [comment]
The `paths` notation in the workflow will allow you to limit to certain files. Here's [GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore). Here's [an example in our code](https://github.com/NCIOCPL/ttc-search-app/blob/develop/.github/workflows/rss-workflow.yml).

**Comment by jfrank-nih** [comment]
[Concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) can be used to cancel previous runs in case of multiple pushes. Also in the example code above.
