### ISSUE TITLE
The gray caption box should not display under the image when new lines (no text) are entered in the "Caption" field

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#4018]
### Issue description

The gray caption box should **not** display under the image when new lines (no text) are entered in the "Caption" field.  We **do not set a credit**. The gray caption box should not display under the image.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Create an image 
2. On the "Caption" field, just enter bunch of new lines by hitting the enter key 9about 5 times) from the keyboard.
3. Do not set the credit.
4. Save

### What's the expected result?
- The gray caption box should **not** display under the image.

### What's the actual result?
- The gray caption box is displaying under the image.

### Additional details / screenshot
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/13b65605-79d9-49e2-840d-56b7ee3bc9fb)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/ba33f07e-8830-42aa-9c78-0fec8c3a5d44)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by andyvanavery31** [comment]
Decision that this use case is not to be expected by users, and therefore this ticket will be closed.
