### ISSUE TITLE
Logging out on PROD sends you to Okta Stage

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#4019]
### Issue description
Hitting the logout button on PROD or waiting for the session timeout sends you to the Okta staging environment rather than the production environment.

> **ESTIMATE** 

1

### Steps to reproduce the issue

1. Log in to Prod CMS 
2. Log out of PROD CMS
3. Expect to be on Okta Prod. Actually on Okta Stage.

**Comment by alinai** [comment]
@bryanpizzillo , @jfrank-nih ,tested and the test result was verified by @jfrank-nih. Thanks @jfrank-nih for confirming the test result!
