### ISSUE TITLE
Create YAML for News & Events

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4021]
## As a user, I want to see NCI's media resources, blogs, and events, so that I can be directed to timely content.

We need to build the English and Spanish YAML for the [News & Events comp](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=770-2948&mode=design&t=YjYW1VplgFhglTKt-0). The right rail is split up into three sections: (English) Media Resources, Cancer Currents, and Events. (Spanish) Recursos para medios de comunicación, Blog temas y relatos, and Eventos.

### DoR

- [x] Refine user story statement
- [x]  Create Scenarios (see comp)
- [x]  Internal review of any changes to the Design solution for nci-heading and its modifiers on Figma

### Resources:
* [Mockups](https://www.figma.com/file/XH87Z6GvJ0MWoX16l0FzKo/News-%26-Events-Landing-Page?type=design&node-id=770-2948&mode=design&t=YjYW1VplgFhglTKt-0)
* [Right Rail Links (English)](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.3/Project%20Management/Content%20Launch/Content%20Templates/News%20and%20Events%20landing%20page%20content%20template_English.docx?d=web82268ff51f468eb54619b05772bcc8&csf=1&web=1&e=MULHhn)
* [Right Rail Links (Spanish)](https://nih.sharepoint.com/:w:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.3/Project%20Management/Content%20Launch/Content%20Templates/News%20and%20Events%20landing%20page%20content%20template_Spanish.docx?d=w510b1709dcdb497e80bd227fef71ab22&csf=1&web=1&e=dgDEHj)

### Requirements

- There will be two YAML files created, one for English and one for Spanish
- The YAML will exactly match the comps (see link in Resources section)
- For the List item links:
  - Colors are consistent with links elsewhere 
  - Only underlined on hover (like megamenu)
  - `usa-list` unstyled for the list items
  - Buttons with icons are tracked in [#580](https://github.com/NCIOCPL/ncids/issues/580)

By default the raw HTML component will fire a set of analytics data based on what was built in [3902](https://github.com/NCIOCPL/cgov-digital-platform/issues/3902). These values can also be overridden by passing adding data attributes associated with a specific link to capture custom defined information. 

For the following values in the acceptance criteria, we will utilize the default values, so no data attributes will need to be added within each link:

- location: 'Body'
- componentType: 'Raw HTML'
- pageRows: total number of rows on the page overall
- pageRowIndex: the index of the selected row from the link click
- rowItems: Default is number of components in the row that was clicked. 
- rowItemIndex: Default is the index of the component in the rows that was clicked.
- componentTheme: Default is `Not Defined'
- linkText: Defaults to the text content of the link clicked.

I've listed these first in the acceptance criteria.

For the following values in the acceptance criteria, custom data attributes will need to be added to each link in the rawHTML block:

- title: This value should match the headings within the right rail based on where the link is
- linkType: This should be set based on the type of link (internal, external, or media).
- linkArea: This will pass 'Text' or 'Button' to based on the link clicked
- totalLinks: This will count the number of links under a given heading and set that value as a data attribute. For example, links in the Cancer Currents section should pass 2 for this value as there are two links.
- linkPosition: This will count the position of the link under the heading and set that value as a data attribute. For example, the 'View all blog posts' link would pass 1 under Cancer Currents and the 'Subscribe to blog' link should pass 2.

I've listed these second in the acceptance criteria.

### Acceptance Criteria
```gherkin
Scenario: Analytics event for the right rail on the News and Events Landing Page
Given a user is on the news and events landing page cancer.gov
When the user clicks on a link within the right rail section of the page built using the raw HTML component
Then there should be an NCIDataLayer Other event 
  And the event has the name “LP:RawHTML:LinkClick”
  And the event has the the linkname “LP:RawHTML:LinkClick”
  And this event should have the following data:
 | key | value|
    | location| Body|
    | pageRows| This should return the number of rows on the page overall. |
    | pageRowIndex | This should return the index of the row number on the page that was clicked |
    | rowItems| Default is number of components in the row that was clicked.  |
    | rowItemIndex | Default is the index of the component in the rows that was clicked. |
    | componentType| Defaults to 'Raw HTML' |
    | componentTheme | Default is `Not Defined' |
        | linkText | Defaults to the text content of the link clicked. Should match text of the link clicked. (I think this should make sense and be fine based on the comp, but let me know if there are any links that might pass something weird or would need this defined by a data attribute)  |

| componentVariant | Pass as a data attribute. Set to 'NewsEventsRightRail  |
    | title | This should be added as a data attribute and the value should reflect the headings within the right rail and match where the link exists, so 'Media Resources', Cancer Currents', or 'Events'  |
    | linkType | This should be added as a data attribute to each link in the raw HTML block and defined as `Internal`, `External`, or `Media` based on the type of link.|
    | linkArea | This should be added as a data attribute and set to either 'Text' or 'Button' based on the link clicked.   |
    | totalLinks | This should be added as a data attribute for each link and should count the number of links within each heading area. For example, links in the Cancer Currents section should pass 2 for this value as there are two links. |
    | linkPosition | This should be added as a data attribute for each link and should count the position of the link in each heading area. For example, the 'View all blog posts' link would pass 1 under Cancer Currents and the 'Subscribe to blog' link should pass 2. |
```

**Comment by welshja** [comment]
Per discussion with @arcepaul, @dev-rana-publicis, and @nicolecrom, two updates were discussed:

1. RowItems and rowItemIndex should consider all items within a 2 column layout as 1 "row". Though multiple components could be stacked within that column, we want to use these values to count the rows at the higher level. Other values will help us determine layout/position within the columns.

So, for the rawHTML in the right column on the News and Events landing page, the rowItems should be 2 and the rowItemIndex should be 2 based on the above.

2. @arcepaul, please update the totalLinks and linkPosition values on each of the links in the rawHTML block as follows: 

- totalLinks should count all the links within the rawHTML block as use that number (instead of by heading as described in the ticket)
- linkPosition should count position based on all the links and not just the ones within the parent heading.
