### ISSUE TITLE
Fix PHPStan issues with CmsProtectionSubscriber

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4027]
### Issue description
> **ESTIMATE** TBD

Basically this is what makes sure that going to www-cms.cancer.gov/foo as an unauthenticated user redirects to the login page. See #2014 for original requirements.

**Comment by santwuma** [comment]
Needs an ACSF environment for testing

**Comment by santwuma** [comment]
Closing - covered in #4026 and PR #4038
