### ISSUE TITLE
Enabler: Disable memcache on ODEs

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4033]
# Do not enable the memcache module when installing on an ODE.

ODEs become slow after some usage.  This _may_ be due to an issue with Acquia's memcache configuration.

We MUST have memcache on ACSF, so this ticket is about disabling it only when installing on an ODE.

**Approach**

We're going to patch the `memcache.settings.php` file (**Important:** According to `composer.lock`, we're currently using v1.1.0.).  

Near the top of the file, the script checks whether the memcache module is present and if so, it loads it (optionally setting it to use the memcached daemon).

The patch will add a condition, checking that the `AH_SITE_ENVIRONMENT` doesn't reflect an ODE.

> **ESTIMATE** TBD

### Resources:

- [memcache.settings.php](https://github.com/acquia/memcache-settings/blob/v1.1.0/memcache.settings.php)

### Notes

- The `memcache.settings.php` file comes in when the `composer install` step runs, so the patch will be applied by composer.
- The patch goes in `~/patches/acquia`, and then, the name should likely be `memcache.settings.php.patch`
- How to detect an ODE
From `docroot/sites/settings/cgov_caching.settings.php`

    ```php
      $env = $_ENV['AH_SITE_ENVIRONMENT'];
      if (preg_match('/^ode\d*$/', $env)) {
        $env = 'ode';
      }
    ```

### Testing Notes

There should be no changes in functionality.  The ODE may run slower, but it should no longer become completely unusable.

**Comment by SupriyaSaxena0605** [comment]
@Blair @Sandra T. All automated regression tests passed on ODE 627. We could create and verify Article successfully without slowness or ODE crashing. Thanks @Blair for fixing ODEs.

**Comment by santwuma** [comment]
Hold for release pending feedback from Acquia

**Comment by SupriyaSaxena0605** [comment]
@blairlearn Full regression passed on ODE 627 without breaking it.
