### ISSUE TITLE
Enabler: Update PHPStan issues in ResponseCacheSubscriber

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4053]
The EventSubscriber in `cgov_core/src/EventSubscriber/ResponseCacheSubscriber.php` needs to be updated. This should just be changing out RequestEvent.

This could be useless code, but it should set the cache time to live for various non-200 response codes. So this should be tested to make sure the following times are set. Additionally, Acquia can set cache times on their own, so an ODE might not match these. The times are basically:
  * 500 status codes should be cached for 1 minute. (60 seconds)
  * 301 redirects should be cached for 30 minutes (1800 seconds)
  * 302 redirects should be cached for 5 minutes (300 seconds) 

See #1811 

**Fixes for cache timeout values are moved to #4095**

> **ESTIMATE** TBD

**Comment by santwuma** [comment]
Needs requirements @sarinapadilla @andyvanavery31

**Comment by blairlearn** [comment]
Question to be resolved: What are the current, actual cache times?

**Comment by blairlearn** [comment]
Running curl against the origin server yields these cache-control headers:
(e.g. `curl -vvvv https://www.cancer.gov/chicken --resolve www.cancer.gov:443:<origin_ip>  --insecure`)

status 301 - `Cache-Control: max-age=900, public` (15 minutes)
status 404 - `Cache-Control: max-age=16588800, public` (192 days!)`
