### ISSUE TITLE
Fix PHPstan issues with ICS- iCalendar file

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#4068]
File to fix:

- /var/www/docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php

**Comment by SupriyaSaxena0605** [comment]
@santwuma @blairl-nih This ticket is working fine on Test-ac. Regression tests as well as manual tests pass on Test-ac.
