### ISSUE TITLE
Implement Notification Area & Display on all pages

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#407]
This story is to create the common display element - Notification Area
* Notifications needs an area on the page that appears on all pages across the site
   * Users should be able to add content blocks and raw html to the notifications section (for Site Notices and Emergency Banners)
      * Content is displayed above the site banner as full width on desktop
      * More than one banner or content block may be displayed
      * Display content with smaller text on mobile

**Comment by lburack** [comment]
Tested English AND Spanish with Brendan and this passes!
