### ISSUE TITLE
Fix phpstan Drupal 10 deprecation in cgov_core.module

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#4073]
Relying on entity queries to check access by default is deprecated in drupal:9.2.0 and an error will be thrown from drupal:10.0.0. Call \Drupal\Core\Entity\Query\QueryInterface::accessCheck() with TRUE or FALSE to specify whether access should be checked.

ODE: https://ncigovcdode642.prod.acquia-sites.com/

**Comment by SupriyaSaxena0605** [comment]
@blairlearn @navsunka @santwuma Visual regression and Functional regression passed on ODE 642.
