### ISSUE TITLE
Resolved with CK-Editor-4- Intro Text and Body section Alignment issue on the CMS

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#4099]
When we just click the "Edit" button and the content is loaded in edit mode, the Body section (Heading and Content) field and the Intro Text field are not aligned to each other. Tools does not wrap to the next line or does not appear collapsed under the drop-down (three dots) in the Body section (Content) field. Once we enter contents (type "test") to the ck-editor or click inside the ck-editor and then scroll down and then up, the Body section (Heading and Content) field and the Intro Text field gets aligned to each other. Is it ok?

Steps to reproduce:

1. Click Contents -> Add Contents-> Article
2. Scroll down to see that the Intro text WYSIWYG and Body Section is not aligned.
3. Notice that all the buttons in the tool bar (including the embedding buttons/icons) are visible.
4. Scroll to the bottom of the screen and then scroll up to the Body Section area
5. Still the Intro text WYSIWYG and Body Section is not aligned and all the buttons in the tool bar (including the embedding buttons/icons) are visible.
6. Now, just click inside the "Contents" WYSIWYG
7. Scroll all the way down
8. Scroll up and at one point you will see that the tool bar of the CK Editor rises up the menu bar (Screen-shot#2)   (https://github.com/orgs/NCIOCPL/projects/52/views/1?pane=issue&itemId=41369207)
9. Scroll up to the "Contents" WYSIWYG area under the Body Section
10. Notice that the the buttons (image, infographic, video, Insert Block Content, Insert Featured content, Glossify, Source) appear under the drop-down (that appears as three-dots) in the tool bar.

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/6ef822ac-57f3-49b7-a72a-c656419a02dd)

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/b6d08f9d-3863-4feb-afc8-232830a6b1bf)

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/00bbc85c-1b88-4961-927c-da25b7a36ea0)

**Comment by santwuma** [comment]
Presenting on:
Browser               Mac                               PC

**Comment by blairlearn** [comment]
A potential clue - the floating toolbar problem only happens if the Content field has focus, that is, the cursor is actually in the field.

**Comment by alinai** [comment]
@navsunka , When we click on the CK Editor and keep scrolling down until we are at the end of the CK Editor, the tool bar of the CK Editor moves up and covers the tool bar of the menu bar.




![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/c3e2e1b7-f7d3-45a7-a874-2720ca7b665e)



![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/e506363e-31f5-4635-84e4-d7ed77fdb83a)

**Comment by alinai** [comment]
Looks good with Ck Editor4
