### ISSUE TITLE
CK-Editor 5 isn't respecting field widgets row settings

### ISSUE THREAD

**Issue by navsunka** [NCIOCPL/cgov-digital-platform#4105]
### Issue description
*When you create a new node with CKEditor 5, the body field is only 1 row (when no content is entered).*

drupal.org issue: https://www.drupal.org/project/drupal/issues/3241295

**Comment by alinai** [comment]
@navsunka , Now seeing No. of Rows =5 for Intro Text field. Please confirm this is the expectation from this ticket?

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/96afcfab-74d8-4b6b-adea-87d1fe4228c9)

**Comment by alinai** [comment]
Verified that the row height for CK Editor has been increased on the ODE compared to cms-test.
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/c733b962-9048-4e37-8e36-66e6dcb78a59)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/0e19b734-3c15-4fe1-a9fc-55a6819a173d)

**Comment by santwuma** [comment]
Passed on ODE
