### ISSUE TITLE
Switch simplesamlphp_auth to saml_auth

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#4116]
Update the SAML Service Provider from `simplesamlphp_auth` to `samlauth`. `simplesamlphp_auth` can't be upgraded until we're on Drupal 10 and we want to verify as many modules as possible _before_ upgrading to Durpal 10. Also, `samlauth` is a simpler configuration without the extra SimpleSAMLphp standalone application in place.

### Existing Requirements

- Replicate existing SAML activity with Okta
    - Ability to log in with Okta
    - Log out button and autologout still work

### Bonus Requirements

- Add a SAML login button to the normal `/user/login` page
- If the site supports Okta login the user will just see “Log in with PIV/SSO” and there will be a link for “Log in with Drupal”.
    - When the user clicks the “Log in with Drupal login” link, they are taken back to the /user/login page, but with `?show_login_fields=true`, and then the User/Password/Submit button will appear. 
    - On the `/user/login?show_login_fields=true` page there will be a "Log in with Single Sign-on" link to return to the page with the "Log in with PIV/SSO" button
- If the site does not support Okta (e.g., ODEs)
    - The user will just see User/Password/Submit button
    - The ?show_login_fields=true param will not change anything, but will also not break anything.

## Testing

- [ ] Verify that logging in and out as an SSO user works
- [ ] Verify that logging in and out as a non-SSO user works
- [ ] Verify that no other functionality has broken
- [ ] Verify that the `/user/login` page behaves per the Bonus Requirements above

## Changes Needed

- Remove `simplesamlphp_auth`
- Install `samlauth`
- Update `cgov_saml_auth_config`
- Set up local development with the ability to test SSO

## Deployment Steps

- [x] Ensure that non-SSO users are cleaned up and disabled where needed
- [ ] On each site run `/var/www/html/<tier>/vendor/bin$ ./drush --uri=<site>.<tier>ncigov.acsitefactory.com pmu simplesamlphp_auth`
- In Okta:
    - Update General/SAML Settings
        - [ ] Change Single Sign-On URL to `https://tier.cancer.gov/<path?/>saml/acs`
            - Note! If it is a path based microsite, you need to include that
        - [ ] Change entity ID to `https://tier.cancer.gov`
    - Update General/App Settings
        - [ ] Hide the application from being visible to users
    - Go to Sign on Tab
        - [ ] Beside the active certificate click Actions > View IDP metadata
        - [ ] Download the XML and save as <tier>.xml
- [ ] Deploy branch that contains `samlauth` using the ACSF console
- On the Acquia host:
    - [ ] Remove `saml/config` folder
    - [ ] Remove contents of `saml/idp-metadata`
    - For each site:
        - [ ] Upload `/mnt/files/<tier>/saml/idp-metadata/<tier>.xml`
        - [ ] Run the `saml_convert.php` script: `php /var/www/html/<tier>/scripts/utility/saml_convert.php <xml filename without extension>`

**Comment by alinai** [comment]
@jfrank-nih , This looks good on test-ac and cms-dev. Thanks! cc: @KateMashkinaNIH
