### ISSUE TITLE
Enabler: Replace EOL CKEditor4 with the LTS CKEditor.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4122]
# Replace EOL CKEditor4 with the LTS CKEditor.

CKEditor5 is not presently in a state to support our requirements. We need to switch to the [external ckeditor module](https://www.drupal.org/project/ckeditor) (as opposed to the EOL one in Drupal core).

**Comment by alinai** [comment]
Looks good on ODE 647.
