### ISSUE TITLE
Opening images from CMS gets 404 status

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4133]
### Issue description
Image URLs containing spaces are double-url encoded.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Login to the CMS
2. Go to `Content` > `Media` > `Add Media` > `Image` (`/media/add/cgov_image`)
3. Upload an image with a file name containing spaces (e.g. `A photo of a person.jpg`)
4. Fill out the other required fields as well
5. Select required crops.
6. Click the `Save` button.
7. Find the new image in the list of media items.
8. Click on the "Media Name".

### What's the expected result?
- The image displays

### What's the actual result?
- A "Not Found" (status 404) message appears.  The spaces in the URL are incorrectly encoded.  Instead of `%20`, they're coming out as `%2520`.

### Additional details / screenshot

This regression appears to have started between `v2.9.1` and `v2.10.0`.

**Comment by SupriyaSaxena0605** [comment]
@dev-rana-publicis This looks good on ODE. Checked all the following:
-Run regression 
manually test creating new images with various file names that include characters ( test space.jpg,test_underscore-and-dash.jpeg, space%20encoded.jpeg, test!.jpeg 
 Create images with above names  - embed them all in the single article, make sure to have console open to catch any errors
Create a home and landing page with ncids template, add NCIDS 2 guide card row and upload those images - make sure there are no errors
Spotted no new error on Console while creating image, article or landing page. cc: @KateMashkinaNIH
