### ISSUE TITLE
Spanish Translation - Warning message appears between the Intro text and Header when we edit the Body Section

### ISSUE THREAD

**Issue by navsunka** [NCIOCPL/cgov-digital-platform#4134]
On the Spanish Translation warning message appears between the Intro text and Header when we edit the Body Section. Earlier we used to see only 1 warning message at the top of the page.

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/bcebe964-3e26-4d6c-9606-bdb76bed9957)

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/668cba49-d796-4bac-9fe2-6e6cb1404cca)

This is known issue which got fixed in Drupal core 11.x-dev. Applying patch which is available for version 9.5.x

Issue link: https://www.drupal.org/project/drupal/issues/3002571

**Comment by navsunka** [comment]
@alinai, Earlier we are seeing same warning message couple of times on node edit form. After the fix, we should not see multiple warning messages when having untranslatable fields.

**Comment by alinai** [comment]
@navsunka . This looks good on ODE 647. Verified the following:
1) Multiple warning messages does NOT appear when we "Edit" a paragraph and we can see only 1 warning message at the top of the content page in edit mode (as expected and same behavior as the existing system).  
2) In the collapsed state , the non-breaking spaces are not appearing in the field values of the paragraph beside the paragraph name.

Noticed one more change with this issue being fixed: 
(https://github.com/orgs/NCIOCPL/projects/52/views/1?pane=issue&itemId=43121856)

@laurelthrash , @sarinapadilla - please confirm if the new button "Edit all" described in https://github.com/orgs/NCIOCPL/projects/52/views/1?pane=issue&itemId=43121856 looks good to you.

**Comment by laurelthrash** [comment]
The "Edit all" function on ODE 647 looks good and was verified by @laurelthrash @sarinapadilla @lburack.

**Comment by alinai** [comment]
> The "Edit all" function on ODE 647 looks good and was verified by @laurelthrash @sarinapadilla @lburack.

Thanks @laurelthrash for confirming!

**Comment by alinai** [comment]
Looks good on ODE 647.
