### ISSUE TITLE
Change the Twitter Logo on the Bio content type 

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#4147]
There is new HHS guidance which states that the Twitter logo should be replaced with the X logo on Federal websites.

1. Please identify the current twitter logos used within cancer.gov within the sprites
2. Replace these logos to be the new X logo (@bennettcc can help connect you with a designer to provide the needed logos once you determine what you need)
3. Please update the accessible text/label that accompanies the X logo to be "Follow on X."

As an example, here is a bio page which currently shows the twitter logo: https://dceg.cancer.gov/about/staff-directory/barnholtz-sloan-jill

**Comment by bennettcc** [comment]
Information shared by Bryan on 10/31: 
1. To change the logo: yes, a release is needed to change the logo. we should also change the label associated with that logo for accessibility (Cam to verify with the Feds)
2. low LOE: about 20 min code change then the standard building + testing process for a release

**Comment by arcepaul** [comment]
@zhuomingao 
We are trying to determine if the Custom tweet/tweet this that can be added in content is being used anywhere.  If not, then it can be safely removed.  Would you please search content for the css class `social-share--custom-tweet`?  This would be content for anywhere using the platform.
