### ISSUE TITLE
Cgov_common needs to move to use stable9

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4151]
### Issue description
> **ESTIMATE** TBD

`stable` has been removed from D10. `stable9` is the new replacement. Who knows what this might break.

**Comment by santwuma** [comment]
Can not be tested on ODE. It's a legacy feature for DCEG connect and has be to tested on DCEG Connect ACSF.

**Comment by KateMashkinaNIH** [comment]
Automated regression passed, plus QA performed visual comparison between https://www-test-acsf.cancer.gov/connect-prevention-study and https://www-dev-acsf.cancer.gov/connect-prevention-study and found no discrepancies
