### ISSUE TITLE
Drush 12 does not support drush launcher.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4171]
### Issue description
> **ESTIMATE** TBD

#### Container

In our container we use [drush-launcher](https://github.com/drush-ops/drush-launcher), which basically tries to find the closest drush to your repo root. So if you are buried 10 levels deep in the front-end theme, a `drush cr` is going to work. With drush 12 this no longer works. 

Since our container only has 1 codebase, we can probably just add `/var/www/vendor/bin` to the `$PATH` and call it a day. This will also put BLT on the path too... This however will not fix the problem elsewhere, but this ticket is not for that.

#### Cloud hooks (`hooks/common/**` structure)

The cloud hooks (e.g. hooks/common/post-code-deploy/post-code-deploy.sh) modify the path to include vendor/bin. No modification is needed.

#### Factory hooks (`factory-hooks/**` structure)

The factory hooks (e.g. post-site-install.sh) invoke blt  directly from the vendor directory in which they were installed. (i.e. `blt="/mnt/www/html/$sitegroup.$env/vendor/acquia/blt/bin/blt"`).

However, the scripts in `vendor/bin` are nothing more than proxies which invoke the scripts from their installation directories. (i.e. the blt script is a PHP file which executes return include __DIR__ . '/..'.'/acquia/blt/bin/blt';

#### CI workfklow

In the CI workflow, it is necessary to add the vendor/bin directory to the path.

In the "Test Ability to Deploy" workflow, it is necessary to add the vendor/bin directory to the path. Additionally, it is also necessary to modify the "Does this workflow need to run?" logic to check whether the workflow itself has changed.

**Comment by blairlearn** [comment]
Removed blt and drush launchers from the Docker container, and also the GitHub workflows, putting `vendor/bin` on the path so scripts don't need to be changed.

The cloud hooks (e.g. `hooks/common/post-code-deploy/post-code-deploy.sh`) modify the path to include `vendor/bin`. No modification is needed.

The factory hooks (e.g. `post-site-install.sh`) invoke `blt ` directly from the vendor directory in which they were installed. (i.e. `blt="/mnt/www/html/$sitegroup.$env/vendor/acquia/blt/bin/blt"`).

No modification is needed for the factory hooks however as the scripts in `vendor/bin` are nothing more than proxies which invoke the scripts from their installation directories.  (i.e. the `blt` script is a PHP file which executes `return include __DIR__ . '/..'.'/acquia/blt/bin/blt';`
