### ISSUE TITLE
Update NCIDS to 2.4.x

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4192]
### Issue description
For the 2.3 release of NCIDS components on the digital platform, we need to update the `ncids` package to 2.4.x.

> **ESTIMATE** TBD

### What's the expected change?
- The `ncids` package is updated to version 2.4.x.

### What's the current functionality?
- The `ncids` package uses version 2.2.0.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bryanpizzillo** [comment]
@sarinapadilla or @olitharp-nci - Can we also note any required changed for this update? e.g the banner template should be updated to reflect the new markup. Where there any other changes that need to be completed with this package bump?

**Comment by olitharp-nci** [comment]
[v2.4.0](https://github.com/NCIOCPL/ncids/releases/tag/v2.4.0) backwards compatible changes to markdown

#1394 Banner component 
```diff
- <section class="usa-banner usa-banner--nci-banner" class="usa-banner" aria-label="Official government website">
+ <section class="usa-banner" class="usa-banner" aria-label="Official government website">
```

#1399 Site alert component
```diff
<section
	aria-label="Standard information site alert example with close"
	class="usa-site-alert usa-site-alert--nci-standard usa-site-alert--nci-info"
-	id="site-alert-example6"
	data-site-alert-closable="true"
>
	<div class="usa-alert">
		<div class="usa-alert__body">
			<div class="usa-alert__nci-header">
				<h3 class="usa-alert__heading">COVID-19 resources.</h3>
			</div>
-			<div class="usa-alert__nci-content" id="site-alert-content">
+			<div class="usa-alert__nci-content">
				<ul class="usa-alert__nci-list">
					<li>
```
