### ISSUE TITLE
Spike: Investigate how to add CSS/JS to a single Home and Landing page

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4207]
## In order to implement the functionality of the combo box on the Cancer Types landing page, a developer needs to determine an approach for adding CSS/JS to a single Home and Landing page without overloading other H&L pages.
> **Estimate** *# point* 

### Bryan Notes
* This should really be adding a Drupal Library to the page. As in attach_library.
* It would be nice if you could select the library from a dropdown...
* it would be even nicer if you could select multiple libraries

### Expected Deliverables:
* A new enabler ticket outlining the approach to implement the findings from this spike

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

- We can create a new filed within our `cgov_home_landing` form display that gets populated with all libraries associated with the theme of the page (in this case, we would be targeting `ncids_trans`). 
- In the fields storage config, add in the name of the [`allowed_values_function`](https://chromatichq.com/insights/dynamic-default-and-allowed-values-list-fields-drupal-8/) and implement that function within `cgov_home_landing`. This function will populate the drop down with all the libraries associated with the theme. 
  - I was having trouble loading in a different theme within this function as [ThemeManager](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Theme%21ThemeManager.php/class/ThemeManager/8.2.x) only deals with the current active theme, which in this case would always be `cgov_admin` as we are inside the CMS.
- We would need to create a new library that has the javascript and css that we would want to use on a specific page for the Cancer Types Landing Pages - [Drupal Documentation](https://www.drupal.org/node/2274843#define-library)
- Once a library is selected from the drop down, we would use [`hook_page_attachments`](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_page_attachments/8.0.x) to attach the javascript that we selected to the correct page on our site.

**Comment by bryanpizzillo** [comment]
@dev-rana-publicis as you seem to be stuck getting libraries, try out:
```
$themesvc = \Drupal::service('theme_handler');
$front_end_theme = $themesvc->getDefault();
$disco = \Drupal::service('library.discovery');
$libs = $disco->getLibrariesByExtension($front_end_theme);
```

The "default" theme for a site is the front-end theme. It should never return the admin theme even if it runs in the admin. 

One thing is you can try this in `drush php`. That command opens up a PHP REPL prompt with all of Drupal available. It makes it easy to try out some of these types of things.

(REPL is "Read, Evaluate, Print, and Loop" and not limited to PHP, you can find a REPL prompt for many languages.)

**Comment by bennettcc** [comment]
Closing this ticket - the spike is complete. New ticket will be created for implementation
