### ISSUE TITLE
Enabler: Split BLT reinstall command in two

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#4208]
Splitting the current `blt cgov:reinstall` into two, and changing it into a combined command.

* `blt cgov:install-drupal`
* `blt cgov:install-content`
* `blt cgov:reinstall` 

Here is the current command:

https://github.com/NCIOCPL/cgov-digital-platform/blob/0867ed128618e3a78298e7d87fbac5c897fe99f3/blt/src/Blt/Plugin/Commands/SlevenCommands.php#L13-L32

The `install-drupal` command should have:

* Drupal install
* Load users
* Translate locales

The `install-content` content command should have the remaining commands:

* Install content
* Load front-end globals
* Load glossifier

The `reinstall` should just call the other two in order to achieve a site installed with content.

## Testing

* Regressions 
* For devs: run `cgov:reinstall` locally and verify you get the same content

## Notes

**Comment by laurelthrash** [comment]
This ticket does not have any dependencies.
