### ISSUE TITLE
Enabler: Update cgov:reinstall to use artifact:install:drupal

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/cgov-digital-platform#4209]
## Change

Update `blt cgov:reinstall` to use `artifact:install:drupal` instead of `drupal:install`

https://github.com/NCIOCPL/cgov-digital-platform/blob/0867ed128618e3a78298e7d87fbac5c897fe99f3/blt/src/Blt/Plugin/Commands/SlevenCommands.php#L21

Make sure that reinstalling on local dev works as expected.

## Testing

- Standard regression tests

## Background

> ODEs use artifact:install:drupal and local uses drupal:install. They both are, for all intents and purpose, doing the same thing. The only difference is if we enable the multisite flag on an ODE. If an ODE uses multisite, then the local environment should as well.
> When might we use multisite on an ODE and local? If we had to have 2 profiles or themes. Back when we were working on the redesign we had a ticket for figuring out to to have 2 installed sites, one with ncids_trans and the other with cgov_common . However, we changed the scope such that only DCEG Connect was on cgov_common and dropped the ticket. So it is a thing.
> Isn't ACSF multisite? Not for the purposes of BLT.
> TODO:
> I want to say change cgov:reinstall to call artifact:install:drupal so that if we have multisite in the future we don't have to change the command then. (more so, so we don't have to wonder why it does not work when we change the blt.yml)

**Comment by laurelthrash** [comment]
This ticket does not have any dependencies.
