### ISSUE TITLE
Site Admins, and probably others, Can delete Block Content types from the site.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4229]
### Issue description
> **ESTIMATE** TBD

This is some artifact of the new block permissions and we must have missed removing one or more than one. People should only be able to edit block_content content items, NOT modify the block types. They should very much not be allowed to delete the content types. See the screen shot below that we can see. No one should have access to the block types menu item at all.

Developer note: you will need to modify the install hook for new sites and make an update hook to handle existing sites.

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/11215649/7282784a-cd60-46f4-883f-6ac6391bfc0b)

**Comment by navsunka** [comment]
Note:
- administer block types, administer block content  permissions should not exist in the _cgov_core_install_permissions function which is present in cgov_core.install file. 
- This issue is only affecting existing sites.

**Comment by KateMashkinaNIH** [comment]
Confirmed issue is resolved on prod 
![image (3)](https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/0da77a0b-a585-452a-b4b3-5bd50e095fc1)
![image (2)](https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/cd8cabe0-5e9b-4ce7-b7ce-8751cad7abe8)
