### ISSUE TITLE
Spike: Investigate schema.org Site Name for Google Results for "unbranded" sites

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4237]
### Notes

- This could be used for more than unbranded sites, but we may be able to control the site name in Google search results. https://developers.google.com/search/docs/appearance/site-names

In the case of the following screenshot, if the "- NCI" is removed, then currently the site name is "National Cancer Institute (.gov) and it should become "National Cancer Plan (.gov)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/143126208/4a1cb88b-a661-46d8-bd39-8483cf4d92a3)

### Expected Deliverables:

* An analysis of the impact of the use of "unbranded" sites on SEO
* An analysis of behavior changes that we need to know when using "unbranded" sites

### Results of Spike
As per documentation(https://developers.google.com/search/docs/appearance/site-names), we have to include Json-ld Schema of website type  & google serps will read this json to display sitename.
There is one contrib module which can help us to achieve this (https://www.drupal.org/project/schema_metatag), there is a submodule of this which we have to enable(https://www.drupal.org/project/schema_metatag).
this will add one fieldset inside metatags configs in which we have to add name, id,url & select website as type.
As this module depends on metatag, current Metatag module version is 8.x-1.26 so we need to install schema_metatag 8x-2.5.
As we can't test locally, so we need to test this may be in prod.
if above works fine than we can think of setting this custom sitename in our custom config & we can create new tokens for that to replace that value.

**Output from SEO Review:** any impact of removing the branding of site name from schema.org is already occurring and we should not see a large impact on our SEO rankings. Google determines and sets the value of the page as it sees fit (like what is happening for NCP currently). We can consider the spike completed and advance to the actual ticket.

**Comment by andyvanavery31** [comment]
Spike completed.
