### ISSUE TITLE
[Meta] We need to be able to create web sites without NCI branding.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4238]
We currently can change many things like a sites logo and footer to not include NCI branding, but there are still items that sneak through. This is a meta for all. 

TODO: Find all items that need to change.

- [x] #4233 
- [x] #4237
- [x] #4246
- [x] #4247
- [x] #4300 
- [x] #4335

**Comment by andyvanavery31** [comment]
All tickets in Meta were completed.
