### ISSUE TITLE
Remove CSS Patch for Icon Button

### ISSUE THREAD

**Issue by dlescarbeau** [NCIOCPL/cgov-digital-platform#4242]
Per the developer notes on [this ticket in NCIDS](https://github.com/NCIOCPL/ncids/issues/1458), remove the patch below from home and landing page CSS (once [the PR addressing this](https://github.com/NCIOCPL/ncids/pull/1519) is merged). 
`
.usa-button--nci-icon.usa-button--nci-full-width {
	@include u-display('block');

	.usa-icon {
		float: left;
	}

	> span {
		display: inline-block;
		width: calc(100% - 48px);
	}
}
`

### Acceptance Criteria
`ncids-home-landing.scss` should have the above code removed once the code has been moved to the NCIDS via [this PR](https://github.com/NCIOCPL/ncids/pull/1519).

### Notes
The buttons' look/feel should not change, we're simply moving the code from digital-platform to the NCIDS.

**Comment by bryanpizzillo** [comment]
This was closed by #4298
