### ISSUE TITLE
SPIKE: Convert Favicons From Hardcoded in the Page Template to be Selectable

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4246]
**NOTE:** This is a spike/research story.

### Request Description
Favicons are currently hardcoded into the page template. This request is to change their implementation so that they can be set on a per-site basis with a default to the NCI luggage tag if the favicon is not overridden. Note: favicon are all of the icons - which includes apple icons and other unimportant ones.

### Technical Notes
- Should fix #3893 upon completion of this ticket. Whatever solution we pick shall /favicon.ico shall be set to the correct favicon in those cases
- There is a constraint the micro sites under www will need to have their favicon's set, but it will not be able to override the /favicon.ico (i.e. all microsites under the same root should have the exact same favicon)
  - **Requirement:** In our implementation we will set a theme folder that will be the root website. For pages under the root website, they will generate paths for the root website's files

### What is the Expected Change?
- Favicons will be set as the NCI luggage tag as default.
- Favicons will be able to be set on a per-site basis by overriding the default favicon

### What is the Current Functionality?
- Favicons are hardcoded in the page template

### Tasks

- [ ] @navsunka please investigate what modules set the "icons" and what options exist. First step is to find out what Drupal or a third-party module do, then verify against one of the sources listed below in the Notes section.

### What is the Updated Acceptance Criteria?
```gherkin
Scenario: An individual searching for a site on the Digital Platform sees the favicon of an NCI site in their Search Engine Results
  Given a user is on a search engine
    And they have searched for cancer.gov
  When the user is on the search engine results page
  Then the user will see the NCI favicon on the search result for cancer.gov
  When the user clicks the link of the page with the NCI favicon
  Then the tab that is opened of cancer.gov will show the NCI favicon
```

```gherkin
Scenario: An individual searching for a site on the Digital Platform sees a favicon for a site that does not use the NCI favicon in their Search Engine Results
  Given a user is on a search engine
    And they have searched for a site on the digital platform that does not use the NCI favicon
  When the user is on the search engine results page
  Then the user will see the custom favicon for the page that does not use the NCI favicon
  When the user clicks on the link of the page with the non-NCI favicon
  Then the tab that is opened will show the non-NCI favicon on the tab
```

```gherkin
Scenario: A site admin edits the favicon for a site within the Digital Platform
  Given the favicon is an editable field
    And the user is logged in as a site admin
  When the user chooses the NCI favicon
  Then the NCI favicon will appear in Search Engine results
    And the NCI favicon will appear on the tabs of pages opened with the NCI favicon selected
  When the user chooses a non-NCI favicon
  Then the selected non-NCI favicon will appear in Search Engine results
    And the selected non-NCI favicon will appear on the tabs of pages opened with the non-NCI favicon selected
  When the user does not make a selection of the favicon
  Then the favicon will default to the NCI favicon
    And the NCI favicon will appear in Search Engine results
    And the NCI favicon will appear in the tabs of pages without a favicon selection
```

### Notes
- There is not an easily accessible list of the specific icons/metatags from Googling, however they will be needed
- Some sources for information may be:
    - https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
    - https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/
- If Drupal has something built in, it is most likely out of date. If there is something built in/third party, we will most likely need to deal with what they do.
- Another thing found by Bryan:

> 
    <link rel="apple-touch-icon" sizes="180x180" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/apple-touch-icon.png?v=1" />
    <link rel="icon" type="image/png" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon-32x32.png?v=1" sizes="32x32" />
    <link rel="icon" type="image/png" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon-16x16.png?v=1" sizes="16x16" />
    <link rel="mask-icon" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/safari-pinned-tab.svg?v=1" color="#c0143c" />
    <link rel="shortcut icon" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon.ico?v=1" />
<link rel="icon" href="/core/misc/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="icon" href="/core/misc/favicon.ico" type="image/vnd.microsoft.icon" />
<meta name="msapplication-config" content="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/browserconfig.xml?v=1" />

**Comment by santwuma** [comment]
Automation ticket - for any Drupal dev

**Comment by blairlearn** [comment]
Preliminary notes on the `responsive_favicons` module.

`drupal.org/project/responsive_favicons`

Limitations/Issues:
- Does not support custom favicons on path-based domains (e.g. cancer.gov/nano).
- Does not clear cache when the form is saved.
- Does not log any messages to tell you why it suppressed one of the link tags.
- We'd likely want to create a patch to remove the `realfavicongenerator.net` "ad."

# Process for setting the icons on a top-level domain

1. Generate the zip file with icons (see below), specifying that the icons will be put in `/sites/default/files/favicons`.
	1. Be sure to save the generated tags.
3. Login to the CMS site
4. Go to `Configuration` > `User interface` > `Responsive favicons`
5. Set the inputs:
	- Favicions location: Uplaod zip file
	- Path to favicon files: `/sites/default/files/favicons`
	- Favicon tags: Paste in the generated tags
6. Under "Upload a zip file", click "Choose File" and browse to the generated zip file.
7. Click the "Save configuration" button.
8. Clear the site's Drupal and Varnish caches
9. If applicable, clear the site's Akamai cache
10. 

# Process for creating icons with `realfavicongenerator.net` 

URL: https://realfavicongenerator.net/


- Upload the source image ("Select your Favicon image" button)
	- Needs to be at least 70x70, preferably 260x260
- Adjust parameters
  - On the settings tab: margins and background colors as needed for the different platforms. (This will require designer input)
  - Android has manifest options for "Add to Homescreen"
- Under Favicon Generator options
	- Choose "I cannot place favicon files at the root of my web site."
	- Specify the site upload directory (`/sites/default/files/favicons`)
- Generate and download the  favicon zip file.

**Notes:**
- Includes adjustments for quirks of some OS versions, this seems to be based on older versions (e.g. iOS 7, Android Chrome 39)
- [The code in GitHub](https://github.com/RealFaviconGenerator/realfavicongenerator) is just the web site, not the actual generator.  It's at least four years old; there have been no releases in 5 1/2 years.


# CLI interface

GitHub: https://github.com/RealFaviconGenerator/cli-real-favicon

- This is an npm package that's installed as a global tool.
- It's not super robust (e.g. crashes when command line arguments are missing), but does seem to get the job done
- Takes inputs from a JSON file.
	- Unwanted icons can be omitted and will not be generated.
	- Most (but not all) values from the web UI can be found in the sample document (e.g. OS-specific images).
		- The web UI submits a JSON document which loosely maps to the names in the sample document
		- snake_case names map to camelCaseNames
		- the overall webui JSON is loosely the API document's `design` property

**Comment by santwuma** [comment]
This spike is complete. @blairlearn to create dev ticket before we close this.

**Comment by andyvanavery31** [comment]
Spike completed.
