### ISSUE TITLE
Technical Item: Create Citation Pub Med ID Common Field 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#426]
This story is to create the [Citation Pub Med ID](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#citation-pub-med-id) common field.

The Citation Pub Med ID will allow only numbers and will be used to create a link to the pub med content.

**Comment by VictoriaSunNIH** [comment]
This will not be implemented as a common field,it has already been implemented as a field on the paragraph type for citations.  Closing this ticket.
