### ISSUE TITLE
Spike: Investigate LOE to Implement Taxonomies to Populate Dynamic Lists

### ISSUE THREAD

**Issue by laurelthrash** [NCIOCPL/cgov-digital-platform#4260]
## In order to determine if we want to implement taxonomies that populate dynamic lists, IAs, designers, Product Managers, and developers, need to explore what we would like to implement and the associated LOE.
> **Estimate** SP TBD | *NOTE: a single story point is about 1 day.  A spike should not go on for more than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.*

### Expected Deliverables:
* *Information to better determine feasibility of using taxonomies to populate dynamic lists*
* *An idea of how we would recommend implementing the taxonomies to populate Dynamic Lists*
* *Development implications if we implement taxonomies to populate Dynamic Lists*

### Additional Notes:
* During our end of sprint retro on 10/4, the team demoed a competitive analysis report for the News & Events landing page. In the discussion, the federal team indicated renewed interest in using taxonomies to generate content in dynamic lists. Though this idea has come up in previous discussions, we have yet to adopt and implement this due to other factors at the time. Now we want to investigate what would go into the implementation of using taxonomies to generate dynamic lists and determine if we want to prioritize this in the near future, given the targeted LOE and other implications. 
* Per retro on 10/4, recommend starting with CGov taxonomies first (prior to exploring this with the DOCs). This is in response to the suggestion that we socialize dynamic content to DOCs and prepare them for benefits and limitations ([retro board here](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1664456499911/ee459f967d8a85397ff3d2b951114d60648c9b10?sender=uc8881d65820946a13d002641)).
* Related ticket: NCIOCPL/ncids#482 

### Results of Spike
*Enter the information, or links to any (non-sensitive) files with the findings here*

**Comment by andyvanavery31** [comment]
This is not going to be investigated further at this time. Closing this ticket. In the future, a similar ticket can be opened with clearer direction for the goal.
