### ISSUE TITLE
Enabler: Update to newest version of NCIDS

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4268]
# Update to newest NCIDS version
For the 2.4 release of NCIDS components on the digital platform, we need to update the `ncids` package to `<insert package number here>`.

* Remove `--nci-side-nav` modifier from `usa-side-nav`

> **ESTIMATE** TBD

**Comment by bryanpizzillo** [comment]
This will be targeting 2.6.0. The main cleanup changes will be:
1. Switch from using `@nciocpl/ncids-js` and instead use the specific modules. (e.g. `@nciocpl/ncids-js/nci-header`, `@nciocpl/ncids-js/usa-site-alert`, `@nciocpl/ncids-js/usa-footer`, `@nciocpl/ncids-js/nci-autocomplete`) in imports.
2. Rename all "Adaptor" classes to "Adapter"
3. Update nci-header to use: `nci-header--megamenu` and change the id from https://github.com/NCIOCPL/ncids/commit/5eba98317882093be72ecbe5f82fafdc1826a8d1
    * There were other HTML changes in the mdx, but it looks like they were to match
4. Remove `usa-sidenav--nci-sidenav"` from the sidenav
5.  



> ![NOTE]
> Site Alert is actually HTML copied in as raw html, so there should be no HTML in the ODE content or Drupal templates
