### ISSUE TITLE
Highchart PDF Export Issues

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#4283]
### Issue description

1. When some charts are downloaded, the chart title is cut off in the exported PDF file. An example of this can be seen when the export hamburger menu is clicked in a chart with the "Download PDF document" option selected for the [NRSA chart](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/nrsa)

2. For [Grants & Awards Contract chart](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/grant-contract-awards), the exported PDF file has some of the state names (e,g, PR, GU) blending with the background color of the states. Hence not making them quite legible.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by seyilonge-nci** [comment]
This actually applies to all charts as we can see the same issue for https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/nrsa. Fix should work for all chart exports.
