### ISSUE TITLE
DRUPAL: Error with Image Browser Popup

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#429]
This has been fixed in the latest core, but core cannot be updated due to other patches not working yet.

Limiting options for exposed Language filters causes errors and doesn't work for special languages.
https://www.drupal.org/project/drupal/issues/2693727

**Comment by amydugan** [comment]
@bryanpizzillo - is this fixed with the application of the latest core?

**Comment by amydugan** [comment]
Confirmed this has been fixed
