### ISSUE TITLE
Adobe Analytics Clean-up in Drupal Code to Fix Activity Map

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4295]
### Issue description
Currently, many of the analytics click event functions across Cancer.gov are passing generic values into Activity Map, which makes the information in the tool less useful for stakeholders. This is due to the way the linkname value gets set in the legacy implementation.

This legacy implementation also includes a lot of old code that no longer exists on the site, so we want to clean that up as well. To help  further future clean-up, we'd also like a way to help trace this back through Adobe by passing information about the functions into Adobe Analytics.

This file sets where link clicks will fire and identifies some data points: https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js
This file then sets analytics variables and triggers "logToOminture" to push data to Adobe: https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/nci-analytics-functions.js

> **ESTIMATE** TBD

### What's the expected change?
* Update logToOminiture function to pass to EDDL and address linkname issue and pass more unique values to match specific links clicked.
* Removal of old code that is no longer used
* Add data element, to be passed into eVar60, that collects details about what the function is that is helping to call the code in the legacy file in Drupal. This will help us further cleanup in the future.

### What's the current functionality?
Elements like related resources or cards pass very generic values into Activity Map. More examples of this are detailed in the spreadsheet at the bottom of the ticket.

Legacy code fires data directly to Adobe without using EDDL and updated implementation. 

### What's the updated acceptance criteria?
Analytics click events across cancer.gov are pushing information to the EDDL to fire the click events through Launch
Activity Map values in Omnibug are more descriptive and unique to links clicked on the page

```gherkin
```

### Additional details / screenshot
- Audit/review of the functions has started to be captured here: https://nih.sharepoint.com/:x:/r/sites/NCI-AARBTeam/Shared%20Documents/Analytics/AnalyticsFunctionsMatrix_EnterpriseCMS/AnalyticsJSFilesAudit+ActivityMap.xlsx?d=w3bcbd99ff8714a4d83fc0b7f968c4f30&csf=1&web=1&e=mzDKGR 

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by bryanpizzillo** [comment]
@welshja there are 3 events in nci analytics that do not pass the 'o' option, but instead a 'd' for download:
* PDFLink
* DownloadKindleClick
* DownloadOtherEReaderClick

Can these stay `o`? That is the simplest option. 

If you want the why:
If you look at the how that gets set, it is done in the Send Beacon type, and is not configurable -- you must select Custom Link, Exit, or Download from a dropdown. So if you needed them, we would need to find some way to change the Direct Call name depending on which one was used and then we would have 3 seperate `[AA]` rules to handle when this legacy call was a Custom link, Exit, or Download.

**Comment by bryanpizzillo** [comment]
Some notes for req above:
* The event name should be `LegacyAnalytics:Other`, which would mean the direct call to listen for will be `EDDL:LegacyAnalytics:Other`.
* The original linkName will be passed in as the link name. (Which is `event.detail.linkName`) The send beacon action could do something like `Legacy:%event.detail.linkName%` to differentiate these analytics calls from react apps that might have used the exact same link name for their events.
* The data element for eVar60 will be `legacyFunction`
* The props/evars/events will be captured as a data element named `rawData`. (This is what `LegacyDDLOther` does, so that will make it easier to copy/paste the custom code for the `[AA]` direct call rule.)

**Comment by bryanpizzillo** [comment]
### Direct references to `nci-analytics-functions`
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/analytics/analytics.js`
   *  we know this.
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/cts/cts-analytics.js`
   * this should actually be deleted as CTS moved out.
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/AppMeasurement.custom.js`
   * This we don't know. Look for where this is used, if, at all.
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/analytics/dumb-datalayer.js`
   * This just calls ClickParams to fire the trackLink
   * References AppMeasurement.custom.js to fire the s.t() event
   * Is dumb-datalayer even used??
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/enlarge/enlarge.js`
   * Calls `GlobalLinkTrack`
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/imageCarousel/image-carousel.js`
   * Calls `ImageCarouselClickSwipe`
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/liveHelpPopup/ProactiveLiveHelp.js`
   * Calls `RecordProactiveChatPromptDisplay`
   * Calls `RecordProactiveChatPromptClick`
   * Calls `RecordProactiveChatPromptDismissal`
* `docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/videoCarousel/video-carousel.js`
   * Calls `VideoCarouselComplete`
   * Calls `VideoCarouselClickSwipe`

### Rando references to NCIAnalytics not as a direct reference, i.e. the window or s object:
...

**Comment by bryanpizzillo** [comment]
### Deleted nci-analytics-functions
* SiteWideSearchResultsSearch
* SiteWideSearchResults
* TermsDictionarySearch
* GeneticsDictionarySearch
* GeneticsDictionarySearchNew
* GeneticsDictionarySearchAlphaList
* GeneticsDictionaryResults
* TermsDictionarySearchAlphaList
* TermsDictionarySearchAlphaListSpanish
* TermsDictionarySearchCore
* TermsDictionaryResults
* DrugDictionarySearch
* DrugDictionarySearchAlphaList
* DrugDictionarySearchCore
* DrugDictionaryResults
*

**Comment by welshja** [comment]
Completed testing on ACSF Test. Looking good!
