### ISSUE TITLE
Factbook Data Update FY 2023 

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/cgov-digital-platform#4302]
FactBook chart data update for fiscal year 2023
Update all related YAML and chart data content files for FactBook to reflect fiscal year 2023

> **ESTIMATE** 2

### Related Tickets
[CGOV-20618](https://tracker.nci.nih.gov/browse/CGOV-20618)

**Comment by santwuma** [comment]
Pending OBF feedback before code review.
