### ISSUE TITLE
Actually bump NCIDS package to v2.7.0 

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#4321]
### Issue description
> **ESTIMATE** TBD

In the 3.5.0 release candidate we left in the NCIDS package to 2.7.0-beta.1. This should be changed to the actual release.

**Comment by bennettcc** [comment]
Closing this story as discussed on 4/24 - completed (the PR was not merged into develop, so did not close automagically)
