### ISSUE TITLE
Translating a video with an override thumbnail image is prevented from saving the translation

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform#4326]
### Issue description
*Description of the issue*
When english video has an override thumbnail image and published, if user attempts to translate that video they are unable to save the translation because of the error ""Non-translatable field elements can only be changed when updating the original language."

Here is the log message 
<img width="2142" alt="Screenshot 2024-04-23 at 9 10 46 AM" src="https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/09423e2a-b847-451f-a707-0d91cea5cd76">

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  create a new english video with an override thumbnail image added and publish
2. edit -> translate the video
3. dont change anything and try to save spanish translation

### What's the expected result?
- user succesfully translates the video with  or without thumbnail override

### What's the actual result?
- error is thrown preventing from saving spanish video 

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
Looks good on test-acsf
