### ISSUE TITLE
CR: Allow site name in schema.org to be optional/configurable

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4335]
### Request Description
There is a need for some of our platform sites to not have explicit NCI branding. Currently the schema.org site name is configured to be "National Cancer Institute (.gov)" see the top of the screenshot below. The goal of this change is to make the site name optional/configurable where "National Cancer Institute (.gov)" is the default option, the second option is to choose for it to be unbranded (Google displays the URL in this location), or allow sites to make their own custom site name.

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/143126208/4a1cb88b-a661-46d8-bd39-8483cf4d92a3)

### What's the expected change?
- A site admin is able to edit the schema.org site name to be "National Cancer Institute (.gov)" (default) or custom

### What's the current functionality?
- All schema.org site names are "National Cancer Institute (.gov)".

### What's the updated acceptance criteria?
```gherkin
Scenario: A site admin is editing the Main page content on the Site Branding settings
  Given the site admin is logged into the CMS
    And the hover over the Configuration section in the mega menu
    And they hover over the System section
    And they click the Site Branding option
    And the schema.org site name has been updated to be optional/configurable
  When a site admin is editing the site branding settings
  Then they will see a collapsable section titled "Site Branding"
  When the "Site Branding" section is expanded
  Then the second to last field displayed will be the "Search Results Site Name Display Option"
    And this field will be required
    And this field will be a dropdown
    And the options will be "National Cancer Institute", and "Custom Site Name"
    And the "National Cancer Institute" option will be the default
    And the tooltip text for this field will be "Site Name that appears at the top of search results on a search engine for all pages on the site. Default is 'National Cancer Institute'."
    And the last field displayed will be the "Search Results Custom Site Name"
    And this field will be optional
    And the field will be a text input
    And the maximum number of characters for the field will be 60
    And the tooltip text for the field will be "Search Results Custom Site Name text replaces the search result site name"
    And the Search Results Custom Site Name field will be disabled
  When the site admin selects the "Search Results Custom Site Name" option from the Search Results Site Name Display Option
  Then the Search Results Custom Site Name field will become enabled
  When the site admin selects the "Search Results Custom Site Name" option from the Search Results Site Name Display Option
    And the user enters text into the Search Results Custom Site Name field
  Then the user returns to the Search Results Site Name Display Option field
    And the user selects a different option from this field
  Then the Search Results Custom Site Name field will return to the disabled state
    And the text entered into the Custom Site Name field will keep the text previously entered
  When the site admin selects the "Search Results Custom Site Name" option from the Search Results Site Name Display Option
    And does not enter any text into the Search Results Custom Site Name field
    And presses Save
  Then the page will not save
    And an error will appear
    And the error will say, "Please enter the Search Results Custom Site Name text to save this page."
```

```gherkin
Scenario: A site admin choses "National Cancer Institute" as the option from the "Search Results Site Name Display Option" field in the site branding settings on main page content
  Given the site admin is on the site branding settings for a main page content
    And they selected "National Cancer Institute" as the option for the "Search Results Site Name Display Option" field
  When the site admin chooses the "National Cancer Institute" option from the "Search Results Site Name Display Option" field 
    And a user views the search results page from a search engine for a page within the site with this selection
  Then the Search Results Site Name in the search engine results will be "National Cancer Institute (.gov)"
```

```gherkin
Scenario: A site admin chooses "Custom Site Name" as the option from the "Search Results Site Name Display Option" field in the site branding settings on main page content
  Given the site admin is on the site branding settings for a main page content
    And they selected "Search Results Custom Site Name" as the option for the "Search Results Site Name Display Option" field
  When the site admin chooses the "Search Results Custom Site Name" option from the "Search Results Site Name Display Option" field
    And the site admin has not entered any text into the "Search Results Custom Site Name" field
    And the user tries to save the edits to the page
  Then an error will appear on the "Search Results Custom Site Name" field which will state, "Please enter the Search Results Custom Site Name text to save this page."
  When the user views the search results page from a search engine for a page with a pretty URL "cancer.gov"
    And they enter text, "Custom1" into the "Custom Site Name" field
  Then the Search Results Site Name in the search engine results will be "Custom1"
```

```gherkin
Scenario: The site name functionality has been deployed.
Given the site name functionality has been deployed
When a user visits any page on the site, the page head markup will contain at least one script tag with the type attribute set to "application/ld+json"
And there will exactly one such schema.org script tag containing a JSON object with a "@context" key with a value of "https://sitemap.org"
And the schema.org JSON object contains a @graph key which is an array of objects.
And the @graph array will contain exactly one object with the "@type" property set to the value "WebSite"
And the WebSite object will contain a "url" key with a value set to the web site's base URL
And the WebSite object will contain a "name" key containing the site name
```

```gherkin
Scenario: The site name has not been customized
Given the admin UI's Search Results Site Name Display Option has been set to "National Cancer Institute"
Then the WebSite object will contain a "name" key containing the value "National Cancer Institute (.gov)".
```

```gherkin
Scenario: The site name has been customized
Given the admin UI's Search Results Site Name Display Option has been set to "Custom Site Name"
And the admin UI's Search Results Custom Site Name field contains a value
Then the WebSite object will contain a "name" key containing the same value as the Search Results Custom Site Name field
```

### Related Tickets
* Original Spike: #4237 

**Add alternate name to AC's*

**Comment by alinai** [comment]
@andyvanavery31 , can you please confirm if we want both error messages or we just want one of them? Currently on ODE818, we see the following error message on saving without entering any text into the Search Results Custom Site Name field
![image](https://github.com/user-attachments/assets/a4fbf5ce-1d97-49a1-8934-ce2bfb0de33b)

**Comment by alinai** [comment]
@andyvanavery31 , this appears always in expanded form when we navigate to https://ncigovcdode818.prod.acquia-sites.com/admin/config/sitebranding/settings

cc: @KateMashkinaNIH 

![image](https://github.com/user-attachments/assets/c1351205-b4d9-4cc7-8f7c-d1084babfa5b)

**Comment by alinai** [comment]
@navsunka , @andyvanavery31 , @KateMashkinaNIH, the "Search Results Custom Site Name" field does not get clear when   we select "National Cancer Institute" from "Search Results Site Name Display Option" dropdown 

Steps to reproduce: 

1. Select "Custom Site Name" from "Search Results Site Name Display Option" dropdown
2. Enter text into "Search Results Custom Site Name" field
3. Click the "Save configuration" button
4. Then navigate to https://ncigovcdode818.prod.acquia-sites.com/admin/config/sitebranding/settings
5. Clear the existing text from "Search Results Custom Site Name" field
6. Select "National Cancer Institute" from "Search Results Site Name Display Option" dropdown
7. Click the "Save configuration" button
8. The status message "The configuration options have been saved." appears
9. Scroll down to the "Search Results Custom Site Name" field
10. See that the "Search Results Custom Site Name" field has the text that was entered when we selected the "Custom Site Name" from "Search Results Site Name Display Option" dropdown


![image](https://github.com/user-attachments/assets/b49bb4e4-fdfb-4792-bd67-782fa830b254)

**Comment by andyvanavery31** [comment]
@alinai replying in order of your comments:

- I only want one error message, I am updating the AC's to match the error message that is appearing on the screenshot.

- It being expanded initially is acceptable functionality. The 'When' statement in the ACs is just a precursor to ensure that it is expanded before seeing the fields. If it were to be collapsed, then those fields would not be visible. I see this as acceptable and as a pass.

- This is the expected behavior per the ACs:

>  When the site admin selects the "Search Results Custom Site Name" option from the Search Results Site Name Display Option
    And the user enters text into the Search Results Custom Site Name field
  Then the user returns to the Search Results Site Name Display Option field
    And the user selects a different option from this field
  Then the Search Results Custom Site Name field will return to the disabled state
    And the text entered into the Custom Site Name field will keep the text previously entered
