### ISSUE TITLE
Blog series can be deleted while it has posts

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4341]
### Issue description
Users are able to delete a blog series even if there are still posts that belong to it.

### Steps to reproduce the issue

**HINT:** Perform these steps on a site with the the standard test content.

1. Login as a user with the `site_admin` role.
2. Archive all the posts in RAS blog.
3. Go to the content view.
4. Filter for the "Blog Series" content type.
5. Click the down arrow next to the RAS blog's Edit button.

### What's the expected result?
- The "Delete" option should not be available.

### What's the actual result?
- It's possible to delete a blog series that still has blog posts. ( e.g. The "Delete" option is available )

### Acceptance Criteria
```gherkin
Scenario: A blog manager is editing a blog series that has posts that belong to the series
  Given a blog manager is logged into the CMS
    And is editing a blog series
    And the blog series has posts belonging to the series
    And the blog manager archives the the blog series
  When the blog manager scrolls to the bottom of the blog series editing page
  Then the 'Delete' button will not appear
 
```
```gherkin
Scenario: A blog manager is editing a blog series that has all posts archived
  Given a blog manager is logged into the CMS
    And is editing a blog series
    And the blog series has all posts belonging to the series archived
    And the blog manager archives the the blog series
  When the blog manager scrolls to the bottom of the blog series editing page
    Then the 'Delete' button will not appear
```

```gherkin
Scenario: A blog manager is editing a blog series that has NO posts associated with it ( all archived and deleted, or none added initially)
  Given a blog manager is logged into the CMS
    And is editing a blog series
    And the blog series has no posts belonging to the series
  When the blog manager scrolls to the bottom of the blog series editing page
    And the blog manager archives the the blog series
    Then the 'Delete' button will appear
    And the blog manager can delete the blog series by clicking the 'Delete' button
```

**Comment by alinai** [comment]
@andyvanavery31 , can you please double check the AC and confirm that it is ok? It seems the "Expected Result" under "Steps to reproduce" is not in sync with AC. Currently on ODE 766, no matter blog posts exists under a Blog series or not, the "Delete" option does not appear. 
cc: @KateMashkinaNIH

**Comment by alinai** [comment]
On ODE 766, I archived all Blog posts under "RAS Dialogue Blog" series according to the Steps to Reproduce and noticed that the "Delete" button does not appear under the down arrow next to the RAS blog's Edit button, The "Delete: button does not appear under the down arrow next to any Blog Series no matter the Blog Series has any Blog posts or not.

Then per AC, I archived the "RAS Dialogue Blog" series, still the the "Delete" button does not appear under the down arrow next to the RAS blog's Edit button.

**Comment by blairlearn** [comment]
The delete button should not appear for a blog series until all of the posts belonging to the series have been **deleted**.

When a blog post is archived, it still exists in the system and still belongs to the series. It should not be possible to manipulate the system in a manner that leaves a blog post without a series.

**Comment by alinai** [comment]
Scenario: A blog manager is editing a blog series that has posts that belong to the series

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/091f72ca-9d7a-44d4-986e-31c322ffc51c)

**Comment by alinai** [comment]
Scenario: A blog manager is editing a blog series that has all posts archived

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/1c3dda53-d72a-4fe8-8a1c-47a2009c8c64)

**Comment by alinai** [comment]
Scenario: A blog manager is editing a blog series that has NO posts associated with it ( all archived and deleted, or none added initially)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/ab0a7db3-4858-4ad6-a40c-4f347c1db3f0)


![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/39f99943-0f95-40bc-bb3a-c15c5c96db32)

**Comment by alinai** [comment]
@andyvanavery31 , @sarinapadilla , @blairlearn , @kate-mashkina , 
For Spanish Blog series, for all 3 scenarios, a non-functional "Delete" button continue to appear on the archived Edit Spanish Blog Series page. The "Delete" button is non-functional means if we click it, the Blog Series is not deleted and user is returned to the Content View page and the Blog Series does not get deleted. The behavior that the "Delete" button is non-functional on blog Series pages is same as dev-ac. Please confirm if you are "ok" with the "Delete" button appearing on the Edit mode of Spanish Blog Series page for the Scenario#1 and Scenario#2. I have confirmed that the "Delete" button does NOT appear for Scenario#1 and Scenario#2 and DOES appear for Scenario#3 under the drop-down for Spanish Blog Series on the Content view page.

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/06c97f03-c4ff-435a-9239-12c97d8127dd)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/91061a83-2da3-403d-8613-f177b391632f)

![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/901687bd-6959-4caf-90d1-70218f02974b)

**Comment by andyvanavery31** [comment]
Product accepts the exception in the Spanish behavior displaying the delete button when it should not. Subsequent ticket will be created to address it.

**Comment by alinai** [comment]
Created https://github.com/NCIOCPL/cgov-digital-platform/issues/4370 to address the "Delete" button appearing when Editing the Spanish Blog Series page on The CMS.
cc: @andyvanavery31 , @blairlearn , @KateMashkinaNIH
