### ISSUE TITLE
Update DCEG Footer for Linkage Sign-Up Update

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#4348]
DCEG has requested to update their site footer in an effort to enhance the user experience for a user who wants to sign up for their linkage newsletter.  Please update their footer in the following way:

1) Update the 'Sign up for email updates' to read 'Sign up for Linkage, the DCEG Newsletter'
2) Remove the 'enter your email address' sub heading and remove the white text box that a user would use to enter an email address
3) Update the yellow sign up button to point to a new URL location: https://public.govdelivery.com/accounts/USNIHNCI/signup/40123

The analytics for the newly formatted sign up areas should mirror what is currently working on the National Cancer Plan site: https://nationalcancerplan.cancer.gov/

To test this change on a lower environment:
- @bennettcc can verify the front end behavior + content change
- @welshja (and team) can verify that the analytics work as expected

**Comment by welshja** [comment]
Analytics are working as expected with the change.

**Comment by bennettcc** [comment]
Woop, thanks Joe! And the behavior testing passed on my end.

@dev-rana-publicis I'll coordinate with the DCEG team to determine when they want this change made on their site. Will update you when I know.

**Comment by bennettcc** [comment]
@dev-rana-publicis We have approval from DCEG to make this change today (or at earlier availability). Please make the change on the DCEG prod site 

https://dceg-cms.cancer.gov/

**Comment by bennettcc** [comment]
The change looks good - thanks Dev! Closing this ticket
