### ISSUE TITLE
Create Mini Landing Page Template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4356]
## As a user, I want to have NCIDS components available for my mini landing page, so that I can feature content.

The Mini Landing Page content type needs to be updated to allow for the new NCIDS page template style. The Mini Landing Page Style dropdown field will have two options: Standard/Default/something and NCIDS. (wordsmith these later)

Additionally, we are updating `usa-section` on MLPs:
1. First component on an MLP page should get:
    * Top Padding: None
    * Bottom Padding:
      * 16px (Token: 2) on desktop
      * 12px (Token: 1.5) on mobile
2. All other components in the MLP page should get:
    * Top and Bottom Padding:
      * 16px (Token: 2) on desktop
      * 12px (Token: 1.5) on mobile
3. The last component on the MLP page should get:
    * Top Padding:
      * 16px (Token: 2) on desktop
      * 12px (Token: 1.5) on mobile
    * Bottom Padding:
      * 32px (Token: 4) on desktop
      * 24px (Token: 3) on mobile
4. The NCIDS Page Title Block component will have zero (0) spacing on the bottom of it regardless of what component follows
    * This reduces the overall space between the NCIDS Page Title Block and the subsequent component by half
    * This will be a universal rule for all Mini Landing Pages using the NCIDS style 

### DoR Tasks

- [x] [Content Model](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page) Drafted
- [x] [Content Model](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page) Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] [Content Model](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page) Approved
  - [x]  Developer Approval
  - [ ] IA Approval
- [x] Acceptance Criteria Drafted
- [ ] Scenarios created for YAML
- [x] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] Acceptance Criteria Approved
  - [x] Developer Approval
  - [x] IA Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client Review with Demo

### Acceptance Criteria

```gherkin
Scenario: Mini Landing Page Style field displays on Mini Landing Page content type
  Given the user is logged in as an editor 
    And the user adds new content 
    And selects Mini Landing Page as the content type 
  Then the edit screen for a new Mini Landing Page content item displays
    And the Mini Landing Page Style field appears
    And the field displays under the Language field and above the Site Section field
    And the field is a dropdown
    And under the dropdown the tooltip text appears that reads "Select a template for the page"
    And the dropdown defaults to "Standard" 
    And the dropdown has the option "NCIDS"
    And the field is required 
```

### Test Content
Create the following pages to help test that the template is working as expected:

English: https://www-dev-ac.cancer.gov/test/ncids-mini-landing/template
Spanish: https://www-dev-ac.cancer.gov/espanol/test-es/ncids-mini-landing-es/template
- Add new content, select Mini Landing Page as the content type
- On the Mini Landing Page Style field, select NCIDS as the page style.
- Add a rawHTML component to the page and add "hello world" - or some generic text inside a usa-prose tag (or something else?) to demonstrate that the template is working and pulling in NCIDS styling.

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

---

**Comment by laurelthrash** [comment]
Template approved by Anna in weekly PM/PO meeting on 07/08.
