### ISSUE TITLE
Create Title paragraph for Mini Landing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4357]
## As a user, I want to be able to dynamically add a title to my page, so that my page will have an H1 where I want it to be.

This paragraph will have no fields (can this work? we'll find out) where the page title will be rendered on the page.

### Requirements
- There will be padding of zero (0) px after the Title paragraph for Mini Landing Pages using the NCIDS template, regardless of the component that follows it

### DoR Tasks

- [x] Determine if this paragraph can be created without any fields @dev-rana-publicis @andyvanavery31 
  - We will create the NCIDS Mini Landing Title with no fields - using `drupal_token('current-page:title')` in our template to get the page title
  - We will later create the Page Title Wide Guide Card that does not have a title field - still using `drupal-token('current-page:title')` in the template
- [x] Content Model Drafted @andyvanavery31 - see the new table added under the NCIDS Mini Landing Page Components section on the [Paragraph Types page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Types), and see the [Paragraph Type NCIDS Page Title Block](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Page-Title-Block) page
- [x] Content Model Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] Content Model Approved
  - [x]  Developer Approval
  - [x] IA Approval
- [x] Acceptance Criteria Drafted
- [x] Scenarios created for YAML
- [x] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] Acceptance Criteria Approved
  - [x] Developer Approval
  - [x] IA Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client Review with Demo

### Scenarios
- For the first page that displays the title, please make the page title be, "The RAS Initiative"
- For the second page that displays a long title, please make the page title be, "The Adventures and Chronicles of the Quick Brown Fox Who Jumped Over the Lazy Dog and Their Friends the Tortoise and the Hare With Interludes from Alice in Wonderland"
- For the second page that can translate into Spanish, please make the page title be, "Las Aventuras y Crónicas del Veloz Zorro Marrón que Saltó Sobre el Perro Perezoso y Sus Amigas la Tortuga y la Liebre con Interludios de Alicia en el País de las Maravillas"
- Please use the Raw HTML Example page for the page that does not display the page title

### Acceptance Criteria

**Adding the NCIDS Title paragraph to the MLP on the CMS**
```gherkin
Scenario: NCIDS Title paragraph being added to Mini Landing Page content type on the CMS
  Given the user is logged in as an editor on the CMS
    And the user is editing a "Mini Landing Page" content item
  When the user expands the dropdown to add a paragraph to Contents
  Then the dropdown displays "Add NCIDS Page Title Block"
  When the user selects "Add NCIDS Page Title Block"
  Then the NCIDS Page Title Block will be added to the page
    And there will be no fields in the NCIDS Page Title Block
```

**Viewing a page with the Title paragraph added**
```gherkin
Scenario: A visitor to an MLP sees a page with a title
  Given the user is on an MLP
    And the MLP is on the new NCIDS MLP Template
    And the MLP has the NCIDS Title paragraph added
  When the visitor views the page
    And the title paragraph was added in content editing
  Then the visitor will see the Page Title displayed on the page
```

**Viewing a page with no Title paragraph added**
```gherkin
Scenario: A visitor to an MLP sees a page with no title
  Given the user is on an MLP
    And the MLP is on the new NCIDS MLP Template
    And the MLP does not have the NCIDS Title paragraph added
  When the visitor views the page
    And the title paragraph was not added in content editing
  Then the visitor will not see the Page Title displayed on the page
```

### Resources:
* [Figma](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4132-35842&t=y2q8UjojxqvzHKv6-0)
* [R3 Design Scope](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B8985BEA6-3D0D-4A03-8AB6-83D26B12AC10%7D&file=R3%20Design%20Scope.xlsx&action=default)

### Notes
- Use the `drupal_token('current-page:title')` on the template.
---

**Comment by dev-rana-publicis** [comment]
### Approach

- [ ] Get confirmation on content model (the approach is using two names for the paragraph at the moment) 
- [ ] Create a paragraph with no fields
- [ ] Create Drupal template for NCIDS Title
    - `paragraph--ncids-mini-landing-title.html.twig`
    - Use `drupal_token('current-page:title')` to display the `<h1>`
- [ ] Create CSS for `cgdp-mini-landing-page-title`
- [ ] Create Example mini-landing YAML (with Title + Raw HTML)

**Comment by laurelthrash** [comment]
Template approved by Anna in weekly PM/PO meeting on 07/08.
