### ISSUE TITLE
Create Slim Hero paragraph for Mini Landing Pages

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4358]
## As a content editor, I want to be able to add a Slim Hero paragraph, so that I can add a visually appealing image to the top of the page.

This paragraph will have an image field to upload an image directly, and a field to set alt text (this comes with an image upload). Image size requirements is 1988 x 460 px.

### DoR Tasks

- [x] @lburack to work with designers to come to a solution on the impact of using usa-measure with this component.
- [x] Designers to update comps to match outcome from usa-measure impact
- [x] Content Model Drafted
- [ ] Content Model Reviewed
  - [ ] Developer Review
  - [x] IA Review
- [ ] Content Model Approved
  - [ ]  Developer Approval
  - [x] IA Approval
- [x] Acceptance Criteria Drafted
- [x] Scenarios created for YAML
- [ ] Acceptance Criteria Reviewed
  - [ ] Developer Review
  - [x] IA Review
- [ ] Acceptance Criteria Approved
  - [ ] Developer Approval
  - [x] IA Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client Review with Demo

### Technical Notes
**Content Model**
- [Paragraph Types](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Types#ncids-mini-landing-page-components) update
- New [NCIDS Slim Hero Component](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Slim-Hero) page

**Scenarios**
- For the example page with the title "The RAS Initiative", please add the hero image for the RAS Initiative page from the comp [here](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4132-33023&t=e3akVTHEvfXnZojT-0) above the title. See the previous link for this comp.
_Image below. Sized to 1988x460:_ 
![Slim Hero - The RAS Initiative](https://github.com/NCIOCPL/cgov-digital-platform/assets/109552399/1889c233-a09d-4a4c-b00a-fdc807d7f3a7)

- For the example page with the long title, "The Adventures and Chronicles of the Quick Brown Fox Who Jumped Over the Lazy Dog and Their Friends the Tortoise and the Hare With Interludes from Alice in Wonderland", please add the hero image from the link [here](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4553-33524&t=e3akVTHEvfXnZojT-0) below the title
_Image here. Sized to 1988x460:_
![Slim Hero - NCI Education and Outreach Program](https://github.com/NCIOCPL/cgov-digital-platform/assets/109552399/f02f25ad-8a22-4321-bcb5-6fead80cf986)

### Acceptance Criteria
**CMS Experience**
```gherkin
Scenario: NCIDS Title paragraph can be added to Mini Landing Page content type
  Given the user is logged in as an editor 
    And the user is editing a "Mini Landing Page" content item
  When the user expands the dropdown to add a paragraph to Contents
  Then the dropdown displays "Add NCIDS Slim Hero"
  When the user selects "Add NCIDS Slim Hero"
  Then the fields for a "NCIDS Slim Hero" paragraph appear
    And the "Image" field appears
    And the field is required
    And it is an image upload
    And the image field has the Alt Text property editable
    And only one file can be selected
    And there is a 256MB limit
    And the allowed types are png, gif, jpg, and jpeg
    And the image must be 1988px x 460px
  When the user does not upload an image
    And the user tries to save the page
  Then the page will not save
    And an error will be thrown that the required field is not completed
  When the user uploads an image that is not the correct size size
  Then the image will not be uploaded
    And an error will be thrown to the user stating, "Error message. The specified file <insert name of file> could not be uploaded. The image is not the required size. The image dimensions are 1988x460 pixels and the image size is <insert image size>."
  When the user uploads an image that is the correct size and aspect ratio
  Then the user will be able to save the page
```

**Front End Experience**
```gherkin
Scenario: A site visitor goes to a Mini Landing Page with the new template that has an NCIDS Slim Hero component on it
  Given a site visitor is on a Mini Landing Page
    And the Mini Landing Page is using the NCIDS style
    And the Mini Landing Page has an NCIDS Slim Hero component on it
  When the user views the Mini Landing Page
    And the breakpoint is greater than 479px
  Then the user will see the NCIDS Slim Hero image
    And the NCIDS Slim Hero Image will scale with the breakpoint width
  When the user views the Mini Landing Page
    And the breakpoint is less than 480px
  Then the user will not see the NCIDS Slim Hero image
```

**Analytics Requirements**
```gherkin
Scenario: Mini Landing Page analytics are being reviewed for pages with an NCIDS Slim Hero
  Given the Mini Landing Page being reviewed is using the NCIDS style
    And the Mini Landing Page has an NCIDS Slim Hero component
  When the analytics rows are being counted
  Then the NCIDS Slim Hero is counted as a row in analytics
```

### Resources:
* [Figma - 3.1 Priority MLP Comps](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4132-33023&t=FhriI6ek0zRKgQxQ-1)
* [Figma - Component Library List (3.1)](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=3910-17421&t=FhriI6ek0zRKgQxQ-1)
* [R3 Design Scope](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/_layouts/15/Doc.aspx?sourcedoc=%7B8985BEA6-3D0D-4A03-8AB6-83D26B12AC10%7D&file=R3%20Design%20Scope.xlsx&action=default)

---

**Comment by laurelthrash** [comment]
Comps updated and links provided in Description of this ticket. Marking as complete from Design board for the time being and tagging @andyvanavery31 @sarinapadilla for next steps. Cc: @lburack @monika-jaeger @blilianyu

**Comment by dev-rana-publicis** [comment]
### Approach

- [ ] Create Drupal paragraph for the slim hero
    - Label: NCIDS Slim Hero
    - Machine name: `ncids_slim_hero`
    - Description: **Needs DOR**
    - [ ] Create fields
        - Need to confirm with product if this is going to be a `cgov_image` or uploaded from local computer
    - [ ] Add to allowed components for MLP
- [ ] Create Drupal template for Slim Hero
    - `paragraph--ncids-slim-hero.html.twig`
- [ ] Create entrypoint for slim hero
    - `cgdp-slim-hero`
- [ ] Create CSS for `cgdp-slim-hero`
- [ ] Create Example mini-landing YAML (with Slim Hero + Title + Raw HTML)

**Comment by monika-jaeger** [comment]
Images added to Scenario section.
cc: @andyvanavery31 @dev-rana-publicis

**Comment by bennettcc** [comment]
This PR was approved by the Federal team on 7/22
