### ISSUE TITLE
Create kernel test for Boolean field storage values

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#436]
Create test for `boolean` type field storage in `docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/FieldStorage/CGovFieldStorageTest.php`.

- `Public Use` field was created in #205 
- `Syndicate` field to be created will need tests (no ticket yet)

**Comment by VictoriaSunNIH** [comment]
At this point in time we need a larger test strategy, and have some regression tests in place.
