### ISSUE TITLE
Update Raw HTML Content paragraph to support NCIDS Mini Landing Page Template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#4364]
## As a [role], I want [feature], so that [benefit]

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s)*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by welshja** [comment]
@sarinapadilla @andyvanavery31 - per a conversation with @bryanpizzillo this ticket can be cancelled as a separate ticket and can be a task within the mini-landing page template ticket in order for us to test and confirm the template is working.

**Comment by welshja** [comment]
@sarinapadilla @andyvanavery31 - per a conversation with @bryanpizzillo this ticket can be cancelled as a separate ticket and can be a task within the mini-landing page template ticket in order for us to test and confirm the template is working.
