### ISSUE TITLE
Front end website referencing CMS urls for favicon items.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4374]
The `responsive_favicons` module doesn't vary the URL according to which hostname the site is using. If the cms hostname is referenced before the front-end name, then the URLs for the favicon-related files are cached with that name.

This leads to www-test-acsf pulling favicons from www-cms-test, plus CORS errors.

https://www-test-acsf.cancer.gov/about-cancer/coping/feelings/test-article123

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/72219df4-0ae4-40c2-b525-67c197bd05b7)

Related to #4300

**Comment by KateMashkinaNIH** [comment]
this is fixed on acsf test


![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/67657582/b7768f10-ab50-4e48-b39c-0ac003a8d464)
