### ISSUE TITLE
Story: Create Flag Card Group Paragraph for MLP

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4389]
### Requirements

**Functional Requirements**
- No maximum number of cards
- A new row of cards will be started after each row of 2 is filled
- The Flag Cards will function the same as the NCIDS Feature Cards on MLPs (They will use the Card Title and Feature Card description from the featured item unless overridden)
- The Card Title font shall be the same size visually and in the page hierarchy as the title on updated Feature Cards (as of writing, not all Feature Cards have been updated to the new styling - see Specifications)
- The description font shall be the same size as the description on updated Feature Cards (as of writing, not all Feature Cards have been updated to the new styling - see Specifications)
- The same elements from the Feature Card Internal/External/Multimedia will be pulled for this component
- The component group will have a required heading that will have an option to be visually hidden
- The Flag Card Group heading will be the same size visually and in the page hierarchy as the heading for updated Feature Card Rows (as of writing, not all Feature Cards have been updated to the new styling - see Specifications)
- If the text of the title and description add height to the card, the image will remain the same size and will be top aligned. The card will expand to contain all the text, and both cards in the row will remain equal height. Guidance will be written so that if this occurs, the user should override the title and description with shorter text

**Analytics Requirements**
- location: 'Body'
- pageType: 'cgvMiniLanding'
- pageTemplate: 'ncids_default'
- componentType: 'Flag Card'
- pageRows: The total number of rows on the page overall
- pageRowIndex: The index of the selected row from the link click
- pageRowCols: The total number of columns in the row from the link click
- pageRowColIndex: The index of the selected column within the selected row from the link click
- containerItems: The total number of flag cards added to the flag card row (there is no maximum)
- containerItemIndex: The index of the selected flag card, counting will start in the upper left, count left to right, and at the end of each row, the count will continue on the next row again going left to right
- componentTheme: Default is 'Not Defined'
- componentVariant: Default is 'Not Defined'
- linkText: This should be set to the title of the Flag Card clicked
- title: This value should be the heading value of the Flag Card Group (regardless if it is hidden/shown on page). If value is left blank, then it should pass as "Not Defined".
- linkType: This will be set based on the type of link (internal, external, or multimedia)
- linkArea: This will pass 'Card' Based on the Flag Card clicked
- totalLinks: Default will be 1
- linkPosition: Default will be 1

**Specifications**
- The Flag Card Group will have a required heading field that is a text editor
- The Flag Card Group heading will be an h2 element
- The Flag Card Group heading will stylistically use token size xl (24px)
- The Flag Card Title will stylistically use token size md (20px)
- The Flag Card Description will stylistically use token size xs (16px)

### DoR Tasks

- [x] Content Model Drafted
- [x] Content Model Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] Content Model Approved
  - [x] Developer Approval
  - [x] IA Approval
- [x] Acceptance Criteria Drafted
  - [x] Analytics Acceptance Criteria Drafted
- [x] Scenarios created for YAML
- [x] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [x] IA Review
  - [x] Analytics Review
- [x] Acceptance Criteria Approved
  - [x] Developer Approval
  - [x] IA Approval
  - [x] Analytics Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client Review with Demo

### Technical Notes

**Content Model**
- [Paragraph Types](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Types) update
- New [NCIDS Flag Card Paragraph](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Flag-Card-Group)

**Scenarios/Figma**
- On the example page that shows real content, make it look like [these Flag Cards on each breakpoint](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4553-33524&t=CFvSIv0WjCLrdxvV-0). Please use the url of /test/eop. Please use the following links for the content on the comp:
  - [Outreach Opportunities and Events Flag Card](https://www.cancer.gov/grants-training/training/at-nci/eop/outreach-opportunities)
  - [Partnerships flag card 2](https://www.cancer.gov/grants-training/training/about/cancer-community-partnership/partnerships)
  - [What We Do list item 1](https://www.cancer.gov/about-nci/organization/cche/about/what-we-do)
  - [Education and Outreach Staff and Contact Information](https://www.cancer.gov/grants-training/training/at-nci/eop/contact-info)
- On the example page that shows not real content, please make a test page [[comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5719-80379&t=AaZx6zGYKBnPLIU3-1)] that has the title, "Test Page". Below the title is a content block with approximately 10 lines of lorem ipsum. Below the content block is a Flag Card Group, with the Heading, "The Optional Flag Card Group Heading" with five cards: the first card is an internal card and it goes to [About Cancer](https://www.cancer.gov/about-cancer), is titled "About Cancer", and has a description of, "This flag card is an internal link to About Cancer". The second card is an external card and it goes to [Google](https://www.google.com/), is titled "External Card to Google", and has a description, "This is an extremely long description on an external card that will redirect the user to Google.com. Extra text in this card to test the behavior of a card when the text is very very long." The third card is a multimedia card that links to [Implementation Science Infographic](https://www.cancer.gov/research/implementation-science-infographic), is titled, "Multimedia Card linking to Implementation Science Infographic with a Very Long Title to Test the Behavior of a Card with a Very Long Title Set", and it has the description of, "This is the description for the multimedia card". The fourth card is an internal card linking to [Cancer Types](https://www.cancer.gov/types) with the title "Cancer Types", and it has no description. The fifth card is an internal card which links to [Cancer Research](https://www.cancer.gov/research), is titled "Cancer Research", and has the description, "This is the fifth card and should be on its own line when cards appear in the side-by-side orientation." Please use the url of /test/ncids-flag-card-test

**IMPORTANT NOTE**
- Until [DS ticket 1815](https://github.com/NCIOCPL/ncids/issues/1815) is completed, this solution will need a work around because the heading size on the DS uses token size LG instead of the token size MD (font size 20px/line-height-2).

### Acceptance Criteria

**CMS User Experience**
```gherkin
Scenario: NCIDS Flag Card Group paragraph can be added to Mini Landing Page content type
  Given the user is logged into the CMS as an editor
    And the user is editing a "Mini Landing Page" content item
    And the Mini Landing Page is using the NCIDS Style
  When the user expands the dropdown to add a paragraph to Contents
  Then the dropdown displays "Add NCIDS Flag Card Group"
  When the user selects "Add NCIDS Flag Card Group"
  Then the fields for an "NCIDS Flag Card Group" paragraph appear
    And the first field is the Heading field
    And the Heading field is required
    And it is a text entry field
    And the tooltip says, "Displays above the group of cards. Used to concisely describe the featured content."
    And the next field is the Heading Visibility field
    And the Heading Visibility field is required
    And the field is a dropdown
    And the dropdown has the following options, "Visible" (default), and "Screen Reader Only"
    And the next field is the Flag Cards field
    And the Flag Cards field is required
    And it allows the selection of the following types: NCIDS Card Internal (default), NCIDS Card External, and NCIDS Card Multimedia
    And one NCIDS Card Internal will automatically be added to the NCIDS Flag Card Group
    And the NCIDS Card Internal will show the same fields as an NCIDS Card Internal (see Content Model)
    And at the bottom of the NCIDS Flag Card Group paragraph there is a dropdown that allows the content editor to add other flag cards to the group
    And there will be no limit to the number of Flag Cards that can be added to the NCIDS Flag Card Group
  When the content editor adds an NCIDS Card External to the NCIDS Card Group
  Then the NCIDS Card External will show the same fields as an NCIDS Card External (see Content Model)
  When the content editor adds and NCIDS Card Multimedia to the NCIDS Flag Card Group
  Then the NCIDS Card Multimedia will show the same fields as an NCIDS Card Multimedia (see Content Model)
```

**Front-End Experience**
```gherkin
Scenario: A user views an NCIDS Flag Card Group on a Mini Landing Page
  Given the Mini Landing Page is using the NCIDS style
    And the NCIDS Flag Card Group is added to a Mini Landing Page
    And the NCIDS Flag Card Group has the scenarios added per the Scenarios section above
  When the visitor views the Mini Landing Page with the NCIDS style and the NCIDS Flag Card Group
  Then the visitor will see the NCIDS Flag Card Group on the page
    And it will exactly match the comps
  When the user hovers over one of the NCIDS Flag Cards
  Then the NCIDS Flag Card that is being hovered over will display the hover state
  When the user clicks on one of the NCIDS Flag Cards
  Then they will be redirected to the linked page
  When the text of the title and body are longer than the image is tall
  Then the image will not change size
    And the image will be top aligned
    And the card will expand to contain all of the text
    And the row will keep the cards the same height
```

**Analytics**
```gherkin
Scenario: Analytics events for the NCIDS Flag Card Group on Mini Landing Pages using the NCIDS style
  Given a user is on a Mini Landing Page
    And the Mini Landing Page uses the NCIDS style
    And the Mini Landing Page has an NCIDS Flag Card Group
  When the user clicks on one of the NCIDS Flag Cards
  Then there will be an NCIDataLayer Other event
    And the event has the name "MLP:FlagCard:LinkClick"
    And the event has the linkname "MLP:FlagCard:LinkClick"
    And the event will have the following data
    | key | value |
    | location | body |
    | pageType | This will return the value of the page type and should match the dcterms.type meta data tag on the page. |
    | pageTemplate | This will return the value of the page template and should match the cgdp.template meta data tag on the page.   |
    | pageRows | This will return the number of rows on the page overall |
    | pageRowIndex | This will return the index of the row number on the page that was clicked |
    | pageRowCols | This will return the number of columns of components in the container in the row where the click was made |
    | pageRowColIndex | This will return the index of the component in the container that was clicked by column |
    | containerItems | This will return the number of components in the container that was clicked |
    | containerItemIndex | This will return the index of the component in the container that was clicked (count occurs starting at the top left, counting left to right, and at the end of each row continuing the count on the following row again going left to right) |
    | componentType | Default to 'Flag Card' |
    | componentTheme | Default to 'Not Defined' |
    | linkText | Default to the title of the Flag Card clicked |
    | componentVariant | Default to 'Not Defined' |
    | title | This will be the title of the Flag Card |
    | linkType | This will be added as a data attribute to each link in the Flag Card Group and defined as 'Internal', 'External', or 'Multimedia' based on the type of link in the code |
    | linkArea | This will be set to 'Card' for all the flag cards |
    | totalLinks | Default will be 1 |
    | linkPosition | Default will be 1 |
```
Analytics Evars for Testing:
61: pageType|pageTemplate
64: linkType|title|linkText
65: componentType|componentTheme|componentVariant
66: pageRows|pageRowIndex|pageRowCols|pageRowColIndex|containerItems|containerItemIndex
67: linkArea|totalLinks|linkPosition
68: location

### Notes

---

**Comment by adrianacastaneda** [comment]
Looks good to me! thank you for the updates! @andyvanavery31

**Comment by laurelthrash** [comment]
Review complete from UX side. Closing out on UX board. Cc: @andyvanavery31
