### ISSUE TITLE
Press Release Date Display Rules

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#439]
This story is to display the [common date field](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#content-dates)s to [Press Release](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) content type. 

**[Date Display Rules](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release#date-display)**
 * **Sorting** When sorting by date for lists, use the Posted Date
 * **Display Date on Content** On Press Release Content, display *All* dates selected 
 * **Display Date on Lists** On lists, display Posted Date

**Comment by amydugan** [comment]
@bgnih - https://www.cancer.gov/news-events/press-releases/2013/E3805
