### ISSUE TITLE
Create a Custom Favicon for PCP

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4394]
### Requirements

- The new favicon shall be unique to PCP
- The new favicon will be approved by stakeholders
- The new favicon will be created following the [Customizing the Favicon](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Customizing-the-Favicon) process

### DoR Tasks

- [x] Designer creates favicon image
- [x] Client approval of favicon image
- [x] Designer uses the Customizing the Favicon workflow to make all instances of the Favicon
- [x] Acceptance Criteria Drafted
- [x] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [x] QA Review
- [x] Acceptance Criteria Approved
  - [x] Developer Approval
  - [x] QA Approval

### Acceptance Criteria

```gherkin
Scenario: An individual on the internet sees the favicon branding for PCP
  Given the user is on a browser
    And they have conducted a search on their preferred search engine for "presidential cancer panel"
  When the user searches for "presidential cancer panel"
  Then the favicon in the search results for the PCP page will show the new favicon
  When the user goes to the PCP page
  Then the new favicon will appear in the tab of the browser
```

### Resources:
- [Customizing the Favicon](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Customizing-the-Favicon)
- [PCP Site](https://prescancerpanel.cancer.gov/)

### Notes

---

**Comment by blilianyu** [comment]
@santwuma @andyvanavery31 Here is the favicon
[favicon_package_v0.16.zip](https://github.com/user-attachments/files/16336090/favicon_package_v0.16.zip)

**Comment by santwuma** [comment]
Done. No dev work needed - closing
