### ISSUE TITLE
Display sprint 1 Article

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#44]
There is only a \<h1\> title field right now. So the body area should just be lorum ipsum. (i.e. NO FANCY Stuff)

Examples of Articles:
SIMPLE: https://www.cancer.gov/about-nci/legislative/history
COMPLEX: https://www.cancer.gov/about-cancer/understanding/what-is-cancer

This should just output the HTML - no look and feel.

**Comment by BrendanBeltzNIH** [comment]
Is this just asking for the line in the node cgov-article template that referes to {{ content.body }} to be changed to just {{ content }} for the nonce? Or am I misunderstanding the ask?
