### ISSUE TITLE
Editing CGov File doesn't create new revisions by default

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4420]
### Issue description
Multiple users have reported that when editing an existing media item of type File, the "Create new revision" checkbox is unchecked. This is inconsistent with all other media content types as well as the node types.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Login as a user with permission to upload/edit files.
2. Go to the list page for media content items (`/admin/content/media`)
3. Filter for type "File"
4. Scroll to the bottom of the page.

### What's the expected result?
- The "Create new revision" checkbox should have a check mark.

### What's the actual result?
- The "Create new revision" checkbox is unchecked.

### Additional details / screenshot
- ![Screenshot 2024-08-19 at 11 35 51 AM](https://github.com/user-attachments/assets/395eccf1-c990-4da7-bac7-a43c5eae477f)

### Related Tickets
* Issue #1085

**Comment by KateMashkinaNIH** [comment]
The issue is fixed + regression passed on ODE809
