### ISSUE TITLE
Extract all classes and inline styles from WYSIWYG on Inner Pages to be analyzed

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4439]
To support discovery around redesign of the WYSIWYG editor and help assess the current state and what may need to be cleaned up, this ticket is requesting an export of all classes and inline styles used within the editor.

We'd like to receive this information as an export that can be used for analysis (csv or some other delimited format). It would be great to have:

- the class/style
- page it is on
- page template of the page
- page title
- count of times used within the page for each returned value. 

Exact format can be discussed and worked on as part of this ticket. If this can be provided in one file, that is great. If it is easier to split, that is also okay and can be combined in the analysis.

**Comment by bryanpizzillo** [comment]
I uploaded the csvs to https://nih.sharepoint.com/:f:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/Development%20Track/inner-page-html-analysis-data?csf=1&web=1&e=XmX9fl

**Comment by welshja** [comment]
Exports look good to me. Entered https://tracker.nci.nih.gov/browse/CGOV-22120 for creating a PowerBI report to enable the analysis
