### ISSUE TITLE
Create Content Types

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#444]
Create/update descriptions for the following content types:
[Home/Landing Page](Content-Type-Home-Page)
[Cancer Type Homepage](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-CTHP)
[Blog Series](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series)
[Blog Posts](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts)
[Article](Content-Type-Article)
[Press Release](Content-Type-Press-Release)
[Institution](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Institution)
[Biography](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography)
[Event](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Event)
[PDQ Info Summary](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-PDQ-Drug-Info-Summary)
[General](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-General)
[Mini Landing Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Mini-Landing-Page)
[Cancer Research Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page)

**Comment by VictoriaSunNIH** [comment]
Attaching the excel sheet of content name, machine name and description for review
[Content Types.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/2742578/Content.Types.xlsx)

**Comment by lburack** [comment]
Updated excel sheet as well as wiki pages. Need to revisit the General page description though, depending on whether all content-esque general pages should become articles in the migration.
[20190109 Content-Types-LBB.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/2750734/20190109.Content-Types-LBB.xlsx)

Content types still without a description are:

- Event (this content type is still TBD. IAs are discussing next week, so I will update once I know what this is going to be)
- App module (these aren't even getting built)
- Raw HTML content blocks (self explanatory? used mostly by dev team anyway)
- Content blocks
