### ISSUE TITLE
Analyze Inner page classes and inline styles from WYSIWYG

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4440]
With the information provided in: [#4439](https://github.com/NCIOCPL/cgov-digital-platform/issues/4439)

Analyze the classes and inline styles from the WYSIWYG.

This information should be used to help quantify and assess the current state of how folks have used the WYSIWYG and what we may need to address or consider in R4

This may roll into Iteration 57.

**Comment by bennettcc** [comment]
Closing this as complete - initial findings presented to the Fed team on 12/2
