### ISSUE TITLE
PDFs now download rather than open in browser (as they used to)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#4446]
### Issue description
PDFs that used to open in a browser tab would now automatically download rather than open in browser. I've verified that my Chrome settings are set to Open PDFs in Chrome (rather than the Download PDFs option).

A client asked about this and I checked a few Cgov pages and they all download now rather than open in browser. They used to open in browser. Here are some sample pages:

- https://www.cancer.gov/publications/patient-education/understanding-breast-changes
- https://www.cancer.gov/types/breast/breast-changes (callout box near the top of the page with the heading "Talk with your health care provider about breast changes" has a link directly to the PDF as well)

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Click on a PDF link for a PDF file served by Drupal

### What's the expected result?
- PDFs open in the browser window

### What's the actual result?
- PDFs download rather than opening in the window

### Additional details / screenshot
- Files are getting a header that forces them to download instead of to show in the browser
    - A header of `Content-Disposition: attachment` will force a download. A header of `Content-Disposition: inline` will ask the browser to open in-line
    - This happens when going straight to the site factor, bypassing Akamai
- [Probable culprit](https://github.com/NCIOCPL/cgov-digital-platform/blob/bda582ecc29a25208ac7fd174f9c9b60f3a7ccc2/docroot/profiles/custom/cgov_site/modules/custom/cgov_file/src/EventSubscriber/DirectFileDownloadSubscriber.php#L190C30-L190C43)

### Related Tickets
*

**Comment by sarinapadilla** [comment]
From testing during the 11/7 deployment, this ticket needs to be reopened - it was working for me, but not working for others (Nadia, Bryan, Cam, Liam).

**Comment by bryanpizzillo** [comment]
Just to add to Sarina's notes, the cache for www was manually cleared after the issue was found. So there were multiple clearing of the caches. 

I curled the URL and got the following, which does *NOT* have the correct header.:
```
❯ curl -I "https://www.cancer.gov/types/breast/breast-changes/understanding-breast-changes.pdf" 
HTTP/2 200 
accept-ranges: bytes
content-disposition: attachment; filename="Understanding_Breast_Changes_2024 FINAL.pdf"
content-language: en
content-type: application/pdf
last-modified: Tue, 08 Oct 2024 12:54:50 GMT
server: nginx
x-age: 1331609
x-ah-environment: 01live
x-cache-hits: 22
x-cgdp-managed-file: true
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-generator: Drupal 10 (https://www.drupal.org)
x-request-id: v-b80a563a-86a3-11ef-8e84-13fea73be651
content-length: 2840466
expires: Fri, 08 Nov 2024 03:20:41 GMT
cache-control: max-age=0, no-cache
pragma: no-cache
date: Fri, 08 Nov 2024 03:20:41 GMT
strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
```

**Comment by jfrank-nih** [comment]
Re-closing. This was working correctly on the origin. Akamai caches not getting cleared properly were the issue.
