### ISSUE TITLE
R4: Build Power BI report to anlayze classes/styles and begin analysis

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4452]
Capturing the work of building the dashboard for the analysis, regrouping on approach people working on this, and beginning analysis

Utilize the information in: https://github.com/NCIOCPL/cgov-digital-platform/issues/4439
To be continued by: https://github.com/NCIOCPL/cgov-digital-platform/issues/4440

Target: Build Power BI report by the week of 9/30

**Comment by bennettcc** [comment]
As discussed on 10/10, this task is complete. Analysis of the report will continue as part of https://github.com/NCIOCPL/cgov-digital-platform/issues/4440. Closing ticket
