### ISSUE TITLE
Moderation sidebar is blank

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#4461]
### Issue description
After saving a page, the moderation sidebar comes up blank.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Install with the default YAML content.
2. Create a new article under the `/about-cancer/understanding` site section.
3. Save the article.
4. At the top of the page, click the "Tasks" list.

### What's the expected result?
- The moderation side bar should appear with a list of potential actions.

### What's the actual result?
- The moderation side bar is blank.

### Additional details / screenshot
- ![image](https://github.com/user-attachments/assets/cdd228d3-34fc-4465-825f-56c0c49c4805)

**Comment by blairlearn** [comment]
This is caused by the CIS Slider injecting a nested `<body>` tag.
See https://github.com/NCIOCPL/cis-slider/issues/8

**Comment by welshja** [comment]
@blairlearn - the fix to the slider has been closed and published and the Launch rule has been updated, so this issue should now be resolved and ready to close out.

**Comment by welshja** [comment]
And closing
