### ISSUE TITLE
Story: Create Imageless Card Group Paragraph for MLP

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4464]
### Requirements

**Front-End Functional Requirements**

- The front-end display of the Imageless Card shall behave identical to the behavior created for #4383 
- The Imageless Card Group Heading shall display at the same font size as other NCIDS card groups on the platform. (Not all cards have been updated to the agreed upon size at the time of writing. See specifications for token size.)
- The Imageless Card Title shall display at the same font size as other NCIDS card titles on the platform. (Not all cards have been updated to the agreed upon size at the time of writing. See specifications for token size.)
- The Imageless Card Description shall display at the same font size as other NCIDS card descriptions on the platform. (Not all cards have been updated to the agreed upon size at the time of writing. See specifications for token size.)

**Drupal Group Functional Requirements**

- There is no maximum limit to the number of cards added
- Cards can be added in the 1-Card, 2-Card, or 3-Card layouts as selected by the content editor
- If more cards are added to the container than the number indicated by the X-Card layout, then the cards will go to the subsequent row in the same format of the layout
- If a subsequent row has fewer cards than the row above it, the cards in the subsequent row will match the spacing rules (100% width, 50/50 width, or 33/33/33 width) of the row above it. In the case of 50/50 or 33/33/33, an empty spot will intentionally be left if the subsequent row is not filled.
- The Group Heading will be a required text field
- The Group Heading will have an option to be displayed or hidden for screen readers only

**Drupal Single Imageless Card Functional Requirements**

- A user shall be able to select if the Imageless Card will show internal, external, or multimedia content
- If a user chooses internal or multimedia content, then they shall be able to override the title and/or the description for the card

**Analytics Requirements**
On click of a link button within a summary box, an EDDL event shall be raised with the linkName and event of: MLP:ImagelessCard:LinkClick.

This click event shall send the following information as data elements to EDDL:
- location: 'Body'
- pageType: 'cgvMiniLanding'
- pageTemplate: 'ncids_default'
- componentType: 'Imageless Card'
- pageRows: The total number of rows on the page overall
- pageRowIndex: The index of the selected row from the link click
- pageRowCols: The total number of columns in the row from the link click
- pageRowColIndex: The index of the selected column within the selected row from the link click
- containerItems: The total number of imageless cards added to the Imageless Card Group (there is no maximum)
- containerItemIndex: The index of the selected imageless card, counting will start in the upper left, count left to right, and at the end of each row, the count will continue on the next row again going left to right
- componentTheme: Default is 'Not Defined'
- componentVariant: This should be set based on the layout selected by the user. This should be set to 1 Card Row, 2 Card Row or 3 Card Row.
- linkText: This should be set to the title of the Imageless Card clicked. If the value is longer than 50 characters, this value should be truncated.
- title: This value should be the heading value of the Imageless Card Group (regardless of if it is hidden/shown on the page.) If value is left blank, then it should pass 'Not Defined'.
- linkType: This will be set based on the type of link (internal, external, or multimedia)
- linkArea: For imageless cards, this value should be set to “Description” or “Title” based on where the user clicks. If the area cannot be determined, please pass "Undefined"
- totalLinks: Default will be 1
- linkPosition: Default will be 1

### Specifications

- The Imageless Card Group's required heading field will be a text editor
- The Imageless Card Group's heading will be an h2 element
- The Imageless Card Group's heading will stylistically use token xl (24px)
- The Imageless Card Title will stylistically use token md (20px)
- The Imageless Card Description will use token xs (16px)

### DoR Tasks

- [x] Content Model Drafted
- [x] Content Model Reviewed
  - [x] Developer Review
  - [x] IA Review
- [x] Content Model Approved
  - [x] Developer Approval
  - [x] IA Approval
- [x] Acceptance Criteria Drafted
  - [ ] Analytics Acceptance Criteria Drafted
- [x] Scenarios created for YAML
- [ ] Acceptance Criteria Reviewed
  - [x] Developer Review
  - [x] IA Review
  - [ ] Analytics Review
- [ ] Acceptance Criteria Approved
  - [x] Developer Approval
  - [x] IA Approval
  - [ ] Analytics Approval

### DoD Tasks

- [ ] Governance Drafted
- [ ] PR Review (see PR for review and comments)
- [ ] Client review with demo

### Technical Notes

**Content Model**

- [Update to Paragraph Types](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Types)
- [Imageless Card Group Paragraph](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Imageless-Card-Group)

**Scenarios/Figma**

- On the example page that shows real content, make it look identical to the [Key Initiatives comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4141-27219&node-type=frame&m=dev), but use the [Breakpoints & Specs page](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4403-29459&node-type=text&m=dev) to appropriately define its behavior on each breakpoint. Please use a test url similar to /test/research/key-initiatives. For the links for this page please use the following (NOTE: For Imageless Cards, the comps are being updated, but please do not add an override description so the fallback rules can be tested):
  - [Wide Guide Card CTA "See Funding Opportunities"](https://www.cancer.gov/research/key-initiatives/moonshot-cancer-initiative/funding)
  - [Imageless Card "NCI Equity and Inclusion Program"](https://www.cancer.gov/research/key-initiatives/nci-equity-inclusion-program)
  - [Imageless Card "NCI COVID-19 Research Initiatives"](https://www.cancer.gov/research/key-initiatives/covid-19)
  - [Imageless Card "Childhood Cancer Data Initiative (CCDI)"](https://www.cancer.gov/research/areas/childhood/childhood-cancer-data-initiative)
  - [Imageless Card "The RAS Initiative"](https://www.cancer.gov/research/key-initiatives/ras)
- On the example page for test content, please make a test page following the breakpoints for the Imageless Card found [here](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4403-29460&node-type=vector&m=dev).
  - Page URL: Something similar to /test/imageless-cards/
  - Page Title: Test Page for Imageless Cards
  - 1st component: Content Block with 10 sentences of lorem ipsum.
  - 2nd component: Imageless Card Group
    - Heading: "The Optional Imageless Card Group Heading - One Card"
    - Heading Visibility: Visible
    - Card Layout Display: 1 Column
    - Card 1: Imageless Card Internal
      - Featured Content: [About NCI](https://www.cancer.gov/about-nci)
      - Override Title: N/A
      - Override Description: "This test override description will link to the About NCI page."
    - Card 2: Imageless Card External
      - Link: www.google.com
      - Title: External Link to Google
      - Description: "Test description for external Imageless Card."
    - Card 3: Imageless Card Multimedia
      - Featured Content: ["Pediatric MATCH Infographic"](https://www.cancer.gov/research/infrastructure/clinical-trials/nci-supported/pediatric-match/pediatric-match-infographic)
      - Override Title: N/A
      - Override Description: N/A
  - 3rd Component: Summary Box with title, "Test Summary Box", and the body has 10 sentences of lorem ipsum.
  - 4th Component: Imageless Card Group
    - Heading: "The Optional Imageless Card Group Heading - two Card"
    - Heading Visibility: Visible    - Card Layout Display: 2 Column
    - Card 1: Imageless Card External
      - Link: www.google.com
      - Title: "Second Test of External Card with Longer Title"
      - Description: "This is the second external card in the 2-Imageless Card layout."
    - Card 2: Imageless Card Multimedia
      - Featured Content: NCI at a Glance Infographic
      - Override Title: "Test Multimedia Card"
      - Override Description: "This is a test of the multimedia card in the 2-Imageless Card layout."
    - Card 3: Imageless Card Internal
      - Featured Content: [About Cancer](https://www.cancer.gov/about-cancer)
      - Override Title: "This is an Override Title for About Cancer"
      - Override Description: N/A
  - 5th Component: 3-Feature Card Row
    - Card 1: Feature Card Internal
      - Featured Item: [Cancer Research](https://www.cancer.gov/research)
      - Override Title: N/A
      - Override Description: N/A
    - Card 2: Feature Card Internal
      - Featured Item: [Grants & Training](https://www.cancer.gov/grants-training)
      - Override Title: N/A
      - Override Description: N/A
    - Card 3: Feature Card Internal
      - Featured Item: [Cancer Types](https://www.cancer.gov/types)
      - Override Title: N/A
      - Override Description: N/A
  - 6th Component: Imageless Card Group
    - Heading: "The Optional Imageless Card Group Heading - One Card"
    - Heading Visibility: Visible
    - Card Layout Display: 3 Column
    - Card 1: Imageless Card Multimedia
      - Featured Content: Screen to Save Infographic
      - Override Title: "Override Title for Multimedia"
      - Override Description: N/A
    - Card 2: Imageless Card Internal
      - Featured Content: [Cancer Types](https://www.cancer.gov/types)
      - Override Title: N/A
      - Override Description: N/A
    - Card 3: Imageless Card External
      - Link: www.google.com
      - Title: "Imageless Card External"
      - Description: "Description for Imageless Card External"
    - Card 4: Imageless Card Multimedia
      - Featured Content: [NCI Formulary Infographic](https://www.cancer.gov/research/areas/treatment/nci-formulary-infographic)
      - Override Title: N/A
      - Override Description: "Override description for Multimedia"
    - Card 5: Imageless Card Internal
      - Featured Content: [NCI Homepage](https://www.cancer.gov/)
      - Override Title: "Override Title for Homepage"
      - Override Description: "Override Description for Imageless Card Internal"

### Acceptance Criteria

**CMS User Experience**

```gherkin
Scenario: The NCIDS Imageless Card Group paragraph can be added to the Mini Landing Page content type
  Given the user is logged into the CMS as an editor
    And the user is editing a "Mini Landing Page" content item
    And the Mini Landing Page is using the NCIDS style
  When the user expands the dropdown to add a paragraph to Contents
  Then the dropdown displays "Add NCIDS Imageless Card Group"
  When the user selects "Add NCIDS Imageless Card Group"
  Then the fields for an "NCIDS Imageless Card Group" paragraph appear
    And the first field is the "Heading" field
    And that field is required
    And it is a text entry field
    And the tooltip says, "Displays above the group of cards. Used to concisely describe the featured content."
    And the next field is the "Heading Visibility" field
    And that field is required
    And the field is a dropdown
    And the dropdown has the following options, "Visible" (default), and "Screen Reader Only"
    And the next field is the "Card Layout Display" field
    And that field is required
    And the field is a dropdown
    And the tooltip says, "Sets the number of cards to display in a row, in either a 1, 2, or 3-card layout per row."
    And the dropdown has the following options, "1 Column", "2 Column", "3 Column" (default)
    And the next field is the "Imageless Cards" field
    And that field is required
    And it allows the selection of the following types: "NCIDS Imageless Card Internal" (default), "NCIDS Imageless Card External", and "NCIDS Imageless Card Multimedia"
    And one "NCIDS Imageless Card Internal" will automatically be added to the NCIDS Imageless Card Group
    And at the bottom of the NCIDS Imageless Card Group paragraph there is a dropdown that allows the content editor to add other Imageless Cards to the group
    And there is no limit on the number of Imageless Cards that can be added to the NCIDS Imageless Card Group
  When the NCIDS Imageless Card Internal paragraph is added to the NCIDS Imageless Card Group
  Then the fields for an NCIDS Imageless Card Internal paragraph appear
    And the first field is the "Featured Item" field
    And that field is required
    And it is an entity reference field using the Content Browser allowing Node types
    And the next field is the Override Card Title field
    And that field is optional
    And it is a text entry field
    And the tooltip says, "Used to override the page's card title. Leave blank if no need to override."
    And the next field is the Override Card Description field
    And that field is optional
    And it is a text entry field
    And the tooltip says, "Used to override the page's card description. Leave blank if no need to override."
  When the "NCIDS Imageless Card External" paragraph is added to the NCIDS Imageless Card Group
  Then the fields for an NCIDS Imageless Card External paragraph appear
    And the first field is the "Featured Item Url" field
    And that field is required
    And it is a text entry field
    And the tooltip says, "Enter the full URL starting with https://"
    And the next field is the "Card Title" field
    And that field is required
    And it is a text entry field
    And the tooltip says, "Add card title for page."
    And the next field is the "Card Description" field
    And that field is optional
    And it is a text entry field
    And the tooltip says, "Add description of content."
  When the "NCIDS Imageless Card Multimedia" paragraph is added to the NCIDS Imageless Card Group
  Then the fields for an NCIDS Imageless Card Multimedia paragraph appear
    And the first field is the "Featured Media" field
    And that field is required
    And it is an entity reference field using the content browser with the allowed types cgov_infographic and cgov_file
    And the next field is the Override Card Title field
    And that field is optional
    And it is a text entry field
    And the tooltip says, "Used to override the page's card title. Leave blank if no need to override."
    And the next field is the Override Card Description field
    And that field is optional
    And it is a text entry field
    And the tooltip says, "Used to override the page's card description. Leave blank if no need to override."
```

**Front-End Experience**

```gherkin
Scenario: A user views the NCIDS Imageless Card Group on a Mini Landing Page
  Given the NCIDS Imageless Card Group is created on a Mini Landing Page
    And the Mini Landing Page is using the NCIDS style
  When a user views the NCIDS Imageless Card Group
  Then they will exactly match the comp
  When a user hovers their mouse over an NCIDS Imageless Card
  Then the Title of the NCIDS Imageless Card will display the changed color for the hover state
  When a user clicks on an NCIDS Imageless Card
  Then they will be redirected to the link for that card
  When the breakpoint is smaller than tablet large (less than 880px)
  Then the cards will stack vertically
```

**Analytics**

```gherkin
Scenario: Analytics events for the NCIDS Imageless Card Group on Mini Landing Pages using the NCIDS style

```

**Comment by bryanpizzillo** [comment]
@dev-rana-publicis please make sure that the Internal & External imageless cards do not use the default display mode when drawing them in the group. This is so that we can possibly use a single imageless card in the 2 column in the future. (This is basically what we had to do for the Feature Cards if you remember)

**Comment by welshja** [comment]
Updating analytics reqs for componentvariant that did not make it onto the ticket before.

componentVariant: This should be set based on the layout selected by the user. This should be set to 1 Card Row, 2 Card Row or 3 Card Row.

**Comment by bryanpizzillo** [comment]
@andyvanavery31 I changed the third feature card to be "Cancer Types" instead of "News & Events", because of the ordering of the YAML. @dev-rana-publicis changed the filename of "News & Events" to correct allow the test page to reference it,  but the change broke the "News & Events" page's featured news row.
