### ISSUE TITLE
Create Recommended Content Common Field

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#447]
This story is to create the common paragraph [Recommended Content](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Recommended-Content) (aka clickbait).

This should allow for internal and external links to be featured.  This currently should only display on blog posts.

The user can enter up to 3 pages (or if the system can't limit how many pages to enter, than only 3 will be displayed on the front end)

**Comment by bgnih** [comment]
@nicolecrom  @VictoriaSunNIH  Should I use the existing paragraph bundle "cgov_eternal_link" or create something new that matches these requirements?   

![image.png](https://images.zenhubusercontent.com/5c0fd0a81a65780cf410b298/ca0c54a4-3e81-4781-93db-7739191802cc)

**Comment by bryanpizzillo** [comment]
Ok, see https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#recommended-content

Tasks:
* Make a cgov_promo module
* Move cgov_card_* content types into cgov_promo
  * Fields, display modes, etc for those cards
* Create field_recommended_content shared storage in cgov_promo module
* Create new display mode for Recommended Content  (recommended_content_card)
  * Add for cgov_card_* paragraph types

**Comment by bgnih** [comment]
@daquinohd @bryanpizzillo So are we replacing the existing External Link paragraph bundle with this new specification, or renaming the Label/Machine name of it?  

`cgov_external_link` is currently used in `cgov_cancer_center`, `cgov_cgov_biography`, etc.

**Comment by bryanpizzillo** [comment]
Links and Cards are two separate things. The content model page incorrectly referred to the Recommended Resources as being links. I adjusted the page to address that mistake. I have enumerated what I believe to be the tasks in the comment above.

**Comment by VictoriaSunNIH** [comment]
@daquinohd , @bgnih - just to be clear, this should only get attached to blog posts for now.  Article and Press release are future backlog items.

**Comment by lburack** [comment]
I see that the field is on the blog series so marking this as Passed IA Review. I'm not seeing this on my blog posts though. That's #450 so we can deal with it there.
