### ISSUE TITLE
CR: Remove MLP Title Paragraph and Add it to the MLP Template

### ISSUE THREAD

**Issue by andyvanavery31** [NCIOCPL/cgov-digital-platform#4471]
### Change Request
This request is to remove the MLP Title paragraph from Drupal and to add the title back to the template of Mini Landing Pages. 
Notable Proposed Changes (agreed upon by internal team 16OCT2024):
- The MLP Title paragraph will not be a paragraph to be added by content editors
- The MLP Title will appear above all other body content on MLP pages using the NCIDS style (including slim hero)
- Requirements change: 
  - The content editor shall **not** have the ability to control where the title is placed on MLPs

**Questions**
- How would we have to adjust the current measurement pages?
  - Only pages impacted are [Managing Cancer Care](https://www.cancer.gov/about-cancer/managing-care) and [Research Areas](https://www.cancer.gov/research/areas), do those need to be manually changed?
- Do we need to mark the change as a landmark in analytics testing to evaluate the change?

### DoR Tasks

- [x] Product (Andy) to gain approval from client on making this change
- [x] Design (@blilianyu @monika-jaeger) to make changes to comps to reflect the title going to the top (after gaining client approval)
- [x] Ticket, comp, and AC reviewed and approved by developer

### What's the expected change?
- The MLP pages with the NCIDS style will have the title appear at the top of the page above all body content.
- On the CMS, the MLP Title paragraph will be removed as a paragraph and it will be added to the template to render at the top of the page

### What's the current functionality?
- The MLP Title paragraph needs to be manually added to MLP pages using the NCIDS style, and it can be placed anywhere on the page (before or after the slim hero).

### What's the updated acceptance criteria?
**CMS Behavior**
```gherkin
Scenario: Adding or editing a new Mini Landing Page content type with the NCIDS Style on the CMS
  Given the user is logged in as an editor on the CMS
    And the user is adding or editing a "Mini Landing Page" content item
  When the user is on the Mini Landing Page content type
  Then the user sees the "Page Title" required field as a part of the Mini Landing Page template
  When the user adds text to the "Page Title"
  Then the Title will be added to the top of the page
    And there will be no paragraph to add a title to the Mini Landing Page
```

**Front-End Behavior**
```gherkin
Scenario: A site visitor goes to a Mini Landing Page using the NCIDS Style
  Given the user is on a Mini Landing Page
    And the Mini Landing Page is using the NCIDS Style
  When the user views the top of the page
  Then the page title will be displayed above all other body content
```

**Analytics**
- Any Mini Landing Page components that reference the page title shall maintain their functionality for analytics without change.

### Related Tickets
* Original Story Ticket #4357

**Comment by monika-jaeger** [comment]
All [Priority MLP Comps](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4132-32847&t=eR1nGMntrCzy9ph3-1) have been updated with the page title displayed above all other body content. 
cc: @andyvanavery31 @blilianyu
