### ISSUE TITLE
Analytics on Spanish Cancer Types Landing Page Not Setting Page Row Values Correctly for Accordion

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4502]
### Issue description
When users click on items on the Spanish Cancer Types landing page, analytics clicks within the A-Z accordion section are not firing analytics as expected. The total page rows value is off by 1 (showing 2 not 3) and the page row index value is passing as 0.

It looks like the accordion section is not being counted as a row within the page. 

### Steps to reproduce the issue
Go to the [Spanish Cancer Types landing page](https://www.cancer.gov/espanol/tipos) with Omnibug or some analytics debugging tool open. Scroll to the accordion section, and click a letter to expand the accordion. Look at the evar66 values. Next click on cancer type to go to that page and look at the evar66 values.

### What's the expected result?
The total page rows should be 3 as there are 3 rows of rawHTML components within the page. 
The page row index should also be 3 as the clicks are happening in the 3rd row on the page.

### What's the actual result?
The total page rows value is off by 1 (showing 2 not 3) and the page row index value is passing as 0.

**Comment by navsunka** [comment]
@welshja , It is a spanish content issue on production. Raw HTML content in the backend needs to be updated.
Currently the structure is like this
![Screenshot 2024-11-15 at 10 54 37 AM](https://github.com/user-attachments/assets/70734127-3074-4326-b52c-8f1b7e35cf96)
It has to be like this
![Screenshot 2024-11-15 at 10 55 01 AM](https://github.com/user-attachments/assets/48300bbc-49a9-4af0-ac54-89279489d7be)

**Comment by welshja** [comment]
The updates Naveen identified have been published in production. Closing this one out. CC - @navsunka
