### ISSUE TITLE
Home and Landing: Build rev 1 of home and landing pages 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#46]
This story is to build the minimally viable product version of [layout ](https://github.com/bryanpizzillo/cgov-digital-platform/wiki/Content-Type-Home-Page#layout-builder-regions. )builder for home and landing pages. Hero Header/Banner is being created in ticket #47 

**[Regions to Include:](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-Page#layout-builder-regions)**
* Primary Feature Card Row
* Secondary Feature Card Row
* Guide Card Row 
* Multimedia Row 
* Thumbnail Row
* News & Events Row

**Comment by amydugan** [comment]
Closing this ticket. This was built out to the point where we could discuss the features. However, without a draft moderation state, PMO decided to go with the Paragraphs for Home/Landing page.
