### ISSUE TITLE
PMO Dry Run Content for 1/10/2019

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#460]
For the demo for the Article Page, we would like to see the following (in priority order):
### Section Nav should display the following (See attached screenshot):
* Parent Section 
  * Child Section 1 (with plus sign) 
  * Child Section 2 
      * Child Page 2 (underneath section 2)

<img width="298" alt="screen shot 2019-01-09 at 11 52 20 am" src="https://user-images.githubusercontent.com/29731392/50914786-5bdb4700-1405-11e9-9d2d-d94e5fd9a2af.png">

### Megamenu Display:
  * All of the sections should appear in the black bar, as it does on Cancer.gov on prod.  (About Cancer, Cancer Types, Research, Grants & Training, News & Events, About NCI) -- don't need the actual megamenu to work, just want to have it looking like it.
  * The search bar should appear in the black bar
## Things that are already correct, but make sure they stay this way:
* The NCI banner
* The translation toggle
* The Blue Utility Bar
* Page Options
* Footer
* Body Content
* Appearance of Article Image in the body content

**Comment by lburack** [comment]
Here is what the section nav should look like

<img width="298" alt="screen shot 2019-01-09 at 11 52 20 am" src="https://user-images.githubusercontent.com/29731392/50914741-3fd7a580-1405-11e9-8f29-cfb16f160300.png">

**Comment by VictoriaSunNIH** [comment]
Completed!
