### ISSUE TITLE
Home and Landing: Build hero banner

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#47]
[Hero Banner](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-Page#layout-builder-regions) consists of:
* HTML block that displays provided text on top of the homepage hero banner image at desktop and tablet breakpoints
* Images (desktop and tablet) for the banner

Hero Banner does not display on Mobile

**Comment by amydugan** [comment]
Closing out as this was associated with the layout builder Home/Landing ticket. It is a duplicate of https://app.zenhub.com/workspaces/cgov-digital-platform-5c0fc73f4b5806bc2bfc78bd/issues/nciocpl/cgov-digital-platform/310.
