### ISSUE TITLE
Enlarge Field on Image Content Type

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#471]
This story is to create the file [Enlarge](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#enlarge) and attach it to the Image content type.

This field will be a checkbox with the label "Enlarge" that, if selected, will add an Enlarge button to an image which allows the user to view the full original image. If it is not checked, there will be no Enlarge button on the image. The checkbox should default to unchecked.

**Comment by amydugan** [comment]
Moving to Sprint 7 with Implementing Image Requirements. @amydugan to group tickets.
