### ISSUE TITLE
On This Page - Accordion 

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#473]
This story is to enable the Accordion feature for Mobile views for [On This Page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article#on-this-page)

If there is no heading provided for the section (i.e. no H2), no bullet should be drawn in OTP on desktop. For the display on mobile, the "headerless content" should not be swallowed into the accordion.

**Comment by alifr** [comment]
I'm encountering an issue with the front-end concerning accordions. For the styles to be applied properly to home-landing pages, we need a specific class name on the `<body>` tag. In Percussion this class name was `ncilandingpage`. It looks like this may also be true for `cgvcancertypehome`, `cgvfactsheet` and `pdqcancerinfosummary`.

I've seen in other Drupal themes, they often add code to the `html.html.twig` template to attach the content node type as a class to the body, which is similar to what was being done in Percussion.
```
{%
  set body_classes = [
    logged_in ? 'user-logged-in',
    node_type ? node_type|clean_class,
  ]
%}
```
```
<body{{ attributes.addClass(body_classes) }} {{ attributes }}>
```

However, the class names will not match up as `ncilandingpage` is in Percussion and Drupal will produce `cgov-home-landing` as the class name. So, should I adjust the template logic to include a switch statement that will map the node types to their Percussion class names or should I update the CSS to match the Drupal node classes or should this be handled on the module level?

**Comment by bryanpizzillo** [comment]
@alifr Can you please inventory all the places we are targeting the content types? It is a little more complicated than just getting the type
* we have merged cgvFactSheet, *some* cgvGeneral and cgvArticle into cgov-article. 
* cgvGeneral could be a cgov-mini-landing or cgvArticle
* cgvTopic could be a cgov-article or cgov-mini-landing
* Some features of the old system are being replaced and new features added:
  * The hack https://github.com/NCIOCPL/wcms-front-end/blob/261f0cc46a65facf84d820a12310cea7c17ed5ca/CancerGov/_src/StyleSheets/_hacks.scss#L2 could possibly apply to all content types. More correctly it would apply just to field-article-body.
  * https://github.com/NCIOCPL/wcms-front-end/blob/2147ddbaa4fc657433b3ef72fb5d5fdba03be228/CancerGov/_src/Scripts/NCI/UX/Themes/purple/purple.scss#L19 could apply to any wysiwyg really.

So we really need to find those places and determine how best to target those things. In fact as I type this, the best way to target may be by field... (he says not knowing what new hell that will unleash)

**Comment by VictoriaSunNIH** [comment]
@alifr , @bryanpizzillo  - I've asked @markecramer to create the inventory.

**Comment by markecramer** [comment]
I've put together an excel sheet with the info.

[body-tag-styles.xlsx](https://github.com/NCIOCPL/cgov-digital-platform/files/3005506/body-tag-styles.xlsx)

**Comment by markecramer** [comment]
My inventory was based on things in the body tag. There may be more to this than that, if so I'll have to look further during the week.

**Comment by VictoriaSunNIH** [comment]
Split off the inventory into 1339.  I think OTP Accordion is working as expected on mobile.  @alifr - can we close this out now that I've opened #1339?

**Comment by alifr** [comment]
@VictoriaSunNIH Mark's spreadsheet captures the full inventory. Not just the accordions.

**Comment by amydugan** [comment]
#1339 includes the full inventory. Closing this OTP - Accordion ticket.
