### ISSUE TITLE
Change Article Image field to Lead Image

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#474]
The label on pages that have the Article Image field should be changed to "Lead Image".  As this is going to be changed, we should just change the field name.

https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#article-image

**Comment by amydugan** [comment]
The remaining update that will need to be made is to change the machine name in the drupal field manager

**Comment by bryanpizzillo** [comment]
Never going to happen. Closing. (The label did get changed though) Blame @lburack if you don't like this fact. :P
