### ISSUE TITLE
BUG: Unable to Add Translation to published node in UI

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#475]
Once a node has been published, it can no longer have a translation attached via the UI.

Error Demo:
1. Create a new Article or Press Release node 
1. Publish Node (eg: `/node/1`)
1. Create Spanish Translation of this node (eg: `/espanol/node/1/translations/add/en/es`)
1. When you try to save the content, it gives an error `Invalid state transition from Publicado to Draft` (fails for all moderation state options)

It will properly create the Spanish Translation if done prior to the original node being published.

**Comment by bkline** [comment]
I can reproduce in my branch. I had thought this was working at one point but could be mistaken. One wild though I had was: could Drupal be so dumb that it's confusing the display names for the states with the machine names? I do know that at least in [the kernel test](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php#L136) we verify that it's possible to:

1. create a new content type
1. attach the editorial workflow to it
1. create a new node of that type in the default language (English)
1. create a Spanish translation of the node
1. save the translation in the draft state
1. transition from `draft` to `draft` or `review`

Don't know why that's not working in the UI.

**Comment by bkline** [comment]
I have tracked down the failure to another bug in Drupal core.

https://www.drupal.org/project/drupal/issues/3029219

**Comment by bkline** [comment]
Here's a patch which fixes the problem until the core team can get around to it:

```
diff --git a/modules/content_moderation/src/ModerationInformation.php b/modules/content_moderation/src/ModerationInformation.php
index abc93f403f..3934dad49f 100644
--- a/modules/content_moderation/src/ModerationInformation.php
+++ b/modules/content_moderation/src/ModerationInformation.php
@@ -85,8 +85,8 @@ class ModerationInformation implements ModerationInformationInterface {
   /**
    * {@inheritdoc}
    */
-  public function getLatestRevision($entity_type_id, $entity_id) {
-    if ($latest_revision_id = $this->getLatestRevisionId($entity_type_id, $entity_id)) {
+  public function getLatestRevision($entity_type_id, $entity_id, $langcode='') {
+    if ($latest_revision_id = $this->getLatestRevisionId($entity_type_id, $entity_id, $langcode)) {
       return $this->entityTypeManager->getStorage($entity_type_id)->loadRevision($latest_revision_id);
     }
   }
@@ -94,15 +94,18 @@ class ModerationInformation implements ModerationInformationInterface {
   /**
    * {@inheritdoc}
    */
-  public function getLatestRevisionId($entity_type_id, $entity_id) {
+  public function getLatestRevisionId($entity_type_id, $entity_id, $langcode='') {
     if ($storage = $this->entityTypeManager->getStorage($entity_type_id)) {
-      $result = $storage->getQuery()
+      $query = $storage->getQuery()
         ->latestRevision()
         ->condition($this->entityTypeManager->getDefinition($entity_type_id)->getKey('id'), $entity_id)
         // No access check is performed here since this is an API function and
         // should return the same ID regardless of the current user.
-        ->accessCheck(FALSE)
-        ->execute();
+        ->accessCheck(FALSE);
+      if (!empty($langcode)) {
+        $query->condition('langcode', $langcode);
+      }
+      $result = $query->execute();
       if ($result) {
         return key($result);
       }
diff --git a/modules/content_moderation/src/Plugin/Validation/Constraint/ModerationStateConstraintValidator.php b/modules/content_moderation/src/Plugin/Validation/Constraint/ModerationStateConstraintValidator.php
index 7894cadf75..6b6ea3dd5d 100644
--- a/modules/content_moderation/src/Plugin/Validation/Constraint/ModerationStateConstraintValidator.php
+++ b/modules/content_moderation/src/Plugin/Validation/Constraint/ModerationStateConstraintValidator.php
@@ -177,7 +177,8 @@ class ModerationStateConstraintValidator extends ConstraintValidator implements
    *   TRUE if this is the entity's first time being moderated, FALSE otherwise.
    */
   protected function isFirstTimeModeration(EntityInterface $entity) {
-    $original_entity = $this->moderationInformation->getLatestRevision($entity->getEntityTypeId(), $entity->id());
+    $langcode = $entity->language()->getId();
+    $original_entity = $this->moderationInformation->getLatestRevision($entity->getEntityTypeId(), $entity->id(), $langcode);
 
     if ($original_entity) {
       $original_id = $original_entity->moderation_state;
```

**Comment by bgnih** [comment]
FYI: Bob's issue [State transition validation ignores language when determining "first time moderation"](https://www.drupal.org/project/drupal/issues/3029219) was marked as a duplicate of [When adding a new translation the entity should start from the draft state
](https://www.drupal.org/project/drupal/issues/2927455) and flagged as a feature request instead of a bug (which doesn't seem right to me).

**Comment by bkline** [comment]
@bgnih I reopened the bug report, explaining in careful detail why this is a different bug.
