### ISSUE TITLE
Identify additional GateKeeper functionality to be replaced

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#494]
The decisions has been made to retire the GateKeeper software. We are well on the way to defining and importing PDQ Cancer Information Summary documents, replacing that portion of the GateKeeper functionality. We need to determine what else from that subsystem needs to be implemented for the new CMS. For example,

- image processing/storage?
- drug information summary import?
- reporting?
- other?

**Comment by blairlearn** [comment]
List of dependencies: https://github.com/NCIOCPL/cgov-digital-platform/wiki/GateKeeper-Dependencies

**Comment by amydugan** [comment]
Closing this, as the investigation piece was done.
