### ISSUE TITLE
List Description Field Should be Multi-row

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#502]
These two should present as a multi-row editing interface. (5 rows?)

@lburack I am not including Feature Card Description since that should be short.
@bryanpizzillo  I'm deleting Meta Description from this ticket because we want that field to have a 320 character limit.

**Comment by amydugan** [comment]
Assigning to @VictoriaSunNIH for punchlist

**Comment by VictoriaSunNIH** [comment]
Closing this and folding it into the separate content type updates tickets I'll be entering.
