### ISSUE TITLE
Configure to use NIH Authentication

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#505]
This story is to setup the system to use NIH Login Authentication.

**Comment by blairlearn** [comment]
# SAML
Install the [simpleSAMLphp Authentication module](https://www.drupal.org/project/simplesamlphp_auth)
* Requires installing SimpleSAML.php
  * Must be configured as a service provider.
  * Must be configured to use either memcache or sql.
* Add [memcache](https://hub.docker.com/_/memcached) to the Docker container setup.

# Alternative - SiteMinder
A failed alternative approach would be to reuse the [NCI SSO module](https://github.com/NCIOCPL/nci_SSO) (or an updated copy from myNCI or a similar project). This alternative fails however in that it requires the SiteMinder agent to be installed which we will most likely not be able to have installed in the Acquia hosted environment.

**Comment by blairlearn** [comment]
WooHoo!  Going to http://www-int-ac.cancer.gov/simplesaml/module.php/core/authenticate.php and testing (via the `cancergov-sp` provider) takes you the NIH authentication dev server. WooHoo!
