### ISSUE TITLE
Autoload SSO Users for Our Team when an ACSF site is Provisioned

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#508]
We need to pre-load our SSO user accounts when an ACSF site is provisioned so that we may build out the site.

Remaining tasks to be completed:
- [ ] Copy `cgov-drupal-users.yml` from ACE.
- [ ] Verify all of our team members are listed in the `cgov-drupal-users.yml`.
- [ ] Remove end user test accounts.

**Comment by adriancofie** [comment]
This ticket is to ensure that NIH roles are mapped correctly to Drupal through SAML

**Comment by blairlearn** [comment]
The existing `drush cgov:bulk-load-users` command gets us most of the way there.  What remains is to create an entry in the `authmap` table for each user.

**Comment by blairlearn** [comment]
As part of #505, `drush/Commands/cgov/CgovUserCommands.php` has been modified so `drush cgov:bulk-load-users` will create an entry in the `authmap` table.

PR #1581 will add this functionality.

**Comment by bryanpizzillo** [comment]
* The Drush command drush/Commands/cgov/CgovUserCommands.php has been updated to allows nulls for passwords.
* ACSF-convert has its own cgov-drupal-users.yml
* A post-install script has been created which as part of the steps is to load our version of the cgov-drupal-users.yml.
   * This will alternatively look for /mnt/gfs/ncigov/home/common/cgov-drupal-users.yml.

This was part of #2001.
