### ISSUE TITLE
Migration Scripts Epic

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#510]
This story is to create Migration Scripts

**Comment by bryanpizzillo** [comment]
Yeah... @nicolecrom can you mark this as an epic? Or make it a "Create Approach for Migration?" Otherwise this is waaaaay too vague.

**Comment by amydugan** [comment]
Moving to Epics "sprint" since the specific scripts will span multiple sprints.

**Comment by bryanpizzillo** [comment]
I am going to call this one closed.
