### ISSUE TITLE
Sort of content list by status is broken

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#523]
Clicking on the STATUS header on the `/admin/content` page as the administrator (so you see unpublished content) leaves the order of the list with published and unpublished content intermixed.

**Comment by blairlearn** [comment]
@bkline - this appears to have been fixed. Can you verify?

**Comment by bkline** [comment]
Yes, I think this must have been fixed with the latest update of Drupal core.
