### ISSUE TITLE
Add rules to workflow to prevent private archive

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#528]
phase 1: we will build relationship manager and impact analysis report - and nothing in the system guards against private archive.  Only super admins can approve the private archive
phase 2: add in guards in the system to not allow people to private archive unless they've checked impact analysis

**Comment by bkline** [comment]
@VictoriaSunNIH, I'm not sure I understand everything in this ticket.

> ... nothing in the system guards against it.

What's the _it_ in this sentence?

> Only super admins can approve the private archive

This appears to contradict the diagram in https://github.com/NCIOCPL/cgov-digital-platform/wiki/Editorial-Workflow, which allows editors to approve requests to archive a piece of content.

> ... unless they've checked

Is this sentence incomplete?

**Comment by VictoriaSunNIH** [comment]
@bkline - this is not completed yet, as this is a backlog item.  Please ignore for now.  Will not be happening for the migration.
