### ISSUE TITLE
Public Use configuration error

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#546]
I believe the fix for #503 is incorrect.

In `cgov_core`, `field.storage.node.field_public_use.yml` defines `public_use` as type `list_integer`.

In `cgov_article` and `cgov_press_release`, the `field.field.node.MODULE.field_public_use.yml` files set field_type to `list_string`. It should be set to `list_integer` instead.

Making a similar change in `pdq_cancer_information_summary` works in the user interface, but Functional tests fail with a schema error.
```
1) Drupal\Tests\cgov_site\Functional\PDQSummaryTest::testSummaryFieldsExist
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for field.field.node.pdq_cancer_information_summary.field_public_use with the following errors: field.field.node.pdq_cancer_information_summary.field_public_use:default_value.0.value variable type is integer but applied schema class is Drupal\Core\TypedData\Plugin\DataType\StringData
```

**Comment by bgnih** [comment]
Fixed as part of #860
