### ISSUE TITLE
Update Syndication Default on Article (to be unchecked now)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#548]
Per 1/23 conversation with Lynn, users should choose to syndicate their content. This ticket is to change the Syndication field default on Articles to now be unchecked ((https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Article). This is pending input from the core team (meeting on 1/29).

Note: as a migration rule, content that is currently syndicated should migrate into Drupal with this option checked so it continues to be syndicated.

**Comment by VictoriaSunNIH** [comment]
I'm closing this ticket - we haven't implemented this on Article yet, so this should be set when we add syndication to article in a future sprint.
