### ISSUE TITLE
Technical Item: Prevent taxonomy term deletion if it is referenced within any entities

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#570]
>**_NOTE:_** This had been worked on as part of PR#2489. We closed it as it had aged out of usefulness, but there are probably useful code snippets.

## Description 

Implement functionality to prevent taxonomy term deletion if is referenced within any entities.

**General logic**
 1. Admin users may delete taxonomy items provided they are not referenced within a published revision.  (An exception to this is Blog topics which an can deleted at any time.)

2.  If an entity is reverted to a version which references the deleted term, the field should be empty.

Affected taxonomies:

This ticket prevents taxonomy term deletion if used in the default revision for the following taxonomies:

cgov_event_series
cgov_event_venue
cgov_cancer_center_types
cgov_cancer_center_regions
cgov_biography_campuses

**Blog topic logic**
    1. Blog topics can be deleted at any time
    2.  If a topic is deleted: All blog posts that were tagged with the topic should be untagged

### Acceptance Criteria
```gherkin
Scenario: An admin attempts to delete a taxonomy item from a published revision entity
  Given the admin is logged into the CMS
    And they have found a taxonomy item to delete
  When the taxonomy item is referenced within a published revision entity
    And the published revision entity is not a Blog topic
  Then the taxonomy term cannot be deleted
    And on the taxonomy term page a warning will be shown to the admin of "Taxonomy term cannot be deleted. The term is used in a published revision."
  When the taxonomy item is referenced in a published revision entity
    And the published revision entity is a Blog topic(s) only
  Then the taxonomy item will be deleted
    And all blog posts that were tagged with the topic will be untagged
  When the taxonomy item is not referenced in any published revision entities
  Then the taxonomy item will be deleted
  When a published revision entity is reverted to a version that references a deleted taxonomy item
  Then the field will be empty
```

**Comment by amydugan** [comment]
@adriancofie - which taxonomy terms are we talking about? Just site sections? Checking to see what generated this issue. 

We may want to set this up on a per taxonomy basis, but we need more info.

**Comment by adriancofie** [comment]
This was created specifically with Site Sections in mind, however it could also be applied to other taxonomies. Either way, capturing it in one ticket should be fine as the solution should apply fairly similarly to all taxonomies.

**Comment by VictoriaSunNIH** [comment]
This should apply to all taxonomies - if a term is being used, it should not be able to be deleted.

**Comment by VictoriaSunNIH** [comment]
Requirements to provide/consider:
- under what circumstances can a site section be deleted? Do we want to allow them to be deleted at all? Or are they just hidden?
- Does this apply to all site sections
- What is the behavior if I try to delete a taxonomy thats currently in usage on a node?
- Whats happens if I revert a node back to a previous version, which used a term which has since been deleted?
- For site sections, can I delete a term thats a parent of other sections?  If so does it delete all the sub sections as well?

**Comment by bryanpizzillo** [comment]
@andyvanavery31 -- Why are we excluding cgov site sections from this rule???

**Comment by KateMashkinaNIH** [comment]
Passed QA ( with added restriction to site sections)
