### ISSUE TITLE
ODEs Provision without an installed profile

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#586]
Something about our current setup is causing ODEs to spin up without a profile installed. It is possible this has to do with the new pre-web-activate hooks ACSF init installed. (e.g. just the fact that there is a hook it does that instead of deploy.

**Comment by bryanpizzillo** [comment]
This was not due in part to pre-web-activate. I tested a update where that folder was removed.

**Comment by amydugan** [comment]
This Acquia bug is a pain but not a blocker for May 2019 go live. Marking it as in scope for May 2019 in case it gets fixed by Acquia in time.

**Comment by amydugan** [comment]
Not to be estimated as this is an Acquia bug that isn't a Blocker for initial go live,

**Comment by bryanpizzillo** [comment]
Yeah, this is now an official Acquia known issue. So this is out of scope for June.

**Comment by VictoriaSunNIH** [comment]
This is now how their system works.  Closing as OBE
