### ISSUE TITLE
If an ODE uses a new server, our secrets files are not available.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#587]
During our update and deploy process (post-code-update and post-code-deploy hooks) we leverage the ncigovcd user's home directory to get the slack web hook information (slack_settings) to announce a deployment has occurred. We also autoload our test users into the new environment as well (cgov-drupal-users.yml).

I have noticed, recently that an ODE was deployed to a new server with a new home directory. That new home directory did NOT contain these files. 

This ticket is to figure out what to do to make these files available whenever a new environment spins up.

**Comment by bryanpizzillo** [comment]
This still does not have a real solution available to us. Well, I guess if we make our own UX for creating ODEs and that UX checks the file existence AFTER the ode is created.

**Comment by andyvanavery31** [comment]
We are looking at creating an automation workflow. The work is being tracked here: https://github.com/NCIOCPL/cgov-digital-platform-automations/wiki/Create-ODE

**Comment by blairlearn** [comment]
Fixed by the "ACE - Create ODE" workflow in cgov-digital-platform-automations
