### ISSUE TITLE
Technical Item: Need a better way of handling credentials for the PDQ importers.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#594]
## Description 

The PDQ importers currently retrieve their password from the PDQ_IMPORTER_PASS environment variable. Ideally, there should be an API key instead of a password which is set in the database.

**Comment by bryanpizzillo** [comment]
Linked to from the REST API pages https://www.drupal.org/project/oauth2_authentication

**Comment by VictoriaSunNIH** [comment]
Closing this - per @bryanpizzillo it's good enough for now, and we will open and address if needed in the future
