### ISSUE TITLE
Technical Item: Validate the Computed Path field for a site section would be unique 

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#604]
## Description 

The computed path field consisting of a terms parent computed path, and the terms Pretty URL must always be unique. Depending on the scenario throw a validation error on either the Pretty URL field, or prevent the reordering of the taxonomy term hierarchy.

**Comment by bryanpizzillo** [comment]
I am going to add this here instead of a new ticket. Create a new one if you don't agree:

A Site Section should not be allowed to have multiple parents.
