### ISSUE TITLE
Implement Press Releases front-end look and feel

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#607]
Implement [Press Releases](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release) front-end look and feel for press releases themselves, as well as their dynamic list (view) pages for each year's archives.

Press Release listing page layout: https://hzgfzw.axshare.com/#g=1&p=press_release_listing_page

Examples on Cancer.gov: 
List View Page Examples (English & Spanish):
https://www.cancer.gov/news-events/press-releases/2019
https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2019
https://www.cancer.gov/news-events/press-releases/2018
https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2018

Blog Post Examples (English & Spanish):
https://www.cancer.gov/news-events/press-releases/2018/cll-ibrutinib-trial
https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2018/llc-ibrutinib-estudio
https://www.cancer.gov/news-events/press-releases/2013/E3805 (older blogs that have 2 dates)
https://www.cancer.gov/espanol/noticias/comunicados-de-prensa/2013/E3805

**Comment by amydugan** [comment]
@alifr - does #743 close this ticket?

**Comment by amydugan** [comment]
Closing as this was addressed in #743
