### ISSUE TITLE
Implement Blogs look and feel on front-end

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#608]
Implement the look and feel on the front-end for:
- [ ] Blog Series
- [x] Blog Posts
- [ ] Blog Archive Listing (View) Pages
- [ ] Blog Category Listing (View) Pages

**Comment by alifr** [comment]
Only Blog Post was completed. The other templates are waiting on back-end implementation.

**Comment by VictoriaSunNIH** [comment]
Will reopen separate tickets for blog series and views
