### ISSUE TITLE
Add Syndication to Blog Posts

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#650]
In 2/4 Core Team meeting, discussion of syndication touched on syndicating blog posts. This ticket is to create/attach [syndication](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#syndicate) and [syndication keywords](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#syndication-keywords)

Syndicate should default to be unchecked on [Blog Posts](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Posts#common-fields).

This ticket relates to #154.

**Comment by amydugan** [comment]
For now, Syndication will not be added to Blog Posts. This may be a future requirement and could be added later if so.
