### ISSUE TITLE
Biography Epic

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#663]
This Epics includes all stories needed to support and implement Biographies including the content type, workflow, templates, and look and feel on the front end.

- [ ] Create Biography Content Type #157 
https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography

- [ ] Implement Biography look and feel on the front-end
Page Display
https://publicis.invisionapp.com/d/main#/projects/prototypes/15695431
This will reuse the same template for display as Cancer Centers Content Type
Image will need to be flexible - max width, flexible height

**Comment by BrendanBeltzNIH** [comment]
I'm closing this because it has no open story points. So in epic terms, the fat lady sang.
