### ISSUE TITLE
YAML content importer should be repeatable

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#679]
At the very least, the importer should recognize when headers, footers, breadcrumbs, etc. are already there and either replace them or avoid installing duplicates. It would also be nice if it replaced nodes it had already imported, though that might be tricker to pull off.

**Comment by BrendanBeltzNIH** [comment]
As I mentioned, the ability to update rather than duplicate entities has been a future update since the beginning. It hasn't been a priority because in practice the loader is only run once on installation.

**Comment by bryanpizzillo** [comment]
I am closing this as I think it is mostly repeatable. The code allows for it, but specific older content that needs to be cleaned up might. This should be tracked as separate tickets.

**Comment by bryanpizzillo** [comment]
FYI, between module updates and tweaks we made for other things this all got much better from when this ticket was created.
