### ISSUE TITLE
Add site sections to PDQ Cancer Information Summaries

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#693]
When a cancer information summary is imported into the system, we need to add it to the navigation structure of the site.
* After a summary is imported (or replaced) OR an update changes the url:
   1.  Determine the language of the summary.
   1. Tokenize the summary URL based on `/`. The url `/foo/bar/bazz/placeholder-treatment` would become `['foo', 'bar', 'bazz', 'placeholder-treatment']`
   2. Find the Term in the Site Section vocabulary with the langcode of the summary language AND a parent TID == 0. (i.e. Either the English Home section or the Spanish Home section)
       * This is depth 0 in the nav tree
   2. Set the current section to the root.
   3. For each token of the URL:
       1. determine if there is a child of the current section with a `field_pretty_url` matching the current token. 
           * If there is, set the current section to that child node.
           * If there is not create a new section supplying the token as the `name` (the title field for a term) and the `field_pretty_url`. Then set the current section to that new node
       2. if this is the last token:
          * Set the `name` to the value of the Nav Label (or whatever the CDR calls it) element
          * Set the `field_landing_page` entity reference to the Summary that was loaded.
       3. IF NOT move on to the next token.
* If a summary is updated and the Nav Label is changed:
   1. Find the site section with that URL path. (`computed_path` is a field that has the full path, it may be quicker with that than traversing the tree).  
    1. Change the `name` field.

**Comment by bkline** [comment]
@bryanpizzillo, you said I'd have some questions and, as always, you were right!

First, why is the form for creating a new `cgov_site_section` entity titled *Main page content*?

> iii. Find the Term in the Site Section vocabulary with the langcode of the summary language AND a parent TID == 0

If it's not there (as would be the case right now, because there are no `cite_gov_section` terms in the system), should I create it, or throw an exception? If create, with what values?

> a. determine if there is a child of the current section with a `field_pretty_url` matching the current token

Does that field match the current token, or does it match the front part of the URL through that token? If it's really just the single piece of the URL, it would probably be helpful to have a description for the Pretty URL field explaining that it's not the full URL but just a piece of it.

> a. Set the `name` to the value of the Nav Label (or whatever the CDR calls it) element

So, override the first part of the previous action, where we set `name` to the value of the token? It would seem to be more intuitive to assign the CDR's "Nav Label" (which I'm guessing would come from the text content of `SummaryURL` element) to the Navigation Label field, not the Name field.

**Comment by bryanpizzillo** [comment]
Question 1. I think it is a Drupal thing...

Question 2. It is on the Todo for the installer to create it. So create it by hand for your tests. 

Question 3. It is just a piece. See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Vocabularies-Site-Sections for more info.

Question 4. It should be name that is the title of a term. Navigation label is the override for when name needs to be less generic than what is is displayed in the UI.

**Comment by bkline** [comment]
I split out half of the work from this ticket into #714.

**Comment by bkline** [comment]
It was the part I split out from this ticket which was supposed to be closed by the PR. This work is still to be done.

**Comment by bkline** [comment]
More discussions from Slack:

**Bob**

> We’ve been talking about having the RESTful APIs do the work of creating the site sections, but it occurs to me that it should probably be in a `post_save` hook, because we’ve also said that on rare occasions a human can create/edit summary documents, and we’d also be leaving the summaries created from YAML files out in the cold. Your thoughts?


**Bryan**

> Hrmm…
> Don’t know. I feel like it is a coin toss. 
> Technically we only have ever edited an existing summary in place
> So to create a new one sounds like a very special case where one should not do that.
> The edits are to fix a major issue with the summary that is currently live on the web site without waiting for the CDR/gatekeeper gears to churn
> So creating a summary through the UI as part of normal operations is VERY frowned upon
> and the only people that will be able to do it are like you, volker, or blair… (I can sit this one out… I wish)

**Bob**
> Since you skipped over the problem with the sample YAML nodes, I assume you missed it, and therefore I’m going let that problem nudge the coin onto the side where we use a hook.

**Bryan**

> You are going to want `hook_ENTITY_TYPE_insert` and `hook_ENTITY_TYPE_update` then if using a hook…
> where `ENTITY_TYPE` is going to be the name of the cancer info summary bundle, which I don’t dare to guess right now…
>

**Comment by bkline** [comment]
`ENTITY_TYPE` is actually `node`, and the hooks need a check to make sure the bundle is `pdq_cancer_information_summary`.
