### ISSUE TITLE
Add Tooltip Text on Pretty URL (Common Field)

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#694]
Please add tooltip text to the [pretty url common field](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#pretty-url).

**Here's the tooltip text:** 
Used as the last segment of the URL. Do not include slash. Leave blank if page is the designated landing page in the site section. Must be lowercase, with no space. Use hyphens to separate words. [See SEO Guidelines PDF for more details.]

**Comment by blairlearn** [comment]
Tooltip text is set on a per-content type.  Added for the Article and Home and Landing types.

Replaced existing text on Blog Post:
> When preceded by the parent section’’s pretty URL path, the full alias must be unique within the site

**Comment by blairlearn** [comment]
Discovered the pretty url helper text is missing from the Mini Landing page.  Fixing that.
Additionally, @lburack requests that the pretty url helper text on Site Sections be updated to:

> Used as the "tail" of the URL for the assigned landing page. When building URL paths for the section, the parent sections' pretty URL path is pre-pended to this.
