### ISSUE TITLE
Mini Landing Page List – No Image Display Option 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#699]
This ticket is to implement a list card block on the mini landing page. This is because not all mini landing page content have images to displays in a thumbnail card. We need this list option so we can display only a title and description.

This mini landing page list should include the following templates @bryanpizzillo:
* List Header | Item Title | Item Description
* Item Title | Item Description (no header)
* Item Title only (no header; no description)

We also need a list with thumbnail image, which has been built as part of #461. Just documenting here for documentation sake.

![mini-landing-list-templates](https://user-images.githubusercontent.com/29731392/52806088-21914500-3056-11e9-8834-48db3a617d83.png)

**Comment by alifr** [comment]
I assume the text would then shift left if there was no image.

**Comment by lburack** [comment]
Hi @alifr. Yes, everything would shift left. Here's what the listing should look like
![screencapture-cancer-gov-about-cancer-coping-2019-02-12-10_21_43](https://user-images.githubusercontent.com/29731392/52646083-1e5c5480-2eb0-11e9-8ec9-d2d86bf880e6.png)

**Comment by amydugan** [comment]
Adding @lburack as an assignee. Lindsay will communicate our recommended approach for "List Card Container" which will contain "List Card" (what we were formerly calling Thumbnail Card)

**Comment by alifr** [comment]
This has been implemented to only render images if they are present in the content item. However, explicit controls to set a display mode have not been implemented.
