### ISSUE TITLE
Cannot Run More than One Docker Stack at a Time

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#72]
Currently with the last change to the docker-compose.yml file, you cannot run more than one container at a time based on the name.  Technically, this was not possible beforehand, but the `-p <project name>` flag with `docker-compose` would use `<project name>` to prepend the containers. So through the command line you could set them.

Partially this was done in order to have the hostname appear on the bash command line of the web container and not say `docker_web_1`. 

So this ticket is to fix the compose file so that we can run more than one stack at a time (with a different -p option). This should also set the hostname in the container TO the full container name. Additionally it should take in account the fact that we expose ports and they would need to either NOT be exposed, or random WHEN THERE IS MORE THAN 1 CONTAINER. (Please make it 80 and mysql when running a single stack)

**Comment by amydugan** [comment]
@bgnih - I am closing out Sprint 2. I see your note that there was a pull request 5 days ago that would close this issue, so can this be closed or do I need to move it to Sprint 3?

**Comment by bgnih** [comment]
Move to sprint 3, still in discussion

**Comment by bryanpizzillo** [comment]
I am going to close this as while it is still a nice to have some day, we launched the platform successfully without it.
