### ISSUE TITLE
Create functionality to prevent users from updating Site Section language

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#736]

**Comment by amydugan** [comment]
@adriancofie - Language, as in the text that is there or language meaning English vs. Spanish? We are trying to determine if this is a must have and thus in scope for May

**Comment by amydugan** [comment]
From @adriancofie: This is a nice to have. It’s more a catch to prevent someone (an IA) from changing the language of a site section. Which would have to be pretty intentional to happen in the first place.

**Comment by VictoriaSunNIH** [comment]
The team is trained on how to properly manage site sections.  Closing this as not an issue, will reopen if it becomes one.
