### ISSUE TITLE
Implement PDQ Cancer Information Summary look and feel on the front end

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#739]
Implement the PDQ Cancer Information Summary look and feel.

Treatment Summary Examples:
* Patient, English: 
** https://www.cancer.gov/types/leukemia/patient/adult-all-treatment-pdq
** https://www.cancer.gov/types/brain/patient/child-glioma-treatment-pdq
* Patient, Spanish: 
** https://www.cancer.gov/espanol/tipos/seno/paciente/tratamiento-seno-pdq
** https://www.cancer.gov/espanol/tipos/cerebro/paciente/tratamiento-glioma-infantil-pdq
* HP, English: 
** https://www.cancer.gov/types/breast/hp/breast-treatment-pdq
** https://www.cancer.gov/types/brain/hp/child-glioma-treatment-pdq
* HP, Spanish: 
** https://www.cancer.gov/espanol/tipos/seno/pro/tratamiento-seno-pdq
** https://www.cancer.gov/espanol/tipos/cerebro/pro/tratamiento-glioma-infantil-pdq

Supportive & Palliative Care Summary Examples:
* Patient, English: https://www.cancer.gov/about-cancer/advanced-cancer/planning/end-of-life-pdq
* Patient, Spanish: https://www.cancer.gov/espanol/cancer/cancer-avanzado/planes/etapa-final-pdq
* HP, English: https://www.cancer.gov/about-cancer/advanced-cancer/planning/end-of-life-hp-pdq
* HP, Spanish: https://www.cancer.gov/espanol/cancer/cancer-avanzado/planes/etapa-final-pro-pdq

Screening Summary Examples:
* Patient, English: https://www.cancer.gov/types/breast/patient/breast-screening-pdq
* Patient, Spanish: https://www.cancer.gov/espanol/tipos/seno/paciente/deteccion-seno-pdq
* HP, English: https://www.cancer.gov/types/breast/hp/breast-screening-pdq
* HP, Spanish: https://www.cancer.gov/espanol/tipos/seno/pro/deteccion-seno-pdq

Prevention Summary Examples:
* Patient, English: https://www.cancer.gov/types/breast/patient/breast-prevention-pdq
* Patient, Spanish: https://www.cancer.gov/espanol/tipos/seno/paciente/prevencion-seno-pdq
* HP, English: https://www.cancer.gov/types/breast/hp/breast-prevention-pdq
* HP, Spanish: https://www.cancer.gov/espanol/tipos/seno/pro/prevencion-seno-pdq

Genetics Summary Examples (only HP, only English): https://www.cancer.gov/types/breast/hp/breast-ovarian-genetics-pdq

Complementary & Alternative Medicine (CAM) or Integrative Medicine Summaries:
* Patient, English: https://www.cancer.gov/about-cancer/treatment/cam/patient/acupuncture-pdq
* Patient, Spanish: https://www.cancer.gov/espanol/cancer/tratamiento/mca/paciente/acupuntura-pdq
* HP, English: https://www.cancer.gov/about-cancer/treatment/cam/hp/acupuncture-pdq
* HP, Spanish: https://www.cancer.gov/espanol/cancer/tratamiento/mca/pro/acupuntura-pdq

**Comment by alifr** [comment]
There are still some styles missing because we have not ported over all the style changes from FEQ. The only really notable style missing, that I've found, is "On This Page" nav links do not hide on mobile breakpoint.
