### ISSUE TITLE
Thumbnail cards do not fallback to field_page_description

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#747]
The Learning to Relax (/about-cancer/coping/feelings/relaxation) page has its page description field (`field_page_description`) field contains the following text:
*Relaxation and imagery exercises to help reduce pain and stress from cancer and its treatment.*

However, when promoted on a landing page, the following is displayed:
<img width="1069" alt="screen shot 2019-02-12 at 11 30 30 am" src="https://user-images.githubusercontent.com/11215649/52651163-b01c8f80-2eb9-11e9-8c19-8202b85470ff.png">

Expectation:
The `field_list_description` is empty for the content type, so the `field_page_description` should be used as the description.

**Comment by lburack** [comment]
Happy to report that this does pass IA Review! Thanks, @bryanpizzillo!
