### ISSUE TITLE
Manually Build Cancer Center Listing Page

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#752]
Build Cancer Center Listing Page https://www.cancer.gov/research/nci-role/cancer-centers/find

https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Center

This ticket is related to Implement Cancer Centers dynamic view (and list page) https://github.com/NCIOCPL/cgov-digital-platform/issues/590. 

@VictoriaSunNIH - Tagging you for additional requirements

**Comment by sarinapadilla** [comment]
@VictoriaSunNIH according to a comment on #590, this ticket is out-of-scope, as the plan is to make this a block of WYSIWYG content for go-live since the content doesn't change often on this page, and then figure out the dynamic view post-golive.

**Comment by amydugan** [comment]
See CGOV-9246

**Comment by VictoriaSunNIH** [comment]
Closing this out - has been captured in JIRA as a content ticket.
