### ISSUE TITLE
Language Toggle Displays English URL Aliases when Spanish Alias Does not Exist

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#756]
There is a condition that when a content item has a URL Alias in English (e.g. `/english-content`), and does not have one in Spanish, the Language Toggle displays a URL of `/espanol/english-content`. Clicking the link does take you to the Spanish content.

* Issue 1. A 404 should appear for this content, because `/espanol/english-content` would not be a valid URL.
* Issue 2. The system should be prevented from generating the link with the alias. In this case, `/espanol/node/123` would be preferable.

**Comment by VictoriaSunNIH** [comment]
Already fixed.
