### ISSUE TITLE
Biography Change Request: Change Promotional Image label to Bio Image

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#794]
On the biography content type, can we change the label on the content type to read "Biography Image" instead of Promotional Image?  (We do not want to change the shared field name, just the name that appears on the bio content type -- while still using the underlying promotional image).

**Comment by sarinapadilla** [comment]
Closed with https://github.com/NCIOCPL/cgov-digital-platform/pull/819
