### ISSUE TITLE
Bio: Create dropdown for Information for Journalists (and update template display)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#796]
2 parts to this story:
1. Refer to how press releases uses this content block, but basically:
    * Create a region on the biography content type (call it "bio_press_info")
    * On install:
      * Create a content block (name of the block should be Press Information for Journalists)
      * Add the block to the bio_press_info region
2.  Add a checkbox to the Biography content type for the [Show Press Information for Journalists](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Biography#press-information-for-journalists)
    * Then in the template for displaying Biography, if Show Press Information for Journalists is selected, then draw the bio_press_info region.  If not, don't draw it.

**Comment by lburack** [comment]
This is working as expected.
Just to note - the checkbox UI for Drupal is easy to gloss over (it doesn't have a heading). Being this is the last item right before the Body WYSIWYG, I think this implementation is fine. Thanks, @sarinapadilla!

**Comment by VictoriaSunNIH** [comment]
Looks good to me as well!
