### ISSUE TITLE
Technical Item/Approach: Creates blocks for hardcoded mainnav elements

### ISSUE THREAD

**Issue by BrendanBeltzNIH** [NCIOCPL/cgov-digital-platform#820]
## Description 

The MainNav template currently has a block of hardcoded markup (the search and mobile nav blocks. This needs to be converted to english and spanish blocks that are placed in the nav region to allow dynamic translations

**Comment by BrendanBeltzNIH** [comment]
This is the overview structure of the main nav area:

```html
<div class="nav-search-bar">
  <div id="nvcgSlMainNav">
    <div class="slot-item">
      <div class="navigation">
        <div class="mobile-menu-bar">{{ MOBILE MENU }}</div>
        <div id="mega-nav">{{ MEGAMENU }}</div>
      </div>
    </div>
    <div class="slot-item">{{ SEARCH BAR }}</div>
  </div>
</div>
```

**Comment by BrendanBeltzNIH** [comment]
My preference is to break this out into three regions that allow us to control the contents with translated blocks.

**Comment by bryanpizzillo** [comment]
The three region approach is closer to what Percussion/CDE do today. The `{{ REGION.MOBILE_NAV }}` will change across the sites within the platform. The mobile menu/hamburder *should* always be in the first position, but all the other options after it can differ. 

Is the idea that the `mobile_nav` region would contain multiple blocks? Such as
1. the mobile nav button (hamburger) block
2. a raw HTML block with the other buttons
    * for nano this would just be the search button
    * for www proper it would be contact, dictionary and search buttons
