### ISSUE TITLE
Preview link doesn't work for Content in Editing (in moderated view)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#834]
When looking at moderated content in the content overview view, the link to view content that is in editing mode is broken (and displays an "unexpected error" page).

**Comment by bgnih** [comment]
@VictoriaSunNIH Can you give me the steps you're taking to get an error?  I haven't been able to duplicate this on my local using article or press release nodes.

**Comment by VictoriaSunNIH** [comment]
On dev:
Move an existing article or press release from published back to editing.

On the overview page, click the tab to switch to moderated view.

Click on the title of the article that is in editing to get the error message.

**Comment by bgnih** [comment]
This is a result of Core Issue:  [Node revision routes don't convert {node} param(https://www.drupal.org/project/drupal/issues/2730631)

A workaround has been added that should continue to work properly after this Issue has been resolved.
