### ISSUE TITLE
WYSIWYG: Ability to control which type to use

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#835]
We need to implement the ability to define which WYSIWYG to use in the field definition.

**Comment by adriancofie** [comment]
Options:
Patch: https://www.drupal.org/project/drupal/issues/784672
Module: https://www.drupal.org/project/allowed_formats

**Comment by adriancofie** [comment]
Add to admin theme.

**Comment by bryanpizzillo** [comment]
Based on the investigation results today I can think of two approaches (that I would be comfortable with):
##Service Based
Service in a utility module handles most of the logic. Each module needs to register its own form alter, but the guts of those hooks are just calling the service.

# Create a new `cgov_util` module
# Create a new service inside of that module, `cgov_util.form_tools`, class CgovFormTools.
    * CgovFormTools will get a method, `allowTextFormats(field_format_map, &$element, $context)`
       * This method will perform the logic of setting the allowed formats.
       * The class should also have a static function for providing the `#after_build` method. 
# Each module that has text formats will implement the following in their .module file:
```
function cgov_core_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Maps field names to an array containing a single format.
  $map = [
    'field_XXX' => ['format_XXX'],
    'field_YYY' => ['format_YYY'],
  ];
  $formHelper = \Drupal::service('cgov_util.form_tools');
  $formHelper->allowTextFormats($map, $element, $context);
}
```
NOTE: cgov_core.tools service would at some point move into this module.

##Hook Based
Less hook_alter implementations, but need to make new methods. Possibly harder than service to debug if you don't know what purpose hook_allowed_text_formats would be used for. (The above approach just reduces duplicate code in form_alter functions.
# Create a new `cgov_util` module
# create a new api hook in the module, `hook_allowed_text_formats(&$map)` (?)
# in the cgov_util.module file implement the cgov_util_field_widget_form_alter() hook, and invoke hook_allowed_text_formats() to get all the various text fields/formats from any enabled modules.

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH or @lburack 
Mappings:
field_body_section_content => full_html
field_html_content = > full_html
field_pdq_section_html => raw_html
field_caption => Simple
field_intro_text => Streamlined
field_citation_content => Streamlined? or full_html? (It needs urls)
field_about_blog => Streamlined

**Comment by VictoriaSunNIH** [comment]
Citation content should be streamlined (not full. We don’t want people doing silly things like putting images in citations).


—
Victoria Sun
NCI OCPL - Office of Communications & Public Liaison
Contractor: Sapient
NCI: 240-276-6994 | Mobile: 301-728-8167


________________________________

**Comment by adriancofie** [comment]
on: http://ncigovcdode47.prod.acquia-sites.com
