### ISSUE TITLE
Blog Post Intro Text is Not Styled 

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#843]
Looks like #608 was closed, but blog post intro text is not styled. 

Here's a live blog post with intro text (the text at the top with the purple line): https://www.cancer.gov/news-events/cancer-currents-blog/2018/new-online-december-2018

Here's a screenshot of that post which I recreated in our Drupal Dev environment: ![blog-post-intro-text-not-styled 2019-02-20.png](https://images.zenhubusercontent.com/5c112f748770e240cb444ff7/0e6a0c40-f3cf-4bc4-912e-1953d83dd305)

**Comment by VictoriaSunNIH** [comment]
Closing - this was completed as part of PDQ.
