### ISSUE TITLE
Biography: Dates don't default to today, and incorrect Date Display format

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/cgov-digital-platform#855]
Update the form display for Biography to have the default date set to today for Posted/Updated/Review dates, as well as update the Date Display Mode field to be checkboxes instead of a dropdown.

**Comment by lburack** [comment]
This is working as expected now on http://ncigovcdode42.prod.acquia-sites.com/. Thanks!

**Comment by VictoriaSunNIH** [comment]
Looks good to me too!
