### ISSUE TITLE
Blog Posts - Remove Site Sections & Auto-Generate URL Path

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#861]
Blog posts are assigned to a blog series. They should inherit the site section from their series. We want to remove the Site Section field from Blog Posts so users can't create a blog post in a different section of the site.

This ticket is to:
- Remove Site Section field from Blog Post content type
- Automagically have a blog post inherit the site section from its blog series. The URL will be `.../[blog-site-section-pretty-url]/[year]/[blog-post-pretty-url]`

*Note: C.gov's blog series' do not have pretty URLs on the actual content type. They each have their own site section. The blog series site section has a pretty URL (like our folder name now).

**Comment by daquinohd** [comment]
http://ncigovcdode69.prod.acquia-sites.com/

**Comment by lburack** [comment]
@daquinohd - the year from the posted date is not being pulled into the URL.

**Comment by lburack** [comment]
@daquinohd  - I created a Spanish blog post from scratch (not as an English translation). Is the URL for Spanish an issue for you or a general translation issue? For whatever reason, _/news-events_ is being pulled into the URL instead of _noticias_
http://ncigovcdode69.prod.acquia-sites.com/espanol/news-events/temas-y-relatos-blog/2019/cooper-allison
