### ISSUE TITLE
Feedburner URL Helper Text on Blog Series

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#862]
The second bullet on the Feedburner helper text on the Blog Series should be removed. It was not part of the [tooltip text on the wiki](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#feedburner-url)

**Remove the following:**
 _Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page._

**Comment by daquinohd** [comment]
This may be a cleaner solution: https://api.drupal.org/api/drupal/core!modules!field!field.api.php/function/hook_field_widget_form_alter/8.2.x
