### ISSUE TITLE
YAML Content Request for Related Resources - Article

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#867]
Content Type: Article
Live Site URL: https://www.cancer.gov/about-cancer/coping/feelings

**Comment by blairlearn** [comment]
This page has already been created.  See: http://ncigovcdstg.prod.acquia-sites.com/about-cancer/coping/feelings

**Comment by popkhadzeg** [comment]
Fine. This URL should work for Article page. Closing
http://ncigovcdstg.prod.acquia-sites.com/about-cancer/coping/feelings
