### ISSUE TITLE
YAML Content Request for Updated Date - Cancer Center

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#876]
Content Type: Cancer Center
Live Site URL: https://www.cancer.gov/research/nci-role/cancer-centers/find/dfharvard

**Comment by blairlearn** [comment]
This content item already exists, though presently it's showing up at [/about-cancer/coping/feelings/relaxation/dfharvard](http://ncigovcdstg.prod.acquia-sites.com/about-cancer/coping/feelings/relaxation/dfharvard) instead of /research/nci-role/cancer-centers/find/dfharvard/

**Comment by popkhadzeg** [comment]
@blairlearn 
This will work. 
I will use this url for Cancer Type.
Thanks
