### ISSUE TITLE
YAML Content Request for Public Use - Article

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#883]
Content Type: Article
Live Site URL: https://www.cancer.gov/about-cancer/understanding/what-is-cancer

**Comment by blairlearn** [comment]
@popkhadzeg - The Public Use banner is already turned on (but not yet displayed) for /about-cancer/coping/feelings. Is it sufficient to reuse that content item instead of creating another?

**Comment by popkhadzeg** [comment]
Content is created:

Article - /about-cancer/coping/feelings/relaxation/stress-fact-sheet
Press Release - /news-events/press-releases/2018/oropharyngeal-hpv-cisplatin
Press Release - /espanol/noticias/comunicados-de-prensa/2018/oropharyngeal-hpv-cisplatin
Blog - about-cancer/coping/feelings/relaxation/hpv-vaccine-presidents-cancer-panel-improving-uptake
