### ISSUE TITLE
YAML Content Request for Recommended Content - Blog

### ISSUE THREAD

**Issue by popkhadzeg** [NCIOCPL/cgov-digital-platform#892]
Content Type:  Blog
Live Site URL: •https://www.cancer.gov/news-events/cancer-currents-blog/2019/translation-inhibitor-immune-checkpoint-protein
•https://www.cancer.gov/news-events/cancer-currents-blog/2018/hpv-vaccine-presidents-cancer-panel-improving-uptake

**Comment by blairlearn** [comment]
Recommended Content field doesn't exist yet,
