### ISSUE TITLE
Technical Item: YAML Content not loading correctly for Biography (when logged in as content editor)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#907]
When logged into dev as a content editor, we looked at a biography content type, but the body field said "you do not have sufficient permissions to view this field"

Please fix it so that we can edit the YAML content after its loaded.

**Comment by BrendanBeltzNIH** [comment]
Why is this a YAML content issue? The yaml content just creates content in the system. When you're in the actual UI and logged in it's just content/access issues, nothing to do with the initial yaml content. Those are like install files. Their job is done.

**Comment by amydugan** [comment]
Note, the YAML was created with Full HTML. It is TBD what mode we will need to use (Basic HTML, Streamlined, Other?).

**Comment by VictoriaSunNIH** [comment]
Once @adriancofie is done implementing the new WYSIWYGs, this should be fixed in all YAML content.

**Comment by VictoriaSunNIH** [comment]
This is verified as no longer being an issue!
