### ISSUE TITLE
Implement a user friendly, performant, Taxonomy Hierarchy overview page

### ISSUE THREAD

**Issue by adriancofie** [NCIOCPL/cgov-digital-platform#920]
## Description 
The current taxonomy term (hierarchy) overview page has a number of issues:

- It has a poor UX which does not render large tree structures cleanly
- It is not performant and processing grows linearly as taxnomy terms are added
- The OOTB Drupal page struggles handling thousands of terms and requires updating the php max_input_vars variable in order to work

This ticket is to either enable a module such as https://www.drupal.org/project/taxonomy_manager, or to create a fully customized page for updating the taxonomy hierarchy.

**Comment by VictoriaSunNIH** [comment]
Covered by #1413. Closing
