### ISSUE TITLE
Investigate Module for "Locking" or "Checking out" content

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#93]
When a user is editing a piece of content, we would like to be able to "lock" the item so another user isn't able to modify it at the same time.  Need to look into a module for this

**Comment by kalidindir** [comment]
Content locking, Content lock timeout and  conflict module should be used together to implement the locking functionality. Conflict module is only required if we need support for translations.

**Does it support entity translations?** Yes
**Does it support media?** Yes it supports all entity types. I have tested for media and node types. 
**Moderation Sidebar:** We will have to implement hook_moderation_sidebar_alter to hide show the links based on the lock state and timeout.

### **Module Approach.**
1)	When user A tries to edit a piece of content, the module checks if a lock already exists. If no lock exists currently, a new database record is inserted into the module’s custom table. A message is displayed on the edit page that the current user has the lock available.
2)	When user B tries to edit the same content, the module displays a message on the edit page that the content is locked by another user and cannot be edited. All input fields and buttons in the edit page are disabled.
3)	It supports different for operations for each entity type. Node has edit and delete. Media has add edit and delete etc.
4)	The lock is for a combination of user id, entity id, entity type, operation, language.

### **Breaking the lock before it is stale:**
1)	The lock has to be broken by the user A by clicking on the “Unlock” button or Saving the content.
2)	A user with the permission “Break content lock” can break the lock of other user.
3)	The lock does not break when user A closes the browser window.

### **Lock Timeout and autolocking.**
1)	A stale timeout value can be set in the config screen(default is 30 minutes).
2)	The lock can be broken by a cron run after the timeout.
3)	Break the lock automatically, when another user edits the content after the timeout.
4)	The stale lock timeout is reset everytime the lock owner reloads the edit page

### **Possible Customizations.** 
1)	Write custom hooks to alter the moderation sidebar links based on lock status and timeouts.
2)	Modifying the drupal lock messages has to be done using language translation. The messages are hardcoded.

**Comment by VictoriaSunNIH** [comment]
Things to investigate further/To Do:
- AJAX items not tested (paragraph, site section) as to whether they are "disabled" when node is locked
- Does not manage node permissions
- Edge case ... can overwrite content (users can still view the content and edit it, even when locked, but can't save. if user 1 has locked the content, saves and unlocks, user 2 can go in and just save their changes and still overwrite the content)
- Test out adding a new translation when a piece of content is locked

**Comment by andyvanavery31** [comment]
If this is required by the Content Modernization project, then they will be responsible for creating a new issue to track and prioritize this work.
