### ISSUE TITLE
Content Buildout: Event View Pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#947]
Referencing the wireframes: https://lm1a12.axshare.com/

Once the views have been created, we need to build out a mini landing page for the event view pages.

**Comment by blairlearn** [comment]
What needs to be done here?

Is this creating a new content types? New YAML content? Creating new functionality? (What does it do?)

**Comment by blairlearn** [comment]
Per @VictoriaSunNIH, this is a pre-release manual task, creating site content:

> that should be a content task once the view blocks are set
> its like the aggregator widget, we need to put together the "view" for past events
> and then put that viewblock on a mini landing page
> and then for the current events
> do the same thing

**Comment by VictoriaSunNIH** [comment]
Captured in JIRA.  Closing this one out.
