### ISSUE TITLE
Ability to override validation error message on Video Content Type?

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#949]
Not a high priority but currently on the Video Content Type, when we provide an incorrect URL for the Youtube URL, the validation error message is: "The given URL does not match any known oEmbed providers."

Is there a way to override this validation error message with something more clear to users, such as "The given URL is not a valid youtube URL."

Thanks!

**Comment by BrendanBeltzNIH** [comment]
This is not a provided feature of the Oembed media source type as a simple customizable value. However, it's quite possibly something that can be done in a hook as the error message is not dynamic and can be easily subjected to some regular expression love.

**Comment by VictoriaSunNIH** [comment]
Closing this - it is not a critical issue, and is not confusing to the user.
