### ISSUE TITLE
Update Biography to use correct Date Display Mode checkbox UI

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#953]
Date Display Mode on the Biography is not correct. It should be the checkbox as used on other content types.

![bio-date-display-mode_2019-03-04_at_11_22_28_AM.png](https://images.zenhubusercontent.com/5c112f748770e240cb444ff7/57ac9c15-269f-4fab-9ead-bd43f7fef609)

**Comment by VictoriaSunNIH** [comment]
Closing - This is a duplicate of 855 (which covers the dropdown/checkbox issue).
