### ISSUE TITLE
Wonky Display of Video Content Type on Front-End

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#968]
The Video page is not displaying as expected:
- only taking up half the video frame on the page
- lots of space between the video and the caption 

I created two different videos, pulling the URL from NCI's YouTube channel. See attached screenshots for what I'm seeing on the front end VS the live pages for these videos on Cgov now:
https://www.cancer.gov/about-cancer/treatment/types/immunotherapy/immunotherapy-video
https://www.cancer.gov/about-nci/leadership/director/presentations/sharpless-asco-2018

![screencapture-ncigovcddev-prod-acquia-sites-video-101-2019-03-05-14_16_28.png](https://images.zenhubusercontent.com/5c112f748770e240cb444ff7/490ea7f6-f35e-40fe-a7e4-c9f1795b9a35)
![screencapture-ncigovcddev-prod-acquia-sites-video-106-2019-03-05-14_16_41.png](https://images.zenhubusercontent.com/5c112f748770e240cb444ff7/afdd14cd-59ff-4ce1-a709-a8c32152c4ec)

**Comment by BrendanBeltzNIH** [comment]
This isn't a bug. The cache on the ODE you're looking at was stale.
