### ISSUE TITLE
Videos - URL/Site Section not working as expected

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#969]
I created a video and selected the site section, but the video is not being placed in that site section. The left side of the video page is just blank. The URL is also not correct — not picking up the site section or appending the pretty URL I entered.

These will soon get blown away, but FWIW now, here are the videos I created:
http://ncigovcddev.prod.acquia-sites.com/video/101
http://ncigovcddev.prod.acquia-sites.com/video/106

**Comment by adriancofie** [comment]
Dev completed / pending build and IA review.
