### ISSUE TITLE
Make list styles work

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#979]
For our lists in Drupal, we want to use the HTML markup for lists, but with the front-end look and feel (for the most part*) of our current thumbnail cards
- Examples for HTML markup:
  - https://www.cancer.gov/about-cancer/managing-care
  - https://www.cancer.gov/about-nci/leadership/director/blog-posts
- Examples for look and feel:
  - https://www.cancer.gov/about-cancer/coping 
  - https://www.cancer.gov/grants-training

*The hover state should only change when a user hovers over the title or the image (and not the description)

**Additional Requirements:**
- When a list has a List Title, that should be an h2
- Each list item title should be an h3 

@lburack and @VictoriaSunNIH to discuss getting rid of lists with dates b/c we only have two of these on the site and one is questionable. Will update this ticket after meeting with Lynn.

**Comment by lburack** [comment]
In checking PR #1138, found a few display issues for lists on mini landing pages. Created bug ticket #1149
