### ISSUE TITLE
Update glossification service in the back end to enable use within WYSIWYG

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#987]
Relates to #917

**Comment by bkline** [comment]
I have added a wiki page to describe a proposed API for the glossifier at https://github.com/NCIOCPL/cgov-digital-platform/wiki/Glossifier-service-API. It doesn't look like the wiki lets us attach files, so to supplement the shorter sample JSON given on the wiki page I have attached a more substantial example as
glossifier-sample.zip (GitHub won't let me attach the .json files directly, but it will let me attach a .zip file containing those files).
