### ISSUE TITLE
Fix Field Order on Press Release

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#992]
Requirements indicate that the "Press Release Type" field should be right after the "Subtitle" field. On the ODE, it's at the bottom of the form. Please update the order of the fields to correct this. See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Press-Release#Form-Display-Order

**Comment by bgnih** [comment]
Fixed in #960 PR
