### ISSUE TITLE
Add URL path to all instances where we use the content browser

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#998]
Adding the path to the site section selector was a big improvement. I'd like to extend this update to all other instances where we use the content browser as I think adding the path would **truly** improve the experience for all our CMS users.

Putting in this change request to include the URL path on: 
- Related Resources 
- Home/landing page cards (feature cards, thumbnail cards/lists)
- Mini landing page feature cards and lists

@bryanpizzillo did I miss any other instances? Let me know if you prefer separate tickets. Thank you!

**Comment by amydugan** [comment]
@lburack - Just checking, is this CR a must have before Phase 1 go live?

**Comment by lburack** [comment]
@amydugan - I think @bryanpizzillo was already working on this for some instances mentioned above. This is probably a really, really nice to have, but it's not a must have to use the system. If it's an easy update though, would be great to get it in :)

It's preferable to have the content browser be consistent across all instances, and I think having the path is a huge improvement to the UX of the CMS, but this shouldn't trump the build out of necessary content types and other must-haves.

**Comment by bryanpizzillo** [comment]
This is just a change to the content browser itself. It would be done as part of #831.

**Comment by amydugan** [comment]
According to @bryanpizzillo 's comment above, this should be closed because https://github.com/NCIOCPL/cgov-digital-platform/issues/831 was fixed/closed.
